/**
 * Creates Irish (ga) index.json translation file (homepage)
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ga';
const today = '2026-04-11';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"bitcoin_builds_a_better_world": "T\u00f3ga\u00edonn Bitcoin domhan n\u00edos fearr.",
	"home_description": "Is airgead n\u00edos fearr \u00e9 Bitcoin at\u00e1 ag t\u00f3g\u00e1il domhain n\u00edos fearr. Tá cearta daonna cosanta ag Bitcoin, shábháil sé daoine ó bhoilsciú ard, thacaigh sé le feirmeoirí áitiúla, laghdaigh sé astaíochtaí ó dhruileáil ola, agus go leor eile.",
	"home_intro": "Is airgead n\u00edos fearr \u00e9 Bitcoin at\u00e1 ag t\u00f3g\u00e1il domhain n\u00edos fearr. Tapáil ar chatagóir thíos chun foghlaim conas a dhéanann Bitcoin é níos fearr, nó níl le déanamh agat ach tosú ag scrollú chun iniúchadh a dhéanamh.",
	"home_btn_money": "AIRGEAD N\u00cdOS FEARR",
	"home_btn_salary": "DO THUARASTAL",
	"home_btn_freedom": "SAOIRSE",
	"home_btn_human_rights": "CEARTA DAONNA",
	"home_btn_equality": "COMHIONANNAS",
	"home_btn_property_rights": "CEARTA MAOINE",
	"home_btn_housing": "TITH\u00cdOCHT",
	"home_btn_business": "GN\u00d3",
	"home_btn_crowdfunding": "CIST\u00cdOCHT SLUAITE",
	"home_btn_energy": "FUINNEAMH",
	"home_btn_environment": "AN COMHSHAOL",
	"home_btn_food": "BIA",
	"home_btn_art": "EALA\u00cdN",
	"home_btn_politics": "POLAIT\u00cdOCHT",
	"home_btn_war": "COGADH",
	"home_btn_coding": "C\u00d3D\u00da",
	"home_btn_networks": "L\u00cdONRA\u00cd",
	"home_btn_payments": "\u00cdOCA\u00cdOCHTA\u00cd",
	"home_btn_self_custody": "F\u00c9INCHOIMIRCE",
	"home_btn_you": "T\u00da",
	"home_section_bitcoin_is": "IS \u00c9 BITCOIN",
	"home_section_bitcoin_and": "BITCOIN &",
	"home_link_type_website": "SU\u00cdOMH GR\u00c9AS\u00c1IN",
	"home_link_type_video": "F\u00cdSE\u00c1N",
	"home_link_type_article": "ALT",
	"home_link_type_podcast": "PODCHRAOLADH",
	"home_link_type_business_kit": "PAC\u00c1ISTE GN\u00d3",
	"home_link_type_data": "SONRA\u00cd",
	"home_link_type_research": "TAIGHDE",
	"home_link_type_story": "SC\u00c9AL",
	"home_link_type_book_excerpt": "SLIOCHT LEABHAIR",
	"home_link_type_street_art": "EALA\u00cdN SR\u00c1IDE",
	"home_link_type_outreach": "FOR-ROCHTAIN",
	"home_link_type_campaign": "FEACHTAS",
	"home_link_type_software": "BOGEARRA\u00cd",
	"home_link_type_hardware": "CRUA-EARRAI",
	"home_link_type_guide": "TREOIR",
	"home_link_type_email": "R\u00cdOMHPHOST",
	"home_link_title_inflation": "N\u00edl Boilsci\u00fa ag Bitcoin",
	"home_link_title_bank_runs": "N\u00edl Rith ar Bhainc ag Bitcoin",
	"home_link_title_gold": "Bitcoin vs \u00d3r",
	"home_link_title_crypto": "Bitcoin vs Cripte\u00e1",
	"home_link_title_cash": "Bitcoin vs Airgead Tirim",
	"home_link_title_bonds": "Bitcoin vs Banna\u00ed",
	"home_link_title_cbdc": "Bitcoin vs ADBLanna",
	"home_link_title_your_salary_1": "Faigh amach c\u00e9 mh\u00e9ad a chaithfidh do thuarastal ard\u00fa chun coinn\u00e1il suas leis an mboilsci\u00fa.",
	"home_link_title_freedom_1": "C\u00e9n f\u00e1th a bhfuil Bitcoin T\u00e1bhachtach don tSaoirse",
	"home_link_title_freedom_2": "Cuireann Bitcoin saoirse ar f\u00e1il \u00f3 chois polaitiúil",
	"home_link_title_human_rights_1": "Conas a Fhorfheidhmíonn Bitcoin Cearta Daonna",
	"home_link_title_human_rights_2": "R\u00e9abhlóid Chiúin Bitcoin san Afraic",
	"home_link_title_human_rights_3": "Tá Bitcoin ag Cosaint Cearta Daonna ar fud an Domhain",
	"home_link_title_equality_1": "Tá Bitcoin ag Tabhairt Dóchais & Deiseanna do Mhuintir na hAfraice Theas",
	"home_link_title_equality_2": "Conas is féidir le Bitcoin a bheith ina Athraitheoir Cluiche do Mheiriceánaigh Dhubha",
	"home_link_title_property_rights_1": "Is í Bitcoin an Fhoirm Foirfe Maoine",
	"home_link_title_property_rights_2": "Bitcoin vs Eastát Réadach",
	"home_link_title_housing_1": "Conas a Dhéanfaidh Bitcoin Tithíocht Inacmhainne Arís",
	"home_link_title_business_3": "Bitcoin vs Stoic",
	"home_link_title_business_1": "Foghlaim cén fáth go bhfuil Bitcoin Go Maith don Ghnó",
	"home_link_title_business_2": "Faigh Gnó Áitiúil chun Glacadh le Bitcoin",
	"home_link_title_crowdfunding_1": "Conas a Chumhachtaigh Bitcoin na hAgóidí Nigéireacha is Mó i nGlúin",
	"home_link_title_crowdfunding_2": "Ardaíonn Agóid Tiománaithe Trucailí Cheanada Airgead i mBitcoin tar éis do GoFundMe Síntiúis a Bhlocáil",
	"home_link_title_crowdfunding_3": "Geyser = Cistiúchán Sluaite le Bitcoin",
	"home_link_title_energy_1": "Conas a Chobhsaíonn Bitcoin Greille Cumhachta Texas",
	"home_link_title_energy_2": "Cén fáth a n-úsáideann Bitcoin fuinneamh?",
	"home_link_title_energy_3": "Ní fadhb é úsáid fuinnimh Bitcoin. Seo an fáth.",
	"home_link_title_energy_4": "Tá mianadóireacht Bitcoin ag cobhsú greillí fuinnimh trí Fhreagairt Éilimh",
	"home_link_title_energy_5": "Tá mianadóirí Bitcoin ag tabhairt cumhacht hidrileictreach chuig pobail tuaithe Afracacha",
	"home_link_title_energy_6": "Conas a Spreagann Bitcoin Fuinneamh In-athnuaite",
	"home_link_title_environment_1": "Conas atá mianadóireacht Bitcoin ag laghdú astaíochtaí meatáin domhanda",
	"home_link_title_environment_2": "Conas a shábháil mianadóireacht Bitcoin Páirc Náisiúnta",
	"home_link_title_environment_3": "Is é Bitcoin an tionscal is glaise ar Domhan!",
	"home_link_title_environment_4": "Tá mianadóireacht Bitcoin ag cosc ar ghás nádúrtha lasraithe an t-atmaisféar a thruailliú",
	"home_link_title_food_1": "Conas a Théann Boilsciú i bhFeidhm ar Phraghsanna Bia",
	"home_link_title_food_2": "Conas atá Airgead Fiat Go hOlc don Bhia, d'Fheirmeacha, agus d'Ithir an Domhain",
	"home_link_title_fine_art": "Bitcoin vs Mín-Ealaín",
	"home_link_title_art_1": "Glac páirt inár dTionscnamh Greamán Bitcoin",
	"home_link_title_art_2": "Seol Cárta Poist Bitcoin chuig duine a bhfuil aithne agat air",
	"home_link_title_art_3": "Priontáil & Cuir Suas Bileoga Bitcoin",
	"home_link_title_politics_1": "Is Paradacsa Polaitiúil é Bitcoin",
	"home_link_title_politics_2": "Is féidir leat Vótáil ar son Airgid Níos Fearr",
	"home_link_title_war_1": "Conas a D'fhéadfadh Bitcoin Deireadh a Chur le Cogadh Gan Deireadh",
	"home_link_title_war_2": "Bitcoin & Seansaighdiúirí: Ailíniú Nádúrtha",
	"home_link_title_war_3": "Conas a Chabhraíonn Bitcoin le Sibhialtaigh Éalú ón gCogadh sa tSúdáin",
	"home_link_title_coding_1": "Rang Teagaisc Idirghníomhach faoi Thaobh Teicniúil Bitcoin",
	"home_link_title_coding_2": "bitcoinSwitch: athfheistigh aon ghléas chun glacadh le Bitcoin",
	"home_link_title_coding_3": "Códáil do bhealach trí rúndiamhair Bitcoin",
	"home_link_title_networks_1": "Radharc beo ar líonra Bitcoin",
	"home_link_title_networks_2": "Bitcoin vs Bainc",
	"home_link_title_payments_1": "Bitcoin vs Visa",
	"home_link_title_payments_2": "Féach ar an Líonra Lightning (Íocaíochtaí Bitcoin Láithreacha)",
	"home_link_title_payments_3": "D'fhéadfadh sparán Bitcoin El Salvador $400M a shábháil do Salvadorians gach bliain ar tháillí seachadta",
	"home_link_title_payments_4": "Faigh do Sheoladh Lightning chun Íocaíochtaí Bitcoin Láithreacha a Fháil",
	"home_link_title_self_custody_1": "Conas do Bitcoin a Stóráil go Sábháilte",
	"home_link_title_self_custody_2": "6 Chúis chun do Bitcoin a Aistarraingt ó Mhalartáin",
	"home_link_title_self_custody_3": "Ór, Bitcoin, agus Féinchoimirce",
	"home_link_title_get_started_1": "Foghlaim buneolas Bitcoin",
	"home_link_title_get_started_2": "Faigh do chéad Sparán Bitcoin",
	"home_link_title_get_started_3": "Conas Bitcoin a Cheannach",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Áireamhán Boilscithe Iolraithe",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! Created index.json.');
