/**
 * Creates Irish (ga) common.json translation file
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ga';
const today = '2026-04-11';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"common_footer_mission_1": "Is \u00e9 misean bitcoin.rocks glacadh le bitcoin a l\u00fair\u00fa tr\u00ed oideachas.",
	"common_footer_mission_2": "Foghlaim conas cur leis an tionscadal foinse oscailte seo.",
	"common_footer_follow_first_half": "Lean sinn ar Nostr tr\u00ed chuardach a dh\u00e9anamh ar",
	"common_footer_follow_second_half": "in aon chliant Nostr.",
	"common_footer_what_is_nostr": "C\u00e9ard \u00e9 Nostr?",
	"common_footer_about": "Maidir Linn",
	"common_footer_email_us": "Seol r\u00edomhphost chugainn:",
	"common_cta_section_get_started": "TOSAIGH",
	"common_cta_section_with_bitcoin": "LE BITCOIN",
	"common_cta_section_title_1": "Foghlaim buneolas Bitcoin",
	"common_cta_section_title_1_alt": "Foghlaim tuilleadh faoi Bitcoin",
	"common_cta_section_title_2": "Faigh do ch\u00e9ad Spar\u00e1n Bitcoin",
	"common_cta_section_title_3": "Conas Bitcoin a Cheannach",
	"common_cta_link_type_email": "R\u00cdOMHPHOST",
	"common_cta_link_type_guide": "TREOIR",
	"common_cta_link_type_website": "SU\u00cdOMH GR\u00c9AS\u00c1IN",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "C\u00c9ARD \u00c9 BITCOIN?",
	"common_what_is_bitcoin_content_1": "Is dh\u00e1 rud \u00e9 Bitcoin: airgead digiteach agus l\u00edonra \u00edoca\u00edochta. Is f\u00e9idir leat Bitcoin (an t-airgead digiteach) a sheoladh go d\u00edreach chuig daoine eile ag \u00fas\u00e1id l\u00edonra Bitcoin (an l\u00edonra \u00edoca\u00edochta).",
	"common_what_is_bitcoin_content_2": "Is bealach radacach nua \u00e9 Bitcoin chun luach a st\u00f3r\u00e1il agus a aistriú. Murab ionann agus l\u00edonra\u00ed airgeadais gn\u00e1thacha, t\u00e1 l\u00edonra Bitcoin in ann oibri\u00fa gan \u00fadar\u00e1is l\u00e1rnacha n\u00f3 riarthóir\u00ed iontaofa. D\u00e9anann s\u00e9 sin Bitcoin mar an ch\u00e9ad airgead oscailte gan teorainneacha riamh.",
	"common_what_is_bitcoin_content_3": "Is airgead digiteach \u00e9 Bitcoin a thugann \u00fain\u00e9ireacht ioml\u00e1n duit ar do shaibhreas. Den ch\u00e9ad uair i stair an chine dhaonna is f\u00e9idir le gach duine s\u00f3cmhainn a bheith acu at\u00e1 f\u00edr-ghann, nach dt\u00e9asta\u00edonn cead chun \u00e9 a \u00fas\u00e1id, agus nach f\u00e9idir \u00e9 a urghabh\u00e1il nuair a st\u00f3r\u00e1iltear i gceart \u00e9.",
	"common_what_is_bitcoin_content_4": "Is f\u00e9idir Bitcoin a sheoladh \u00e1it ar bith ar domhan, go tapa agus go saor. N\u00ed theast\u00e1ionn 3\u00fa p\u00e1irt\u00ed seolad\u00f3ra uaidh, cos\u00fail le banc.",
	"common_what_is_bitcoin_content_5": "Ligeann Bitcoin d'aon duine a saibhreas a st\u00f3r\u00e1il go s\u00e1bh\u00e1ilte agus go sl\u00e1n gan a bheith buartha go ngoidfidh an rialtas \u00e9 n\u00f3 go mboilsceoidh siad a luach tr\u00ed airgead a phriont\u00e1il.",
	"common_what_is_bitcoin_content_6": "Is f\u00e9idir le rialtais i ngach \u00e1it n\u00edos m\u00f3 p\u00e1ip\u00e9ir airgid a phriont\u00e1il, ach n\u00ed f\u00e9idir le haon duine n\u00edos m\u00f3 bitcoin a phriont\u00e1il.",
	"common_what_is_bitcoin_content_7": "Is f\u00e9idir leat f\u00e9inchoimirce a ghlacadh ar do Bitcoin go h\u00e9asca chun smacht ioml\u00e1n a f\u00e1il air, rud a thugann rochtain ioml\u00e1n duit ar chumhacht Bitcoin.",
	"common_what_is_bitcoin_content_8": "M\u00e1s f\u00e9idir leat aip a \u00edosl\u00f3d\u00e1il, is f\u00e9idir leat f\u00e9inchoimirce a dh\u00e9anamh ar Bitcoin agus do shaibhreas a st\u00f3r\u00e1il gan a bheith ag brath ar aon duine eile.",
	"common_what_is_bitcoin_content_9": "Is airgead n\u00edos fearr \u00e9 Bitcoin.",
	"common_bitcoin_volatile": "CHUALA M\u00c9 GO BHFUIL BITCOIN LUAINEACH. AN BHFUIL S\u00c9 SIN S\u00c1BH\u00c1ILTE?",
	"common_bitcoin_volatile_content_1": "Sa ghearrth\u00e9arma, t\u00e1 claonadh ag r\u00e1ta malairte Bitcoin luaineacht. Tugtar luaineacht air seo.",
	"common_bitcoin_volatile_content_2": "Ach 'imíonn' an luaineacht a fheiceann tú ó lá go lá san fhadtéarma.",
	"common_bitcoin_volatile_content_3": "Leanann Bitcoin ag éirí níos lú agus níos lú luaineach le himeacht ama. De réir mar a úsáideann níos mó daoine Bitcoin mar chuntas coigiltis fadtéarmach, is ea is mó a chobhsaíonn a luach.",
	"common_bitcoin_volatile_content_4": "Roghnaíonn go leor daoine luach a stóráil i mBitcoin ar feadh go leor blianta mar bhealach sábháilte chun riosca na luaineachta a íoslaghdú agus a gcumhacht ceannaigh a chosaint le himeacht ama.",
	"common_bitcoin_volatile_content_5": "I dtíortha áirithe, cosúil le Veiniséala, an tSúdáin, an Liobáin, an tSiria, an Airgintín, an Tuirc, an Bhrasaíl, agus go leor eile, boilscíonn luach an airgeadra áitiúil chomh tapa sin go bhfeictear Bitcoin mar an bealach níos cobhsaí chun airgead a shábháil.",
	"common_bitcoin_afford": "NÍ FÉIDIR LIOM BITCOIN IOMLÁN A CHEANNACH",
	"common_bitcoin_afford_content_1": "Tá 100 cent i ndollar. Tá 100,000,000 (100 milliún) sat i mbitcoin.",
	"common_bitcoin_afford_content_2": "Ní gá duit bitcoin iomlán a bheith agat. Níl ag formhór na ndaoine ach sats. Is codáin de bitcoin iad sats. Mar shampla, má tá 1 bitcoin iomlán $100,000 ansin ceannaíonn $1 duit 1,000 sats!",
	"common_bitcoin_hacked": "AR HAICEÁLADH BITCOIN RIAMH?",
	"common_bitcoin_hacked_content_1": "Seans gur chuala tú faoi 'haiceáil Bitcoin' ar líne nó ar na nuachtáin. Léann formhór na ndaoine na hailt seo agus creideann siad gur haiceáladh líonra Bitcoin. Áfach, ní raibh líonra Bitcoin haiceáilte riamh.",
	"common_bitcoin_hacked_content_2": "Céard é líonra Bitcoin? Bhuel, smaoinigh ar líonra Bitcoin mar rianta traenach. Is iad na traenacha atá ag rith ar rianta traenach líonra Bitcoin ná idirbhearta Bitcoin.",
	"common_bitcoin_hacked_content_3": "Nuair a léann tú faoi haiceáil Bitcoin sna nuachtáin, tá tú ag léamh faoi choimhdeachtóir (cosúil le FTX) á haiceáil nó ag dul i bhféimheacht.",
	"common_bitcoin_hacked_content_4": "Is cuideachtaí iad coimhdeachtóirí a choinníonn do bitcoin duit. Áfach, tagann riosca leis sin: do bitcoin a chailleadh nuair a dhéanann an chuideachta mí-bhainistiú air, goidte é, nó téann as gnó.",
	"common_bitcoin_hacked_content_5": "Tharla sé seo le déanaí le FTX.",
	"common_bitcoin_hacked_content_6": "Chaill gach duine a thug a muinín do FTX lena gcuid bitcoin a gcuid bitcoin. Ní raibh aon tionchar ar aon duine a choinnigh a gcuid bitcoin i bhféinchoimirce ag FTX. Sin í cumhacht bitcoin i bhféinchoimirce: fíorsmacht ar d'airgead.",
	"common_bitcoin_hacked_content_7": "In ionad do bitcoin a fhágáil ar mhalartán nó i gclúdach cosúil le ETF, coinnigh é i do sparán féin le haghaidh na mbuntáistí saoirse ar fad.",
	"common_bitcoin_hacked_content_8": "Nuair a dhéanann tú féinchoimirce ar do bitcoin, tá d'airgead cosanta ag líonra Bitcoin. Is é an líonra airgeadais is sláine ar domhan é.",
	"common_bitcoin_hacked_content_9": "I bhféinchoimirce, ní féidir le Sam ó FTX do bitcoin a ghoid uait.",
	"common_bitcoin_hacked_content_10": "Ní féidir leis an rialtas níos mó bitcoin a phriontáil agus boilsciú a chúisiú.",
	"common_bitcoin_hacked_content_11": "Is é bitcoin i bhféinchoimirce d'airgead, a bhuíochas le cumhacht líonra Bitcoin.",
	"common_bitcoin_energy": "CÉN FÁTH A ÚSÁIDEANN BITCOIN FUINNEAMH?",
	"common_bitcoin_energy_content_1": "Úsáideann Bitcoin fuinneamh chun an líonra a dhaingniú agus d'airgead a chosaint.",
	"common_bitcoin_energy_content_2": "Úsáideann Bitcoin méid suntasach fuinnimh, agus is rud iontach é seo ar go leor cúiseanna.",
	"common_bitcoin_energy_list_1": "Níl rith ar bhainc ag Bitcoin.",
	"common_bitcoin_energy_list_2": "Cabhraíonn Bitcoin le greillí fuinnimh a chobhsú le mianadóireacht bitcoin.",
	"common_bitcoin_energy_list_3": "Laghdaíonn Bitcoin astaíochtaí ó dhruileáil ola.",
	"common_bitcoin_energy_list_4": "Úsáideann Bitcoin níos lú fuinnimh ná mar a úsáideann Meiriceánaigh le haghaidh Soilse Nollag gach bliain.",
	"common_bitcoin_energy_list_5": "Is í Bitcoin an tionscal is glaise ar Domhan!",
	"common_cic_intro_1": "Tá a fhios ag go leor daoine faoi Ús Iolraithe, ach is beag duine a bhfuil a fhios acu faoi Bhoilsciú Iolraithe.",
	"common_cic_intro_2": "Lenár nÁireamhán Boilscithe Iolraithe, is féidir leat an méid a chaithfidh do thuarastal ardú a ríomh go héasca chun do chumhacht ceannaigh a choinneáil le himeacht ama.",
	"common_cic_intro_3": "Níl le déanamh agat ach do thuarastal reatha, ráta boilscithe, agus líon na mblianta a cuireadh isteach, agus taispeánfaidh ár n-áireamhán duit céard ba cheart do do thuarastal a bheith chun coinneáil suas leis an mboilsciú.",
	"common_current_salary": "tuarastal reatha",
	"common_inflation_rate": "ráta boilscithe",
	"common_year": "bliain",
	"common_years": "blianta",
	"common_result_starting_message": "Líon an fhoirm thuas agus cliceáil ríomh.",
	"common_error_message": "Earráid: Líon isteach na 3 réimse foirme ar fad le do thoil.",
	"common_result_message_1": "Le ráta boilscithe de",
	"common_result_message_2": "caithfidh do thuarastal",
	"common_result_message_3": "ardú go",
	"common_result_message_in": "i gceann",
	"common_result_message_4": "chun do chumhacht ceannaigh a choinneáil.",
	"common_calculate_button_text": "RÍOMH",
	"common_learn_more": "FOGHLAIM TUILLEADH",
	"common_success": "D'ÉIRIGH LEIS!",
	"common_choose_your_country": "Roghnaigh do thír",
	"common_country_usa": "SAM",
	"common_country_canada": "Ceanada",
	"common_submit": "SEOL",
	"common_language_afrikaans": "AFRACÁINIS",
	"common_language_arabic": "ARAIBIS",
	"common_language_basque": "BASCAIS",
	"common_language_bulgarian": "BULGÁIRIS",
	"common_language_catalan": "CATALÓINIS",
	"common_language_chinese": "SÍNIS",
	"common_language_croatian": "CRÓITIS",
	"common_language_czech": "SEICIS",
	"common_language_danish": "DANMHAIRGIS",
	"common_language_dutch": "OLLAINNIS",
	"common_language_english": "BÉARLA",
	"common_language_estonian": "EASTÓINIS",
	"common_language_filipino": "FILIPÍNIS",
	"common_language_finnish": "FIONLAINNIS",
	"common_language_french": "FRAINCIS",
	"common_language_german": "GEARMÁINIS",
	"common_language_greek": "GRÉIGIS",
	"common_language_hausa": "HÁSAIS",
	"common_language_hebrew": "EABHRAIS",
	"common_language_hindi": "HIONDÚIS",
	"common_language_hungarian": "UNGÁIRIS",
	"common_language_indonesian": "INDINÉISIS",
	"common_language_irish": "GAEILGE",
	"common_language_italian": "IODÁILIS",
	"common_language_japanese": "SEAPÁINIS",
	"common_language_korean": "CÓIRÉIS",
	"common_language_malay": "MALAEIS",
	"common_language_norwegian": "IORUAIS",
	"common_language_persian": "PEIRSIS",
	"common_language_polish": "POLAINNIS",
	"common_language_portuguese": "PORTAINGÉILIS",
	"common_language_russian": "RÚISIS",
	"common_language_sinhala": "SIOLÓINIS",
	"common_language_slovak": "SLÓVAICIS",
	"common_language_slovenian": "SLÓIVÉINIS",
	"common_language_spanish": "SPÁINNIS",
	"common_language_swahili": "SVAHAÍLIS",
	"common_language_swedish": "SUALAINNIS",
	"common_language_thai": "TÉALAINNIS",
	"common_language_turkish": "TUIRCIS",
	"common_language_urdu": "URDÚIS",
	"common_language_vietnamese": "VÍTNEAIMIS",
	"common_language_yoruba": "IORÚIBIS",
	"common_stickers_bulk_mess": "Nach mian leat déileáil leis na comhaid tú féin?",
	"common_stickers_bulk_want": "Ar mhaith leat níos mó ná cúpla greamán?",
	"common_stickers_bulk_store": "Ordaigh greamáin i mbulc ón bpriontóir céanna a úsáidimid.",
	"common_stickers_bulk_cheaper": "Is mó greamán a cheannaíonn tú, is saoire iad in aghaidh an ghreamáin.",
	"common_stickers_print_instructions_1": "Is féidir leat páirt a ghlacadh trí do chuid greamán féin a phriontáil, is cuma cá bhfuil tú! Cliceáil ar do theanga thíos chun na comhaid ghreamán & treoracha a íoslódáil.",
	"common_stickers_print_instructions_2": "Tabhair faoi deara: níl gach greamán ar fáil i ngach teanga.",
	"common_stickers_request_language_1": "Nach bhfeiceann tú do theanga?",
	"common_stickers_request_language_2": "Líon an fhoirm thíos chun comhaid ghreamán i do theanga áitiúil a iarraidh.",
	"common_stickers_dimensions": "Toisí:",
	"common_stickers_type": "Cineál:",
	"common_stickers_material": "Ábhar:",
	"common_stickers_where_to_print": "Cá háit le priontáil:",
	"common_stickers_type_die_cut": "greamán gearrtha",
	"common_stickers_material_vinyl": "greamáin vinile d'úsáid lasmuigh",
	"common_stickers_printer": "Úsáidimid StickerMule.com ach is féidir leat aon chuideachta greamán a úsáid.",
	"common_stickers_dimensions_danger": "11.4544 cm x 8.382 cm (4.51 in x 3.3 in)",
	"common_stickers_dimensions_warning": "10.414 cm x 9.2202 cm (4.1 in x 3.63 in)",
	"common_stickers_dimensions_caution": "12.0142 cm x 7.9502 cm (4.73 in x 3.13 in)",
	"common_stickers_dimensions_fix": "11.3792 cm x 6.8072 cm (4.48 in x 2.68 in)",
	"common_stickers_dimensions_study": "14.605 cm x 5.1308 cm (5.75 in x 2.02 in)",
	"common_stickers_dimensions_bdhi": "21.59 cm x 4.6482 cm (8.5 in x 1.83 in)",
	"common_stickers_dimensions_cure_v2": "6.35 cm x 12.7 cm (2.5 in x 5 in)",
	"common_stickers_dimensions_got_inflation": "7.9248 cm x 14.605 cm (3.12 in x 5.75 in)",
	"common_stickers_dimensions_what_if": "21.7932 cm x 7.62 cm (8.58 in x 3 in)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20.995 cm x 6.35 cm (8.25 in x 2.5 in)",
	"common_nostr_join": "CLÁRAIGH AR NOSTR ANOIS",
	"common_nostr_protocol_header": "Prótacal, ní ardán",
	"common_nostr_protocol_c1": "Is prótacal nua é Nostr a ligeann duit cumarsáid a dhéanamh ar líne gan eagla roimh chinsireacht, dí-ardánú, nó dí-threisiú",
	"common_nostr_protocol_c2": "Tá ardáin cosúil le Twitter agus Facebook faoi smacht cuideachta amháin, ach ní rialaíonn aon duine prótacal Nostr.",
	"common_nostr_freedom_header": "Saoirse bogadh",
	"common_nostr_freedom_c1": "Tá Nostr cosúil le ríomhphost. Ní rialaíonn aon duine an prótacal ríomhphoist, agus is féidir le haon duine cliant (cosúil le Gmail, Hotmail, srl.) a thógáil air.",
	"common_nostr_freedom_c2": "Ní rialaíonn aon duine prótacal Nostr, agus is féidir le haon duine cliant (cosúil le Damus, Amethyst, srl.) a thógáil air.",
	"common_nostr_freedom_c3": "Mura dtaitníonn leat conas a oibríonn cliant áirithe, is féidir leat do chuntas Nostr a bhogadh go réidh go cliant eile gan do lucht leanúna ná d'ábhar a chailleadh.",
	"common_nostr_bitcoin_header": "Tá Bitcoin ionsuite ann",
	"common_nostr_bitcoin_c1": "Tá Bitcoin ionsuite go dúchasach i bprótacal Nostr. Má fheiceann tú ábhar a thaitníonn leat, is féidir leat bitcoin a zap chuig duine mar bhuíochas!",
	"common_nostr_bitcoin_c2": "Ar ardáin láraithe cosúil le Twitter agus Facebook, tuilleann an chuideachta láraithe airgead ó d'ábhar. Ach ar phrótacail oscailte cosúil le Nostr, tuilleann tú airgead ó d'ábhar.",
	"common_nostr_download_client": "ÍOSLÓDÁIL CLIANT SAOR IN AISCE CHUN CLÁRU AR NOSTR",
	"common_nostr_iphone_clients": "Cliaint iPhone",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "Aip iPhone",
	"common_nostr_first_client": "Cliant molta le tosú",
	"common_nostr_wallet_built_in": "Sparán zap Bitcoin ionsuite",
	"common_nostr_download_now": "ÍOSLÓDÁIL ANOIS",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "Comhéadan aitheanta",
	"common_nostr_separate_wallet": "Teastaíonn sparán bitcoin ar leith",
	"common_nostr_android_clients": "Cliaint Android",
	"common_nostr_android_app": "Aip Android",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "Go leor gnéithe",
	"common_nostr_browser_clients": "Cliaint Brabhsálaí",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "Cliant Gréasáin",
	"common_nostr_simple": "An-simplí",
	"common_nostr_test": "Bealach éasca chun Nostr a thriail ag úsáid cuntas tástála",
	"common_nostr_view_client": "FÉACH AR CHLIANT",
	"common_kit_printer": "Molaimid VistaPrint.com chun do bhileoga Pacáiste Gnó Bitcoin féin a phriontáil. Ach is féidir leat aon chuideachta phriontála a úsáid chomh fada agus is féidir leo priontáil dhá thaobhach a dhéanamh.",
	"common_kit_link_to_print": "Nasc le priontáil:",
	"common_kit_fold": "Fill:",
	"common_kit_fold_trifold": "Trí-fhill",
	"common_kit_unfolded_size": "Méid neamhfhillte:",
	"common_kit_unfolded_size_bbk": "Méid litreach (8.5 in x 11 in)",
	"common_kit_paper_thickness": "Tiús páipéir:",
	"common_kit_paper_thickness_standard": "Caighdeánach",
	"common_kit_paper_stock": "Stoc páipéir:",
	"common_kit_paper_stock_glossy": "Snasta",
	"common_kit_exterior_print_file": "Comhad priontála seachtrach:",
	"common_kit_interior_print_file": "Comhad priontála inmheánach:",
	"common_kit_cta_header": "Faigh gnó áitiúil chun glacadh le Bitcoin",
	"common_biz_learn": "Foghlaim cén fáth go bhfuil Bitcoin go maith don ghnó",
	"common_biz_wallets": "Faigh sparán Bitcoin chun glacadh le híocaíochtaí Bitcoin",
	"common_biz_maps": "Liostáil ar léarscáileanna ceannaithe Bitcoin",
	"common_biz_stickers": "Greamáin 'Glactar le Bitcoin Anseo' saor in aisce",
	"common_biz_rewards": "Luaíochtaí Bitcoin",
	"common_biz_accounting": "Treoir Chuntasaíochta Bitcoin",
	"common_biz_faq": "Ceisteanna Coitianta",
	"common_biz_kit": "Priontáil do Phacáiste Gnó Bitcoin féin",
	"common_biz_accept_bitcoin_payments": "GLAC LE HÍOCAÍOCHTAÍ BITCOIN",
	"common_biz_ready": "AN BHFUIL TÚ RÉIDH CHUN GLACADH LE BITCOIN AG DO GHNÓ?",
	"common_biz_more": "TUILLEADH ACMHAINNÍ GNÓ",
	"common_self_custody": "FÉINCHOIMIRCE",
	"common_not_your_keys": "NÍ HÉ D'EOCHRACHA",
	"common_cold_wallet": "SPARÁN FUAR",
	"common_hot_wallet": "SPARÁN TE",
	"common_sticker_files_mission_1": "Is é ár misean cabhrú leat níos mó daoine a oráistephiollú trí ghreamáin Bitcoin a chur in áiteanna poiblí. Tá cóid QR ar ár ngreamáin ar fad a nascann le leathanaigh oideachais faoi",
	"common_sticker_files_mission_2": "Bitcoin",
	"common_sticker_files_mission_3": "boilsciú",
	"common_sticker_files_mission_4": "Má chónaíonn tú i SAM nó i gCeanada, is féidir leat",
	"common_sticker_files_mission_5": "pacáiste greamán Béarla saor in aisce a iarraidh",
	"common_published_by": "Foilsithe ag",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "Oideachas Bitcoin ó 2022",
	"common_publisher_open_source": "Tionscadal foinse oscailte",
	"common_reviewed_accuracy": "\u2713 Athbhreithnithe le haghaidh cruinnis: 2026",
	"common_footer_tagline": "Glacadh le bitcoin á luathú trí oideachas.",
	"common_footer_contribute": "Cuir Leis",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "Foinsí"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! Created common.json.');
