/**
 * Creates Irish (ga) translation files for remaining content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ga';
const today = '2026-04-11';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "N\u00edl Rith ar Bhainc ag Bitcoin",
	"bank_runs_header": "N\u00cdL RITH AR BHAINC AG BITCOIN",
	"bank_runs_header_2": "ACH D'FH\u00c9ADFADH GO MBEADH AG DO BHANC",
	"bank_runs_what": "C\u00c9ARD \u00c9 RITH AR BHANC?",
	"bank_runs_what_content_1": "Tarla\u00edonn rith ar bhanc nuair a dh\u00e9anann an iomarca daoine iarracht a gcuid airgid a aistarraingt \u00f3n mbanc ag an am c\u00e9anna.",
	"bank_runs_what_content_2": "Mura bhfuil go leor airgid ar f\u00e1il ag bainc chun aistarraingt\u00ed a mheait\u00e1il, is f\u00e9idir leo titim go hioml\u00e1n nuair a tharla\u00edonn rith ar bhanc.",
	"bank_runs_how": "CONAS A THARLA\u00cdONN RITH AR BHAINC?",
	"bank_runs_how_content_1": "Is c\u00f3ras 'c\u00falchiste codach' \u00e9 \u00e1r gc\u00f3ras bainc\u00e9ireachta rud a chialla\u00edonn nach gcoinn\u00edonn na bainc d'airgead i dt\u00e1isce agus fanacht go gcaitheann t\u00fa \u00e9 n\u00f3 go n-aistarraing\u00edonn t\u00fa \u00e9.",
	"bank_runs_how_content_2": "Ina ionad sin, glacann do bhanc d'airgead agus tugann ar iasacht \u00e9 n\u00f3 infheist\u00edonn \u00e9. Is f\u00e9idir le seo d'airgead a ghlasáil ar feadh tréimhsí fada ama, cé go ngeallann an banc duit an cumas d'airgead a aistarraingt am ar bith.",
	"bank_runs_how_content_3": "Mar sin céard a tharlaíonn má dhéanann tú iarracht d'airgead a aistarraingt tar éis don bhanc é a thabhairt ar iasacht nó a infheistiú cheana?",
	"bank_runs_how_content_4": "Ní fadhb é má tá tú mar an t-aon duine ag iarraidh aistarraingt. Tógfaidh an banc airgead duine eile agus tabharfaidh duit é. Ach céard a tharlaíonn nuair a dhéanann an iomarca daoine iarracht aistarraingt ag an am céanna?",
	"bank_runs_how_content_5": "Fuair go leor daoine sa SAM amach nuair a bhí rith ar Silicon Valley Bank i Márta 2023.",
	"bank_runs_how_content_6": "Bhí an banc tar éis airgead a gcustaiméirí a infheistiú i mbannaí rialtais a bhí glasáilte ar feadh suas le 30 bliain. Níos measa fós, bhí luach na mbannaí sin tar éis titim go mór le déanaí, mar sin ní fhéadfadh Silicon Valley Bank na bannaí a dhíol chun airgead a dtaisceolairí a fháil ar ais. Bhí siad dócmhainneach. Ní raibh go leor airgid acu chun aistarraingtí a dtaisceolairí a mheaitseáil.",
	"bank_runs_how_content_7": "De réir mar a fuair níos mó daoine amach, ní dheachaigh an fhadhb ach in olcas. Tháinig níos mó iarrataí aistarraingthe isteach, ach níor próiseáladh go leor acu. Thuig na mílte gnólacht nach mbeidís in ann a gcuid fostaithe a íoc mar gheall ar theip an bhainc.",
	"bank_runs_how_content_8": "Chéim an FDIC isteach agus d'aontaigh siad taisceolairí a dhéanamh iomlán. Fadhb réitithe? Ní go díreach...",
	"bank_runs_fdic": "AN GCOSNAÍONN ÁRACHAS FDIC MO CHUID AIRGID?",
	"bank_runs_fdic_content_1": "Tá árachas FDIC deartha chun taisceolairí bainc a chosaint sa chás go dteipeann ar bhanc. Tá taiscí árachaithe suas le $250,000 in aghaidh an taisceolaí. Sin go hiontach, nach ea?",
	"bank_runs_fdic_content_2": "Ní go díreach. Má theipeann ar bhanc, cá bhfaigheann an FDIC an t-airgead? Tá ciste árachais acu le 125 billiún dollar ann.",
	"bank_runs_fdic_content_3": "Is cosúil gur go leor airgid é sin go dtí go gcuirtear i gcomparáid é leis an méid taiscí a árachaíonn siad: beagnach 10 trilliún nó 10,000 billiún dollar.",
	"bank_runs_fdic_content_4": "Taispeánann an FDIC fiú ar a suíomh gréasáin nach bhfuil go leor airgid ina gciste árachais ach chun beagán níos mó ná 1% de thaiscí a chlúdach.",
	"bank_runs_fdic_content_5": "Sa chás go dteipeadh ar bhanc a sháródh an ciste árachais FDIC, is dócha (ach ní cinnte) go bpriontálfadh rialtas SAM airgead chun taisceolairí a dhéanamh iomlán.",
	"bank_runs_fdic_content_6": "Ach cúisíonn priontáil airgid boilsciú, mar sin ní réiteach iontach é.",
	"bank_runs_safe": "AN BHFUIL BAINC ANN NACH N-ÚSÁIDEANN CÚLCHISTE CODACH?",
	"bank_runs_safe_content_1": "Rinne roinnt bainc iarracht a bheith ina 'mbainc shábháilte' nach dtugann airgead taisceolairí ar iasacht ná nach n-infheistíonn é.",
	"bank_runs_safe_content_2": "Cé nach mbeadh aon riosca rith ar bhainc ag na bainc shábháilte seo, diúltaíodh dá gcuid iarratas ag an gCúlchiste Feidearálach. Ciallaíonn sé seo nach féidir leo oibriú go dlíthiúil mar bhainc.",
	"bank_runs_safe_content_3": "Toisc gur cuireadh cosc orthu oibriú, níl aon bhanc ann inniu nach n-úsáideann cúlchiste codach.",
	"bank_runs_safe_content_4": "Ar an dea-uair, tá bealach ann chun éirí as an gcóras cúlchiste codach trí bheith mar do bhanc féin. Ní hé go bhfuilimid ag caint faoi airgead tirim a sháthú faoi do mhairteas.",
	"bank_runs_safe_content_5": "Tá coigilt in airgead tirim fós leochaileach do bhoilsciú.",
	"bank_runs_safe_content_6": "Táimid ag caint faoi Bitcoin: córas airgeadais nua a ligeann duit a bheith mar do bhanc féin.",
	"bank_runs_protect": "AN FÉIDIR LE BITCOIN MÉ A CHOSAINT Ó RITH AR BHAINC?",
	"bank_runs_protect_content_1": "Is féidir, is córas airgeadais lánchúlchiste é Bitcoin.",
	"bank_runs_protect_content_2": "Tá rith ar bhainc dodhéanta i mBitcoin chomh fada agus a aistarraingíonn tú do Bitcoin chuig do sparán féin. Ná fág do bitcoin ar mhalartán nó i gclúdach cosúil le ETF Bitcoin.",
	"bank_runs_protect_content_3": "Féach ar ár dTreoir Sparán Bitcoin simplí chun foghlaim conas aistarraingt chuig do sparán féin.",
	"bank_runs_protect_content_4": "Le Bitcoin, is féidir leat a bheith i smacht ar d'airgead faoi dheireadh."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Treoir Sparán Bitcoin",
	"wallets_description": "Tá go leor sparán Bitcoin éagsúla ann a dhifríonn ar bhealaí tábhachtacha. Is féidir leat a chinneadh an bhfuil sparán ceart duit trí na ceisteanna simplí seo a chur.",
	"wallets_header": "CONAS DO BITCOIN A STÓRÁIL GO SÁBHÁILTE",
	"wallets_s1_c1": "Tá sparáin Bitcoin idir-inoibritheach, mar sin is féidir leat Bitcoin a sheoladh chuig aon duine is cuma cén sparán a úsáideann siad.",
	"wallets_s1_c2": "Tá go leor sparán Bitcoin éagsúla ann a dhifríonn ar bhealaí tábhachtacha. Is féidir leat a chinneadh an bhfuil sparán ceart duit trí na ceisteanna simplí seo a chur:",
	"wallets_question_1": "AN SPARÁN FÉINCHOIMIRCE É?",
	"wallets_s2_c1": "Ceann de nuálaíochtaí Bitcoin ná an cumas é a stóráil gan a bheith ag brath ar choimhdeachtóir, cosúil le banc.",
	"wallets_s2_c2": "Má tá bitcoin á choinneáil agat ar mhalartán nó in ETF, cailleann tú buntáistí saoirse bitcoin.",
	"wallets_s2_c3": "Osclaíonn sparáin féinchoimirce cumhacht iomlán Bitcoin: airgead saoirse.",
	"wallets_s2_c4": "Le sparán féinchoimirce, is tú an t-aon duine a bhfuil an cumas aige d'airgead a chaitheamh nó a aistriú. Ní féidir le haon duine tú a stopadh ó d'airgead a sheoladh nó a fháil nuair a úsáideann tú sparán féinchoimirce.",
	"wallets_s2_c5": "Tugtar sparáin neamhchoimhdeachta freisin ar sparáin féinchoimirce.",
	"wallets_s3_c1": "Is sparáin iad sparáin choimhdeachta nach bhfuil tú i smacht ar d'airgead iontu.",
	"wallets_s3_c2": "Tá na sparáin seo níos cosúla leis an gcóras baincéireachta inar gá duit muinín a bheith agat as tríú páirtí chun rochtain ar d'airgead a thabhairt duit. Má tá do Bitcoin ar mhalartán, tá tú ag úsáid sparán coimhdeachta.",
	"wallets_s3_c3": "Má cheannaigh tú ETF Bitcoin, tá tú ag úsáid sparán coimhdeachta nach ligeann duit aistarraingt chuig féinchoimirce.",
	"wallets_s3_c4": "D'fhéadfadh sparáin choimhdeachta a bheith áisiúil, ach tá an cumas teicniúil ag an gcoimhdeachtóir cistí úsáideoirí ar fad a ghoid am ar bith.",
	"wallets_s3_c5": "Ní hé d'eochracha, ní hé do bhoinn!",
	"wallets_question_2": "AN TE NÓ FUAR É?",
	"wallets_s4_c1": "Stórálann sparáin fhuara eochracha do Bitcoin ar bhealach nach nochtann iad don idirlíon riamh.",
	"wallets_s4_c2": "Cuireann sé seo teorainn shuntasach ar na veicteoirí ionsaithe a d'fhéadfadh gadaí a úsáid chun do Bitcoin a ghoid, agus is fearr é a úsáid le haghaidh suimeanna móra Bitcoin nach gá duit a aistriú go minic.",
	"wallets_s4_c3": "Is féidir leat smaoineamh ar sparán fuar mar chuntas coigiltis fadtéarmach, ar a dtugtar stóráil fhuar freisin.",
	"wallets_s5_c1": "Stórálann sparáin the eochracha do Bitcoin ar ghléas atá nasctha leis an idirlíon, cosúil le d'fhón.",
	"wallets_s5_c2": "Meastar go ginearálta go bhfuil sparáin the sábháilte, ach d'fhéadfadh níos mó leochaileachtaí slándála a bheith acu ná sparáin fhuara.",
	"wallets_s5_c3": "Is féidir leat smaoineamh ar sparán te díreach mar a dhéanfá le sparán fisiciúil. Ní stórálfá do choigilteas ar fad i do sparán, ach stórálfá roinnt airgid chaiteachais.",
	"wallets_s5_c4": "Déanann sparáin the i bhfad níos éasca do Bitcoin a chaitheamh gan do choigilteas ar fad a tharraingt amach as stóráil fhuar.",
	"wallets_question_3": "CONAS A DHÉANFAIDH MÉ CÚLTACA DE MO FHRÁSA AISGHABHÁLA?",
	"wallets_s6_c1": "Nuair a bhunóidh tú do sparán Bitcoin, ginfidh do ghléas frása aisghabhála. Tá 12 nó 24 focal san fhrása aisghabhála seo (ar a dtugtar frása síl freisin).",
	"wallets_s6_c2": "Má chailleann tú rochtain ar do sparán nó má stopann do ghléas ag obair, is féidir leat an frása aisghabhála seo a ionchur i sparán nua chun rochtain ar do Bitcoin a fháil ar ais.",
	"wallets_s6_c3": "Áiríonn an chuid is mó de sparáin bileog pháipéir chun d'fhrása aisghabhála a scríobh síos, ach is fearr le go leor daoine cúltaca a dhéanamh den fhrása seo ar chruach ina ionad. Déanann sé seo i bhfad níos lú dóchúil d'fhrása aisghabhála a chailleadh i gcás tubaiste nádúrtha cosúil le dóiteán nó tuile.",
	"wallets_s6_c4": "Tá 70 pacáiste cúltaca cruach tástáilte ag Jameson Lopp chun cabhrú leat an ceann ceart duit a roghnú.",
	"wallets_s6_c5": "Féach ar threoir chúltaca miotail Bitcoin Jameson anseo.",
	"wallets_s6_c6": "Nó lean ort ag scrollú chun roghanna sparán Bitcoin a fhiosrú.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "Ag lorg ár dTreoir Sparán Lightning?",
	"wallets_starter_wallet": "Sparán iontach le tosú",
	"wallets_mobile_app": "Aip mhóibíleach",
	"wallets_2fa_support": "Tacaíocht 2FA",
	"wallets_air_gap_mode": "Mód aer-bhearna",
	"wallets_air_gap_camera": "Mód aer-bhearna + ceamara",
	"wallets_bitcoin_only": "Bitcoin amháin",
	"wallets_security_features": "Go leor gnéithe slándála",
	"wallets_free": "100% saor in aisce",
	"wallets_coldcard_mk5_costs": "Cosnaíonn $189",
	"wallets_coldcard_q_costs": "Cosnaíonn $289",
	"wallets_blockstream_jade_costs": "Cosnaíonn $79",
	"wallets_foundation_passport_costs": "Cosnaíonn $199",
	"wallets_seedsigner_costs": "Cosnaíonn codanna $50",
	"wallets_very_affordable": "An-inacmhainne",
	"wallets_pair_with_phone": "Péireáil le d'fhón",
	"wallets_battery": "Ceallra in-athluchtaithe",
	"wallets_build_your_own": "Tóg do cheann féin",
	"wallets_qwerty_keyboard": "Méarchlár QWERTY iomlán",
	"wallets_qr_scanner": "Scanóir cód QR"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "Conas Bitcoin a Cheannach - Treoir Céim ar Chéim",
	"buy_header": "CONAS BITCOIN A CHEANNACH",
	"buy_intro_c1": "D'fhéadfadh sé a bheith scanrúil Bitcoin a cheannach den chéad uair, ach tá sé simplí go leor nuair a bhriseann tú síos i gcéimeanna é.",
	"buy_intro_c2": "Treorófar tú sa treoir seo tríd an bpróiseas Bitcoin a cheannach go sábháilte agus é a stóráil i do sparán féin.",
	"buy_step_1_header": "CÉIM 1: ROGHNAIGH DO THÍR",
	"buy_step_1_description": "Tá roghanna éagsúla ceannaithe Bitcoin ar fáil i dtíortha éagsúla. Roghnaigh do thír chun na roghanna is fearr duit a fheiceáil.",
	"buy_search_countries": "Cuardaigh do thír",
	"buy_country_united_states": "Stáit Aontaithe",
	"buy_country_australia": "an Astráil",
	"buy_country_austria": "an Ostair",
	"buy_country_belgium": "an Bheilg",
	"buy_country_brazil": "an Bhrasaíl",
	"buy_country_canada": "Ceanada",
	"buy_country_france": "an Fhrainc",
	"buy_country_germany": "an Ghearmáin",
	"buy_country_ireland": "Éire",
	"buy_country_italy": "an Iodáil",
	"buy_country_netherlands": "an Ísiltír",
	"buy_country_new_zealand": "an Nua-Shéalainn",
	"buy_country_spain": "an Spáinn",
	"buy_country_united_kingdom": "an Ríocht Aontaithe",
	"buy_country_argentina": "an Airgintín",
	"buy_country_chile": "an tSile",
	"buy_country_colombia": "an Cholóim",
	"buy_country_costa_rica": "Cósta Ríce",
	"buy_country_czech_republic": "Poblacht na Seice",
	"buy_country_denmark": "an Danmhairg",
	"buy_country_el_salvador": "an tSalvadóir",
	"buy_country_estonia": "an Eastóin",
	"buy_country_finland": "an Fhionlainn",
	"buy_country_greece": "an Ghréig",
	"buy_country_guatemala": "Guatamala",
	"buy_country_hong_kong": "Hong Cong",
	"buy_country_hungary": "an Ungáir",
	"buy_country_iceland": "an Íoslainn",
	"buy_country_india": "an India",
	"buy_country_israel": "Iosrael",
	"buy_country_japan": "an tSeapáin",
	"buy_country_latvia": "an Laitvia",
	"buy_country_lithuania": "an Liotuáin",
	"buy_country_luxembourg": "Lucsamburg",
	"buy_country_malta": "Málta",
	"buy_country_mexico": "Meicsiceo",
	"buy_country_norway": "an Iorua",
	"buy_country_panama": "Panama",
	"buy_country_poland": "an Pholainn",
	"buy_country_portugal": "an Phortaingéil",
	"buy_country_romania": "an Rómáin",
	"buy_country_singapore": "Singeapór",
	"buy_country_slovakia": "an tSlóvaic",
	"buy_country_slovenia": "an tSlóivéin",
	"buy_country_south_africa": "an Afraic Theas",
	"buy_country_south_korea": "an Chóiré Theas",
	"buy_country_sweden": "an tSualainn",
	"buy_country_switzerland": "an Eilvéis",
	"buy_country_thailand": "an Téalainn",
	"buy_country_turkey": "an Tuirc",
	"buy_country_ukraine": "an Úcráin",
	"buy_country_uruguay": "Uragua",
	"buy_step_2_header": "CÉIM 2: ROGHNAIGH DO MHODH ÍOCAÍOCHTA",
	"buy_step_2_description": "Tá dhá phríomhbhealach chun Bitcoin a cheannach: le haistriú bainc nó le hairgead tirim. Tá buntáistí éagsúla ag gach ceann.",
	"buy_method_bank_transfer": "AISTRIÚ BAINC",
	"buy_method_bank_fast": "Tapa & Éasca",
	"buy_method_bank_less_private": "Níos Lú Príobháideach",
	"buy_method_bank_description": "Is é aistriú bainc an bealach is coitianta chun Bitcoin a cheannach. Tá sé tapa, áisiúil, agus de ghnáth tá táillí níos ísle aige.",
	"buy_method_choose_bank": "Roghnaigh Aistriú Bainc",
	"buy_method_cash": "AIRGEAD TIRIM",
	"buy_method_cash_private": "Níos Príobháidí",
	"buy_method_cash_limited": "Roghanna Teoranta",
	"buy_method_cash_description": "Cuireann ceannacháin airgid tirim níos mó príobháideachta ar fáil ach tá níos lú roghanna acu agus d'fhéadfadh go mbeadh ort bualadh le duine go pearsanta nó ATM Bitcoin a úsáid.",
	"buy_method_choose_cash": "Roghnaigh Airgead Tirim",
	"buy_step_3_header": "CÉIM 3: ROGHANNA CEANNAIGH",
	"buy_step_3_description": "Seo iad na roghanna ceannaigh Bitcoin is fearr do do thír agus do mhodh íocaíochta:",
	"buy_platform_recommended": "MOLTA",
	"buy_platform_strike_description": "Is é Strike an bealach is tapúla agus is éasca chun Bitcoin a cheannach le táillí ísle agus tacaíocht láithreach Líonra Lightning.",
	"buy_platform_swan_description": "Déanann Swan Bitcoin speisialtóireacht i seirbhísí Bitcoin-amháin le meánú costais dollair agus acmhainní oideachais.",
	"buy_platform_river_description": "Cuireann River ceannach Bitcoin, mianadóireacht, agus seirbhísí coimhdeachta ar fáil le fócas ar oideachas agus slándáil.",
	"buy_platform_coinsquare_description": "Is malartán Bitcoin Ceanadach é Coinsquare le comhlíonadh rialála láidir agus tacaíocht custaiméara.",
	"buy_platform_kraken_description": "Is malartán Bitcoin bunaithe é Kraken le gnéithe trádála ardleibhéil agus slándáil láidir.",
	"buy_platform_atm_description": "Ligeann ATManna Bitcoin duit Bitcoin a cheannach le hairgead tirim go láithreach. Faigh ceann in aice leat ag úsáid Coin ATM Radar.",
	"buy_platform_bisq_description": "Is malartán díláraithe piara le piara é Bisq a ligeann d'idirbhearta príobháideacha Bitcoin gan KYC.",
	"buy_platform_feature_instant": "Ceannacháin láithreacha",
	"buy_platform_feature_low_fees": "Táillí ísle",
	"buy_platform_feature_lightning": "Líonra Lightning",
	"buy_platform_feature_dca": "Meánú costais dollair",
	"buy_platform_feature_education": "Acmhainní oideachais",
	"buy_platform_feature_withdrawal": "Aistarraingt éasca",
	"buy_platform_feature_mining": "Mianadóireacht Bitcoin",
	"buy_platform_feature_custody": "Seirbhísí coimhdeachta",
	"buy_platform_feature_canadian": "Dírithe ar Cheanada",
	"buy_platform_feature_regulated": "Malartán rialáilte",
	"buy_platform_feature_support": "Tacaíocht custaiméara",
	"buy_platform_feature_established": "Ardán bunaithe",
	"buy_platform_feature_security": "Slándáil láidir",
	"buy_platform_feature_advanced": "Gnéithe ardleibhéil",
	"buy_platform_feature_cash": "Ceannacháin airgid thirim",
	"buy_platform_feature_anonymous": "Níos anaithnide",
	"buy_platform_feature_p2p": "Piara le piara",
	"buy_platform_feature_private": "Trádáil phríobháideach",
	"buy_platform_feature_decentralized": "Díláraithe",
	"buy_platform_relai_description": "Is aip Eilvéiseach Bitcoin-amháin é Relai le sparán féinchoimirce, gnéithe uathinfheistíochta, agus táillí ísle d'úsáideoirí Eorpacha.",
	"buy_platform_feature_bitcoin_only": "Bitcoin amháin",
	"buy_platform_feature_self_custody": "Sparán féinchoimirce",
	"buy_platform_feature_auto_invest": "Pleananna uathinfheistíochta",
	"buy_platform_feature_european": "Dírithe ar an Eoraip",
	"buy_step_4_header": "CÉIM 4: STÓRÁIL DO BITCOIN GO SÁBHÁILTE",
	"buy_step_4_c1": "Tar éis Bitcoin a cheannach, is í an chéim is tábhachtaí ná é a bhogadh chuig do sparán féin ina bhfuil smacht agat ar na heochracha príobháideacha.",
	"buy_step_4_c2": "Tá sé riosca Bitcoin a fhágáil ar mhalartán toisc nach leatsa an Bitcoin i ndáiríre - is leis an malartán é.",
	"buy_step_4_c3": "Nuair a rialaíonn tú d'eochracha príobháideacha féin, tá fíorúinéireacht agat ar do Bitcoin agus ní féidir le haon duine é a thógáil uait.",
	"buy_step_4_c4": "Foghlaim conas an sparán Bitcoin ceart a roghnú do do riachtanais:",
	"buy_cta_wallets": "Féach ar ár dTreoir Sparán Bitcoin"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Treoir Sparán Lightning Bitcoin",
	"lightning_description": "Cumasaíonn sparáin Lightning duit Bitcoin a sheoladh go tapa agus go saor agus do cheannasacht phearsanta á coinneáil agat.",
	"lightning_header": "TREOIR SPARÁN LIGHTNING",
	"lightning_s1_c1": "Cumasaíonn Lightning duit íocaíochtaí Bitcoin a sheoladh go tapa agus go saor.",
	"lightning_s1_c2": "Tá sé tábhachtach a fhios a bheith agat go dtagann comhbhabhtálacha le húsáid lightning. Mar mhalairt ar íocaíochtaí Bitcoin níos tapúla agus níos saoire, íobraíonn tú roinnt slándála go minic.",
	"lightning_s1_c3": "Go ginearálta, níor cheart Lightning a úsáid ach le méideanna beaga bitcoin. Níor cheart duit méideanna móra bitcoin a stóráil ach i sparán crua-earraí.",
	"lightning_s1_c4": "Féach ar ár dTreoir Sparán Crua-earraí le haghaidh tuilleadh eolais.",
	"lightning_s1_c5": "Ní hionann gach sparán Lightning. Is féidir leat a chinneadh cé acu sparán a bhfuil an meascán comhbhabhtálacha ceart agat trí aon cheist shimplí a chur:",
	"lightning_question_1": "CÉN COTHROMAÍOCHT CHOMHBHABHTÁLA ATÁ CEART DOM?",
	"lightning_s2_c1": "Ceann de nuálaíochtaí Bitcoin ná an cumas é a stóráil gan a bheith ag brath ar choimhdeachtóir, cosúil le banc. Osclaíonn sparáin féinchoimirce cumhacht iomlán Bitcoin.",
	"lightning_s2_c2": "Le sparán féinchoimirce, is tú an t-aon duine a bhfuil an cumas aige d'airgead a chaitheamh nó a aistriú. Ní féidir le haon duine tú a stopadh, tú a chinsireacht, nó goid uait nuair a úsáideann tú sparán féinchoimirce. Tugtar sparáin neamhchoimhdeachta orthu seo freisin.",
	"lightning_s2_c3": "Is é an bealach is ceannasaí chun Lightning a úsáid ná do nód féin a rith.",
	"lightning_s2_c4": "Díríonn an treoir seo ar sparáin shimplí Lightning nach dteastaíonn do nód féin uathu.",
	"lightning_s2_c5": "Tá sé tábhachtach a fhios a bheith agat fiú ag úsáid sparán Lightning neamhchoimhdeachta, go bhfuil tú fós ag muinín chruthaitheoir an sparáin gan nuashonrú mailíseach aip a bhrú agus do chistí a ghoid.",
	"lightning_s3_c1": "Is sparáin iad sparáin choimhdeachta nach bhfuil tú i smacht ar d'airgead iontu.",
	"lightning_s3_c2": "Tá na sparáin seo níos cosúla leis an gcóras baincéireachta inar gá duit muinín a bheith agat as tríú páirtí chun rochtain ar d'airgead a thabhairt duit. Má tá do Bitcoin ar mhalartán, tá tú ag úsáid sparán coimhdeachta.",
	"lightning_s3_c3": "D'fhéadfadh sparáin choimhdeachta a bheith áisiúil, ach tá an cumas teicniúil ag an gcoimhdeachtóir cistí úsáideoirí ar fad a ghoid am ar bith.",
	"lightning_s3_c4": "Is fearr le roinnt daoine sparáin Lightning choimhdeachta do mhéideanna beaga bitcoin mar gheall ar a n-éascaíocht úsáide. Cuimhnigh: ní hé d'eochracha, ní hé do bhoinn!",
	"lightning_question_2": "ROGHNAIGH DO SPARÁN",
	"lightning_s4_c1": "Leis an méid sin ar fad i gcuimhne, is féidir leat anois an sparán lightning a roghnú a bhfuil an chothromaíocht chomhbhabhtála ceart agat.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "Go leor gnéithe",
	"lightning_mobile_app": "Aip mhóibíleach",
	"lightning_free": "100% saor in aisce",
	"lightning_merchants": "Iontach do cheannaithe",
	"lightning_starter": "Sparán iontach le tosú",
	"lightning_browser": "Bunaithe ar bhrabhsálaí",
	"lightning_custodial": "Sparán go hiomlán coimhdeachta",
	"lightning_cta_hardware": "Ag lorg ár dTreoir Sparán Crua-earraí Bitcoin?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "Greamáin Bitcoin saor in aisce ó bitcoin.rocks",
	"stickers_description": "Cuir greamán bitcoin in áit phoiblí chun iad siúd timpeall ort a oráistephiollú.",
	"stickers_header": "GREAMÁIN BITCOIN SAOR IN AISCE",
	"stickers_choose_header": "ROGHNAIGH DO PHACÁISTE GREAMÁN",
	"stickers_choose_c1": "Is é ár misean cabhrú leat níos mó daoine a oráistephiollú trí ghreamáin Bitcoin a chur in áiteanna poiblí. Tá cóid QR ar ár ngreamáin ar fad a nascann le leathanaigh oideachais faoi",
	"stickers_choose_c2": "Bitcoin",
	"stickers_choose_c3": "boilsciú",
	"stickers_choose_c4": "Roghnaigh do phacáiste greamán thíos",
	"stickers_text_pack": "AN PACÁISTE TÉACS",
	"stickers_signs_pack": "AN PACÁISTE COMHARTHAÍ",
	"stickers_instructions_1": "Cuir do sheoladh poist isteach agus cuirfimid Pacáiste Greamán Bitcoin saor in aisce chugat sa phost! Seolfar do chuid greamán i gclúdach bán simplí.",
	"stickers_instructions_2": "Scriostar sonraí seoltaí tar éis do ghreamáin saor in aisce a sheoladh.",
	"stickers_share_header": "ROINN DO LÁITHREACHA GREAMÁN",
	"stickers_share_c1": "Roinn do láithreacha greamán linn ar Nostr agus féach cá bhfuil daoine eile ag cur a gcuid greamán.",
	"stickers_btn_share_on_nostr": "ROINN AR NOSTR",
	"stickers_btn_what_is_nostr": "CÉARD É NOSTR?",
	"stickers_flyers_link_before": "Agus tú ag é, priontáil & cuir suas do chuid ",
	"stickers_flyers_link_text": "bileoga Bitcoin",
	"stickers_flyers_link_after": " féin chun níos mó daoine fós a oráistephiollú.",
	"stickers_country_global_print": "Domhanda — Priontáil mo ghreamáin féin",
	"stickers_country_global_order": "Domhanda — Ordaigh i mbulc",
	"placeholder_name_optional": "Ainm (roghnach)",
	"placeholder_address_line_1": "Líne Seolta 1",
	"placeholder_address_line_2": "Líne Seolta 2 (roghnach)",
	"placeholder_city": "Cathair",
	"placeholder_state": "Stát",
	"placeholder_province": "Cúige",
	"placeholder_zip_code": "Cód Zip",
	"placeholder_postal_code": "Cód Poist",
	"placeholder_language": "Teanga",
	"placeholder_which_stickers": "Cé na greamáin?",
	"placeholder_email_optional": "Cuir do ríomhphost isteach le fógra a fháil (roghnach)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "Cártaí Poist Bitcoin saor in aisce ó bitcoin.rocks",
	"postcards_description": "Faigh Pacáiste Cártaí Poist Bitcoin saor in aisce agus roinn Bitcoin le duine a bhfuil aithne agat air.",
	"postcards_header": "CLÁR CÁRTAÍ POIST DÚNTA",
	"postcards_program_closed_message": "Tá ár gclár cártaí poist Bitcoin saor in aisce tagtha chun deiridh. Go raibh maith agat le gach duine a ghlac páirt i scaipeadh oideachais Bitcoin tríd an bpost!",
	"postcards_sticker_alternative_header": "FAIGH GREAMÁIN BITCOIN SAOR IN AISCE INA IONAD",
	"postcards_sticker_alternative_message": "Lean ort ag scaipeadh feasachta Bitcoin lenár gclár greamán saor in aisce! Tá ár ngreamáin Bitcoin foirfe le roinnt in áiteanna poiblí agus tagann cóid QR leo a nascann le hábhar oideachais.",
	"postcards_sticker_cta": "FAIGH GREAMÁIN SAOR IN AISCE",
	"postcards_step_2": "CÉARD A BHÍ CÁRTAÍ POIST COSÚIL LEIS",
	"postcards_instructions_4": "Rinneamar na cártaí poist seo chun é a dhéanamh níos éasca duit duine a bhfuil aithne agat air a chur in aithne do Bitcoin! Níl le déanamh agat ach seoladh agus stampa a chur air agus do chárta poist a chur sa phost.",
	"postcards_instructions_5": "Is é ár misean glacadh le Bitcoin a luathú. Is féidir leat cabhrú trí ghreamáin saor in aisce a fháil agus iad a chur in áiteanna poiblí!",
	"postcards_instructions_6": "Tá a fhios againn ar fad roinnt daoine a d'fhéadfadh tairbhe a bhaint as tuilleadh a fhoghlaim faoi Bitcoin. Roinn greamáin Bitcoin leo inniu!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "Cabhraigh linn na Comharthaí Bitcoin seo a chur ar fud Mheiriceá!",
	"signs_title": "Comharthaí Bitcoin saor in aisce ó bitcoin.rocks",
	"signs_choose_header": "GO RAIBH MAITH AGAT AS CABHRÚ LINN NA COMHARTHAÍ BITCOIN SEO A CHUR AR FUD MHEIRICEÁ!",
	"signs_choose_c1": "Táimid go hiomlán as comharthaí anois! Is é ár misean glacadh le Bitcoin a luathú trí oideachas.",
	"signs_choose_c2": "Chabhraigh go leor agaibh trí na comharthaí Bitcoin saor in aisce seo a chur in áiteanna poiblí. Tá cóid QR ar ár gcomharthaí ar fad a nascann le leathanach oideachais faoi",
	"signs_choose_c3": "boilsciú",
	"signs_choose_c4": "A bhuíochas lenár bpobal iontach, shroicheamar na mílte daoine agus chabh raíomar leo a gcéad chéimeanna a ghlacadh síos poll coinín Bitcoin.",
	"signs_share_header": "ROINN DO LÁITHREACHA COMHARTHAÍ",
	"signs_share_c1": "Roinn grianghraf de do láthair chomhartha linn ar Nostr agus féach cá bhfuil daoine eile ag cur a gcuid comharthaí.",
	"signs_btn_share_on_nostr": "ROINN AR NOSTR",
	"signs_btn_what_is_nostr": "CÉARD É NOSTR?",
	"signs_instructions_1": "Cuir do sheoladh poist isteach agus cuirfimid bosca de 10 gcomhartha Bitcoin chugat sa phost!",
	"signs_instructions_2": "Scriostar sonraí seoltaí tar éis do chomharthaí saor in aisce a sheoladh."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "Bileoga Bitcoin saor in aisce ó bitcoin.rocks",
	"flyers_description": "Priontáil bileog Bitcoin sa bhaile agus cuir in áit phoiblí í chun iad siúd timpeall ort a oráistephiollú.",
	"flyers_header_1": "PRIONTÁIL & CUIR SUAS",
	"flyers_header_2": "BILEOGA BITCOIN",
	"flyers_intro_header": "CONAS NA BILEOGA BITCOIN SEO A PHRIONTÁIL & A CHUR SUAS",
	"flyers_intro_c1": "Is é ár misean cabhrú leat níos mó daoine a oráistephiollú trí bhileoga Bitcoin a chur in áiteanna poiblí. Tá cód QR ar an mbileog seo a nascann lenár",
	"flyers_intro_c2": "suíomh oideachais Bitcoin.",
	"flyers_intro_c3": "boilsciú",
	"flyers_intro_c4": "Priontáil an bhileog seo sa bhaile nó i siopa priontála. Ansin, cuir ar chláir fhógraí, ar chuaillí teileafóin timpeall an bhaile, agus in áiteanna poiblí eile inar féidir le daoine í a fheiceáil agus foghlaim faoi Bitcoin.",
	"flyers_intro_c5": "Agus tú ag é, iarr pacáiste dár",
	"flyers_intro_c6": "ngreamáin Bitcoin saor in aisce",
	"flyers_intro_c7": "chun níos mó daoine fós a oráistephiollú.",
	"flyers_btn_download": "ÍOSLÓDÁIL BILEOG",
	"flyers_btn_print": "PRIONTÁIL BILEOG",
	"flyers_share_header": "ROINN DO LÁITHREACHA BILEOG",
	"flyers_share_c1": "Roinn do láithreacha bileog linn ar Nostr agus féach cá bhfuil daoine eile ag cur a gcuid bileog.",
	"flyers_btn_share_on_nostr": "ROINN AR NOSTR",
	"flyers_btn_what_is_nostr": "CÉARD É NOSTR?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "Glac páirt agus cabhraigh le Bitcoin a scaipeadh",
	"get_involved_description": "Déanann ár n-acmhainní saor in aisce é níos éasca glacadh le Bitcoin a scaipeadh.",
	"get_involved_header": "GLAC PÁIRT",
	"get_involved_header_2": "SCAIP BITCOIN",
	"get_involved_intro_1": "Is féidir le sé a bheith gruama a bheith beo i riocht reatha ár ndomhain.",
	"get_involved_intro_2": "Tá ár n-airgead briste. Dá bharr sin, tá píosaí bunúsacha den tsochaí briste freisin.",
	"get_involved_intro_3": "Má tá tú i mBitcoin cheana féin, tá a fhios agat an braistint dóchais gur féidir le Bitcoin a thabhairt. Dóchas do thodhchaí níos gile arna fhéidearthú ag airgead níos fearr.",
	"get_involved_intro_4": "Ach ní bhfuil a fhios ag an oiread sin daoine timpeall ort faoi Bitcoin. Tá siad ag maireachtáil sa domhan briste céanna leatsa, ach gan lóchrann dóchais chun cabhrú leo tríd an dorchadas.",
	"get_involved_intro_5": "Ach is féidir leatsa cabhrú le sin a athrú. Tá roinnt acmhainní saor in aisce déanta againn chun é a dhéanamh níos éasca an dóchas a thugann Bitcoin a scaipeadh chuig iad siúd timpeall ort.",
	"get_involved_sticker_header": "Cuir greamán in áit phoiblí",
	"get_involved_sticker_content_1": "Is féidir leat cabhrú le hiad siúd timpeall ort a oideachasú faoi Bitcoin gan dul i dteagmháil le haon duine. Níl le déanamh agat ach ceann dár ngreamáin Bitcoin saor in aisce a chur in áit phoiblí.",
	"get_involved_sticker_content_2": "Scanann na céadta daoine na cóid QR ar na greamáin seo gach mí. Nascann na greamáin bhoilscithe le leathanach faoi",
	"get_involved_sticker_content_3": "Bitcoin mar réiteach ar bhoilsciú.",
	"get_involved_sticker_content_4": "Nascann na greamáin eile lenár leathanach baile oideachais a thaispeánann do dhaoine conas atá",
	"get_involved_sticker_content_5": "Bitcoin ag tógáil domhain níos fearr.",
	"get_involved_sticker_content_6": "Trí na greamáin seo a chur suas i do phobal in áiteanna a bhfeicfidh daoine iad, is féidir leat cabhrú le iad siúd timpeall ort a gcéad chéimeanna a ghlacadh síos poll coinín Bitcoin.",
	"get_involved_request_a": "IARR",
	"get_involved_sticker_pack": "PACÁISTE GREAMÁN",
	"get_involved_postcard_header": "Seol cárta poist",
	"get_involved_postcard_content_1": "Is féidir leat cabhrú le Dóchas Bitcoin a scaipeadh chuig duine a bhfuil aithne agat air trí cheann dár gcártaí poist saor in aisce a sheoladh chucu.",
	"get_involved_postcard_content_2": "Tá achoimre spreagúil faoi Bitcoin ar chúl gach cárta poist mar aon le cód QR chun tuilleadh a fhoghlaim.",
	"get_involved_postcard_content_3": "Trí chárta poist Bitcoin a sheoladh chuig duine, is féidir leat cabhrú leo Bitcoin a fheiceáil ar bhealach nua.",
	"get_involved_postcard_pack": "PACÁISTE CÁRTAÍ POIST",
	"get_involved_business_header": "Cuir gnó ar bun",
	"get_involved_business_content_1": "Ar mhaith leat cabhrú le geilleagar ciorclach Bitcoin a thógáil? Déanann ár bPacáiste Gnó Bitcoin é éasca cur chuige a dhéanamh ar ghnó faoi ghlacadh le híocaíochtaí Bitcoin.",
	"get_involved_business_content_2": "Cuimsíonn gach pacáiste gnó bileoga a aibhsíonn na buntáistí a bhaineann le glacadh le híocaíochtaí Bitcoin. Nascann gach bileog le raon",
	"get_involved_business_content_3": "acmhainní gnó Bitcoin saor in aisce.",
	"get_involved_business_kit": "PACÁISTE GNÓ"
});

console.log(`\nDone! Created 9 content files.`);
