/**
 * Creates Japanese (ja) translation file for index.json (~140 keys)
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ja';
const today = '2026-04-02';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"bitcoin_builds_a_better_world": "ビットコインはより良い世界を築いています。",
	"home_description": "ビットコインはより良い世界を築いているより良いお金です。ビットコインは人権を守り、高インフレから人々を救い、地元の農家を支援し、石油掘削からの排出を削減し、その他にも多くのことを成し遂げています。",
	"home_intro": "ビットコインはより良い世界を築いているより良いお金です。下のカテゴリをタップしてビットコインがどのように改善しているかを学ぶか、スクロールして探索を始めましょう。",
	"home_btn_money": "より良いお金",
	"home_btn_salary": "あなたの給与",
	"home_btn_freedom": "自由",
	"home_btn_human_rights": "人権",
	"home_btn_equality": "平等",
	"home_btn_property_rights": "財産権",
	"home_btn_housing": "住宅",
	"home_btn_business": "ビジネス",
	"home_btn_crowdfunding": "クラウドファンディング",
	"home_btn_energy": "エネルギー",
	"home_btn_environment": "環境",
	"home_btn_food": "食料",
	"home_btn_art": "アート",
	"home_btn_politics": "政治",
	"home_btn_war": "戦争",
	"home_btn_coding": "プログラミング",
	"home_btn_networks": "ネットワーク",
	"home_btn_payments": "決済",
	"home_btn_self_custody": "自己管理",
	"home_btn_you": "あなた",
	"home_section_bitcoin_is": "ビットコインは",
	"home_section_bitcoin_and": "ビットコインと",
	"home_link_type_website": "ウェブサイト",
	"home_link_type_video": "動画",
	"home_link_type_article": "記事",
	"home_link_type_podcast": "ポッドキャスト",
	"home_link_type_business_kit": "ビジネスキット",
	"home_link_type_data": "データ",
	"home_link_type_research": "研究",
	"home_link_type_story": "ストーリー",
	"home_link_type_book_excerpt": "本の抜粋",
	"home_link_type_street_art": "ストリートアート",
	"home_link_type_outreach": "アウトリーチ",
	"home_link_type_campaign": "キャンペーン",
	"home_link_type_software": "ソフトウェア",
	"home_link_type_hardware": "ハードウェア",
	"home_link_type_guide": "ガイド",
	"home_link_type_email": "メール",
	"home_link_title_inflation": "ビットコインにはインフレがない",
	"home_link_title_bank_runs": "ビットコインには取り付け騒ぎがない",
	"home_link_title_gold": "ビットコイン vs 金",
	"home_link_title_crypto": "ビットコイン vs 暗号通貨",
	"home_link_title_cash": "ビットコイン vs 現金",
	"home_link_title_bonds": "ビットコイン vs 債券",
	"home_link_title_cbdc": "ビットコイン vs CBDC",
	"home_link_title_your_salary_1": "インフレに追いつくために給与をどれだけ上げる必要があるか確認しましょう。",
	"home_link_title_freedom_1": "ビットコインが自由にとって重要な理由",
	"home_link_title_freedom_2": "ビットコインは政治的抑圧からの自由を提供する",
	"home_link_title_human_rights_1": "ビットコインが人権をどのように守っているか",
	"home_link_title_human_rights_2": "アフリカの静かなビットコイン革命",
	"home_link_title_human_rights_3": "ビットコインは世界中で人権を守っている",
	"home_link_title_equality_1": "ビットコインは南アフリカの人々に希望と機会をもたらしている",
	"home_link_title_equality_2": "ビットコインがアフリカ系アメリカ人にとってゲームチェンジャーになり得る理由",
	"home_link_title_property_rights_1": "ビットコインは完璧な財産の形態",
	"home_link_title_property_rights_2": "ビットコイン vs 不動産",
	"home_link_title_housing_1": "ビットコインが住宅を再び手頃にする方法",
	"home_link_title_business_3": "ビットコイン vs 株式",
	"home_link_title_business_1": "ビットコインがビジネスに最適な理由を学ぶ",
	"home_link_title_business_2": "地元のビジネスにビットコイン決済を導入する",
	"home_link_title_crowdfunding_1": "ビットコインがナイジェリア最大の抗議運動を支えた方法",
	"home_link_title_crowdfunding_2": "GoFundMeが寄付をブロックした後、カナダのトラック運転手の抗議運動がビットコインで資金を調達",
	"home_link_title_crowdfunding_3": "Geyser = ビットコインでクラウドファンディング",
	"home_link_title_energy_1": "ビットコインがテキサスの電力網をどのように安定化させているか",
	"home_link_title_energy_2": "なぜビットコインはエネルギーを使うのか？",
	"home_link_title_energy_3": "ビットコインのエネルギー使用は問題ではない。その理由。",
	"home_link_title_energy_4": "ビットコインマイニングはデマンドレスポンスでエネルギーグリッドを安定化させている",
	"home_link_title_energy_5": "ビットコインマイナーはアフリカの農村コミュニティに水力発電をもたらしている",
	"home_link_title_energy_6": "ビットコインが再生可能エネルギーを促進する方法",
	"home_link_title_environment_1": "ビットコインマイニングが世界のメタン排出量を削減している方法",
	"home_link_title_environment_2": "ビットコインマイニングが国立公園を救った方法",
	"home_link_title_environment_3": "ビットコインは地球上で最もグリーンな産業！",
	"home_link_title_environment_4": "ビットコインマイニングはフレアガスの大気汚染を防いでいる",
	"home_link_title_food_1": "インフレが食品価格にどのように影響するか",
	"home_link_title_food_2": "法定通貨が食料、農場、地球の土壌に悪影響を及ぼす理由",
	"home_link_title_fine_art": "ビットコイン vs 高級美術品",
	"home_link_title_art_1": "ビットコインステッカーイニシアチブに参加しよう",
	"home_link_title_art_2": "知り合いにビットコインポストカードを送ろう",
	"home_link_title_art_3": "ビットコインチラシを印刷して掲示しよう",
	"home_link_title_politics_1": "ビットコインは政治的パラドックス",
	"home_link_title_politics_2": "より良いお金に投票できる",
	"home_link_title_war_1": "ビットコインが終わりなき戦争を終わらせる方法",
	"home_link_title_war_2": "ビットコインと退役軍人：自然な結びつき",
	"home_link_title_war_3": "ビットコインがスーダンの内戦から民間人が逃れるのを助けている方法",
	"home_link_title_coding_1": "ビットコインの技術面に関するインタラクティブチュートリアル",
	"home_link_title_coding_2": "bitcoinSwitch：あらゆるデバイスをビットコイン対応にレトロフィット",
	"home_link_title_coding_3": "ビットコインの謎をコードで解き明かそう",
	"home_link_title_networks_1": "ビットコインネットワークのライブビュー",
	"home_link_title_networks_2": "ビットコイン vs 銀行",
	"home_link_title_payments_1": "ビットコイン vs Visa",
	"home_link_title_payments_2": "ライトニングネットワーク（即時ビットコイン決済）を見てみよう",
	"home_link_title_payments_3": "エルサルバドルのビットコインウォレットで送金手数料を年間4億ドル節約可能",
	"home_link_title_payments_4": "ライトニングアドレスを取得して即時ビットコイン決済を受け取ろう",
	"home_link_title_self_custody_1": "ビットコインを安全に保管する方法",
	"home_link_title_self_custody_2": "取引所からビットコインを引き出すべき6つの理由",
	"home_link_title_self_custody_3": "金、ビットコイン、そして自己管理",
	"home_link_title_get_started_1": "ビットコインの基本を学ぶ",
	"home_link_title_get_started_2": "最初のビットコインウォレットを入手する",
	"home_link_title_get_started_3": "ビットコインの購入方法",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "複利インフレ計算機",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! index.json created for Japanese (ja).');
