/**
 * Creates Swahili (sw) translation file for common.json (~180+ keys)
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'sw';
const today = '2026-04-03';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"common_footer_mission_1": "Dhamira ya bitcoin.rocks ni kuharakisha kupitishwa kwa bitcoin kupitia elimu.",
	"common_footer_mission_2": "Jifunze jinsi ya kuchangia mradi huu wa chanzo huria.",
	"common_footer_follow_first_half": "Tufuate kwenye Nostr kwa kutafuta",
	"common_footer_follow_second_half": "katika programu yoyote ya Nostr.",
	"common_footer_what_is_nostr": "Nostr ni nini?",
	"common_footer_about": "Kuhusu",
	"common_footer_email_us": "Tuandikie barua pepe:",
	"common_cta_section_get_started": "ANZA",
	"common_cta_section_with_bitcoin": "NA BITCOIN",
	"common_cta_section_title_1": "Jifunze misingi ya Bitcoin",
	"common_cta_section_title_1_alt": "Jifunze zaidi kuhusu Bitcoin",
	"common_cta_section_title_2": "Pata Pochi yako ya kwanza ya Bitcoin",
	"common_cta_section_title_3": "Jinsi ya Kununua Bitcoin",
	"common_cta_link_type_email": "BARUA PEPE",
	"common_cta_link_type_guide": "MWONGOZO",
	"common_cta_link_type_website": "TOVUTI",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "BITCOIN NI NINI?",
	"common_what_is_bitcoin_content_1": "Bitcoin ni vitu viwili: pesa za kidijitali na mtandao wa malipo. Unaweza kutuma Bitcoin (pesa za kidijitali) moja kwa moja kwa watu wengine ukitumia mtandao wa Bitcoin (mtandao wa malipo).",
	"common_what_is_bitcoin_content_2": "Bitcoin ni njia mpya kabisa ya kuhifadhi na kubadilishana thamani. Tofauti na mitandao ya kawaida ya fedha, mtandao wa Bitcoin unaweza kufanya kazi bila mamlaka kuu au wasimamizi wanaoaminiwa. Hii inafanya Bitcoin kuwa pesa ya kwanza ya wazi na isiyo na mipaka.",
	"common_what_is_bitcoin_content_3": "Bitcoin ni pesa za kidijitali zinazokupa umiliki kamili wa mali yako. Kwa mara ya kwanza katika historia ya binadamu kila mtu anaweza kumiliki mali ambayo ni adimu kweli kweli, haihitaji ruhusa kutumika, na haiwezi kunyang'anywa ikihifadhiwa vizuri.",
	"common_what_is_bitcoin_content_4": "Bitcoin inaweza kutumwa popote duniani, haraka na kwa bei nafuu. Haihitaji mpitishaji wa wahusika wa tatu, kama benki.",
	"common_what_is_bitcoin_content_5": "Bitcoin inamruhusu mtu yeyote kuhifadhi mali yake kwa usalama bila wasiwasi wa serikali kuiba au kupunguza thamani yake kupitia uchapishaji wa pesa.",
	"common_what_is_bitcoin_content_6": "Serikali kila mahali zinaweza kuchapisha pesa zaidi za karatasi, lakini hakuna mtu anayeweza kuchapisha bitcoin zaidi.",
	"common_what_is_bitcoin_content_7": "Unaweza kuhifadhi Bitcoin yako mwenyewe kwa urahisi kuchukua udhibiti kamili, kukupa ufikiaji kamili wa nguvu ya Bitcoin.",
	"common_what_is_bitcoin_content_8": "Ukiweza kupakua programu, unaweza kuhifadhi Bitcoin mwenyewe na kuhifadhi mali yako bila kutegemea mtu mwingine yeyote.",
	"common_what_is_bitcoin_content_9": "Bitcoin ni pesa bora.",
	"common_bitcoin_volatile": "NIMESIKIA BITCOIN NI YENYE MABADILIKO. JE, NI SALAMA?",
	"common_bitcoin_volatile_content_1": "Kwa muda mfupi, kiwango cha ubadilishaji wa Bitcoin kinaweza kubadilika. Hii inaitwa mabadiliko ya bei.",
	"common_bitcoin_volatile_content_2": "Lakini mabadiliko unayoyaona kila siku 'yanapotea' kwa muda mrefu.",
	"common_bitcoin_volatile_content_3": "Bitcoin inaendelea kuwa na mabadiliko kidogo zaidi kwa muda. Kadiri watu wengi wanavyotumia Bitcoin kama akaunti ya akiba ya muda mrefu, ndivyo thamani yake inavyoimarika.",
	"common_bitcoin_volatile_content_4": "Watu wengi wanachagua kuhifadhi thamani katika Bitcoin kwa miaka mingi kama njia salama ya kupunguza hatari ya mabadiliko na kulinda nguvu yao ya ununuzi kwa muda.",
	"common_bitcoin_volatile_content_5": "Katika nchi zingine, kama Venezuela, Sudan, Lebanon, Syria, Argentina, Uturuki, Brazil, na nyingine nyingi, thamani ya sarafu ya ndani inapungua haraka sana hivi kwamba Bitcoin inaonekana kuwa njia thabiti zaidi ya kuokoa pesa.",
	"common_bitcoin_afford": "SIWEZI KUMUDU BITCOIN NZIMA",
	"common_bitcoin_afford_content_1": "Dola inajumuisha senti 100. Bitcoin inajumuisha sats 100,000,000 (milioni 100).",
	"common_bitcoin_afford_content_2": "Huhitaji kumiliki bitcoin nzima. Watu wengi wanamiliki tu sats. Sats ni sehemu ndogo za bitcoin. Kwa mfano, ikiwa bitcoin 1 nzima ni $100,000 basi $1 inakununulia sats 1,000!",
	"common_bitcoin_hacked": "JE, BITCOIN IMEWAHI KUDUKULIWA?",
	"common_bitcoin_hacked_content_1": "Huenda umesikia kuhusu 'udukuzi wa Bitcoin' mtandaoni au kwenye habari. Watu wengi wanasoma makala hizi na kuamini mtandao wa Bitcoin umedukuliwa. Hata hivyo, mtandao wa Bitcoin haujawahi kudukuliwa.",
	"common_bitcoin_hacked_content_2": "Mtandao wa Bitcoin ni nini? Fikiria mtandao wa Bitcoin kama reli za treni. Treni zinazopita kwenye reli za mtandao wa Bitcoin ni miamala ya Bitcoin.",
	"common_bitcoin_hacked_content_3": "Unaposoma kuhusu udukuzi wa Bitcoin kwenye habari, unasoma kuhusu mhifadhiaji (kama FTX) kudukuliwa au kufilisika.",
	"common_bitcoin_hacked_content_4": "Wahifadhiaji ni makampuni yanayoshikilia bitcoin yako kwa niaba yako. Hata hivyo, hiyo ina hatari: kupoteza bitcoin yako wakati kampuni inaposimamia vibaya, kuiba, au kutoka biasharani.",
	"common_bitcoin_hacked_content_5": "Hii ilitokea hivi karibuni na FTX.",
	"common_bitcoin_hacked_content_6": "Kila mtu aliyeamini FTX na bitcoin yao alipoteza bitcoin yake. Kila mtu aliyeshikilia bitcoin yake kwa uhifadhi wa kibinafsi hakuathiriwa kabisa na FTX. Hiyo ndiyo nguvu ya bitcoin katika uhifadhi wa kibinafsi: udhibiti wa kweli wa pesa yako.",
	"common_bitcoin_hacked_content_7": "Badala ya kuacha bitcoin yako kwenye soko la kubadilishana au katika kifungashio kama ETF, ishikilie katika pochi yako mwenyewe kwa faida zote za uhuru.",
	"common_bitcoin_hacked_content_8": "Unapohifadhi bitcoin yako mwenyewe, pesa yako inalindwa na Mtandao wa Bitcoin. Ni mtandao salama zaidi wa fedha duniani.",
	"common_bitcoin_hacked_content_9": "Katika uhifadhi wa kibinafsi, Sam wa FTX hawezi kuiba bitcoin yako.",
	"common_bitcoin_hacked_content_10": "Serikali haiwezi kuchapisha bitcoin zaidi na kusababisha mfumuko wa bei.",
	"common_bitcoin_hacked_content_11": "Bitcoin katika uhifadhi wa kibinafsi ni pesa yako, shukrani kwa nguvu ya Mtandao wa Bitcoin.",
	"common_bitcoin_energy": "KWA NINI BITCOIN INATUMIA NISHATI?",
	"common_bitcoin_energy_content_1": "Bitcoin inatumia nishati kulinda mtandao na kulinda pesa yako.",
	"common_bitcoin_energy_content_2": "Bitcoin inatumia kiasi kikubwa cha nishati, na hii ni jambo zuri kwa sababu nyingi.",
	"common_bitcoin_energy_list_1": "Bitcoin haina mikimbilio ya benki.",
	"common_bitcoin_energy_list_2": "Bitcoin inasaidia kuimarisha gridi za nishati na uchimbaji wa bitcoin.",
	"common_bitcoin_energy_list_3": "Bitcoin inapunguza utoaji wa hewa chafu kutoka kwa uchimbaji wa mafuta.",
	"common_bitcoin_energy_list_4": "Bitcoin inatumia nishati kidogo kuliko Waamerika wanavyotumia kwa Taa za Krismasi kila mwaka.",
	"common_bitcoin_energy_list_5": "Bitcoin ni tasnia ya kijani zaidi Duniani!",
	"common_cic_intro_1": "Watu wengi wanajua kuhusu Riba ya Mkusanyiko, lakini watu wachache wanajua kuhusu Mfumuko wa Bei wa Mkusanyiko.",
	"common_cic_intro_2": "Na Kikokotoo chetu cha Mfumuko wa Bei wa Mkusanyiko, unaweza kukokotoa kwa urahisi kiasi gani mshahara wako unahitaji kuongezeka ili kudumisha nguvu yako ya ununuzi kwa muda.",
	"common_cic_intro_3": "Ingiza tu mshahara wako wa sasa, kiwango cha mfumuko wa bei, na idadi ya miaka unayotaka kukokotoa, na kikokotoo chetu kitakuonyesha mshahara wako unapaswa kuwa nini ili kuendana na mfumuko wa bei.",
	"common_current_salary": "mshahara wa sasa",
	"common_inflation_rate": "kiwango cha mfumuko wa bei",
	"common_year": "mwaka",
	"common_years": "miaka",
	"common_result_starting_message": "Jaza fomu hapo juu na bofya kokotoa.",
	"common_error_message": "Kosa: Tafadhali jaza sehemu zote 3 za fomu.",
	"common_result_message_1": "Kwa kiwango cha mfumuko wa bei cha",
	"common_result_message_2": "mshahara wako wa",
	"common_result_message_3": "unahitaji kuongezeka hadi",
	"common_result_message_in": "katika",
	"common_result_message_4": "ili kudumisha nguvu yako ya ununuzi.",
	"common_calculate_button_text": "KOKOTOA",
	"common_learn_more": "JIFUNZE ZAIDI",
	"common_success": "MAFANIKIO!",
	"common_choose_your_country": "Chagua nchi yako",
	"common_country_usa": "Marekani",
	"common_country_canada": "Kanada",
	"common_submit": "WASILISHA",
	"common_language_afrikaans": "KIAFRIKAANS",
	"common_language_arabic": "KIARABU",
	"common_language_basque": "KIBASQUE",
	"common_language_bulgarian": "KIBULGARIA",
	"common_language_catalan": "KIKATALANI",
	"common_language_chinese": "KICHINA",
	"common_language_croatian": "KIKROESHIA",
	"common_language_czech": "KICHEKI",
	"common_language_danish": "KIDENMAKI",
	"common_language_dutch": "KIHOLANZI",
	"common_language_english": "KIINGEREZA",
	"common_language_estonian": "KIESTONIA",
	"common_language_filipino": "KIFILIPINO",
	"common_language_finnish": "KIFINI",
	"common_language_french": "KIFARANSA",
	"common_language_german": "KIJERUMANI",
	"common_language_greek": "KIGIRIKI",
	"common_language_hausa": "KIHAUSA",
	"common_language_hebrew": "KIEBRANIA",
	"common_language_hindi": "KIHINDI",
	"common_language_hungarian": "KIHUNGARI",
	"common_language_indonesian": "KIINDONESIA",
	"common_language_irish": "KIAYALANDI",
	"common_language_italian": "KIITALIANO",
	"common_language_japanese": "KIJAPANI",
	"common_language_korean": "KIKOREA",
	"common_language_malay": "KIMALEI",
	"common_language_norwegian": "KINORWE",
	"common_language_persian": "KIAJEMI",
	"common_language_polish": "KIPOLANDI",
	"common_language_portuguese": "KIRENO",
	"common_language_russian": "KIRUSI",
	"common_language_sinhala": "KISINHALA",
	"common_language_slovak": "KISLOVAKI",
	"common_language_slovenian": "KISLOVENIA",
	"common_language_spanish": "KIHISPANIA",
	"common_language_swahili": "KISWAHILI",
	"common_language_swedish": "KISWIDI",
	"common_language_thai": "KITHAI",
	"common_language_turkish": "KITURUKI",
	"common_language_urdu": "KIURDU",
	"common_language_vietnamese": "KIVIETINAMU",
	"common_language_yoruba": "KIYORUBA",
	"common_stickers_bulk_mess": "Hutaki kushughulikia faili mwenyewe?",
	"common_stickers_bulk_want": "Unataka zaidi ya vibandiko vichache tu?",
	"common_stickers_bulk_store": "Agiza vibandiko kwa wingi kutoka kwa mchapishaji tunayetumia.",
	"common_stickers_bulk_cheaper": "Kadiri unavyonunua vibandiko vingi, ndivyo bei inavyopungua kwa kila kibandiko.",
	"common_stickers_print_instructions_1": "Unaweza kushiriki kwa kuchapisha vibandiko vyako mwenyewe, popote unapoishi! Bofya lugha yako hapa chini kupakua faili za vibandiko na maelekezo.",
	"common_stickers_print_instructions_2": "Tafadhali kumbuka: vibandiko vyote havipatikani katika lugha zote.",
	"common_stickers_request_language_1": "Huoni lugha yako?",
	"common_stickers_request_language_2": "Jaza fomu hapa chini kuomba faili za vibandiko kwa lugha yako ya ndani.",
	"common_stickers_dimensions": "Vipimo:",
	"common_stickers_type": "Aina:",
	"common_stickers_material": "Nyenzo:",
	"common_stickers_where_to_print": "Mahali pa kuchapisha:",
	"common_stickers_type_die_cut": "kibandiko kilichokatwa",
	"common_stickers_material_vinyl": "vibandiko vya vinyl kwa matumizi ya nje",
	"common_stickers_printer": "Tunatumia StickerMule.com lakini unaweza kutumia kampuni yoyote ya vibandiko.",
	"common_stickers_dimensions_danger": "11.4544 cm x 8.382 cm (4.51 in x 3.3 in)",
	"common_stickers_dimensions_warning": "10.414 cm x 9.2202 cm (4.1 in x 3.63 in)",
	"common_stickers_dimensions_caution": "12.0142 cm x 7.9502 cm (4.73 in x 3.13 in)",
	"common_stickers_dimensions_fix": "11.3792 cm x 6.8072 cm (4.48 in x 2.68 in)",
	"common_stickers_dimensions_study": "14.605 cm x 5.1308 cm (5.75 in x 2.02 in)",
	"common_stickers_dimensions_bdhi": "21.59 cm x 4.6482 cm (8.5 in x 1.83 in)",
	"common_stickers_dimensions_cure_v2": "6.35 cm x 12.7 cm (2.5 in x 5 in)",
	"common_stickers_dimensions_got_inflation": "7.9248 cm x 14.605 cm (3.12 in x 5.75 in)",
	"common_stickers_dimensions_what_if": "21.7932 cm x 7.62 cm (8.58 in x 3 in)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20.995 cm x 6.35 cm (8.25 in x 2.5 in)",
	"common_nostr_join": "JIUNGE NA NOSTR SASA",
	"common_nostr_protocol_header": "Itifaki, si jukwaa",
	"common_nostr_protocol_c1": "Nostr ni itifaki mpya inayokuruhusu kuwasiliana mtandaoni bila hofu ya udhibiti, kufutwa, au kupunguzwa uonekano",
	"common_nostr_protocol_c2": "Majukwaa kama Twitter na Facebook yanadhibitiwa na kampuni moja, lakini hakuna anayedhibiti itifaki ya Nostr.",
	"common_nostr_freedom_header": "Uhuru wa kuhamia",
	"common_nostr_freedom_c1": "Nostr inafanana na barua pepe. Hakuna anayedhibiti itifaki ya barua pepe, na mtu yeyote anaweza kujenga programu (kama Gmail, Hotmail, nk.) juu yake.",
	"common_nostr_freedom_c2": "Hakuna anayedhibiti itifaki ya Nostr, na mtu yeyote anaweza kujenga programu (kama Damus, Amethyst, nk.) juu yake.",
	"common_nostr_freedom_c3": "Usipopenda jinsi programu fulani inavyofanya kazi, unaweza kuhamisha akaunti yako ya Nostr kwa programu nyingine bila kupoteza wafuasi au maudhui yako.",
	"common_nostr_bitcoin_header": "Bitcoin imejumuishwa ndani",
	"common_nostr_bitcoin_c1": "Bitcoin imejumuishwa asili katika itifaki ya Nostr. Ukiona maudhui unayopenda, unaweza kutuma bitcoin kwa mtu kwa urahisi kama shukrani!",
	"common_nostr_bitcoin_c2": "Kwenye majukwaa ya kati kama Twitter na Facebook, kampuni ya kati inapata pesa kutoka kwa maudhui yako. Lakini kwenye itifaki za wazi kama Nostr, wewe unapata pesa kutoka kwa maudhui yako.",
	"common_nostr_download_client": "PAKUA PROGRAMU YA BURE KUJIUNGE NA NOSTR",
	"common_nostr_iphone_clients": "Programu za iPhone",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "Programu ya iPhone",
	"common_nostr_first_client": "Programu inayopendekezwa ya kwanza",
	"common_nostr_wallet_built_in": "Pochi ya zap ya Bitcoin imejumuishwa",
	"common_nostr_download_now": "PAKUA SASA",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "Muonekano unaojulikana",
	"common_nostr_separate_wallet": "Inahitaji pochi tofauti ya bitcoin",
	"common_nostr_android_clients": "Programu za Android",
	"common_nostr_android_app": "Programu ya Android",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "Vipengele vingi",
	"common_nostr_browser_clients": "Programu za Kivinjari",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "Programu ya Wavuti",
	"common_nostr_simple": "Rahisi sana",
	"common_nostr_test": "Njia rahisi ya kujaribu Nostr kwa kutumia akaunti ya majaribio",
	"common_nostr_view_client": "TAZAMA PROGRAMU",
	"common_kit_printer": "Tunapendekeza VistaPrint.com kuchapisha vijitabu vyako vya Kifurushi cha Biashara ya Bitcoin. Hata hivyo, unaweza kutumia kampuni yoyote ya uchapishaji mradi tu wanaweza kuchapisha pande mbili.",
	"common_kit_link_to_print": "Kiungo cha kuchapisha:",
	"common_kit_fold": "Kukunja:",
	"common_kit_fold_trifold": "Kukunja mara tatu",
	"common_kit_unfolded_size": "Ukubwa usiokunjiwa:",
	"common_kit_unfolded_size_bbk": "Ukubwa wa barua (8.5 in x 11 in)",
	"common_kit_paper_thickness": "Unene wa karatasi:",
	"common_kit_paper_thickness_standard": "Kawaida",
	"common_kit_paper_stock": "Aina ya karatasi:",
	"common_kit_paper_stock_glossy": "Yenye kung'aa",
	"common_kit_exterior_print_file": "Faili ya uchapishaji wa nje:",
	"common_kit_interior_print_file": "Faili ya uchapishaji wa ndani:",
	"common_kit_cta_header": "Fanya biashara ya ndani ikubali Bitcoin",
	"common_biz_learn": "Jifunze kwa nini Bitcoin ni nzuri kwa biashara",
	"common_biz_wallets": "Pata pochi ya Bitcoin kukubali malipo ya Bitcoin",
	"common_biz_maps": "Orodheshwa kwenye ramani za wafanyabiashara wa Bitcoin",
	"common_biz_stickers": "Vibandiko vya 'Bitcoin Inakubaliwa Hapa' bure",
	"common_biz_rewards": "Zawadi za Bitcoin",
	"common_biz_accounting": "Mwongozo wa Uhasibu wa Bitcoin",
	"common_biz_faq": "Maswali Yanayoulizwa Mara kwa Mara",
	"common_biz_kit": "Chapisha Kifurushi chako cha Biashara ya Bitcoin",
	"common_biz_accept_bitcoin_payments": "KUBALI MALIPO YA BITCOIN",
	"common_biz_ready": "UKO TAYARI KUKUBALI BITCOIN KATIKA BIASHARA YAKO?",
	"common_biz_more": "RASILIMALI ZAIDI ZA BIASHARA",
	"common_self_custody": "UHIFADHI WA KIBINAFSI",
	"common_not_your_keys": "SI FUNGUO ZAKO",
	"common_cold_wallet": "POCHI BARIDI",
	"common_hot_wallet": "POCHI MOTO",
	"common_sticker_files_mission_1": "Dhamira yetu ni kukusaidia kueneza Bitcoin zaidi kwa kuweka vibandiko vya Bitcoin hadharani. Vibandiko vyetu vyote vina misimbo ya QR inayounganisha na kurasa za elimu kuhusu",
	"common_sticker_files_mission_2": "Bitcoin",
	"common_sticker_files_mission_3": "mfumuko wa bei",
	"common_sticker_files_mission_4": "Ikiwa unaishi Marekani au Kanada, unaweza",
	"common_sticker_files_mission_5": "kuomba kifurushi cha vibandiko vya Kiingereza bure",
	"common_published_by": "Imechapishwa na",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "Elimu ya Bitcoin tangu 2022",
	"common_publisher_open_source": "Mradi wa chanzo huria",
	"common_reviewed_accuracy": "\u2713 Imekaguliwa kwa usahihi: 2026",
	"common_footer_tagline": "Kuharakisha kupitishwa kwa bitcoin kupitia elimu.",
	"common_footer_contribute": "Changia",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "Vyanzo"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! Created Swahili common.json.');
