/**
 * Creates Swahili (sw) translation files for remaining content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'sw';
const today = '2026-04-03';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "Bitcoin Haina Mikimbilio ya Benki",
	"bank_runs_header": "BITCOIN HAINA MIKIMBILIO YA BENKI",
	"bank_runs_header_2": "LAKINI BENKI YAKO INAWEZA KUWA NAYO",
	"bank_runs_what": "MIKIMBILIO YA BENKI NI NINI?",
	"bank_runs_what_content_1": "Mikimbilio ya benki hutokea wakati watu wengi sana wanajaribu kutoa pesa zao kutoka benki kwa wakati mmoja.",
	"bank_runs_what_content_2": "Ikiwa benki hazina pesa za kutosha zinazoweza kupatikana kulingana na utolewa, zinaweza kuanguka kabisa wakati mikimbilio ya benki inapotokea.",
	"bank_runs_how": "MIKIMBILIO YA BENKI HUTOKEA VIPI?",
	"bank_runs_how_content_1": "Mfumo wetu wa benki ni wa 'akiba ya sehemu' ikimaanisha benki haishikilii pesa yako tu katika kabati na kusubiri uitumie au uitoe.",
	"bank_runs_how_content_2": "Badala yake, benki yako inachukua pesa yako na kuikopesha au kuiwekeza. Hii inaweza kufunga pesa yako kwa muda mrefu, ingawa benki inakuahidi uwezo wa kutoa pesa yako wakati wowote.",
	"bank_runs_how_content_3": "Je, kinatokea nini ukijaribu kutoa pesa yako baada ya benki kuishakuikopesha au kuiwekeza?",
	"bank_runs_how_content_4": "Si shida ikiwa wewe peke yako unajaribu kutoa. Benki itachukua tu pesa ya mtu mwingine na kukupa badala yake. Lakini kinatokea nini watu wengi sana wanajaribu kutoa kwa wakati mmoja?",
	"bank_runs_how_content_5": "Watu wengi nchini Marekani waligundua wakati kulikuwa na mikimbilio ya Silicon Valley Bank mnamo Machi wa 2023.",
	"bank_runs_how_content_6": "Benki ilikuwa imewekeza pesa za wateja wao katika dhamana za serikali ambazo zilifungwa kwa hadi miaka 30. Mbaya zaidi, thamani ya dhamana hizo ilikuwa imeshuka sana hivi karibuni, kwa hivyo Silicon Valley Bank haikuweza kuuza tu dhamana kupata pesa za wanaoweka amana. Walikuwa wamefilisika. Hawakuwa na pesa za kutosha kulingana na utolewa wa wanaoweka amana wao.",
	"bank_runs_how_content_7": "Kadiri watu wengi zaidi walivyogundua, shida ilizidi kuwa mbaya. Maombi zaidi ya kutoa yalikuja, lakini mengi hayakushughulikiwa. Maelfu ya biashara ziligundua hawataweza kulipa wafanyakazi wao kutokana na benki kushindwa.",
	"bank_runs_how_content_8": "FDIC iliingilia na kukubaliana kuwalipa wanaoweka amana wote. Shida imetatuliwa? Si kabisa...",
	"bank_runs_fdic": "JE, BIMA YA FDIC INALINDA PESA YANGU?",
	"bank_runs_fdic_content_1": "Bima ya FDIC imeundwa kulinda wanaoweka amana wa benki iwapo benki itashindwa. Amana zimebimishwa hadi $250,000 kwa kila mweka amana. Inaonekana vizuri, sivyo?",
	"bank_runs_fdic_content_2": "Si kabisa. Ikiwa benki itashindwa, FDIC inapata pesa wapi? Wana mfuko wa bima wenye dola bilioni 125.",
	"bank_runs_fdic_content_3": "Hiyo inaonekana kama pesa nyingi hadi ukilinganisha na kiasi cha amana wanazobima: karibu trilioni 10 au bilioni 10,000 za dola.",
	"bank_runs_fdic_content_4": "FDIC hata inaonyesha kwenye tovuti yao kuwa wana pesa za kutosha tu katika mfuko wao wa bima kufidia zaidi kidogo ya 1% ya amana.",
	"bank_runs_fdic_content_5": "Iwapo benki itashindwa na kuzidi mfuko wa bima wa FDIC, inawezekana (lakini si uhakika) kuwa serikali ya Marekani itachapisha pesa kuwalipa wanaoweka amana wote.",
	"bank_runs_fdic_content_6": "Lakini kuchapisha pesa kunasababisha mfumuko wa bei, kwa hivyo si suluhisho zuri.",
	"bank_runs_safe": "JE, KUNA BENKI AMBAZO HAZITUMII AKIBA YA SEHEMU?",
	"bank_runs_safe_content_1": "Benki zingine zimejaribu kuwa 'benki salama' ambazo hazikopesha au kuwekeza fedha za wanaoweka amana.",
	"bank_runs_safe_content_2": "Ingawa benki hizi salama zingekuwa na hatari ya sifuri ya mikimbilio ya benki, maombi yao yamekataliwa na Benki Kuu ya Marekani. Hii inamaanisha haziwezi kufanya kazi kisheria kama benki.",
	"bank_runs_safe_content_3": "Kwa sababu zimezuiwa kufanya kazi, hakuna benki za sasa ambazo hazitumii akiba ya sehemu.",
	"bank_runs_safe_content_4": "Kwa bahati nzuri, kuna njia ya kujiondoa katika mfumo wa akiba ya sehemu kwa kuwa benki yako mwenyewe. Hapana, hatuongei kuhusu kuficha fedha taslimu chini ya godoro lako.",
	"bank_runs_safe_content_5": "Kuhifadhi kwa fedha taslimu bado iko hatarini kwa mfumuko wa bei.",
	"bank_runs_safe_content_6": "Tunaongea kuhusu Bitcoin: mfumo mpya wa fedha unaokuruhusu kuwa benki yako mwenyewe.",
	"bank_runs_protect": "JE, BITCOIN INAWEZA KUNILINDA DHIDI YA MIKIMBILIO YA BENKI?",
	"bank_runs_protect_content_1": "Ndiyo, Bitcoin ni mfumo kamili wa fedha wa akiba.",
	"bank_runs_protect_content_2": "Mikimbilio ya benki haiwezekani katika Bitcoin mradi tu uitoe Bitcoin yako kwenye pochi yako mwenyewe. Usiache bitcoin yako kwenye soko la kubadilishana au katika kifungashio kama ETF ya Bitcoin.",
	"bank_runs_protect_content_3": "Angalia Mwongozo wetu rahisi wa Pochi ya Bitcoin kujifunza jinsi ya kutoa kwenye pochi yako mwenyewe.",
	"bank_runs_protect_content_4": "Na Bitcoin, hatimaye unaweza kudhibiti pesa yako."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Mwongozo wa Pochi ya Bitcoin",
	"wallets_description": "Kuna pochi nyingi tofauti za Bitcoin zinazotofautiana kwa njia muhimu. Unaweza kuamua kama pochi inafaa kwako kwa kuuliza maswali haya rahisi.",
	"wallets_header": "JINSI YA KUHIFADHI BITCOIN YAKO KWA USALAMA",
	"wallets_s1_c1": "Pochi za Bitcoin zinafanya kazi pamoja, kwa hivyo unaweza kutuma Bitcoin kwa mtu yeyote bila kujali wanatumia pochi gani.",
	"wallets_s1_c2": "Kuna pochi nyingi tofauti za Bitcoin zinazotofautiana kwa njia muhimu. Unaweza kuamua kama pochi inafaa kwako kwa kuuliza maswali haya rahisi:",
	"wallets_question_1": "JE, NI POCHI YA UHIFADHI WA KIBINAFSI?",
	"wallets_s2_c1": "Mojawapo ya uvumbuzi wa Bitcoin ni uwezo wa kuihifadhi bila kutegemea mhifadhiaji, kama benki.",
	"wallets_s2_c2": "Ukishikilia bitcoin kwenye soko la kubadilishana au katika ETF, unapoteza faida za uhuru za bitcoin.",
	"wallets_s2_c3": "Pochi za uhifadhi wa kibinafsi zinafungua nguvu kamili ya Bitcoin: pesa ya uhuru.",
	"wallets_s2_c4": "Na pochi ya uhifadhi wa kibinafsi, wewe ndiye pekee mwenye uwezo wa kutumia au kuhamisha pesa yako. Hakuna anayeweza kukuzuia kutuma au kupokea pesa yako unapotumia pochi ya uhifadhi wa kibinafsi.",
	"wallets_s2_c5": "Pochi za uhifadhi wa kibinafsi pia huitwa pochi zisizo za mhifadhiaji.",
	"wallets_s3_c1": "Pochi za mhifadhiaji ni pochi ambapo wewe haudhibiti pesa yako.",
	"wallets_s3_c2": "Pochi hizi zinafanana zaidi na mfumo wa benki ambapo lazima uamini mhusika wa tatu kukupa ufikiaji wa pesa yako. Ikiwa Bitcoin yako ipo kwenye soko la kubadilishana, unatumia pochi ya mhifadhiaji.",
	"wallets_s3_c3": "Ikiwa umenunua ETF ya Bitcoin, unatumia pochi ya mhifadhiaji ambayo haikuruhusu kutoa kwa uhifadhi wa kibinafsi.",
	"wallets_s3_c4": "Pochi za mhifadhiaji zinaweza kuonekana rahisi, lakini mhifadhiaji ana uwezo wa kiufundi wa kuiba fedha zote za watumiaji wakati wowote.",
	"wallets_s3_c5": "Si funguo zako, si sarafu zako!",
	"wallets_question_2": "JE, NI MOTO AU BARIDI?",
	"wallets_s4_c1": "Pochi baridi huhifadhi funguo za Bitcoin yako kwa njia ambayo hazijawahi kufichuliwa kwa mtandao.",
	"wallets_s4_c2": "Hii inapunguza sana njia za mashambulizi ambazo mwizi anaweza kutumia kujaribu kuiba Bitcoin yako, na ni bora kutumia kwa kiasi kikubwa cha Bitcoin ambayo huhitaji kuihamisha mara kwa mara.",
	"wallets_s4_c3": "Unaweza kufikiria pochi baridi kama akaunti ya akiba ya muda mrefu, pia inajulikana kama uhifadhi baridi.",
	"wallets_s5_c1": "Pochi moto huhifadhi funguo za Bitcoin yako kwenye kifaa kilichounganishwa na mtandao, kama simu yako.",
	"wallets_s5_c2": "Pochi moto kwa ujumla zinachukuliwa kuwa salama, lakini zinaweza kuwa na udhaifu zaidi wa usalama kuliko pochi baridi.",
	"wallets_s5_c3": "Unaweza kufikiria pochi moto kama unavyofikiria pochi halisi. Hungekaa akiba yako yote katika pochi yako, lakini ungehifadhi pesa fulani za kutumia.",
	"wallets_s5_c4": "Pochi moto zinafanya iwe rahisi zaidi kutumia Bitcoin yako bila kutoa akiba yako yote kutoka uhifadhi baridi.",
	"wallets_question_3": "NITAHIFADHI VIPI MANENO YANGU YA UREJESHAJI?",
	"wallets_s6_c1": "Unapoanzisha pochi yako ya Bitcoin, kifaa chako kitatengeneza maneno ya urejeshaji. Maneno haya ya urejeshaji (pia yanaitwa maneno ya mbegu) yana maneno 12 au 24.",
	"wallets_s6_c2": "Ukipoteza ufikiaji wa pochi yako au kifaa chako kikiacha kufanya kazi, unaweza kuingiza maneno haya ya urejeshaji kwenye pochi mpya kupata ufikiaji wa Bitcoin yako tena.",
	"wallets_s6_c3": "Pochi nyingi zinajumuisha karatasi ya kuandika maneno yako ya urejeshaji, lakini watu wengi wanapendelea kuhifadhi maneno haya kwenye chuma badala yake. Hii inafanya iwe vigumu zaidi kupoteza maneno yako ya urejeshaji iwapo maafa ya asili kama moto au mafuriko.",
	"wallets_s6_c4": "Jameson Lopp amejaribu vifurushi 70 vya kuhifadhi kwa chuma kukusaidia kuchagua kinachofaa kwako.",
	"wallets_s6_c5": "Angalia mwongozo wa Jameson wa kuhifadhi Bitcoin kwa chuma hapa.",
	"wallets_s6_c6": "Au endelea kusogeza kuchunguza chaguzi za pochi za Bitcoin.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "Unatafuta Mwongozo wetu wa Pochi ya Lightning?",
	"wallets_starter_wallet": "Pochi nzuri ya kuanzia",
	"wallets_mobile_app": "Programu ya simu",
	"wallets_2fa_support": "Msaada wa 2FA",
	"wallets_air_gap_mode": "Hali ya hewa-pengo",
	"wallets_air_gap_camera": "Hali ya hewa-pengo + kamera",
	"wallets_bitcoin_only": "Bitcoin pekee",
	"wallets_security_features": "Vipengele vingi vya usalama",
	"wallets_free": "Bure 100%",
	"wallets_coldcard_mk5_costs": "Inagharimu $189",
	"wallets_coldcard_q_costs": "Inagharimu $289",
	"wallets_blockstream_jade_costs": "Inagharimu $79",
	"wallets_foundation_passport_costs": "Inagharimu $199",
	"wallets_seedsigner_costs": "Vipengele vinagharimu $50",
	"wallets_very_affordable": "Bei nafuu sana",
	"wallets_pair_with_phone": "Unganisha na simu yako",
	"wallets_battery": "Betri inayochajika",
	"wallets_build_your_own": "Jitengenezee mwenyewe",
	"wallets_qwerty_keyboard": "Kibodi kamili ya QWERTY",
	"wallets_qr_scanner": "Skana ya msimbo wa QR"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "Jinsi ya Kununua Bitcoin - Mwongozo wa Hatua kwa Hatua",
	"buy_header": "JINSI YA KUNUNUA BITCOIN",
	"buy_intro_c1": "Kununua Bitcoin kwa mara ya kwanza kunaweza kuonekana kuogopesha, lakini ni rahisi sana unapovigawanya katika hatua.",
	"buy_intro_c2": "Mwongozo huu utakuongoza kupitia mchakato wa kununua Bitcoin kwa usalama na kuihifadhi katika pochi yako mwenyewe.",
	"buy_step_1_header": "HATUA YA 1: CHAGUA NCHI YAKO",
	"buy_step_1_description": "Nchi tofauti zina chaguzi tofauti za kununulia Bitcoin. Chagua nchi yako kuona chaguzi bora zaidi kwako.",
	"buy_search_countries": "Tafuta nchi yako",
	"buy_country_united_states": "Marekani",
	"buy_country_australia": "Australia",
	"buy_country_austria": "Austria",
	"buy_country_belgium": "Ubelgiji",
	"buy_country_brazil": "Brazil",
	"buy_country_canada": "Kanada",
	"buy_country_france": "Ufaransa",
	"buy_country_germany": "Ujerumani",
	"buy_country_ireland": "Ayalandi",
	"buy_country_italy": "Italia",
	"buy_country_netherlands": "Uholanzi",
	"buy_country_new_zealand": "New Zealand",
	"buy_country_spain": "Hispania",
	"buy_country_united_kingdom": "Uingereza",
	"buy_country_argentina": "Argentina",
	"buy_country_chile": "Chile",
	"buy_country_colombia": "Kolombia",
	"buy_country_costa_rica": "Kosta Rika",
	"buy_country_czech_republic": "Jamhuri ya Cheki",
	"buy_country_denmark": "Denmaki",
	"buy_country_el_salvador": "El Salvador",
	"buy_country_estonia": "Estonia",
	"buy_country_finland": "Ufini",
	"buy_country_greece": "Ugiriki",
	"buy_country_guatemala": "Guatemala",
	"buy_country_hong_kong": "Hong Kong",
	"buy_country_hungary": "Hungaria",
	"buy_country_iceland": "Aisilandi",
	"buy_country_india": "India",
	"buy_country_israel": "Israeli",
	"buy_country_japan": "Japani",
	"buy_country_latvia": "Latvia",
	"buy_country_lithuania": "Lithuania",
	"buy_country_luxembourg": "Luxemburg",
	"buy_country_malta": "Malta",
	"buy_country_mexico": "Meksiko",
	"buy_country_norway": "Norwe",
	"buy_country_panama": "Panama",
	"buy_country_poland": "Polandi",
	"buy_country_portugal": "Ureno",
	"buy_country_romania": "Romania",
	"buy_country_singapore": "Singapuri",
	"buy_country_slovakia": "Slovakia",
	"buy_country_slovenia": "Slovenia",
	"buy_country_south_africa": "Afrika Kusini",
	"buy_country_south_korea": "Korea Kusini",
	"buy_country_sweden": "Uswidi",
	"buy_country_switzerland": "Uswisi",
	"buy_country_thailand": "Thailand",
	"buy_country_turkey": "Uturuki",
	"buy_country_ukraine": "Ukraine",
	"buy_country_uruguay": "Uruguay",
	"buy_step_2_header": "HATUA YA 2: CHAGUA NJIA YAKO YA MALIPO",
	"buy_step_2_description": "Kuna njia mbili kuu za kununua Bitcoin: kwa uhamisho wa benki au kwa fedha taslimu. Kila moja ina faida tofauti.",
	"buy_method_bank_transfer": "UHAMISHO WA BENKI",
	"buy_method_bank_fast": "Haraka na Rahisi",
	"buy_method_bank_less_private": "Faragha Ndogo",
	"buy_method_bank_description": "Uhamisho wa benki ni njia ya kawaida zaidi ya kununua Bitcoin. Ni haraka, rahisi, na kwa kawaida una ada ndogo.",
	"buy_method_choose_bank": "Chagua Uhamisho wa Benki",
	"buy_method_cash": "FEDHA TASLIMU",
	"buy_method_cash_private": "Faragha Zaidi",
	"buy_method_cash_limited": "Chaguzi Chache",
	"buy_method_cash_description": "Ununuzi kwa fedha taslimu unatoa faragha zaidi lakini una chaguzi chache na inaweza kuhitaji kukutana na mtu ana kwa ana au kutumia ATM ya Bitcoin.",
	"buy_method_choose_cash": "Chagua Fedha Taslimu",
	"buy_step_3_header": "HATUA YA 3: CHAGUZI ZA KUNUNUA",
	"buy_step_3_description": "Hapa kuna chaguzi bora za kununulia Bitcoin kwa nchi na njia yako ya malipo:",
	"buy_platform_recommended": "INASHAURIWA",
	"buy_platform_strike_description": "Strike ni njia ya haraka na rahisi zaidi ya kununua Bitcoin kwa ada ndogo na msaada wa papo hapo wa Mtandao wa Lightning.",
	"buy_platform_swan_description": "Swan Bitcoin inabobea katika huduma za Bitcoin pekee na wastani wa gharama za dola na rasilimali za elimu.",
	"buy_platform_river_description": "River inatoa ununuzi wa Bitcoin, uchimbaji, na huduma za uhifadhi na kuzingatia elimu na usalama.",
	"buy_platform_coinsquare_description": "Coinsquare ni soko la kubadilishana Bitcoin la Kanada lenye uzingatiaji mkali wa udhibiti na msaada wa wateja.",
	"buy_platform_kraken_description": "Kraken ni soko lililoimarishwa la kubadilishana Bitcoin lenye vipengele vya biashara vya hali ya juu na usalama mkali.",
	"buy_platform_atm_description": "ATM za Bitcoin zinakuruhusu kununua Bitcoin kwa fedha taslimu papo hapo. Pata moja karibu nawe ukitumia Coin ATM Radar.",
	"buy_platform_bisq_description": "Bisq ni soko la kubadilishana la rika kwa rika lililogatuliwa linaruhusu biashara ya Bitcoin ya kibinafsi bila KYC.",
	"buy_platform_feature_instant": "Ununuzi wa papo hapo",
	"buy_platform_feature_low_fees": "Ada ndogo",
	"buy_platform_feature_lightning": "Mtandao wa Lightning",
	"buy_platform_feature_dca": "Wastani wa gharama za dola",
	"buy_platform_feature_education": "Rasilimali za elimu",
	"buy_platform_feature_withdrawal": "Kutoa kwa urahisi",
	"buy_platform_feature_mining": "Uchimbaji wa Bitcoin",
	"buy_platform_feature_custody": "Huduma za uhifadhi",
	"buy_platform_feature_canadian": "Inalenga Kanada",
	"buy_platform_feature_regulated": "Soko lililosimamiwa",
	"buy_platform_feature_support": "Msaada wa wateja",
	"buy_platform_feature_established": "Jukwaa lililoimarishwa",
	"buy_platform_feature_security": "Usalama mkali",
	"buy_platform_feature_advanced": "Vipengele vya hali ya juu",
	"buy_platform_feature_cash": "Ununuzi kwa fedha taslimu",
	"buy_platform_feature_anonymous": "Isiyo na jina zaidi",
	"buy_platform_feature_p2p": "Rika kwa rika",
	"buy_platform_feature_private": "Biashara ya faragha",
	"buy_platform_feature_decentralized": "Iliyogatuliwa",
	"buy_platform_relai_description": "Relai ni programu ya Bitcoin pekee ya Uswisi yenye pochi ya uhifadhi wa kibinafsi, vipengele vya uwekezaji otomatiki, na ada ndogo kwa watumiaji wa Ulaya.",
	"buy_platform_feature_bitcoin_only": "Bitcoin pekee",
	"buy_platform_feature_self_custody": "Pochi ya uhifadhi wa kibinafsi",
	"buy_platform_feature_auto_invest": "Mipango ya uwekezaji otomatiki",
	"buy_platform_feature_european": "Inalenga Ulaya",
	"buy_step_4_header": "HATUA YA 4: HIFADHI BITCOIN YAKO KWA USALAMA",
	"buy_step_4_c1": "Baada ya kununua Bitcoin, hatua muhimu zaidi ni kuihamisha kwenye pochi yako mwenyewe ambapo unadhibiti funguo za kibinafsi.",
	"buy_step_4_c2": "Kuacha Bitcoin kwenye soko la kubadilishana ni hatari kwa sababu wewe kweli humiliki Bitcoin - soko la kubadilishana ndiyo linalomiliki.",
	"buy_step_4_c3": "Unapodhibiti funguo zako za kibinafsi, una umiliki wa kweli wa Bitcoin yako na hakuna anayeweza kuichukua kutoka kwako.",
	"buy_step_4_c4": "Jifunze jinsi ya kuchagua pochi sahihi ya Bitcoin kwa mahitaji yako:",
	"buy_cta_wallets": "Angalia Mwongozo Wetu wa Pochi ya Bitcoin"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Mwongozo wa Pochi ya Lightning ya Bitcoin",
	"lightning_description": "Pochi za Lightning zinakuwezesha kutuma Bitcoin haraka na kwa bei nafuu huku ukidumisha uhuru wako wa kibinafsi.",
	"lightning_header": "MWONGOZO WA POCHI YA LIGHTNING",
	"lightning_s1_c1": "Lightning inakuwezesha kutuma malipo ya Bitcoin haraka na kwa bei nafuu.",
	"lightning_s1_c2": "Ni muhimu kujua kwamba kutumia Lightning kuna maelewano. Kwa kubadilishana na malipo ya haraka, ya bei nafuu ya Bitcoin, mara nyingi unaachia usalama fulani.",
	"lightning_s1_c3": "Kwa ujumla, Lightning inapaswa kutumika na kiasi kidogo cha bitcoin pekee. Unapaswa kuhifadhi kiasi kikubwa cha bitcoin kwenye pochi ya vifaa tu.",
	"lightning_s1_c4": "Angalia Mwongozo wetu wa Pochi ya Vifaa kwa maelezo zaidi.",
	"lightning_s1_c5": "Pochi zote za Lightning si sawa. Unaweza kuamua pochi gani ina maelewano sahihi kwako kwa kuuliza swali moja rahisi:",
	"lightning_question_1": "USAWA GANI WA MAELEWANO NI SAHIHI KWANGU?",
	"lightning_s2_c1": "Mojawapo ya uvumbuzi wa Bitcoin ni uwezo wa kuihifadhi bila kutegemea mhifadhiaji, kama benki. Pochi za uhifadhi wa kibinafsi zinafungua nguvu kamili ya Bitcoin.",
	"lightning_s2_c2": "Na pochi ya uhifadhi wa kibinafsi, wewe ndiye pekee mwenye uwezo wa kutumia au kuhamisha pesa yako. Hakuna anayeweza kukuzuia, kukudhibiti, au kukuibia unapotumia pochi ya uhifadhi wa kibinafsi. Hizi pia huitwa pochi zisizo za mhifadhiaji.",
	"lightning_s2_c3": "Njia ya uhuru zaidi ya kutumia Lightning ni kuendesha nodi yako mwenyewe.",
	"lightning_s2_c4": "Mwongozo huu unalenga pochi rahisi za Lightning ambazo hazihitaji nodi yako mwenyewe.",
	"lightning_s2_c5": "Ni muhimu kujua kwamba hata ukitumia pochi ya Lightning isiyo ya mhifadhiaji, bado unaaminisha mtengenezaji wa pochi asitume sasisho la programu la uovu na kuiba fedha zako.",
	"lightning_s3_c1": "Pochi za mhifadhiaji ni pochi ambapo wewe haudhibiti pesa yako.",
	"lightning_s3_c2": "Pochi hizi zinafanana zaidi na mfumo wa benki ambapo lazima uamini mhusika wa tatu kukupa ufikiaji wa pesa yako. Ikiwa Bitcoin yako ipo kwenye soko la kubadilishana, unatumia pochi ya mhifadhiaji.",
	"lightning_s3_c3": "Pochi za mhifadhiaji zinaweza kuonekana rahisi, lakini mhifadhiaji ana uwezo wa kiufundi wa kuiba fedha zote za watumiaji wakati wowote.",
	"lightning_s3_c4": "Watu wengine wanapendelea pochi za Lightning za mhifadhiaji kwa kiasi kidogo cha bitcoin kwa sababu ya urahisi wao wa kutumia. Kumbuka tu: si funguo zako, si sarafu zako!",
	"lightning_question_2": "CHAGUA POCHI YAKO",
	"lightning_s4_c1": "Ukizingatia haya yote, sasa unaweza kuchagua pochi ya Lightning yenye usawa sahihi wa maelewano kwako.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "Vipengele vingi",
	"lightning_mobile_app": "Programu ya simu",
	"lightning_free": "Bure 100%",
	"lightning_merchants": "Nzuri kwa wafanyabiashara",
	"lightning_starter": "Pochi nzuri ya kuanzia",
	"lightning_browser": "Inategemea kivinjari",
	"lightning_custodial": "Pochi kamili ya mhifadhiaji",
	"lightning_cta_hardware": "Unatafuta Mwongozo wetu wa Pochi ya Vifaa ya Bitcoin?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "Vibandiko vya Bitcoin bure kutoka bitcoin.rocks",
	"stickers_description": "Weka kibandiko cha bitcoin hadharani kueneza ufahamu wa Bitcoin kwa watu wanaokuzunguka.",
	"stickers_header": "VIBANDIKO VYA BITCOIN BURE",
	"stickers_choose_header": "CHAGUA KIFURUSHI CHAKO CHA VIBANDIKO",
	"stickers_choose_c1": "Dhamira yetu ni kukusaidia kueneza Bitcoin zaidi kwa kuweka vibandiko vya Bitcoin hadharani. Vibandiko vyetu vyote vina misimbo ya QR inayounganisha na kurasa za elimu kuhusu",
	"stickers_choose_c2": "Bitcoin",
	"stickers_choose_c3": "mfumuko wa bei",
	"stickers_choose_c4": "Chagua kifurushi chako cha vibandiko hapa chini",
	"stickers_text_pack": "KIFURUSHI CHA MAANDISHI",
	"stickers_signs_pack": "KIFURUSHI CHA ALAMA",
	"stickers_instructions_1": "Ingiza anwani yako ya posta na tutakutumia Kifurushi cha Vibandiko vya Bitcoin bure kwa barua! Vibandiko vyako vitatumwa katika bahasha nyeupe.",
	"stickers_instructions_2": "Data ya anwani inafutwa baada ya vibandiko vyako vya bure kutumwa.",
	"stickers_share_header": "SHIRIKI MAHALI PA VIBANDIKO VYAKO",
	"stickers_share_c1": "Shiriki mahali pa vibandiko vyako nasi kwenye Nostr na uone wapi watu wengine wanaweka vibandiko vyao.",
	"stickers_btn_share_on_nostr": "SHIRIKI KWENYE NOSTR",
	"stickers_btn_what_is_nostr": "NOSTR NI NINI?",
	"stickers_flyers_link_before": "Huku ukifanya hivyo, chapisha na bandika ",
	"stickers_flyers_link_text": "vipeperushi vya Bitcoin",
	"stickers_flyers_link_after": " vyako kusaidia kueneza Bitcoin zaidi.",
	"stickers_country_global_print": "Duniani kote - Chapisha vibandiko vyangu mwenyewe",
	"stickers_country_global_order": "Duniani kote - Agiza kwa wingi",
	"placeholder_name_optional": "Jina (si lazima)",
	"placeholder_address_line_1": "Anwani Mstari wa 1",
	"placeholder_address_line_2": "Anwani Mstari wa 2 (si lazima)",
	"placeholder_city": "Jiji",
	"placeholder_state": "Jimbo",
	"placeholder_province": "Mkoa",
	"placeholder_zip_code": "Msimbo wa Posta",
	"placeholder_postal_code": "Msimbo wa Posta",
	"placeholder_language": "Lugha",
	"placeholder_which_stickers": "Vibandiko vipi?",
	"placeholder_email_optional": "Ingiza barua pepe yako ili ujulishwe (si lazima)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "Kadi za Posta za Bitcoin bure kutoka bitcoin.rocks",
	"postcards_description": "Pata Kifurushi cha Kadi za Posta za Bitcoin bure na ushiriki Bitcoin na mtu unayemjua.",
	"postcards_header": "PROGRAMU YA KADI ZA POSTA IMEFUNGWA",
	"postcards_program_closed_message": "Programu yetu ya kadi za posta za Bitcoin bure imeisha. Asante kwa kila mtu aliyeshiriki katika kueneza elimu ya Bitcoin kupitia barua!",
	"postcards_sticker_alternative_header": "PATA VIBANDIKO VYA BITCOIN BURE BADALA YAKE",
	"postcards_sticker_alternative_message": "Endelea kueneza ufahamu wa Bitcoin na programu yetu ya vibandiko bure! Vibandiko vyetu vya Bitcoin vinafaa kwa kushiriki mahali pa umma na vina misimbo ya QR inayounganisha na maudhui ya elimu.",
	"postcards_sticker_cta": "PATA VIBANDIKO BURE",
	"postcards_step_2": "KADI ZA POSTA ZILIKUWA ZINAVYOONEKANA",
	"postcards_instructions_4": "Tulitengeneza kadi hizi za posta kurahisisha kumtambulisha mtu unayemjua kwa Bitcoin! Ongeza tu anwani na stempu na utupe kadi yako ya posta kwenye sanduku la barua.",
	"postcards_instructions_5": "Dhamira yetu ni kuharakisha kupitishwa kwa Bitcoin. Unaweza kusaidia kwa kupata vibandiko bure na kuviweka mahali pa umma!",
	"postcards_instructions_6": "Sisi sote tunajua watu wachache ambao wangeweza kufaidika kwa kujifunza zaidi kuhusu Bitcoin. Shiriki vibandiko vya Bitcoin nao leo!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "Tusaidie kuweka Mabango haya ya Bitcoin kote Amerika!",
	"signs_title": "Mabango ya Bitcoin bure kutoka bitcoin.rocks",
	"signs_choose_header": "ASANTE KWA KUTUSAIDIA KUWEKA MABANGO HAYA YA BITCOIN KOTE AMERIKA!",
	"signs_choose_c1": "Sasa tumemaliza mabango kabisa! Dhamira yetu ni kuharakisha kupitishwa kwa Bitcoin kupitia elimu.",
	"signs_choose_c2": "Wengi wenu mlisaidia kwa kuweka mabango haya ya Bitcoin bure hadharani. Mabango yetu yote yana misimbo ya QR inayounganisha na ukurasa wa elimu kuhusu",
	"signs_choose_c3": "mfumuko wa bei",
	"signs_choose_c4": "Shukrani kwa jumuiya yetu ya ajabu, tulifikia maelfu ya watu na kuwasaidia kuchukua hatua zao za kwanza katika shimo la sungura la Bitcoin.",
	"signs_share_header": "SHIRIKI MAHALI PA MABANGO YAKO",
	"signs_share_c1": "Shiriki picha ya mahali pa bango lako nasi kwenye Nostr na uone wapi watu wengine wanaweka mabango yao.",
	"signs_btn_share_on_nostr": "SHIRIKI KWENYE NOSTR",
	"signs_btn_what_is_nostr": "NOSTR NI NINI?",
	"signs_instructions_1": "Ingiza anwani yako ya posta na tutakutumia sanduku la mabango 10 ya Bitcoin kwa barua!",
	"signs_instructions_2": "Data ya anwani inafutwa baada ya mabango yako ya bure kutumwa."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "Vipeperushi vya Bitcoin bure kutoka bitcoin.rocks",
	"flyers_description": "Chapisha kipeperushi cha Bitcoin nyumbani na ukiweke hadharani kueneza ufahamu wa Bitcoin kwa watu wanaokuzunguka.",
	"flyers_header_1": "CHAPISHA NA BANDIKA",
	"flyers_header_2": "VIPEPERUSHI VYA BITCOIN",
	"flyers_intro_header": "JINSI YA KUCHAPISHA NA KUBANDIKA VIPEPERUSHI HIVI VYA BITCOIN",
	"flyers_intro_c1": "Dhamira yetu ni kukusaidia kueneza Bitcoin zaidi kwa kuweka vipeperushi vya Bitcoin hadharani. Kipeperushi hiki kina msimbo wa QR unaoelekeza kwenye",
	"flyers_intro_c2": "tovuti yetu ya elimu ya Bitcoin.",
	"flyers_intro_c3": "mfumuko wa bei",
	"flyers_intro_c4": "Chapisha kipeperushi hiki nyumbani au dukani la uchapishaji. Kisha, kibandike kwenye bodi za matangazo, nguzo za simu mjini, na maeneo mengine ya umma ambapo watu wanaweza kukiona na kujifunza kuhusu Bitcoin.",
	"flyers_intro_c5": "Huku ukifanya hivyo, omba kifurushi cha",
	"flyers_intro_c6": "vibandiko vya Bitcoin bure",
	"flyers_intro_c7": "kusaidia kueneza Bitcoin zaidi.",
	"flyers_btn_download": "PAKUA KIPEPERUSHI",
	"flyers_btn_print": "CHAPISHA KIPEPERUSHI",
	"flyers_share_header": "SHIRIKI MAHALI PA VIPEPERUSHI VYAKO",
	"flyers_share_c1": "Shiriki mahali pa vipeperushi vyako nasi kwenye Nostr na uone wapi watu wengine wanaweka vipeperushi vyao.",
	"flyers_btn_share_on_nostr": "SHIRIKI KWENYE NOSTR",
	"flyers_btn_what_is_nostr": "NOSTR NI NINI?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "Shiriki na usaidie kueneza Bitcoin",
	"get_involved_description": "Rasilimali zetu za bure zinaifanya iwe rahisi kueneza kupitishwa kwa Bitcoin.",
	"get_involved_header": "SHIRIKI",
	"get_involved_header_2": "ENEZA BITCOIN",
	"get_involved_intro_1": "Inaweza kukatisha tamaa kuishi katika hali ya sasa ya ulimwengu wetu.",
	"get_involved_intro_2": "Pesa yetu imeharibika. Kwa hivyo, sehemu za msingi za jamii zimeharibika pia.",
	"get_involved_intro_3": "Ikiwa tayari uko katika Bitcoin, unajua hisia ya matumaini ambayo Bitcoin inaweza kuleta. Matumaini ya mustakabali mzuri unaowezeshwa na pesa bora.",
	"get_involved_intro_4": "Lakini watu wengi walio karibu nawe hawajui kuhusu Bitcoin. Wanaishi katika ulimwengu huo huo ulioharibika kama wewe, lakini bila mwanga wa matumaini kuwasaidia kupitia giza.",
	"get_involved_intro_5": "Lakini unaweza kusaidia kubadilisha hilo. Tumetengeneza rasilimali kadhaa za bure kurahisisha kueneza matumaini ambayo Bitcoin inaleta kwa watu wanaokuzunguka.",
	"get_involved_sticker_header": "Weka kibandiko hadharani",
	"get_involved_sticker_content_1": "Unaweza kusaidia kuelimisha watu wanaokuzunguka kuhusu Bitcoin bila kulazimika kuwasiliana na mtu yeyote. Weka tu mojawapo ya vibandiko vyetu vya Bitcoin bure hadharani.",
	"get_involved_sticker_content_2": "Mamia ya watu wanaskanisha misimbo ya QR kwenye vibandiko hivi kila mwezi. Vibandiko vya mfumuko wa bei vinaelekeza kwenye ukurasa kuhusu",
	"get_involved_sticker_content_3": "Bitcoin kama suluhisho la mfumuko wa bei.",
	"get_involved_sticker_content_4": "Vibandiko vingine vinaelekeza kwenye ukurasa wetu wa elimu wa nyumbani unaowaonyesha watu jinsi",
	"get_involved_sticker_content_5": "Bitcoin inavyojenga ulimwengu bora.",
	"get_involved_sticker_content_6": "Kwa kuweka vibandiko hivi katika jamii yako mahali ambapo watu wataona, unaweza kusaidia watu wanaokuzunguka kuchukua hatua zao za kwanza katika shimo la sungura la Bitcoin.",
	"get_involved_request_a": "OMBA",
	"get_involved_sticker_pack": "KIFURUSHI CHA VIBANDIKO",
	"get_involved_postcard_header": "Tuma kadi ya posta",
	"get_involved_postcard_content_1": "Unaweza kusaidia kueneza Matumaini ya Bitcoin kwa mtu unayemjua kwa kumtumia mojawapo ya kadi zetu za posta bure.",
	"get_involved_postcard_content_2": "Nyuma ya kila kadi ya posta kuna maelezo ya kuvutia kuhusu Bitcoin pamoja na msimbo wa QR wa kujifunza zaidi.",
	"get_involved_postcard_content_3": "Kwa kumtumia mtu kadi ya posta ya Bitcoin, unaweza kumsaidia kuona Bitcoin kwa njia mpya.",
	"get_involved_postcard_pack": "KIFURUSHI CHA KADI ZA POSTA",
	"get_involved_business_header": "Ingiza biashara",
	"get_involved_business_content_1": "Unataka kusaidia kujenga uchumi wa mzunguko wa Bitcoin? Kifurushi chetu cha Biashara ya Bitcoin kinafanya iwe rahisi kumkaribia mfanyabiashara kuhusu kukubali malipo ya Bitcoin.",
	"get_involved_business_content_2": "Kila kifurushi cha biashara kinajumuisha vipeperushi vinavyoonyesha faida za kukubali malipo ya Bitcoin. Kila kipeperushi kinaelekeza kwa aina mbalimbali za",
	"get_involved_business_content_3": "rasilimali za bure za biashara ya Bitcoin.",
	"get_involved_business_kit": "KIFURUSHI CHA BIASHARA"
});

console.log('\nDone! Created all Swahili content translation files.');
