/**
 * Creates Uzbek (uz) common_uz.json translation file
 */
const fs = require('fs');
const path = require('path');
const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'uz';
const today = '2026-04-11';

const data = {
	"@metadata": { "authors": ["Satoshi"], "last-updated": today, "locale": lang },
	"common_footer_mission_1": "bitcoin.rocks vazifasi ta\u02BClim orqali bitcoinni qabul qilishni tezlashtirishdir.",
	"common_footer_mission_2": "Ushbu ochiq kodli loyihaga qanday hissa qo\u02BBshishni bilib oling.",
	"common_footer_follow_first_half": "Har qanday Nostr klientida",
	"common_footer_follow_second_half": "qidirib bizni Nostr-da kuzating.",
	"common_footer_what_is_nostr": "Nostr nima?",
	"common_footer_about": "Biz haqimizda",
	"common_footer_email_us": "Bizga elektron pochta yuboring:",
	"common_cta_section_get_started": "BITCOIN BILAN",
	"common_cta_section_with_bitcoin": "BOSHLANG",
	"common_cta_section_title_1": "Bitcoin asoslarini o\u02BBrganing",
	"common_cta_section_title_1_alt": "Bitcoin haqida ko\u02BBproq bilib oling",
	"common_cta_section_title_2": "Birinchi Bitcoin hamyoningizni oling",
	"common_cta_section_title_3": "Bitcoin qanday sotib olinadi",
	"common_cta_link_type_email": "ELEKTRON POCHTA",
	"common_cta_link_type_guide": "YO\u02BBRIQNOMA",
	"common_cta_link_type_website": "VEB-SAYT",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "BITCOIN NIMA?",
	"common_what_is_bitcoin_content_1": "Bitcoin ikki narsadir: raqamli pul va to\u02BBlov tarmog\u02BBi. Bitcoin tarmog\u02BBi (to\u02BBlov tarmog\u02BBi) orqali boshqa odamlarga bevosita Bitcoin (raqamli pul) yuborishingiz mumkin.",
	"common_what_is_bitcoin_content_2": "Bitcoin qiymat saqlash va o\u02BBtkazishning tubdan yangi usuli. Oddiy moliya tarmoqlaridan farqli o\u02BBlaroq, Bitcoin tarmog\u02BBi markaziy hokimiyatlar yoki ishonchli boshqaruvchilarsiz ishlashi mumkin. Bu Bitcoinni tarixdagi birinchi ochiq va chegarasiz pul qiladi.",
	"common_what_is_bitcoin_content_3": "Bitcoin boyligingiz ustidan to\u02BBliq mulkchilik beruvchi raqamli pul. Inson tarixida birinchi marta har kim haqiqatan kam bo\u02BBlgan, foydalanish uchun ruxsat talab qilmaydigan va to\u02BBg\u02BBri saqlanganda musodara qilib bo\u02BBlmaydigan aktivga ega bo\u02BBlishi mumkin.",
	"common_what_is_bitcoin_content_4": "Bitcoin dunyoning istalgan joyiga tez va arzon yuborilishi mumkin. Bank kabi vositachi uchinchi tomonga muhtoj emas.",
	"common_what_is_bitcoin_content_5": "Bitcoin har kimga hukumatning o\u02BBg\u02BBirlab olishi yoki pul bosib qadrsizlantirishi xavfisiz boylikni xavfsiz saqlash imkonini beradi.",
	"common_what_is_bitcoin_content_6": "Dunyoning hamma yerida hukumatlar ko\u02BBproq qog\u02BBoz pul bosa oladi, lekin hech kim ko\u02BBproq bitcoin bosa olmaydi.",
	"common_what_is_bitcoin_content_7": "Bitcoinni osonlik bilan o\u02BBz nazoratiga olib, to\u02BBliq nazoratni qo\u02BBlga kiritishingiz mumkin, shunda Bitcoinning barcha kuchiga ega bo\u02BBlasiz.",
	"common_what_is_bitcoin_content_8": "Ilova yuklab olishni bilsangiz, Bitcoinni o\u02BBz nazoratiga olib, boshqa hech kimga ishonmasdan boyligingizni saqlashingiz mumkin.",
	"common_what_is_bitcoin_content_9": "Bitcoin yaxshiroq pul.",
	"common_bitcoin_volatile": "BITCOIN O\u02BBZGARUVCHAN EKANLIGINI ESHITDIM. BU XAVFSIZMI?",
	"common_bitcoin_volatile_content_1": "Qisqa muddatda Bitcoinning valyuta kursi tebranishga moyil. Bu o\u02BBzgaruvchanlik deyiladi.",
	"common_bitcoin_volatile_content_2": "Ammo kundalik ko\u02BBrayotgan o\u02BBzgaruvchanlik uzoq muddatda \u02BByo\u02BBqoladi\u02BB.",
	"common_bitcoin_volatile_content_3": "Bitcoin vaqt o\u02BBtishi bilan tobora kamroq o\u02BBzgaruvchan bo\u02BBlib bormoqda. Ko\u02BBproq odam Bitcoinni uzoq muddatli jamg\u02BBarma hisobi sifatida ishlatgan sari, uning qiymati yanada barqaror bo\u02BBlib bormoqda.",
	"common_bitcoin_volatile_content_4": "Ko\u02BBplab odamlar o\u02BBzgaruvchanlik xavfini kamaytirish va vaqt o\u02BBtishi bilan sotib olish quvvatini saqlashning xavfsiz usuli sifatida ko\u02BBp yillar davomida qiymatlarini Bitcoinda saqlashni tanlaydi.",
	"common_bitcoin_volatile_content_5": "Venesuela, Sudan, Livan, Suriya, Argentina, Turkiya, Braziliya va boshqa ko\u02BBplab mamlakatlarda mahalliy valyutaning qiymati shunchalik tez tushayaptiki, Bitcoin yanada barqaror jamg\u02BBarma usuli sifatida qaralmoqda.",
	"common_bitcoin_afford": "BUTUN BIR BITCOIN SOTIB OLA OLMAYMAN",
	"common_bitcoin_afford_content_1": "Bir dollar 100 sentdan iborat. Bir Bitcoin 100,000,000 (100 million) satoshidan iborat.",
	"common_bitcoin_afford_content_2": "Butun bir bitcoinga ega bo\u02BBlishingiz shart emas. Ko\u02BBpchilik odamlarning faqat satoshisi bor. Satoshilar bitcoinning birliklari. Masalan, 1 butun bitcoin 100,000 $ tursa, 1 $ bilan 1,000 satoshi sotib olasiz!",
	"common_bitcoin_hacked": "BITCOIN HECH QACHON XAKERLIK HUJUMIGA UCHRAGANMI?",
	"common_bitcoin_hacked_content_1": "Internetda yoki yangiliklarда \u02BBBitcoin xakerlik hujumiga uchradi\u02BB iborasini eshitgan bo\u02BBlishingiz mumkin. Ko\u02BBpchilik odamlar bu maqolalarni o\u02BBqib, Bitcoin tarmog\u02BBi xakerlik hujumiga uchragan deb ishonadi. Ammo Bitcoin tarmog\u02BBi hech qachon xakerlik hujumiga uchramagan.",
	"common_bitcoin_hacked_content_2": "Bitcoin tarmog\u02BBi nima? Bitcoin tarmog\u02BBini temir yo\u02BBl relslari deb tasavvur qiling. Bitcoin tarmog\u02BBi relslari ustida yuradigan poezdlar Bitcoin tranzaksiyalaridir.",
	"common_bitcoin_hacked_content_3": "Yangiliklarда Bitcoin xakerligi haqida gapirilganda, aslida saqlovchi (FTX kabi) xakerlik hujumiga uchragan yoki bankrot bo\u02BBlganini o\u02BBqiyapsiz.",
	"common_bitcoin_hacked_content_4": "Saqlovchilar bitcoiningizni siz uchun saqlaydigan kompaniyalardir. Ammo bu xavf tug\u02BBdiradi: kompaniya yomon boshqarganda, o\u02BBg\u02BBirlaganda yoki yopilganda bitcoiningizni yo\u02BBqotasiz.",
	"common_bitcoin_hacked_content_5": "Bu eng so\u02BBnggi marta FTX bilan sodir bo\u02BBldi.",
	"common_bitcoin_hacked_content_6": "Bitcoinini FTX-ga ishonib topshirgan har kim bitcoinini yo\u02BBqotdi. Bitcoinini o\u02BBz nazoratida saqlagan har kim FTX-ning qulashidan umuman ta\u02BCsirlanmadi. O\u02BBz nazoratidagi Bitcoinning kuchi ana shunda: pulingiz ustidan haqiqiy nazorat.",
	"common_bitcoin_hacked_content_7": "Bitcoiningizni birzha yoki ETF kabi o\u02BBramda qoldirish o\u02BBrniga, erkinlikning barcha afzalliklari uchun o\u02BBz hamyoningizda saqlang.",
	"common_bitcoin_hacked_content_8": "Bitcoiningiz o\u02BBz nazoratida bo\u02BBlganda, pulingiz Bitcoin tarmog\u02BBi tomonidan himoyalanadi. Bu dunyodagi eng xavfsiz moliya tarmog\u02BBi.",
	"common_bitcoin_hacked_content_9": "O\u02BBz nazoratida, FTX-dan Sam bitcoiningizni o\u02BBg\u02BBirlay olmaydi.",
	"common_bitcoin_hacked_content_10": "Hukumat ko\u02BBproq bitcoin bosib inflyatsiyaga sabab bo\u02BBla olmaydi.",
	"common_bitcoin_hacked_content_11": "O\u02BBz nazoratidagi Bitcoin, Bitcoin tarmog\u02BBining kuchi tufayli sizning pulingiz.",
	"common_bitcoin_energy": "BITCOIN NIMA UCHUN ENERGIYA SARFLAYDI?",
	"common_bitcoin_energy_content_1": "Bitcoin tarmoqni himoya qilish va pulingizni saqlash uchun energiya sarflaydi.",
	"common_bitcoin_energy_content_2": "Bitcoin sezilarli miqdorda energiya sarflaydi va bu ko\u02BBplab sabablarga ko\u02BBra ajoyib narsa.",
	"common_bitcoin_energy_list_1": "Bitcoinda bank hujumlari bo\u02BBlmaydi.",
	"common_bitcoin_energy_list_2": "Bitcoin, bitcoin qazib olish orqali energiya tarmoqlarini barqarorlashtrishga yordam beradi.",
	"common_bitcoin_energy_list_3": "Bitcoin neft qazib olishdagi chiqindilarni kamaytiradi.",
	"common_bitcoin_energy_list_4": "Bitcoin amerikaliklar har yili Rojdestvo chiroqlari uchun sarflaydigan energiyadan kam sarflaydi.",
	"common_bitcoin_energy_list_5": "Bitcoin Yerdagi eng toza sanoat!",
	"common_cic_intro_1": "Ko\u02BBpchilik odamlar murakkab foizni biladi, lekin juda kam odam murakkab inflyatsiyani biladi.",
	"common_cic_intro_2": "Murakkab inflyatsiya kalkulyatorimiz yordamida maoshingiz vaqt o\u02BBtishi bilan sotib olish quvvatini saqlab qolish uchun qancha oshishi kerakligini oson hisoblashingiz mumkin.",
	"common_cic_intro_3": "Joriy maoshingizni, inflyatsiya darajasini va hisoblashni xohlagan yillar sonini kiriting, kalkulyatorimiz maoshingiz inflyatsiyaga mos kelish uchun qancha bo\u02BBlishi kerakligini ko\u02BBrsatadi.",
	"common_current_salary": "joriy maosh",
	"common_inflation_rate": "inflyatsiya darajasi",
	"common_year": "yil",
	"common_years": "yil",
	"common_result_starting_message": "Yuqoridagi formani to\u02BBldirib, hisoblash tugmasini bosing.",
	"common_error_message": "Xato: Iltimos, barcha 3 ta form maydonini to\u02BBldiring.",
	"common_result_message_1": "Inflyatsiya darajasida",
	"common_result_message_2": "maoshingiz",
	"common_result_message_3": "ga oshishi kerak",
	"common_result_message_in": "ichida",
	"common_result_message_4": "sotib olish quvvatini saqlash uchun.",
	"common_calculate_button_text": "HISOBLASH",
	"common_learn_more": "KO\u02BBPROQ BILIB OLING",
	"common_success": "MUVAFFAQIYAT!",
	"common_choose_your_country": "Mamlakatingizni tanlang",
	"common_country_usa": "AQSh",
	"common_country_canada": "Kanada",
	"common_submit": "YUBORISH",
	"common_language_afrikaans": "AFRIKAANSCHA",
	"common_language_arabic": "ARABCHA",
	"common_language_basque": "BASKCHA",
	"common_language_bulgarian": "BOLGARCHA",
	"common_language_catalan": "KATALANCHA",
	"common_language_chinese": "XITOYCHA",
	"common_language_croatian": "XORVATCHA",
	"common_language_czech": "CHEXCHA",
	"common_language_danish": "DANIYACHA",
	"common_language_dutch": "GOLLANDCHA",
	"common_language_english": "INGLIZCHA",
	"common_language_estonian": "ESTONCHA",
	"common_language_filipino": "FILIPINCHA",
	"common_language_finnish": "FINCHA",
	"common_language_french": "FRANSUZCHA",
	"common_language_german": "NEMISCHA",
	"common_language_greek": "GREKSCHA",
	"common_language_hausa": "HAUSA",
	"common_language_hebrew": "IBRONIYCHA",
	"common_language_hindi": "HINDCHA",
	"common_language_hungarian": "VENGERCHA",
	"common_language_indonesian": "INDONEZCHA",
	"common_language_irish": "IRLANDCHA",
	"common_language_italian": "ITALYANCHA",
	"common_language_japanese": "YAPONCHA",
	"common_language_korean": "KOREYSCHA",
	"common_language_malay": "MALAYCHA",
	"common_language_norwegian": "NORVEGCHA",
	"common_language_persian": "FORSCHA",
	"common_language_polish": "POLYAKCHA",
	"common_language_portuguese": "PORTUGALCHA",
	"common_language_russian": "RUSCHA",
	"common_language_sinhala": "SINGALCHA",
	"common_language_slovak": "SLOVAKCHA",
	"common_language_slovenian": "SLOVENCHA",
	"common_language_spanish": "ISPANCHA",
	"common_language_swahili": "SUAHILICHA",
	"common_language_swedish": "SHVEDCHA",
	"common_language_thai": "TAYCHA",
	"common_language_turkish": "TURKCHA",
	"common_language_urdu": "URDUCHA",
	"common_language_vietnamese": "VYETNAMCHA",
	"common_language_yoruba": "YORUBACHA",
	"common_stickers_bulk_mess": "Fayllar bilan o\u02BBzingiz shug\u02BBullanishni xohlamaysizmi?",
	"common_stickers_bulk_want": "Bir nechta stikerdan ko\u02BBproq xohlaysizmi?",
	"common_stickers_bulk_store": "Biz foydalanadigan matbaadan ommaviy stiker buyurtma bering.",
	"common_stickers_bulk_cheaper": "Qancha ko\u02BBp stiker olsangiz, har bir stiker shuncha arzon bo\u02BBladi.",
	"common_stickers_print_instructions_1": "Qaerda yashasangiz ham, o\u02BBzingizning stikerlaringizni chop etish orqali qatnashishingiz mumkin! Stiker fayllari va ko\u02BBrsatmalarni yuklab olish uchun quyida tilingizni bosing.",
	"common_stickers_print_instructions_2": "Eslatma: barcha stikerlar barcha tillarda mavjud emas.",
	"common_stickers_request_language_1": "Tilingizni ko\u02BBrmayapsizmi?",
	"common_stickers_request_language_2": "Quyidagi formani to\u02BBldirib, o\u02BBz tilingizdagi stiker fayllarini so\u02BBrang.",
	"common_stickers_dimensions": "O\u02BBlchamlari:",
	"common_stickers_type": "Turi:",
	"common_stickers_material": "Material:",
	"common_stickers_where_to_print": "Qaerda chop etiladi:",
	"common_stickers_type_die_cut": "kesilgan stiker",
	"common_stickers_material_vinyl": "tashqi vinil stikerlar",
	"common_stickers_printer": "StickerMule.com dan foydalanamiz, lekin istalgan bosma kompaniyani ham ishlatishingiz mumkin.",
	"common_stickers_dimensions_danger": "11,4544 sm x 8,382 sm (4,51 in x 3,3 in)",
	"common_stickers_dimensions_warning": "10,414 sm x 9,2202 sm (4,1 in x 3,63 in)",
	"common_stickers_dimensions_caution": "12,0142 sm x 7,9502 sm (4,73 in x 3,13 in)",
	"common_stickers_dimensions_fix": "11,3792 sm x 6,8072 sm (4,48 in x 2,68 in)",
	"common_stickers_dimensions_study": "14,605 sm x 5,1308 sm (5,75 in x 2,02 in)",
	"common_stickers_dimensions_bdhi": "21,59 sm x 4,6482 sm (8,5 in x 1,83 in)",
	"common_stickers_dimensions_cure_v2": "6,35 sm x 12,7 sm (2,5 in x 5 in)",
	"common_stickers_dimensions_got_inflation": "7,9248 sm x 14,605 sm (3,12 in x 5,75 in)",
	"common_stickers_dimensions_what_if": "21,7932 sm x 7,62 sm (8,58 in x 3 in)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20,995 sm x 6,35 sm (8,25 in x 2,5 in)",
	"common_nostr_join": "HOZIR NOSTR-GA QO\u02BBSHILING",
	"common_nostr_protocol_header": "Platforma emas, protokol",
	"common_nostr_protocol_c1": "Nostr senzura, o\u02BBchirilish yoki bosim qo\u02BBrquvisiz veb orqali aloqa qilish imkonini beruvchi yangi protokol",
	"common_nostr_protocol_c2": "Twitter va Facebook kabi platformalar bitta kompaniya tomonidan nazorat qilinadi, lekin Nostr protokolini hech kim nazorat qilmaydi.",
	"common_nostr_freedom_header": "Harakat erkinligi",
	"common_nostr_freedom_c1": "Nostr elektron pochtaga o\u02BBxshaydi. Elektron pochta protokolini hech kim nazorat qilmaydi va har kim uning ustida klient (Gmail, Hotmail va h.k.) ishlab chiqishi mumkin.",
	"common_nostr_freedom_c2": "Nostr protokolini hech kim nazorat qilmaydi va har kim uning ustida klient (Damus, Amethyst va h.k.) ishlab chiqishi mumkin.",
	"common_nostr_freedom_c3": "Muayyan klientning ishlash usulini yoqtirmasangiz, Nostr hisobingizni kuzatuvchilaringiz yoki kontentingizni yo\u02BBqotmasdan boshqa klientga muammosiz ko\u02BBchirishingiz mumkin.",
	"common_nostr_bitcoin_header": "Bitcoin o\u02BBrnatilgan",
	"common_nostr_bitcoin_c1": "Bitcoin Nostr protokoliga mahalliy o\u02BBrnatilgan. Yoqqan kontent ko\u02BBrsangiz, rahmat sifatida birovga osonlik bilan bitcoin yuborishingiz mumkin!",
	"common_nostr_bitcoin_c2": "Twitter va Facebook kabi markazlashtirilgan platformalarda markazlashtirilgan kompaniya kontentingizdan pul ishlaydi. Lekin Nostr kabi ochiq protokollarda siz kontentingizdan pul ishlaysiz.",
	"common_nostr_download_client": "BEPUL KLIENT YUKLAB OLING VA NOSTR-GA QO\u02BBSHILING",
	"common_nostr_iphone_clients": "iPhone klientlari",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "iPhone ilovasi",
	"common_nostr_first_client": "Tavsiya etilgan birinchi klient",
	"common_nostr_wallet_built_in": "Zap\u02BBlar uchun o\u02BBrnatilgan Bitcoin hamyoni",
	"common_nostr_download_now": "HOZIR YUKLAB OLING",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "Tanish interfeys",
	"common_nostr_separate_wallet": "Alohida Bitcoin hamyoni talab qilinadi",
	"common_nostr_android_clients": "Android klientlari",
	"common_nostr_android_app": "Android ilovasi",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "Ko\u02BBp sonli xususiyatlar",
	"common_nostr_browser_clients": "Brauzer klientlari",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "Veb klient",
	"common_nostr_simple": "Juda oddiy",
	"common_nostr_test": "Sinov hisobi yordamida Nostr-ni sinab ko\u02BBrishning oson usuli",
	"common_nostr_view_client": "KLIENTNI KO\u02BBRING",
	"common_kit_printer": "O\u02BBzingizning Bitcoin biznes to\u02BBplami broshyuralaringizni chop etish uchun VistaPrint.com ni tavsiya qilamiz. Ammo ikki tomonlama chop etishni qo\u02BBllab-quvvatlaydigan istalgan matbaani ham ishlatishingiz mumkin.",
	"common_kit_link_to_print": "Chop etish havolasi:",
	"common_kit_fold": "Buklama:",
	"common_kit_fold_trifold": "Uchga buklama",
	"common_kit_unfolded_size": "Ochiq hajmi:",
	"common_kit_unfolded_size_bbk": "Letter formati (8,5 in x 11 in)",
	"common_kit_paper_thickness": "Qog\u02BBoz qalinligi:",
	"common_kit_paper_thickness_standard": "Standart",
	"common_kit_paper_stock": "Qog\u02BBoz turi:",
	"common_kit_paper_stock_glossy": "Yaltiroq",
	"common_kit_exterior_print_file": "Tashqi chop fayli:",
	"common_kit_interior_print_file": "Ichki chop fayli:",
	"common_kit_cta_header": "Mahalliy biznesni Bitcoin qabul qilishga ishontiring",
	"common_biz_learn": "Bitcoin biznes uchun nima uchun foydali ekanligini bilib oling",
	"common_biz_wallets": "To\u02BBlov qabul qilish uchun Bitcoin hamyoni oling",
	"common_biz_maps": "Bitcoin savdogar xaritalariga ro\u02BByxatdan o\u02BBting",
	"common_biz_stickers": "Bepul \u02BBBu yerda Bitcoin qabul qilinadi\u02BB stikerlari",
	"common_biz_rewards": "Bitcoin mukofotlari",
	"common_biz_accounting": "Bitcoin buxgalteriya yo\u02BBriqnomasi",
	"common_biz_faq": "Tez-tez beriladigan savollar",
	"common_biz_kit": "Bitcoin biznes to\u02BBplamingizni chop eting",
	"common_biz_accept_bitcoin_payments": "BITCOIN TO\u02BBLOVLARINI QABUL QILING",
	"common_biz_ready": "BIZNESINGIZDA BITCOIN QABUL QILISHGA TAYYORMISIZ?",
	"common_biz_more": "KO\u02BBPROQ BIZNES RESURSLARI",
	"common_self_custody": "O\u02BBZ NAZORATI",
	"common_not_your_keys": "SIZNING KALITLARINGIZ EMAS",
	"common_cold_wallet": "SOVUQ HAMYON",
	"common_hot_wallet": "ISSIQ HAMYON",
	"common_sticker_files_mission_1": "Bizning vazifamiz Bitcoin stikerlarini ommaviy joylarga yopishtirib, ko\u02BBproq odamlarni xabardor qilishga yordam berishdir. Barcha stikerlarimizda quyidagi mavzulardagi ta\u02BClim sahifalariga yo\u02BBnaltiruvchi QR kodlar mavjud:",
	"common_sticker_files_mission_2": "Bitcoin",
	"common_sticker_files_mission_3": "inflyatsiya",
	"common_sticker_files_mission_4": "AQSh yoki Kanadada yashasangiz,",
	"common_sticker_files_mission_5": "bepul inglizcha stiker to\u02BBplami so\u02BBrashingiz mumkin",
	"common_published_by": "Nashr qiluvchi",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "2022-yildan beri Bitcoin ta\u02BClimi",
	"common_publisher_open_source": "Ochiq kodli loyiha",
	"common_reviewed_accuracy": "\u2713 Aniqlik uchun tekshirilgan: 2026",
	"common_footer_tagline": "Ta\u02BClim orqali bitcoinni qabul qilishni tezlashtiramiz.",
	"common_footer_contribute": "Hissa qo\u02BBshing",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "Manbalar"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}\n\nDone! Created common.json.`);
