/**
 * Creates Uzbek (uz) index_uz.json translation file
 */
const fs = require('fs');
const path = require('path');
const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'uz';
const today = '2026-04-11';

const data = {
	"@metadata": { "authors": ["Satoshi"], "last-updated": today, "locale": lang },
	"bitcoin_builds_a_better_world": "Bitcoin yaxshiroq dunyo qurayapti.",
	"home_description": "Bitcoin yaxshiroq dunyo qurayotgan yaxshiroq pul. Bitcoin inson huquqlarini himoya qildi, odamlarni yuqori inflyatsiyadan qutqardi, mahalliy fermerlarni qo\u02BBllab-quvvatladi, neft qazib olishdagi chiqindilarni kamaytirdi va yana ko\u02BBp narsalarni amalga oshirdi.",
	"home_intro": "Bitcoin yaxshiroq dunyo qurayotgan yaxshiroq pul. Bitcoin holatlarni qanday yaxshilayotganini kashf etish uchun quyidagi kategoriyaga bosing yoki aylantirish orqali kashf qilishni boshlang.",
	"home_btn_money": "YAXSHIROQ PUL",
	"home_btn_salary": "MAOSHINGIZ",
	"home_btn_freedom": "ERKINLIK",
	"home_btn_human_rights": "INSON HUQUQLARI",
	"home_btn_equality": "TENGLIK",
	"home_btn_property_rights": "MULKCHILIK HUQUQLARI",
	"home_btn_housing": "UY-JOY",
	"home_btn_business": "BIZNES",
	"home_btn_crowdfunding": "OMMAVIY MOLIYALASHTIRISH",
	"home_btn_energy": "ENERGIYA",
	"home_btn_environment": "ATROF-MUHIT",
	"home_btn_food": "OZIQ-OVQAT",
	"home_btn_art": "SAN\u02BBAT",
	"home_btn_politics": "SIYOSAT",
	"home_btn_war": "URUSH",
	"home_btn_coding": "DASTURLASH",
	"home_btn_networks": "TARMOQLAR",
	"home_btn_payments": "TO\u02BBLOVLAR",
	"home_btn_self_custody": "O\u02BBZ NAZORATI",
	"home_btn_you": "SIZ",
	"home_section_bitcoin_is": "BITCOIN",
	"home_section_bitcoin_and": "BITCOIN VA",
	"home_link_type_website": "VEB-SAYT",
	"home_link_type_video": "VIDEO",
	"home_link_type_article": "MAQOLA",
	"home_link_type_podcast": "PODKAST",
	"home_link_type_business_kit": "BIZNES TO\u02BBPLAMI",
	"home_link_type_data": "MA\u02BCLUMOT",
	"home_link_type_research": "TADQIQOT",
	"home_link_type_story": "HIKOYA",
	"home_link_type_book_excerpt": "KITOB PARCHA",
	"home_link_type_street_art": "KO\u02BBCHA SAN\u02BBATI",
	"home_link_type_outreach": "IJTIMOIY YORDAM",
	"home_link_type_campaign": "KAMPANIYA",
	"home_link_type_software": "DASTURIY TA\u02BCMINOT",
	"home_link_type_hardware": "APPARAT TA\u02BCMINOT",
	"home_link_type_guide": "YO\u02BBRIQNOMA",
	"home_link_type_email": "ELEKTRON POCHTA",
	"home_link_title_inflation": "Bitcoinning inflyatsiyasi yo\u02BBq",
	"home_link_title_bank_runs": "Bitcoinda bank hujumlari bo\u02BBlmaydi",
	"home_link_title_gold": "Bitcoin va Oltin",
	"home_link_title_crypto": "Bitcoin va Kripto",
	"home_link_title_cash": "Bitcoin va Naqd pul",
	"home_link_title_bonds": "Bitcoin va Obligatsiyalar",
	"home_link_title_cbdc": "Bitcoin va CBDC",
	"home_link_title_your_salary_1": "Maoshingiz inflyatsiyaga mos kelishi uchun qancha oshishi kerakligini bilib oling.",
	"home_link_title_freedom_1": "Bitcoin erkinlik uchun nima uchun muhim",
	"home_link_title_freedom_2": "Bitcoin siyosiy bosimdan erkinlik taklif qiladi",
	"home_link_title_human_rights_1": "Bitcoin inson huquqlarini qanday qo\u02BBllab-quvvatlaydi",
	"home_link_title_human_rights_2": "Afrikadagi jimjit Bitcoin inqilobi",
	"home_link_title_human_rights_3": "Bitcoin butun dunyoda inson huquqlarini himoya qilmoqda",
	"home_link_title_equality_1": "Bitcoin janubiy afrikaliklar uchun umid va imkoniyat keltirmoqda",
	"home_link_title_equality_2": "Bitcoin qora tanli amerikaliklar uchun qanday burilish nuqtasi bo\u02BBlishi mumkin",
	"home_link_title_property_rights_1": "Bitcoin mukammal mulkchilik shaklidir",
	"home_link_title_property_rights_2": "Bitcoin va Ko\u02BBchmas mulk",
	"home_link_title_housing_1": "Bitcoin uy-joyni qanday yana arzon qiladi",
	"home_link_title_business_3": "Bitcoin va Aksiyalar",
	"home_link_title_business_1": "Bitcoin biznes uchun nima uchun foydali ekanligini bilib oling",
	"home_link_title_business_2": "Mahalliy biznesni Bitcoin qabul qilishga ishontiring",
	"home_link_title_crowdfunding_1": "Bitcoin bir avlodning eng katta Nigeriya noroziliklarini qanday imkon qildi",
	"home_link_title_crowdfunding_2": "Kanada yuk mashinalari noroziligi GoFundMe ehsonlarni to\u02BBsganidan keyin Bitcoin bilan ehson yig\u02BBmoqda",
	"home_link_title_crowdfunding_3": "Geyser = Bitcoin bilan Ommaviy moliyalashtirish",
	"home_link_title_energy_1": "Bitcoin Texas energiya tarmog\u02BBini qanday barqarorlashtirmoqda",
	"home_link_title_energy_2": "Bitcoin nima uchun energiya sarflaydi?",
	"home_link_title_energy_3": "Bitcoinning energiya sarfi muammo emas. Mana sababi.",
	"home_link_title_energy_4": "Bitcoin qazib olish talab boshqaruvi orqali energiya tarmoqlarini barqarorrlashtirmoqda",
	"home_link_title_energy_5": "Bitcoin konchilari qishloq Afrika jamiyatlariga gidroelektrik energiya keltirmoqda",
	"home_link_title_energy_6": "Bitcoin qayta tiklanadigan energiyani qanday rag\u02BBbatlantirmoqda",
	"home_link_title_environment_1": "Bitcoin qazib olish global metan chiqindilarini qanday kamaytirmoqda",
	"home_link_title_environment_2": "Bitcoin qazib olish milliy bog\u02BBni qanday saqlab qoldi",
	"home_link_title_environment_3": "Bitcoin Yerdagi eng toza sanoat!",
	"home_link_title_environment_4": "Bitcoin qazib olish tabiiy gaz yondirilishi atmosferani ifloslantirishiga yo\u02BBl qo\u02BBymaydi",
	"home_link_title_food_1": "Inflyatsiya oziq-ovqat narxlariga qanday ta\u02BCsir qiladi",
	"home_link_title_food_2": "Fiat pul oziq-ovqat, fermalar va Yerning tuproqiga qanday zarar yetkazmoqda",
	"home_link_title_fine_art": "Bitcoin va Nozik san\u02BBat",
	"home_link_title_art_1": "Bitcoin stiker tashabbusimizga qo\u02BBshiling",
	"home_link_title_art_2": "Tanishingizga Bitcoin otkritla yuboring",
	"home_link_title_art_3": "Bitcoin varaqalarini chop eting va yopishtiring",
	"home_link_title_politics_1": "Bitcoin siyosiy paradoks",
	"home_link_title_politics_2": "Yaxshiroq pulga ovoz berishingiz mumkin",
	"home_link_title_war_1": "Bitcoin cheksiz urushni qanday tugatishi mumkin",
	"home_link_title_war_2": "Bitcoin va faxriylar: tabiiy uyg\u02BBunlik",
	"home_link_title_war_3": "Bitcoin Sudandagi tinch aholiga urushdan qochishda qanday yordam bermoqda",
	"home_link_title_coding_1": "Bitcoinning texnik tomoni haqida interaktiv ta\u02BClim",
	"home_link_title_coding_2": "bitcoinSwitch: har qanday qurilmani Bitcoin qabul qiladigan qilish",
	"home_link_title_coding_3": "Kod yozish orqali Bitcoinning sirlariga sayohat",
	"home_link_title_networks_1": "Bitcoin tarmog\u02BBiga jonli nazar",
	"home_link_title_networks_2": "Bitcoin va Banklar",
	"home_link_title_payments_1": "Bitcoin va Visa",
	"home_link_title_payments_2": "Lightning Network-ga nazar (bir zumda Bitcoin to\u02BBlovlari)",
	"home_link_title_payments_3": "El Salvadorning Bitcoin hamyoni salvadorliklarga remittens to\u02BBlovlarida yiliga 400 million dollar tejash imkonini berishi mumkin",
	"home_link_title_payments_4": "Bir zumda Bitcoin to\u02BBlovlari olish uchun Lightning manzilingizni oling",
	"home_link_title_self_custody_1": "Bitcoiningizni xavfsiz qanday saqlash",
	"home_link_title_self_custody_2": "Bitcoiningizni birzhalardan chiqarish uchun 6 sabab",
	"home_link_title_self_custody_3": "Oltin, Bitcoin va o\u02BBz nazorati",
	"home_link_title_get_started_1": "Bitcoin asoslarini o\u02BBrganing",
	"home_link_title_get_started_2": "Birinchi Bitcoin hamyoningizni oling",
	"home_link_title_get_started_3": "Bitcoin qanday sotib olinadi",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Murakkab Inflyatsiya Kalkulyatori",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}\n\nDone! Created index.json.`);
