/**
 * Creates Czech (cs) index_cs.json translation file
 */
const fs = require('fs');
const path = require('path');
const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'cs';
const today = '2026-04-02';

const data = {
	"@metadata": { "authors": ["Satoshi"], "last-updated": today, "locale": lang },
	"bitcoin_builds_a_better_world": "Bitcoin buduje lepší svět.",
	"home_description": "Bitcoin jsou lepší peníze, které budují lepší svět. Bitcoin chránil lidská práva, zachránil lidi před vysokou inflací, podpořil místní farmáře, snížil emise z těžby ropy a mnoho dalšího.",
	"home_intro": "Bitcoin jsou lepší peníze, které budují lepší svět. Klepněte na kategorii níže a zjistěte, jak Bitcoin věci zlepšuje, nebo prostě scrollujte a prozkoumejte.",
	"home_btn_money": "LEPŠÍ PENÍZE",
	"home_btn_salary": "VÁŠ PLAT",
	"home_btn_freedom": "SVOBODA",
	"home_btn_human_rights": "LIDSKÁ PRÁVA",
	"home_btn_equality": "ROVNOST",
	"home_btn_property_rights": "VLASTNICKÁ PRÁVA",
	"home_btn_housing": "BYDLENÍ",
	"home_btn_business": "PODNIKÁNÍ",
	"home_btn_crowdfunding": "CROWDFUNDING",
	"home_btn_energy": "ENERGIE",
	"home_btn_environment": "ŽIVOTNÍ PROSTŘEDÍ",
	"home_btn_food": "JÍDLO",
	"home_btn_art": "UMĚNÍ",
	"home_btn_politics": "POLITIKA",
	"home_btn_war": "VÁLKA",
	"home_btn_coding": "PROGRAMOVÁNÍ",
	"home_btn_networks": "SÍTĚ",
	"home_btn_payments": "PLATBY",
	"home_btn_self_custody": "VLASTNÍ SPRÁVA",
	"home_btn_you": "VY",
	"home_section_bitcoin_is": "BITCOIN JE",
	"home_section_bitcoin_and": "BITCOIN A",
	"home_link_type_website": "WEB",
	"home_link_type_video": "VIDEO",
	"home_link_type_article": "ČLÁNEK",
	"home_link_type_podcast": "PODCAST",
	"home_link_type_business_kit": "PODNIKATELSKÁ SADA",
	"home_link_type_data": "DATA",
	"home_link_type_research": "VÝZKUM",
	"home_link_type_story": "PŘÍBĚH",
	"home_link_type_book_excerpt": "ÚRYVEK Z KNIHY",
	"home_link_type_street_art": "STREET ART",
	"home_link_type_outreach": "OSVĚTA",
	"home_link_type_campaign": "KAMPAŇ",
	"home_link_type_software": "SOFTWARE",
	"home_link_type_hardware": "HARDWARE",
	"home_link_type_guide": "PRŮVODCE",
	"home_link_type_email": "E-MAIL",
	"home_link_title_inflation": "Bitcoin nemá inflaci",
	"home_link_title_bank_runs": "Bitcoin nemá bankovní runy",
	"home_link_title_gold": "Bitcoin vs Zlato",
	"home_link_title_crypto": "Bitcoin vs Krypto",
	"home_link_title_cash": "Bitcoin vs Hotovost",
	"home_link_title_bonds": "Bitcoin vs Dluhopisy",
	"home_link_title_cbdc": "Bitcoin vs CBDC",
	"home_link_title_your_salary_1": "Zjistěte, o kolik musí vzrůst váš plat, aby udržel krok s inflací.",
	"home_link_title_freedom_1": "Proč Bitcoin záleží pro svobodu",
	"home_link_title_freedom_2": "Bitcoin nabízí svobodu od politického útlaku",
	"home_link_title_human_rights_1": "Jak Bitcoin prosazuje lidská práva",
	"home_link_title_human_rights_2": "Tichá bitcoinová revoluce v Africe",
	"home_link_title_human_rights_3": "Bitcoin chrání lidská práva po celém světě",
	"home_link_title_equality_1": "Bitcoin přináší naději a příležitosti Jihoafričanům",
	"home_link_title_equality_2": "Jak může být Bitcoin průlomem pro černošské Američany",
	"home_link_title_property_rights_1": "Bitcoin je dokonalá forma vlastnictví",
	"home_link_title_property_rights_2": "Bitcoin vs Nemovitosti",
	"home_link_title_housing_1": "Jak Bitcoin znovu zpřístupní bydlení",
	"home_link_title_business_3": "Bitcoin vs Akcie",
	"home_link_title_business_1": "Zjistěte, proč je Bitcoin dobrý pro podnikání",
	"home_link_title_business_2": "Přesvědčte místní firmu, aby přijímala Bitcoin",
	"home_link_title_crowdfunding_1": "Jak Bitcoin podpořil největší nigerijské protesty za generaci",
	"home_link_title_crowdfunding_2": "Kanadský protest řidičů kamionů sbírá peníze v Bitcoinu poté, co GoFundMe zablokoval dary",
	"home_link_title_crowdfunding_3": "Geyser = Crowdfunding s Bitcoinem",
	"home_link_title_energy_1": "Jak Bitcoin stabilizuje texaskou energetickou síť",
	"home_link_title_energy_2": "Proč Bitcoin spotřebovává energii?",
	"home_link_title_energy_3": "Spotřeba energie Bitcoinu není problém. Zde je důvod.",
	"home_link_title_energy_4": "Těžba Bitcoinu stabilizuje energetické sítě prostřednictvím řízení poptávky",
	"home_link_title_energy_5": "Těžaři Bitcoinu přinášejí vodní energii venkovským africkým komunitám",
	"home_link_title_energy_6": "Jak Bitcoin motivuje obnovitelnou energii",
	"home_link_title_environment_1": "Jak těžba Bitcoinu snižuje globální emise metanu",
	"home_link_title_environment_2": "Jak těžba Bitcoinu zachránila národní park",
	"home_link_title_environment_3": "Bitcoin je nejzelenější průmysl na Zemi!",
	"home_link_title_environment_4": "Těžba Bitcoinu brání spalovanému zemnímu plynu v znečišťování atmosféry",
	"home_link_title_food_1": "Jak inflace ovlivňuje ceny potravin",
	"home_link_title_food_2": "Jak fiat peníze škodí potravinám, farmám a půdě",
	"home_link_title_fine_art": "Bitcoin vs Umění",
	"home_link_title_art_1": "Připojte se k naší iniciativě bitcoinových nálepek",
	"home_link_title_art_2": "Pošlete bitcoinovou pohlednici někomu, koho znáte",
	"home_link_title_art_3": "Tiskněte a vylepujte bitcoinové letáky",
	"home_link_title_politics_1": "Bitcoin je politický paradox",
	"home_link_title_politics_2": "Můžete hlasovat za lepší peníze",
	"home_link_title_war_1": "Jak by Bitcoin mohl ukončit nekonečnou válku",
	"home_link_title_war_2": "Bitcoin a veteráni: přirozená souhra",
	"home_link_title_war_3": "Jak Bitcoin pomáhá civilistům uniknout válce v Súdánu",
	"home_link_title_coding_1": "Interaktivní tutoriál o technické stránce Bitcoinu",
	"home_link_title_coding_2": "bitcoinSwitch: přestavte jakékoli zařízení na přijímání Bitcoinu",
	"home_link_title_coding_3": "Programujte si cestu tajemstvími Bitcoinu",
	"home_link_title_networks_1": "Živý pohled na Bitcoinovou síť",
	"home_link_title_networks_2": "Bitcoin vs Banky",
	"home_link_title_payments_1": "Bitcoin vs Visa",
	"home_link_title_payments_2": "Pohled na Lightning Network (okamžité bitcoinové platby)",
	"home_link_title_payments_3": "Bitcoinová peněženka El Salvadoru by mohla ušetřit Salvadorcům 400 milionů dolarů ročně na remitencích",
	"home_link_title_payments_4": "Získejte svou Lightning adresu pro příjem okamžitých bitcoinových plateb",
	"home_link_title_self_custody_1": "Jak bezpečně uchovávat svůj Bitcoin",
	"home_link_title_self_custody_2": "6 důvodů, proč vybrat svůj Bitcoin z burz",
	"home_link_title_self_custody_3": "Zlato, Bitcoin a vlastní správa",
	"home_link_title_get_started_1": "Naučte se základy Bitcoinu",
	"home_link_title_get_started_2": "Získejte svou první bitcoinovou peněženku",
	"home_link_title_get_started_3": "Jak koupit Bitcoin",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Kalkulačka složené inflace",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}\n\nDone! Created index.json.`);
