/**
 * Creates Korean (ko) index.json translation file (~130+ keys).
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ko';
const today = '2026-04-04';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"bitcoin_builds_a_better_world": "비트코인은 더 나은 세상을 만듭니다.",
	"home_description": "비트코인은 더 나은 세상을 만드는 더 나은 화폐입니다. 비트코인은 인권을 보호하고, 높은 인플레이션으로부터 사람들을 구하고, 지역 농부를 지원하고, 석유 시추 배출을 줄이는 등 훨씬 더 많은 일을 합니다.",
	"home_intro": "비트코인은 더 나은 세상을 만드는 더 나은 화폐입니다. 아래 카테고리를 눌러 비트코인이 어떻게 세상을 더 낫게 만드는지 알아보거나, 스크롤하여 탐색하세요.",
	"home_btn_money": "더 나은 화폐",
	"home_btn_salary": "급여",
	"home_btn_freedom": "자유",
	"home_btn_human_rights": "인권",
	"home_btn_equality": "평등",
	"home_btn_property_rights": "재산권",
	"home_btn_housing": "주거",
	"home_btn_business": "비즈니스",
	"home_btn_crowdfunding": "크라우드펀딩",
	"home_btn_energy": "에너지",
	"home_btn_environment": "환경",
	"home_btn_food": "식품",
	"home_btn_art": "예술",
	"home_btn_politics": "정치",
	"home_btn_war": "전쟁",
	"home_btn_coding": "코딩",
	"home_btn_networks": "네트워크",
	"home_btn_payments": "결제",
	"home_btn_self_custody": "셀프 커스터디",
	"home_btn_you": "당신",
	"home_section_bitcoin_is": "비트코인은",
	"home_section_bitcoin_and": "비트코인과",
	"home_link_type_website": "웹사이트",
	"home_link_type_video": "영상",
	"home_link_type_article": "기사",
	"home_link_type_podcast": "팟캐스트",
	"home_link_type_business_kit": "비즈니스 키트",
	"home_link_type_data": "데이터",
	"home_link_type_research": "연구",
	"home_link_type_story": "이야기",
	"home_link_type_book_excerpt": "책 발췌",
	"home_link_type_street_art": "스트리트 아트",
	"home_link_type_outreach": "홍보",
	"home_link_type_campaign": "캠페인",
	"home_link_type_software": "소프트웨어",
	"home_link_type_hardware": "하드웨어",
	"home_link_type_guide": "가이드",
	"home_link_type_email": "이메일",
	"home_link_title_inflation": "비트코인에는 인플레이션이 없습니다",
	"home_link_title_bank_runs": "비트코인에는 뱅크런이 없습니다",
	"home_link_title_gold": "비트코인 vs 금",
	"home_link_title_crypto": "비트코인 vs 암호화폐",
	"home_link_title_cash": "비트코인 vs 현금",
	"home_link_title_bonds": "비트코인 vs 채권",
	"home_link_title_cbdc": "비트코인 vs CBDC",
	"home_link_title_your_salary_1": "인플레이션에 맞추기 위해 급여가 얼마나 올라야 하는지 알아보세요.",
	"home_link_title_freedom_1": "비트코인이 자유에 중요한 이유",
	"home_link_title_freedom_2": "비트코인은 정치적 억압으로부터 자유를 제공합니다",
	"home_link_title_human_rights_1": "비트코인이 인권을 어떻게 시행하는지",
	"home_link_title_human_rights_2": "아프리카의 조용한 비트코인 혁명",
	"home_link_title_human_rights_3": "비트코인은 전 세계에서 인권을 보호하고 있습니다",
	"home_link_title_equality_1": "비트코인이 남아프리카인들에게 희망과 기회를 가져다주고 있습니다",
	"home_link_title_equality_2": "비트코인이 흑인 미국인들에게 어떤 변화를 가져올 수 있는지",
	"home_link_title_property_rights_1": "비트코인은 완벽한 형태의 재산입니다",
	"home_link_title_property_rights_2": "비트코인 vs 부동산",
	"home_link_title_housing_1": "비트코인이 주거 문제를 어떻게 해결할 수 있는지",
	"home_link_title_business_3": "비트코인 vs 주식",
	"home_link_title_business_1": "비트코인이 비즈니스에 좋은 이유",
	"home_link_title_business_2": "지역 비즈니스에 비트코인 결제를 도입하기",
	"home_link_title_crowdfunding_1": "비트코인이 나이지리아 역사상 최대 시위에 어떻게 힘을 실었는지",
	"home_link_title_crowdfunding_2": "GoFundMe가 기부를 차단한 후 캐나다 트럭 운전사 시위가 비트코인으로 자금을 모금",
	"home_link_title_crowdfunding_3": "Geyser = 비트코인으로 크라우드펀딩",
	"home_link_title_energy_1": "비트코인이 텍사스 전력망을 어떻게 안정화하는지",
	"home_link_title_energy_2": "비트코인은 왜 에너지를 사용하나요?",
	"home_link_title_energy_3": "비트코인의 에너지 사용은 문제가 아닙니다. 그 이유는 다음과 같습니다.",
	"home_link_title_energy_4": "비트코인 채굴이 수요 반응을 통해 에너지 그리드를 안정화하고 있습니다",
	"home_link_title_energy_5": "비트코인 채굴자들이 아프리카 농촌 지역에 수력 발전을 가져다주고 있습니다",
	"home_link_title_energy_6": "비트코인이 재생 에너지를 어떻게 촉진하는지",
	"home_link_title_environment_1": "비트코인 채굴이 전 세계 메탄 배출을 어떻게 줄이는지",
	"home_link_title_environment_2": "비트코인 채굴이 국립공원을 어떻게 구했는지",
	"home_link_title_environment_3": "비트코인은 지구상에서 가장 친환경적인 산업입니다!",
	"home_link_title_environment_4": "비트코인 채굴이 방출되는 천연가스가 대기를 오염시키는 것을 방지하고 있습니다",
	"home_link_title_food_1": "인플레이션이 식품 가격에 어떤 영향을 미치는지",
	"home_link_title_food_2": "법정화폐가 식품, 농장, 토양에 어떻게 나쁜지",
	"home_link_title_fine_art": "비트코인 vs 미술품",
	"home_link_title_art_1": "비트코인 스티커 이니셔티브에 참여하세요",
	"home_link_title_art_2": "아는 사람에게 비트코인 엽서를 보내세요",
	"home_link_title_art_3": "비트코인 전단지를 인쇄하고 게시하세요",
	"home_link_title_politics_1": "비트코인은 정치적 역설입니다",
	"home_link_title_politics_2": "더 나은 화폐에 투표할 수 있습니다",
	"home_link_title_war_1": "비트코인이 끝없는 전쟁을 어떻게 종식시킬 수 있는지",
	"home_link_title_war_2": "비트코인과 참전 용사: 자연스러운 조화",
	"home_link_title_war_3": "비트코인이 수단 전쟁에서 민간인 탈출을 어떻게 돕는지",
	"home_link_title_coding_1": "비트코인의 기술적 측면에 대한 인터랙티브 튜토리얼",
	"home_link_title_coding_2": "bitcoinSwitch: 비트코인 결제를 받도록 기기 개조",
	"home_link_title_coding_3": "코딩으로 비트코인의 미스터리를 풀어보세요",
	"home_link_title_networks_1": "비트코인 네트워크 실시간 보기",
	"home_link_title_networks_2": "비트코인 vs 은행",
	"home_link_title_payments_1": "비트코인 vs Visa",
	"home_link_title_payments_2": "라이트닝 네트워크 살펴보기 (즉시 비트코인 결제)",
	"home_link_title_payments_3": "엘살바도르의 비트코인 지갑이 송금 수수료에서 연간 4억 달러를 절약할 수 있습니다",
	"home_link_title_payments_4": "즉시 비트코인 결제를 받을 라이트닝 주소 만들기",
	"home_link_title_self_custody_1": "비트코인을 안전하게 보관하는 방법",
	"home_link_title_self_custody_2": "거래소에서 비트코인을 인출해야 하는 6가지 이유",
	"home_link_title_self_custody_3": "금, 비트코인, 셀프 커스터디",
	"home_link_title_get_started_1": "비트코인의 기본을 배우세요",
	"home_link_title_get_started_2": "첫 번째 비트코인 지갑을 만드세요",
	"home_link_title_get_started_3": "비트코인 구매 방법",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "복리 인플레이션 계산기",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! index.json created for Korean (ko).');
