/**
 * Creates Korean (ko) common.json translation file (~180+ keys).
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ko';
const today = '2026-04-04';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"common_footer_mission_1": "bitcoin.rocks의 사명은 교육을 통해 비트코인 채택을 가속화하는 것입니다.",
	"common_footer_mission_2": "이 오픈소스 프로젝트에 기여하는 방법을 알아보세요.",
	"common_footer_follow_first_half": "Nostr 클라이언트에서",
	"common_footer_follow_second_half": "을 검색하여 팔로우하세요.",
	"common_footer_what_is_nostr": "Nostr란?",
	"common_footer_about": "소개",
	"common_footer_email_us": "이메일:",
	"common_cta_section_get_started": "시작하기",
	"common_cta_section_with_bitcoin": "비트코인과 함께",
	"common_cta_section_title_1": "비트코인의 기본을 배우세요",
	"common_cta_section_title_1_alt": "비트코인에 대해 더 알아보세요",
	"common_cta_section_title_2": "첫 번째 비트코인 지갑을 만드세요",
	"common_cta_section_title_3": "비트코인 구매 방법",
	"common_cta_link_type_email": "이메일",
	"common_cta_link_type_guide": "가이드",
	"common_cta_link_type_website": "웹사이트",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "비트코인이란?",
	"common_what_is_bitcoin_content_1": "비트코인은 두 가지입니다: 디지털 화폐와 결제 네트워크. 비트코인 네트워크(결제 네트워크)를 사용하여 비트코인(디지털 화폐)을 다른 사람에게 직접 보낼 수 있습니다.",
	"common_what_is_bitcoin_content_2": "비트코인은 가치를 저장하고 거래하는 근본적으로 새로운 방법입니다. 일반 금융 네트워크와 달리 비트코인 네트워크는 중앙 기관이나 신뢰할 수 있는 관리자 없이 운영됩니다. 이것이 비트코인을 역사상 최초의 개방적이고 국경 없는 화폐로 만듭니다.",
	"common_what_is_bitcoin_content_3": "비트코인은 여러분에게 재산에 대한 완전한 소유권을 부여하는 디지털 화폐입니다. 인류 역사상 처음으로 누구나 진정으로 희소하고, 사용 허가가 필요 없으며, 올바르게 보관하면 압수할 수 없는 자산을 소유할 수 있습니다.",
	"common_what_is_bitcoin_content_4": "비트코인은 은행 같은 제3자 중개자 없이도 전 세계 어디든 빠르고 저렴하게 보낼 수 있습니다.",
	"common_what_is_bitcoin_content_5": "비트코인을 사용하면 정부가 훔치거나 화폐 발행을 통해 가치를 떨어뜨릴 걱정 없이 안전하게 재산을 보관할 수 있습니다.",
	"common_what_is_bitcoin_content_6": "세계 어디서나 정부는 더 많은 종이 돈을 인쇄할 수 있지만, 아무도 비트코인을 더 만들 수 없습니다.",
	"common_what_is_bitcoin_content_7": "비트코인을 셀프 커스터디하여 완전히 통제할 수 있으며, 비트코인의 모든 힘에 접근할 수 있습니다.",
	"common_what_is_bitcoin_content_8": "앱을 다운로드할 수 있다면, 비트코인을 셀프 커스터디하고 다른 누구에게도 의존하지 않고 재산을 보관할 수 있습니다.",
	"common_what_is_bitcoin_content_9": "비트코인은 더 나은 화폐입니다.",
	"common_bitcoin_volatile": "비트코인이 변동성이 크다는데, 안전한가요?",
	"common_bitcoin_volatile_content_1": "단기적으로 비트코인의 환율은 변동하는 경향이 있습니다. 이것을 변동성이라고 합니다.",
	"common_bitcoin_volatile_content_2": "하지만 일상적으로 보이는 변동성은 장기적으로 '사라집니다'.",
	"common_bitcoin_volatile_content_3": "비트코인은 시간이 지남에 따라 점점 덜 변동적이 됩니다. 더 많은 사람들이 비트코인을 장기 저축 수단으로 사용할수록 가치가 더 안정됩니다.",
	"common_bitcoin_volatile_content_4": "많은 사람들이 변동성 위험을 최소화하고 시간이 지남에 따라 구매력을 보호하는 안전한 방법으로 수년간 비트코인에 가치를 저장합니다.",
	"common_bitcoin_volatile_content_5": "베네수엘라, 수단, 레바논, 시리아, 아르헨티나, 터키, 브라질 등 많은 국가에서 현지 통화의 가치가 너무 빨리 떨어져 비트코인이 돈을 저축하는 더 안정적인 방법으로 여겨집니다.",
	"common_bitcoin_afford": "비트코인 한 개를 살 수 없어요",
	"common_bitcoin_afford_content_1": "1달러가 100센트로 구성되듯이, 1비트코인은 100,000,000(1억) 사토시로 구성됩니다.",
	"common_bitcoin_afford_content_2": "비트코인 전체를 소유할 필요가 없습니다. 대부분의 사람들은 사토시만 소유합니다. 사토시는 비트코인의 소수 단위입니다. 예를 들어, 1비트코인이 $100,000이면 $1로 1,000사토시를 살 수 있습니다!",
	"common_bitcoin_hacked": "비트코인이 해킹된 적이 있나요?",
	"common_bitcoin_hacked_content_1": "온라인이나 뉴스에서 '비트코인 해킹'에 대해 들어보셨을 수 있습니다. 대부분의 사람들은 이 기사를 읽고 비트코인 네트워크가 해킹되었다고 믿습니다. 하지만 비트코인 네트워크는 한 번도 해킹된 적이 없습니다.",
	"common_bitcoin_hacked_content_2": "비트코인 네트워크란 무엇일까요? 비트코인 네트워크를 기차 선로라고 생각하세요. 비트코인 네트워크의 기차 선로 위를 달리는 기차가 비트코인 거래입니다.",
	"common_bitcoin_hacked_content_3": "뉴스에서 비트코인 해킹에 대해 읽을 때, 그것은 FTX 같은 수탁자가 해킹되거나 파산한 것에 대한 이야기입니다.",
	"common_bitcoin_hacked_content_4": "수탁자는 여러분의 비트코인을 대신 보관해주는 회사입니다. 하지만 이에는 위험이 따릅니다: 회사가 잘못 관리하거나, 훔치거나, 사업을 접으면 비트코인을 잃게 됩니다.",
	"common_bitcoin_hacked_content_5": "가장 최근에 FTX에서 이런 일이 발생했습니다.",
	"common_bitcoin_hacked_content_6": "FTX에 비트코인을 맡긴 모든 사람은 비트코인을 잃었습니다. 셀프 커스터디로 비트코인을 보관한 모든 사람은 FTX의 영향을 전혀 받지 않았습니다. 이것이 셀프 커스터디된 비트코인의 힘입니다: 진정한 돈의 통제권.",
	"common_bitcoin_hacked_content_7": "비트코인을 거래소에 두거나 ETF 같은 래퍼에 넣는 대신, 자유의 이점을 모두 누리려면 자신의 지갑에 보관하세요.",
	"common_bitcoin_hacked_content_8": "비트코인을 셀프 커스터디하면, 여러분의 돈은 비트코인 네트워크로 보호됩니다. 세계에서 가장 안전한 금융 네트워크입니다.",
	"common_bitcoin_hacked_content_9": "셀프 커스터디에서는 FTX의 Sam이 여러분의 비트코인을 훔칠 수 없습니다.",
	"common_bitcoin_hacked_content_10": "정부가 비트코인을 더 인쇄하여 인플레이션을 일으킬 수 없습니다.",
	"common_bitcoin_hacked_content_11": "셀프 커스터디된 비트코인은 비트코인 네트워크의 힘 덕분에 여러분의 돈입니다.",
	"common_bitcoin_energy": "비트코인은 왜 에너지를 사용하나요?",
	"common_bitcoin_energy_content_1": "비트코인은 네트워크를 보호하고 여러분의 돈을 지키기 위해 에너지를 사용합니다.",
	"common_bitcoin_energy_content_2": "비트코인은 상당한 양의 에너지를 사용하며, 이것은 여러 이유로 좋은 일입니다.",
	"common_bitcoin_energy_list_1": "비트코인에는 뱅크런이 없습니다.",
	"common_bitcoin_energy_list_2": "비트코인은 채굴을 통해 전력망 안정화에 도움을 줍니다.",
	"common_bitcoin_energy_list_3": "비트코인은 석유 시추로 인한 배출을 줄입니다.",
	"common_bitcoin_energy_list_4": "비트코인은 미국인들이 매년 크리스마스 조명에 사용하는 것보다 적은 에너지를 사용합니다.",
	"common_bitcoin_energy_list_5": "비트코인은 지구상에서 가장 친환경적인 산업입니다!",
	"common_cic_intro_1": "많은 사람들이 복리에 대해 알고 있지만, 복리 인플레이션에 대해 아는 사람은 거의 없습니다.",
	"common_cic_intro_2": "복리 인플레이션 계산기를 사용하면 시간이 지남에 따라 구매력을 유지하기 위해 급여가 얼마나 올라야 하는지 쉽게 계산할 수 있습니다.",
	"common_cic_intro_3": "현재 급여, 인플레이션율, 계산하려는 연수를 입력하면 인플레이션에 맞추기 위해 급여가 얼마가 되어야 하는지 계산기가 보여줍니다.",
	"common_current_salary": "현재 급여",
	"common_inflation_rate": "인플레이션율",
	"common_year": "년",
	"common_years": "년",
	"common_result_starting_message": "위 양식을 작성하고 계산 버튼을 클릭하세요.",
	"common_error_message": "오류: 3개 필드를 모두 입력해 주세요.",
	"common_result_message_1": "인플레이션율",
	"common_result_message_2": "에서",
	"common_result_message_3": "급여가",
	"common_result_message_in": "으로 올라야",
	"common_result_message_4": "구매력을 유지할 수 있습니다.",
	"common_calculate_button_text": "계산하기",
	"common_learn_more": "자세히 알아보기",
	"common_success": "성공!",
	"common_choose_your_country": "국가를 선택하세요",
	"common_country_usa": "미국",
	"common_country_canada": "캐나다",
	"common_submit": "제출",
	"common_language_afrikaans": "아프리칸스어",
	"common_language_arabic": "아랍어",
	"common_language_basque": "바스크어",
	"common_language_bulgarian": "불가리아어",
	"common_language_catalan": "카탈루냐어",
	"common_language_chinese": "중국어",
	"common_language_croatian": "크로아티아어",
	"common_language_czech": "체코어",
	"common_language_danish": "덴마크어",
	"common_language_dutch": "네덜란드어",
	"common_language_english": "영어",
	"common_language_estonian": "에스토니아어",
	"common_language_filipino": "필리핀어",
	"common_language_finnish": "핀란드어",
	"common_language_french": "프랑스어",
	"common_language_german": "독일어",
	"common_language_greek": "그리스어",
	"common_language_hausa": "하우사어",
	"common_language_hebrew": "히브리어",
	"common_language_hindi": "힌디어",
	"common_language_hungarian": "헝가리어",
	"common_language_indonesian": "인도네시아어",
	"common_language_irish": "아일랜드어",
	"common_language_italian": "이탈리아어",
	"common_language_japanese": "일본어",
	"common_language_korean": "한국어",
	"common_language_malay": "말레이어",
	"common_language_norwegian": "노르웨이어",
	"common_language_persian": "페르시아어",
	"common_language_polish": "폴란드어",
	"common_language_portuguese": "포르투갈어",
	"common_language_russian": "러시아어",
	"common_language_sinhala": "싱할라어",
	"common_language_slovak": "슬로바키아어",
	"common_language_slovenian": "슬로베니아어",
	"common_language_spanish": "스페인어",
	"common_language_swahili": "스와힐리어",
	"common_language_swedish": "스웨덴어",
	"common_language_thai": "태국어",
	"common_language_turkish": "터키어",
	"common_language_urdu": "우르두어",
	"common_language_vietnamese": "베트남어",
	"common_language_yoruba": "요루바어",
	"common_stickers_bulk_mess": "파일을 직접 다루고 싶지 않으신가요?",
	"common_stickers_bulk_want": "스티커 몇 장 이상 원하시나요?",
	"common_stickers_bulk_store": "저희가 사용하는 것과 같은 인쇄소에서 대량으로 주문하세요.",
	"common_stickers_bulk_cheaper": "더 많은 스티커를 구매할수록 개당 가격이 더 저렴해집니다.",
	"common_stickers_print_instructions_1": "어디에 살든 직접 스티커를 인쇄하여 참여할 수 있습니다! 아래에서 원하는 언어를 클릭하여 스티커 파일과 인쇄 방법을 다운로드하세요.",
	"common_stickers_print_instructions_2": "참고: 모든 스티커가 모든 언어로 제공되는 것은 아닙니다.",
	"common_stickers_request_language_1": "원하는 언어가 없나요?",
	"common_stickers_request_language_2": "아래 양식을 작성하여 원하는 언어의 스티커 파일을 요청하세요.",
	"common_stickers_dimensions": "크기:",
	"common_stickers_type": "유형:",
	"common_stickers_material": "재질:",
	"common_stickers_where_to_print": "인쇄처:",
	"common_stickers_type_die_cut": "다이컷 스티커",
	"common_stickers_material_vinyl": "야외용 비닐 스티커",
	"common_stickers_printer": "저희는 StickerMule.com을 사용하지만 어떤 스티커 회사든 이용할 수 있습니다.",
	"common_stickers_dimensions_danger": "11.4544 cm x 8.382 cm (4.51 in x 3.3 in)",
	"common_stickers_dimensions_warning": "10.414 cm x 9.2202 cm (4.1 in x 3.63 in)",
	"common_stickers_dimensions_caution": "12.0142 cm x 7.9502 cm (4.73 in x 3.13 in)",
	"common_stickers_dimensions_fix": "11.3792 cm x 6.8072 cm (4.48 in x 2.68 in)",
	"common_stickers_dimensions_study": "14.605 cm x 5.1308 cm (5.75 in x 2.02 in)",
	"common_stickers_dimensions_bdhi": "21.59 cm x 4.6482 cm (8.5 in x 1.83 in)",
	"common_stickers_dimensions_cure_v2": "6.35 cm x 12.7 cm (2.5 in x 5 in)",
	"common_stickers_dimensions_got_inflation": "7.9248 cm x 14.605 cm (3.12 in x 5.75 in)",
	"common_stickers_dimensions_what_if": "21.7932 cm x 7.62 cm (8.58 in x 3 in)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20.995 cm x 6.35 cm (8.25 in x 2.5 in)",
	"common_nostr_join": "지금 NOSTR에 가입하세요",
	"common_nostr_protocol_header": "플랫폼이 아닌 프로토콜",
	"common_nostr_protocol_c1": "Nostr는 검열, 플랫폼 퇴출, 도달률 감소 걱정 없이 온라인으로 소통할 수 있게 해주는 새로운 프로토콜입니다.",
	"common_nostr_protocol_c2": "Twitter나 Facebook 같은 플랫폼은 단일 기업이 통제하지만, 아무도 Nostr 프로토콜을 통제하지 않습니다.",
	"common_nostr_freedom_header": "이동의 자유",
	"common_nostr_freedom_c1": "Nostr는 이메일과 비슷합니다. 아무도 이메일 프로토콜을 통제하지 않으며, 누구나 그 위에 클라이언트(Gmail, Hotmail 등)를 구축할 수 있습니다.",
	"common_nostr_freedom_c2": "아무도 Nostr 프로토콜을 통제하지 않으며, 누구나 그 위에 클라이언트(Damus, Amethyst 등)를 구축할 수 있습니다.",
	"common_nostr_freedom_c3": "특정 클라이언트의 작동 방식이 마음에 들지 않으면, 팔로워나 콘텐츠를 잃지 않고 Nostr 계정을 다른 클라이언트로 원활하게 이동할 수 있습니다.",
	"common_nostr_bitcoin_header": "비트코인이 내장되어 있습니다",
	"common_nostr_bitcoin_c1": "비트코인이 Nostr 프로토콜에 기본적으로 내장되어 있습니다. 마음에 드는 콘텐츠를 보면 감사의 표시로 쉽게 비트코인을 zap할 수 있습니다!",
	"common_nostr_bitcoin_c2": "Twitter나 Facebook 같은 중앙화된 플랫폼에서는 중앙화된 기업이 여러분의 콘텐츠로 수익을 올립니다. 하지만 Nostr 같은 오픈 프로토콜에서는 여러분이 콘텐츠로 수익을 올립니다.",
	"common_nostr_download_client": "무료 클라이언트를 다운로드하여 NOSTR에 가입하세요",
	"common_nostr_iphone_clients": "iPhone 클라이언트",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "iPhone 앱",
	"common_nostr_first_client": "추천 첫 클라이언트",
	"common_nostr_wallet_built_in": "비트코인 zap 지갑 내장",
	"common_nostr_download_now": "지금 다운로드",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "익숙한 인터페이스",
	"common_nostr_separate_wallet": "별도의 비트코인 지갑 필요",
	"common_nostr_android_clients": "Android 클라이언트",
	"common_nostr_android_app": "Android 앱",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "다양한 기능",
	"common_nostr_browser_clients": "브라우저 클라이언트",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "웹 클라이언트",
	"common_nostr_simple": "매우 간단",
	"common_nostr_test": "테스트 계정으로 Nostr를 쉽게 체험",
	"common_nostr_view_client": "클라이언트 보기",
	"common_kit_printer": "비트코인 비즈니스 키트 브로셔 인쇄에는 VistaPrint.com을 추천합니다. 양면 인쇄가 가능한 어떤 인쇄소든 이용할 수 있습니다.",
	"common_kit_link_to_print": "인쇄 링크:",
	"common_kit_fold": "접기:",
	"common_kit_fold_trifold": "삼단 접기",
	"common_kit_unfolded_size": "펼친 크기:",
	"common_kit_unfolded_size_bbk": "레터 사이즈 (8.5 in x 11 in)",
	"common_kit_paper_thickness": "종이 두께:",
	"common_kit_paper_thickness_standard": "표준",
	"common_kit_paper_stock": "종이 종류:",
	"common_kit_paper_stock_glossy": "광택",
	"common_kit_exterior_print_file": "외부 인쇄 파일:",
	"common_kit_interior_print_file": "내부 인쇄 파일:",
	"common_kit_cta_header": "지역 비즈니스에 비트코인 결제를 도입하세요",
	"common_biz_learn": "비트코인이 비즈니스에 좋은 이유 알아보기",
	"common_biz_wallets": "비트코인 결제를 받기 위한 비트코인 지갑 만들기",
	"common_biz_maps": "비트코인 가맹점 지도에 등록하기",
	"common_biz_stickers": "무료 'Bitcoin Accepted Here' 스티커",
	"common_biz_rewards": "비트코인 리워드",
	"common_biz_accounting": "비트코인 회계 가이드",
	"common_biz_faq": "자주 묻는 질문",
	"common_biz_kit": "비트코인 비즈니스 키트 인쇄하기",
	"common_biz_accept_bitcoin_payments": "비트코인 결제 받기",
	"common_biz_ready": "비즈니스에서 비트코인을 받을 준비가 되셨나요?",
	"common_biz_more": "더 많은 비즈니스 리소스",
	"common_self_custody": "셀프 커스터디",
	"common_not_your_keys": "키가 없으면",
	"common_cold_wallet": "콜드 월렛",
	"common_hot_wallet": "핫 월렛",
	"common_sticker_files_mission_1": "우리의 사명은 공공장소에 비트코인 스티커를 붙여 더 많은 사람들이 비트코인에 관심을 갖게 하는 것입니다. 모든 스티커에는 교육 페이지로 연결되는 QR 코드가 있습니다:",
	"common_sticker_files_mission_2": "비트코인",
	"common_sticker_files_mission_3": "인플레이션",
	"common_sticker_files_mission_4": "미국이나 캐나다에 거주하신다면,",
	"common_sticker_files_mission_5": "무료 영어 스티커 팩을 요청하세요",
	"common_published_by": "게시자:",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "2022년부터 비트코인 교육",
	"common_publisher_open_source": "오픈소스 프로젝트",
	"common_reviewed_accuracy": "✓ 정확성 검토: 2026",
	"common_footer_tagline": "교육을 통해 비트코인 채택을 가속화합니다.",
	"common_footer_contribute": "기여하기",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "출처"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! common.json created for Korean (ko).');
