/**
 * Creates Korean (ko) translation files for content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ko';
const today = '2026-04-04';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "비트코인에는 뱅크런이 없습니다",
	"bank_runs_header": "비트코인에는 뱅크런이 없습니다",
	"bank_runs_header_2": "하지만 여러분의 은행에는 있을 수 있습니다",
	"bank_runs_what": "뱅크런이란?",
	"bank_runs_what_content_1": "뱅크런은 너무 많은 사람들이 동시에 은행에서 돈을 인출하려 할 때 발생합니다.",
	"bank_runs_what_content_2": "은행이 인출 요청을 충족할 만큼 충분한 돈을 보유하고 있지 않으면, 뱅크런이 발생할 때 완전히 무너질 수 있습니다.",
	"bank_runs_how": "뱅크런은 어떻게 발생하나요?",
	"bank_runs_how_content_1": "우리의 은행 시스템은 '부분 지급준비금' 방식입니다. 은행은 여러분의 돈을 금고에 보관하며 인출을 기다리는 것이 아닙니다.",
	"bank_runs_how_content_2": "대신, 은행은 여러분의 돈을 가져가서 대출하거나 투자합니다. 이렇게 하면 오랜 기간 돈이 묶일 수 있지만, 은행은 언제든지 인출할 수 있다고 약속합니다.",
	"bank_runs_how_content_3": "그렇다면 은행이 이미 돈을 대출하거나 투자한 후에 인출하려고 하면 어떻게 될까요?",
	"bank_runs_how_content_4": "혼자만 인출하려는 것이라면 문제가 되지 않습니다. 은행은 다른 사람의 돈을 가져와 여러분에게 줄 것입니다. 하지만 너무 많은 사람이 동시에 인출하려 하면 어떻게 될까요?",
	"bank_runs_how_content_5": "2023년 3월 실리콘밸리 은행에서 뱅크런이 발생했을 때 많은 미국인들이 이를 알게 되었습니다.",
	"bank_runs_how_content_6": "은행은 고객의 돈을 최대 30년간 묶인 국채에 투자했습니다. 설상가상으로, 최근 그 국채의 가치가 급락하여 실리콘밸리 은행은 예금자의 돈을 마련하기 위해 국채를 팔 수도 없었습니다. 그들은 지급불능 상태였습니다. 예금자의 인출 요청을 충족할 충분한 돈이 없었습니다.",
	"bank_runs_how_content_7": "더 많은 사람들이 알게 되면서 문제는 더욱 악화되었습니다. 더 많은 인출 요청이 들어왔지만, 많은 것이 처리되지 않았습니다. 수천 개의 기업이 은행 파산으로 직원 급여를 지급하지 못할 것이라는 것을 깨달았습니다.",
	"bank_runs_how_content_8": "FDIC가 개입하여 예금자들을 전액 보상하기로 합의했습니다. 문제 해결? 정확히 그렇지는 않습니다...",
	"bank_runs_fdic": "FDIC 보험이 내 돈을 보호하나요?",
	"bank_runs_fdic_content_1": "FDIC 보험은 은행이 파산할 경우 예금자를 보호하기 위해 설계되었습니다. 예금자당 최대 $250,000까지 보험이 적용됩니다. 좋아 보이죠?",
	"bank_runs_fdic_content_2": "정확히는 아닙니다. 은행이 파산하면 FDIC는 어디서 돈을 가져올까요? 1,250억 달러의 보험 기금을 보유하고 있습니다.",
	"bank_runs_fdic_content_3": "많은 돈처럼 들리지만, 보험 대상 예금액인 거의 10조 달러, 즉 10,000억 달러와 비교하면 그렇지 않습니다.",
	"bank_runs_fdic_content_4": "FDIC는 웹사이트에서 보험 기금이 예금의 1% 남짓만 커버할 수 있다는 것을 보여주고 있습니다.",
	"bank_runs_fdic_content_5": "FDIC 보험 기금을 초과하는 은행 파산이 발생하면, 미국 정부가 돈을 인쇄하여 예금자를 전액 보상할 가능성이 높지만(보장되지는 않습니다).",
	"bank_runs_fdic_content_6": "하지만 돈을 인쇄하면 인플레이션이 발생하므로 좋은 해결책은 아닙니다.",
	"bank_runs_safe": "부분 지급준비금을 사용하지 않는 은행이 있나요?",
	"bank_runs_safe_content_1": "일부 은행은 예금자의 자금을 대출하거나 투자하지 않는 '안전 은행'이 되려고 시도했습니다.",
	"bank_runs_safe_content_2": "이러한 안전 은행은 뱅크런 위험이 전혀 없겠지만, 연방준비제도에 의해 신청이 거부되었습니다. 이는 합법적으로 은행으로 운영할 수 없다는 것을 의미합니다.",
	"bank_runs_safe_content_3": "운영이 차단되었기 때문에, 현재 부분 지급준비금을 사용하지 않는 은행은 없습니다.",
	"bank_runs_safe_content_4": "다행히도, 직접 자신의 은행이 되어 부분 지급준비금 시스템에서 벗어나는 방법이 있습니다. 침대 밑에 현금을 숨기는 것이 아닙니다.",
	"bank_runs_safe_content_5": "현금으로 저축하는 것은 여전히 인플레이션에 취약합니다.",
	"bank_runs_safe_content_6": "우리가 말하는 것은 비트코인입니다: 자신의 은행이 될 수 있게 해주는 새로운 금융 시스템.",
	"bank_runs_protect": "비트코인이 뱅크런으로부터 나를 보호할 수 있나요?",
	"bank_runs_protect_content_1": "네, 비트코인은 완전 지급준비금 금융 시스템입니다.",
	"bank_runs_protect_content_2": "비트코인을 자신의 지갑으로 인출하기만 하면 뱅크런은 비트코인에서 불가능합니다. 비트코인을 거래소에 두거나 Bitcoin ETF 같은 래퍼에 넣지 마세요.",
	"bank_runs_protect_content_3": "자신의 지갑으로 인출하는 방법을 알아보려면 간단한 비트코인 지갑 가이드를 확인하세요.",
	"bank_runs_protect_content_4": "비트코인으로 드디어 자신의 돈을 통제할 수 있습니다."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "비트코인 지갑 가이드",
	"wallets_description": "중요한 면에서 차이가 나는 다양한 비트코인 지갑이 있습니다. 간단한 질문을 통해 적합한 지갑을 결정할 수 있습니다.",
	"wallets_header": "비트코인을 안전하게 보관하는 방법",
	"wallets_s1_c1": "비트코인 지갑은 상호 운용이 가능하므로 어떤 지갑을 사용하든 누구에게나 비트코인을 보낼 수 있습니다.",
	"wallets_s1_c2": "중요한 면에서 차이가 나는 다양한 비트코인 지갑이 있습니다. 간단한 질문을 통해 적합한 지갑을 결정할 수 있습니다:",
	"wallets_question_1": "셀프 커스터디 지갑인가요?",
	"wallets_s2_c1": "비트코인의 혁신 중 하나는 은행 같은 수탁자에 의존하지 않고 보관할 수 있는 능력입니다.",
	"wallets_s2_c2": "거래소나 ETF에 비트코인을 보유하면 비트코인의 자유 혜택을 잃게 됩니다.",
	"wallets_s2_c3": "셀프 커스터디 지갑은 비트코인의 모든 힘을 발휘합니다: 자유의 화폐.",
	"wallets_s2_c4": "셀프 커스터디 지갑을 사용하면 돈을 쓰거나 전송할 수 있는 유일한 사람은 바로 여러분입니다. 셀프 커스터디 지갑을 사용하면 아무도 돈의 송금이나 수령을 막을 수 없습니다.",
	"wallets_s2_c5": "셀프 커스터디 지갑은 비수탁형 지갑이라고도 합니다.",
	"wallets_s3_c1": "수탁형 지갑은 돈을 통제할 수 없는 지갑입니다.",
	"wallets_s3_c2": "이러한 지갑은 제3자가 돈에 대한 접근을 제공해야 하는 은행 시스템과 더 유사합니다. 비트코인이 거래소에 있다면 수탁형 지갑을 사용하는 것입니다.",
	"wallets_s3_c3": "Bitcoin ETF를 구매했다면, 셀프 커스터디로 출금할 수 없는 수탁형 지갑을 사용하는 것입니다.",
	"wallets_s3_c4": "수탁형 지갑은 편리해 보일 수 있지만, 수탁자는 언제든지 모든 사용자 자금을 도용할 수 있는 기술적 능력을 가지고 있습니다.",
	"wallets_s3_c5": "키가 없으면 코인도 없습니다!",
	"wallets_question_2": "핫 월렛인가요, 콜드 월렛인가요?",
	"wallets_s4_c1": "콜드 월렛은 비트코인 키를 인터넷에 노출하지 않는 방식으로 보관합니다.",
	"wallets_s4_c2": "이것은 도둑이 비트코인을 훔치려 할 수 있는 공격 벡터를 크게 제한하며, 자주 전송할 필요가 없는 큰 금액의 비트코인에 가장 적합합니다.",
	"wallets_s4_c3": "콜드 월렛은 장기 저축 계좌, 즉 콜드 스토리지로 생각할 수 있습니다.",
	"wallets_s5_c1": "핫 월렛은 휴대폰처럼 인터넷에 연결된 기기에 비트코인 키를 보관합니다.",
	"wallets_s5_c2": "핫 월렛은 일반적으로 안전한 것으로 간주되지만, 콜드 월렛보다 더 많은 보안 취약점이 있을 수 있습니다.",
	"wallets_s5_c3": "핫 월렛은 물리적 지갑처럼 생각하면 됩니다. 전체 저축을 지갑에 넣지는 않겠지만, 용돈 정도는 넣어 둘 것입니다.",
	"wallets_s5_c4": "핫 월렛은 콜드 스토리지에서 전체 저축을 꺼내지 않고도 비트코인을 훨씬 쉽게 사용할 수 있게 합니다.",
	"wallets_question_3": "복구 문구를 어떻게 백업하나요?",
	"wallets_s6_c1": "비트코인 지갑을 설정하면 기기가 복구 문구를 생성합니다. 이 복구 문구(시드 문구라고도 함)는 12개 또는 24개의 단어로 구성됩니다.",
	"wallets_s6_c2": "지갑에 대한 접근을 잃거나 기기가 작동하지 않으면, 이 복구 문구를 새 지갑에 입력하여 비트코인에 다시 접근할 수 있습니다.",
	"wallets_s6_c3": "대부분의 지갑에는 복구 문구를 적을 종이가 포함되어 있지만, 많은 사람들은 종이 대신 스틸에 백업하는 것을 선호합니다. 이렇게 하면 화재나 홍수 같은 자연재해 시 복구 문구를 잃을 가능성이 훨씬 줄어듭니다.",
	"wallets_s6_c4": "Jameson Lopp이 70개의 스틸 백업 키트를 테스트하여 적합한 것을 선택하는 데 도움을 줍니다.",
	"wallets_s6_c5": "Jameson의 금속 비트코인 백업 가이드를 여기서 확인하세요.",
	"wallets_s6_c6": "또는 계속 스크롤하여 비트코인 지갑 옵션을 살펴보세요.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "라이트닝 지갑 가이드를 찾고 계신가요?",
	"wallets_starter_wallet": "훌륭한 입문 지갑",
	"wallets_mobile_app": "모바일 앱",
	"wallets_2fa_support": "2FA 지원",
	"wallets_air_gap_mode": "에어갭 모드",
	"wallets_air_gap_camera": "에어갭 모드 + 카메라",
	"wallets_bitcoin_only": "비트코인 전용",
	"wallets_security_features": "다양한 보안 기능",
	"wallets_free": "100% 무료",
	"wallets_coldcard_mk5_costs": "가격 $189",
	"wallets_coldcard_q_costs": "가격 $289",
	"wallets_blockstream_jade_costs": "가격 $79",
	"wallets_foundation_passport_costs": "가격 $199",
	"wallets_seedsigner_costs": "부품 비용 $50",
	"wallets_very_affordable": "매우 저렴",
	"wallets_pair_with_phone": "휴대폰과 페어링",
	"wallets_battery": "충전식 배터리",
	"wallets_build_your_own": "직접 조립",
	"wallets_qwerty_keyboard": "풀 QWERTY 키보드",
	"wallets_qr_scanner": "QR 코드 스캐너"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "비트코인 구매 방법 - 단계별 가이드",
	"buy_header": "비트코인 구매 방법",
	"buy_intro_c1": "처음 비트코인을 구매하는 것이 부담스럽게 느껴질 수 있지만, 단계별로 나누면 실제로 매우 간단합니다.",
	"buy_intro_c2": "이 가이드는 비트코인을 안전하게 구매하고 자신의 지갑에 보관하는 과정을 안내합니다.",
	"buy_step_1_header": "1단계: 국가 선택",
	"buy_step_1_description": "국가마다 이용 가능한 비트코인 구매 옵션이 다릅니다. 국가를 선택하여 최적의 옵션을 확인하세요.",
	"buy_search_countries": "국가 검색",
	"buy_country_united_states": "미국",
	"buy_country_australia": "호주",
	"buy_country_austria": "오스트리아",
	"buy_country_belgium": "벨기에",
	"buy_country_brazil": "브라질",
	"buy_country_canada": "캐나다",
	"buy_country_france": "프랑스",
	"buy_country_germany": "독일",
	"buy_country_ireland": "아일랜드",
	"buy_country_italy": "이탈리아",
	"buy_country_netherlands": "네덜란드",
	"buy_country_new_zealand": "뉴질랜드",
	"buy_country_spain": "스페인",
	"buy_country_united_kingdom": "영국",
	"buy_country_argentina": "아르헨티나",
	"buy_country_chile": "칠레",
	"buy_country_colombia": "콜롬비아",
	"buy_country_costa_rica": "코스타리카",
	"buy_country_czech_republic": "체코",
	"buy_country_denmark": "덴마크",
	"buy_country_el_salvador": "엘살바도르",
	"buy_country_estonia": "에스토니아",
	"buy_country_finland": "핀란드",
	"buy_country_greece": "그리스",
	"buy_country_guatemala": "과테말라",
	"buy_country_hong_kong": "홍콩",
	"buy_country_hungary": "헝가리",
	"buy_country_iceland": "아이슬란드",
	"buy_country_india": "인도",
	"buy_country_israel": "이스라엘",
	"buy_country_japan": "일본",
	"buy_country_latvia": "라트비아",
	"buy_country_lithuania": "리투아니아",
	"buy_country_luxembourg": "룩셈부르크",
	"buy_country_malta": "몰타",
	"buy_country_mexico": "멕시코",
	"buy_country_norway": "노르웨이",
	"buy_country_panama": "파나마",
	"buy_country_poland": "폴란드",
	"buy_country_portugal": "포르투갈",
	"buy_country_romania": "루마니아",
	"buy_country_singapore": "싱가포르",
	"buy_country_slovakia": "슬로바키아",
	"buy_country_slovenia": "슬로베니아",
	"buy_country_south_africa": "남아프리카공화국",
	"buy_country_south_korea": "대한민국",
	"buy_country_sweden": "스웨덴",
	"buy_country_switzerland": "스위스",
	"buy_country_thailand": "태국",
	"buy_country_turkey": "터키",
	"buy_country_ukraine": "우크라이나",
	"buy_country_uruguay": "우루과이",
	"buy_step_2_header": "2단계: 결제 방법 선택",
	"buy_step_2_description": "비트코인을 구매하는 두 가지 주요 방법이 있습니다: 은행 송금과 현금. 각각 다른 장점이 있습니다.",
	"buy_method_bank_transfer": "은행 송금",
	"buy_method_bank_fast": "빠르고 쉬움",
	"buy_method_bank_less_private": "프라이버시 낮음",
	"buy_method_bank_description": "은행 송금은 비트코인을 구매하는 가장 일반적인 방법입니다. 빠르고 편리하며 일반적으로 수수료가 낮습니다.",
	"buy_method_choose_bank": "은행 송금 선택",
	"buy_method_cash": "현금",
	"buy_method_cash_private": "프라이버시 높음",
	"buy_method_cash_limited": "제한된 옵션",
	"buy_method_cash_description": "현금 구매는 더 많은 프라이버시를 제공하지만 옵션이 적고 직접 만남이나 비트코인 ATM 사용이 필요할 수 있습니다.",
	"buy_method_choose_cash": "현금 선택",
	"buy_step_3_header": "3단계: 구매 옵션",
	"buy_step_3_description": "귀하의 국가와 결제 방법에 맞는 최적의 비트코인 구매 옵션입니다:",
	"buy_platform_recommended": "추천",
	"buy_platform_strike_description": "Strike는 낮은 수수료와 즉각적인 라이트닝 네트워크 지원으로 비트코인을 구매하는 가장 빠르고 쉬운 방법입니다.",
	"buy_platform_swan_description": "Swan Bitcoin은 정기 매수와 교육 리소스를 갖춘 비트코인 전용 서비스를 전문으로 합니다.",
	"buy_platform_river_description": "River는 교육과 보안에 중점을 둔 비트코인 매수, 채굴, 수탁 서비스를 제공합니다.",
	"buy_platform_coinsquare_description": "Coinsquare는 강력한 규제 준수와 고객 지원을 갖춘 캐나다 비트코인 거래소입니다.",
	"buy_platform_kraken_description": "Kraken은 고급 거래 기능과 강력한 보안을 갖춘 검증된 비트코인 거래소입니다.",
	"buy_platform_atm_description": "비트코인 ATM을 통해 현금으로 즉시 비트코인을 구매할 수 있습니다. Coin ATM Radar로 가까운 ATM을 찾으세요.",
	"buy_platform_bisq_description": "Bisq는 KYC 없이 비공개 비트코인 거래를 가능하게 하는 탈중앙화 P2P 거래소입니다.",
	"buy_platform_feature_instant": "즉시 구매",
	"buy_platform_feature_low_fees": "낮은 수수료",
	"buy_platform_feature_lightning": "라이트닝 네트워크",
	"buy_platform_feature_dca": "정기 매수",
	"buy_platform_feature_education": "교육 리소스",
	"buy_platform_feature_withdrawal": "쉬운 출금",
	"buy_platform_feature_mining": "비트코인 채굴",
	"buy_platform_feature_custody": "수탁 서비스",
	"buy_platform_feature_canadian": "캐나다 전문",
	"buy_platform_feature_regulated": "규제 거래소",
	"buy_platform_feature_support": "고객 지원",
	"buy_platform_feature_established": "검증된 플랫폼",
	"buy_platform_feature_security": "강력한 보안",
	"buy_platform_feature_advanced": "고급 기능",
	"buy_platform_feature_cash": "현금 구매",
	"buy_platform_feature_anonymous": "익명성 강화",
	"buy_platform_feature_p2p": "P2P",
	"buy_platform_feature_private": "비공개 거래",
	"buy_platform_feature_decentralized": "탈중앙화",
	"buy_platform_relai_description": "Relai는 셀프 커스터디 지갑, 자동 투자 기능, 유럽 사용자를 위한 낮은 수수료를 갖춘 스위스 비트코인 전용 앱입니다.",
	"buy_platform_feature_bitcoin_only": "비트코인 전용",
	"buy_platform_feature_self_custody": "셀프 커스터디 지갑",
	"buy_platform_feature_auto_invest": "자동 투자 플랜",
	"buy_platform_feature_european": "유럽 전문",
	"buy_step_4_header": "4단계: 비트코인 안전하게 보관",
	"buy_step_4_c1": "비트코인을 구매한 후 가장 중요한 단계는 개인 키를 통제하는 자신의 지갑으로 옮기는 것입니다.",
	"buy_step_4_c2": "거래소에 비트코인을 두는 것은 위험합니다. 실제로 비트코인을 소유하는 것이 아니라 거래소가 소유하는 것이기 때문입니다.",
	"buy_step_4_c3": "자신의 개인 키를 통제하면 비트코인의 진정한 소유권을 갖게 되며, 아무도 빼앗아 갈 수 없습니다.",
	"buy_step_4_c4": "필요에 맞는 비트코인 지갑 선택 방법을 알아보세요:",
	"buy_cta_wallets": "비트코인 지갑 가이드 보기"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "비트코인 라이트닝 지갑 가이드",
	"lightning_description": "라이트닝 지갑을 사용하면 개인 주권을 유지하면서 빠르고 저렴하게 비트코인을 전송할 수 있습니다.",
	"lightning_header": "라이트닝 지갑 가이드",
	"lightning_s1_c1": "라이트닝을 사용하면 빠르고 저렴하게 비트코인 결제를 보낼 수 있습니다.",
	"lightning_s1_c2": "라이트닝 사용에는 트레이드오프가 있다는 것을 아는 것이 중요합니다. 더 빠르고 저렴한 비트코인 결제를 위해 일부 보안을 희생하는 경우가 많습니다.",
	"lightning_s1_c3": "일반적으로 라이트닝은 소액의 비트코인에만 사용해야 합니다. 큰 금액의 비트코인은 항상 하드웨어 지갑에만 보관해야 합니다.",
	"lightning_s1_c4": "자세한 내용은 하드웨어 지갑 가이드를 확인하세요.",
	"lightning_s1_c5": "모든 라이트닝 지갑이 같지는 않습니다. 간단한 질문을 통해 적합한 트레이드오프를 가진 지갑을 결정할 수 있습니다:",
	"lightning_question_1": "나에게 맞는 트레이드오프 균형은?",
	"lightning_s2_c1": "비트코인의 혁신 중 하나는 은행 같은 수탁자에 의존하지 않고 보관할 수 있는 능력입니다. 셀프 커스터디 지갑은 비트코인의 모든 힘을 발휘합니다.",
	"lightning_s2_c2": "셀프 커스터디 지갑을 사용하면 돈을 쓰거나 전송할 수 있는 유일한 사람은 바로 여러분입니다. 아무도 막거나, 검열하거나, 훔칠 수 없습니다. 이것은 비수탁형 지갑이라고도 합니다.",
	"lightning_s2_c3": "라이트닝을 사용하는 가장 주권적인 방법은 자체 노드를 운영하는 것입니다.",
	"lightning_s2_c4": "이 가이드는 자체 노드가 필요 없는 간단한 라이트닝 지갑에 초점을 맞추고 있습니다.",
	"lightning_s2_c5": "비수탁형 라이트닝 지갑을 사용하더라도, 지갑 제작자가 악의적인 앱 업데이트를 배포하여 자금을 훔치지 않을 것이라고 신뢰해야 한다는 점을 아는 것이 중요합니다.",
	"lightning_s3_c1": "수탁형 지갑은 돈을 통제할 수 없는 지갑입니다.",
	"lightning_s3_c2": "이러한 지갑은 제3자가 돈에 대한 접근을 제공해야 하는 은행 시스템과 더 유사합니다. 비트코인이 거래소에 있다면 수탁형 지갑을 사용하는 것입니다.",
	"lightning_s3_c3": "수탁형 지갑은 편리해 보일 수 있지만, 수탁자는 언제든지 모든 사용자 자금을 도용할 수 있는 기술적 능력을 가지고 있습니다.",
	"lightning_s3_c4": "일부 사람들은 사용의 편의성 때문에 소액 비트코인에 수탁형 라이트닝 지갑을 선호합니다. 기억하세요: 키가 없으면 코인도 없습니다!",
	"lightning_question_2": "지갑을 선택하세요",
	"lightning_s4_c1": "이 모든 것을 염두에 두고, 이제 적합한 트레이드오프 균형을 가진 라이트닝 지갑을 선택할 수 있습니다.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "다양한 기능",
	"lightning_mobile_app": "모바일 앱",
	"lightning_free": "100% 무료",
	"lightning_merchants": "가맹점에 적합",
	"lightning_starter": "훌륭한 입문 지갑",
	"lightning_browser": "브라우저 기반",
	"lightning_custodial": "완전 수탁형 지갑",
	"lightning_cta_hardware": "비트코인 하드웨어 지갑 가이드를 찾고 계신가요?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "bitcoin.rocks의 무료 비트코인 스티커",
	"stickers_description": "공공장소에 비트코인 스티커를 붙여 주변 사람들에게 비트코인을 알리세요.",
	"stickers_header": "무료 비트코인 스티커",
	"stickers_choose_header": "스티커 팩을 선택하세요",
	"stickers_choose_c1": "우리의 사명은 공공장소에 비트코인 스티커를 붙여 더 많은 사람들이 비트코인에 관심을 갖게 하는 것입니다. 모든 스티커에는 교육 페이지로 연결되는 QR 코드가 있습니다:",
	"stickers_choose_c2": "비트코인",
	"stickers_choose_c3": "인플레이션",
	"stickers_choose_c4": "아래에서 스티커 팩을 선택하세요",
	"stickers_text_pack": "텍스트 팩",
	"stickers_signs_pack": "표지판 팩",
	"stickers_instructions_1": "우편 주소를 입력하시면 무료 비트코인 스티커 팩을 배송해 드립니다! 스티커는 흰색 봉투로 발송됩니다.",
	"stickers_instructions_2": "주소 데이터는 무료 스티커 발송 후 삭제됩니다.",
	"stickers_share_header": "스티커 설치 장소 공유하기",
	"stickers_share_c1": "Nostr에서 스티커 설치 장소를 공유하고 다른 사람들이 어디에 스티커를 붙이는지 확인하세요.",
	"stickers_btn_share_on_nostr": "NOSTR에서 공유하기",
	"stickers_btn_what_is_nostr": "NOSTR란?",
	"stickers_flyers_link_before": "스티커를 붙이는 김에 ",
	"stickers_flyers_link_text": "비트코인 전단지",
	"stickers_flyers_link_after": "도 인쇄해서 붙이면 더 많은 사람들에게 알릴 수 있습니다.",
	"stickers_country_global_print": "글로벌 — 직접 스티커 인쇄",
	"stickers_country_global_order": "글로벌 — 대량 주문",
	"placeholder_name_optional": "이름 (선택사항)",
	"placeholder_address_line_1": "주소 1행",
	"placeholder_address_line_2": "주소 2행 (선택사항)",
	"placeholder_city": "도시",
	"placeholder_state": "주/도",
	"placeholder_province": "지방",
	"placeholder_zip_code": "우편번호",
	"placeholder_postal_code": "우편번호",
	"placeholder_language": "언어",
	"placeholder_which_stickers": "어떤 스티커?",
	"placeholder_email_optional": "알림을 받을 이메일 입력 (선택사항)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "bitcoin.rocks의 무료 비트코인 엽서",
	"postcards_description": "무료 비트코인 엽서 팩을 받아 아는 사람에게 비트코인을 알리세요.",
	"postcards_header": "엽서 프로그램 종료",
	"postcards_program_closed_message": "무료 비트코인 엽서 프로그램이 종료되었습니다. 우편을 통한 비트코인 교육 확산에 참여해 주신 모든 분들께 감사드립니다!",
	"postcards_sticker_alternative_header": "대신 무료 비트코인 스티커를 받으세요",
	"postcards_sticker_alternative_message": "무료 스티커 프로그램으로 비트코인 인식을 계속 확산하세요! 비트코인 스티커는 공공장소에서 공유하기에 완벽하며 교육 콘텐츠로 연결되는 QR 코드가 있습니다.",
	"postcards_sticker_cta": "무료 스티커 받기",
	"postcards_step_2": "엽서 디자인",
	"postcards_instructions_4": "아는 사람에게 비트코인을 소개하기 쉽도록 이 엽서를 만들었습니다! 주소와 우표를 붙이고 엽서를 우편함에 넣으세요.",
	"postcards_instructions_5": "우리의 사명은 비트코인 채택을 가속화하는 것입니다. 무료 스티커를 받아 공공장소에 붙여 도와주세요!",
	"postcards_instructions_6": "비트코인에 대해 더 배울 수 있는 사람을 주변에서 알고 계실 겁니다. 오늘 그들에게 비트코인 스티커를 공유하세요!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "미국 전역에 이 비트코인 간판을 설치하는 데 도와주세요!",
	"signs_title": "bitcoin.rocks의 무료 비트코인 간판",
	"signs_choose_header": "미국 전역에 이 비트코인 간판을 설치해 주셔서 감사합니다!",
	"signs_choose_c1": "간판이 모두 소진되었습니다! 우리의 사명은 교육을 통해 비트코인 채택을 가속화하는 것입니다.",
	"signs_choose_c2": "많은 분들이 공공장소에 이 무료 비트코인 간판을 설치하여 도움을 주셨습니다. 모든 간판에는 교육 페이지로 연결되는 QR 코드가 있습니다:",
	"signs_choose_c3": "인플레이션",
	"signs_choose_c4": "놀라운 커뮤니티 덕분에 수천 명의 사람들에게 다가가 비트코인 토끼굴의 첫걸음을 내딛도록 도울 수 있었습니다.",
	"signs_share_header": "간판 설치 장소 공유하기",
	"signs_share_c1": "Nostr에서 간판 설치 장소 사진을 공유하고 다른 사람들이 어디에 간판을 설치하는지 확인하세요.",
	"signs_btn_share_on_nostr": "NOSTR에서 공유하기",
	"signs_btn_what_is_nostr": "NOSTR란?",
	"signs_instructions_1": "우편 주소를 입력하시면 비트코인 간판 10개가 든 상자를 배송해 드립니다!",
	"signs_instructions_2": "주소 데이터는 무료 간판 발송 후 삭제됩니다."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "bitcoin.rocks의 무료 비트코인 전단지",
	"flyers_description": "비트코인 전단지를 집에서 인쇄하여 공공장소에 게시하세요.",
	"flyers_header_1": "인쇄 & 게시",
	"flyers_header_2": "비트코인 전단지",
	"flyers_intro_header": "비트코인 전단지 인쇄 및 게시 방법",
	"flyers_intro_c1": "우리의 사명은 공공장소에 비트코인 전단지를 붙여 더 많은 사람들이 비트코인에 관심을 갖게 하는 것입니다. 이 전단지에는 저희",
	"flyers_intro_c2": "교육 비트코인 웹사이트로 연결되는 QR 코드가 있습니다.",
	"flyers_intro_c3": "인플레이션",
	"flyers_intro_c4": "이 전단지를 집이나 인쇄소에서 인쇄하세요. 그런 다음 게시판, 전봇대, 사람들이 볼 수 있는 공공장소에 게시하여 비트코인에 대해 알리세요.",
	"flyers_intro_c5": "전단지를 게시하는 김에",
	"flyers_intro_c6": "무료 비트코인 스티커",
	"flyers_intro_c7": "도 요청하여 더 많은 사람들에게 알리세요.",
	"flyers_btn_download": "전단지 다운로드",
	"flyers_btn_print": "전단지 인쇄",
	"flyers_share_header": "전단지 게시 장소 공유하기",
	"flyers_share_c1": "Nostr에서 전단지 게시 장소를 공유하고 다른 사람들이 어디에 전단지를 붙이는지 확인하세요.",
	"flyers_btn_share_on_nostr": "NOSTR에서 공유하기",
	"flyers_btn_what_is_nostr": "NOSTR란?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "참여하여 비트코인 확산을 도우세요",
	"get_involved_description": "무료 리소스로 비트코인 채택 확산을 더 쉽게 할 수 있습니다.",
	"get_involved_header": "참여하기",
	"get_involved_header_2": "비트코인을 알리세요",
	"get_involved_intro_1": "현재 세상의 상태에 살면서 우울해질 수 있습니다.",
	"get_involved_intro_2": "우리의 화폐가 망가져 있습니다. 그 결과, 사회의 근본적인 부분도 망가져 있습니다.",
	"get_involved_intro_3": "이미 비트코인을 알고 계시다면, 비트코인이 가져다 줄 수 있는 희망의 느낌을 알고 계실 것입니다. 더 나은 화폐가 가능하게 하는 밝은 미래에 대한 희망.",
	"get_involved_intro_4": "하지만 주변의 많은 사람들은 비트코인에 대해 모릅니다. 여러분과 같은 망가진 세상에 살고 있지만, 어둠 속에서 길을 밝혀줄 희망의 빛이 없습니다.",
	"get_involved_intro_5": "하지만 여러분이 그것을 바꿀 수 있습니다. 비트코인이 가져다 주는 희망을 주변 사람들에게 쉽게 전파할 수 있는 여러 무료 리소스를 만들었습니다.",
	"get_involved_sticker_header": "공공장소에 스티커 붙이기",
	"get_involved_sticker_content_1": "아무와도 대화하지 않고도 주변 사람들에게 비트코인에 대해 교육할 수 있습니다. 공공장소에 무료 비트코인 스티커를 붙이기만 하면 됩니다.",
	"get_involved_sticker_content_2": "매달 수백 명이 이 스티커의 QR 코드를 스캔합니다. 인플레이션 스티커는",
	"get_involved_sticker_content_3": "인플레이션 해결책으로서의 비트코인 페이지로 연결됩니다.",
	"get_involved_sticker_content_4": "다른 스티커들은 사람들에게",
	"get_involved_sticker_content_5": "비트코인이 더 나은 세상을 만들고 있다는 것을 보여주는 교육 홈페이지로 연결됩니다.",
	"get_involved_sticker_content_6": "사람들이 볼 수 있는 커뮤니티 장소에 이 스티커를 붙이면 주변 사람들이 비트코인 토끼굴의 첫걸음을 내딛도록 도울 수 있습니다.",
	"get_involved_request_a": "요청하기",
	"get_involved_sticker_pack": "스티커 팩",
	"get_involved_postcard_header": "엽서 보내기",
	"get_involved_postcard_content_1": "무료 엽서를 보내 아는 사람에게 비트코인의 희망을 전파할 수 있습니다.",
	"get_involved_postcard_content_2": "각 엽서 뒷면에는 비트코인에 대한 설득력 있는 설명과 더 알아볼 수 있는 QR 코드가 있습니다.",
	"get_involved_postcard_content_3": "비트코인 엽서를 보내면 그들이 비트코인을 새로운 시각으로 볼 수 있게 도울 수 있습니다.",
	"get_involved_postcard_pack": "엽서 팩",
	"get_involved_business_header": "비즈니스 온보딩",
	"get_involved_business_content_1": "비트코인 순환경제를 구축하고 싶으신가요? 비트코인 비즈니스 키트를 사용하면 비즈니스에 비트코인 결제 수납을 쉽게 소개할 수 있습니다.",
	"get_involved_business_content_2": "각 비즈니스 키트에는 비트코인 결제 수납의 장점을 강조하는 전단지가 포함되어 있습니다. 각 전단지는 다양한",
	"get_involved_business_content_3": "무료 비트코인 비즈니스 리소스로 연결됩니다.",
	"get_involved_business_kit": "비즈니스 키트"
});

console.log('\nDone! Content files created for Korean (ko).');
