/**
 * Creates Finnish (fi) index.json translation file
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'fi';
const today = '2026-04-08';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"bitcoin_builds_a_better_world": "Bitcoin rakentaa parempaa maailmaa.",
	"home_description": "Bitcoin on parempaa rahaa, joka rakentaa parempaa maailmaa. Bitcoin on suojannut ihmisoikeuksia, pelastanut ihmisi\u00e4 korkealta inflaatiolta, tukenut paikallisia maanviljelij\u00f6it\u00e4, v\u00e4hent\u00e4nyt \u00f6ljynporauksen p\u00e4\u00e4st\u00f6j\u00e4 ja paljon muuta.",
	"home_intro": "Bitcoin on parempaa rahaa, joka rakentaa parempaa maailmaa. Napauta alla olevaa kategoriaa oppiaksesi, miten Bitcoin tekee siit\u00e4 parempaa, tai ala vain vieritt\u00e4\u00e4 tutkiaksesi.",
	"home_btn_money": "PAREMPI RAHA",
	"home_btn_salary": "PALKKASI",
	"home_btn_freedom": "VAPAUS",
	"home_btn_human_rights": "IHMISOIKEUDET",
	"home_btn_equality": "TASA-ARVO",
	"home_btn_property_rights": "OMISTUSOIKEUDET",
	"home_btn_housing": "ASUMINEN",
	"home_btn_business": "LIIKETOIMINTA",
	"home_btn_crowdfunding": "JOUKKORAHOITUS",
	"home_btn_energy": "ENERGIA",
	"home_btn_environment": "YMP\u00c4RIST\u00d6",
	"home_btn_food": "RUOKA",
	"home_btn_art": "TAIDE",
	"home_btn_politics": "POLITIIKKA",
	"home_btn_war": "SOTA",
	"home_btn_coding": "KOODAUS",
	"home_btn_networks": "VERKOT",
	"home_btn_payments": "MAKSUT",
	"home_btn_self_custody": "OMA HALLINNOINTI",
	"home_btn_you": "SIN\u00c4",
	"home_section_bitcoin_is": "BITCOIN ON",
	"home_section_bitcoin_and": "BITCOIN &",
	"home_link_type_website": "VERKKOSIVUSTO",
	"home_link_type_video": "VIDEO",
	"home_link_type_article": "ARTIKKELI",
	"home_link_type_podcast": "PODCAST",
	"home_link_type_business_kit": "YRITYSPAKETTI",
	"home_link_type_data": "DATA",
	"home_link_type_research": "TUTKIMUS",
	"home_link_type_story": "TARINA",
	"home_link_type_book_excerpt": "KIRJAOTE",
	"home_link_type_street_art": "KATUTAIDE",
	"home_link_type_outreach": "TIEDOTUS",
	"home_link_type_campaign": "KAMPANJA",
	"home_link_type_software": "OHJELMISTO",
	"home_link_type_hardware": "LAITTEISTO",
	"home_link_type_guide": "OPAS",
	"home_link_type_email": "S\u00c4HK\u00d6POSTI",
	"home_link_title_inflation": "Bitcoinissa ei ole inflaatiota",
	"home_link_title_bank_runs": "Bitcoinissa ei ole talletuspakoja",
	"home_link_title_gold": "Bitcoin vs kulta",
	"home_link_title_crypto": "Bitcoin vs krypto",
	"home_link_title_cash": "Bitcoin vs k\u00e4teinen",
	"home_link_title_bonds": "Bitcoin vs joukkovelkakirjat",
	"home_link_title_cbdc": "Bitcoin vs CBDC:t",
	"home_link_title_your_salary_1": "Selvit\u00e4, kuinka paljon palkkasi t\u00e4ytyy nousta pysy\u00e4kseen inflaation tahdissa.",
	"home_link_title_freedom_1": "Miksi Bitcoin on t\u00e4rke\u00e4 vapaudelle",
	"home_link_title_freedom_2": "Bitcoin tarjoaa vapautta poliittisesta sorrosta",
	"home_link_title_human_rights_1": "Miten Bitcoin toteuttaa ihmisoikeuksia",
	"home_link_title_human_rights_2": "Afrikan hiljainen Bitcoin-vallankumous",
	"home_link_title_human_rights_3": "Bitcoin suojaa ihmisoikeuksia ymp\u00e4ri maailmaa",
	"home_link_title_equality_1": "Bitcoin tuo toivoa ja mahdollisuuksia etel\u00e4afrikkalaisille",
	"home_link_title_equality_2": "Miten Bitcoin voi olla k\u00e4\u00e4nteentekij\u00e4 mustille amerikkalaisille",
	"home_link_title_property_rights_1": "Bitcoin on t\u00e4ydellinen omaisuuden muoto",
	"home_link_title_property_rights_2": "Bitcoin vs kiinteist\u00f6t",
	"home_link_title_housing_1": "Miten Bitcoin tekee asumisesta j\u00e4lleen edullista",
	"home_link_title_business_3": "Bitcoin vs osakkeet",
	"home_link_title_business_1": "Opi, miksi Bitcoin on hyv\u00e4 yrityksille",
	"home_link_title_business_2": "Saa paikallinen yritys hyv\u00e4ksym\u00e4\u00e4n Bitcoin",
	"home_link_title_crowdfunding_1": "Miten Bitcoin vauhditti Nigerian suurimpia protesteja sukupolveen",
	"home_link_title_crowdfunding_2": "Kanadan rekkakuskiprotesti ker\u00e4si rahaa Bitcoinilla sen j\u00e4lkeen, kun GoFundMe esti lahjoitukset",
	"home_link_title_crowdfunding_3": "Geyser = Joukkorahoita Bitcoinilla",
	"home_link_title_energy_1": "Miten Bitcoin vakauttaa Texasin s\u00e4hk\u00f6verkkoa",
	"home_link_title_energy_2": "Miksi Bitcoin k\u00e4ytt\u00e4\u00e4 energiaa?",
	"home_link_title_energy_3": "Bitcoinin energiank\u00e4ytt\u00f6 ei ole ongelma. T\u00e4ss\u00e4 on syy.",
	"home_link_title_energy_4": "Bitcoin-louhinta vakauttaa s\u00e4hk\u00f6verkkoja kysynt\u00e4vasteen avulla",
	"home_link_title_energy_5": "Bitcoin-louhijat tuovat vesivoimaa Afrikan maaseutuyhteis\u00f6ille",
	"home_link_title_energy_6": "Miten Bitcoin kannustaa uusiutuvaan energiaan",
	"home_link_title_environment_1": "Miten Bitcoin-louhinta v\u00e4hent\u00e4\u00e4 maailmanlaajuisia metaanip\u00e4\u00e4st\u00f6j\u00e4",
	"home_link_title_environment_2": "Miten Bitcoin-louhinta pelasti kansallispuiston",
	"home_link_title_environment_3": "Bitcoin on maailman vihrein teollisuudenala!",
	"home_link_title_environment_4": "Bitcoin-louhinta est\u00e4\u00e4 soihdutetun maakaasun saastuttamasta ilmakeh\u00e4\u00e4",
	"home_link_title_food_1": "Miten inflaatio vaikuttaa ruoan hintoihin",
	"home_link_title_food_2": "Miten fiat-raha on haitallista ruoalle, maatiloille ja maan maaper\u00e4lle",
	"home_link_title_fine_art": "Bitcoin vs taide",
	"home_link_title_art_1": "Liity Bitcoin-tarraaloitteeseemme",
	"home_link_title_art_2": "L\u00e4het\u00e4 Bitcoin-postikortti tuntemallesi henkil\u00f6lle",
	"home_link_title_art_3": "Tulosta ja kiinnit\u00e4 Bitcoin-lentolehtisi\u00e4",
	"home_link_title_politics_1": "Bitcoin on poliittinen paradoksi",
	"home_link_title_politics_2": "Voit \u00e4\u00e4nest\u00e4\u00e4 paremman rahan puolesta",
	"home_link_title_war_1": "Miten Bitcoin voisi lopettaa loputtomat sodat",
	"home_link_title_war_2": "Bitcoin ja veteraanit: luonnollinen yhteys",
	"home_link_title_war_3": "Miten Bitcoin auttaa siviilejä pakenemaan Sudanin sotaa",
	"home_link_title_coding_1": "Interaktiivinen opetusohjelma Bitcoinin teknisest\u00e4 puolesta",
	"home_link_title_coding_2": "bitcoinSwitch: muunna mik\u00e4 tahansa laite vastaanottamaan Bitcoinia",
	"home_link_title_coding_3": "Koodaa tiesi l\u00e4pi Bitcoinin mysteerien",
	"home_link_title_networks_1": "Live-n\u00e4kym\u00e4 Bitcoin-verkkoon",
	"home_link_title_networks_2": "Bitcoin vs pankit",
	"home_link_title_payments_1": "Bitcoin vs Visa",
	"home_link_title_payments_2": "Katsaus Lightning-verkkoon (v\u00e4litt\u00f6m\u00e4t Bitcoin-maksut)",
	"home_link_title_payments_3": "El Salvadorin Bitcoin-lompakko voi s\u00e4\u00e4st\u00e4\u00e4 salvadorilaisille 400 milj. $ vuosittain rahansiirtomaksuissa",
	"home_link_title_payments_4": "Hanki Lightning-osoitteesi vastaanottaaksesi v\u00e4litt\u00f6mi\u00e4 Bitcoin-maksuja",
	"home_link_title_self_custody_1": "Miten s\u00e4ilytt\u00e4\u00e4 Bitcoinisi turvallisesti",
	"home_link_title_self_custody_2": "6 syyt\u00e4 siirt\u00e4\u00e4 Bitcoinisi p\u00f6rsseist\u00e4",
	"home_link_title_self_custody_3": "Kulta, Bitcoin ja oma hallinnointi",
	"home_link_title_get_started_1": "Opi Bitcoinin perusteet",
	"home_link_title_get_started_2": "Hanki ensimm\u00e4inen Bitcoin-lompakkosi",
	"home_link_title_get_started_3": "Miten ostaa Bitcoinia",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Korkoa korolle -inflaatiolaskuri",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
