/**
 * Creates Finnish (fi) common.json translation file
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'fi';
const today = '2026-04-08';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"common_footer_mission_1": "bitcoin.rocksin teht\u00e4v\u00e4n\u00e4 on nopeuttaa Bitcoinin k\u00e4ytt\u00f6\u00f6nottoa koulutuksen avulla.",
	"common_footer_mission_2": "Opi, miten voit osallistua t\u00e4h\u00e4n avoimen l\u00e4hdekoodin projektiin.",
	"common_footer_follow_first_half": "Seuraa meit\u00e4 Nostrissa etsim\u00e4ll\u00e4",
	"common_footer_follow_second_half": "miss\u00e4 tahansa Nostr-asiakassovelluksessa.",
	"common_footer_what_is_nostr": "Mik\u00e4 on Nostr?",
	"common_footer_about": "Tietoja",
	"common_footer_email_us": "L\u00e4het\u00e4 meille s\u00e4hk\u00f6postia:",
	"common_cta_section_get_started": "ALOITA",
	"common_cta_section_with_bitcoin": "BITCOININ KANSSA",
	"common_cta_section_title_1": "Opi Bitcoinin perusteet",
	"common_cta_section_title_1_alt": "Opi lis\u00e4\u00e4 Bitcoinista",
	"common_cta_section_title_2": "Hanki ensimm\u00e4inen Bitcoin-lompakkosi",
	"common_cta_section_title_3": "Miten ostaa Bitcoinia",
	"common_cta_link_type_email": "S\u00c4HK\u00d6POSTI",
	"common_cta_link_type_guide": "OPAS",
	"common_cta_link_type_website": "VERKKOSIVUSTO",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "MIK\u00c4 ON BITCOIN?",
	"common_what_is_bitcoin_content_1": "Bitcoin on kaksi asiaa: digitaalinen raha ja maksuverkko. Voit l\u00e4hett\u00e4\u00e4 Bitcoinia (digitaalista rahaa) suoraan muille ihmisille k\u00e4ytt\u00e4m\u00e4ll\u00e4 Bitcoin-verkkoa (maksuverkkoa).",
	"common_what_is_bitcoin_content_2": "Bitcoin on radikaalisti uusi tapa s\u00e4ilytt\u00e4\u00e4 ja siirt\u00e4\u00e4 arvoa. Toisin kuin tavalliset rahoitusverkot, Bitcoin-verkko toimii ilman keskusviranomaisia tai luotettuja yll\u00e4pit\u00e4ji\u00e4. T\u00e4m\u00e4 tekee Bitcoinista ensimm\u00e4isen avoimen ja rajattoman rahan.",
	"common_what_is_bitcoin_content_3": "Bitcoin on digitaalinen raha, joka antaa sinulle t\u00e4ydellisen omistajuuden varallisuuteesi. Ensimm\u00e4ist\u00e4 kertaa ihmiskunnan historiassa jokainen voi omistaa omaisuuserän, joka on aidosti niukka, ei vaadi lupaa k\u00e4ytt\u00e4miseen eik\u00e4 sit\u00e4 voida takavarikoida, kun se s\u00e4ilytet\u00e4\u00e4n oikein.",
	"common_what_is_bitcoin_content_4": "Bitcoinia voidaan l\u00e4hett\u00e4\u00e4 minne tahansa maailmassa nopeasti ja edullisesti. Se ei tarvitse kolmatta osapuolta v\u00e4litt\u00e4j\u00e4ksi, kuten pankkia.",
	"common_what_is_bitcoin_content_5": "Bitcoin mahdollistaa kenelle tahansa varallisuutensa turvallisen s\u00e4ilytt\u00e4misen ilman huolta siit\u00e4, ett\u00e4 hallitus varastaa sen tai sy\u00f6 sen arvon inflaation kautta rahan painamisella.",
	"common_what_is_bitcoin_content_6": "Hallitukset kaikkialla voivat painaa lis\u00e4\u00e4 paperirahaa, mutta kukaan ei voi painaa lis\u00e4\u00e4 bitcoinia.",
	"common_what_is_bitcoin_content_7": "Voit helposti hallinnoida Bitcoiniasi itse ottaaksesi sen t\u00e4ysin hallintaasi, mik\u00e4 antaa sinulle t\u00e4yden p\u00e4\u00e4syn Bitcoinin voimaan.",
	"common_what_is_bitcoin_content_8": "Jos osaat ladata sovelluksen, voit hallinnoida Bitcoinia itse ja s\u00e4ilytt\u00e4\u00e4 varallisuutesi luottamatta kehenk\u00e4\u00e4n muuhun.",
	"common_what_is_bitcoin_content_9": "Bitcoin on parempaa rahaa.",
	"common_bitcoin_volatile": "KUULIN, ETT\u00c4 BITCOIN ON ARVOLTAAN VAIHTELEVA. ONKO SE TURVALLISTA?",
	"common_bitcoin_volatile_content_1": "Lyhyell\u00e4 aikav\u00e4lill\u00e4 Bitcoinin vaihtokurssi vaihtelee. T\u00e4t\u00e4 kutsutaan volatiliteetiksi.",
	"common_bitcoin_volatile_content_2": "Mutta p\u00e4ivitt\u00e4inen volatiliteetti 'katoaa' pitk\u00e4ll\u00e4 aikav\u00e4lill\u00e4.",
	"common_bitcoin_volatile_content_3": "Bitcoinin volatiliteetti v\u00e4henee jatkuvasti ajan my\u00f6t\u00e4. Mit\u00e4 useammat ihmiset k\u00e4ytt\u00e4v\u00e4t Bitcoinia pitk\u00e4aikaisena s\u00e4\u00e4st\u00f6tilin\u00e4, sit\u00e4 enemm\u00e4n sen arvo vakiintuu.",
	"common_bitcoin_volatile_content_4": "Monet ihmiset valitsevat arvon s\u00e4ilytt\u00e4misen Bitcoinissa useiden vuosien ajan turvallisena tapana minimoida volatiliteettiriskin ja suojata ostovoimaansa ajan my\u00f6t\u00e4.",
	"common_bitcoin_volatile_content_5": "Joissakin maissa, kuten Venezuelassa, Sudanissa, Libanonissa, Syyriassa, Argentiinassa, Turkissa, Brasiliassa ja monissa muissa, paikallisen valuutan arvo heikkenee niin nopeasti, ett\u00e4 Bitcoin n\u00e4hd\u00e4\u00e4n vakaampana tapana s\u00e4\u00e4st\u00e4\u00e4 rahaa.",
	"common_bitcoin_afford": "MINULLA EI OLE VARAA KOKONAISEEN BITCOINIIN",
	"common_bitcoin_afford_content_1": "Dollari koostuu 100 sentist\u00e4. Bitcoin koostuu 100 000 000 (100 miljoonasta) satsista.",
	"common_bitcoin_afford_content_2": "Sinun ei tarvitse omistaa kokonaista bitcoinia. Useimmat ihmiset omistavat vain satseja. Satsit ovat bitcoinin murto-osia. Esimerkiksi, jos 1 kokonainen bitcoin on 100 000 $, niin 1 $ ostaa sinulle 1 000 satsia!",
	"common_bitcoin_hacked": "ONKO BITCOINIA KOSKAAN HAKKEROITU?",
	"common_bitcoin_hacked_content_1": "Olet ehk\u00e4 kuullut 'Bitcoin-hakkeroinnista' verkossa tai uutisissa. Useimmat ihmiset lukevat n\u00e4m\u00e4 artikkelit ja uskovat, ett\u00e4 Bitcoin-verkko on hakkeroitu. Bitcoin-verkkoa ei kuitenkaan ole koskaan hakkeroitu.",
	"common_bitcoin_hacked_content_2": "Mik\u00e4 on Bitcoin-verkko? Ajattele Bitcoin-verkkoa junaratoina. Junat, jotka kulkevat Bitcoin-verkon junaradoilla, ovat Bitcoin-tapahtumia.",
	"common_bitcoin_hacked_content_3": "Kun luet Bitcoin-hakkeroinnista uutisissa, luet s\u00e4ilytt\u00e4j\u00e4n (kuten FTX) hakkeroinnista tai konkurssista.",
	"common_bitcoin_hacked_content_4": "S\u00e4ilytt\u00e4j\u00e4t ovat yrityksi\u00e4, jotka pitav\u00e4t bitcoiniasi sinun puolestasi. T\u00e4h\u00e4n liittyy kuitenkin riski: bitcoiniesi menett\u00e4minen, kun yritys hoitaa niit\u00e4 huonosti, varastaa ne tai menee konkurssiin.",
	"common_bitcoin_hacked_content_5": "T\u00e4m\u00e4 tapahtui viimeksi FTX:n kanssa.",
	"common_bitcoin_hacked_content_6": "Jokainen, joka luotti FTX:lle bitcoininsa, menetti ne. Jokainen, joka piti bitcoininsa omassa hallinnassa, ei vaikuttunut FTX:st\u00e4 lainkaan. T\u00e4m\u00e4 on omahallinnoidun bitcoinin voima: todellinen rahan hallinta.",
	"common_bitcoin_hacked_content_7": "Sen sijaan, ett\u00e4 j\u00e4t\u00e4t bitcoinisi p\u00f6rssiin tai kuten ETF-rahastoihin, pid\u00e4 ne omassa lompakossasi kaikkien vapaushyotyjen saamiseksi.",
	"common_bitcoin_hacked_content_8": "Kun hallinnoit bitcoiniasi itse, rahasi on suojattu Bitcoin-verkon toimesta. Se on maailman turvallisin rahoitusverkko.",
	"common_bitcoin_hacked_content_9": "Omassa hallinnassa Sam FTX:st\u00e4 ei voi varastaa bitcoiniasi sinulta.",
	"common_bitcoin_hacked_content_10": "Hallitus ei voi painaa lis\u00e4\u00e4 bitcoinia ja aiheuttaa inflaatiota.",
	"common_bitcoin_hacked_content_11": "Omahallinnassa oleva Bitcoin on sinun rahasi, Bitcoin-verkon voiman ansiosta.",
	"common_bitcoin_energy": "MIKSI BITCOIN K\u00c4YTT\u00c4\u00c4 ENERGIAA?",
	"common_bitcoin_energy_content_1": "Bitcoin k\u00e4ytt\u00e4\u00e4 energiaa verkon turvaamiseen ja rahasi suojaamiseen.",
	"common_bitcoin_energy_content_2": "Bitcoin k\u00e4ytt\u00e4\u00e4 merkitt\u00e4v\u00e4n m\u00e4\u00e4r\u00e4n energiaa, ja t\u00e4m\u00e4 on hieno asia monista syist\u00e4.",
	"common_bitcoin_energy_list_1": "Bitcoinissa ei ole talletuspakoja.",
	"common_bitcoin_energy_list_2": "Bitcoin auttaa vakauttamaan s\u00e4hk\u00f6verkkoja louhinnalla.",
	"common_bitcoin_energy_list_3": "Bitcoin v\u00e4hent\u00e4\u00e4 \u00f6ljynporauksen p\u00e4\u00e4st\u00f6j\u00e4.",
	"common_bitcoin_energy_list_4": "Bitcoin k\u00e4ytt\u00e4\u00e4 v\u00e4hemm\u00e4n energiaa kuin amerikkalaiset k\u00e4ytt\u00e4v\u00e4t jouluvaloisin vuosittain.",
	"common_bitcoin_energy_list_5": "Bitcoin on maailman vihrein teollisuudenala!",
	"common_cic_intro_1": "Monet ihmiset tiet\u00e4v\u00e4t korkoa korolle -ilmi\u00f6st\u00e4, mutta harvat tiet\u00e4v\u00e4t korkoa korolle -inflaatiosta.",
	"common_cic_intro_2": "Korkoa korolle -inflaatiolaskurillamme voit helposti laskea, kuinka paljon palkkasi t\u00e4ytyy nousta s\u00e4ilytt\u00e4\u00e4ksesi ostovoimasi ajan my\u00f6t\u00e4.",
	"common_cic_intro_3": "Sy\u00f6t\u00e4 vain nykyinen palkkasi, inflaatioaste ja laskettavien vuosien m\u00e4\u00e4r\u00e4, ja laskurimme n\u00e4ytt\u00e4\u00e4, mik\u00e4 palkkasi t\u00e4ytyy olla pysy\u00e4kseen inflaation tahdissa.",
	"common_current_salary": "nykyinen palkka",
	"common_inflation_rate": "inflaatioaste",
	"common_year": "vuosi",
	"common_years": "vuotta",
	"common_result_starting_message": "T\u00e4yt\u00e4 yll\u00e4 oleva lomake ja paina laske.",
	"common_error_message": "Virhe: T\u00e4yt\u00e4 kaikki 3 lomakekentt\u00e4\u00e4.",
	"common_result_message_1": "Inflaatioasteella",
	"common_result_message_2": "sinun",
	"common_result_message_3": "palkkasi t\u00e4ytyy nousta tasolle",
	"common_result_message_in": "",
	"common_result_message_4": "s\u00e4ilytt\u00e4\u00e4ksesi ostovoimasi.",
	"common_calculate_button_text": "LASKE",
	"common_learn_more": "LIS\u00c4TIETOJA",
	"common_success": "ONNISTUI!",
	"common_choose_your_country": "Valitse maasi",
	"common_country_usa": "USA",
	"common_country_canada": "Kanada",
	"common_submit": "L\u00c4HET\u00c4",
	"common_language_afrikaans": "AFRIKAANS",
	"common_language_arabic": "ARABIA",
	"common_language_basque": "BASKI",
	"common_language_bulgarian": "BULGARIA",
	"common_language_catalan": "KATALAANI",
	"common_language_chinese": "KIINA",
	"common_language_croatian": "KROATIA",
	"common_language_czech": "TSHEKKI",
	"common_language_danish": "TANSKA",
	"common_language_dutch": "HOLLANTI",
	"common_language_english": "ENGLANTI",
	"common_language_estonian": "VIRO",
	"common_language_filipino": "FILIPINO",
	"common_language_finnish": "SUOMI",
	"common_language_french": "RANSKA",
	"common_language_german": "SAKSA",
	"common_language_greek": "KREIKKA",
	"common_language_hausa": "HAUSA",
	"common_language_hebrew": "HEPREA",
	"common_language_hindi": "HINDI",
	"common_language_hungarian": "UNKARI",
	"common_language_indonesian": "INDONESIA",
	"common_language_irish": "IIRI",
	"common_language_italian": "ITALIA",
	"common_language_japanese": "JAPANI",
	"common_language_korean": "KOREA",
	"common_language_malay": "MALAIJI",
	"common_language_norwegian": "NORJA",
	"common_language_persian": "PERSIA",
	"common_language_polish": "PUOLA",
	"common_language_portuguese": "PORTUGALI",
	"common_language_russian": "VEN\u00c4J\u00c4",
	"common_language_sinhala": "SINGALEESI",
	"common_language_slovak": "SLOVAKKI",
	"common_language_slovenian": "SLOVEENI",
	"common_language_spanish": "ESPANJA",
	"common_language_swahili": "SWAHILI",
	"common_language_swedish": "RUOTSI",
	"common_language_thai": "THAI",
	"common_language_turkish": "TURKKI",
	"common_language_urdu": "URDU",
	"common_language_vietnamese": "VIETNAM",
	"common_language_yoruba": "JORUBA",
	"common_stickers_bulk_mess": "Etkö halua vaivautua tiedostojen kanssa itse?",
	"common_stickers_bulk_want": "Haluatko enemm\u00e4n kuin vain muutaman tarran?",
	"common_stickers_bulk_store": "Tilaa tarroja suuremp\u00e4na er\u00e4n\u00e4 samalta painajalta, jota me k\u00e4yt\u00e4mme.",
	"common_stickers_bulk_cheaper": "Mit\u00e4 enemm\u00e4n tarroja ostat, sit\u00e4 halvempia ne ovat kappalehinnaltaan.",
	"common_stickers_print_instructions_1": "Voit osallistua tulostamalla omat tarrasi, riippumatta asuinpaikastasi! Klikkaa kieltesi alla ladataksesi tarratiedostot ja ohjeet.",
	"common_stickers_print_instructions_2": "Huomaa: kaikki tarrat eiv\u00e4t ole saatavilla kaikilla kielill\u00e4.",
	"common_stickers_request_language_1": "Etkö n\u00e4e kieltesi?",
	"common_stickers_request_language_2": "T\u00e4yt\u00e4 alla oleva lomake pyyt\u00e4\u00e4ksesi tarratiedostoja omalla kielelläsi.",
	"common_stickers_dimensions": "Mitat:",
	"common_stickers_type": "Tyyppi:",
	"common_stickers_material": "Materiaali:",
	"common_stickers_where_to_print": "Miss\u00e4 tulostaa:",
	"common_stickers_type_die_cut": "muotoiltu tarra",
	"common_stickers_material_vinyl": "vinyylitarrat ulkok\u00e4ytt\u00f6\u00f6n",
	"common_stickers_printer": "K\u00e4yt\u00e4mme StickerMule.comia, mutta voit k\u00e4ytt\u00e4\u00e4 mit\u00e4 tahansa tarrayrityst\u00e4.",
	"common_stickers_dimensions_danger": "11,4544 cm x 8,382 cm (4,51 in x 3,3 in)",
	"common_stickers_dimensions_warning": "10,414 cm x 9,2202 cm (4,1 in x 3,63 in)",
	"common_stickers_dimensions_caution": "12,0142 cm x 7,9502 cm (4,73 in x 3,13 in)",
	"common_stickers_dimensions_fix": "11,3792 cm x 6,8072 cm (4,48 in x 2,68 in)",
	"common_stickers_dimensions_study": "14,605 cm x 5,1308 cm (5,75 in x 2,02 in)",
	"common_stickers_dimensions_bdhi": "21,59 cm x 4,6482 cm (8,5 in x 1,83 in)",
	"common_stickers_dimensions_cure_v2": "6,35 cm x 12,7 cm (2,5 in x 5 in)",
	"common_stickers_dimensions_got_inflation": "7,9248 cm x 14,605 cm (3,12 in x 5,75 in)",
	"common_stickers_dimensions_what_if": "21,7932 cm x 7,62 cm (8,58 in x 3 in)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20,995 cm x 6,35 cm (8,25 in x 2,5 in)",
	"common_nostr_join": "LIITY NOSTRIIN NYT",
	"common_nostr_protocol_header": "Protokolla, ei alusta",
	"common_nostr_protocol_c1": "Nostr on uusi protokolla, jonka avulla voit kommunikoida verkossa ilman sensuurin, alustan poiston tai n\u00e4kyvyyden v\u00e4hent\u00e4misen pelkoa",
	"common_nostr_protocol_c2": "Alustat kuten Twitter ja Facebook ovat yhden yrityksen hallinnassa, mutta kukaan ei hallitse Nostr-protokollaa.",
	"common_nostr_freedom_header": "Vapaus siirty\u00e4",
	"common_nostr_freedom_c1": "Nostr on samankaltainen kuin s\u00e4hk\u00f6posti. Kukaan ei hallitse s\u00e4hk\u00f6postiprotokollaa, ja kuka tahansa voi rakentaa asiakasohjelman (kuten Gmail, Hotmail jne.) sen p\u00e4\u00e4lle.",
	"common_nostr_freedom_c2": "Kukaan ei hallitse Nostr-protokollaa, ja kuka tahansa voi rakentaa asiakasohjelman (kuten Damus, Amethyst jne.) sen p\u00e4\u00e4lle.",
	"common_nostr_freedom_c3": "Jos et pid\u00e4 tietyn asiakasohjelman toiminnasta, voit siirt\u00e4\u00e4 Nostr-tilisi saumattomasti toiseen asiakasohjelmaan menett\u00e4m\u00e4tt\u00e4 seuraajiasi tai sis\u00e4lt\u00f6\u00e4si.",
	"common_nostr_bitcoin_header": "Bitcoin on sis\u00e4\u00e4nrakennettu",
	"common_nostr_bitcoin_c1": "Bitcoin on rakennettu natiivisti Nostr-protokollaan. Jos n\u00e4et sis\u00e4lt\u00f6\u00e4, josta pid\u00e4t, voit helposti z\u00e4p\u00e4t\u00e4 bitcoinia jollekulle kiitokseksi!",
	"common_nostr_bitcoin_c2": "Keskitetyill\u00e4 alustoilla kuten Twitteriss\u00e4 ja Facebookissa yritys ansaitsee rahaa sis\u00e4ll\u00f6st\u00e4si. Mutta avoimissa protokollissa kuten Nostrissa sin\u00e4 ansaitset rahaa sis\u00e4ll\u00f6st\u00e4si.",
	"common_nostr_download_client": "LATAA ILMAINEN ASIAKASOHJELMA LIITTY\u00c4KSESI NOSTRIIN",
	"common_nostr_iphone_clients": "iPhone-asiakasohjelmat",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "iPhone-sovellus",
	"common_nostr_first_client": "Suositeltu ensimm\u00e4inen asiakasohjelma",
	"common_nostr_wallet_built_in": "Bitcoin-zap-lompakko sis\u00e4\u00e4nrakennettu",
	"common_nostr_download_now": "LATAA NYT",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "Tuttu k\u00e4ytt\u00f6liittym\u00e4",
	"common_nostr_separate_wallet": "Vaatii erillisen bitcoin-lompakon",
	"common_nostr_android_clients": "Android-asiakasohjelmat",
	"common_nostr_android_app": "Android-sovellus",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "Paljon ominaisuuksia",
	"common_nostr_browser_clients": "Selainpohjaiset asiakasohjelmat",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "Verkkoasiakasohjelma",
	"common_nostr_simple": "Erittäin yksinkertainen",
	"common_nostr_test": "Helppo tapa kokeilla Nostria testitilill\u00e4",
	"common_nostr_view_client": "N\u00c4YT\u00c4 ASIAKASOHJELMA",
	"common_kit_printer": "Suosittelemme VistaPrint.comia Bitcoin-yrityspaketin esitteiden tulostamiseen. Voit kuitenkin k\u00e4ytt\u00e4\u00e4 mit\u00e4 tahansa painoyrityst\u00e4, kunhan he pystyv\u00e4t kaksipuoliseen tulostukseen.",
	"common_kit_link_to_print": "Linkki tulostukseen:",
	"common_kit_fold": "Taitto:",
	"common_kit_fold_trifold": "Kolmitaitto",
	"common_kit_unfolded_size": "Avattu koko:",
	"common_kit_unfolded_size_bbk": "Letter-koko (8,5 in x 11 in)",
	"common_kit_paper_thickness": "Paperin paksuus:",
	"common_kit_paper_thickness_standard": "Standardi",
	"common_kit_paper_stock": "Paperilaji:",
	"common_kit_paper_stock_glossy": "Kiilt\u00e4v\u00e4",
	"common_kit_exterior_print_file": "Ulkopuolen tulostustiedosto:",
	"common_kit_interior_print_file": "Sis\u00e4puolen tulostustiedosto:",
	"common_kit_cta_header": "Saa paikallinen yritys hyv\u00e4ksym\u00e4\u00e4n Bitcoin",
	"common_biz_learn": "Opi, miksi Bitcoin on hyv\u00e4 yrityksille",
	"common_biz_wallets": "Hanki Bitcoin-lompakko vastaanottaaksesi Bitcoin-maksuja",
	"common_biz_maps": "Listaudu Bitcoin-kauppiaskarttoihin",
	"common_biz_stickers": "Ilmaiset 'Bitcoin hyv\u00e4ksyt\u00e4\u00e4n t\u00e4\u00e4ll\u00e4' -tarrat",
	"common_biz_rewards": "Bitcoin-palkinnot",
	"common_biz_accounting": "Bitcoin-kirjanpito-opas",
	"common_biz_faq": "Usein kysytyt kysymykset",
	"common_biz_kit": "Tulosta oma Bitcoin-yrityspakettisi",
	"common_biz_accept_bitcoin_payments": "VASTAANOTA BITCOIN-MAKSUJA",
	"common_biz_ready": "OLETKO VALMIS VASTAANOTTAMAAN BITCOINIA YRITYKSESSÄSI?",
	"common_biz_more": "LIS\u00c4\u00c4 YRITYSRESURSSEJA",
	"common_self_custody": "OMA HALLINNOINTI",
	"common_not_your_keys": "EI SINUN AVAIMESI",
	"common_cold_wallet": "KYLM\u00c4 LOMPAKKO",
	"common_hot_wallet": "KUUMA LOMPAKKO",
	"common_sticker_files_mission_1": "Teht\u00e4v\u00e4n\u00e4mme on auttaa sinua oranssipilleröim\u00e4\u00e4n enemm\u00e4n ihmisi\u00e4 laittamalla Bitcoin-tarroja julkisille paikoille. Kaikissa tarroissa on QR-koodit, jotka linkitt\u00e4v\u00e4t opetussivuille aiheesta",
	"common_sticker_files_mission_2": "Bitcoin",
	"common_sticker_files_mission_3": "inflaatio",
	"common_sticker_files_mission_4": "Jos asut Yhdysvalloissa tai Kanadassa, voit",
	"common_sticker_files_mission_5": "pyyt\u00e4\u00e4 ilmaisen englanninkielisten tarrojen paketin",
	"common_published_by": "Julkaisija",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "Bitcoin-koulutusta vuodesta 2022",
	"common_publisher_open_source": "Avoimen l\u00e4hdekoodin projekti",
	"common_reviewed_accuracy": "\u2713 Tarkistettu tarkkuuden osalta: 2026",
	"common_footer_tagline": "Nopeutetaan Bitcoinin k\u00e4ytt\u00f6\u00f6nottoa koulutuksen avulla.",
	"common_footer_contribute": "Osallistu",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "L\u00e4hteet"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
