/**
 * Creates Swedish (sv) common_sv.json translation file
 */
const fs = require('fs');
const path = require('path');
const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'sv';
const today = '2026-04-02';

const data = {
	"@metadata": { "authors": ["Satoshi"], "last-updated": today, "locale": lang },
	"common_footer_mission_1": "bitcoin.rocks uppdrag är att påskynda bitcoinanvändningen genom utbildning.",
	"common_footer_mission_2": "Lär dig hur du kan bidra till detta open source-projekt.",
	"common_footer_follow_first_half": "Följ oss på Nostr genom att söka efter",
	"common_footer_follow_second_half": "i valfri Nostr-klient.",
	"common_footer_what_is_nostr": "Vad är Nostr?",
	"common_footer_about": "Om oss",
	"common_footer_email_us": "Maila oss:",
	"common_cta_section_get_started": "KOM IGÅNG",
	"common_cta_section_with_bitcoin": "MED BITCOIN",
	"common_cta_section_title_1": "Lär dig grunderna i Bitcoin",
	"common_cta_section_title_1_alt": "Lär dig mer om Bitcoin",
	"common_cta_section_title_2": "Skaffa din första Bitcoin-plånbok",
	"common_cta_section_title_3": "Hur man köper Bitcoin",
	"common_cta_link_type_email": "E-POST",
	"common_cta_link_type_guide": "GUIDE",
	"common_cta_link_type_website": "WEBB",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "VAD ÄR BITCOIN?",
	"common_what_is_bitcoin_content_1": "Bitcoin är två saker: digitala pengar och ett betalningsnätverk. Du kan skicka Bitcoin (digitala pengar) direkt till andra människor med hjälp av Bitcoin-nätverket (betalningsnätverket).",
	"common_what_is_bitcoin_content_2": "Bitcoin är ett radikalt nytt sätt att lagra och överföra värde. Till skillnad från vanliga finansiella nätverk kan Bitcoin-nätverket fungera utan centrala myndigheter eller betrodda förvaringsinstitut. Det gör Bitcoin till de första öppna och gränslösa pengarna i historien.",
	"common_what_is_bitcoin_content_3": "Bitcoin är digitala pengar som ger dig fullständigt ägande av din förmögenhet. För första gången i mänsklighetens historia kan alla äga en tillgång som är genuint knapp, inte kräver tillstånd att använda och vid korrekt förvaring inte kan konfiskeras.",
	"common_what_is_bitcoin_content_4": "Bitcoin kan skickas vart som helst i världen, snabbt och billigt. Det behöver ingen mellanhand som en bank.",
	"common_what_is_bitcoin_content_5": "Bitcoin gör det möjligt för vem som helst att säkert lagra sin förmögenhet utan oro för att staten ska stjäla den eller urholka dess värde genom att trycka pengar.",
	"common_what_is_bitcoin_content_6": "Stater över hela världen kan trycka mer papperspengar, men ingen kan trycka mer bitcoin.",
	"common_what_is_bitcoin_content_7": "Du kan enkelt ta din Bitcoin i eget förvar och ta full kontroll, vilket ger dig full tillgång till Bitcoins kraft.",
	"common_what_is_bitcoin_content_8": "Om du kan ladda ner en app kan du ta Bitcoin i eget förvar och lagra din förmögenhet utan beroende av någon annan.",
	"common_what_is_bitcoin_content_9": "Bitcoin är bättre pengar.",
	"common_bitcoin_volatile": "JAG HAR HÖRT ATT BITCOIN ÄR VOLATILT. ÄR DET SÄKERT?",
	"common_bitcoin_volatile_content_1": "På kort sikt tenderar Bitcoins växelkurs att fluktuera. Detta kallas volatilitet.",
	"common_bitcoin_volatile_content_2": "Men volatiliteten du ser dagligen 'försvinner' på lång sikt.",
	"common_bitcoin_volatile_content_3": "Bitcoin blir allt mindre volatilt med tiden. Ju fler människor som använder Bitcoin som ett långsiktigt sparkonto, desto mer stabiliseras dess värde.",
	"common_bitcoin_volatile_content_4": "Många väljer att lagra värde i Bitcoin under många år som ett säkert sätt att minimera volatilitetsrisken och skydda sin köpkraft över tid.",
	"common_bitcoin_volatile_content_5": "I vissa länder, som Venezuela, Sudan, Libanon, Syrien, Argentina, Turkiet, Brasilien och många andra, tappar den lokala valutan värde så snabbt att Bitcoin uppfattas som ett stabilare sätt att spara.",
	"common_bitcoin_afford": "JAG HAR INTE RÅD MED EN HEL BITCOIN",
	"common_bitcoin_afford_content_1": "En krona består av 100 ören. En Bitcoin består av 100 000 000 (100 miljoner) satoshi.",
	"common_bitcoin_afford_content_2": "Du behöver inte äga en hel bitcoin. De flesta äger bara satoshi. Satoshi är bråkdelar av en bitcoin. Till exempel, om 1 hel bitcoin kostar 100 000 dollar, köper du 1 000 satoshi för 1 dollar!",
	"common_bitcoin_hacked": "HAR BITCOIN NÅGONSIN HACKATS?",
	"common_bitcoin_hacked_content_1": "Du kanske har hört om 'Bitcoin-hack' på internet eller i nyheterna. De flesta läser dessa artiklar och tror att Bitcoin-nätverket har hackats. Men Bitcoin-nätverket har aldrig hackats.",
	"common_bitcoin_hacked_content_2": "Vad är Bitcoin-nätverket? Tänk dig Bitcoin-nätverket som järnvägsspår. Tågen som åker på Bitcoin-nätverkets spår är Bitcoin-transaktioner.",
	"common_bitcoin_hacked_content_3": "När du läser om Bitcoin-hack i nyheterna läser du om att ett förvaringsinstitut (som FTX) hackades eller gick i konkurs.",
	"common_bitcoin_hacked_content_4": "Förvaringsinstitut är företag som förvarar din bitcoin åt dig. Men det medför risk: att förlora din bitcoin när företaget missköter sig, stjäl den eller lägger ner.",
	"common_bitcoin_hacked_content_5": "Senast hände det med FTX.",
	"common_bitcoin_hacked_content_6": "Alla som litade på FTX med sin bitcoin förlorade den. Alla som hade sin bitcoin i eget förvar påverkades inte alls av FTX-kollapsen. Det är kraften i eget förvar av bitcoin: verklig kontroll över dina pengar.",
	"common_bitcoin_hacked_content_7": "Istället för att lämna din bitcoin på en börs eller i ett omslag som en ETF, håll den i din egen plånbok för alla frihetens fördelar.",
	"common_bitcoin_hacked_content_8": "När du har din bitcoin i eget förvar skyddas dina pengar av Bitcoin-nätverket. Det är det säkraste finansiella nätverket i världen.",
	"common_bitcoin_hacked_content_9": "I eget förvar kan Sam från FTX inte stjäla din bitcoin.",
	"common_bitcoin_hacked_content_10": "Staten kan inte trycka mer bitcoin och orsaka inflation.",
	"common_bitcoin_hacked_content_11": "Bitcoin i eget förvar är dina pengar, tack vare Bitcoin-nätverkets kraft.",
	"common_bitcoin_energy": "VARFÖR FÖRBRUKAR BITCOIN ENERGI?",
	"common_bitcoin_energy_content_1": "Bitcoin förbrukar energi för att säkra nätverket och skydda dina pengar.",
	"common_bitcoin_energy_content_2": "Bitcoin förbrukar en betydande mängd energi, och det är fantastiskt av många anledningar.",
	"common_bitcoin_energy_list_1": "Bitcoin har inga bankrusningar.",
	"common_bitcoin_energy_list_2": "Bitcoin hjälper till att stabilisera elnät genom bitcoin-mining.",
	"common_bitcoin_energy_list_3": "Bitcoin minskar utsläpp från oljeutvinning.",
	"common_bitcoin_energy_list_4": "Bitcoin förbrukar mindre energi än vad amerikaner använder på julbelysning varje år.",
	"common_bitcoin_energy_list_5": "Bitcoin är den grönaste industrin på jorden!",
	"common_cic_intro_1": "Många känner till ränta på ränta, men få känner till sammansatt inflation.",
	"common_cic_intro_2": "Med vår kalkylator för sammansatt inflation kan du enkelt beräkna hur mycket din lön måste öka för att behålla din köpkraft över tid.",
	"common_cic_intro_3": "Ange helt enkelt din nuvarande lön, inflationstakt och antal år du vill beräkna, så visar vår kalkylator vad din lön behöver vara för att hålla jämna steg med inflationen.",
	"common_current_salary": "nuvarande lön",
	"common_inflation_rate": "inflationstakt",
	"common_year": "år",
	"common_years": "år",
	"common_result_starting_message": "Fyll i formuläret ovan och klicka på beräkna.",
	"common_error_message": "Fel: Fyll i alla 3 fälten i formuläret.",
	"common_result_message_1": "Vid en inflationstakt på",
	"common_result_message_2": "din",
	"common_result_message_3": "lön måste öka till",
	"common_result_message_in": "på",
	"common_result_message_4": "för att behålla din köpkraft.",
	"common_calculate_button_text": "BERÄKNA",
	"common_learn_more": "LÄR DIG MER",
	"common_success": "KLART!",
	"common_choose_your_country": "Välj ditt land",
	"common_country_usa": "USA",
	"common_country_canada": "Kanada",
	"common_submit": "SKICKA",
	"common_language_afrikaans": "AFRIKAANS",
	"common_language_arabic": "ARABISKA",
	"common_language_basque": "BASKISKA",
	"common_language_bulgarian": "BULGARISKA",
	"common_language_catalan": "KATALANSKA",
	"common_language_chinese": "KINESISKA",
	"common_language_croatian": "KROATISKA",
	"common_language_czech": "TJECKISKA",
	"common_language_danish": "DANSKA",
	"common_language_dutch": "NEDERLÄNDSKA",
	"common_language_english": "ENGELSKA",
	"common_language_estonian": "ESTNISKA",
	"common_language_filipino": "FILIPPINSKA",
	"common_language_finnish": "FINSKA",
	"common_language_french": "FRANSKA",
	"common_language_german": "TYSKA",
	"common_language_greek": "GREKISKA",
	"common_language_hausa": "HAUSA",
	"common_language_hebrew": "HEBREISKA",
	"common_language_hindi": "HINDI",
	"common_language_hungarian": "UNGERSKA",
	"common_language_indonesian": "INDONESISKA",
	"common_language_irish": "IRISKA",
	"common_language_italian": "ITALIENSKA",
	"common_language_japanese": "JAPANSKA",
	"common_language_korean": "KOREANSKA",
	"common_language_malay": "MALAJISKA",
	"common_language_norwegian": "NORSKA",
	"common_language_persian": "PERSISKA",
	"common_language_polish": "POLSKA",
	"common_language_portuguese": "PORTUGISISKA",
	"common_language_russian": "RYSKA",
	"common_language_sinhala": "SINGALESISKA",
	"common_language_slovak": "SLOVAKISKA",
	"common_language_slovenian": "SLOVENSKA",
	"common_language_spanish": "SPANSKA",
	"common_language_swahili": "SWAHILI",
	"common_language_swedish": "SVENSKA",
	"common_language_thai": "THAILÄNDSKA",
	"common_language_turkish": "TURKISKA",
	"common_language_urdu": "URDU",
	"common_language_vietnamese": "VIETNAMESISKA",
	"common_language_yoruba": "YORUBA",
	"common_stickers_bulk_mess": "Vill du inte hantera filerna själv?",
	"common_stickers_bulk_want": "Vill du ha fler än bara några klistermärken?",
	"common_stickers_bulk_store": "Beställ klistermärken i bulk från samma tryckeri som vi använder.",
	"common_stickers_bulk_cheaper": "Ju fler klistermärken du köper, desto billigare blir varje klistermärke.",
	"common_stickers_print_instructions_1": "Du kan delta genom att skriva ut dina egna klistermärken oavsett var du bor! Klicka på ditt språk nedan för att ladda ner klistermärkesfiler och instruktioner.",
	"common_stickers_print_instructions_2": "Obs: inte alla klistermärken finns tillgängliga på alla språk.",
	"common_stickers_request_language_1": "Ser du inte ditt språk?",
	"common_stickers_request_language_2": "Fyll i formuläret nedan för att begära klistermärkesfiler på ditt språk.",
	"common_stickers_dimensions": "Mått:",
	"common_stickers_type": "Typ:",
	"common_stickers_material": "Material:",
	"common_stickers_where_to_print": "Var man skriver ut:",
	"common_stickers_type_die_cut": "stansad klistermärke",
	"common_stickers_material_vinyl": "vinyl-klistermärken för utomhusbruk",
	"common_stickers_printer": "Vi använder StickerMule.com, men du kan använda vilket tryckeri som helst.",
	"common_stickers_dimensions_danger": "11,4544 cm x 8,382 cm (4,51 in x 3,3 in)",
	"common_stickers_dimensions_warning": "10,414 cm x 9,2202 cm (4,1 in x 3,63 in)",
	"common_stickers_dimensions_caution": "12,0142 cm x 7,9502 cm (4,73 in x 3,13 in)",
	"common_stickers_dimensions_fix": "11,3792 cm x 6,8072 cm (4,48 in x 2,68 in)",
	"common_stickers_dimensions_study": "14,605 cm x 5,1308 cm (5,75 in x 2,02 in)",
	"common_stickers_dimensions_bdhi": "21,59 cm x 4,6482 cm (8,5 in x 1,83 in)",
	"common_stickers_dimensions_cure_v2": "6,35 cm x 12,7 cm (2,5 in x 5 in)",
	"common_stickers_dimensions_got_inflation": "7,9248 cm x 14,605 cm (3,12 in x 5,75 in)",
	"common_stickers_dimensions_what_if": "21,7932 cm x 7,62 cm (8,58 in x 3 in)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20,995 cm x 6,35 cm (8,25 in x 2,5 in)",
	"common_nostr_join": "GÅ MED I NOSTR",
	"common_nostr_protocol_header": "Ett protokoll, inte en plattform",
	"common_nostr_protocol_c1": "Nostr är ett nytt protokoll som låter dig kommunicera online utan oro för censur, avstängning eller nedtystning",
	"common_nostr_protocol_c2": "Plattformar som Twitter och Facebook kontrolleras av ett företag, men ingen kontrollerar Nostr-protokollet.",
	"common_nostr_freedom_header": "Frihet att flytta",
	"common_nostr_freedom_c1": "Nostr liknar e-post. Ingen kontrollerar e-postprotokollet och vem som helst kan bygga en klient ovanpå det (som Gmail, Hotmail etc.).",
	"common_nostr_freedom_c2": "Ingen kontrollerar Nostr-protokollet och vem som helst kan bygga en klient ovanpå det (som Damus, Amethyst etc.).",
	"common_nostr_freedom_c3": "Om du inte gillar hur en viss klient fungerar kan du sömlöst flytta ditt Nostr-konto till en annan klient utan att förlora följare eller innehåll.",
	"common_nostr_bitcoin_header": "Bitcoin är inbyggt",
	"common_nostr_bitcoin_c1": "Bitcoin är nativt inbyggt i Nostr-protokollet. Om du ser innehåll du gillar kan du enkelt skicka bitcoin till någon som tack!",
	"common_nostr_bitcoin_c2": "På centraliserade plattformar som Twitter och Facebook tjänar det centraliserade företaget pengar på ditt innehåll. Men på öppna protokoll som Nostr tjänar du pengar på ditt innehåll.",
	"common_nostr_download_client": "LADDA NER EN GRATIS KLIENT OCH GÅ MED I NOSTR",
	"common_nostr_iphone_clients": "iPhone-klienter",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "iPhone-app",
	"common_nostr_first_client": "Rekommenderad första klient",
	"common_nostr_wallet_built_in": "Inbyggd Bitcoin-plånbok för zaps",
	"common_nostr_download_now": "LADDA NER NU",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "Bekant gränssnitt",
	"common_nostr_separate_wallet": "Kräver separat Bitcoin-plånbok",
	"common_nostr_android_clients": "Android-klienter",
	"common_nostr_android_app": "Android-app",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "Många funktioner",
	"common_nostr_browser_clients": "Webbläsarklienter",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "Webbklient",
	"common_nostr_simple": "Mycket enkel",
	"common_nostr_test": "Enkelt sätt att testa Nostr med ett testkonto",
	"common_nostr_view_client": "VISA KLIENT",
	"common_kit_printer": "Vi rekommenderar VistaPrint.com för att skriva ut dina egna flygblad till Bitcoin-företagspaketet. Du kan dock använda vilket tryckeri som helst som kan dubbelsidig utskrift.",
	"common_kit_link_to_print": "Länk till utskrift:",
	"common_kit_fold": "Vikning:",
	"common_kit_fold_trifold": "Trevikt",
	"common_kit_unfolded_size": "Utvikt storlek:",
	"common_kit_unfolded_size_bbk": "Letter-format (8,5 in x 11 in)",
	"common_kit_paper_thickness": "Papperstjocklek:",
	"common_kit_paper_thickness_standard": "Standard",
	"common_kit_paper_stock": "Papperstyp:",
	"common_kit_paper_stock_glossy": "Glansigt",
	"common_kit_exterior_print_file": "Utsidans tryckfil:",
	"common_kit_interior_print_file": "Insidans tryckfil:",
	"common_kit_cta_header": "Övertyga ett lokalt företag att acceptera Bitcoin",
	"common_biz_learn": "Lär dig varför Bitcoin är bra för företag",
	"common_biz_wallets": "Skaffa en Bitcoin-plånbok för att ta emot betalningar",
	"common_biz_maps": "Registrera dig på kartor över Bitcoin-handlare",
	"common_biz_stickers": "Gratis klistermärken 'Bitcoin accepteras här'",
	"common_biz_rewards": "Bitcoin-belöningar",
	"common_biz_accounting": "Guide för Bitcoin-bokföring",
	"common_biz_faq": "Vanliga frågor",
	"common_biz_kit": "Skriv ut ditt eget Bitcoin-företagspaket",
	"common_biz_accept_bitcoin_payments": "ACCEPTERA BITCOIN-BETALNINGAR",
	"common_biz_ready": "ÄR DU REDO ATT ACCEPTERA BITCOIN I DITT FÖRETAG?",
	"common_biz_more": "FLER FÖRETAGSRESURSER",
	"common_self_custody": "EGET FÖRVAR",
	"common_not_your_keys": "INTE DINA NYCKLAR",
	"common_cold_wallet": "KALL PLÅNBOK",
	"common_hot_wallet": "VARM PLÅNBOK",
	"common_sticker_files_mission_1": "Vårt uppdrag är att hjälpa dig övertyga fler människor genom att sätta Bitcoin-klistermärken på offentliga platser. Alla våra klistermärken har QR-koder som länkar till utbildningssidor om",
	"common_sticker_files_mission_2": "Bitcoin",
	"common_sticker_files_mission_3": "inflation",
	"common_sticker_files_mission_4": "Om du bor i USA eller Kanada kan du",
	"common_sticker_files_mission_5": "beställa ett gratis paket engelska klistermärken",
	"common_published_by": "Publicerad av",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "Bitcoinutbildning sedan 2022",
	"common_publisher_open_source": "Open source-projekt",
	"common_reviewed_accuracy": "✓ Granskad för noggrannhet: 2026",
	"common_footer_tagline": "Vi påskyndar bitcoinanvändningen genom utbildning.",
	"common_footer_contribute": "Bidra",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "Källor"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}\n\nDone! Created common.json.`);
