/**
 * Creates Catalan (ca) translation files for remaining content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ca';
const today = '2026-04-07';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "Bitcoin no té pànics bancaris",
	"bank_runs_header": "BITCOIN NO TÉ PÀNICS BANCARIS",
	"bank_runs_header_2": "PERÒ EL TEU BANC POTSER SÍ",
	"bank_runs_what": "QUÈ ÉS UN PÀNIC BANCARI?",
	"bank_runs_what_content_1": "Un pànic bancari passa quan massa gent intenta retirar els seus diners del banc al mateix temps.",
	"bank_runs_what_content_2": "Si els bancs no tenen prou diners disponibles per cobrir les retirades, poden col·lapsar completament quan es produeix un pànic bancari.",
	"bank_runs_how": "COM PASSEN ELS PÀNICS BANCARIS?",
	"bank_runs_how_content_1": "El nostre sistema bancari és de 'reserva fraccionària', la qual cosa significa que els bancs no es limiten a guardar els teus diners en una caixa forta i esperar que els gastis o els retiris.",
	"bank_runs_how_content_2": "En lloc d'això, el teu banc agafa els teus diners i els presta o els inverteix. Això pot bloquejar els teus diners durant llargs períodes de temps, tot i que el banc et promet la capacitat de retirar els teus diners en qualsevol moment.",
	"bank_runs_how_content_3": "Llavors, què passa si intentes retirar els teus diners després que el banc ja els hagi prestat o invertit?",
	"bank_runs_how_content_4": "No és un problema si ets l'únic que intenta retirar. El banc simplement agafarà els diners d'algú altre i te'ls donarà. Però què passa quan massa gent intenta retirar al mateix temps?",
	"bank_runs_how_content_5": "Molta gent als EUA ho va descobrir quan va haver-hi un pànic al Silicon Valley Bank el març de 2023.",
	"bank_runs_how_content_6": "El banc havia invertit els diners dels seus clients en bons governamentals que estaven bloquejats fins a 30 anys. Encara pitjor, el valor d'aquests bons havia caigut dràsticament recentment, de manera que Silicon Valley Bank no podia simplement vendre els bons per obtenir els diners dels seus dipositants. Eren insolvents. No tenien prou diners per cobrir les retirades dels seus dipositants.",
	"bank_runs_how_content_7": "A mesura que més gent ho descobria, el problema només empitjorava. Van arribar més sol·licituds de retirada, però moltes no es van processar. Milers d'empreses es van adonar que no podrien pagar els seus empleats a causa de la fallida del banc.",
	"bank_runs_how_content_8": "La FDIC va intervenir i va acceptar compensar els dipositants. Problema resolt? No exactament...",
	"bank_runs_fdic": "L'ASSEGURANÇA DE LA FDIC PROTEGEIX ELS MEUS DINERS?",
	"bank_runs_fdic_content_1": "L'assegurança de la FDIC està dissenyada per protegir els dipositants bancaris en cas que un banc falli. Els dipòsits estan assegurats fins a 250.000$ per dipositant. Sona bé, oi?",
	"bank_runs_fdic_content_2": "No exactament. Si un banc falla, d'on treu els diners la FDIC? Tenen un fons d'assegurança amb 125 mil milions de dòlars.",
	"bank_runs_fdic_content_3": "Sona com molts diners fins que ho compares amb la quantitat de dipòsits que asseguren: gairebé 10 bilions o 10.000 mil milions de dòlars.",
	"bank_runs_fdic_content_4": "La FDIC fins i tot mostra al seu lloc web que només tenen prou diners al seu fons d'assegurança per cobrir poc més de l'1% dels dipòsits.",
	"bank_runs_fdic_content_5": "En cas d'una fallida bancària que excedís el fons d'assegurança de la FDIC, és probable (però no garantit) que el govern dels EUA imprimís diners per compensar els dipositants.",
	"bank_runs_fdic_content_6": "Però imprimir diners causa inflació, de manera que no és una gran solució.",
	"bank_runs_safe": "HI HA BANCS QUE NO FAN SERVIR RESERVA FRACCIONÀRIA?",
	"bank_runs_safe_content_1": "Alguns bancs han intentat ser 'bancs segurs' que no presten ni inverteixen els fons dels dipositants.",
	"bank_runs_safe_content_2": "Tot i que aquests bancs segurs tindrien zero risc de pànics bancaris, les seves sol·licituds han estat denegades per la Reserva Federal. Això significa que no poden operar legalment com a bancs.",
	"bank_runs_safe_content_3": "Com que se'ls ha bloquejat operar, avui no existeixen bancs que no utilitzin reserva fraccionària.",
	"bank_runs_safe_content_4": "Afortunadament, hi ha una manera de sortir del sistema de reserva fraccionària sent el teu propi banc. No, no estem parlant d'amagar efectiu sota el matalàs.",
	"bank_runs_safe_content_5": "Estalviar en efectiu segueix sent vulnerable a la inflació.",
	"bank_runs_safe_content_6": "Estem parlant de Bitcoin: un nou sistema financer que et permet ser el teu propi banc.",
	"bank_runs_protect": "BITCOIN POT PROTEGIR-ME DELS PÀNICS BANCARIS?",
	"bank_runs_protect_content_1": "Sí, Bitcoin és un sistema financer de reserva completa.",
	"bank_runs_protect_content_2": "Els pànics bancaris són impossibles amb Bitcoin sempre que retiris el teu Bitcoin a la teva pròpia cartera. No deixis el teu bitcoin en una borsa o en un embolcall com un ETF de Bitcoin.",
	"bank_runs_protect_content_3": "Consulta la nostra senzilla Guia de Carteres Bitcoin per aprendre com retirar a la teva pròpia cartera.",
	"bank_runs_protect_content_4": "Amb Bitcoin, finalment pots tenir el control dels teus diners."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Guia de Carteres Bitcoin",
	"wallets_description": "Hi ha moltes carteres Bitcoin diferents que difereixen en aspectes importants. Pots determinar si una cartera és adequada per a tu fent-te aquestes senzilles preguntes.",
	"wallets_header": "COM EMMAGATZEMAR EL TEU BITCOIN DE MANERA SEGURA",
	"wallets_s1_c1": "Les carteres Bitcoin són interoperables, de manera que pots enviar Bitcoin a qualsevol persona sense importar quina cartera faci servir.",
	"wallets_s1_c2": "Hi ha moltes carteres Bitcoin diferents que difereixen en aspectes importants. Pots determinar si una cartera és adequada per a tu fent-te aquestes senzilles preguntes:",
	"wallets_question_1": "ÉS UNA CARTERA D'AUTOCUSTÒDIA?",
	"wallets_s2_c1": "Una de les innovacions de Bitcoin és la capacitat d'emmagatzemar-lo sense dependre d'un custodi, com un banc.",
	"wallets_s2_c2": "Si mantens bitcoin en una borsa o en un ETF, perds els beneficis de llibertat de bitcoin.",
	"wallets_s2_c3": "Les carteres d'autocustòdia desbloquegen tot el poder de Bitcoin: diners de llibertat.",
	"wallets_s2_c4": "Amb una cartera d'autocustòdia, ets l'únic amb la capacitat de gastar o transferir els teus diners. Ningú et pot impedir enviar o rebre els teus diners quan fas servir una cartera d'autocustòdia.",
	"wallets_s2_c5": "Les carteres d'autocustòdia també s'anomenen carteres no custodials.",
	"wallets_s3_c1": "Les carteres custodials són carteres on no tens el control dels teus diners.",
	"wallets_s3_c2": "Aquestes carteres són més similars al sistema bancari on has de confiar en un tercer perquè et doni accés als teus diners. Si el teu Bitcoin està en una borsa, estàs fent servir una cartera custodial.",
	"wallets_s3_c3": "Si has comprat un ETF de Bitcoin, estàs fent servir una cartera custodial que no et permet retirar a autocustòdia.",
	"wallets_s3_c4": "Les carteres custodials poden semblar còmodes, però el custodi té la capacitat tècnica de robar tots els fons dels usuaris en qualsevol moment.",
	"wallets_s3_c5": "No les teves claus, no les teves monedes!",
	"wallets_question_2": "ÉS CALENTA O FREDA?",
	"wallets_s4_c1": "Les carteres fredes emmagatzemen les claus del teu Bitcoin d'una manera que mai les exposa a Internet.",
	"wallets_s4_c2": "Això limita significativament els vectors d'atac que un lladre podria fer servir per intentar robar el teu Bitcoin, i s'utilitza millor per a grans quantitats de Bitcoin que no necessites transferir sovint.",
	"wallets_s4_c3": "Pots pensar en una cartera freda com un compte d'estalvi a llarg termini, també conegut com a emmagatzematge en fred.",
	"wallets_s5_c1": "Les carteres calentes emmagatzemen les claus del teu Bitcoin en un dispositiu connectat a Internet, com el teu telèfon.",
	"wallets_s5_c2": "Les carteres calentes generalment es consideren segures, però podrien tenir més vulnerabilitats de seguretat que les carteres fredes.",
	"wallets_s5_c3": "Pots pensar en una cartera calenta com ho faries amb una cartera física. No emmagatzemaries tots els teus estalvis a la teva cartera, però hi guardaries alguns diners per gastar.",
	"wallets_s5_c4": "Les carteres calentes fan molt més fàcil gastar el teu Bitcoin sense haver de treure tots els teus estalvis de l'emmagatzematge en fred.",
	"wallets_question_3": "COM FARÉ UNA CÒPIA DE SEGURETAT DE LA MEVA FRASE DE RECUPERACIÓ?",
	"wallets_s6_c1": "Quan configures la teva cartera Bitcoin, el teu dispositiu generarà una frase de recuperació. Aquesta frase de recuperació (també anomenada frase llavor) conté 12 o 24 paraules.",
	"wallets_s6_c2": "Si alguna vegada perds l'accés a la teva cartera o el teu dispositiu deixa de funcionar, pots introduir aquesta frase de recuperació en una nova cartera per recuperar l'accés al teu Bitcoin.",
	"wallets_s6_c3": "La majoria de carteres inclouen un full de paper per escriure la teva frase de recuperació, però molta gent prefereix fer una còpia de seguretat d'aquesta frase en acer. Això fa molt menys probable perdre la teva frase de recuperació en cas de desastre natural com un incendi o una inundació.",
	"wallets_s6_c4": "Jameson Lopp ha provat 70 kits de còpia de seguretat en acer per ajudar-te a escollir el que és adequat per a tu.",
	"wallets_s6_c5": "Veure la guia de còpies de seguretat en metall de Bitcoin de Jameson aquí.",
	"wallets_s6_c6": "O continua desplaçant-te per explorar les opcions de carteres Bitcoin.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "Busques la nostra Guia de Carteres Lightning?",
	"wallets_starter_wallet": "Excel·lent cartera per principiants",
	"wallets_mobile_app": "Aplicació mòbil",
	"wallets_2fa_support": "Suport 2FA",
	"wallets_air_gap_mode": "Mode air-gap",
	"wallets_air_gap_camera": "Mode air-gap + càmera",
	"wallets_bitcoin_only": "Només Bitcoin",
	"wallets_security_features": "Moltes funcions de seguretat",
	"wallets_free": "100% gratuïta",
	"wallets_coldcard_mk5_costs": "Costa 189$",
	"wallets_coldcard_q_costs": "Costa 289$",
	"wallets_blockstream_jade_costs": "Costa 79$",
	"wallets_foundation_passport_costs": "Costa 199$",
	"wallets_seedsigner_costs": "Les peces costen 50$",
	"wallets_very_affordable": "Molt assequible",
	"wallets_pair_with_phone": "Emparella amb el teu telèfon",
	"wallets_battery": "Bateria recarregable",
	"wallets_build_your_own": "Construeix la teva pròpia",
	"wallets_qwerty_keyboard": "Teclat QWERTY complet",
	"wallets_qr_scanner": "Escàner de codis QR"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "Com Comprar Bitcoin - Guia Pas a Pas",
	"buy_header": "COM COMPRAR BITCOIN",
	"buy_intro_c1": "Comprar Bitcoin per primera vegada pot semblar aclaparador, però en realitat és bastant senzill quan ho desgloses en passos.",
	"buy_intro_c2": "Aquesta guia et guiarà a través del procés de comprar Bitcoin de manera segura i emmagatzemar-lo a la teva pròpia cartera.",
	"buy_step_1_header": "PAS 1: SELECCIONA EL TEU PAÍS",
	"buy_step_1_description": "Diferents països tenen diferents opcions de compra de Bitcoin disponibles. Selecciona el teu país per veure les millors opcions per a tu.",
	"buy_search_countries": "Cerca el teu país",
	"buy_country_united_states": "Estats Units",
	"buy_country_australia": "Austràlia",
	"buy_country_austria": "Àustria",
	"buy_country_belgium": "Bèlgica",
	"buy_country_brazil": "Brasil",
	"buy_country_canada": "Canadà",
	"buy_country_france": "França",
	"buy_country_germany": "Alemanya",
	"buy_country_ireland": "Irlanda",
	"buy_country_italy": "Itàlia",
	"buy_country_netherlands": "Països Baixos",
	"buy_country_new_zealand": "Nova Zelanda",
	"buy_country_spain": "Espanya",
	"buy_country_united_kingdom": "Regne Unit",
	"buy_country_argentina": "Argentina",
	"buy_country_chile": "Xile",
	"buy_country_colombia": "Colòmbia",
	"buy_country_costa_rica": "Costa Rica",
	"buy_country_czech_republic": "República Txeca",
	"buy_country_denmark": "Dinamarca",
	"buy_country_el_salvador": "El Salvador",
	"buy_country_estonia": "Estònia",
	"buy_country_finland": "Finlàndia",
	"buy_country_greece": "Grècia",
	"buy_country_guatemala": "Guatemala",
	"buy_country_hong_kong": "Hong Kong",
	"buy_country_hungary": "Hongria",
	"buy_country_iceland": "Islàndia",
	"buy_country_india": "Índia",
	"buy_country_israel": "Israel",
	"buy_country_japan": "Japó",
	"buy_country_latvia": "Letònia",
	"buy_country_lithuania": "Lituània",
	"buy_country_luxembourg": "Luxemburg",
	"buy_country_malta": "Malta",
	"buy_country_mexico": "Mèxic",
	"buy_country_norway": "Noruega",
	"buy_country_panama": "Panamà",
	"buy_country_poland": "Polònia",
	"buy_country_portugal": "Portugal",
	"buy_country_romania": "Romania",
	"buy_country_singapore": "Singapur",
	"buy_country_slovakia": "Eslovàquia",
	"buy_country_slovenia": "Eslovènia",
	"buy_country_south_africa": "Sud-àfrica",
	"buy_country_south_korea": "Corea del Sud",
	"buy_country_sweden": "Suècia",
	"buy_country_switzerland": "Suïssa",
	"buy_country_thailand": "Tailàndia",
	"buy_country_turkey": "Turquia",
	"buy_country_ukraine": "Ucraïna",
	"buy_country_uruguay": "Uruguai",
	"buy_step_2_header": "PAS 2: TRIA EL TEU MÈTODE DE PAGAMENT",
	"buy_step_2_description": "Hi ha dues maneres principals de comprar Bitcoin: amb transferència bancària o amb efectiu. Cada una té avantatges diferents.",
	"buy_method_bank_transfer": "TRANSFERÈNCIA BANCÀRIA",
	"buy_method_bank_fast": "Ràpid i fàcil",
	"buy_method_bank_less_private": "Menys privat",
	"buy_method_bank_description": "Les transferències bancàries són la manera més comuna de comprar Bitcoin. Són ràpides, còmodes i normalment tenen comissions més baixes.",
	"buy_method_choose_bank": "Tria transferència bancària",
	"buy_method_cash": "EFECTIU",
	"buy_method_cash_private": "Més privat",
	"buy_method_cash_limited": "Opcions limitades",
	"buy_method_cash_description": "Les compres en efectiu ofereixen més privacitat però tenen menys opcions i poden requerir quedar amb algú en persona o fer servir un caixer Bitcoin.",
	"buy_method_choose_cash": "Tria efectiu",
	"buy_step_3_header": "PAS 3: OPCIONS DE COMPRA",
	"buy_step_3_description": "Aquí tens les millors opcions de compra de Bitcoin per al teu país i mètode de pagament:",
	"buy_platform_recommended": "RECOMANAT",
	"buy_platform_strike_description": "Strike és la manera més ràpida i fàcil de comprar Bitcoin amb comissions baixes i suport instantani per a la Xarxa Lightning.",
	"buy_platform_swan_description": "Swan Bitcoin s'especialitza en serveis exclusivament de Bitcoin amb promig de cost en dòlars i recursos educatius.",
	"buy_platform_river_description": "River ofereix compra de Bitcoin, mineria i serveis de custòdia amb un enfocament en l'educació i la seguretat.",
	"buy_platform_coinsquare_description": "Coinsquare és una borsa canadenca de Bitcoin amb un fort compliment normatiu i atenció al client.",
	"buy_platform_kraken_description": "Kraken és una borsa de Bitcoin establerta amb funcions de negociació avançades i una seguretat sòlida.",
	"buy_platform_atm_description": "Els caixers Bitcoin et permeten comprar Bitcoin amb efectiu instantàniament. Troba'n un a prop teu amb Coin ATM Radar.",
	"buy_platform_bisq_description": "Bisq és una borsa descentralitzada entre iguals que permet la negociació privada de Bitcoin sense KYC.",
	"buy_platform_feature_instant": "Compres instantànies",
	"buy_platform_feature_low_fees": "Comissions baixes",
	"buy_platform_feature_lightning": "Xarxa Lightning",
	"buy_platform_feature_dca": "Promig de cost en dòlars",
	"buy_platform_feature_education": "Recursos educatius",
	"buy_platform_feature_withdrawal": "Retirada fàcil",
	"buy_platform_feature_mining": "Mineria de Bitcoin",
	"buy_platform_feature_custody": "Serveis de custòdia",
	"buy_platform_feature_canadian": "Enfocat al Canadà",
	"buy_platform_feature_regulated": "Borsa regulada",
	"buy_platform_feature_support": "Atenció al client",
	"buy_platform_feature_established": "Plataforma establerta",
	"buy_platform_feature_security": "Seguretat sòlida",
	"buy_platform_feature_advanced": "Funcions avançades",
	"buy_platform_feature_cash": "Compres amb efectiu",
	"buy_platform_feature_anonymous": "Més anònim",
	"buy_platform_feature_p2p": "Entre iguals",
	"buy_platform_feature_private": "Negociació privada",
	"buy_platform_feature_decentralized": "Descentralitzat",
	"buy_platform_relai_description": "Relai és una aplicació suïssa exclusivament de Bitcoin amb cartera d'autocustòdia, funcions d'autoinversió i comissions baixes per a usuaris europeus.",
	"buy_platform_feature_bitcoin_only": "Només Bitcoin",
	"buy_platform_feature_self_custody": "Cartera d'autocustòdia",
	"buy_platform_feature_auto_invest": "Plans d'autoinversió",
	"buy_platform_feature_european": "Enfocat a Europa",
	"buy_step_4_header": "PAS 4: EMMAGATZEMA EL TEU BITCOIN DE MANERA SEGURA",
	"buy_step_4_c1": "Després de comprar Bitcoin, el pas més important és moure'l a la teva pròpia cartera on tu controles les claus privades.",
	"buy_step_4_c2": "Deixar Bitcoin en una borsa és arriscat perquè realment no posseeixes el Bitcoin - la borsa sí.",
	"buy_step_4_c3": "Quan controles les teves pròpies claus privades, tens la propietat real del teu Bitcoin i ningú te'l pot treure.",
	"buy_step_4_c4": "Aprèn a triar la cartera Bitcoin adequada per a les teves necessitats:",
	"buy_cta_wallets": "Veure la nostra Guia de Carteres Bitcoin"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Guia de Carteres Lightning de Bitcoin",
	"lightning_description": "Les carteres Lightning et permeten enviar Bitcoin ràpidament i a baix cost mantenint la teva sobirania personal.",
	"lightning_header": "GUIA DE CARTERES LIGHTNING",
	"lightning_s1_c1": "Lightning et permet enviar pagaments de Bitcoin ràpidament i a baix cost.",
	"lightning_s1_c2": "És important saber que fer servir Lightning comporta compromisos. A canvi de pagaments de Bitcoin més ràpids i barats, sovint sacrifiques una mica de seguretat.",
	"lightning_s1_c3": "En general, Lightning s'hauria d'utilitzar només amb petites quantitats de bitcoin. Només hauries d'emmagatzemar grans quantitats de bitcoin en una cartera de maquinari.",
	"lightning_s1_c4": "Consulta la nostra Guia de Carteres de Maquinari per a més informació.",
	"lightning_s1_c5": "No totes les carteres Lightning són iguals. Pots determinar quina cartera té el conjunt adequat de compromisos per a tu fent-te una senzilla pregunta:",
	"lightning_question_1": "QUIN EQUILIBRI DE COMPROMISOS ÉS ADEQUAT PER A MI?",
	"lightning_s2_c1": "Una de les innovacions de Bitcoin és la capacitat d'emmagatzemar-lo sense dependre d'un custodi, com un banc. Les carteres d'autocustòdia desbloquegen tot el poder de Bitcoin.",
	"lightning_s2_c2": "Amb una cartera d'autocustòdia, ets l'únic amb la capacitat de gastar o transferir els teus diners. Ningú et pot aturar, censurar o robar quan fas servir una cartera d'autocustòdia. Aquestes també s'anomenen carteres no custodials.",
	"lightning_s2_c3": "La manera més sobirana d'utilitzar Lightning és executant el teu propi node.",
	"lightning_s2_c4": "Aquesta guia se centra en carteres Lightning senzilles que no requereixen el teu propi node.",
	"lightning_s2_c5": "És important saber que fins i tot fent servir una cartera Lightning no custodial, segueixes confiant que el creador de la cartera no enviarà una actualització maliciosa de l'aplicació i robi els teus fons.",
	"lightning_s3_c1": "Les carteres custodials són carteres on no tens el control dels teus diners.",
	"lightning_s3_c2": "Aquestes carteres són més similars al sistema bancari on has de confiar en un tercer perquè et doni accés als teus diners. Si el teu Bitcoin està en una borsa, estàs fent servir una cartera custodial.",
	"lightning_s3_c3": "Les carteres custodials poden semblar còmodes, però el custodi té la capacitat tècnica de robar tots els fons dels usuaris en qualsevol moment.",
	"lightning_s3_c4": "Algunes persones prefereixen carteres Lightning custodials per a petites quantitats de bitcoin a causa de la seva facilitat d'ús. Només recorda: no les teves claus, no les teves monedes!",
	"lightning_question_2": "TRIA LA TEVA CARTERA",
	"lightning_s4_c1": "Amb tot això en ment, ara pots triar la cartera Lightning que tingui l'equilibri de compromisos adequat per a tu.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "Moltes funcionalitats",
	"lightning_mobile_app": "Aplicació mòbil",
	"lightning_free": "100% gratuïta",
	"lightning_merchants": "Ideal per a comerciants",
	"lightning_starter": "Excel·lent cartera per principiants",
	"lightning_browser": "Basada en navegador",
	"lightning_custodial": "Cartera totalment custodial",
	"lightning_cta_hardware": "Busques la nostra Guia de Carteres de Maquinari Bitcoin?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "Adhesius de Bitcoin gratuïts de bitcoin.rocks",
	"stickers_description": "Posa un adhesiu de Bitcoin en públic per fer que els que t'envolten s'apassionin per Bitcoin.",
	"stickers_header": "ADHESIUS DE BITCOIN GRATUÏTS",
	"stickers_choose_header": "TRIA EL TEU PAQUET D'ADHESIUS",
	"stickers_choose_c1": "La nostra missió és ajudar-te a fer que més gent s'apassioni per Bitcoin posant adhesius de Bitcoin en públic. Tots els nostres adhesius tenen codis QR que enllaçen a pàgines educatives sobre",
	"stickers_choose_c2": "Bitcoin",
	"stickers_choose_c3": "inflació",
	"stickers_choose_c4": "Tria el teu paquet d'adhesius a continuació",
	"stickers_text_pack": "EL PAQUET DE TEXT",
	"stickers_signs_pack": "EL PAQUET DE CARTELLS",
	"stickers_instructions_1": "Introdueix la teva adreça postal i t'enviarem un paquet d'adhesius de Bitcoin gratuït per correu! Els teus adhesius s'enviaran en un sobre blanc pla.",
	"stickers_instructions_2": "Les dades d'adreça s'eliminen després que s'enviïn els teus adhesius gratuïts.",
	"stickers_share_header": "COMPARTEIX ELS TEUS LLOCS D'ADHESIUS",
	"stickers_share_c1": "Comparteix els teus llocs d'adhesius amb nosaltres a Nostr i veu on posa la gent els seus adhesius.",
	"stickers_btn_share_on_nostr": "COMPARTEIX A NOSTR",
	"stickers_btn_what_is_nostr": "QUÈ ÉS NOSTR?",
	"stickers_flyers_link_before": "Ja que hi ets, imprimeix i penja els teus propis ",
	"stickers_flyers_link_text": "fulletons de Bitcoin",
	"stickers_flyers_link_after": " per ajudar a fer que encara més gent s'apassioni per Bitcoin.",
	"stickers_country_global_print": "Global — Imprimeix els meus propis adhesius",
	"stickers_country_global_order": "Global — Demana al per major",
	"placeholder_name_optional": "Nom (opcional)",
	"placeholder_address_line_1": "Línia d'adreça 1",
	"placeholder_address_line_2": "Línia d'adreça 2 (opcional)",
	"placeholder_city": "Ciutat",
	"placeholder_state": "Estat",
	"placeholder_province": "Província",
	"placeholder_zip_code": "Codi postal",
	"placeholder_postal_code": "Codi postal",
	"placeholder_language": "Idioma",
	"placeholder_which_stickers": "Quins adhesius?",
	"placeholder_email_optional": "Introdueix el teu correu electrònic per ser notificat (opcional)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "Postals de Bitcoin gratuïtes de bitcoin.rocks",
	"postcards_description": "Aconsegueix un paquet de postals de Bitcoin gratuït i comparteix Bitcoin amb algú que coneixes.",
	"postcards_header": "PROGRAMA DE POSTALS TANCAT",
	"postcards_program_closed_message": "El nostre programa gratuït de postals de Bitcoin ha finalitzat. Gràcies a tothom que va participar en la difusió de l'educació sobre Bitcoin per correu!",
	"postcards_sticker_alternative_header": "ACONSEGUEIX ADHESIUS DE BITCOIN GRATUÏTS EN LLOC D'AIXÒ",
	"postcards_sticker_alternative_message": "Continua difonent el coneixement de Bitcoin amb el nostre programa gratuït d'adhesius! Els nostres adhesius de Bitcoin són perfectes per compartir en espais públics i inclouen codis QR que enllaçen a contingut educatiu.",
	"postcards_sticker_cta": "ACONSEGUEIX ADHESIUS GRATUÏTS",
	"postcards_step_2": "COM EREN LES POSTALS",
	"postcards_instructions_4": "Vam crear aquestes postals per facilitar-te la presentació de Bitcoin a algú que coneixes! Només afegeix una adreça i un segell i llença la teva postal al correu.",
	"postcards_instructions_5": "La nostra missió és accelerar l'adopció de Bitcoin. Pots ajudar aconseguint adhesius gratuïts i posant-los en espais públics!",
	"postcards_instructions_6": "Tots coneixem algunes persones que es beneficiarien d'aprendre més sobre Bitcoin. Comparteix adhesius de Bitcoin amb ells avui!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "Ajuda'ns a posar aquests cartells de Bitcoin per tota Amèrica!",
	"signs_title": "Cartells de Bitcoin gratuïts de bitcoin.rocks",
	"signs_choose_header": "GRÀCIES PER AJUDAR-NOS A POSAR AQUESTS CARTELLS DE BITCOIN PER TOTA AMÈRICA!",
	"signs_choose_c1": "Ara estem completament sense cartells! La nostra missió és accelerar l'adopció de Bitcoin a través de l'educació.",
	"signs_choose_c2": "Molts de vosaltres heu ajudat posant aquests cartells de Bitcoin gratuïts en públic. Tots els nostres cartells tenen codis QR que enllaçen a una pàgina educativa sobre",
	"signs_choose_c3": "inflació",
	"signs_choose_c4": "Gràcies a la nostra increïble comunitat, vam arribar a milers de persones i les vam ajudar a fer els seus primers passos pel cau del conill de Bitcoin.",
	"signs_share_header": "COMPARTEIX ELS TEUS LLOCS DE CARTELLS",
	"signs_share_c1": "Comparteix una foto del lloc del teu cartell amb nosaltres a Nostr i veu on posa la gent els seus cartells.",
	"signs_btn_share_on_nostr": "COMPARTEIX A NOSTR",
	"signs_btn_what_is_nostr": "QUÈ ÉS NOSTR?",
	"signs_instructions_1": "Introdueix la teva adreça postal i t'enviarem una caixa de 10 cartells de Bitcoin per correu!",
	"signs_instructions_2": "Les dades d'adreça s'eliminen després que s'enviïn els teus cartells gratuïts."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "Fulletons de Bitcoin gratuïts de bitcoin.rocks",
	"flyers_description": "Imprimeix un fulletó de Bitcoin a casa i penja'l en públic per fer que els que t'envolten s'apassionin per Bitcoin.",
	"flyers_header_1": "IMPRIMEIX I PENJA",
	"flyers_header_2": "FULLETONS DE BITCOIN",
	"flyers_intro_header": "COM IMPRIMIR I PENJAR AQUESTS FULLETONS DE BITCOIN",
	"flyers_intro_c1": "La nostra missió és ajudar-te a fer que més gent s'apassioni per Bitcoin penjant fulletons de Bitcoin en públic. Aquest fulletó té un codi QR que enllaça al nostre",
	"flyers_intro_c2": "lloc web educatiu sobre Bitcoin.",
	"flyers_intro_c3": "inflació",
	"flyers_intro_c4": "Imprimeix aquest fulletó a casa o en una impremta. Després, penja'l en taulers d'anuncis, pals de telèfon del poble i altres espais públics on la gent el pugui veure i aprendre sobre Bitcoin.",
	"flyers_intro_c5": "Ja que hi ets, sol·licita un paquet dels nostres",
	"flyers_intro_c6": "adhesius de Bitcoin gratuïts",
	"flyers_intro_c7": "per ajudar a fer que encara més gent s'apassioni per Bitcoin.",
	"flyers_btn_download": "DESCARREGA FULLETÓ",
	"flyers_btn_print": "IMPRIMEIX FULLETÓ",
	"flyers_share_header": "COMPARTEIX ELS TEUS LLOCS DE FULLETONS",
	"flyers_share_c1": "Comparteix els teus llocs de fulletons amb nosaltres a Nostr i veu on penja la gent els seus fulletons.",
	"flyers_btn_share_on_nostr": "COMPARTEIX A NOSTR",
	"flyers_btn_what_is_nostr": "QUÈ ÉS NOSTR?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "Participa i ajuda a difondre Bitcoin",
	"get_involved_description": "Els nostres recursos gratuïts faciliten la difusió de l'adopció de Bitcoin.",
	"get_involved_header": "PARTICIPA",
	"get_involved_header_2": "DIFON BITCOIN",
	"get_involved_intro_1": "Pot ser depriment viure en l'estat actual del nostre món.",
	"get_involved_intro_2": "Els nostres diners estan trencats. Com a resultat, peces fonamentals de la societat també estan trencades.",
	"get_involved_intro_3": "Si ja coneixes Bitcoin, coneixes la sensació d'esperança que Bitcoin pot portar. Esperança per a un futur més brillant fet possible per uns diners millors.",
	"get_involved_intro_4": "Però tanta gent al teu voltant no coneix Bitcoin. Viuen al mateix món trencat que tu, però sense un far d'esperança que els ajudi a travessar la foscor.",
	"get_involved_intro_5": "Però tu pots ajudar a canviar això. Hem creat diversos recursos gratuïts per facilitar la difusió de l'esperança que Bitcoin porta als que t'envolten.",
	"get_involved_sticker_header": "Posa un adhesiu en públic",
	"get_involved_sticker_content_1": "Pots ajudar a educar els que t'envolten sobre Bitcoin sense haver d'interactuar amb ningú. Simplement posa un dels nostres adhesius de Bitcoin gratuïts en públic.",
	"get_involved_sticker_content_2": "Centenars de persones escanegen els codis QR d'aquests adhesius cada mes. Els adhesius d'inflació enllaçen a una pàgina sobre",
	"get_involved_sticker_content_3": "Bitcoin com a solució a la inflació.",
	"get_involved_sticker_content_4": "Els altres adhesius enllaçen a la nostra pàgina d'inici educativa que mostra a la gent com",
	"get_involved_sticker_content_5": "Bitcoin està construint un món millor.",
	"get_involved_sticker_content_6": "Posant aquests adhesius a la teva comunitat en llocs on la gent els veurà, pots ajudar els que t'envolten a fer els seus primers passos pel cau del conill de Bitcoin.",
	"get_involved_request_a": "SOL·LICITA UN",
	"get_involved_sticker_pack": "PAQUET D'ADHESIUS",
	"get_involved_postcard_header": "Envia una postal",
	"get_involved_postcard_content_1": "Pots ajudar a difondre l'esperança de Bitcoin a algú que coneixes enviant-li una de les nostres postals gratuïtes.",
	"get_involved_postcard_content_2": "El revers de cada postal conté un text convincent sobre Bitcoin juntament amb un codi QR per aprendre'n més.",
	"get_involved_postcard_content_3": "Enviant a algú una postal de Bitcoin, pots ajudar-lo a veure Bitcoin d'una manera nova.",
	"get_involved_postcard_pack": "PAQUET DE POSTALS",
	"get_involved_business_header": "Incorpora un negoci",
	"get_involved_business_content_1": "Vols ajudar a construir l'economia circular de Bitcoin? El nostre Kit Empresarial Bitcoin facilita apropar-se a un negoci per acceptar pagaments amb Bitcoin.",
	"get_involved_business_content_2": "Cada kit empresarial inclou fulletons que destaquen els avantatges d'acceptar pagaments amb Bitcoin. Cada fulletó enllaça a una varietat de",
	"get_involved_business_content_3": "recursos gratuïts per a negocis Bitcoin.",
	"get_involved_business_kit": "KIT EMPRESARIAL"
});

console.log('\nDone creating content files for Catalan (ca).');
