/**
 * Creates Norwegian Bokmål (nb) translation file for index.json (~130+ keys)
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'nb';
const today = '2026-04-04';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"bitcoin_builds_a_better_world": "Bitcoin bygger en bedre verden.",
	"home_description": "Bitcoin er bedre penger som bygger en bedre verden. Bitcoin har beskyttet menneskerettigheter, reddet folk fra høy inflasjon, støttet lokale bønder, redusert utslipp fra oljeboring og mye mer.",
	"home_intro": "Bitcoin er bedre penger som bygger en bedre verden. Trykk på en kategori nedenfor for å lære hvordan Bitcoin gjør det bedre, eller bare begynn å scrolle for å utforske.",
	"home_btn_money": "BEDRE PENGER",
	"home_btn_salary": "DIN LØNN",
	"home_btn_freedom": "FRIHET",
	"home_btn_human_rights": "MENNESKERETTIGHETER",
	"home_btn_equality": "LIKESTILLING",
	"home_btn_property_rights": "EIENDOMSRETTIGHETER",
	"home_btn_housing": "BOLIG",
	"home_btn_business": "BEDRIFT",
	"home_btn_crowdfunding": "FOLKEFINANSIERING",
	"home_btn_energy": "ENERGI",
	"home_btn_environment": "MILJØET",
	"home_btn_food": "MAT",
	"home_btn_art": "KUNST",
	"home_btn_politics": "POLITIKK",
	"home_btn_war": "KRIG",
	"home_btn_coding": "KODING",
	"home_btn_networks": "NETTVERK",
	"home_btn_payments": "BETALINGER",
	"home_btn_self_custody": "SELVFORVARING",
	"home_btn_you": "DEG",
	"home_section_bitcoin_is": "BITCOIN ER",
	"home_section_bitcoin_and": "BITCOIN OG",
	"home_link_type_website": "NETTSTED",
	"home_link_type_video": "VIDEO",
	"home_link_type_article": "ARTIKKEL",
	"home_link_type_podcast": "PODKAST",
	"home_link_type_business_kit": "BEDRIFTSPAKKE",
	"home_link_type_data": "DATA",
	"home_link_type_research": "FORSKNING",
	"home_link_type_story": "HISTORIE",
	"home_link_type_book_excerpt": "BOKUTDRAG",
	"home_link_type_street_art": "GATEKUNST",
	"home_link_type_outreach": "OPPSØKENDE",
	"home_link_type_campaign": "KAMPANJE",
	"home_link_type_software": "PROGRAMVARE",
	"home_link_type_hardware": "MASKINVARE",
	"home_link_type_guide": "GUIDE",
	"home_link_type_email": "E-POST",
	"home_link_title_inflation": "Bitcoin har ikke inflasjon",
	"home_link_title_bank_runs": "Bitcoin har ingen bankkriser",
	"home_link_title_gold": "Bitcoin vs gull",
	"home_link_title_crypto": "Bitcoin vs krypto",
	"home_link_title_cash": "Bitcoin vs kontanter",
	"home_link_title_bonds": "Bitcoin vs obligasjoner",
	"home_link_title_cbdc": "Bitcoin vs CBDC-er",
	"home_link_title_your_salary_1": "Finn ut hvor mye lønnen din må øke for å holde tritt med inflasjonen.",
	"home_link_title_freedom_1": "Hvorfor Bitcoin er viktig for frihet",
	"home_link_title_freedom_2": "Bitcoin tilbyr frihet fra politisk undertrykkelse",
	"home_link_title_human_rights_1": "Hvordan Bitcoin håndhever menneskerettigheter",
	"home_link_title_human_rights_2": "Den stille Bitcoin-revolusjonen i Afrika",
	"home_link_title_human_rights_3": "Bitcoin beskytter menneskerettigheter over hele verden",
	"home_link_title_equality_1": "Bitcoin gir håp og muligheter til sørafrikanere",
	"home_link_title_equality_2": "Hvordan Bitcoin kan være en gamechanger for svarte amerikanere",
	"home_link_title_property_rights_1": "Bitcoin er den perfekte formen for eiendom",
	"home_link_title_property_rights_2": "Bitcoin vs eiendom",
	"home_link_title_housing_1": "Hvordan Bitcoin vil gjøre bolig overkommelig igjen",
	"home_link_title_business_3": "Bitcoin vs aksjer",
	"home_link_title_business_1": "Lær hvorfor Bitcoin er bra for bedrifter",
	"home_link_title_business_2": "Få en lokal bedrift til å akseptere Bitcoin",
	"home_link_title_crowdfunding_1": "Hvordan Bitcoin drev de største nigerianske protestene på en generasjon",
	"home_link_title_crowdfunding_2": "Canadiske lastebilsjåførprotester samler inn penger i Bitcoin etter at GoFundMe blokkerer donasjoner",
	"home_link_title_crowdfunding_3": "Geyser = Folkefinansier med Bitcoin",
	"home_link_title_energy_1": "Hvordan Bitcoin stabiliserer strømnettet i Texas",
	"home_link_title_energy_2": "Hvorfor bruker Bitcoin energi?",
	"home_link_title_energy_3": "Bitcoins energiforbruk er ikke et problem. Her er hvorfor.",
	"home_link_title_energy_4": "Bitcoin-utvinning stabiliserer strømnett gjennom etterspørselsrespons",
	"home_link_title_energy_5": "Bitcoin-utvinnere bringer vannkraft til rurale afrikanske samfunn",
	"home_link_title_energy_6": "Hvordan Bitcoin stimulerer fornybar energi",
	"home_link_title_environment_1": "Hvordan bitcoin-utvinning reduserer globale metanutslipp",
	"home_link_title_environment_2": "Hvordan bitcoin-utvinning reddet en nasjonalpark",
	"home_link_title_environment_3": "Bitcoin er den grønneste industrien på jorden!",
	"home_link_title_environment_4": "Bitcoin-utvinning forhindrer avfaklet naturgass fra å forurense atmosfæren",
	"home_link_title_food_1": "Hvordan inflasjon påvirker matpriser",
	"home_link_title_food_2": "Hvordan fiat-penger er dårlig for mat, gårder og jordens jord",
	"home_link_title_fine_art": "Bitcoin vs kunst",
	"home_link_title_art_1": "Bli med i vårt Bitcoin-klistremerkeinitiativ",
	"home_link_title_art_2": "Send et Bitcoin-postkort til noen du kjenner",
	"home_link_title_art_3": "Skriv ut og heng opp Bitcoin-flygeblad",
	"home_link_title_politics_1": "Bitcoin er et politisk paradoks",
	"home_link_title_politics_2": "Du kan stemme for bedre penger",
	"home_link_title_war_1": "Hvordan Bitcoin kan avslutte endeløse kriger",
	"home_link_title_war_2": "Bitcoin og veteraner: En naturlig kobling",
	"home_link_title_war_3": "Hvordan Bitcoin hjelper sivile å flykte fra krigen i Sudan",
	"home_link_title_coding_1": "En interaktiv veiledning om Bitcoins tekniske side",
	"home_link_title_coding_2": "bitcoinSwitch: oppgrader enhver enhet til å akseptere Bitcoin",
	"home_link_title_coding_3": "Kod deg gjennom Bitcoins mysterier",
	"home_link_title_networks_1": "En live visning av Bitcoin-nettverket",
	"home_link_title_networks_2": "Bitcoin vs banker",
	"home_link_title_payments_1": "Bitcoin vs Visa",
	"home_link_title_payments_2": "Et blikk på Lightning-nettverket (umiddelbare Bitcoin-betalinger)",
	"home_link_title_payments_3": "El Salvadors Bitcoin-lommebok kan spare salvadoranere 400 millioner dollar årlig i overføringsgebyrer",
	"home_link_title_payments_4": "Skaff din Lightning-adresse for å motta umiddelbare Bitcoin-betalinger",
	"home_link_title_self_custody_1": "Hvordan lagre din Bitcoin trygt",
	"home_link_title_self_custody_2": "6 grunner til å ta ut din Bitcoin fra børser",
	"home_link_title_self_custody_3": "Gull, Bitcoin og selvforvaring",
	"home_link_title_get_started_1": "Lær det grunnleggende om Bitcoin",
	"home_link_title_get_started_2": "Skaff deg din første Bitcoin-lommebok",
	"home_link_title_get_started_3": "Hvordan kjøpe Bitcoin",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Kalkulator for sammensatt inflasjon",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! Created index.json.');
