/**
 * Creates Norwegian Bokmål (nb) translation file for common.json (~180+ keys)
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'nb';
const today = '2026-04-04';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"common_footer_mission_1": "Oppdraget til bitcoin.rocks er å akselerere bitcoin-adopsjon gjennom utdanning.",
	"common_footer_mission_2": "Lær hvordan du kan bidra til dette åpen kildekode-prosjektet.",
	"common_footer_follow_first_half": "Følg oss på Nostr ved å søke etter",
	"common_footer_follow_second_half": "i en hvilken som helst Nostr-klient.",
	"common_footer_what_is_nostr": "Hva er Nostr?",
	"common_footer_about": "Om oss",
	"common_footer_email_us": "Send oss e-post:",
	"common_cta_section_get_started": "KOM I GANG",
	"common_cta_section_with_bitcoin": "MED BITCOIN",
	"common_cta_section_title_1": "Lær det grunnleggende om Bitcoin",
	"common_cta_section_title_1_alt": "Lær mer om Bitcoin",
	"common_cta_section_title_2": "Skaff deg din første Bitcoin-lommebok",
	"common_cta_section_title_3": "Hvordan kjøpe Bitcoin",
	"common_cta_link_type_email": "E-POST",
	"common_cta_link_type_guide": "GUIDE",
	"common_cta_link_type_website": "NETTSTED",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "HVA ER BITCOIN?",
	"common_what_is_bitcoin_content_1": "Bitcoin er to ting: digitale penger og et betalingsnettverk. Du kan sende Bitcoin (de digitale pengene) direkte til andre mennesker ved hjelp av Bitcoin-nettverket (betalingsnettverket).",
	"common_what_is_bitcoin_content_2": "Bitcoin er en radikalt ny måte å lagre og overføre verdi på. I motsetning til vanlige finansielle nettverk kan Bitcoin-nettverket operere uten sentrale myndigheter eller pålitelige administratorer. Det gjør Bitcoin til de første åpne og grenseløse pengene noensinne.",
	"common_what_is_bitcoin_content_3": "Bitcoin er digitale penger som gir deg fullstendig eierskap over formuen din. For første gang i menneskets historie kan alle eie en eiendel som virkelig er knapp, ikke krever tillatelse for å brukes, og ikke kan beslaglegges når den oppbevares riktig.",
	"common_what_is_bitcoin_content_4": "Bitcoin kan sendes hvor som helst i verden, raskt og billig. Det trenger ingen tredjepart for overføring, som en bank.",
	"common_what_is_bitcoin_content_5": "Bitcoin gjør det mulig for hvem som helst å lagre formuen sin trygt og sikkert uten å bekymre seg for at myndighetene stjeler den eller inflaterer bort verdien gjennom pengetrykking.",
	"common_what_is_bitcoin_content_6": "Myndigheter overalt kan trykke mer papirpenger, men ingen kan trykke mer bitcoin.",
	"common_what_is_bitcoin_content_7": "Du kan enkelt selvforvarere din Bitcoin for å ta full kontroll over den, og gi deg full tilgang til kraften i Bitcoin.",
	"common_what_is_bitcoin_content_8": "Hvis du kan laste ned en app, kan du selvforvarere Bitcoin og lagre formuen din uten å stole på noen andre.",
	"common_what_is_bitcoin_content_9": "Bitcoin er bedre penger.",
	"common_bitcoin_volatile": "JEG HØRTE AT BITCOIN ER VOLATILT. ER DET TRYGT?",
	"common_bitcoin_volatile_content_1": "På kort sikt har vekslingskursen for Bitcoin en tendens til å svinge. Dette kalles volatilitet.",
	"common_bitcoin_volatile_content_2": "Men volatiliteten du ser på daglig basis «forsvinner» på lang sikt.",
	"common_bitcoin_volatile_content_3": "Bitcoin fortsetter å bli mindre og mindre volatilt over tid. Etter hvert som flere mennesker bruker Bitcoin som en langsiktig sparekonto, stabiliseres verdien mer.",
	"common_bitcoin_volatile_content_4": "Mange mennesker velger å lagre verdi i Bitcoin i mange år som en trygg måte å minimere risikoen for volatilitet og beskytte kjøpekraften sin over tid.",
	"common_bitcoin_volatile_content_5": "I noen land, som Venezuela, Sudan, Libanon, Syria, Argentina, Tyrkia, Brasil og mange andre, inflateres verdien av den lokale valutaen bort så raskt at Bitcoin sees som den mer stabile måten å spare penger på.",
	"common_bitcoin_afford": "JEG HAR IKKE RÅD TIL EN HEL BITCOIN",
	"common_bitcoin_afford_content_1": "En dollar består av 100 cent. En bitcoin består av 100 000 000 (100 millioner) sats.",
	"common_bitcoin_afford_content_2": "Du trenger ikke å eie en hel bitcoin. De fleste eier bare sats. Sats er brøkdeler av en bitcoin. For eksempel, hvis 1 hel bitcoin er $100 000, så kjøper $1 deg 1 000 sats!",
	"common_bitcoin_hacked": "HAR BITCOIN NOENSINNE BLITT HACKET?",
	"common_bitcoin_hacked_content_1": "Du har kanskje hørt om et «Bitcoin-hack» på nettet eller i nyhetene. De fleste leser disse artiklene og tror Bitcoin-nettverket har blitt hacket. Bitcoin-nettverket har imidlertid aldri blitt hacket.",
	"common_bitcoin_hacked_content_2": "Hva er Bitcoin-nettverket? Tenk på Bitcoin-nettverket som jernbaneskinner. Togene som kjører på jernbanesporet til Bitcoin-nettverket er Bitcoin-transaksjoner.",
	"common_bitcoin_hacked_content_3": "Når du leser om et Bitcoin-hack i nyhetene, leser du om en forvalter (som FTX) som har blitt hacket eller gått konkurs.",
	"common_bitcoin_hacked_content_4": "Forvaltere er selskaper som oppbevarer din bitcoin for deg. Men dette medfører en risiko: å miste din bitcoin når selskapet forvalter den dårlig, stjeler den, eller går ut av drift.",
	"common_bitcoin_hacked_content_5": "Dette skjedde sist med FTX.",
	"common_bitcoin_hacked_content_6": "Alle som stolte på FTX med sin bitcoin mistet sin bitcoin. Alle som holdt sin bitcoin i selvforvaring var helt upåvirket av FTX. Det er kraften i bitcoin i selvforvaring: ekte kontroll over pengene dine.",
	"common_bitcoin_hacked_content_7": "I stedet for å la din bitcoin ligge på en børs eller i en wrapper som en ETF, hold den i din egen lommebok for alle frihetsgodene.",
	"common_bitcoin_hacked_content_8": "Når du selvforvarerer din bitcoin, er pengene dine beskyttet av Bitcoin-nettverket. Det er det mest sikre finansielle nettverket i verden.",
	"common_bitcoin_hacked_content_9": "I selvforvaring kan ikke Sam fra FTX stjele din bitcoin fra deg.",
	"common_bitcoin_hacked_content_10": "Myndighetene kan ikke trykke mer bitcoin og forårsake inflasjon.",
	"common_bitcoin_hacked_content_11": "Bitcoin i selvforvaring er dine penger, takket være kraften i Bitcoin-nettverket.",
	"common_bitcoin_energy": "HVORFOR BRUKER BITCOIN ENERGI?",
	"common_bitcoin_energy_content_1": "Bitcoin bruker energi for å sikre nettverket og beskytte pengene dine.",
	"common_bitcoin_energy_content_2": "Bitcoin bruker en betydelig mengde energi, og dette er en god ting av mange grunner.",
	"common_bitcoin_energy_list_1": "Bitcoin har ingen bankkriser.",
	"common_bitcoin_energy_list_2": "Bitcoin bidrar til å stabilisere strømnett med bitcoin-utvinning.",
	"common_bitcoin_energy_list_3": "Bitcoin reduserer utslipp fra oljeboring.",
	"common_bitcoin_energy_list_4": "Bitcoin bruker mindre energi enn amerikanere bruker på julebelysning hvert år.",
	"common_bitcoin_energy_list_5": "Bitcoin er den grønneste industrien på jorden!",
	"common_cic_intro_1": "Mange kjenner til rentes rente, men få kjenner til sammensatt inflasjon.",
	"common_cic_intro_2": "Med vår kalkulator for sammensatt inflasjon kan du enkelt beregne hvor mye lønnen din må øke for å opprettholde kjøpekraften din over tid.",
	"common_cic_intro_3": "Skriv ganske enkelt inn din nåværende lønn, inflasjonsrate og antall år du vil beregne for, og kalkulatoren vår vil vise deg hva lønnen din må være for å holde tritt med inflasjonen.",
	"common_current_salary": "nåværende lønn",
	"common_inflation_rate": "inflasjonsrate",
	"common_year": "år",
	"common_years": "år",
	"common_result_starting_message": "Fyll ut skjemaet over og klikk beregn.",
	"common_error_message": "Feil: Vennligst fyll inn alle 3 skjemafeltene.",
	"common_result_message_1": "Med en inflasjonsrate på",
	"common_result_message_2": "må din",
	"common_result_message_3": "lønn øke til",
	"common_result_message_in": "i løpet av",
	"common_result_message_4": "for å opprettholde kjøpekraften din.",
	"common_calculate_button_text": "BEREGN",
	"common_learn_more": "LÆR MER",
	"common_success": "SUKSESS!",
	"common_choose_your_country": "Velg ditt land",
	"common_country_usa": "USA",
	"common_country_canada": "Canada",
	"common_submit": "SEND INN",
	"common_language_afrikaans": "AFRIKAANS",
	"common_language_arabic": "ARABISK",
	"common_language_basque": "BASKISK",
	"common_language_bulgarian": "BULGARSK",
	"common_language_catalan": "KATALANSK",
	"common_language_chinese": "KINESISK",
	"common_language_croatian": "KROATISK",
	"common_language_czech": "TSJEKKISK",
	"common_language_danish": "DANSK",
	"common_language_dutch": "NEDERLANDSK",
	"common_language_english": "ENGELSK",
	"common_language_estonian": "ESTISK",
	"common_language_filipino": "FILIPPINSK",
	"common_language_finnish": "FINSK",
	"common_language_french": "FRANSK",
	"common_language_german": "TYSK",
	"common_language_greek": "GRESK",
	"common_language_hausa": "HAUSA",
	"common_language_hebrew": "HEBRAISK",
	"common_language_hindi": "HINDI",
	"common_language_hungarian": "UNGARSK",
	"common_language_indonesian": "INDONESISK",
	"common_language_irish": "IRSK",
	"common_language_italian": "ITALIENSK",
	"common_language_japanese": "JAPANSK",
	"common_language_korean": "KOREANSK",
	"common_language_malay": "MALAYISK",
	"common_language_norwegian": "NORSK",
	"common_language_persian": "PERSISK",
	"common_language_polish": "POLSK",
	"common_language_portuguese": "PORTUGISISK",
	"common_language_russian": "RUSSISK",
	"common_language_sinhala": "SINGALESISK",
	"common_language_slovak": "SLOVAKISK",
	"common_language_slovenian": "SLOVENSK",
	"common_language_spanish": "SPANSK",
	"common_language_swahili": "SWAHILI",
	"common_language_swedish": "SVENSK",
	"common_language_thai": "THAI",
	"common_language_turkish": "TYRKISK",
	"common_language_urdu": "URDU",
	"common_language_vietnamese": "VIETNAMESISK",
	"common_language_yoruba": "YORUBA",
	"common_stickers_bulk_mess": "Vil du ikke styre med filene selv?",
	"common_stickers_bulk_want": "Vil du ha mer enn bare noen få klistremerker?",
	"common_stickers_bulk_store": "Bestill klistremerker i bulk fra samme trykkeri vi bruker.",
	"common_stickers_bulk_cheaper": "Jo flere klistremerker du kjøper, jo billigere blir de per klistremerke.",
	"common_stickers_print_instructions_1": "Du kan delta ved å skrive ut dine egne klistremerker, uansett hvor du bor! Klikk på ditt språk nedenfor for å laste ned klistremerkefiler og instruksjoner.",
	"common_stickers_print_instructions_2": "Merk: ikke alle klistremerker er tilgjengelige på alle språk.",
	"common_stickers_request_language_1": "Ser du ikke ditt språk?",
	"common_stickers_request_language_2": "Fyll ut skjemaet nedenfor for å be om klistremerkefiler på ditt lokale språk.",
	"common_stickers_dimensions": "Dimensjoner:",
	"common_stickers_type": "Type:",
	"common_stickers_material": "Materiale:",
	"common_stickers_where_to_print": "Hvor du kan trykke:",
	"common_stickers_type_die_cut": "utstanset klistremerke",
	"common_stickers_material_vinyl": "vinylklistremerker for utendørs bruk",
	"common_stickers_printer": "Vi bruker StickerMule.com, men du kan bruke et hvilket som helst klistremerkeselskap.",
	"common_stickers_dimensions_danger": "11,4544 cm x 8,382 cm",
	"common_stickers_dimensions_warning": "10,414 cm x 9,2202 cm",
	"common_stickers_dimensions_caution": "12,0142 cm x 7,9502 cm",
	"common_stickers_dimensions_fix": "11,3792 cm x 6,8072 cm",
	"common_stickers_dimensions_study": "14,605 cm x 5,1308 cm",
	"common_stickers_dimensions_bdhi": "21,59 cm x 4,6482 cm",
	"common_stickers_dimensions_cure_v2": "6,35 cm x 12,7 cm",
	"common_stickers_dimensions_got_inflation": "7,9248 cm x 14,605 cm",
	"common_stickers_dimensions_what_if": "21,7932 cm x 7,62 cm",
	"common_stickers_dimensions_bitcoin_accepted_here": "20,995 cm x 6,35 cm",
	"common_nostr_join": "BLI MED PÅ NOSTR NÅ",
	"common_nostr_protocol_header": "Protokoll, ikke plattform",
	"common_nostr_protocol_c1": "Nostr er en ny protokoll som lar deg kommunisere på nett uten frykt for sensur, deplattforming eller nedgradering",
	"common_nostr_protocol_c2": "Plattformer som Twitter og Facebook kontrolleres av et enkelt selskap, men ingen kontrollerer Nostr-protokollen.",
	"common_nostr_freedom_header": "Frihet til å flytte",
	"common_nostr_freedom_c1": "Nostr ligner på e-post. Ingen kontrollerer e-postprotokollen, og hvem som helst kan bygge en klient (som Gmail, Hotmail osv.) oppå den.",
	"common_nostr_freedom_c2": "Ingen kontrollerer Nostr-protokollen, og hvem som helst kan bygge en klient (som Damus, Amethyst osv.) oppå den.",
	"common_nostr_freedom_c3": "Hvis du ikke liker hvordan en bestemt klient fungerer, kan du sømløst flytte Nostr-kontoen din til en annen klient uten å miste følgerne eller innholdet ditt.",
	"common_nostr_bitcoin_header": "Bitcoin er innebygd",
	"common_nostr_bitcoin_c1": "Bitcoin er innebygd i Nostr-protokollen. Hvis du ser innhold du liker, kan du enkelt zappe bitcoin til noen som en takk!",
	"common_nostr_bitcoin_c2": "På sentraliserte plattformer som Twitter og Facebook tjener det sentraliserte selskapet penger på innholdet ditt. Men på åpne protokoller som Nostr tjener du penger på innholdet ditt.",
	"common_nostr_download_client": "LAST NED EN GRATIS KLIENT FOR Å BLI MED PÅ NOSTR",
	"common_nostr_iphone_clients": "iPhone-klienter",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "iPhone-app",
	"common_nostr_first_client": "Anbefalt første klient",
	"common_nostr_wallet_built_in": "Bitcoin zap-lommebok innebygd",
	"common_nostr_download_now": "LAST NED NÅ",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "Kjent grensesnitt",
	"common_nostr_separate_wallet": "Krever separat bitcoin-lommebok",
	"common_nostr_android_clients": "Android-klienter",
	"common_nostr_android_app": "Android-app",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "Mange funksjoner",
	"common_nostr_browser_clients": "Nettleserklienter",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "Nettklient",
	"common_nostr_simple": "Superenkelt",
	"common_nostr_test": "Enkel måte å prøve Nostr med en testkonto",
	"common_nostr_view_client": "VIS KLIENT",
	"common_kit_printer": "Vi anbefaler VistaPrint.com for å trykke dine egne Bitcoin-bedriftspakkebrosjyrer. Du kan imidlertid bruke et hvilket som helst trykkeri så lenge de kan gjøre dobbeltsidig utskrift.",
	"common_kit_link_to_print": "Lenke til utskrift:",
	"common_kit_fold": "Brett:",
	"common_kit_fold_trifold": "Trebrett",
	"common_kit_unfolded_size": "Utbrettet størrelse:",
	"common_kit_unfolded_size_bbk": "Letter-størrelse (8,5 in x 11 in)",
	"common_kit_paper_thickness": "Papirtykkelse:",
	"common_kit_paper_thickness_standard": "Standard",
	"common_kit_paper_stock": "Papirkvalitet:",
	"common_kit_paper_stock_glossy": "Glanset",
	"common_kit_exterior_print_file": "Utvendig utskriftsfil:",
	"common_kit_interior_print_file": "Innvendig utskriftsfil:",
	"common_kit_cta_header": "Få en lokal bedrift til å akseptere Bitcoin",
	"common_biz_learn": "Lær hvorfor Bitcoin er bra for bedrifter",
	"common_biz_wallets": "Skaff en Bitcoin-lommebok for å akseptere Bitcoin-betalinger",
	"common_biz_maps": "Bli listet på kart over Bitcoin-forhandlere",
	"common_biz_stickers": "Gratis klistremerker «Bitcoin aksepteres her»",
	"common_biz_rewards": "Bitcoin-belønninger",
	"common_biz_accounting": "Guide for Bitcoin-regnskap",
	"common_biz_faq": "Ofte stilte spørsmål",
	"common_biz_kit": "Skriv ut din egen Bitcoin-bedriftspakke",
	"common_biz_accept_bitcoin_payments": "AKSEPTER BITCOIN-BETALINGER",
	"common_biz_ready": "KLAR TIL Å AKSEPTERE BITCOIN I BEDRIFTEN DIN?",
	"common_biz_more": "FLERE BEDRIFTSRESSURSER",
	"common_self_custody": "SELVFORVARING",
	"common_not_your_keys": "IKKE DINE NØKLER",
	"common_cold_wallet": "KALD LOMMEBOK",
	"common_hot_wallet": "VARM LOMMEBOK",
	"common_sticker_files_mission_1": "Vårt oppdrag er å hjelpe deg med å oransje-pille flere mennesker ved å sette Bitcoin-klistremerker offentlig. Alle klistremerkene våre har QR-koder som lenker til utdanningssider om",
	"common_sticker_files_mission_2": "Bitcoin",
	"common_sticker_files_mission_3": "inflasjon",
	"common_sticker_files_mission_4": "Hvis du bor i USA eller Canada, kan du",
	"common_sticker_files_mission_5": "be om en gratis pakke med engelske klistremerker",
	"common_published_by": "Publisert av",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "Bitcoin-utdanning siden 2022",
	"common_publisher_open_source": "Åpen kildekode-prosjekt",
	"common_reviewed_accuracy": "✓ Gjennomgått for nøyaktighet: 2026",
	"common_footer_tagline": "Akselererer bitcoin-adopsjon gjennom utdanning.",
	"common_footer_contribute": "Bidra",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "Kilder"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! Created common.json.');
