/**
 * Creates Norwegian Bokmål (nb) translation files for remaining content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'nb';
const today = '2026-04-04';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "Bitcoin har ingen bankkriser",
	"bank_runs_header": "BITCOIN HAR INGEN BANKKRISER",
	"bank_runs_header_2": "MEN BANKEN DIN KAN HA DET",
	"bank_runs_what": "HVA ER EN BANKKRISE?",
	"bank_runs_what_content_1": "En bankkrise oppstår når for mange mennesker prøver å ta ut pengene sine fra banken samtidig.",
	"bank_runs_what_content_2": "Hvis bankene ikke har nok penger tilgjengelig til å dekke uttakene, kan de kollapse fullstendig under en bankkrise.",
	"bank_runs_how": "HVORDAN OPPSTÅR BANKKRISER?",
	"bank_runs_how_content_1": "Banksystemet vårt er «fraksjonelt reservebasert», noe som betyr at bankene ikke bare oppbevarer pengene dine i et hvelv og venter på at du skal bruke dem eller ta dem ut.",
	"bank_runs_how_content_2": "I stedet tar banken din pengene dine og låner dem ut eller investerer dem. Dette kan låse pengene dine i lange perioder, selv om banken lover deg muligheten til å ta ut pengene dine når som helst.",
	"bank_runs_how_content_3": "Så hva skjer hvis du prøver å ta ut pengene dine etter at banken allerede har lånt dem ut eller investert dem?",
	"bank_runs_how_content_4": "Det er ikke et problem hvis du er den eneste som prøver å ta ut. Banken vil bare ta noen andres penger og gi dem til deg i stedet. Men hva skjer når for mange mennesker prøver å ta ut samtidig?",
	"bank_runs_how_content_5": "Mange i USA fant det ut da det var en krise i Silicon Valley Bank i mars 2023.",
	"bank_runs_how_content_6": "Banken hadde investert kundenes penger i statsobligasjoner som var låst i opptil 30 år. Enda verre, verdien av disse obligasjonene hadde falt dramatisk nylig, så Silicon Valley Bank kunne ikke bare selge obligasjonene for å få tilbake pengene til innskyterne. De var insolvente. De hadde ikke nok penger til å dekke uttakene til innskyterne.",
	"bank_runs_how_content_7": "Etter hvert som flere fant ut av det, ble problemet bare verre. Flere uttaksforespørsler kom inn, men mange ble ikke behandlet. Tusenvis av bedrifter innså at de ikke ville kunne betale sine ansatte på grunn av bankens svikt.",
	"bank_runs_how_content_8": "FDIC grep inn og gikk med på å gjøre innskyterne hele. Problem løst? Ikke helt...",
	"bank_runs_fdic": "BESKYTTER FDIC-FORSIKRING PENGENE MINE?",
	"bank_runs_fdic_content_1": "FDIC-forsikring er designet for å beskytte bankinnskytere i tilfelle en bank svikter. Innskudd er forsikret opptil $250 000 per innskyter. Høres bra ut, ikke sant?",
	"bank_runs_fdic_content_2": "Ikke helt. Hvis en bank svikter, hvor får FDIC pengene fra? De har et forsikringsfond med 125 milliarder dollar i seg.",
	"bank_runs_fdic_content_3": "Det høres ut som mye penger til du sammenligner det med mengden innskudd de forsikrer: nesten 10 billioner eller 10 000 milliarder dollar.",
	"bank_runs_fdic_content_4": "FDIC viser til og med på nettsiden sin at de bare har nok penger i forsikringsfondet til å dekke litt mer enn 1% av innskuddene.",
	"bank_runs_fdic_content_5": "I tilfelle en banksvikt som oversteg FDIC-forsikringsfondet, er det sannsynlig (men ikke garantert) at den amerikanske regjeringen ville trykke penger for å gjøre innskyterne hele.",
	"bank_runs_fdic_content_6": "Men å trykke penger forårsaker inflasjon, så det er ikke en god løsning.",
	"bank_runs_safe": "FINNES DET BANKER SOM IKKE BRUKER FRAKSJONELL RESERVE?",
	"bank_runs_safe_content_1": "Noen banker har prøvd å være «trygge banker» som ikke låner ut eller investerer innskyternes midler.",
	"bank_runs_safe_content_2": "Selv om disse trygge bankene ville ha null risiko for bankkriser, har søknadene deres blitt avvist av Federal Reserve. Dette betyr at de ikke lovlig kan operere som banker.",
	"bank_runs_safe_content_3": "Fordi de har blitt blokkert fra å operere, finnes det ingen banker i dag som ikke bruker fraksjonell reserve.",
	"bank_runs_safe_content_4": "Heldigvis finnes det en måte å velge bort det fraksjonelle reservesystemet ved å være din egen bank. Nei, vi snakker ikke om å stappe kontanter under madrassen.",
	"bank_runs_safe_content_5": "Å spare i kontanter er fortsatt sårbart for inflasjon.",
	"bank_runs_safe_content_6": "Vi snakker om Bitcoin: et nytt finansielt system som lar deg være din egen bank.",
	"bank_runs_protect": "KAN BITCOIN BESKYTTE MEG MOT BANKKRISER?",
	"bank_runs_protect_content_1": "Ja, Bitcoin er et fullreserve finansielt system.",
	"bank_runs_protect_content_2": "Bankkriser er umulige i Bitcoin så lenge du tar ut din Bitcoin til din egen lommebok. Ikke la din bitcoin ligge på en børs eller i en wrapper som en Bitcoin-ETF.",
	"bank_runs_protect_content_3": "Sjekk ut vår enkle Bitcoin-lommebokguide for å lære hvordan du tar ut til din egen lommebok.",
	"bank_runs_protect_content_4": "Med Bitcoin kan du endelig ha kontroll over pengene dine."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Bitcoin-lommebokguide",
	"wallets_description": "Det finnes mange forskjellige Bitcoin-lommebøker som skiller seg på viktige måter. Du kan avgjøre om en lommebok passer for deg ved å stille disse enkle spørsmålene.",
	"wallets_header": "HVORDAN LAGRE DIN BITCOIN TRYGT",
	"wallets_s1_c1": "Bitcoin-lommebøker er kompatible med hverandre, slik at du kan sende Bitcoin til hvem som helst uansett hvilken lommebok de bruker.",
	"wallets_s1_c2": "Det finnes mange forskjellige Bitcoin-lommebøker som skiller seg på viktige måter. Du kan avgjøre om en lommebok passer for deg ved å stille disse enkle spørsmålene:",
	"wallets_question_1": "ER DET EN SELVFORVARENDE LOMMEBOK?",
	"wallets_s2_c1": "En av innovasjonene til Bitcoin er muligheten til å lagre det uten å stole på en forvalter, som en bank.",
	"wallets_s2_c2": "Hvis du holder bitcoin på en børs eller i en ETF, mister du frihetsgodene til bitcoin.",
	"wallets_s2_c3": "Selvforvarende lommebøker låser opp den fulle kraften til Bitcoin: frihetspenger.",
	"wallets_s2_c4": "Med en selvforvarende lommebok er du den eneste med muligheten til å bruke eller overføre pengene dine. Ingen kan stoppe deg fra å sende eller motta pengene dine når du bruker en selvforvarende lommebok.",
	"wallets_s2_c5": "Selvforvarende lommebøker kalles også ikke-forvarende lommebøker.",
	"wallets_s3_c1": "Forvarende lommebøker er lommebøker der du ikke har kontroll over pengene dine.",
	"wallets_s3_c2": "Disse lommebøkene ligner mer på banksystemet der du må stole på en tredjepart for å gi deg tilgang til pengene dine. Hvis din Bitcoin er på en børs, bruker du en forvarende lommebok.",
	"wallets_s3_c3": "Hvis du kjøpte en Bitcoin-ETF, bruker du en forvarende lommebok som ikke lar deg ta ut til selvforvaring.",
	"wallets_s3_c4": "Forvarende lommebøker kan virke praktiske, men forvalteren har den tekniske muligheten til å stjele alle brukermidler når som helst.",
	"wallets_s3_c5": "Ikke dine nøkler, ikke dine mynter!",
	"wallets_question_2": "ER DEN VARM ELLER KALD?",
	"wallets_s4_c1": "Kalde lommebøker lagrer nøklene til din Bitcoin på en måte som aldri eksponerer dem for internett.",
	"wallets_s4_c2": "Dette begrenser betydelig angrepsvektorene en tyv kan bruke for å prøve å stjele din Bitcoin, og brukes best for store beløp Bitcoin som du ikke trenger å overføre ofte.",
	"wallets_s4_c3": "Du kan tenke på en kald lommebok som en langsiktig sparekonto, også kjent som kaldlagring.",
	"wallets_s5_c1": "Varme lommebøker lagrer nøklene til din Bitcoin på en enhet som er koblet til internett, som telefonen din.",
	"wallets_s5_c2": "Varme lommebøker anses generelt som trygge, men de kan ha flere sikkerhetssårbarheter enn kalde lommebøker.",
	"wallets_s5_c3": "Du kan tenke på en varm lommebok på samme måte som en fysisk lommebok. Du ville ikke lagret hele sparepengene dine i lommeboken, men du ville lagret litt brukspenger.",
	"wallets_s5_c4": "Varme lommebøker gjør det mye enklere å bruke din Bitcoin uten å måtte ta ut alle sparepengene fra kaldlagring.",
	"wallets_question_3": "HVORDAN VIL JEG SIKKERHETSKOPIERE GJENOPPRETTINGSFRASEN MIN?",
	"wallets_s6_c1": "Når du setter opp din Bitcoin-lommebok, vil enheten din generere en gjenopprettingsfrase. Denne gjenopprettingsfrasen (også kalt en frøfrase) inneholder 12 eller 24 ord.",
	"wallets_s6_c2": "Hvis du noen gang mister tilgangen til lommeboken din eller enheten din slutter å fungere, kan du skrive inn denne gjenopprettingsfrasen i en ny lommebok for å gjenopprette tilgangen til din Bitcoin.",
	"wallets_s6_c3": "De fleste lommebøker inkluderer et ark papir for å skrive ned gjenopprettingsfrasen, men mange foretrekker å sikkerhetskopiere denne frasen på stål i stedet. Dette gjør det mye mindre sannsynlig å miste gjenopprettingsfrasen i tilfelle en naturkatastrofe som brann eller flom.",
	"wallets_s6_c4": "Jameson Lopp har testet 70 stål-sikkerhetskopisett for å hjelpe deg å velge det som passer for deg.",
	"wallets_s6_c5": "Se Jamesons guide for metallsikkerhetskopiering av Bitcoin her.",
	"wallets_s6_c6": "Eller fortsett å scrolle for å utforske Bitcoin-lommebokalternativer.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "Leter du etter vår Lightning-lommebokguide?",
	"wallets_starter_wallet": "Flott startlommebok",
	"wallets_mobile_app": "Mobilapp",
	"wallets_2fa_support": "2FA-støtte",
	"wallets_air_gap_mode": "Air-gap-modus",
	"wallets_air_gap_camera": "Air-gap-modus + kamera",
	"wallets_bitcoin_only": "Kun Bitcoin",
	"wallets_security_features": "Mange sikkerhetsfunksjoner",
	"wallets_free": "100% gratis",
	"wallets_coldcard_mk5_costs": "Koster $189",
	"wallets_coldcard_q_costs": "Koster $289",
	"wallets_blockstream_jade_costs": "Koster $79",
	"wallets_foundation_passport_costs": "Koster $199",
	"wallets_seedsigner_costs": "Deler koster $50",
	"wallets_very_affordable": "Svært rimelig",
	"wallets_pair_with_phone": "Par med telefonen din",
	"wallets_battery": "Oppladbart batteri",
	"wallets_build_your_own": "Bygg din egen",
	"wallets_qwerty_keyboard": "Fullt QWERTY-tastatur",
	"wallets_qr_scanner": "QR-kodeskanner"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "Hvordan kjøpe Bitcoin – Steg for steg-guide",
	"buy_header": "HVORDAN KJØPE BITCOIN",
	"buy_intro_c1": "Å kjøpe Bitcoin for første gang kan virke overveldende, men det er faktisk ganske enkelt når du bryter det ned i trinn.",
	"buy_intro_c2": "Denne guiden vil lede deg gjennom prosessen med å kjøpe Bitcoin trygt og lagre det i din egen lommebok.",
	"buy_step_1_header": "TRINN 1: VELG DITT LAND",
	"buy_step_1_description": "Forskjellige land har forskjellige Bitcoin-kjøpsalternativer tilgjengelig. Velg ditt land for å se de beste alternativene for deg.",
	"buy_search_countries": "Søk etter ditt land",
	"buy_country_united_states": "USA",
	"buy_country_australia": "Australia",
	"buy_country_austria": "Østerrike",
	"buy_country_belgium": "Belgia",
	"buy_country_brazil": "Brasil",
	"buy_country_canada": "Canada",
	"buy_country_france": "Frankrike",
	"buy_country_germany": "Tyskland",
	"buy_country_ireland": "Irland",
	"buy_country_italy": "Italia",
	"buy_country_netherlands": "Nederland",
	"buy_country_new_zealand": "New Zealand",
	"buy_country_spain": "Spania",
	"buy_country_united_kingdom": "Storbritannia",
	"buy_country_argentina": "Argentina",
	"buy_country_chile": "Chile",
	"buy_country_colombia": "Colombia",
	"buy_country_costa_rica": "Costa Rica",
	"buy_country_czech_republic": "Tsjekkia",
	"buy_country_denmark": "Danmark",
	"buy_country_el_salvador": "El Salvador",
	"buy_country_estonia": "Estland",
	"buy_country_finland": "Finland",
	"buy_country_greece": "Hellas",
	"buy_country_guatemala": "Guatemala",
	"buy_country_hong_kong": "Hongkong",
	"buy_country_hungary": "Ungarn",
	"buy_country_iceland": "Island",
	"buy_country_india": "India",
	"buy_country_israel": "Israel",
	"buy_country_japan": "Japan",
	"buy_country_latvia": "Latvia",
	"buy_country_lithuania": "Litauen",
	"buy_country_luxembourg": "Luxembourg",
	"buy_country_malta": "Malta",
	"buy_country_mexico": "Mexico",
	"buy_country_norway": "Norge",
	"buy_country_panama": "Panama",
	"buy_country_poland": "Polen",
	"buy_country_portugal": "Portugal",
	"buy_country_romania": "Romania",
	"buy_country_singapore": "Singapore",
	"buy_country_slovakia": "Slovakia",
	"buy_country_slovenia": "Slovenia",
	"buy_country_south_africa": "Sør-Afrika",
	"buy_country_south_korea": "Sør-Korea",
	"buy_country_sweden": "Sverige",
	"buy_country_switzerland": "Sveits",
	"buy_country_thailand": "Thailand",
	"buy_country_turkey": "Tyrkia",
	"buy_country_ukraine": "Ukraina",
	"buy_country_uruguay": "Uruguay",
	"buy_step_2_header": "TRINN 2: VELG BETALINGSMETODE",
	"buy_step_2_description": "Det finnes to hovedmåter å kjøpe Bitcoin på: med bankoverføring eller med kontanter. Hver har forskjellige fordeler.",
	"buy_method_bank_transfer": "BANKOVERFØRING",
	"buy_method_bank_fast": "Raskt og enkelt",
	"buy_method_bank_less_private": "Mindre privat",
	"buy_method_bank_description": "Bankoverføringer er den vanligste måten å kjøpe Bitcoin på. De er raske, praktiske og har vanligvis lavere avgifter.",
	"buy_method_choose_bank": "Velg bankoverføring",
	"buy_method_cash": "KONTANTER",
	"buy_method_cash_private": "Mer privat",
	"buy_method_cash_limited": "Begrensede alternativer",
	"buy_method_cash_description": "Kontantkjøp gir mer privatliv, men har færre alternativer og kan kreve å møte noen personlig eller bruke en Bitcoin-minibank.",
	"buy_method_choose_cash": "Velg kontanter",
	"buy_step_3_header": "TRINN 3: KJØPSALTERNATIVER",
	"buy_step_3_description": "Her er de beste Bitcoin-kjøpsalternativene for ditt land og betalingsmetode:",
	"buy_platform_recommended": "ANBEFALT",
	"buy_platform_strike_description": "Strike er den raskeste og enkleste måten å kjøpe Bitcoin med lave avgifter og umiddelbar Lightning Network-støtte.",
	"buy_platform_swan_description": "Swan Bitcoin spesialiserer seg på kun-Bitcoin-tjenester med dollar-cost averaging og utdanningsressurser.",
	"buy_platform_river_description": "River tilbyr Bitcoin-kjøp, -utvinning og forvaringstjenester med fokus på utdanning og sikkerhet.",
	"buy_platform_coinsquare_description": "Coinsquare er en kanadisk Bitcoin-børs med sterk reguleringsoverholdelse og kundestøtte.",
	"buy_platform_kraken_description": "Kraken er en etablert Bitcoin-børs med avanserte handelsfunksjoner og sterk sikkerhet.",
	"buy_platform_atm_description": "Bitcoin-minibanker lar deg kjøpe Bitcoin med kontanter umiddelbart. Finn en nær deg med Coin ATM Radar.",
	"buy_platform_bisq_description": "Bisq er en desentralisert peer-to-peer-børs som muliggjør privat Bitcoin-handel uten KYC.",
	"buy_platform_feature_instant": "Umiddelbare kjøp",
	"buy_platform_feature_low_fees": "Lave avgifter",
	"buy_platform_feature_lightning": "Lightning Network",
	"buy_platform_feature_dca": "Dollar-cost averaging",
	"buy_platform_feature_education": "Utdanningsressurser",
	"buy_platform_feature_withdrawal": "Enkelt uttak",
	"buy_platform_feature_mining": "Bitcoin-utvinning",
	"buy_platform_feature_custody": "Forvaringstjenester",
	"buy_platform_feature_canadian": "Kanadisk fokus",
	"buy_platform_feature_regulated": "Regulert børs",
	"buy_platform_feature_support": "Kundestøtte",
	"buy_platform_feature_established": "Etablert plattform",
	"buy_platform_feature_security": "Sterk sikkerhet",
	"buy_platform_feature_advanced": "Avanserte funksjoner",
	"buy_platform_feature_cash": "Kontantkjøp",
	"buy_platform_feature_anonymous": "Mer anonymt",
	"buy_platform_feature_p2p": "Peer-to-peer",
	"buy_platform_feature_private": "Privat handel",
	"buy_platform_feature_decentralized": "Desentralisert",
	"buy_platform_relai_description": "Relai er en sveitsisk kun-Bitcoin-app med selvforvarende lommebok, auto-invester-funksjoner og lave avgifter for europeiske brukere.",
	"buy_platform_feature_bitcoin_only": "Kun Bitcoin",
	"buy_platform_feature_self_custody": "Selvforvarende lommebok",
	"buy_platform_feature_auto_invest": "Automatiske investeringsplaner",
	"buy_platform_feature_european": "Europeisk fokus",
	"buy_step_4_header": "TRINN 4: LAGRE DIN BITCOIN TRYGT",
	"buy_step_4_c1": "Etter å ha kjøpt Bitcoin er det viktigste trinnet å flytte det til din egen lommebok der du kontrollerer de private nøklene.",
	"buy_step_4_c2": "Å la Bitcoin ligge på en børs er risikabelt fordi du faktisk ikke eier Bitcoin – det gjør børsen.",
	"buy_step_4_c3": "Når du kontrollerer dine egne private nøkler, har du ekte eierskap av din Bitcoin og ingen kan ta det fra deg.",
	"buy_step_4_c4": "Lær hvordan du velger riktig Bitcoin-lommebok for dine behov:",
	"buy_cta_wallets": "Se vår Bitcoin-lommebokguide"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Bitcoin Lightning-lommebokguide",
	"lightning_description": "Lightning-lommebøker gjør det mulig å sende Bitcoin raskt og billig samtidig som du opprettholder din personlige suverenitet.",
	"lightning_header": "LIGHTNING-LOMMEBOKGUIDE",
	"lightning_s1_c1": "Lightning gjør det mulig å sende Bitcoin-betalinger raskt og billig.",
	"lightning_s1_c2": "Det er viktig å vite at bruk av Lightning innebærer kompromisser. I bytte mot raskere, billigere Bitcoin-betalinger ofrer du ofte noe sikkerhet.",
	"lightning_s1_c3": "Generelt bør Lightning kun brukes med små beløp bitcoin. Du bør bare lagre store beløp bitcoin i en maskinvarelommebok.",
	"lightning_s1_c4": "Sjekk ut vår maskinvarelommebokguide for mer informasjon.",
	"lightning_s1_c5": "Ikke alle Lightning-lommebøker er like. Du kan avgjøre hvilken lommebok som har riktig balanse av kompromisser for deg ved å stille ett enkelt spørsmål:",
	"lightning_question_1": "HVILKEN KOMPROMISSBALANSE ER RIKTIG FOR MEG?",
	"lightning_s2_c1": "En av innovasjonene til Bitcoin er muligheten til å lagre det uten å stole på en forvalter, som en bank. Selvforvarende lommebøker låser opp den fulle kraften til Bitcoin.",
	"lightning_s2_c2": "Med en selvforvarende lommebok er du den eneste med muligheten til å bruke eller overføre pengene dine. Ingen kan stoppe deg, sensurere deg eller stjele fra deg når du bruker en selvforvarende lommebok. Disse kalles også ikke-forvarende lommebøker.",
	"lightning_s2_c3": "Den mest suverene måten å bruke Lightning på er ved å kjøre din egen node.",
	"lightning_s2_c4": "Denne guiden fokuserer på enkle Lightning-lommebøker som ikke krever din egen node.",
	"lightning_s2_c5": "Det er viktig å vite at selv ved bruk av en ikke-forvarende Lightning-lommebok, stoler du fortsatt på lommebokskaperen om å ikke sende en ondsinnet appoppdatering og stjele midlene dine.",
	"lightning_s3_c1": "Forvarende lommebøker er lommebøker der du ikke har kontroll over pengene dine.",
	"lightning_s3_c2": "Disse lommebøkene ligner mer på banksystemet der du må stole på en tredjepart for å gi deg tilgang til pengene dine. Hvis din Bitcoin er på en børs, bruker du en forvarende lommebok.",
	"lightning_s3_c3": "Forvarende lommebøker kan virke praktiske, men forvalteren har den tekniske muligheten til å stjele alle brukermidler når som helst.",
	"lightning_s3_c4": "Noen foretrekker forvarende Lightning-lommebøker for små beløp bitcoin på grunn av brukervennligheten. Bare husk: ikke dine nøkler, ikke dine mynter!",
	"lightning_question_2": "VELG DIN LOMMEBOK",
	"lightning_s4_c1": "Med alt dette i bakhodet kan du nå velge lightning-lommeboken som har riktig kompromissbalanse for deg.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "Mange funksjoner",
	"lightning_mobile_app": "Mobilapp",
	"lightning_free": "100% gratis",
	"lightning_merchants": "Flott for forhandlere",
	"lightning_starter": "Flott startlommebok",
	"lightning_browser": "Nettleserbasert",
	"lightning_custodial": "Helt forvarende lommebok",
	"lightning_cta_hardware": "Leter du etter vår Bitcoin-maskinvarelommebokguide?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "Gratis Bitcoin-klistremerker fra bitcoin.rocks",
	"stickers_description": "Sett et bitcoin-klistremerke offentlig for å oransjepille de rundt deg.",
	"stickers_header": "GRATIS BITCOIN-KLISTREMERKER",
	"stickers_choose_header": "VELG DIN KLISTREMERKEPAKKE",
	"stickers_choose_c1": "Vårt oppdrag er å hjelpe deg med å oransjepille flere mennesker ved å sette Bitcoin-klistremerker offentlig. Alle klistremerkene våre har QR-koder som lenker til utdanningssider om",
	"stickers_choose_c2": "Bitcoin",
	"stickers_choose_c3": "inflasjon",
	"stickers_choose_c4": "Velg din klistremerkepakke nedenfor",
	"stickers_text_pack": "TEKSTPAKKEN",
	"stickers_signs_pack": "SKILTPAKKEN",
	"stickers_instructions_1": "Skriv inn postadressen din, så sender vi deg en gratis Bitcoin-klistremerkepakke i posten! Klistremerkene dine sendes i en vanlig hvit konvolutt.",
	"stickers_instructions_2": "Adressedata slettes etter at dine gratis klistremerker er sendt.",
	"stickers_share_header": "DEL DINE KLISTREMERKESTEDER",
	"stickers_share_c1": "Del klistremerkestedene dine med oss på Nostr og se hvor andre plasserer sine klistremerker.",
	"stickers_btn_share_on_nostr": "DEL PÅ NOSTR",
	"stickers_btn_what_is_nostr": "HVA ER NOSTR?",
	"stickers_flyers_link_before": "Mens du er i gang, skriv ut og heng opp dine egne ",
	"stickers_flyers_link_text": "Bitcoin-flygeblad",
	"stickers_flyers_link_after": " for å oransjepille enda flere mennesker.",
	"stickers_country_global_print": "Globalt — Skriv ut mine egne klistremerker",
	"stickers_country_global_order": "Globalt — Bestill i bulk",
	"placeholder_name_optional": "Navn (valgfritt)",
	"placeholder_address_line_1": "Adresselinje 1",
	"placeholder_address_line_2": "Adresselinje 2 (valgfritt)",
	"placeholder_city": "By",
	"placeholder_state": "Delstat",
	"placeholder_province": "Provins",
	"placeholder_zip_code": "Postnummer",
	"placeholder_postal_code": "Postnummer",
	"placeholder_language": "Språk",
	"placeholder_which_stickers": "Hvilke klistremerker?",
	"placeholder_email_optional": "Skriv inn e-postadressen din for å bli varslet (valgfritt)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "Gratis Bitcoin-postkort fra bitcoin.rocks",
	"postcards_description": "Få en gratis Bitcoin-postkortpakke og del Bitcoin med noen du kjenner.",
	"postcards_header": "POSTKORTPROGRAMMET ER AVSLUTTET",
	"postcards_program_closed_message": "Vårt gratis Bitcoin-postkortprogram er avsluttet. Takk til alle som deltok i å spre Bitcoin-utdanning gjennom posten!",
	"postcards_sticker_alternative_header": "FÅ GRATIS BITCOIN-KLISTREMERKER I STEDET",
	"postcards_sticker_alternative_message": "Fortsett å spre Bitcoin-bevissthet med vårt gratis klistremerkeprogram! Våre Bitcoin-klistremerker er perfekte for deling på offentlige steder og kommer med QR-koder som lenker til utdanningsinnhold.",
	"postcards_sticker_cta": "FÅ GRATIS KLISTREMERKER",
	"postcards_step_2": "SLIK SÅ POSTKORTENE UT",
	"postcards_instructions_4": "Vi laget disse postkortene for å gjøre det enklere for deg å introdusere noen du kjenner for Bitcoin! Bare legg til en adresse og et frimerke og slipp postkortet i posten.",
	"postcards_instructions_5": "Vårt oppdrag er å akselerere Bitcoin-adopsjon. Du kan hjelpe ved å skaffe gratis klistremerker og plassere dem på offentlige steder!",
	"postcards_instructions_6": "Vi kjenner alle noen som kunne hatt nytte av å lære mer om Bitcoin. Del Bitcoin-klistremerker med dem i dag!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "Hjelp oss med å sette opp disse Bitcoin-skiltene over hele Amerika!",
	"signs_title": "Gratis Bitcoin-skilt fra bitcoin.rocks",
	"signs_choose_header": "TAKK FOR AT DU HJELPER OSS MED Å SETTE OPP DISSE BITCOIN-SKILTENE OVER HELE AMERIKA!",
	"signs_choose_c1": "Vi er nå helt tomme for skilt! Vårt oppdrag er å akselerere Bitcoin-adopsjon gjennom utdanning.",
	"signs_choose_c2": "Mange av dere hjalp ved å sette opp disse gratis Bitcoin-skiltene offentlig. Alle skiltene våre har QR-koder som lenker til en utdanningsside om",
	"signs_choose_c3": "inflasjon",
	"signs_choose_c4": "Takket være vårt fantastiske fellesskap nådde vi tusenvis av mennesker og hjalp dem med å ta sine første skritt ned i Bitcoin-kaninhullet.",
	"signs_share_header": "DEL DINE SKILTSTEDER",
	"signs_share_c1": "Del et bilde av ditt skiltsted med oss på Nostr og se hvor andre setter opp sine skilt.",
	"signs_btn_share_on_nostr": "DEL PÅ NOSTR",
	"signs_btn_what_is_nostr": "HVA ER NOSTR?",
	"signs_instructions_1": "Skriv inn postadressen din, så sender vi deg en boks med 10 Bitcoin-skilt i posten!",
	"signs_instructions_2": "Adressedata slettes etter at dine gratis skilt er sendt."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "Gratis Bitcoin-flygeblad fra bitcoin.rocks",
	"flyers_description": "Skriv ut et Bitcoin-flygeblad hjemme og heng det opp offentlig for å oransjepille de rundt deg.",
	"flyers_header_1": "SKRIV UT OG HENG OPP",
	"flyers_header_2": "BITCOIN-FLYGEBLAD",
	"flyers_intro_header": "HVORDAN SKRIVE UT OG HENGE OPP DISSE BITCOIN-FLYGEBLADENE",
	"flyers_intro_c1": "Vårt oppdrag er å hjelpe deg med å oransjepille flere mennesker ved å henge opp Bitcoin-flygeblad offentlig. Dette flygebladet har en QR-kode som lenker til vår",
	"flyers_intro_c2": "pedagogiske Bitcoin-nettside.",
	"flyers_intro_c3": "inflasjon",
	"flyers_intro_c4": "Skriv ut dette flygebladet hjemme eller på et trykkeri. Heng det deretter opp på oppslagstavler, telefonstolper rundt om i byen og andre offentlige steder der folk kan se det og lære om Bitcoin.",
	"flyers_intro_c5": "Mens du er i gang, bestill en pakke med våre",
	"flyers_intro_c6": "gratis Bitcoin-klistremerker",
	"flyers_intro_c7": "for å oransjepille enda flere mennesker.",
	"flyers_btn_download": "LAST NED FLYGEBLAD",
	"flyers_btn_print": "SKRIV UT FLYGEBLAD",
	"flyers_share_header": "DEL DINE FLYGEBLADSTEDER",
	"flyers_share_c1": "Del flygebladstedene dine med oss på Nostr og se hvor andre henger opp sine flygeblad.",
	"flyers_btn_share_on_nostr": "DEL PÅ NOSTR",
	"flyers_btn_what_is_nostr": "HVA ER NOSTR?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "Bli med og hjelp med å spre Bitcoin",
	"get_involved_description": "Våre gratis ressurser gjør det enklere å spre Bitcoin-adopsjon.",
	"get_involved_header": "BLI MED",
	"get_involved_header_2": "SPRE BITCOIN",
	"get_involved_intro_1": "Det kan være deprimerende å leve i den nåværende tilstanden i verden vår.",
	"get_involved_intro_2": "Pengene våre er ødelagt. Som et resultat er grunnleggende deler av samfunnet også ødelagt.",
	"get_involved_intro_3": "Hvis du allerede er interessert i Bitcoin, kjenner du følelsen av håp som Bitcoin kan gi. Håp for en lysere fremtid gjort mulig av bedre penger.",
	"get_involved_intro_4": "Men så mange mennesker rundt deg vet ikke om Bitcoin. De lever i den samme ødelagte verden som deg, men uten et fyrtårn av håp som hjelper dem gjennom mørket.",
	"get_involved_intro_5": "Men du kan hjelpe med å endre det. Vi har laget flere gratis ressurser for å gjøre det enklere å spre håpet som Bitcoin bringer til de rundt deg.",
	"get_involved_sticker_header": "Sett et klistremerke offentlig",
	"get_involved_sticker_content_1": "Du kan hjelpe med å utdanne de rundt deg om Bitcoin uten å måtte samhandle med noen. Bare sett et av våre gratis Bitcoin-klistremerker offentlig.",
	"get_involved_sticker_content_2": "Hundrevis av mennesker skanner QR-kodene på disse klistremerkene hver måned. Inflasjonsklistremerkene lenker til en side om",
	"get_involved_sticker_content_3": "Bitcoin som en løsning på inflasjon.",
	"get_involved_sticker_content_4": "De andre klistremerkene lenker til vår pedagogiske hjemmeside som viser folk hvordan",
	"get_involved_sticker_content_5": "Bitcoin bygger en bedre verden.",
	"get_involved_sticker_content_6": "Ved å sette disse klistremerkene opp i ditt lokalsamfunn på steder folk vil se dem, kan du hjelpe de rundt deg med å ta sine første skritt ned i Bitcoin-kaninhullet.",
	"get_involved_request_a": "BESTILL EN",
	"get_involved_sticker_pack": "KLISTREMERKEPAKKE",
	"get_involved_postcard_header": "Send et postkort",
	"get_involved_postcard_content_1": "Du kan hjelpe med å spre håpet om Bitcoin til noen du kjenner ved å sende dem et av våre gratis postkort.",
	"get_involved_postcard_content_2": "Baksiden av hvert postkort inneholder en overbevisende tekst om Bitcoin sammen med en QR-kode for å lære mer.",
	"get_involved_postcard_content_3": "Ved å sende noen et Bitcoin-postkort kan du hjelpe dem med å se Bitcoin i et nytt lys.",
	"get_involved_postcard_pack": "POSTKORTPAKKE",
	"get_involved_business_header": "Innrullere en bedrift",
	"get_involved_business_content_1": "Vil du hjelpe med å bygge den sirkulære Bitcoin-økonomien? Vår Bitcoin-bedriftspakke gjør det enkelt å nærme seg en bedrift om å akseptere Bitcoin-betalinger.",
	"get_involved_business_content_2": "Hver bedriftspakke inkluderer flygeblad som fremhever fordelene med å akseptere Bitcoin-betalinger. Hvert flygeblad lenker til en rekke",
	"get_involved_business_content_3": "gratis Bitcoin-bedriftsressurser.",
	"get_involved_business_kit": "BEDRIFTSPAKKE"
});

console.log(`\nDone! Created 9 content files.`);
