/**
 * Creates Slovak (sk) index_sk.json translation file
 */
const fs = require('fs');
const path = require('path');
const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'sk';
const today = '2026-04-04';

const data = {
	"@metadata": { "authors": ["Satoshi"], "last-updated": today, "locale": lang },
	"bitcoin_builds_a_better_world": "Bitcoin buduje lepší svet.",
	"home_description": "Bitcoin sú lepšie peniaze, ktoré budujú lepší svet. Bitcoin chránil ľudské práva, zachránil ľudí pred vysokou infláciou, podporil miestnych farmárov, znížil emisie z ťažby ropy a mnoho ďalšieho.",
	"home_intro": "Bitcoin sú lepšie peniaze, ktoré budujú lepší svet. Klepnite na kategóriu nižšie a zistite, ako Bitcoin veci zlepšuje, alebo jednoducho scrollujte a preskúmajte.",
	"home_btn_money": "LEPŠIE PENIAZE",
	"home_btn_salary": "VÁŠ PLAT",
	"home_btn_freedom": "SLOBODA",
	"home_btn_human_rights": "ĽUDSKÉ PRÁVA",
	"home_btn_equality": "ROVNOSŤ",
	"home_btn_property_rights": "VLASTNÍCKE PRÁVA",
	"home_btn_housing": "BÝVANIE",
	"home_btn_business": "PODNIKANIE",
	"home_btn_crowdfunding": "CROWDFUNDING",
	"home_btn_energy": "ENERGIA",
	"home_btn_environment": "ŽIVOTNÉ PROSTREDIE",
	"home_btn_food": "JEDLO",
	"home_btn_art": "UMENIE",
	"home_btn_politics": "POLITIKA",
	"home_btn_war": "VOJNA",
	"home_btn_coding": "PROGRAMOVANIE",
	"home_btn_networks": "SIETE",
	"home_btn_payments": "PLATBY",
	"home_btn_self_custody": "VLASTNÁ SPRÁVA",
	"home_btn_you": "VY",
	"home_section_bitcoin_is": "BITCOIN JE",
	"home_section_bitcoin_and": "BITCOIN A",
	"home_link_type_website": "WEB",
	"home_link_type_video": "VIDEO",
	"home_link_type_article": "ČLÁNOK",
	"home_link_type_podcast": "PODCAST",
	"home_link_type_business_kit": "PODNIKATEĽSKÁ SADA",
	"home_link_type_data": "DÁTA",
	"home_link_type_research": "VÝSKUM",
	"home_link_type_story": "PRÍBEH",
	"home_link_type_book_excerpt": "ÚRYVOK Z KNIHY",
	"home_link_type_street_art": "STREET ART",
	"home_link_type_outreach": "OSVETA",
	"home_link_type_campaign": "KAMPAŇ",
	"home_link_type_software": "SOFTVÉR",
	"home_link_type_hardware": "HARDVÉR",
	"home_link_type_guide": "SPRIEVODCA",
	"home_link_type_email": "E-MAIL",
	"home_link_title_inflation": "Bitcoin nemá infláciu",
	"home_link_title_bank_runs": "Bitcoin nemá bankové runy",
	"home_link_title_gold": "Bitcoin vs Zlato",
	"home_link_title_crypto": "Bitcoin vs Krypto",
	"home_link_title_cash": "Bitcoin vs Hotovosť",
	"home_link_title_bonds": "Bitcoin vs Dlhopisy",
	"home_link_title_cbdc": "Bitcoin vs CBDC",
	"home_link_title_your_salary_1": "Zistite, o koľko musí vzrásť váš plat, aby udržal krok s infláciou.",
	"home_link_title_freedom_1": "Prečo Bitcoin záleží pre slobodu",
	"home_link_title_freedom_2": "Bitcoin ponúka slobodu od politického útlaku",
	"home_link_title_human_rights_1": "Ako Bitcoin presadzuje ľudské práva",
	"home_link_title_human_rights_2": "Tichá bitcoinová revolúcia v Afrike",
	"home_link_title_human_rights_3": "Bitcoin chráni ľudské práva po celom svete",
	"home_link_title_equality_1": "Bitcoin prináša nádej a príležitosti Juhoafričanom",
	"home_link_title_equality_2": "Ako môže byť Bitcoin prielomom pre černošských Američanov",
	"home_link_title_property_rights_1": "Bitcoin je dokonalá forma vlastníctva",
	"home_link_title_property_rights_2": "Bitcoin vs Nehnuteľnosti",
	"home_link_title_housing_1": "Ako Bitcoin znovu sprístupní bývanie",
	"home_link_title_business_3": "Bitcoin vs Akcie",
	"home_link_title_business_1": "Zistite, prečo je Bitcoin dobrý pre podnikanie",
	"home_link_title_business_2": "Presvedčte miestnu firmu, aby prijímala Bitcoin",
	"home_link_title_crowdfunding_1": "Ako Bitcoin podporil najväčšie nigérijské protesty za generáciu",
	"home_link_title_crowdfunding_2": "Kanadský protest vodičov kamiónov zbiera peniaze v Bitcoine po tom, čo GoFundMe zablokoval dary",
	"home_link_title_crowdfunding_3": "Geyser = Crowdfunding s Bitcoinom",
	"home_link_title_energy_1": "Ako Bitcoin stabilizuje texaskú energetickú sieť",
	"home_link_title_energy_2": "Prečo Bitcoin spotrebováva energiu?",
	"home_link_title_energy_3": "Spotreba energie Bitcoinu nie je problém. Tu je dôvod.",
	"home_link_title_energy_4": "Ťažba Bitcoinu stabilizuje energetické siete prostredníctvom riadenia dopytu",
	"home_link_title_energy_5": "Ťažiari Bitcoinu prinášajú vodnú energiu vidieckym africkým komunitám",
	"home_link_title_energy_6": "Ako Bitcoin motivuje obnoviteľnú energiu",
	"home_link_title_environment_1": "Ako ťažba Bitcoinu znižuje globálne emisie metánu",
	"home_link_title_environment_2": "Ako ťažba Bitcoinu zachránila národný park",
	"home_link_title_environment_3": "Bitcoin je najzelenší priemysel na Zemi!",
	"home_link_title_environment_4": "Ťažba Bitcoinu bráni spálenému zemnému plynu v znečisťovaní atmosféry",
	"home_link_title_food_1": "Ako inflácia ovplyvňuje ceny potravín",
	"home_link_title_food_2": "Ako fiat peniaze škodia potravinám, farmám a pôde",
	"home_link_title_fine_art": "Bitcoin vs Umenie",
	"home_link_title_art_1": "Pripojte sa k našej iniciatíve bitcoinových nálepiek",
	"home_link_title_art_2": "Pošlite bitcoinovú pohľadnicu niekomu, koho poznáte",
	"home_link_title_art_3": "Tlačte a vylepujte bitcoinové letáky",
	"home_link_title_politics_1": "Bitcoin je politický paradox",
	"home_link_title_politics_2": "Môžete hlasovať za lepšie peniaze",
	"home_link_title_war_1": "Ako by Bitcoin mohol ukončiť nekonečnú vojnu",
	"home_link_title_war_2": "Bitcoin a veteráni: prirodzená súhra",
	"home_link_title_war_3": "Ako Bitcoin pomáha civilistom uniknúť vojne v Sudáne",
	"home_link_title_coding_1": "Interaktívny tutoriál o technickej stránke Bitcoinu",
	"home_link_title_coding_2": "bitcoinSwitch: prestavte akékoľvek zariadenie na prijímanie Bitcoinu",
	"home_link_title_coding_3": "Programujte si cestu tajomstvami Bitcoinu",
	"home_link_title_networks_1": "Živý pohľad na Bitcoinovú sieť",
	"home_link_title_networks_2": "Bitcoin vs Banky",
	"home_link_title_payments_1": "Bitcoin vs Visa",
	"home_link_title_payments_2": "Pohľad na Lightning Network (okamžité bitcoinové platby)",
	"home_link_title_payments_3": "Bitcoinová peňaženka El Salvadoru by mohla ušetriť Salvádorčanom 400 miliónov dolárov ročne na remitenciách",
	"home_link_title_payments_4": "Získajte svoju Lightning adresu pre príjem okamžitých bitcoinových platieb",
	"home_link_title_self_custody_1": "Ako bezpečne uchovávať svoj Bitcoin",
	"home_link_title_self_custody_2": "6 dôvodov, prečo vybrať svoj Bitcoin z búrz",
	"home_link_title_self_custody_3": "Zlato, Bitcoin a vlastná správa",
	"home_link_title_get_started_1": "Naučte sa základy Bitcoinu",
	"home_link_title_get_started_2": "Získajte svoju prvú bitcoinovú peňaženku",
	"home_link_title_get_started_3": "Ako kúpiť Bitcoin",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Kalkulačka zloženej inflácie",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}\n\nDone! Created index.json.`);
