/**
 * Creates Slovenian (sl) index_sl.json translation file
 */
const fs = require('fs');
const path = require('path');
const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'sl';
const today = '2026-04-11';

const data = {
	"@metadata": { "authors": ["Satoshi"], "last-updated": today, "locale": lang },
	"bitcoin_builds_a_better_world": "Bitcoin gradi boljši svet.",
	"home_description": "Bitcoin je boljši denar, ki gradi boljši svet. Bitcoin je zaščitil človekove pravice, rešil ljudi pred visoko inflacijo, podprl lokalne kmete, zmanjšal emisije pri črpanju nafte in še veliko več.",
	"home_intro": "Bitcoin je boljši denar, ki gradi boljši svet. Tapnite na kategorijo spodaj, da ugotovite, kako Bitcoin izboljšuje stvari, ali pa preprosto začnite drseti in raziskujte.",
	"home_btn_money": "BOLJŠI DENAR",
	"home_btn_salary": "VAŠA PLAČA",
	"home_btn_freedom": "SVOBODA",
	"home_btn_human_rights": "ČLOVEKOVE PRAVICE",
	"home_btn_equality": "ENAKOST",
	"home_btn_property_rights": "LASTNINSKE PRAVICE",
	"home_btn_housing": "STANOVANJA",
	"home_btn_business": "PODJETJA",
	"home_btn_crowdfunding": "MNOŽIČNO FINANCIRANJE",
	"home_btn_energy": "ENERGIJA",
	"home_btn_environment": "OKOLJE",
	"home_btn_food": "HRANA",
	"home_btn_art": "UMETNOST",
	"home_btn_politics": "POLITIKA",
	"home_btn_war": "VOJNA",
	"home_btn_coding": "PROGRAMIRANJE",
	"home_btn_networks": "OMREŽJA",
	"home_btn_payments": "PLAČILA",
	"home_btn_self_custody": "LASTNA HRAMBA",
	"home_btn_you": "VI",
	"home_section_bitcoin_is": "BITCOIN JE",
	"home_section_bitcoin_and": "BITCOIN IN",
	"home_link_type_website": "SPLETNA STRAN",
	"home_link_type_video": "VIDEO",
	"home_link_type_article": "ČLANEK",
	"home_link_type_podcast": "PODCAST",
	"home_link_type_business_kit": "POSLOVNI KOMPLET",
	"home_link_type_data": "PODATKI",
	"home_link_type_research": "RAZISKAVA",
	"home_link_type_story": "ZGODBA",
	"home_link_type_book_excerpt": "ODLOMEK IZ KNJIGE",
	"home_link_type_street_art": "ULIČNA UMETNOST",
	"home_link_type_outreach": "OZAVEŠČANJE",
	"home_link_type_campaign": "KAMPANJA",
	"home_link_type_software": "PROGRAMSKA OPREMA",
	"home_link_type_hardware": "STROJNA OPREMA",
	"home_link_type_guide": "VODIČ",
	"home_link_type_email": "E-POŠTA",
	"home_link_title_inflation": "Bitcoin nima inflacije",
	"home_link_title_bank_runs": "Bitcoin nima bančnih naletov",
	"home_link_title_gold": "Bitcoin proti zlatu",
	"home_link_title_crypto": "Bitcoin proti kriptu",
	"home_link_title_cash": "Bitcoin proti gotovini",
	"home_link_title_bonds": "Bitcoin proti obveznicam",
	"home_link_title_cbdc": "Bitcoin proti CBDC",
	"home_link_title_your_salary_1": "Ugotovite, za koliko se mora vaša plača povečati, da drži korak z inflacijo.",
	"home_link_title_freedom_1": "Zakaj je Bitcoin pomemben za svobodo",
	"home_link_title_freedom_2": "Bitcoin ponuja svobodo pred politično represijo",
	"home_link_title_human_rights_1": "Kako Bitcoin uveljavlja človekove pravice",
	"home_link_title_human_rights_2": "Tiha bitcoinova revolucija v Afriki",
	"home_link_title_human_rights_3": "Bitcoin ščiti človekove pravice po vsem svetu",
	"home_link_title_equality_1": "Bitcoin prinaša upanje in priložnosti Južnoafričanom",
	"home_link_title_equality_2": "Kako je lahko Bitcoin prelomnica za črne Američane",
	"home_link_title_property_rights_1": "Bitcoin je popolna oblika lastnine",
	"home_link_title_property_rights_2": "Bitcoin proti nepremičninam",
	"home_link_title_housing_1": "Kako bo Bitcoin znova naredil stanovanja dostopna",
	"home_link_title_business_3": "Bitcoin proti delnicam",
	"home_link_title_business_1": "Ugotovite, zakaj je Bitcoin dober za podjetja",
	"home_link_title_business_2": "Prepričajte lokalno podjetje, da začne sprejemati Bitcoin",
	"home_link_title_crowdfunding_1": "Kako je Bitcoin omogočil največje nigerijske proteste v generaciji",
	"home_link_title_crowdfunding_2": "Kanadski protest tovornjačarjev zbira denar v Bitcoinu, potem ko GoFundMe blokira donacije",
	"home_link_title_crowdfunding_3": "Geyser = Množično financiranje z Bitcoinom",
	"home_link_title_energy_1": "Kako Bitcoin stabilizira teksaško energetsko omrežje",
	"home_link_title_energy_2": "Zakaj Bitcoin porablja energijo?",
	"home_link_title_energy_3": "Poraba energije Bitcoina ni problem. Tukaj je razlog.",
	"home_link_title_energy_4": "Rudarjenje Bitcoina stabilizira energetska omrežja z upravljanjem povpraševanja",
	"home_link_title_energy_5": "Rudarji Bitcoina prinašajo vodno energijo podeželskim afriškim skupnostim",
	"home_link_title_energy_6": "Kako Bitcoin spodbuja obnovljivo energijo",
	"home_link_title_environment_1": "Kako rudarjenje Bitcoina zmanjšuje globalne emisije metana",
	"home_link_title_environment_2": "Kako je rudarjenje Bitcoina rešilo nacionalni park",
	"home_link_title_environment_3": "Bitcoin je najčistejša industrija na Zemlji!",
	"home_link_title_environment_4": "Rudarjenje Bitcoina preprečuje sežiganju zemeljskega plina onesnaževanje atmosfere",
	"home_link_title_food_1": "Kako inflacija vpliva na cene hrane",
	"home_link_title_food_2": "Kako fiat denar škoduje hrani, kmetijam in prsti Zemlje",
	"home_link_title_fine_art": "Bitcoin proti umetnosti",
	"home_link_title_art_1": "Pridružite se naši pobudi z bitcoinovimi nalepkami",
	"home_link_title_art_2": "Pošljite bitcoinovo razglednico nekomu, ki ga poznate",
	"home_link_title_art_3": "Tiskajte in lepite bitcoinove letake",
	"home_link_title_politics_1": "Bitcoin je politični paradoks",
	"home_link_title_politics_2": "Glasujete lahko za boljši denar",
	"home_link_title_war_1": "Kako bi Bitcoin lahko končal neskončno vojno",
	"home_link_title_war_2": "Bitcoin in veterani: naravna usklajenost",
	"home_link_title_war_3": "Kako Bitcoin pomaga civilistom pobegniti vojni v Sudanu",
	"home_link_title_coding_1": "Interaktivna vadnica o tehnični strani Bitcoina",
	"home_link_title_coding_2": "bitcoinSwitch: predelaj katero koli napravo za sprejemanje Bitcoina",
	"home_link_title_coding_3": "Programirajte si pot skozi skrivnosti Bitcoina",
	"home_link_title_networks_1": "Živ pogled na omrežje Bitcoin",
	"home_link_title_networks_2": "Bitcoin proti bankam",
	"home_link_title_payments_1": "Bitcoin proti Visi",
	"home_link_title_payments_2": "Pogled na Lightning Network (takojšnja bitcoinova plačila)",
	"home_link_title_payments_3": "Bitcoinova denarnica El Salvadorja bi lahko Salvadorcem prihranila 400 milijonov dolarjev letno pri nakazilih",
	"home_link_title_payments_4": "Pridobite svoj Lightning naslov za prejemanje takojšnjih bitcoinovih plačil",
	"home_link_title_self_custody_1": "Kako varno shraniti svoj Bitcoin",
	"home_link_title_self_custody_2": "6 razlogov za dvig vašega Bitcoina z borz",
	"home_link_title_self_custody_3": "Zlato, Bitcoin in lastna hramba",
	"home_link_title_get_started_1": "Spoznajte osnove Bitcoina",
	"home_link_title_get_started_2": "Pridobite svojo prvo bitcoinovo denarnico",
	"home_link_title_get_started_3": "Kako kupiti Bitcoin",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Kalkulator sestavljene inflacije",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}\n\nDone! Created index.json.`);
