/**
 * Creates Danish (da) translation file for common.json (~180+ keys)
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'da';
const today = '2026-04-07';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"common_footer_mission_1": "Missionen for bitcoin.rocks er at accelerere bitcoin-adoption gennem uddannelse.",
	"common_footer_mission_2": "Lær hvordan du kan bidrage til dette open source-projekt.",
	"common_footer_follow_first_half": "Følg os på Nostr ved at søge efter",
	"common_footer_follow_second_half": "i en hvilken som helst Nostr-klient.",
	"common_footer_what_is_nostr": "Hvad er Nostr?",
	"common_footer_about": "Om os",
	"common_footer_email_us": "Send os en e-mail:",
	"common_cta_section_get_started": "KOM I GANG",
	"common_cta_section_with_bitcoin": "MED BITCOIN",
	"common_cta_section_title_1": "Lær det grundlæggende om Bitcoin",
	"common_cta_section_title_1_alt": "Lær mere om Bitcoin",
	"common_cta_section_title_2": "Få din første Bitcoin-wallet",
	"common_cta_section_title_3": "Sådan køber du Bitcoin",
	"common_cta_link_type_email": "E-MAIL",
	"common_cta_link_type_guide": "GUIDE",
	"common_cta_link_type_website": "HJEMMESIDE",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "HVAD ER BITCOIN?",
	"common_what_is_bitcoin_content_1": "Bitcoin er to ting: digitale penge og et betalingsnetværk. Du kan sende Bitcoin (de digitale penge) direkte til andre mennesker ved hjælp af Bitcoin-netværket (betalingsnetværket).",
	"common_what_is_bitcoin_content_2": "Bitcoin er en radikalt ny måde at opbevare og overføre værdi på. I modsætning til normale finansielle netværk kan Bitcoin-netværket fungere uden centrale myndigheder eller betroede administratorer. Det gør Bitcoin til de første åbne og grænseløse penge nogensinde.",
	"common_what_is_bitcoin_content_3": "Bitcoin er digitale penge, der giver dig fuldstændigt ejerskab over din formue. For første gang i menneskehedens historie kan alle eje et aktiv, der virkelig er knapt, ikke kræver tilladelse for at bruges, og ikke kan konfiskeres, når det opbevares korrekt.",
	"common_what_is_bitcoin_content_4": "Bitcoin kan sendes hvor som helst i verden, hurtigt og billigt. Der er ikke behov for en tredjepart til overførsel, som en bank.",
	"common_what_is_bitcoin_content_5": "Bitcoin gør det muligt for enhver at opbevare sin formue sikkert uden at bekymre sig om, at regeringen stjæler den eller inflaterer værdien væk gennem pengetrykning.",
	"common_what_is_bitcoin_content_6": "Regeringer overalt kan trykke flere papirpenge, men ingen kan trykke flere bitcoin.",
	"common_what_is_bitcoin_content_7": "Du kan nemt selvopbevare din Bitcoin for at tage fuld kontrol over den og give dig fuld adgang til kraften i Bitcoin.",
	"common_what_is_bitcoin_content_8": "Hvis du kan downloade en app, kan du selvopbevare Bitcoin og opbevare din formue uden at stole på nogen andre.",
	"common_what_is_bitcoin_content_9": "Bitcoin er bedre penge.",
	"common_bitcoin_volatile": "JEG HAR HØRT, AT BITCOIN ER VOLATIL. ER DET SIKKERT?",
	"common_bitcoin_volatile_content_1": "På kort sigt har vekselkursen for Bitcoin tendens til at svinge. Dette kaldes volatilitet.",
	"common_bitcoin_volatile_content_2": "Men den volatilitet, du ser på daglig basis, «forsvinder» på lang sigt.",
	"common_bitcoin_volatile_content_3": "Bitcoin bliver fortsat mindre og mindre volatil over tid. Efterhånden som flere mennesker bruger Bitcoin som en langsigtet opsparingskonto, stabiliseres værdien mere.",
	"common_bitcoin_volatile_content_4": "Mange mennesker vælger at opbevare værdi i Bitcoin i mange år som en sikker måde at minimere risikoen for volatilitet og beskytte deres købekraft over tid.",
	"common_bitcoin_volatile_content_5": "I nogle lande, såsom Venezuela, Sudan, Libanon, Syrien, Argentina, Tyrkiet, Brasilien og mange andre, inflateres værdien af den lokale valuta væk så hurtigt, at Bitcoin ses som den mere stabile måde at spare penge på.",
	"common_bitcoin_afford": "JEG HAR IKKE RÅD TIL EN HEL BITCOIN",
	"common_bitcoin_afford_content_1": "En dollar består af 100 cent. En bitcoin består af 100.000.000 (100 millioner) sats.",
	"common_bitcoin_afford_content_2": "Du behøver ikke eje en hel bitcoin. De fleste ejer bare sats. Sats er brøkdele af en bitcoin. For eksempel, hvis 1 hel bitcoin er $100.000, så køber $1 dig 1.000 sats!",
	"common_bitcoin_hacked": "ER BITCOIN NOGENSINDE BLEVET HACKET?",
	"common_bitcoin_hacked_content_1": "Du har måske hørt om et «Bitcoin-hack» online eller i nyhederne. De fleste læser disse artikler og tror, at Bitcoin-netværket er blevet hacket. Bitcoin-netværket er dog aldrig blevet hacket.",
	"common_bitcoin_hacked_content_2": "Hvad er Bitcoin-netværket? Tænk på Bitcoin-netværket som jernbaneskinner. Togene, der kører på Bitcoin-netværkets jernbaneskinner, er Bitcoin-transaktioner.",
	"common_bitcoin_hacked_content_3": "Når du læser om et Bitcoin-hack i nyhederne, læser du om en forvalter (som FTX), der er blevet hacket eller gået konkurs.",
	"common_bitcoin_hacked_content_4": "Forvaltere er virksomheder, der opbevarer din bitcoin for dig. Men det medfører en risiko: at miste din bitcoin, når virksomheden misforvalter den, stjæler den eller går konkurs.",
	"common_bitcoin_hacked_content_5": "Dette skete senest med FTX.",
	"common_bitcoin_hacked_content_6": "Alle, der stolede på FTX med deres bitcoin, mistede deres bitcoin. Alle, der opbevarede deres bitcoin i selvopbevaring, var fuldstændigt upåvirkede af FTX. Det er kraften i bitcoin i selvopbevaring: ægte kontrol over dine penge.",
	"common_bitcoin_hacked_content_7": "I stedet for at lade din bitcoin ligge på en børs eller i en wrapper som en ETF, opbevar den i din egen wallet for alle frihedsfordelene.",
	"common_bitcoin_hacked_content_8": "Når du selvopbevarer din bitcoin, er dine penge beskyttet af Bitcoin-netværket. Det er det mest sikre finansielle netværk i verden.",
	"common_bitcoin_hacked_content_9": "I selvopbevaring kan Sam fra FTX ikke stjæle din bitcoin fra dig.",
	"common_bitcoin_hacked_content_10": "Regeringen kan ikke trykke flere bitcoin og forårsage inflation.",
	"common_bitcoin_hacked_content_11": "Bitcoin i selvopbevaring er dine penge, takket være kraften i Bitcoin-netværket.",
	"common_bitcoin_energy": "HVORFOR BRUGER BITCOIN ENERGI?",
	"common_bitcoin_energy_content_1": "Bitcoin bruger energi til at sikre netværket og beskytte dine penge.",
	"common_bitcoin_energy_content_2": "Bitcoin bruger en betydelig mængde energi, og dette er en god ting af mange grunde.",
	"common_bitcoin_energy_list_1": "Bitcoin har ingen bankkriser.",
	"common_bitcoin_energy_list_2": "Bitcoin hjælper med at stabilisere elnet med bitcoin-mining.",
	"common_bitcoin_energy_list_3": "Bitcoin reducerer udledninger fra olieboring.",
	"common_bitcoin_energy_list_4": "Bitcoin bruger mindre energi, end amerikanere bruger på julebelysning hvert år.",
	"common_bitcoin_energy_list_5": "Bitcoin er den grønneste industri på jorden!",
	"common_cic_intro_1": "Mange kender til renters rente, men få kender til sammensat inflation.",
	"common_cic_intro_2": "Med vores beregner for sammensat inflation kan du nemt beregne, hvor meget din løn skal stige for at opretholde din købekraft over tid.",
	"common_cic_intro_3": "Indtast blot din nuværende løn, inflationsrate og antal år, du vil beregne for, og vores beregner vil vise dig, hvad din løn skal være for at følge med inflationen.",
	"common_current_salary": "nuværende løn",
	"common_inflation_rate": "inflationsrate",
	"common_year": "år",
	"common_years": "år",
	"common_result_starting_message": "Udfyld formularen ovenfor og klik beregn.",
	"common_error_message": "Fejl: Udfyld venligst alle 3 felter.",
	"common_result_message_1": "Med en inflationsrate på",
	"common_result_message_2": "skal din",
	"common_result_message_3": "løn stige til",
	"common_result_message_in": "på",
	"common_result_message_4": "for at opretholde din købekraft.",
	"common_calculate_button_text": "BEREGN",
	"common_learn_more": "LÆR MERE",
	"common_success": "SUCCES!",
	"common_choose_your_country": "Vælg dit land",
	"common_country_usa": "USA",
	"common_country_canada": "Canada",
	"common_submit": "INDSEND",
	"common_language_afrikaans": "AFRIKAANS",
	"common_language_arabic": "ARABISK",
	"common_language_basque": "BASKISK",
	"common_language_bulgarian": "BULGARSK",
	"common_language_catalan": "CATALANSK",
	"common_language_chinese": "KINESISK",
	"common_language_croatian": "KROATISK",
	"common_language_czech": "TJEKKISK",
	"common_language_danish": "DANSK",
	"common_language_dutch": "HOLLANDSK",
	"common_language_english": "ENGELSK",
	"common_language_estonian": "ESTISK",
	"common_language_filipino": "FILIPPINSK",
	"common_language_finnish": "FINSK",
	"common_language_french": "FRANSK",
	"common_language_german": "TYSK",
	"common_language_greek": "GRÆSK",
	"common_language_hausa": "HAUSA",
	"common_language_hebrew": "HEBRAISK",
	"common_language_hindi": "HINDI",
	"common_language_hungarian": "UNGARSK",
	"common_language_indonesian": "INDONESISK",
	"common_language_irish": "IRSK",
	"common_language_italian": "ITALIENSK",
	"common_language_japanese": "JAPANSK",
	"common_language_korean": "KOREANSK",
	"common_language_malay": "MALAJISK",
	"common_language_norwegian": "NORSK",
	"common_language_persian": "PERSISK",
	"common_language_polish": "POLSK",
	"common_language_portuguese": "PORTUGISISK",
	"common_language_russian": "RUSSISK",
	"common_language_sinhala": "SINGALESISK",
	"common_language_slovak": "SLOVAKISK",
	"common_language_slovenian": "SLOVENSK",
	"common_language_spanish": "SPANSK",
	"common_language_swahili": "SWAHILI",
	"common_language_swedish": "SVENSK",
	"common_language_thai": "THAI",
	"common_language_turkish": "TYRKISK",
	"common_language_urdu": "URDU",
	"common_language_vietnamese": "VIETNAMESISK",
	"common_language_yoruba": "YORUBA",
	"common_stickers_bulk_mess": "Vil du ikke rode med filerne selv?",
	"common_stickers_bulk_want": "Vil du have mere end bare et par klistermærker?",
	"common_stickers_bulk_store": "Bestil klistermærker i stor mængde fra samme trykkeri, vi bruger.",
	"common_stickers_bulk_cheaper": "Jo flere klistermærker du køber, jo billigere er de pr. klistermærke.",
	"common_stickers_print_instructions_1": "Du kan deltage ved at printe dine egne klistermærker, uanset hvor du bor! Klik på dit sprog nedenfor for at downloade klistermærkefiler og instruktioner.",
	"common_stickers_print_instructions_2": "Bemærk: ikke alle klistermærker er tilgængelige på alle sprog.",
	"common_stickers_request_language_1": "Kan du ikke se dit sprog?",
	"common_stickers_request_language_2": "Udfyld formularen nedenfor for at anmode om klistermærkefiler på dit lokale sprog.",
	"common_stickers_dimensions": "Dimensioner:",
	"common_stickers_type": "Type:",
	"common_stickers_material": "Materiale:",
	"common_stickers_where_to_print": "Hvor du kan printe:",
	"common_stickers_type_die_cut": "udstanset klistermærke",
	"common_stickers_material_vinyl": "vinylklistermærker til udendørs brug",
	"common_stickers_printer": "Vi bruger StickerMule.com, men du kan bruge enhver klistermærkevirksomhed.",
	"common_stickers_dimensions_danger": "11,4544 cm x 8,382 cm",
	"common_stickers_dimensions_warning": "10,414 cm x 9,2202 cm",
	"common_stickers_dimensions_caution": "12,0142 cm x 7,9502 cm",
	"common_stickers_dimensions_fix": "11,3792 cm x 6,8072 cm",
	"common_stickers_dimensions_study": "14,605 cm x 5,1308 cm",
	"common_stickers_dimensions_bdhi": "21,59 cm x 4,6482 cm",
	"common_stickers_dimensions_cure_v2": "6,35 cm x 12,7 cm",
	"common_stickers_dimensions_got_inflation": "7,9248 cm x 14,605 cm",
	"common_stickers_dimensions_what_if": "21,7932 cm x 7,62 cm",
	"common_stickers_dimensions_bitcoin_accepted_here": "20,995 cm x 6,35 cm",
	"common_nostr_join": "TILMELD DIG NOSTR NU",
	"common_nostr_protocol_header": "Protokol, ikke platform",
	"common_nostr_protocol_c1": "Nostr er en ny protokol, der giver dig mulighed for at kommunikere online uden frygt for censur, deplatforming eller nedgradering",
	"common_nostr_protocol_c2": "Platforme som Twitter og Facebook kontrolleres af en enkelt virksomhed, men ingen kontrollerer Nostr-protokollen.",
	"common_nostr_freedom_header": "Frihed til at flytte",
	"common_nostr_freedom_c1": "Nostr ligner e-mail. Ingen kontrollerer e-mailprotokollen, og enhver kan bygge en klient (som Gmail, Hotmail osv.) oven på den.",
	"common_nostr_freedom_c2": "Ingen kontrollerer Nostr-protokollen, og enhver kan bygge en klient (som Damus, Amethyst osv.) oven på den.",
	"common_nostr_freedom_c3": "Hvis du ikke kan lide, hvordan en bestemt klient fungerer, kan du problemfrit flytte din Nostr-konto til en anden klient uden at miste dine følgere eller dit indhold.",
	"common_nostr_bitcoin_header": "Bitcoin er indbygget",
	"common_nostr_bitcoin_c1": "Bitcoin er indbygget i Nostr-protokollen. Hvis du ser indhold, du kan lide, kan du nemt zappe bitcoin til nogen som tak!",
	"common_nostr_bitcoin_c2": "På centraliserede platforme som Twitter og Facebook tjener den centraliserede virksomhed penge på dit indhold. Men på åbne protokoller som Nostr tjener du penge på dit indhold.",
	"common_nostr_download_client": "DOWNLOAD EN GRATIS KLIENT FOR AT TILMELDE DIG NOSTR",
	"common_nostr_iphone_clients": "iPhone-klienter",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "iPhone-app",
	"common_nostr_first_client": "Anbefalet første klient",
	"common_nostr_wallet_built_in": "Bitcoin zap-wallet indbygget",
	"common_nostr_download_now": "DOWNLOAD NU",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "Velkendt interface",
	"common_nostr_separate_wallet": "Kræver separat bitcoin-wallet",
	"common_nostr_android_clients": "Android-klienter",
	"common_nostr_android_app": "Android-app",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "Mange funktioner",
	"common_nostr_browser_clients": "Browserklienter",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "Webklient",
	"common_nostr_simple": "Supersimpelt",
	"common_nostr_test": "Nem måde at prøve Nostr med en testkonto",
	"common_nostr_view_client": "VIS KLIENT",
	"common_kit_printer": "Vi anbefaler VistaPrint.com til at printe dine egne Bitcoin-virksomhedspakkebrochurer. Du kan dog bruge ethvert trykkeri, så længe de kan lave dobbeltsidet print.",
	"common_kit_link_to_print": "Link til print:",
	"common_kit_fold": "Fold:",
	"common_kit_fold_trifold": "Trefold",
	"common_kit_unfolded_size": "Udfoldet størrelse:",
	"common_kit_unfolded_size_bbk": "Letter-størrelse (8,5 in x 11 in)",
	"common_kit_paper_thickness": "Papirtykkelse:",
	"common_kit_paper_thickness_standard": "Standard",
	"common_kit_paper_stock": "Papirkvalitet:",
	"common_kit_paper_stock_glossy": "Blankt",
	"common_kit_exterior_print_file": "Udvendig printfil:",
	"common_kit_interior_print_file": "Indvendig printfil:",
	"common_kit_cta_header": "Få en lokal virksomhed til at acceptere Bitcoin",
	"common_biz_learn": "Lær hvorfor Bitcoin er godt for virksomheder",
	"common_biz_wallets": "Få en Bitcoin-wallet til at acceptere Bitcoin-betalinger",
	"common_biz_maps": "Bliv opført på kort over Bitcoin-forhandlere",
	"common_biz_stickers": "Gratis klistermærker «Bitcoin accepteres her»",
	"common_biz_rewards": "Bitcoin-belønninger",
	"common_biz_accounting": "Guide til Bitcoin-regnskab",
	"common_biz_faq": "Ofte stillede spørgsmål",
	"common_biz_kit": "Print din egen Bitcoin-virksomhedspakke",
	"common_biz_accept_bitcoin_payments": "ACCEPTER BITCOIN-BETALINGER",
	"common_biz_ready": "KLAR TIL AT ACCEPTERE BITCOIN I DIN VIRKSOMHED?",
	"common_biz_more": "FLERE VIRKSOMHEDSRESSOURCER",
	"common_self_custody": "SELVOPBEVARING",
	"common_not_your_keys": "IKKE DINE NØGLER",
	"common_cold_wallet": "KOLD WALLET",
	"common_hot_wallet": "VARM WALLET",
	"common_sticker_files_mission_1": "Vores mission er at hjælpe dig med at orange-pille flere mennesker ved at sætte Bitcoin-klistermærker op offentligt. Alle vores klistermærker har QR-koder, der linker til uddannelsessider om",
	"common_sticker_files_mission_2": "Bitcoin",
	"common_sticker_files_mission_3": "inflation",
	"common_sticker_files_mission_4": "Hvis du bor i USA eller Canada, kan du",
	"common_sticker_files_mission_5": "anmode om en gratis pakke med engelske klistermærker",
	"common_published_by": "Udgivet af",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "Bitcoin-uddannelse siden 2022",
	"common_publisher_open_source": "Open source-projekt",
	"common_reviewed_accuracy": "✓ Gennemgået for nøjagtighed: 2026",
	"common_footer_tagline": "Accelererer bitcoin-adoption gennem uddannelse.",
	"common_footer_contribute": "Bidrag",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "Kilder"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! Created common.json.');
