/**
 * Creates Hungarian (hu) index.json translation file
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'hu';
const today = '2026-04-11';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"bitcoin_builds_a_better_world": "A Bitcoin egy jobb vil\u00E1got \u00E9p\u00EDt.",
	"home_description": "A Bitcoin jobb p\u00E9nz, amely egy jobb vil\u00E1got \u00E9p\u00EDt. A Bitcoin v\u00E9dte az emberi jogokat, megmentette az embereket a magas infl\u00E1ci\u00F3t\u00F3l, t\u00E1mogatta a helyi gazd\u00E1kat, cs\u00F6kkentette az olajf\u00FAr\u00E1sb\u00F3l sz\u00E1rmaz\u00F3 kibocs\u00E1t\u00E1sokat, \u00E9s m\u00E9g sok m\u00E1st tett.",
	"home_intro": "A Bitcoin jobb p\u00E9nz, amely egy jobb vil\u00E1got \u00E9p\u00EDt. Koppints egy kateg\u00F3ri\u00E1ra lent, hogy megtudd, hogyan teszi a Bitcoin jobb\u00E1, vagy egyszer\u0171en g\u00F6rgess, hogy felfedezd.",
	"home_btn_money": "JOBB P\u00C9NZ",
	"home_btn_salary": "A FIZET\u00C9SED",
	"home_btn_freedom": "SZABADS\u00C1G",
	"home_btn_human_rights": "EMBERI JOGOK",
	"home_btn_equality": "EGYENL\u0150S\u00C9G",
	"home_btn_property_rights": "TULAJDONJOGOK",
	"home_btn_housing": "LAK\u00C1S",
	"home_btn_business": "\u00DCZLET",
	"home_btn_crowdfunding": "K\u00D6Z\u00D6SS\u00C9GI FINANSZ\u00CDROZ\u00C1S",
	"home_btn_energy": "ENERGIA",
	"home_btn_environment": "K\u00D6RNYEZET",
	"home_btn_food": "\u00C9LELEM",
	"home_btn_art": "M\u0170V\u00C9SZET",
	"home_btn_politics": "POLITIKA",
	"home_btn_war": "H\u00C1BOR\u00DA",
	"home_btn_coding": "K\u00D3DOL\u00C1S",
	"home_btn_networks": "H\u00C1L\u00D3ZATOK",
	"home_btn_payments": "FIZET\u00C9SEK",
	"home_btn_self_custody": "\u00D6N\u00C1LL\u00D3 MEG\u0150RZ\u00C9S",
	"home_btn_you": "TE",
	"home_section_bitcoin_is": "A BITCOIN",
	"home_section_bitcoin_and": "BITCOIN \u00C9S",
	"home_link_type_website": "WEBOLDAL",
	"home_link_type_video": "VIDE\u00D3",
	"home_link_type_article": "CIKK",
	"home_link_type_podcast": "PODCAST",
	"home_link_type_business_kit": "\u00DCZLETI CSOMAG",
	"home_link_type_data": "ADATOK",
	"home_link_type_research": "KUTAT\u00C1S",
	"home_link_type_story": "T\u00D6RT\u00C9NET",
	"home_link_type_book_excerpt": "K\u00D6NYVRÉSZLET",
	"home_link_type_street_art": "UTCAI M\u0170V\u00C9SZET",
	"home_link_type_outreach": "KAPCSOLATFELV\u00C9TEL",
	"home_link_type_campaign": "KAMP\u00C1NY",
	"home_link_type_software": "SZOFTVER",
	"home_link_type_hardware": "HARDVER",
	"home_link_type_guide": "\u00DATMUTAT\u00D3",
	"home_link_type_email": "E-MAIL",
	"home_link_title_inflation": "A Bitcoinnak nincs infl\u00E1ci\u00F3ja",
	"home_link_title_bank_runs": "A Bitcoinnak nincsenek bankp\u00E1nikjai",
	"home_link_title_gold": "Bitcoin vs arany",
	"home_link_title_crypto": "Bitcoin vs kripto",
	"home_link_title_cash": "Bitcoin vs k\u00E9szp\u00E9nz",
	"home_link_title_bonds": "Bitcoin vs k\u00F6tv\u00E9nyek",
	"home_link_title_cbdc": "Bitcoin vs CBDC-k",
	"home_link_title_your_salary_1": "Tudd meg, mennyivel kell emelkednie a fizet\u00E9sednek, hogy l\u00E9p\u00E9st tartson az infl\u00E1ci\u00F3val.",
	"home_link_title_freedom_1": "Mi\u00E9rt fontos a Bitcoin a szabads\u00E1g\u00E9rt",
	"home_link_title_freedom_2": "A Bitcoin szabads\u00E1got k\u00EDn\u00E1l a politikai elnyom\u00E1s el\u0151l",
	"home_link_title_human_rights_1": "Hogyan \u00E9rv\u00E9nyes\u00EDti a Bitcoin az emberi jogokat",
	"home_link_title_human_rights_2": "Afrika csendes Bitcoin forradalma",
	"home_link_title_human_rights_3": "A Bitcoin v\u00E9di az emberi jogokat a vil\u00E1g minden t\u00E1j\u00E1n",
	"home_link_title_equality_1": "A Bitcoin rem\u00E9nyt \u00E9s lehet\u0151s\u00E9get hoz a d\u00E9l-afrikai embereknek",
	"home_link_title_equality_2": "Hogyan lehet a Bitcoin j\u00E1t\u00E9kmegv\u00E1ltoztat\u00F3 a fekete amerikaiak sz\u00E1m\u00E1ra",
	"home_link_title_property_rights_1": "A Bitcoin a tulajdon t\u00F6k\u00E9letes form\u00E1ja",
	"home_link_title_property_rights_2": "Bitcoin vs ingatlan",
	"home_link_title_housing_1": "Hogyan teszi a Bitcoin \u00FAjra megfizethet\u0151v\u00E9 a lak\u00E1st",
	"home_link_title_business_3": "Bitcoin vs r\u00E9szv\u00E9nyek",
	"home_link_title_business_1": "Tudd meg, mi\u00E9rt j\u00F3 a Bitcoin az \u00FCzletnek",
	"home_link_title_business_2": "Seg\u00EDts egy helyi v\u00E1llalkoz\u00E1snak elfogadni a Bitcoint",
	"home_link_title_crowdfunding_1": "Hogyan mozd\u00EDtotta el\u0151 a Bitcoin a legnagyobb nig\u00E9riai tiltakoz\u00E1sokat egy gener\u00E1ci\u00F3ban",
	"home_link_title_crowdfunding_2": "A kanadai kamionosok tiltakoz\u00E1sa Bitcoinban gy\u0171jt p\u00E9nzt, miut\u00E1n a GoFundMe blokkolta az adom\u00E1nyokat",
	"home_link_title_crowdfunding_3": "Geyser = K\u00F6z\u00F6ss\u00E9gi finansz\u00EDroz\u00E1s Bitcoinnal",
	"home_link_title_energy_1": "Hogyan stabiliz\u00E1lja a Bitcoin a texasi energiah\u00E1l\u00F3zatot",
	"home_link_title_energy_2": "Mi\u00E9rt haszn\u00E1l a Bitcoin energi\u00E1t?",
	"home_link_title_energy_3": "A Bitcoin energiafelhaszn\u00E1l\u00E1sa nem probl\u00E9ma. \u00CDme, mi\u00E9rt.",
	"home_link_title_energy_4": "A bitcoin b\u00E1ny\u00E1szat stabiliz\u00E1lja az energiah\u00E1l\u00F3zatokat a kereslet-v\u00E1laszon kereszt\u00FCl",
	"home_link_title_energy_5": "A bitcoin b\u00E1ny\u00E1szok v\u00EDzer\u0151t hoznak az afrikai vid\u00E9ki k\u00F6z\u00F6ss\u00E9geknek",
	"home_link_title_energy_6": "Hogyan \u00F6szt\u00F6nzi a Bitcoin a meg\u00FAjul\u00F3 energi\u00E1t",
	"home_link_title_environment_1": "Hogyan cs\u00F6kkenti a bitcoin b\u00E1ny\u00E1szat a glob\u00E1lis met\u00E1nkibocs\u00E1t\u00E1st",
	"home_link_title_environment_2": "Hogyan mentett meg a bitcoin b\u00E1ny\u00E1szat egy nemzeti parkot",
	"home_link_title_environment_3": "A Bitcoin a F\u00F6ld legz\u00F6ldebb ipara!",
	"home_link_title_environment_4": "A bitcoin b\u00E1ny\u00E1szat megakad\u00E1lyozza, hogy az el\u00E9getett f\u00F6ldg\u00E1z szennyezze a l\u00E9gk\u00F6rt",
	"home_link_title_food_1": "Hogyan hat az infl\u00E1ci\u00F3 az \u00E9lelmiszer\u00E1rakra",
	"home_link_title_food_2": "Hogyan \u00E1rt a fiat p\u00E9nz az \u00E9lelemnek, a gazdas\u00E1goknak \u00E9s a F\u00F6ld talaj\u00E1nak",
	"home_link_title_fine_art": "Bitcoin vs k\u00E9pz\u0151m\u0171v\u00E9szet",
	"home_link_title_art_1": "Csatlakozz a Bitcoin matrica kezdem\u00E9nyez\u00E9s\u00FCnkh\u00F6z",
	"home_link_title_art_2": "K\u00FCldj Bitcoin k\u00E9peslapot valakinek, akit ismersz",
	"home_link_title_art_3": "Nyomtass \u00E9s ragassz ki Bitcoin sz\u00F3r\u00F3lapokat",
	"home_link_title_politics_1": "A Bitcoin politikai paradoxon",
	"home_link_title_politics_2": "Szavazhatsz a jobb p\u00E9nzre",
	"home_link_title_war_1": "Hogyan vethet v\u00E9get a Bitcoin a v\u00E9g n\u00E9lk\u00FCli h\u00E1bor\u00FAnak",
	"home_link_title_war_2": "Bitcoin \u00E9s veter\u00E1nok: Term\u00E9szetes \u00F6sszhang",
	"home_link_title_war_3": "Hogyan seg\u00EDti a Bitcoin a civileket menek\u00FClni a szud\u00E1ni h\u00E1bor\u00FAb\u00F3l",
	"home_link_title_coding_1": "Interakt\u00EDv oktat\u00F3anyag a Bitcoin technikai oldal\u00E1r\u00F3l",
	"home_link_title_coding_2": "bitcoinSwitch: b\u00E1rmely eszk\u00F6z \u00E1talak\u00EDt\u00E1sa Bitcoin elfogad\u00E1sra",
	"home_link_title_coding_3": "K\u00F3dolj v\u00E9gig a Bitcoin rejtelmein",
	"home_link_title_networks_1": "\u00C9l\u0151 n\u00E9zet a Bitcoin h\u00E1l\u00F3zatr\u00F3l",
	"home_link_title_networks_2": "Bitcoin vs bankok",
	"home_link_title_payments_1": "Bitcoin vs Visa",
	"home_link_title_payments_2": "Pillant\u00E1s a Lightning h\u00E1l\u00F3zatra (azonnali Bitcoin fizet\u00E9sek)",
	"home_link_title_payments_3": "El Salvador Bitcoin t\u00E1rc\u00E1ja \u00E9vente 400 milli\u00F3 doll\u00E1rt takar\u00EDthat meg a salvadoriaknak \u00E1tutal\u00E1si d\u00EDjakb\u00F3l",
	"home_link_title_payments_4": "Szerezd meg a Lightning c\u00EDmedet azonnali Bitcoin fizet\u00E9sek fogad\u00E1s\u00E1hoz",
	"home_link_title_self_custody_1": "Hogyan t\u00E1rold biztons\u00E1gosan a Bitcoinodat",
	"home_link_title_self_custody_2": "6 ok, ami\u00E9rt ki kell vonnod a Bitcoinodat a t\u0151zsd\u00E9kr\u0151l",
	"home_link_title_self_custody_3": "Arany, Bitcoin \u00E9s \u00F6n\u00E1ll\u00F3 meg\u0151rz\u00E9s",
	"home_link_title_get_started_1": "Ismerd meg a Bitcoin alapjait",
	"home_link_title_get_started_2": "Szerezd meg az els\u0151 Bitcoin t\u00E1rc\u00E1dat",
	"home_link_title_get_started_3": "Hogyan v\u00E1s\u00E1rolj Bitcoint",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Kamatos infl\u00E1ci\u00F3 kalkul\u00E1tor",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! Created index.json.');
