/**
 * Creates Russian (ru) common.json translation file (~180+ keys).
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ru';
const today = '2026-04-04';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"common_footer_mission_1": "Миссия bitcoin.rocks — ускорить принятие биткоина через образование.",
	"common_footer_mission_2": "Узнайте, как внести вклад в этот проект с открытым исходным кодом.",
	"common_footer_follow_first_half": "Подпишитесь на нас в Nostr, найдя",
	"common_footer_follow_second_half": "в любом клиенте Nostr.",
	"common_footer_what_is_nostr": "Что такое Nostr?",
	"common_footer_about": "О нас",
	"common_footer_email_us": "Напишите нам:",
	"common_cta_section_get_started": "НАЧНИТЕ",
	"common_cta_section_with_bitcoin": "С БИТКОИНОМ",
	"common_cta_section_title_1": "Изучите основы Биткоина",
	"common_cta_section_title_1_alt": "Узнайте больше о Биткоине",
	"common_cta_section_title_2": "Получите свой первый биткоин-кошелёк",
	"common_cta_section_title_3": "Как купить Биткоин",
	"common_cta_link_type_email": "ЭЛ. ПОЧТА",
	"common_cta_link_type_guide": "РУКОВОДСТВО",
	"common_cta_link_type_website": "САЙТ",
	"common_cta_author_21_days_of_bitcoin": "21 день Биткоина",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "ЧТО ТАКОЕ БИТКОИН?",
	"common_what_is_bitcoin_content_1": "Биткоин — это две вещи: цифровые деньги и платёжная сеть. Вы можете отправлять Биткоин (цифровые деньги) напрямую другим людям через сеть Биткоина (платёжную сеть).",
	"common_what_is_bitcoin_content_2": "Биткоин — это принципиально новый способ хранения и передачи стоимости. В отличие от обычных финансовых сетей, сеть Биткоина способна работать без центральных властей или доверенных администраторов. Это делает Биткоин первыми в истории открытыми и трансграничными деньгами.",
	"common_what_is_bitcoin_content_3": "Биткоин — это цифровые деньги, дающие вам полный контроль над вашим богатством. Впервые в истории человечества каждый может владеть активом, который действительно дефицитен, не требует разрешения для использования и не может быть конфискован при правильном хранении.",
	"common_what_is_bitcoin_content_4": "Биткоин можно отправить куда угодно в мире быстро и дёшево. Ему не нужен сторонний передатчик, такой как банк.",
	"common_what_is_bitcoin_content_5": "Биткоин позволяет каждому хранить своё богатство безопасно и надёжно, не беспокоясь о том, что правительство украдёт его или обесценит через печатание денег.",
	"common_what_is_bitcoin_content_6": "Правительства повсюду могут печатать больше бумажных денег, но никто не может напечатать больше биткоинов.",
	"common_what_is_bitcoin_content_7": "Вы можете легко взять биткоин на самостоятельное хранение, чтобы получить полный контроль над ним, открывая все возможности Биткоина.",
	"common_what_is_bitcoin_content_8": "Если вы можете скачать приложение, вы можете хранить Биткоин самостоятельно и сберегать своё богатство, не полагаясь ни на кого.",
	"common_what_is_bitcoin_content_9": "Биткоин — это лучшие деньги.",
	"common_bitcoin_volatile": "Я СЛЫШАЛ, ЧТО БИТКОИН ВОЛАТИЛЕН. ЭТО БЕЗОПАСНО?",
	"common_bitcoin_volatile_content_1": "В краткосрочной перспективе обменный курс Биткоина склонен к колебаниям. Это называется волатильностью.",
	"common_bitcoin_volatile_content_2": "Но волатильность, которую вы видите изо дня в день, «исчезает» в долгосрочной перспективе.",
	"common_bitcoin_volatile_content_3": "Биткоин продолжает становиться всё менее и менее волатильным со временем. Чем больше людей используют Биткоин как долгосрочный сберегательный счёт, тем более стабильной становится его стоимость.",
	"common_bitcoin_volatile_content_4": "Многие люди предпочитают хранить стоимость в Биткоине в течение многих лет как безопасный способ минимизировать риск волатильности и защитить свою покупательную способность со временем.",
	"common_bitcoin_volatile_content_5": "В некоторых странах, таких как Венесуэла, Судан, Ливан, Сирия, Аргентина, Турция, Бразилия и многих других, стоимость местной валюты обесценивается настолько быстро, что Биткоин рассматривается как более стабильный способ хранения денег.",
	"common_bitcoin_afford": "Я НЕ МОГУ СЕБЕ ПОЗВОЛИТЬ ЦЕЛЫЙ БИТКОИН",
	"common_bitcoin_afford_content_1": "Доллар состоит из 100 центов. Биткоин состоит из 100 000 000 (100 миллионов) сатоши.",
	"common_bitcoin_afford_content_2": "Вам не нужно владеть целым биткоином. Большинство людей просто владеют сатоши. Сатоши — это доли биткоина. Например, если 1 целый биткоин стоит $100 000, то за $1 вы получите 1000 сатоши!",
	"common_bitcoin_hacked": "БИТКОИН КОГДА-НИБУДЬ ВЗЛАМЫВАЛИ?",
	"common_bitcoin_hacked_content_1": "Возможно, вы слышали о «взломе Биткоина» в интернете или в новостях. Большинство людей, читая такие статьи, считают, что была взломана сеть Биткоина. Однако сеть Биткоина никогда не была взломана.",
	"common_bitcoin_hacked_content_2": "Что такое сеть Биткоина? Представьте себе сеть Биткоина как железнодорожные пути. Поезда, едущие по этим путям, — это транзакции Биткоина.",
	"common_bitcoin_hacked_content_3": "Когда вы читаете о взломе Биткоина в новостях, вы читаете о кастодиане (например, FTX), который был взломан или обанкротился.",
	"common_bitcoin_hacked_content_4": "Кастодианы — это компании, которые хранят ваш биткоин за вас. Однако это сопряжено с риском: потеря вашего биткоина, когда компания неправильно им управляет, крадёт его или прекращает деятельность.",
	"common_bitcoin_hacked_content_5": "Это произошло совсем недавно с FTX.",
	"common_bitcoin_hacked_content_6": "Все, кто доверил FTX свой биткоин, потеряли его. Все, кто хранил биткоин самостоятельно, совершенно не пострадали от FTX. В этом сила биткоина на самостоятельном хранении: настоящий контроль над своими деньгами.",
	"common_bitcoin_hacked_content_7": "Вместо того чтобы оставлять биткоин на бирже или в обёртке вроде ETF, храните его в собственном кошельке для всех преимуществ свободы.",
	"common_bitcoin_hacked_content_8": "Когда вы храните биткоин самостоятельно, ваши деньги защищены сетью Биткоина. Это самая безопасная финансовая сеть в мире.",
	"common_bitcoin_hacked_content_9": "На самостоятельном хранении Сэм из FTX не может украсть ваш биткоин.",
	"common_bitcoin_hacked_content_10": "Правительство не может напечатать больше биткоинов и вызвать инфляцию.",
	"common_bitcoin_hacked_content_11": "Биткоин на самостоятельном хранении — это ваши деньги, благодаря силе сети Биткоина.",
	"common_bitcoin_energy": "ПОЧЕМУ БИТКОИН ИСПОЛЬЗУЕТ ЭНЕРГИЮ?",
	"common_bitcoin_energy_content_1": "Биткоин использует энергию для обеспечения безопасности сети и защиты ваших денег.",
	"common_bitcoin_energy_content_2": "Биткоин использует значительное количество энергии, и это прекрасно по многим причинам.",
	"common_bitcoin_energy_list_1": "В Биткоине нет банковских паник.",
	"common_bitcoin_energy_list_2": "Биткоин помогает стабилизировать энергосети с помощью майнинга биткоина.",
	"common_bitcoin_energy_list_3": "Биткоин сокращает выбросы при нефтедобыче.",
	"common_bitcoin_energy_list_4": "Биткоин использует меньше энергии, чем американцы тратят на рождественские гирлянды каждый год.",
	"common_bitcoin_energy_list_5": "Биткоин — самая экологичная индустрия на Земле!",
	"common_cic_intro_1": "Многие люди знают о сложном проценте, но немногие знают о сложной инфляции.",
	"common_cic_intro_2": "С помощью нашего калькулятора сложной инфляции вы можете легко рассчитать, насколько должна вырасти ваша зарплата, чтобы сохранить покупательную способность со временем.",
	"common_cic_intro_3": "Просто введите вашу текущую зарплату, уровень инфляции и количество лет, для которых вы хотите произвести расчёт, и наш калькулятор покажет вам, какой должна быть ваша зарплата, чтобы не отставать от инфляции.",
	"common_current_salary": "текущая зарплата",
	"common_inflation_rate": "уровень инфляции",
	"common_year": "год",
	"common_years": "лет",
	"common_result_starting_message": "Заполните форму выше и нажмите рассчитать.",
	"common_error_message": "Ошибка: пожалуйста, заполните все 3 поля формы.",
	"common_result_message_1": "При уровне инфляции",
	"common_result_message_2": "ваша",
	"common_result_message_3": "зарплата должна вырасти до",
	"common_result_message_in": "через",
	"common_result_message_4": "чтобы сохранить вашу покупательную способность.",
	"common_calculate_button_text": "РАССЧИТАТЬ",
	"common_learn_more": "УЗНАТЬ БОЛЬШЕ",
	"common_success": "УСПЕХ!",
	"common_choose_your_country": "Выберите свою страну",
	"common_country_usa": "США",
	"common_country_canada": "Канада",
	"common_submit": "ОТПРАВИТЬ",
	"common_language_afrikaans": "АФРИКААНС",
	"common_language_arabic": "АРАБСКИЙ",
	"common_language_basque": "БАСКСКИЙ",
	"common_language_bulgarian": "БОЛГАРСКИЙ",
	"common_language_catalan": "КАТАЛАНСКИЙ",
	"common_language_chinese": "КИТАЙСКИЙ",
	"common_language_croatian": "ХОРВАТСКИЙ",
	"common_language_czech": "ЧЕШСКИЙ",
	"common_language_danish": "ДАТСКИЙ",
	"common_language_dutch": "ГОЛЛАНДСКИЙ",
	"common_language_english": "АНГЛИЙСКИЙ",
	"common_language_estonian": "ЭСТОНСКИЙ",
	"common_language_filipino": "ФИЛИППИНСКИЙ",
	"common_language_finnish": "ФИНСКИЙ",
	"common_language_french": "ФРАНЦУЗСКИЙ",
	"common_language_german": "НЕМЕЦКИЙ",
	"common_language_greek": "ГРЕЧЕСКИЙ",
	"common_language_hausa": "ХАУСА",
	"common_language_hebrew": "ИВРИТ",
	"common_language_hindi": "ХИНДИ",
	"common_language_hungarian": "ВЕНГЕРСКИЙ",
	"common_language_indonesian": "ИНДОНЕЗИЙСКИЙ",
	"common_language_irish": "ИРЛАНДСКИЙ",
	"common_language_italian": "ИТАЛЬЯНСКИЙ",
	"common_language_japanese": "ЯПОНСКИЙ",
	"common_language_korean": "КОРЕЙСКИЙ",
	"common_language_malay": "МАЛАЙСКИЙ",
	"common_language_norwegian": "НОРВЕЖСКИЙ",
	"common_language_persian": "ПЕРСИДСКИЙ",
	"common_language_polish": "ПОЛЬСКИЙ",
	"common_language_portuguese": "ПОРТУГАЛЬСКИЙ",
	"common_language_russian": "РУССКИЙ",
	"common_language_sinhala": "СИНГАЛЬСКИЙ",
	"common_language_slovak": "СЛОВАЦКИЙ",
	"common_language_slovenian": "СЛОВЕНСКИЙ",
	"common_language_spanish": "ИСПАНСКИЙ",
	"common_language_swahili": "СУАХИЛИ",
	"common_language_swedish": "ШВЕДСКИЙ",
	"common_language_thai": "ТАЙСКИЙ",
	"common_language_turkish": "ТУРЕЦКИЙ",
	"common_language_urdu": "УРДУ",
	"common_language_vietnamese": "ВЬЕТНАМСКИЙ",
	"common_language_yoruba": "ЙОРУБА",
	"common_stickers_bulk_mess": "Не хотите возиться с файлами самостоятельно?",
	"common_stickers_bulk_want": "Хотите больше, чем несколько стикеров?",
	"common_stickers_bulk_store": "Закажите стикеры оптом у того же типографа, которого используем мы.",
	"common_stickers_bulk_cheaper": "Чем больше стикеров вы покупаете, тем дешевле они обходятся за штуку.",
	"common_stickers_print_instructions_1": "Вы можете участвовать, печатая свои собственные стикеры, независимо от того, где вы живёте! Нажмите на свой язык ниже, чтобы скачать файлы стикеров и инструкции.",
	"common_stickers_print_instructions_2": "Обратите внимание: не все стикеры доступны на всех языках.",
	"common_stickers_request_language_1": "Не видите свой язык?",
	"common_stickers_request_language_2": "Заполните форму ниже, чтобы запросить файлы стикеров на вашем языке.",
	"common_stickers_dimensions": "Размеры:",
	"common_stickers_type": "Тип:",
	"common_stickers_material": "Материал:",
	"common_stickers_where_to_print": "Где печатать:",
	"common_stickers_type_die_cut": "вырубной стикер",
	"common_stickers_material_vinyl": "виниловые стикеры для наружного использования",
	"common_stickers_printer": "Мы используем StickerMule.com, но вы можете использовать любую компанию по печати стикеров.",
	"common_stickers_dimensions_danger": "11,4544 см x 8,382 см (4,51 дюйма x 3,3 дюйма)",
	"common_stickers_dimensions_warning": "10,414 см x 9,2202 см (4,1 дюйма x 3,63 дюйма)",
	"common_stickers_dimensions_caution": "12,0142 см x 7,9502 см (4,73 дюйма x 3,13 дюйма)",
	"common_stickers_dimensions_fix": "11,3792 см x 6,8072 см (4,48 дюйма x 2,68 дюйма)",
	"common_stickers_dimensions_study": "14,605 см x 5,1308 см (5,75 дюйма x 2,02 дюйма)",
	"common_stickers_dimensions_bdhi": "21,59 см x 4,6482 см (8,5 дюйма x 1,83 дюйма)",
	"common_stickers_dimensions_cure_v2": "6,35 см x 12,7 см (2,5 дюйма x 5 дюймов)",
	"common_stickers_dimensions_got_inflation": "7,9248 см x 14,605 см (3,12 дюйма x 5,75 дюйма)",
	"common_stickers_dimensions_what_if": "21,7932 см x 7,62 см (8,58 дюйма x 3 дюйма)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20,995 см x 6,35 см (8,25 дюйма x 2,5 дюйма)",
	"common_nostr_join": "ПРИСОЕДИНИТЬСЯ К NOSTR",
	"common_nostr_protocol_header": "Протокол, а не платформа",
	"common_nostr_protocol_c1": "Nostr — это новый протокол, позволяющий общаться онлайн без страха цензуры, деплатформинга или понижения видимости",
	"common_nostr_protocol_c2": "Платформы вроде Twitter и Facebook контролируются одной компанией, но протокол Nostr никто не контролирует.",
	"common_nostr_freedom_header": "Свобода перемещения",
	"common_nostr_freedom_c1": "Nostr похож на электронную почту. Никто не контролирует протокол электронной почты, и любой может создать клиент (как Gmail, Hotmail и т.д.) на его основе.",
	"common_nostr_freedom_c2": "Никто не контролирует протокол Nostr, и любой может создать клиент (как Damus, Amethyst и т.д.) на его основе.",
	"common_nostr_freedom_c3": "Если вам не нравится, как работает определённый клиент, вы можете беспрепятственно перенести свой аккаунт Nostr на другой клиент, не теряя подписчиков или контента.",
	"common_nostr_bitcoin_header": "Биткоин встроен",
	"common_nostr_bitcoin_c1": "Биткоин изначально встроен в протокол Nostr. Если вы видите контент, который вам нравится, вы можете легко отправить биткоин кому-то в качестве благодарности!",
	"common_nostr_bitcoin_c2": "На централизованных платформах вроде Twitter и Facebook централизованная компания зарабатывает на вашем контенте. А на открытых протоколах вроде Nostr вы зарабатываете на своём контенте.",
	"common_nostr_download_client": "СКАЧАЙТЕ БЕСПЛАТНЫЙ КЛИЕНТ, ЧТОБЫ ПРИСОЕДИНИТЬСЯ К NOSTR",
	"common_nostr_iphone_clients": "Клиенты для iPhone",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "Приложение для iPhone",
	"common_nostr_first_client": "Рекомендуемый первый клиент",
	"common_nostr_wallet_built_in": "Встроенный кошелёк для зэпов Биткоина",
	"common_nostr_download_now": "СКАЧАТЬ СЕЙЧАС",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "Знакомый интерфейс",
	"common_nostr_separate_wallet": "Требуется отдельный биткоин-кошелёк",
	"common_nostr_android_clients": "Клиенты для Android",
	"common_nostr_android_app": "Приложение для Android",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "Много функций",
	"common_nostr_browser_clients": "Браузерные клиенты",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "Веб-клиент",
	"common_nostr_simple": "Очень простой",
	"common_nostr_test": "Лёгкий способ попробовать Nostr с тестовым аккаунтом",
	"common_nostr_view_client": "ОТКРЫТЬ КЛИЕНТ",
	"common_kit_printer": "Мы рекомендуем VistaPrint.com для печати собственных брошюр Bitcoin Business Kit. Однако вы можете использовать любую типографию, которая делает двустороннюю печать.",
	"common_kit_link_to_print": "Ссылка для печати:",
	"common_kit_fold": "Сгиб:",
	"common_kit_fold_trifold": "Тройной сгиб",
	"common_kit_unfolded_size": "Размер в развёрнутом виде:",
	"common_kit_unfolded_size_bbk": "Формат Letter (8,5 дюйма x 11 дюймов)",
	"common_kit_paper_thickness": "Толщина бумаги:",
	"common_kit_paper_thickness_standard": "Стандартная",
	"common_kit_paper_stock": "Тип бумаги:",
	"common_kit_paper_stock_glossy": "Глянцевая",
	"common_kit_exterior_print_file": "Файл печати внешней стороны:",
	"common_kit_interior_print_file": "Файл печати внутренней стороны:",
	"common_kit_cta_header": "Помогите местному бизнесу принять Биткоин",
	"common_biz_learn": "Узнайте, почему Биткоин полезен для бизнеса",
	"common_biz_wallets": "Получите биткоин-кошелёк для приёма платежей в Биткоине",
	"common_biz_maps": "Разместитесь на картах биткоин-торговцев",
	"common_biz_stickers": "Бесплатные стикеры «Здесь принимают Биткоин»",
	"common_biz_rewards": "Награды в Биткоине",
	"common_biz_accounting": "Руководство по бухгалтерскому учёту Биткоина",
	"common_biz_faq": "Часто задаваемые вопросы",
	"common_biz_kit": "Распечатайте свой бизнес-набор Биткоина",
	"common_biz_accept_bitcoin_payments": "ПРИНИМАЙТЕ ПЛАТЕЖИ В БИТКОИНЕ",
	"common_biz_ready": "ГОТОВЫ ПРИНИМАТЬ БИТКОИН В ВАШЕМ БИЗНЕСЕ?",
	"common_biz_more": "БОЛЬШЕ БИЗНЕС-РЕСУРСОВ",
	"common_self_custody": "САМОСТОЯТЕЛЬНОЕ ХРАНЕНИЕ",
	"common_not_your_keys": "НЕ ВАШИ КЛЮЧИ",
	"common_cold_wallet": "ХОЛОДНЫЙ КОШЕЛЁК",
	"common_hot_wallet": "ГОРЯЧИЙ КОШЕЛЁК",
	"common_sticker_files_mission_1": "Наша миссия — помочь вам «оранжевопилить» больше людей, размещая стикеры Биткоина в общественных местах. Все наши стикеры имеют QR-коды, ведущие на образовательные страницы о",
	"common_sticker_files_mission_2": "Биткоине",
	"common_sticker_files_mission_3": "инфляции",
	"common_sticker_files_mission_4": "Если вы живёте в США или Канаде, вы можете",
	"common_sticker_files_mission_5": "запросить бесплатный набор английских стикеров",
	"common_published_by": "Опубликовано",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "Обучение Биткоину с 2022 года",
	"common_publisher_open_source": "Проект с открытым исходным кодом",
	"common_reviewed_accuracy": "✓ Проверено на точность: 2026",
	"common_footer_tagline": "Ускоряем принятие биткоина через образование.",
	"common_footer_contribute": "Внести вклад",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "Источники"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! common.json created for Russian (ru).');
