/**
 * Creates Basque (eu) index.json translation file (~130+ keys)
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'eu';
const today = '2026-04-06';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"bitcoin_builds_a_better_world": "Bitcoin-ek mundu hobea eraikitzen du.",
	"home_description": "Bitcoin diru hobea da, mundu hobea eraikitzen ari dena. Bitcoin-ek giza eskubideak babestu ditu, jendea inflazio altutatik salbatu du, tokiko nekazariak lagundu ditu, petrolio-zulatzeen emisioak murriztu ditu, eta askoz gehiago.",
	"home_intro": "Bitcoin diru hobea da, mundu hobea eraikitzen ari dena. Sakatu beheko kategoria batean Bitcoin-ek nola hobetzen duen ikasteko, edo hasi behera mugitzen esploratzeko.",
	"home_btn_money": "DIRU HOBEA",
	"home_btn_salary": "ZURE SOLDATA",
	"home_btn_freedom": "ASKATASUNA",
	"home_btn_human_rights": "GIZA ESKUBIDEAK",
	"home_btn_equality": "BERDINTASUNA",
	"home_btn_property_rights": "JABETZA ESKUBIDEAK",
	"home_btn_housing": "ETXEBIZITZA",
	"home_btn_business": "NEGOZIOA",
	"home_btn_crowdfunding": "CROWDFUNDING",
	"home_btn_energy": "ENERGIA",
	"home_btn_environment": "INGURUMENA",
	"home_btn_food": "ELIKADURA",
	"home_btn_art": "ARTEA",
	"home_btn_politics": "POLITIKA",
	"home_btn_war": "GERRA",
	"home_btn_coding": "PROGRAMAZIOA",
	"home_btn_networks": "SAREAK",
	"home_btn_payments": "ORDAINKETAK",
	"home_btn_self_custody": "AUTO-ZAINTZA",
	"home_btn_you": "ZU",
	"home_section_bitcoin_is": "BITCOIN DA",
	"home_section_bitcoin_and": "BITCOIN ETA",
	"home_link_type_website": "WEBGUNEA",
	"home_link_type_video": "BIDEOA",
	"home_link_type_article": "ARTIKULUA",
	"home_link_type_podcast": "PODCASTA",
	"home_link_type_business_kit": "NEGOZIO-KITA",
	"home_link_type_data": "DATUAK",
	"home_link_type_research": "IKERKETA",
	"home_link_type_story": "ISTORIOA",
	"home_link_type_book_excerpt": "LIBURU ZATIA",
	"home_link_type_street_art": "KALE ARTEA",
	"home_link_type_outreach": "ZABALKUNTZA",
	"home_link_type_campaign": "KANPAINA",
	"home_link_type_software": "SOFTWAREA",
	"home_link_type_hardware": "HARDWAREA",
	"home_link_type_guide": "GIDA",
	"home_link_type_email": "EMAILA",
	"home_link_title_inflation": "Bitcoin-ek ez du inflaziorik",
	"home_link_title_bank_runs": "Bitcoin-ek ez du banku-ihesik",
	"home_link_title_gold": "Bitcoin vs Urrea",
	"home_link_title_crypto": "Bitcoin vs Crypto",
	"home_link_title_cash": "Bitcoin vs Eskudirua",
	"home_link_title_bonds": "Bitcoin vs Bonuak",
	"home_link_title_cbdc": "Bitcoin vs CBDC-ak",
	"home_link_title_your_salary_1": "Jakin ezazu zure soldatak zenbat igo behar duen inflazioarekin mantentzeko.",
	"home_link_title_freedom_1": "Zergatik den garrantzitsua Bitcoin askatasunerako",
	"home_link_title_freedom_2": "Bitcoin-ek errepresio politikotik askatasuna eskaintzen du",
	"home_link_title_human_rights_1": "Nola betearazten dituen Bitcoin-ek giza eskubideak",
	"home_link_title_human_rights_2": "Afrikako Bitcoin iraultza isila",
	"home_link_title_human_rights_3": "Bitcoin-ek giza eskubideak babesten ditu mundu osoan",
	"home_link_title_equality_1": "Bitcoin-ek itxaropena eta aukera ekartzen die Hegoafrikarrei",
	"home_link_title_equality_2": "Nola izan daitekeen Bitcoin joko-aldaketa Beltzentzat Amerikan",
	"home_link_title_property_rights_1": "Bitcoin jabetzaren forma perfektua da",
	"home_link_title_property_rights_2": "Bitcoin vs Higiezinak",
	"home_link_title_housing_1": "Nola egingo duen Bitcoin-ek etxebizitza berriro eskuragarria",
	"home_link_title_business_3": "Bitcoin vs Akzioak",
	"home_link_title_business_1": "Ikasi zergatik den Bitcoin negoziorako ona",
	"home_link_title_business_2": "Lortu tokiko negozio batek Bitcoin onartzea",
	"home_link_title_crowdfunding_1": "Nola bultzatu zuen Bitcoin-ek Nigeriako protesta handienak belaunaldi batean",
	"home_link_title_crowdfunding_2": "Kanadako kamioi gidarien protestak Bitcoin bidez dirua bildu zuen GoFundMe-k dohaintzak blokeatu ondoren",
	"home_link_title_crowdfunding_3": "Geyser = Crowdfund Bitcoin-ekin",
	"home_link_title_energy_1": "Nola egonkortzen duen Bitcoin-ek Texasko energia-sarea",
	"home_link_title_energy_2": "Zergatik erabiltzen du Bitcoin-ek energia?",
	"home_link_title_energy_3": "Bitcoin-en energia erabilera ez da arazoa. Hona hemen zergatik.",
	"home_link_title_energy_4": "Bitcoin meatzaritza energia-sareak egonkortzen ari da Eskari Erantzunaren bidez",
	"home_link_title_energy_5": "Bitcoin meatzariak Afrikako landa-komunitateetara hidro-energia eramaten ari dira",
	"home_link_title_energy_6": "Nola pizten duen Bitcoin-ek energia berriztagarria",
	"home_link_title_environment_1": "Nola murrizten ari den Bitcoin meatzaritza mundu-mailako metano emisioak",
	"home_link_title_environment_2": "Nola salbatu zuen Bitcoin meatzaritzak Parke Nazional bat",
	"home_link_title_environment_3": "Bitcoin Lurreko industriarik berdeena da!",
	"home_link_title_environment_4": "Bitcoin meatzaritza gas naturalaren kea atmosfera kutsatzea saihesten ari da",
	"home_link_title_food_1": "Nola eragiten dien inflazioak elikagai-prezioei",
	"home_link_title_food_2": "Nola kaltegarria den fiat dirua elikadurarentzat, baserrientzat eta Lurreko zoruentzat",
	"home_link_title_fine_art": "Bitcoin vs Arte Fina",
	"home_link_title_art_1": "Batu gure Bitcoin eranskailu ekimenera",
	"home_link_title_art_2": "Bidali Bitcoin postal bat ezagutzen duzun norbaiti",
	"home_link_title_art_3": "Inprimatu eta jarri Bitcoin liburuxkak",
	"home_link_title_politics_1": "Bitcoin paradoxa politikoa da",
	"home_link_title_politics_2": "Diru hobea bozka dezakezu",
	"home_link_title_war_1": "Nola amai lezakeen Bitcoin-ek amaigabeko gerra",
	"home_link_title_war_2": "Bitcoin eta beteranoak: lerrokadura naturala",
	"home_link_title_war_3": "Nola laguntzen dien Bitcoin-ek zibilei Sudango gerratik ihes egiten",
	"home_link_title_coding_1": "Bitcoin-en alde teknikoari buruzko tutorial interaktiboa",
	"home_link_title_coding_2": "bitcoinSwitch: moldatu edozein gailu Bitcoin onartzeko",
	"home_link_title_coding_3": "Programatu Bitcoin-en misterioak zeharkatuz",
	"home_link_title_networks_1": "Bitcoin sarearen zuzeneko ikuspegia",
	"home_link_title_networks_2": "Bitcoin vs Bankuak",
	"home_link_title_payments_1": "Bitcoin vs Visa",
	"home_link_title_payments_2": "Lightning sarea begiratu bat (Berehala Bitcoin ordainketak)",
	"home_link_title_payments_3": "El Salvadorreko Bitcoin zorroak urtero $400M aurreztu diezaieke Salvadortarrei transferentzia-komisoetan",
	"home_link_title_payments_4": "Lortu zure Lightning helbidea berehala Bitcoin ordainketak jasotzeko",
	"home_link_title_self_custody_1": "Nola gorde modu seguruan zure Bitcoin",
	"home_link_title_self_custody_2": "Bitcoin truketatik ateratzeko 6 arrazoi",
	"home_link_title_self_custody_3": "Urrea, Bitcoin eta auto-zaintza",
	"home_link_title_get_started_1": "Ikasi Bitcoin-en oinarriak",
	"home_link_title_get_started_2": "Lortu zure lehen Bitcoin zorroa",
	"home_link_title_get_started_3": "Nola erosi Bitcoin",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Inflazio Konposatu Kalkulagailua",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone creating index.json for Basque (eu).');
