/**
 * Creates Basque (eu) content page translation files:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'eu';
const today = '2026-04-06';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "Bitcoin-ek ez du banku-ihesik",
	"bank_runs_header": "BITCOIN-EK EZ DU BANKU-IHESIK",
	"bank_runs_header_2": "BAINA ZURE BANKUAK BAI IZAN DEZAKE",
	"bank_runs_what": "ZER DA BANKU-IHES BAT?",
	"bank_runs_what_content_1": "Banku-ihes bat jende askok aldi berean bankutik dirua ateratzea saiatzen denean gertatzen da.",
	"bank_runs_what_content_2": "Bankuek ez badute nahikoa diru eskuragarri ateratzeei aurre egiteko, guztiz hondoratu daitezke banku-ihes bat gertatzen denean.",
	"bank_runs_how": "NOLA GERTATZEN DIRA BANKU-IHESAK?",
	"bank_runs_how_content_1": "Gure banku-sistema 'erreserba zatikaria' da, eta horrek esan nahi du bankuek ez dutela zure dirua ganga batean gordetzen eta itxaroten gastatu edo ateratzeko.",
	"bank_runs_how_content_2": "Horren ordez, zure bankuak zure dirua hartzen du eta maileguan ematen edo inbertitzen du. Honek zure dirua denbora luzerako blokea dezake, nahiz eta bankuak edozein unetan ateratzeko gaitasuna bermatu dizun.",
	"bank_runs_how_content_3": "Beraz, zer gertatzen da bankuak zure dirua dagoeneko maileguan eman edo inbertitu ondoren ateratzen saiatzen bazara?",
	"bank_runs_how_content_4": "Ez da arazoa zuk bakarrik ateratzen saiatzen bazara. Bankuak beste norbaiten dirua hartuko du eta zuri emango dizu. Baina zer gertatzen da jende askok aldi berean ateratzen saiatzen denean?",
	"bank_runs_how_content_5": "AEBetako jende askok jakin zuen 2023ko martxoan Silicon Valley Bankean banku-ihes bat izan zenean.",
	"bank_runs_how_content_6": "Bankuak bere bezeroen dirua 30 urte arteko gobernu-bonuetan inbertitu zuen. Are okerrago, bonu horien balioa azkenaldian nabarmen jaitsi zen, beraz, Silicon Valley Bankek ezin zituen bonuak saldu gordailuzaleen dirua atzera lortzeko. Kaudimengabea ziren. Ez zuten nahikoa diru gordailuzaleen ateratzeei aurre egiteko.",
	"bank_runs_how_content_7": "Jende gehiagok jakin ahala, arazoa larriagotu egin zen. Ateratze-eskaera gehiago iritsi ziren, baina asko ez ziren prozesatu. Milaka enpresak konturatu ziren ezin izango zietela langileei ordaindu bankuaren hutsegiteen ondorioz.",
	"bank_runs_how_content_8": "FDIC-ak esku hartu zuen eta gordailuzaileei dena itzultzea adostu zuen. Arazoa konponduta? Ez guztiz...",
	"bank_runs_fdic": "FDIC ASEGURUAK NIRE DIRUA BABESTEN DU?",
	"bank_runs_fdic_content_1": "FDIC asegurua banku-gordailuzaileak bankuak huts egiten badu babesteko diseinatuta dago. Gordailuak gordailuzaile bakoitzeko $250.000 arte aseguratuta daude. Oso ondo dirudi, ezta?",
	"bank_runs_fdic_content_2": "Ez guztiz. Banku batek huts egiten badu, nondik ateratzen du FDIC-ak dirua? 125.000 milioi dolarreko aseguru-funts bat dute.",
	"bank_runs_fdic_content_3": "Diru asko dirudi aseguratzen dituzten gordailu kopuruarekin konparatzen duzun arte: ia 10 bilioi edo 10.000.000 milioi dolar.",
	"bank_runs_fdic_content_4": "FDIC-ak bere webgunean erakusten du haien aseguru-funtsean gordailuen %1 baino pixka bat gehiago estaltzeko nahikoa dirua bakarrik dutela.",
	"bank_runs_fdic_content_5": "FDIC aseguru-funtsa gainditzen duen banku-hutsegite baten kasuan, litekeena da (baina ez bermatu) AEBetako gobernuak dirua inprimatzea gordailuzaileei dena itzultzeko.",
	"bank_runs_fdic_content_6": "Baina dirua inprimatzeak inflazioa eragiten du, beraz, ez da soluzio bikaina.",
	"bank_runs_safe": "BA AL DIRA ERRESERBA ZATIKARIA ERABILTZEN EZ DUTEN BANKUAK?",
	"bank_runs_safe_content_1": "Banku batzuk 'banku seguru' izaten saiatu dira, gordailuzaleen funtsak maileguan ematen edo inbertitzen ez dituztenak.",
	"bank_runs_safe_content_2": "Banku seguru hauek banku-ihesen zero arriskua izango luketen arren, haien eskaerak Erreserba Federalak ukatu ditu. Honek esan nahi du ez dutela legez banku gisa funtziona dezaketenik.",
	"bank_runs_safe_content_3": "Funtzionatzea galarazi zaiela, gaur egun ez dago erreserba zatikaria erabiltzen ez duen bankurik.",
	"bank_runs_safe_content_4": "Zorionez, erreserba zatikarien sistematik irteteko modu bat dago zure bankua izanez. Ez, ez gabiltza diru metalikoaz kolchoi azpian gordetzeaz hitz egiten.",
	"bank_runs_safe_content_5": "Eskudiruan gordetzea oraindik inflazioaren aurrean ahula da.",
	"bank_runs_safe_content_6": "Bitcoin-ez hitz egiten gabiltza: zure bankua izateko aukera ematen dizun finantza-sistema berri bat.",
	"bank_runs_protect": "BITCOIN-EK BANKU-IHESETATIK BABESTU NAZAKE?",
	"bank_runs_protect_content_1": "Bai, Bitcoin erreserba osoko finantza-sistema bat da.",
	"bank_runs_protect_content_2": "Banku-ihesak ezinezkoak dira Bitcoin-en zure Bitcoin zure zorrora ateratzen duzun bitartean. Ez utzi zure bitcoin truke batean edo ETF bezalako bilgarri batean.",
	"bank_runs_protect_content_3": "Ikusi gure Bitcoin zorro gida sinplea zure zorrora nola atera ikasteko.",
	"bank_runs_protect_content_4": "Bitcoin-ekin, azkenik zure diruaren kontrolean egon zaitezke."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Bitcoin zorro gida",
	"wallets_description": "Bitcoin zorro asko daude modu garrantzitsuetan desberdintzen direnak. Galdera sinple hauek eginez zorro bat zuretzat egokia den zehaztu dezakezu.",
	"wallets_header": "NOLA GORDE MODU SEGURUAN ZURE BITCOIN",
	"wallets_s1_c1": "Bitcoin zorroak elkarreragileak dira, beraz, Bitcoin edonori bidali dezakezu erabiltzen duen zorroa edozein dela ere.",
	"wallets_s1_c2": "Bitcoin zorro asko daude modu garrantzitsuetan desberdintzen direnak. Galdera sinple hauek eginez zorro bat zuretzat egokia den zehaztu dezakezu:",
	"wallets_question_1": "AUTO-ZAINTZAKO ZORROA DA?",
	"wallets_s2_c1": "Bitcoin-en berrikuntza bat zaintzaile batean, banku batean bezala, fidatu gabe gordetzeko gaitasuna da.",
	"wallets_s2_c2": "Bitcoin truke batean edo ETF batean edukitzen baduzu, bitcoin-en askatasun-abantailak galtzen dituzu.",
	"wallets_s2_c3": "Auto-zaintzako zorroek Bitcoin-en ahalmen osoa desblokeatzen dute: askatasun dirua.",
	"wallets_s2_c4": "Auto-zaintzako zorro batekin, zeu zara zure dirua gastatu edo transferitzeko gaitasuna duen bakarra. Inork ez du zure dirua bidaltzea edo jasotzea galarazi dezake auto-zaintzako zorro bat erabiltzen duzunean.",
	"wallets_s2_c5": "Auto-zaintzako zorroak zorro ez-kustodialak ere deitzen dira.",
	"wallets_s3_c1": "Zorro kustodialak zure diruaren kontrola ez duzun zorroak dira.",
	"wallets_s3_c2": "Zorro hauek banku-sistematik antzekoak dira, non hirugarren baten menpe zauden zure dirura sarbidea izateko. Zure Bitcoin truke batean badago, zorro kustodial bat erabiltzen ari zara.",
	"wallets_s3_c3": "Bitcoin ETF bat erosi baduzu, auto-zaintzara ateratzea ahalbidetzen ez duen zorro kustodial bat erabiltzen ari zara.",
	"wallets_s3_c4": "Zorro kustodialak erosoak iruditu daitezke, baina zaintzaileak erabiltzaile guztien funtsak edozein unetan lapurtzeko gaitasun teknikoa du.",
	"wallets_s3_c5": "Zure gakoak ez, zure txanponak ez!",
	"wallets_question_2": "BEROA ALA HOTZA DA?",
	"wallets_s4_c1": "Zorro hotzek zure Bitcoin-en gakoak inoiz Internetera esposatu ez diren moduan gordetzen dituzte.",
	"wallets_s4_c2": "Honek nabarmen mugatzen du lapurrek zure Bitcoin lapurtzen saiatzeko erabil ditzaketen eraso-bektoreak, eta ondoen erabiltzen da maiz transferitu behar ez dituzun Bitcoin kopuru handietarako.",
	"wallets_s4_c3": "Zorro hotza epe luzeko aurrezki-kontu gisa pentsa dezakezu, hotz-biltegiratzea ere deitua.",
	"wallets_s5_c1": "Zorro beroek zure Bitcoin-en gakoak Internetera konektatuta dagoen gailu batean gordetzen dituzte, zure telefonoan bezala.",
	"wallets_s5_c2": "Zorro beroak orokorrean segurutzat jotzen dira, baina zorro hotzek baino segurtasun-ahultasun gehiago izan ditzakete.",
	"wallets_s5_c3": "Zorro beroa zorro fisiko bat bezala pentsa dezakezu. Ez zenuke zure aurrezki guztiak zure zorroan gordeko, baina gastu pixka bat gordeko zenuke.",
	"wallets_s5_c4": "Zorro beroek zure Bitcoin askoz errazago gastatzea ahalbidetzen dute hotz-biltegiratzeetik zure aurrezki guztiak atera beharrik gabe.",
	"wallets_question_3": "NOLA EGINGO DUT NIRE BERRESKURATZE-ESALDIAREN BABESKOPIA?",
	"wallets_s6_c1": "Zure Bitcoin zorroa konfiguratzen duzunean, zure gailuak berreskuratze-esaldi bat sortuko du. Berreskuratze-esaldi honek (hazi-esaldia ere deitua) 12 edo 24 hitz ditu.",
	"wallets_s6_c2": "Inoiz zure zorrora sarbidea galtzen baduzu edo zure gailuak funtzionatzeari uzten badio, berreskuratze-esaldi hau zorro berri batean sar dezakezu zure Bitcoin-era berriro sarbidea izateko.",
	"wallets_s6_c3": "Zorro gehienek zure berreskuratze-esaldia idazteko paper orri bat barneratzen dute, baina jende askok esaldi honen babeskopia altzairuan egitea nahiago du. Honek askoz gutxiagoko probabilitatea du zure berreskuratze-esaldia galtzeko hondamendi natural baten kasuan, hala nola sute edo uholde baten kasuan.",
	"wallets_s6_c4": "Jameson Lopp-ek 70 altzairuzko babeskopia kit probatu ditu zuretzat egokiena dena aukeratzen laguntzeko.",
	"wallets_s6_c5": "Ikusi hemen Jameson-en metalezko Bitcoin babeskopia gida.",
	"wallets_s6_c6": "Edo jarraitu beherantz Bitcoin zorro aukerak esploratzeko.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "Gure Lightning zorro gida bilatzen ari zara?",
	"wallets_starter_wallet": "Hasierako zorro bikaina",
	"wallets_mobile_app": "Mugikorreko aplikazioa",
	"wallets_2fa_support": "2FA euskarria",
	"wallets_air_gap_mode": "Aire-hutsune modua",
	"wallets_air_gap_camera": "Aire-hutsune modua + kamera",
	"wallets_bitcoin_only": "Bitcoin soilik",
	"wallets_security_features": "Segurtasun-ezaugarri asko",
	"wallets_free": "%100 doakoa",
	"wallets_coldcard_mk5_costs": "$189 kostatzen du",
	"wallets_coldcard_q_costs": "$289 kostatzen du",
	"wallets_blockstream_jade_costs": "$79 kostatzen du",
	"wallets_foundation_passport_costs": "$199 kostatzen du",
	"wallets_seedsigner_costs": "Piezak $50 kostatzen dira",
	"wallets_very_affordable": "Oso eskuragarria",
	"wallets_pair_with_phone": "Lotu zure telefonoarekin",
	"wallets_battery": "Bateria kargagarria",
	"wallets_build_your_own": "Eraiki zeurea",
	"wallets_qwerty_keyboard": "QWERTY teklatua osoa",
	"wallets_qr_scanner": "QR kode eskaner"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "Nola erosi Bitcoin - Urratsez urratseko gida",
	"buy_header": "NOLA EROSI BITCOIN",
	"buy_intro_c1": "Bitcoin lehen aldiz erostea gaindiezina iruditu daiteke, baina benetan nahiko sinplea da urratsetan banatzen duzunean.",
	"buy_intro_c2": "Gida honek Bitcoin modu seguruan erosi eta zure zorroan gordetzeko prozesuan zehar lagunduko dizu.",
	"buy_step_1_header": "1. URRATSA: AUKERATU ZURE HERRIALDEA",
	"buy_step_1_description": "Herrialde desberdinetan Bitcoin erosteko aukera desberdinak daude. Aukeratu zure herrialdea zuretzat aukera onenak ikusteko.",
	"buy_search_countries": "Bilatu zure herrialdea",
	"buy_country_united_states": "Amerikako Estatu Batuak",
	"buy_country_australia": "Australia",
	"buy_country_austria": "Austria",
	"buy_country_belgium": "Belgika",
	"buy_country_brazil": "Brasil",
	"buy_country_canada": "Kanada",
	"buy_country_france": "Frantzia",
	"buy_country_germany": "Alemania",
	"buy_country_ireland": "Irlanda",
	"buy_country_italy": "Italia",
	"buy_country_netherlands": "Herbehereak",
	"buy_country_new_zealand": "Zeelanda Berria",
	"buy_country_spain": "Espainia",
	"buy_country_united_kingdom": "Erresuma Batua",
	"buy_country_argentina": "Argentina",
	"buy_country_chile": "Txile",
	"buy_country_colombia": "Kolonbia",
	"buy_country_costa_rica": "Costa Rica",
	"buy_country_czech_republic": "Txekiar Errepublika",
	"buy_country_denmark": "Danimarka",
	"buy_country_el_salvador": "El Salvador",
	"buy_country_estonia": "Estonia",
	"buy_country_finland": "Finlandia",
	"buy_country_greece": "Grezia",
	"buy_country_guatemala": "Guatemala",
	"buy_country_hong_kong": "Hong Kong",
	"buy_country_hungary": "Hungaria",
	"buy_country_iceland": "Islandia",
	"buy_country_india": "India",
	"buy_country_israel": "Israel",
	"buy_country_japan": "Japonia",
	"buy_country_latvia": "Letonia",
	"buy_country_lithuania": "Lituania",
	"buy_country_luxembourg": "Luxenburgo",
	"buy_country_malta": "Malta",
	"buy_country_mexico": "Mexiko",
	"buy_country_norway": "Norvegia",
	"buy_country_panama": "Panama",
	"buy_country_poland": "Polonia",
	"buy_country_portugal": "Portugal",
	"buy_country_romania": "Errumania",
	"buy_country_singapore": "Singapur",
	"buy_country_slovakia": "Eslovakia",
	"buy_country_slovenia": "Eslovenia",
	"buy_country_south_africa": "Hegoafrika",
	"buy_country_south_korea": "Hego Korea",
	"buy_country_sweden": "Suedia",
	"buy_country_switzerland": "Suitza",
	"buy_country_thailand": "Thailandia",
	"buy_country_turkey": "Turkia",
	"buy_country_ukraine": "Ukraina",
	"buy_country_uruguay": "Uruguai",
	"buy_step_2_header": "2. URRATSA: AUKERATU ZURE ORDAINKETA METODOA",
	"buy_step_2_description": "Bitcoin erosteko bi modu nagusi daude: banku-transferentzia bidez edo eskudiruz. Bakoitzak abantaila desberdinak ditu.",
	"buy_method_bank_transfer": "BANKU-TRANSFERENTZIA",
	"buy_method_bank_fast": "Azkarra eta erraza",
	"buy_method_bank_less_private": "Pribatutasun gutxiago",
	"buy_method_bank_description": "Banku-transferentziak Bitcoin erosteko modurik ohikoena dira. Azkarrak, erosoak eta normalean komisio baxuagoak dituzte.",
	"buy_method_choose_bank": "Aukeratu banku-transferentzia",
	"buy_method_cash": "ESKUDIRUA",
	"buy_method_cash_private": "Pribatutasun gehiago",
	"buy_method_cash_limited": "Aukera mugatuak",
	"buy_method_cash_description": "Eskudiruzko erosketak pribatutasun gehiago eskaintzen dute baina aukera gutxiago dituzte eta norbaitekin pertsonalki biltzea edo Bitcoin kutxazain bat erabiltzea behar dute.",
	"buy_method_choose_cash": "Aukeratu eskudirua",
	"buy_step_3_header": "3. URRATSA: EROSKETA AUKERAK",
	"buy_step_3_description": "Hona hemen zure herrialde eta ordainketa metodorako Bitcoin erosketa aukera onenak:",
	"buy_platform_recommended": "GOMENDATUA",
	"buy_platform_strike_description": "Strike Bitcoin erosteko modurik azkarrena eta errazena da, komisio baxuekin eta Lightning sarearen berehalako laguntzarekin.",
	"buy_platform_swan_description": "Swan Bitcoin Bitcoin soilik zerbitzuetan espezializatzen da, dolar-kostu batezbestekotzea eta hezkuntza-baliabideekin.",
	"buy_platform_river_description": "River-ek Bitcoin erosketa, meatzaritza eta zaintza-zerbitzuak eskaintzen ditu, hezkuntzari eta segurtasunari arreta berezia eskainiz.",
	"buy_platform_coinsquare_description": "Coinsquare Kanadiar Bitcoin trukea da, araudia betetze sendoa eta bezeroaren laguntza duena.",
	"buy_platform_kraken_description": "Kraken Bitcoin truke ezaguna da, merkataritza-ezaugarri aurreratuekin eta segurtasun sendoarekin.",
	"buy_platform_atm_description": "Bitcoin kutxazainek eskudiruz berehala Bitcoin erosteko aukera ematen dute. Aurkitu zuretik gertuen dagoena Coin ATM Radar erabiliz.",
	"buy_platform_bisq_description": "Bisq Bitcoin merkataritza pribatua KYC-rik gabe ahalbidetzen duen pertsona arteko truke deszentralizatua da.",
	"buy_platform_feature_instant": "Berehala erosketak",
	"buy_platform_feature_low_fees": "Komisio baxuak",
	"buy_platform_feature_lightning": "Lightning sarea",
	"buy_platform_feature_dca": "Dolar-kostu batezbestekotzea",
	"buy_platform_feature_education": "Hezkuntza-baliabideak",
	"buy_platform_feature_withdrawal": "Ateratze erraza",
	"buy_platform_feature_mining": "Bitcoin meatzaritza",
	"buy_platform_feature_custody": "Zaintza-zerbitzuak",
	"buy_platform_feature_canadian": "Kanadan zentratua",
	"buy_platform_feature_regulated": "Erregulatutako trukea",
	"buy_platform_feature_support": "Bezero-laguntza",
	"buy_platform_feature_established": "Plataforma ezaguna",
	"buy_platform_feature_security": "Segurtasun sendoa",
	"buy_platform_feature_advanced": "Ezaugarri aurreratuak",
	"buy_platform_feature_cash": "Eskudiruzko erosketak",
	"buy_platform_feature_anonymous": "Anonimotasun gehiago",
	"buy_platform_feature_p2p": "Pertsona artekoa",
	"buy_platform_feature_private": "Merkataritza pribatua",
	"buy_platform_feature_decentralized": "Deszentralizatua",
	"buy_platform_relai_description": "Relai Bitcoin soilik Suitzako aplikazioa da, auto-zaintzako zorroa, auto-inbertsio ezaugarriak eta komisio baxuak Europako erabiltzaileentzat.",
	"buy_platform_feature_bitcoin_only": "Bitcoin soilik",
	"buy_platform_feature_self_custody": "Auto-zaintzako zorroa",
	"buy_platform_feature_auto_invest": "Auto-inbertsio planak",
	"buy_platform_feature_european": "Europan zentratua",
	"buy_step_4_header": "4. URRATSA: GORDE ZURE BITCOIN MODU SEGURUAN",
	"buy_step_4_c1": "Bitcoin erosi ondoren, urrats garrantzitsuena da zure gako pribatuak kontrolatzen dituzun zure zorrora mugitzea.",
	"buy_step_4_c2": "Bitcoin truke batean uztea arriskutsua da, benetan ez baitaukazu Bitcoin-en jabetza - trukeak dauka.",
	"buy_step_4_c3": "Zure gako pribatuak kontrolatzen dituzunean, zure Bitcoin-en benetako jabetza duzu eta inork ezin dizu kendu.",
	"buy_step_4_c4": "Ikasi nola aukeratu zure beharretarako Bitcoin zorro egokia:",
	"buy_cta_wallets": "Ikusi gure Bitcoin zorro gida"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Bitcoin Lightning zorro gida",
	"lightning_description": "Lightning zorroek Bitcoin azkar eta merke bidaltzeko aukera ematen dizute zure subiranotasun pertsonala mantenduz.",
	"lightning_header": "LIGHTNING ZORRO GIDA",
	"lightning_s1_c1": "Lightning-ek Bitcoin ordainketak azkar eta merke bidaltzeko aukera ematen dizu.",
	"lightning_s1_c2": "Garrantzitsua da jakitea Lightning erabiltzeak truke-konpromisoak dituela. Bitcoin ordainketa azkarrago eta merkeagoen truke, askotan segurtasun pixka bat sakrifikatzen duzu.",
	"lightning_s1_c3": "Orokorrean, Lightning bitcoin kopuru txikiekin soilik erabili behar da. Bitcoin kopuru handiak soilik hardware zorro batean gorde beharko zenituzke.",
	"lightning_s1_c4": "Ikusi gure hardware zorro gida informazio gehiagorako.",
	"lightning_s1_c5": "Lightning zorro guztiak ez dira berdinak. Galdera sinple bat eginez zehaztu dezakezu zein zorrok dituen zuretzat egokiak diren truke-konpromisoak:",
	"lightning_question_1": "ZEIN TRUKE-KONPROMISO OREKA DA NIRETZAT EGOKIA?",
	"lightning_s2_c1": "Bitcoin-en berrikuntza bat zaintzaile batean, banku batean bezala, fidatu gabe gordetzeko gaitasuna da. Auto-zaintzako zorroek Bitcoin-en ahalmen osoa desblokeatzen dute.",
	"lightning_s2_c2": "Auto-zaintzako zorro batekin, zeu zara zure dirua gastatu edo transferitzeko gaitasuna duen bakarra. Inork ez du zure gelditu, zentzuratu edo lapurtzea dezake auto-zaintzako zorro bat erabiltzen duzunean. Hauek zorro ez-kustodialak ere deitzen dira.",
	"lightning_s2_c3": "Lightning erabiltzeko modurik subiranoena zure nodo propioa exekutatzea da.",
	"lightning_s2_c4": "Gida hau zure nodorik behar ez duten Lightning zorro sinpleetan zentratzen da.",
	"lightning_s2_c5": "Garrantzitsua da jakitea Lightning zorro ez-kustodial bat erabiliz ere, oraindik ere zorro-sortzailean fidatzen zarela eguneratze maltzur bat bota eta zure funtsak lapurtzeko.",
	"lightning_s3_c1": "Zorro kustodialak zure diruaren kontrola ez duzun zorroak dira.",
	"lightning_s3_c2": "Zorro hauek banku-sistematik antzekoak dira, non hirugarren baten menpe zauden zure dirura sarbidea izateko. Zure Bitcoin truke batean badago, zorro kustodial bat erabiltzen ari zara.",
	"lightning_s3_c3": "Zorro kustodialak erosoak iruditu daitezke, baina zaintzaileak erabiltzaile guztien funtsak edozein unetan lapurtzeko gaitasun teknikoa du.",
	"lightning_s3_c4": "Pertsona batzuek Lightning zorro kustodialak nahiago dituzte bitcoin kopuru txikietarako, erabiltzeko errazak direlako. Baina gogoratu: zure gakoak ez, zure txanponak ez!",
	"lightning_question_2": "AUKERATU ZURE ZORROA",
	"lightning_s4_c1": "Hau guztia kontuan hartuta, orain zuretzat truke-konpromiso oreka egokia duen Lightning zorroa aukera dezakezu.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "Ezaugarri asko",
	"lightning_mobile_app": "Mugikorreko aplikazioa",
	"lightning_free": "%100 doakoa",
	"lightning_merchants": "Merkatarientzat bikaina",
	"lightning_starter": "Hasierako zorro bikaina",
	"lightning_browser": "Nabigatzaile bidez",
	"lightning_custodial": "Guztiz kustodialeko zorroa",
	"lightning_cta_hardware": "Gure Bitcoin hardware zorro gida bilatzen ari zara?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "Bitcoin eranskailu doakoak bitcoin.rocks-etik",
	"stickers_description": "Jarri Bitcoin eranskailu bat leku publikoan zure ingurukoak orange pill egiteko.",
	"stickers_header": "BITCOIN ERANSKAILU DOAKOAK",
	"stickers_choose_header": "AUKERATU ZURE ERANSKAILU PAKETEA",
	"stickers_choose_c1": "Gure helburua jende gehiago orange pill egiten laguntzea da Bitcoin eranskailuak leku publikoetan jarriz. Gure eranskailu guztiek QR kodeak dituzte hezkuntza orrialdetara esteka dutenak",
	"stickers_choose_c2": "Bitcoin",
	"stickers_choose_c3": "inflazioa",
	"stickers_choose_c4": "Aukeratu zure eranskailu paketea behean",
	"stickers_text_pack": "TESTU PAKETEA",
	"stickers_signs_pack": "SEINALE PAKETEA",
	"stickers_instructions_1": "Sartu zure posta-helbidea eta doako Bitcoin eranskailu pakete bat bidaliko dizugu postaz! Zure eranskailuak gutun-azal zuri batean bidaliko dira.",
	"stickers_instructions_2": "Helbide datuak zure doako eranskailuak bidali ondoren ezabatzen dira.",
	"stickers_share_header": "PARTEKATU ZURE ERANSKAILU LEKUAK",
	"stickers_share_c1": "Partekatu zure eranskailu lekuak gurekin Nostr-en eta ikusi beste jendeak non jartzen dituen bere eranskailuak.",
	"stickers_btn_share_on_nostr": "PARTEKATU NOSTR-EN",
	"stickers_btn_what_is_nostr": "ZER DA NOSTR?",
	"stickers_flyers_link_before": "Bitartean, inprimatu eta jarri zure ",
	"stickers_flyers_link_text": "Bitcoin liburuxkak",
	"stickers_flyers_link_after": " jende gehiago orange pill egiteko.",
	"stickers_country_global_print": "Mundua — Nire eranskailuak inprimatu",
	"stickers_country_global_order": "Mundua — Handizkako eskatu",
	"placeholder_name_optional": "Izena (aukerakoa)",
	"placeholder_address_line_1": "Helbide 1. lerroa",
	"placeholder_address_line_2": "Helbide 2. lerroa (aukerakoa)",
	"placeholder_city": "Hiria",
	"placeholder_state": "Estatua",
	"placeholder_province": "Probintzia",
	"placeholder_zip_code": "Posta-kodea",
	"placeholder_postal_code": "Posta-kodea",
	"placeholder_language": "Hizkuntza",
	"placeholder_which_stickers": "Zein eranskailu?",
	"placeholder_email_optional": "Sartu zure emaila jakinarazpena jasotzeko (aukerakoa)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "Bitcoin postal doakoak bitcoin.rocks-etik",
	"postcards_description": "Lortu doako Bitcoin postal pakete bat eta partekatu Bitcoin ezagutzen duzun norbaitekin.",
	"postcards_header": "POSTALAK PROGRAMA ITXITA",
	"postcards_program_closed_message": "Gure doako Bitcoin postal programa amaitu da. Eskerrik asko postaz Bitcoin hezkuntza zabaltzen parte hartu duzuen guztioi!",
	"postcards_sticker_alternative_header": "LORTU DOAKO BITCOIN ERANSKAILUAK ORDEZ",
	"postcards_sticker_alternative_message": "Jarraitu Bitcoin-en kontzientzia zabaltzen gure doako eranskailu programarekin! Gure Bitcoin eranskailuak ezin hobeak dira leku publikoetan partekatzeko eta hezkuntza edukietara esteka duten QR kodeekin datoz.",
	"postcards_sticker_cta": "LORTU DOAKO ERANSKAILUAK",
	"postcards_step_2": "NOLAKOAK ZIREN POSTALAK",
	"postcards_instructions_4": "Postal hauek egin genituen ezagutzen duzun norbaiti Bitcoin aurkeztea errazteko! Gehitu helbide bat eta sello bat eta bota zure postala postontzian.",
	"postcards_instructions_5": "Gure helburua Bitcoin adopzioa azkartzea da. Doako eranskailuak lortu eta leku publikoetan jarriz lagun dezakezu!",
	"postcards_instructions_6": "Guztiok ezagutzen dugu Bitcoin-i buruz gehiago ikasiz onura lortuko luketen jendea. Partekatu Bitcoin eranskailuak haiekin gaur!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "Lagundu iezaguzu Bitcoin kartel hauek AEB osoan jartzen!",
	"signs_title": "Bitcoin kartel doakoak bitcoin.rocks-etik",
	"signs_choose_header": "ESKERRIK ASKO BITCOIN KARTEL HAUEK AEB OSOAN JARTZEN LAGUNTZEAGATIK!",
	"signs_choose_c1": "Orain guztiz kartelik gabe gaude! Gure helburua Bitcoin adopzioa azkartzea da hezkuntzaren bidez.",
	"signs_choose_c2": "Askok lagundu duzue doako Bitcoin kartel hauek leku publikoetan jarriz. Gure kartel guztiek QR kodeak dituzte hezkuntza orrialde batera esteka dutenak",
	"signs_choose_c3": "inflazioa",
	"signs_choose_c4": "Gure komunitate bikainari esker, milaka pertsonetara iritsi ginen eta Bitcoin zuloan lehen urratsak ematen lagundu genien.",
	"signs_share_header": "PARTEKATU ZURE KARTEL LEKUAK",
	"signs_share_c1": "Partekatu zure kartel lekuaren argazki bat gurekin Nostr-en eta ikusi beste jendeak non jartzen dituen bere kartelak.",
	"signs_btn_share_on_nostr": "PARTEKATU NOSTR-EN",
	"signs_btn_what_is_nostr": "ZER DA NOSTR?",
	"signs_instructions_1": "Sartu zure posta-helbidea eta 10 Bitcoin karteleko kutxa bat bidaliko dizugu postaz!",
	"signs_instructions_2": "Helbide datuak zure doako kartelak bidali ondoren ezabatzen dira."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "Bitcoin liburuxka doakoak bitcoin.rocks-etik",
	"flyers_description": "Inprimatu Bitcoin liburuxka bat etxean eta jarri leku publikoan zure ingurukoak orange pill egiteko.",
	"flyers_header_1": "INPRIMATU ETA JARRI",
	"flyers_header_2": "BITCOIN LIBURUXKAK",
	"flyers_intro_header": "NOLA INPRIMATU ETA JARRI BITCOIN LIBURUXKA HAUEK",
	"flyers_intro_c1": "Gure helburua jende gehiago orange pill egiten laguntzea da Bitcoin liburuxkak leku publikoetan jarriz. Liburuxka honek QR kode bat du gure",
	"flyers_intro_c2": "Bitcoin hezkuntza webgunera.",
	"flyers_intro_c3": "inflazioa",
	"flyers_intro_c4": "Inprimatu liburuxka hau etxean edo inprimategi batean. Gero, jarri iragarki-tauletan, telefono-zutabeetan eta jendeak ikus dezakeen eta Bitcoin-i buruz ikas dezakeen beste leku publikoetan.",
	"flyers_intro_c5": "Bitartean, eskatu gure",
	"flyers_intro_c6": "doako Bitcoin eranskailu",
	"flyers_intro_c7": "pakete bat jende gehiago orange pill egiteko.",
	"flyers_btn_download": "DESKARGATU LIBURUXKA",
	"flyers_btn_print": "INPRIMATU LIBURUXKA",
	"flyers_share_header": "PARTEKATU ZURE LIBURUXKA LEKUAK",
	"flyers_share_c1": "Partekatu zure liburuxka lekuak gurekin Nostr-en eta ikusi beste jendeak non jartzen dituen bere liburuxkak.",
	"flyers_btn_share_on_nostr": "PARTEKATU NOSTR-EN",
	"flyers_btn_what_is_nostr": "ZER DA NOSTR?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "Parte hartu eta lagundu Bitcoin zabaltzen",
	"get_involved_description": "Gure baliabide doakoek Bitcoin adopzioa zabaltzea errazten dute.",
	"get_involved_header": "PARTE HARTU",
	"get_involved_header_2": "ZABALDU BITCOIN",
	"get_involved_intro_1": "Gure munduaren egungo egoeran bizitzea etsigarria izan daiteke.",
	"get_involved_intro_2": "Gure dirua hautsita dago. Ondorioz, gizartearen oinarrizko atalak ere hautsita daude.",
	"get_involved_intro_3": "Dagoeneko Bitcoin munduan bazaude, ezagutzen duzu Bitcoin-ek ekar dezakeen itxaropenaren sentsazioa. Diru hobeagoak ahalbidetutako etorkizun distiratsuago baterako itxaropena.",
	"get_involved_intro_4": "Baina zure inguruko jende askok ez daki Bitcoin-i buruz. Zu bezala mundu hautsian bizi dira, baina iluntasunean laguntzeko itxaropenaren argirik gabe.",
	"get_involved_intro_5": "Baina zuk lagundu dezakezu hori aldatzen. Hainbat baliabide doako egin ditugu zure inguruan Bitcoin-ek ekartzen duen itxaropena zabaltzea errazteko.",
	"get_involved_sticker_header": "Jarri eranskailu bat leku publikoan",
	"get_involved_sticker_content_1": "Zure ingurukoak Bitcoin-i buruz heztea lagun dezakezu inorekin elkarreragin beharrik gabe. Besterik gabe, jarri gure doako Bitcoin eranskailu bat leku publikoan.",
	"get_involved_sticker_content_2": "Ehunka pertsonek eskaneatzen dituzte eranskailu hauetako QR kodeak hilero. Inflazio eranskailuek orrialde batera esteka dute",
	"get_involved_sticker_content_3": "Bitcoin inflazioaren soluzioa gisa.",
	"get_involved_sticker_content_4": "Beste eranskailuek gure hezkuntza hasiera orrira esteka dute, jendeari erakusten diena",
	"get_involved_sticker_content_5": "Bitcoin mundu hobea eraikitzen ari dela.",
	"get_involved_sticker_content_6": "Eranskailu hauek zure komunitatean jendeak ikusiko dituen lekuetan jarriz, zure ingurukoak Bitcoin zuloan lehen urratsak ematen lagundu ditzakezu.",
	"get_involved_request_a": "ESKATU",
	"get_involved_sticker_pack": "ERANSKAILU PAKETE BAT",
	"get_involved_postcard_header": "Bidali postal bat",
	"get_involved_postcard_content_1": "Bitcoin-en itxaropena ezagutzen duzun norbaiti zabaltzea lagun dezakezu gure doako postal bat bidaliaz.",
	"get_involved_postcard_content_2": "Postal bakoitzaren atzeko aldean Bitcoin-i buruzko testu erakargarria dago, gehiago ikasteko QR kode batekin.",
	"get_involved_postcard_content_3": "Norbaiti Bitcoin postal bat bidaliaz, Bitcoin modu berri batean ikusten lagundu diezaiokezu.",
	"get_involved_postcard_pack": "POSTAL PAKETE BAT",
	"get_involved_business_header": "Sartu negozio bat",
	"get_involved_business_content_1": "Bitcoin ekonomia zirkularra eraikitzen lagundu nahi duzu? Gure Bitcoin negozio-kitak erraza egiten du negozio bati Bitcoin ordainketak onartzeko proposatzea.",
	"get_involved_business_content_2": "Negozio-kit bakoitzak Bitcoin ordainketak onartzeko abantailak nabarmentzen dituzten liburuxkak barneratzen ditu. Liburuxka bakoitzak hainbat",
	"get_involved_business_content_3": "doako Bitcoin negozio-baliabide",
	"get_involved_business_kit": "NEGOZIO-KITA"
});

console.log('\nDone creating content files for Basque (eu).');
