/**
 * Creates Romanian (ro) translation files for remaining content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ro';
const today = '2026-04-11';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "Bitcoin nu are crize bancare",
	"bank_runs_header": "BITCOIN NU ARE CRIZE BANCARE",
	"bank_runs_header_2": "DAR BANCA TA AR PUTEA AVEA",
	"bank_runs_what": "CE ESTE O CRIZĂ BANCARĂ?",
	"bank_runs_what_content_1": "O criză bancară se întâmplă când prea mulți oameni încearcă să își retragă banii de la bancă în același timp.",
	"bank_runs_what_content_2": "Dacă băncile nu au suficienți bani disponibili pentru a acoperi retragerile, pot colapsaî complet când apare o criză bancară.",
	"bank_runs_how": "CUM APAR CRIZELE BANCARE?",
	"bank_runs_how_content_1": "Sistemul nostru bancar este cu 'rezerve fracționare', ceea ce înseamnă că băncile nu păstrează doar banii tăi într-un seif și așteaptă să îi cheltuiești sau să îi retragi.",
	"bank_runs_how_content_2": "În schimb, banca îți ia banii și îi împrumută sau îi investește. Aceasta poate bloca banii tăi pentru perioade lungi de timp, deși banca îți promite posibilitatea de a-ți retrage banii oricând.",
	"bank_runs_how_content_3": "Deci ce se întâmplă dacă încerci să îți retragi banii după ce banca i-a împrumutat sau investit deja?",
	"bank_runs_how_content_4": "Nu este o problemă dacă ești singurul care încearcă să retragă. Banca va lua banii altcuiva și ți-i va da ție. Dar ce se întâmplă când prea mulți oameni încearcă să retragă în același timp?",
	"bank_runs_how_content_5": "Mulți oameni din SUA au aflat când a fost o criză bancară la Silicon Valley Bank în martie 2023.",
	"bank_runs_how_content_6": "Banca investise banii clienților lor în obligațiuni guvernamentale care erau blocate pentru până la 30 de ani. Mai rău, valoarea acelor obligațiuni scăzuse dramatic recent, așa că Silicon Valley Bank nu putea pur și simplu să vândă obligațiunile pentru a obține banii deponenților. Erau insolvabili. Nu aveau suficienți bani pentru a acoperi retragerile deponenților.",
	"bank_runs_how_content_7": "Pe măsură ce mai mulți oameni au aflat, problema s-a agravat. Au venit mai multe cereri de retragere, dar multe nu au fost procesate. Mii de afaceri au realizat că nu vor putea să își plătească angajații din cauza eșecului băncii.",
	"bank_runs_how_content_8": "FDIC a intervenit și a acceptat să despăgubească deponenții. Problemă rezolvată? Nu chiar...",
	"bank_runs_fdic": "MĂ PROTEJEAZĂ ASIGURAREA FDIC?",
	"bank_runs_fdic_content_1": "Asigurarea FDIC este concepută pentru a proteja deponenții bancari în cazul în care o bancă eșuează. Depozitele sunt asigurate până la 250.000 $ per deponent. Sună grozav, nu?",
	"bank_runs_fdic_content_2": "Nu chiar. Dacă o bancă eșuează, de unde ia FDIC banii? Au un fond de asigurare cu 125 de miliarde de dolari.",
	"bank_runs_fdic_content_3": "Pare mult până când compari cu suma depozitelor pe care le asigură: aproape 10 trilioane sau 10.000 de miliarde de dolari.",
	"bank_runs_fdic_content_4": "FDIC chiar arată pe site-ul lor că au suficienți bani în fondul de asigurare pentru a acoperi puțin peste 1% din depozite.",
	"bank_runs_fdic_content_5": "În cazul unui eșec bancar care depășește fondul de asigurare FDIC, este probabil (dar nu garantat) că guvernul american ar tipări bani pentru a despăgubi deponenții.",
	"bank_runs_fdic_content_6": "Dar tipărirea de bani cauzează inflație, deci nu este o soluție grozavă.",
	"bank_runs_safe": "EXISTĂ BĂNCI CARE NU FOLOSESC REZERVE FRACȚIONARE?",
	"bank_runs_safe_content_1": "Unele bănci au încercat să fie 'bănci sigure' care nu împrumută sau investesc fondurile deponenților.",
	"bank_runs_safe_content_2": "Chiar dacă aceste bănci sigure nu ar avea niciun risc de crize bancare, cererile lor au fost respinse de Rezerva Federală. Aceasta înseamnă că nu pot opera legal ca bănci.",
	"bank_runs_safe_content_3": "Deoarece li s-a blocat funcționarea, nu există bănci astăzi care să nu folosească rezerve fracționare.",
	"bank_runs_safe_content_4": "Din fericire, există o modalitate de a ieși din sistemul de rezerve fracționare fiind propria ta bancă. Nu, nu vorbim despre a ascunde bani sub saltea.",
	"bank_runs_safe_content_5": "Economisirea în numerar este încă vulnerabilă la inflație.",
	"bank_runs_safe_content_6": "Vorbim despre Bitcoin: un nou sistem financiar care îți permite să fii propria ta bancă.",
	"bank_runs_protect": "MĂ POATE PROTEJA BITCOIN DE CRIZE BANCARE?",
	"bank_runs_protect_content_1": "Da, Bitcoin este un sistem financiar cu rezerve complete.",
	"bank_runs_protect_content_2": "Crizele bancare sunt imposibile în Bitcoin atât timp cât îți retragi Bitcoin-ul în propriul portofel. Nu lăsa bitcoin-ul pe un exchange sau într-un wrapper precum un Bitcoin ETF.",
	"bank_runs_protect_content_3": "Consultă ghidul nostru simplu de portofele Bitcoin pentru a afla cum să retragi în propriul tău portofel.",
	"bank_runs_protect_content_4": "Cu Bitcoin, poți fi în sfârșit în controlul banilor tăi."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Ghid portofele Bitcoin",
	"wallets_description": "Există multe portofele Bitcoin diferite care diferă în moduri importante. Poți determina dacă un portofel este potrivit pentru tine punând aceste întrebări simple.",
	"wallets_header": "CUM SĂ STOCHEZI BITCOIN ÎN SIGURANȚĂ",
	"wallets_s1_c1": "Portofelele Bitcoin sunt interoperabile, deci poți trimite Bitcoin oricui indiferent de portofelul pe care îl folosesc.",
	"wallets_s1_c2": "Există multe portofele Bitcoin diferite care diferă în moduri importante. Poți determina dacă un portofel este potrivit pentru tine punând aceste întrebări simple:",
	"wallets_question_1": "ESTE UN PORTOFEL CU AUTO-CUSTODIE?",
	"wallets_s2_c1": "Una dintre inovațiile Bitcoin este capacitatea de a-l stoca fără a te baza pe un custod, precum o bancă.",
	"wallets_s2_c2": "Dacă deții bitcoin pe un exchange sau într-un ETF, pierzi beneficiile de libertate ale bitcoin.",
	"wallets_s2_c3": "Portofelele cu auto-custodie deblochează puterea completă a Bitcoin: bani liberi.",
	"wallets_s2_c4": "Cu un portofel cu auto-custodie, ești singura persoană cu capacitatea de a cheltui sau transfera banii tăi. Nimeni nu te poate opri din a trimite sau primi banii tăi când folosești un portofel cu auto-custodie.",
	"wallets_s2_c5": "Portofelele cu auto-custodie se mai numesc și portofele non-custodiale.",
	"wallets_s3_c1": "Portofelele custodiale sunt portofele în care nu ai controlul banilor tăi.",
	"wallets_s3_c2": "Aceste portofele sunt mai similare cu sistemul bancar unde trebuie să ai încredere într-o terță parte că îți va oferi acces la banii tăi. Dacă Bitcoin-ul tău este pe un exchange, folosești un portofel custodial.",
	"wallets_s3_c3": "Dacă ai cumpărat un Bitcoin ETF, folosești un portofel custodial care nu îți permite să retragi în auto-custodie.",
	"wallets_s3_c4": "Portofelele custodiale pot părea convenabile, dar custodul are capacitatea tehnică de a fura toate fondurile utilizatorilor în orice moment.",
	"wallets_s3_c5": "Nu cheile tale, nu monedele tale!",
	"wallets_question_2": "ESTE CALD SAU RECE?",
	"wallets_s4_c1": "Portofelele reci stochează cheile Bitcoin-ului tău într-un mod care nu le expune niciodată la internet.",
	"wallets_s4_c2": "Aceasta limitează semnificativ vectorii de atac pe care un hoț i-ar putea folosi pentru a încerca să îți fure Bitcoin-ul și este cel mai bine folosit pentru sume mari de Bitcoin pe care nu trebuie să le transferi des.",
	"wallets_s4_c3": "Poți gândi la un portofel rece ca la un cont de economii pe termen lung, cunoscut și sub numele de stocare la rece.",
	"wallets_s5_c1": "Portofelele calde stochează cheile Bitcoin-ului tău pe un dispozitiv conectat la internet, precum telefonul.",
	"wallets_s5_c2": "Portofelele calde sunt în general considerate sigure, dar ar putea avea mai multe vulnerabilități de securitate decât portofelele reci.",
	"wallets_s5_c3": "Poți gândi la un portofel cald ca la un portofel fizic. Nu ai stoca toate economiile într-un portofel, dar ai stoca ceva bani de cheltuială.",
	"wallets_s5_c4": "Portofelele calde fac mult mai ușor să cheltuiești Bitcoin fără a scoate toate economiile din stocarea la rece.",
	"wallets_question_3": "CUM VEI FACE BACKUP LA FRAZA DE RECUPERARE?",
	"wallets_s6_c1": "Când configurezi portofelul Bitcoin, dispozitivul tău va genera o frază de recuperare. Această frază de recuperare (numită și seed phrase) conține 12 sau 24 de cuvinte.",
	"wallets_s6_c2": "Dacă pierzi vreodată accesul la portofel sau dispozitivul tău nu mai funcționează, poți introduce această frază de recuperare într-un portofel nou pentru a recăpăta accesul la Bitcoin.",
	"wallets_s6_c3": "Majoritatea portofelelor includ o foaie de hârtie pentru a nota fraza de recuperare, dar mulți oameni preferă să facă backup pe oțel. Aceasta face mult mai puțin probabil să pierzi fraza de recuperare în cazul unui dezastru natural precum un incendiu sau o inundație.",
	"wallets_s6_c4": "Jameson Lopp a testat 70 de kituri de backup pe oțel pentru a te ajuta să alegi cel potrivit pentru tine.",
	"wallets_s6_c5": "Vezi ghidul de backup pe metal Bitcoin al lui Jameson aici.",
	"wallets_s6_c6": "Sau continuă să derulezi pentru a explora opțiunile de portofele Bitcoin.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "Cauți ghidul nostru de portofele Lightning?",
	"wallets_starter_wallet": "Portofel excelent pentru început",
	"wallets_mobile_app": "Aplicație mobilă",
	"wallets_2fa_support": "Suport 2FA",
	"wallets_air_gap_mode": "Mod air-gap",
	"wallets_air_gap_camera": "Mod air-gap + cameră",
	"wallets_bitcoin_only": "Doar Bitcoin",
	"wallets_security_features": "Multe funcții de securitate",
	"wallets_free": "100% gratuit",
	"wallets_coldcard_mk5_costs": "Costă 189 $",
	"wallets_coldcard_q_costs": "Costă 289 $",
	"wallets_blockstream_jade_costs": "Costă 79 $",
	"wallets_foundation_passport_costs": "Costă 199 $",
	"wallets_seedsigner_costs": "Piesele costă 50 $",
	"wallets_very_affordable": "Foarte accesibil",
	"wallets_pair_with_phone": "Conectare cu telefonul",
	"wallets_battery": "Baterie reîncărcabilă",
	"wallets_build_your_own": "Construiește-l singur",
	"wallets_qwerty_keyboard": "Tastatură QWERTY completă",
	"wallets_qr_scanner": "Scanner de coduri QR"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "Cum să cumperi Bitcoin - Ghid pas cu pas",
	"buy_header": "CUM SĂ CUMPERI BITCOIN",
	"buy_intro_c1": "Cumpărarea Bitcoin pentru prima dată poate părea copleșitoare, dar este de fapt destul de simplă când o împarți în pași.",
	"buy_intro_c2": "Acest ghid te va ghida prin procesul de cumpărare Bitcoin în siguranță și stocare în propriul tău portofel.",
	"buy_step_1_header": "PASUL 1: SELECTEAZĂ ȚARA TA",
	"buy_step_1_description": "Diferite țări au diferite opțiuni de cumpărare Bitcoin disponibile. Selectează țara ta pentru a vedea cele mai bune opțiuni pentru tine.",
	"buy_search_countries": "Caută țara ta",
	"buy_country_united_states": "Statele Unite",
	"buy_country_australia": "Australia",
	"buy_country_austria": "Austria",
	"buy_country_belgium": "Belgia",
	"buy_country_brazil": "Brazilia",
	"buy_country_canada": "Canada",
	"buy_country_france": "Franța",
	"buy_country_germany": "Germania",
	"buy_country_ireland": "Irlanda",
	"buy_country_italy": "Italia",
	"buy_country_netherlands": "Olanda",
	"buy_country_new_zealand": "Noua Zeelandă",
	"buy_country_spain": "Spania",
	"buy_country_united_kingdom": "Regatul Unit",
	"buy_country_argentina": "Argentina",
	"buy_country_chile": "Chile",
	"buy_country_colombia": "Columbia",
	"buy_country_costa_rica": "Costa Rica",
	"buy_country_czech_republic": "Republica Cehă",
	"buy_country_denmark": "Danemarca",
	"buy_country_el_salvador": "El Salvador",
	"buy_country_estonia": "Estonia",
	"buy_country_finland": "Finlanda",
	"buy_country_greece": "Grecia",
	"buy_country_guatemala": "Guatemala",
	"buy_country_hong_kong": "Hong Kong",
	"buy_country_hungary": "Ungaria",
	"buy_country_iceland": "Islanda",
	"buy_country_india": "India",
	"buy_country_israel": "Israel",
	"buy_country_japan": "Japonia",
	"buy_country_latvia": "Letonia",
	"buy_country_lithuania": "Lituania",
	"buy_country_luxembourg": "Luxemburg",
	"buy_country_malta": "Malta",
	"buy_country_mexico": "Mexic",
	"buy_country_norway": "Norvegia",
	"buy_country_panama": "Panama",
	"buy_country_poland": "Polonia",
	"buy_country_portugal": "Portugalia",
	"buy_country_romania": "România",
	"buy_country_singapore": "Singapore",
	"buy_country_slovakia": "Slovacia",
	"buy_country_slovenia": "Slovenia",
	"buy_country_south_africa": "Africa de Sud",
	"buy_country_south_korea": "Coreea de Sud",
	"buy_country_sweden": "Suedia",
	"buy_country_switzerland": "Elveția",
	"buy_country_thailand": "Thailanda",
	"buy_country_turkey": "Turcia",
	"buy_country_ukraine": "Ucraina",
	"buy_country_uruguay": "Uruguay",
	"buy_step_2_header": "PASUL 2: ALEGE METODA DE PLATĂ",
	"buy_step_2_description": "Există două moduri principale de a cumpăra Bitcoin: cu transfer bancar sau cu numerar. Fiecare are avantaje diferite.",
	"buy_method_bank_transfer": "TRANSFER BANCAR",
	"buy_method_bank_fast": "Rapid și ușor",
	"buy_method_bank_less_private": "Mai puțin privat",
	"buy_method_bank_description": "Transferurile bancare sunt cel mai comun mod de a cumpăra Bitcoin. Sunt rapide, convenabile și au de obicei comisioane mai mici.",
	"buy_method_choose_bank": "Alege transfer bancar",
	"buy_method_cash": "NUMERAR",
	"buy_method_cash_private": "Mai privat",
	"buy_method_cash_limited": "Opțiuni limitate",
	"buy_method_cash_description": "Achizițiile cu numerar oferă mai multă confidențialitate, dar au mai puține opțiuni și pot necesita întâlnirea cu cineva în persoană sau utilizarea unui ATM Bitcoin.",
	"buy_method_choose_cash": "Alege numerar",
	"buy_step_3_header": "PASUL 3: OPȚIUNI DE CUMPĂRARE",
	"buy_step_3_description": "Iată cele mai bune opțiuni de cumpărare Bitcoin pentru țara și metoda ta de plată:",
	"buy_platform_recommended": "RECOMANDAT",
	"buy_platform_strike_description": "Strike este cel mai rapid și mai ușor mod de a cumpăra Bitcoin cu comisioane mici și suport instantaneu pentru rețeaua Lightning.",
	"buy_platform_swan_description": "Swan Bitcoin se specializează în servicii exclusiv Bitcoin cu investiții periodice și resurse educaționale.",
	"buy_platform_river_description": "River oferă cumpărare Bitcoin, minerit și servicii de custodie cu accent pe educație și securitate.",
	"buy_platform_coinsquare_description": "Coinsquare este un exchange Bitcoin canadian cu conformitate regulatorie puternică și suport pentru clienți.",
	"buy_platform_kraken_description": "Kraken este un exchange Bitcoin consacrat cu funcții avansate de tranzacționare și securitate puternică.",
	"buy_platform_atm_description": "ATM-urile Bitcoin îți permit să cumperi Bitcoin cu numerar instantaneu. Găsește unul aproape de tine folosind Coin ATM Radar.",
	"buy_platform_bisq_description": "Bisq este un exchange descentralizat peer-to-peer care permite tranzacționarea privată de Bitcoin fără KYC.",
	"buy_platform_feature_instant": "Achiziții instantanee",
	"buy_platform_feature_low_fees": "Comisioane mici",
	"buy_platform_feature_lightning": "Rețeaua Lightning",
	"buy_platform_feature_dca": "Investiții periodice",
	"buy_platform_feature_education": "Resurse educaționale",
	"buy_platform_feature_withdrawal": "Retragere ușoară",
	"buy_platform_feature_mining": "Minerit Bitcoin",
	"buy_platform_feature_custody": "Servicii de custodie",
	"buy_platform_feature_canadian": "Focalizat pe Canada",
	"buy_platform_feature_regulated": "Exchange reglementat",
	"buy_platform_feature_support": "Suport clienți",
	"buy_platform_feature_established": "Platformă consacrată",
	"buy_platform_feature_security": "Securitate puternică",
	"buy_platform_feature_advanced": "Funcții avansate",
	"buy_platform_feature_cash": "Achiziții cu numerar",
	"buy_platform_feature_anonymous": "Mai anonim",
	"buy_platform_feature_p2p": "Peer-to-peer",
	"buy_platform_feature_private": "Tranzacționare privată",
	"buy_platform_feature_decentralized": "Descentralizat",
	"buy_platform_relai_description": "Relai este o aplicație elvețiană exclusiv Bitcoin cu portofel auto-custodie, funcții de investiție automată și comisioane mici pentru utilizatorii europeni.",
	"buy_platform_feature_bitcoin_only": "Doar Bitcoin",
	"buy_platform_feature_self_custody": "Portofel auto-custodie",
	"buy_platform_feature_auto_invest": "Planuri de investiție automată",
	"buy_platform_feature_european": "Focalizat pe Europa",
	"buy_step_4_header": "PASUL 4: STOCHEAZĂ BITCOIN ÎN SIGURANȚĂ",
	"buy_step_4_c1": "După cumpărarea Bitcoin, cel mai important pas este să îl muți în propriul tău portofel unde controlezi cheile private.",
	"buy_step_4_c2": "A lăsa Bitcoin pe un exchange este riscant deoarece nu deții de fapt Bitcoin-ul — exchange-ul îl deține.",
	"buy_step_4_c3": "Când controlezi propriile chei private, ai proprietate reală asupra Bitcoin-ului tău și nimeni nu ți-l poate lua.",
	"buy_step_4_c4": "Află cum să alegi portofelul Bitcoin potrivit pentru nevoile tale:",
	"buy_cta_wallets": "Vezi ghidul nostru de portofele Bitcoin"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Ghid portofele Bitcoin Lightning",
	"lightning_description": "Portofelele Lightning îți permit să trimiți Bitcoin rapid și ieftin, menținând în același timp suveranitatea personală.",
	"lightning_header": "GHID PORTOFELE LIGHTNING",
	"lightning_s1_c1": "Lightning îți permite să trimiți plăți Bitcoin rapid și ieftin.",
	"lightning_s1_c2": "Este important să știi că utilizarea Lightning vine cu compromisuri. În schimbul plăților Bitcoin mai rapide și mai ieftine, sacrifici adesea o parte din securitate.",
	"lightning_s1_c3": "În general, Lightning ar trebui folosit doar cu sume mici de bitcoin. Ar trebui să stochezi sume mari de bitcoin doar într-un portofel hardware.",
	"lightning_s1_c4": "Consultă ghidul nostru de portofele hardware pentru mai multe informații.",
	"lightning_s1_c5": "Nu toate portofelele Lightning sunt la fel. Poți determina care portofel are setul potrivit de compromisuri pentru tine punând o simplă întrebare:",
	"lightning_question_1": "CE ECHILIBRU DE COMPROMISURI ESTE POTRIVIT PENTRU MINE?",
	"lightning_s2_c1": "Una dintre inovațiile Bitcoin este capacitatea de a-l stoca fără a te baza pe un custod, precum o bancă. Portofelele cu auto-custodie deblochează puterea completă a Bitcoin.",
	"lightning_s2_c2": "Cu un portofel cu auto-custodie, ești singura persoană cu capacitatea de a cheltui sau transfera banii tăi. Nimeni nu te poate opri, cenzura sau fura de la tine când folosești un portofel cu auto-custodie. Acestea se mai numesc și portofele non-custodiale.",
	"lightning_s2_c3": "Cel mai suveran mod de a folosi Lightning este prin rularea propriului nod.",
	"lightning_s2_c4": "Acest ghid se concentrează pe portofele Lightning simple care nu necesită propriul nod.",
	"lightning_s2_c5": "Este important de știut că, chiar și folosind un portofel Lightning non-custodial, ai încredere în creatorul portofelului că nu va trimite o actualizare malițioasă a aplicației și nu îți va fura fondurile.",
	"lightning_s3_c1": "Portofelele custodiale sunt portofele în care nu ai controlul banilor tăi.",
	"lightning_s3_c2": "Aceste portofele sunt mai similare cu sistemul bancar unde trebuie să ai încredere într-o terță parte că îți va oferi acces la banii tăi. Dacă Bitcoin-ul tău este pe un exchange, folosești un portofel custodial.",
	"lightning_s3_c3": "Portofelele custodiale pot părea convenabile, dar custodul are capacitatea tehnică de a fura toate fondurile utilizatorilor în orice moment.",
	"lightning_s3_c4": "Unii oameni preferă portofelele Lightning custodiale pentru sume mici de bitcoin datorită ușurinței în utilizare. Ține minte: nu cheile tale, nu monedele tale!",
	"lightning_question_2": "ALEGE-ȚI PORTOFELUL",
	"lightning_s4_c1": "Cu toate acestea în minte, acum poți alege portofelul Lightning care are echilibrul potrivit de compromisuri pentru tine.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "Multe funcționalități",
	"lightning_mobile_app": "Aplicație mobilă",
	"lightning_free": "100% gratuit",
	"lightning_merchants": "Excelent pentru comercianți",
	"lightning_starter": "Portofel excelent pentru început",
	"lightning_browser": "Bazat pe browser",
	"lightning_custodial": "Portofel complet custodial",
	"lightning_cta_hardware": "Cauți ghidul nostru de portofele hardware Bitcoin?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "Autocolante Bitcoin gratuite de la bitcoin.rocks",
	"stickers_description": "Pune un autocolant Bitcoin în public pentru a face orange pill celor din jurul tău.",
	"stickers_header": "AUTOCOLANTE BITCOIN GRATUITE",
	"stickers_choose_header": "ALEGE PACHETUL TĂU DE AUTOCOLANTE",
	"stickers_choose_c1": "Misiunea noastră este de a te ajuta să faci orange pill mai mulți oameni punând autocolante Bitcoin în locuri publice. Toate autocolantele noastre au coduri QR care fac trimitere la pagini educative despre",
	"stickers_choose_c2": "Bitcoin",
	"stickers_choose_c3": "inflație",
	"stickers_choose_c4": "Alege pachetul tău de autocolante de mai jos",
	"stickers_text_pack": "PACHETUL TEXT",
	"stickers_signs_pack": "PACHETUL SEMNE",
	"stickers_instructions_1": "Introdu adresa ta poștală și îți vom trimite un Pachet de Autocolante Bitcoin gratuit prin poștă! Autocolantele tale vor fi livrate într-un plic alb simplu.",
	"stickers_instructions_2": "Datele adresei sunt șterse după expedierea autocolantelor gratuite.",
	"stickers_share_header": "DISTRIBUIE LOCAȚIILE AUTOCOLANTELOR TALE",
	"stickers_share_c1": "Distribuie locațiile autocolantelor tale cu noi pe Nostr și vezi unde alți oameni își pun autocolantele.",
	"stickers_btn_share_on_nostr": "DISTRIBUIE PE NOSTR",
	"stickers_btn_what_is_nostr": "CE ESTE NOSTR?",
	"stickers_flyers_link_before": "Între timp, tipărește și lipește propriii tăi ",
	"stickers_flyers_link_text": "fluturași Bitcoin",
	"stickers_flyers_link_after": " pentru a face orange pill și mai mulți oameni.",
	"stickers_country_global_print": "Global — Îmi tipăresc propriile autocolante",
	"stickers_country_global_order": "Global — Comand în cantitate mare",
	"placeholder_name_optional": "Nume (opțional)",
	"placeholder_address_line_1": "Adresa linia 1",
	"placeholder_address_line_2": "Adresa linia 2 (opțional)",
	"placeholder_city": "Oraș",
	"placeholder_state": "Stat",
	"placeholder_province": "Provincie",
	"placeholder_zip_code": "Cod poștal",
	"placeholder_postal_code": "Cod poștal",
	"placeholder_language": "Limba",
	"placeholder_which_stickers": "Ce autocolante?",
	"placeholder_email_optional": "Introdu email-ul pentru a fi notificat (opțional)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "Cărți poștale Bitcoin gratuite de la bitcoin.rocks",
	"postcards_description": "Obține un pachet gratuit de cărți poștale Bitcoin și distribuie Bitcoin cuiva pe care îl cunoști.",
	"postcards_header": "PROGRAMUL DE CĂRȚI POȘTALE ÎNCHIS",
	"postcards_program_closed_message": "Programul nostru gratuit de cărți poștale Bitcoin s-a încheiat. Mulțumim tuturor celor care au participat la răspândirea educației Bitcoin prin poștă!",
	"postcards_sticker_alternative_header": "OBȚINE AUTOCOLANTE BITCOIN GRATUITE ÎN SCHIMB",
	"postcards_sticker_alternative_message": "Continuă să răspândești conștientizarea Bitcoin cu programul nostru gratuit de autocolante! Autocolantele noastre Bitcoin sunt perfecte pentru distribuirea în spații publice și vin cu coduri QR care fac trimitere la conținut educativ.",
	"postcards_sticker_cta": "OBȚINE AUTOCOLANTE GRATUITE",
	"postcards_step_2": "CUM ARĂTAU CĂRȚILE POȘTALE",
	"postcards_instructions_4": "Am făcut aceste cărți poștale pentru a facilita introducerea cuiva pe care îl cunoști în Bitcoin! Adaugă doar o adresă și un timbru și aruncă cartea poștală în cutia poștală.",
	"postcards_instructions_5": "Misiunea noastră este de a accelera adoptarea Bitcoin. Poți ajuta obținând autocolante gratuite și punându-le în spații publice!",
	"postcards_instructions_6": "Toți cunoaștem câțiva oameni care ar beneficia de a afla mai multe despre Bitcoin. Distribuie autocolante Bitcoin cu ei astăzi!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "Ajută-ne să punem aceste Panouri Bitcoin în toată America!",
	"signs_title": "Panouri Bitcoin gratuite de la bitcoin.rocks",
	"signs_choose_header": "MULȚUMIM CĂ NE-AI AJUTAT SĂ PUNEM ACESTE PANOURI BITCOIN ÎN TOATĂ AMERICA!",
	"signs_choose_c1": "Acum nu mai avem panouri! Misiunea noastră este de a accelera adoptarea Bitcoin prin educație.",
	"signs_choose_c2": "Mulți dintre voi ați ajutat punând aceste panouri Bitcoin gratuite în public. Toate panourile noastre au coduri QR care fac trimitere la o pagină educativă despre",
	"signs_choose_c3": "inflație",
	"signs_choose_c4": "Datorită comunității noastre extraordinare, am ajuns la mii de oameni și i-am ajutat să facă primii pași în lumea Bitcoin.",
	"signs_share_header": "DISTRIBUIE LOCAȚIILE PANOURILOR TALE",
	"signs_share_c1": "Distribuie o fotografie cu locația panoului tău pe Nostr și vezi unde alți oameni își pun panourile.",
	"signs_btn_share_on_nostr": "DISTRIBUIE PE NOSTR",
	"signs_btn_what_is_nostr": "CE ESTE NOSTR?",
	"signs_instructions_1": "Introdu adresa ta poștală și îți vom trimite o cutie de 10 panouri Bitcoin prin poștă!",
	"signs_instructions_2": "Datele adresei sunt șterse după expedierea panourilor gratuite."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "Fluturași Bitcoin gratuite de la bitcoin.rocks",
	"flyers_description": "Tipărește un fluturaș Bitcoin acasă și pune-l în public pentru a face orange pill celor din jurul tău.",
	"flyers_header_1": "TIPĂREȘTE ȘI LIPEȘTE",
	"flyers_header_2": "FLUTURAȘI BITCOIN",
	"flyers_intro_header": "CUM SĂ TIPĂREȘTI ȘI LIPEȘTI ACEȘTI FLUTURAȘI BITCOIN",
	"flyers_intro_c1": "Misiunea noastră este de a te ajuta să faci orange pill mai mulți oameni punând fluturași Bitcoin în public. Acest fluturaș are un cod QR care face trimitere la",
	"flyers_intro_c2": "site-ul nostru educativ Bitcoin.",
	"flyers_intro_c3": "inflație",
	"flyers_intro_c4": "Tipărește acest fluturaș acasă sau la o tipografie. Apoi, lipește-l pe panouri de anunțuri, stâlpi de telefon din oraș și alte spații publice unde oamenii îl pot vedea și învăța despre Bitcoin.",
	"flyers_intro_c5": "Între timp, solicită un pachet din",
	"flyers_intro_c6": "autocolantele noastre Bitcoin gratuite",
	"flyers_intro_c7": "pentru a face orange pill și mai mulți oameni.",
	"flyers_btn_download": "DESCARCĂ FLUTURAȘUL",
	"flyers_btn_print": "TIPĂREȘTE FLUTURAȘUL",
	"flyers_share_header": "DISTRIBUIE LOCAȚIILE FLUTURAȘELOR TALE",
	"flyers_share_c1": "Distribuie locațiile fluturașelor tale cu noi pe Nostr și vezi unde alți oameni își pun fluturașele.",
	"flyers_btn_share_on_nostr": "DISTRIBUIE PE NOSTR",
	"flyers_btn_what_is_nostr": "CE ESTE NOSTR?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "Implică-te și ajută la răspândirea Bitcoin",
	"get_involved_description": "Resursele noastre gratuite facilitează răspândirea adoptării Bitcoin.",
	"get_involved_header": "IMPLICĂ-TE",
	"get_involved_header_2": "RĂSPÂNDEȘTE BITCOIN",
	"get_involved_intro_1": "Poate fi deprimant să trăiești în starea actuală a lumii noastre.",
	"get_involved_intro_2": "Banii noștri sunt stricați. Ca rezultat, piese fundamentale ale societății sunt stricatetde asemenea.",
	"get_involved_intro_3": "Dacă ești deja în Bitcoin, cunoști sentimentul de speranță pe care Bitcoin îl poate aduce. Speranță pentru un viitor mai luminos făcut posibil de bani mai buni.",
	"get_involved_intro_4": "Dar atât de mulți oameni din jurul tău nu știu despre Bitcoin. Trăiesc în aceeași lume stricată ca tine, dar fără un far de speranță care să îi ajute prin întuneric.",
	"get_involved_intro_5": "Dar tu poți ajuta să schimbi asta. Am creat mai multe resurse gratuite pentru a facilita răspândirea speranței pe care Bitcoin o aduce celor din jurul tău.",
	"get_involved_sticker_header": "Pune un autocolant în public",
	"get_involved_sticker_content_1": "Poți ajuta la educarea celor din jurul tău despre Bitcoin fără a interacționa cu cineva. Pur și simplu pune unul dintre autocolantele noastre Bitcoin gratuite în public.",
	"get_involved_sticker_content_2": "Sute de oameni scanează codurile QR de pe aceste autocolante în fiecare lună. Autocolantele cu inflație fac trimitere la o pagină despre",
	"get_involved_sticker_content_3": "Bitcoin ca soluție la inflație.",
	"get_involved_sticker_content_4": "Celelalte autocolante fac trimitere la pagina noastră educativă principală care arată oamenilor cum",
	"get_involved_sticker_content_5": "Bitcoin construiește o lume mai bună.",
	"get_involved_sticker_content_6": "Punând aceste autocolante în comunitatea ta în locuri unde oamenii le vor vedea, poți ajuta pe cei din jurul tău să facă primii pași în lumea Bitcoin.",
	"get_involved_request_a": "SOLICITĂ UN",
	"get_involved_sticker_pack": "PACHET DE AUTOCOLANTE",
	"get_involved_postcard_header": "Trimite o carte poștală",
	"get_involved_postcard_content_1": "Poți ajuta la răspândirea speranței Bitcoin cuiva pe care îl cunoști trimițându-i una dintre cărțile noastre poștale gratuite.",
	"get_involved_postcard_content_2": "Spatele fiecărei cărți poștale conține un text convingător despre Bitcoin împreună cu un cod QR pentru a afla mai multe.",
	"get_involved_postcard_content_3": "Trimițând cuiva o carte poștală Bitcoin, îl poți ajuta să vadă Bitcoin dintr-o perspectivă nouă.",
	"get_involved_postcard_pack": "PACHET DE CĂRȚI POȘTALE",
	"get_involved_business_header": "Integrează o afacere",
	"get_involved_business_content_1": "Vrei să ajuți la construirea economiei circulare Bitcoin? Kitul nostru Bitcoin pentru Afaceri facilitează abordarea unei afaceri despre acceptarea plăților Bitcoin.",
	"get_involved_business_content_2": "Fiecare kit de afaceri include fluturași care evidențiază avantajele acceptării plăților Bitcoin. Fiecare fluturaș face trimitere la o varietate de",
	"get_involved_business_content_3": "resurse gratuite Bitcoin pentru afaceri.",
	"get_involved_business_kit": "KIT DE AFACERI"
});

console.log('\nDone! Content files created for Romanian (ro).');
