/**
 * Creates Romanian (ro) index.json translation file (~130+ keys)
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ro';
const today = '2026-04-11';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"bitcoin_builds_a_better_world": "Bitcoin construiește o lume mai bună.",
	"home_description": "Bitcoin sunt bani mai buni care construiesc o lume mai bună. Bitcoin a protejat drepturile omului, a salvat oameni de inflația ridicată, a sprijinit fermierii locali, a redus emisiile de la forarea petrolului și multe altele.",
	"home_intro": "Bitcoin sunt bani mai buni care construiesc o lume mai bună. Apasă pe o categorie de mai jos pentru a afla cum Bitcoin o face mai bună, sau doar derulează în jos pentru a explora.",
	"home_btn_money": "BANI MAI BUNI",
	"home_btn_salary": "SALARIUL TĂU",
	"home_btn_freedom": "LIBERTATE",
	"home_btn_human_rights": "DREPTURILE OMULUI",
	"home_btn_equality": "EGALITATE",
	"home_btn_property_rights": "DREPTUL DE PROPRIETATE",
	"home_btn_housing": "LOCUINȚE",
	"home_btn_business": "AFACERI",
	"home_btn_crowdfunding": "CROWDFUNDING",
	"home_btn_energy": "ENERGIE",
	"home_btn_environment": "MEDIUL",
	"home_btn_food": "ALIMENTE",
	"home_btn_art": "ARTĂ",
	"home_btn_politics": "POLITICĂ",
	"home_btn_war": "RĂZBOI",
	"home_btn_coding": "PROGRAMARE",
	"home_btn_networks": "REȚELE",
	"home_btn_payments": "PLĂȚI",
	"home_btn_self_custody": "AUTO-CUSTODIE",
	"home_btn_you": "TU",
	"home_section_bitcoin_is": "BITCOIN ESTE",
	"home_section_bitcoin_and": "BITCOIN ȘI",
	"home_link_type_website": "SITE WEB",
	"home_link_type_video": "VIDEO",
	"home_link_type_article": "ARTICOL",
	"home_link_type_podcast": "PODCAST",
	"home_link_type_business_kit": "KIT DE AFACERI",
	"home_link_type_data": "DATE",
	"home_link_type_research": "CERCETARE",
	"home_link_type_story": "POVESTE",
	"home_link_type_book_excerpt": "EXTRAS DE CARTE",
	"home_link_type_street_art": "ARTĂ STRADALĂ",
	"home_link_type_outreach": "INFORMARE",
	"home_link_type_campaign": "CAMPANIE",
	"home_link_type_software": "SOFTWARE",
	"home_link_type_hardware": "HARDWARE",
	"home_link_type_guide": "GHID",
	"home_link_type_email": "EMAIL",
	"home_link_title_inflation": "Bitcoin nu are inflație",
	"home_link_title_bank_runs": "Bitcoin nu are crize bancare",
	"home_link_title_gold": "Bitcoin vs Aur",
	"home_link_title_crypto": "Bitcoin vs Crypto",
	"home_link_title_cash": "Bitcoin vs Numerar",
	"home_link_title_bonds": "Bitcoin vs Obligațiuni",
	"home_link_title_cbdc": "Bitcoin vs CBDC-uri",
	"home_link_title_your_salary_1": "Află cât trebuie să crească salariul tău pentru a ține pasul cu inflația.",
	"home_link_title_freedom_1": "De ce contează Bitcoin pentru libertate",
	"home_link_title_freedom_2": "Bitcoin oferă libertate de reprimarea politică",
	"home_link_title_human_rights_1": "Cum impune Bitcoin drepturile omului",
	"home_link_title_human_rights_2": "Revoluția tăcută Bitcoin din Africa",
	"home_link_title_human_rights_3": "Bitcoin protejează drepturile omului în întreaga lume",
	"home_link_title_equality_1": "Bitcoin aduce speranță și oportunități sud-africanilor",
	"home_link_title_equality_2": "Cum poate Bitcoin schimba situația pentru afro-americani",
	"home_link_title_property_rights_1": "Bitcoin este forma perfectă de proprietate",
	"home_link_title_property_rights_2": "Bitcoin vs Imobiliare",
	"home_link_title_housing_1": "Cum va face Bitcoin locuințele din nou accesibile",
	"home_link_title_business_3": "Bitcoin vs Acțiuni",
	"home_link_title_business_1": "Află de ce Bitcoin este bun pentru afaceri",
	"home_link_title_business_2": "Convinge o afacere locală să accepte Bitcoin",
	"home_link_title_crowdfunding_1": "Cum a alimentat Bitcoin cele mai mari proteste nigeriene dintr-o generație",
	"home_link_title_crowdfunding_2": "Protestul camioniștilor canadieni strânge bani în Bitcoin după ce GoFundMe blochează donațiile",
	"home_link_title_crowdfunding_3": "Geyser = Crowdfunding cu Bitcoin",
	"home_link_title_energy_1": "Cum stabilizează Bitcoin rețeaua electrică din Texas",
	"home_link_title_energy_2": "De ce folosește Bitcoin energie?",
	"home_link_title_energy_3": "Consumul de energie al Bitcoin nu este o problemă. Iată de ce.",
	"home_link_title_energy_4": "Mineritul Bitcoin stabilizează rețelele energetice prin Răspunsul la Cerere",
	"home_link_title_energy_5": "Minerii Bitcoin aduc energie hidroelectrică comunităților rurale africane",
	"home_link_title_energy_6": "Cum stimulează Bitcoin energia regenerabilă",
	"home_link_title_environment_1": "Cum reduce mineritul Bitcoin emisiile globale de metan",
	"home_link_title_environment_2": "Cum a salvat mineritul Bitcoin un Parc Național",
	"home_link_title_environment_3": "Bitcoin este cea mai verde industrie de pe Pământ!",
	"home_link_title_environment_4": "Mineritul Bitcoin previne poluarea atmosferei cu gaz natural ars",
	"home_link_title_food_1": "Cum afectează inflația prețurile alimentelor",
	"home_link_title_food_2": "Cum sunt banii fiat dăunători pentru alimente, ferme și solul Pământului",
	"home_link_title_fine_art": "Bitcoin vs Artă",
	"home_link_title_art_1": "Alătură-te inițiativei noastre de autocolante Bitcoin",
	"home_link_title_art_2": "Trimite o carte poștală Bitcoin cuiva pe care îl cunoști",
	"home_link_title_art_3": "Tipărește și lipește fluturași Bitcoin",
	"home_link_title_politics_1": "Bitcoin este un paradox politic",
	"home_link_title_politics_2": "Poți vota pentru bani mai buni",
	"home_link_title_war_1": "Cum ar putea Bitcoin pune capăt războaielor nesfârșite",
	"home_link_title_war_2": "Bitcoin și Veteranii: O aliniere naturală",
	"home_link_title_war_3": "Cum îi ajută Bitcoin pe civili să scape din războiul din Sudan",
	"home_link_title_coding_1": "Un tutorial interactiv despre partea tehnică a Bitcoin",
	"home_link_title_coding_2": "bitcoinSwitch: transformă orice dispozitiv să accepte Bitcoin",
	"home_link_title_coding_3": "Programează-ți drumul prin misterele Bitcoin",
	"home_link_title_networks_1": "O vizualizare în timp real a rețelei Bitcoin",
	"home_link_title_networks_2": "Bitcoin vs Bănci",
	"home_link_title_payments_1": "Bitcoin vs Visa",
	"home_link_title_payments_2": "O privire asupra rețelei Lightning (Plăți Bitcoin instantanee)",
	"home_link_title_payments_3": "Portofelul Bitcoin al El Salvador ar putea economisi salvadorienilor 400M$ anual în comisioane de remitențe",
	"home_link_title_payments_4": "Obține adresa ta Lightning pentru a primi plăți Bitcoin instantanee",
	"home_link_title_self_custody_1": "Cum să stochezi Bitcoin-ul în siguranță",
	"home_link_title_self_custody_2": "6 motive să îți retragi Bitcoin-ul de pe exchange-uri",
	"home_link_title_self_custody_3": "Aur, Bitcoin și auto-custodia",
	"home_link_title_get_started_1": "Învață bazele Bitcoin",
	"home_link_title_get_started_2": "Obține primul tău portofel Bitcoin",
	"home_link_title_get_started_3": "Cum să cumperi Bitcoin",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Calculator de Inflație Compusă",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! index.json created for Romanian (ro).');
