/**
 * Creates Amharic (am) common.json translation file (~180+ keys).
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'am';
const today = '2026-04-06';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"common_footer_mission_1": "bitcoin.rocks ተልዕኮ በትምህርት አማካኝነት የቢትኮይን ተቀባይነትን ማፋጠን ነው።",
	"common_footer_mission_2": "ለዚህ ክፍት ምንጭ ፕሮጀክት እንዴት ማበርከት እንደሚችሉ ይወቁ።",
	"common_footer_follow_first_half": "በNostr ክላይንት ላይ",
	"common_footer_follow_second_half": "ን ፈልገው ይከተሉ።",
	"common_footer_what_is_nostr": "Nostr ምንድን ነው?",
	"common_footer_about": "ስለ እኛ",
	"common_footer_email_us": "ኢሜይል፡",
	"common_cta_section_get_started": "ይጀምሩ",
	"common_cta_section_with_bitcoin": "ከቢትኮይን ጋር",
	"common_cta_section_title_1": "የቢትኮይን መሰረታዊ ነገሮችን ይማሩ",
	"common_cta_section_title_1_alt": "ስለ ቢትኮይን ተጨማሪ ይወቁ",
	"common_cta_section_title_2": "የመጀመሪያ ቢትኮይን ቦርሳዎን ይፍጠሩ",
	"common_cta_section_title_3": "ቢትኮይን እንዴት መግዛት እንደሚቻል",
	"common_cta_link_type_email": "ኢሜይል",
	"common_cta_link_type_guide": "መመሪያ",
	"common_cta_link_type_website": "ድር ጣቢያ",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "ቢትኮይን ምንድን ነው?",
	"common_what_is_bitcoin_content_1": "ቢትኮይን ሁለት ነገሮች ነው: ዲጂታል ገንዘብ እና የክፍያ ኔትወርክ። የቢትኮይን ኔትወርክን (የክፍያ ኔትወርክ) ተጠቅመው ቢትኮይንን (ዲጂታል ገንዘብ) ለሌላ ሰው ቀጥታ መላክ ይችላሉ።",
	"common_what_is_bitcoin_content_2": "ቢትኮይን ዋጋ ለማከማቸት እና ለመገበያየት መሰረታዊ አዲስ መንገድ ነው። ከተለምዷዊ የፋይናንስ ኔትወርኮች በተለየ የቢትኮይን ኔትወርክ ያለ ማዕከላዊ ባለስልጣን ወይም ታማኝ ተዳዳሪ ይሰራል። ይህ ቢትኮይንን በታሪክ ውስጥ የመጀመሪያው ክፍት እና ድንበር-አልባ ገንዘብ ያደርገዋል።",
	"common_what_is_bitcoin_content_3": "ቢትኮይን በሀብትዎ ላይ ሙሉ ባለቤትነት የሚሰጥ ዲጂታል ገንዘብ ነው። በሰው ልጅ ታሪክ ውስጥ ለመጀመሪያ ጊዜ ማንም ሰው በእውነት ያልተለመደ፣ ለመጠቀም ፍቃድ የማያስፈልገው እና በትክክል ከተቀመጠ ሊቀማ የማይችል ንብረት ሊይዝ ይችላል።",
	"common_what_is_bitcoin_content_4": "ቢትኮይን ያለ ባንክ ያሉ ሶስተኛ ወገን አማላጆች ወደ ዓለም ማንኛውም ቦታ በፍጥነት እና በዝቅተኛ ክፍያ ይላካል።",
	"common_what_is_bitcoin_content_5": "በቢትኮይን መንግስት ሊሰርቅ ወይም ገንዘብ በማተም ዋጋ ሊቀንስ ሳይችል ሀብትዎን በደህንነት ማከማቸት ይችላሉ።",
	"common_what_is_bitcoin_content_6": "በዓለም ማንኛውም ቦታ መንግስታት ተጨማሪ ወረቀት ገንዘብ ያትማሉ ግን ማንም ተጨማሪ ቢትኮይን ሊያመርት አይችልም።",
	"common_what_is_bitcoin_content_7": "ቢትኮይንዎን ራስ-ጠባቂ በማድረግ ሙሉ በሙሉ ይቆጣጠሩ እና የቢትኮይን ሙሉ ኃይል ያግኙ።",
	"common_what_is_bitcoin_content_8": "መተግበሪያ ማውረድ ከቻሉ ቢትኮይንዎን ራስ-ጠባቂ ማድረግ ይችላሉ ሀብትዎን ከሌላ ማንም ሰው ነጻ ሆኖ ያከማቹ።",
	"common_what_is_bitcoin_content_9": "ቢትኮይን የተሻለ ገንዘብ ነው።",
	"common_bitcoin_volatile": "ቢትኮይን ተለዋዋጭ ነው ተባለ፣ ደህንነቱ የተጠበቀ ነው?",
	"common_bitcoin_volatile_content_1": "በአጭር ጊዜ የቢትኮይን ምንዛሪ ተመን ይለዋወጣል። ይህ ተለዋዋጭነት ይባላል።",
	"common_bitcoin_volatile_content_2": "ግን ዕለታዊ የሚያዩት ተለዋዋጭነት በረጅም ጊዜ 'ይጠፋል'።",
	"common_bitcoin_volatile_content_3": "ቢትኮይን ከጊዜ ወደ ጊዜ ያነሰ ተለዋዋጭ ይሆናል። ብዙ ሰዎች ቢትኮይንን ለረጅም ጊዜ ቁጠባ ሲጠቀሙ ዋጋው ይበልጥ ተረጋግቷል።",
	"common_bitcoin_volatile_content_4": "ብዙ ሰዎች የተለዋዋጭነት አደጋን ለመቀነስ እና ከጊዜ ጋር ግዢ ኃይል ለመጠበቅ ደህንነቱ የተጠበቀ መንገድ ሆኖ ለዓመታት ዋጋን በቢትኮይን ያከማቹ።",
	"common_bitcoin_volatile_content_5": "በቬኔዙዌላ፣ ሱዳን፣ ሊባኖስ፣ ሶርያ፣ አርጀንቲና፣ ቱርክ፣ ብራዚል እና ሌሎች ብዙ አገራት አካባቢ ገንዘቡ ዋጋ በፍጥነት ይቀንሳል ቢትኮይን ገንዘብ ለመቆጠብ የተረጋጋ መንገድ ተደርጎ ይወሰዳል።",
	"common_bitcoin_afford": "ሙሉ ቢትኮይን መግዛት አልችልም",
	"common_bitcoin_afford_content_1": "1 ዶላር 100 ሳንቲም እንዳለው 1 ቢትኮይን 100,000,000 (አንድ መቶ ሚሊዮን) ሳቶሺ አለው።",
	"common_bitcoin_afford_content_2": "ሙሉ ቢትኮይን መያዝ አያስፈልግም። አብዛኛው ሰዎች ሳቶሺ ብቻ ይይዛሉ። ሳቶሺ የቢትኮይን ክፍልፋዮች ናቸው። ለምሳሌ 1 ቢትኮይን $100,000 ከሆነ $1 ለ1,000 ሳቶሺ ይገዛሉ!",
	"common_bitcoin_hacked": "ቢትኮይን ተጠልፎ ያውቃል?",
	"common_bitcoin_hacked_content_1": "በመስመር ላይ ወይም ዜና ላይ ስለ 'ቢትኮይን ጠለፋ' ሰምተው ሊሆን ይችላል። አብዛኛው ሰዎች ይህን ሲያነቡ የቢትኮይን ኔትወርክ ተጠልፏል ብለው ያምናሉ። ግን የቢትኮይን ኔትወርክ ፈፅሞ አልተጠለፈም።",
	"common_bitcoin_hacked_content_2": "የቢትኮይን ኔትወርክ ምንድን ነው? የቢትኮይን ኔትወርክን እንደ ባቡር ሐዲድ ያስቡ። በቢትኮይን ኔትወርክ ሐዲድ ላይ የሚሮጡ ባቡሮች የቢትኮይን ግብይቶች ናቸው።",
	"common_bitcoin_hacked_content_3": "ዜና ላይ ስለ ቢትኮይን ጠለፋ ሲያነቡ እንደ FTX ያሉ ተጠባባቂዎች ተጠልፈዋል ወይም ወድቀዋል የሚለውን ነው።",
	"common_bitcoin_hacked_content_4": "ተጠባባቂ ቢትኮይንዎን ለእርስዎ ይይዝልዎታል ግን አደጋ አለው: ኩባንያው ስህተት ቢሰራ፣ ቢሰርቅ ወይም ቢዘጋ ቢትኮይንዎን ያጣሉ።",
	"common_bitcoin_hacked_content_5": "ይህ በቅርቡ FTX ላይ ተከስቷል።",
	"common_bitcoin_hacked_content_6": "ቢትኮይናቸውን FTX ላይ ያስቀመጡ ሁሉ ቢትኮይናቸውን አጡ። ቢትኮይናቸውን ራስ-ጠባቂ ያደረጉ ሁሉ ከFTX ምንም ተፅእኖ አልነበራቸውም። ይህ የራስ-ጠባቂ ቢትኮይን ኃይል ነው: ትክክለኛ ገንዘብ ቁጥጥር።",
	"common_bitcoin_hacked_content_7": "ቢትኮይንዎን ገበያ ወይም ETF ላይ ከማስቀመጥ ይልቅ ሁሉንም የነፃነት ጥቅሞች ለማግኘት ራስዎ ቦርሳ ያስቀምጡ።",
	"common_bitcoin_hacked_content_8": "ቢትኮይንዎን ራስ-ጠባቂ ሲያደርጉ ገንዘብዎ በቢትኮይን ኔትወርክ ይጠበቃል። በዓለም ላይ ደህንነቱ ከፍተኛ የሆነ የፋይናንስ ኔትወርክ ነው።",
	"common_bitcoin_hacked_content_9": "ራስ-ጠባቂነት ላይ ከFTX Sam ቢትኮይንዎን ሊሰርቅ አይችልም።",
	"common_bitcoin_hacked_content_10": "መንግስት ተጨማሪ ቢትኮይን አታሚ ዋጋ ግሽበት ሊያመጣ አይችልም።",
	"common_bitcoin_hacked_content_11": "ራስ-ጠባቂ ቢትኮይን የቢትኮይን ኔትወርክ ኃይል ምክንያት ገንዘብዎ ነው።",
	"common_bitcoin_energy": "ቢትኮይን ለምን ኃይል ይጠቀማል?",
	"common_bitcoin_energy_content_1": "ቢትኮይን ኔትወርኩን ለመጠበቅ እና ገንዘብዎን ለመጠበቅ ኃይል ይጠቀማል።",
	"common_bitcoin_energy_content_2": "ቢትኮይን ከፍተኛ ኃይል ይጠቀማል እና ይህ ለብዙ ምክንያቶች ጥሩ ነው።",
	"common_bitcoin_energy_list_1": "ቢትኮይን የባንክ ሩጫ የለውም።",
	"common_bitcoin_energy_list_2": "ቢትኮይን ማዕድን ቁፋሮ የኤሌክትሪክ ግሪድ ማረጋጋት ይረዳል።",
	"common_bitcoin_energy_list_3": "ቢትኮይን ከነዳጅ ቁፋሮ የሚሆነውን ልቀት ይቀንሳል።",
	"common_bitcoin_energy_list_4": "ቢትኮይን አሜሪካውያን በየዓመቱ ለገና መብራት ከሚጠቀሙት ያነሰ ኃይል ይጠቀማል።",
	"common_bitcoin_energy_list_5": "ቢትኮይን በምድር ላይ በጣም አረንጓዴ ኢንዱስትሪ ነው!",
	"common_cic_intro_1": "ብዙ ሰዎች ስለ ተደራራቢ ወለድ ያውቃሉ ግን ስለ ተደራራቢ ዋጋ ግሽበት ጥቂት ሰዎች ያውቃሉ።",
	"common_cic_intro_2": "ተደራራቢ ዋጋ ግሽበት ካልኩሌተር ከጊዜ ጋር ግዢ ኃይል ለመጠበቅ ደመወዝዎ ምን ያህል መጨመር እንዳለበት ለማስላት ያስችላል።",
	"common_cic_intro_3": "አሁን ያለውን ደመወዝ፣ ዋጋ ግሽበት ተመን እና ዓመት ቁጥር ያስገቡ ካልኩሌተሩ ከዋጋ ግሽበት ጋር ለመከታተል ደመወዝዎ ምን ሊሆን እንዳለበት ያሳየዋል።",
	"common_current_salary": "አሁን ያለ ደመወዝ",
	"common_inflation_rate": "ዋጋ ግሽበት ተመን",
	"common_year": "ዓመት",
	"common_years": "ዓመታት",
	"common_result_starting_message": "ከላይ ያለውን ቅጽ ይሙሉ እና አስላ የሚለውን ጠቅ ያድርጉ።",
	"common_error_message": "ስህተት: 3ቱንም ቦታዎች ይሙሉ።",
	"common_result_message_1": "ዋጋ ግሽበት",
	"common_result_message_2": "ላይ",
	"common_result_message_3": "ደመወዝዎ",
	"common_result_message_in": "ውስጥ",
	"common_result_message_4": "ግዢ ኃይልዎን ለመጠበቅ መሆን ያስፈልጋል።",
	"common_calculate_button_text": "አስላ",
	"common_learn_more": "ተጨማሪ ይወቁ",
	"common_success": "ተሳክቷል!",
	"common_choose_your_country": "አገርዎን ይምረጡ",
	"common_country_usa": "ዩኤስኤ",
	"common_country_canada": "ካናዳ",
	"common_submit": "አስገባ",
	"common_language_afrikaans": "አፍሪካንስ",
	"common_language_arabic": "ዐረብኛ",
	"common_language_basque": "ባስክ",
	"common_language_bulgarian": "ቡልጋሪኛ",
	"common_language_catalan": "ካታላን",
	"common_language_chinese": "ቻይንኛ",
	"common_language_croatian": "ክሮኤሽያኛ",
	"common_language_czech": "ቼክ",
	"common_language_danish": "ዴንማርክኛ",
	"common_language_dutch": "ደች",
	"common_language_english": "እንግሊዝኛ",
	"common_language_estonian": "ኢስቶኒኛ",
	"common_language_filipino": "ፊሊፒንኛ",
	"common_language_finnish": "ፊንላንድኛ",
	"common_language_french": "ፈረንሳይኛ",
	"common_language_german": "ጀርመንኛ",
	"common_language_greek": "ግሪክኛ",
	"common_language_hausa": "ሃውሳ",
	"common_language_hebrew": "ዕብራይስጥ",
	"common_language_hindi": "ሂንዲ",
	"common_language_hungarian": "ሃንጋሪኛ",
	"common_language_indonesian": "ኢንዶኔዢያኛ",
	"common_language_irish": "አይሪሽ",
	"common_language_italian": "ጣልያንኛ",
	"common_language_japanese": "ጃፓንኛ",
	"common_language_korean": "ኮሪያኛ",
	"common_language_malay": "ማሌይ",
	"common_language_norwegian": "ኖርዌጂያን",
	"common_language_persian": "ፋርሲ",
	"common_language_polish": "ፖላንድኛ",
	"common_language_portuguese": "ፖርቱጋልኛ",
	"common_language_russian": "ሩሲያኛ",
	"common_language_sinhala": "ሲንሃላ",
	"common_language_slovak": "ስሎቫክኛ",
	"common_language_slovenian": "ስሎቬንኛ",
	"common_language_spanish": "ስፓኒሽ",
	"common_language_swahili": "ስዋሂሊ",
	"common_language_swedish": "ስዊድንኛ",
	"common_language_thai": "ታይኛ",
	"common_language_turkish": "ቱርክኛ",
	"common_language_urdu": "ኡርዱ",
	"common_language_vietnamese": "ቬትናምኛ",
	"common_language_yoruba": "ዮሩባ",
	"common_stickers_bulk_mess": "ፋይሎቹን ራስዎ ማስተናገድ አይፈልጉም?",
	"common_stickers_bulk_want": "ከጥቂት በላይ ስቲከሮች ይፈልጋሉ?",
	"common_stickers_bulk_store": "እኛ ከምንጠቀመው ማተሚያ ቤት ብዛት ያዙ።",
	"common_stickers_bulk_cheaper": "ብዙ ስቲከር ሲገዙ ለእያንዳንዱ ዋጋ ይቀንሳል።",
	"common_stickers_print_instructions_1": "የትም ቢኖሩ ራስዎ ስቲከር አትመው መሳተፍ ይችላሉ! ከዚህ በታች ቋንቋ ይምረጡ ስቲከር ፋይሎች እና ማተሚያ መመሪያ ለማውረድ።",
	"common_stickers_print_instructions_2": "ማስታወሻ: ሁሉም ስቲከሮች በሁሉም ቋንቋዎች አይገኙም።",
	"common_stickers_request_language_1": "የሚፈልጉት ቋንቋ የለም?",
	"common_stickers_request_language_2": "ከዚህ በታች ያለውን ቅጽ ይሙሉ በሚፈልጉት ቋንቋ ስቲከር ፋይሎችን ለመጠየቅ።",
	"common_stickers_dimensions": "መጠን:",
	"common_stickers_type": "ዓይነት:",
	"common_stickers_material": "ቁሳቁስ:",
	"common_stickers_where_to_print": "ማተሚያ:",
	"common_stickers_type_die_cut": "ዳይ-ካት ስቲከር",
	"common_stickers_material_vinyl": "ውጫዊ ቪኒል ስቲከር",
	"common_stickers_printer": "እኛ StickerMule.com እንጠቀማለን ግን ማንኛውንም ስቲከር ኩባንያ መጠቀም ይችላሉ።",
	"common_stickers_dimensions_danger": "11.4544 cm x 8.382 cm (4.51 in x 3.3 in)",
	"common_stickers_dimensions_warning": "10.414 cm x 9.2202 cm (4.1 in x 3.63 in)",
	"common_stickers_dimensions_caution": "12.0142 cm x 7.9502 cm (4.73 in x 3.13 in)",
	"common_stickers_dimensions_fix": "11.3792 cm x 6.8072 cm (4.48 in x 2.68 in)",
	"common_stickers_dimensions_study": "14.605 cm x 5.1308 cm (5.75 in x 2.02 in)",
	"common_stickers_dimensions_bdhi": "21.59 cm x 4.6482 cm (8.5 in x 1.83 in)",
	"common_stickers_dimensions_cure_v2": "6.35 cm x 12.7 cm (2.5 in x 5 in)",
	"common_stickers_dimensions_got_inflation": "7.9248 cm x 14.605 cm (3.12 in x 5.75 in)",
	"common_stickers_dimensions_what_if": "21.7932 cm x 7.62 cm (8.58 in x 3 in)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20.995 cm x 6.35 cm (8.25 in x 2.5 in)",
	"common_nostr_join": "አሁን NOSTR ይቀላቀሉ",
	"common_nostr_protocol_header": "ፕሮቶኮል እንጂ ፕላትፎርም አይደለም",
	"common_nostr_protocol_c1": "Nostr ያለ ሳንሱር፣ ፕላትፎርም ማባረር ወይም ደራሽነት መቀነስ ስጋት በመስመር ላይ ለመገናኘት የሚያስችል አዲስ ፕሮቶኮል ነው።",
	"common_nostr_protocol_c2": "እንደ Twitter ወይም Facebook ያሉ ፕላትፎርሞች በአንድ ኩባንያ ይቆጣጠራሉ ግን ማንም Nostr ፕሮቶኮልን አይቆጣጠርም።",
	"common_nostr_freedom_header": "የመንቀሳቀስ ነፃነት",
	"common_nostr_freedom_c1": "Nostr ከኢሜይል ጋር ይመሳሰላል። ማንም የኢሜይል ፕሮቶኮልን አይቆጣጠርም እና ማንም ሰው በላዩ ላይ ክላይንት (Gmail, Hotmail ወዘተ) ይገነባል።",
	"common_nostr_freedom_c2": "ማንም Nostr ፕሮቶኮልን አይቆጣጠርም እና ማንም ሰው በላዩ ላይ ክላይንት (Damus, Amethyst ወዘተ) ይገነባል።",
	"common_nostr_freedom_c3": "አንድ ክላይንት እንዴት እንደሚሰራ ካልወደዱ ተከታዮችዎን ወይም ይዘትዎን ሳያጡ Nostr ሂሳብዎን ወደ ሌላ ክላይንት ማዘዋወር ይችላሉ።",
	"common_nostr_bitcoin_header": "ቢትኮይን ውስጥ ተገንብቷል",
	"common_nostr_bitcoin_c1": "ቢትኮይን በNostr ፕሮቶኮል ውስጥ ተገንብቷል። የሚወዱትን ይዘት ሲያዩ በቀላሉ ቢትኮይን ዛፕ ማድረግ ይችላሉ!",
	"common_nostr_bitcoin_c2": "እንደ Twitter ወይም Facebook ያሉ ማዕከላዊ ፕላትፎርሞች ላይ ኩባንያው ከይዘትዎ ይጠቀማል። ግን በNostr ያለ ክፍት ፕሮቶኮል ላይ እርስዎ ከይዘትዎ ይጠቀማሉ።",
	"common_nostr_download_client": "ነፃ ክላይንት አውርደው NOSTR ይቀላቀሉ",
	"common_nostr_iphone_clients": "iPhone ክላይንቶች",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "iPhone መተግበሪያ",
	"common_nostr_first_client": "የሚመከር የመጀመሪያ ክላይንት",
	"common_nostr_wallet_built_in": "ቢትኮይን ዛፕ ቦርሳ ውስጥ ተገንብቷል",
	"common_nostr_download_now": "አሁን ያውርዱ",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "ተለምዶ ዘይቤ",
	"common_nostr_separate_wallet": "የተለየ ቢትኮይን ቦርሳ ያስፈልጋል",
	"common_nostr_android_clients": "Android ክላይንቶች",
	"common_nostr_android_app": "Android መተግበሪያ",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "ብዙ ባህሪዎች",
	"common_nostr_browser_clients": "ብራውዘር ክላይንቶች",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "ዌብ ክላይንት",
	"common_nostr_simple": "በጣም ቀላል",
	"common_nostr_test": "በፈተና ሂሳብ Nostr ን በቀላሉ ይሞክሩ",
	"common_nostr_view_client": "ክላይንት ይመልከቱ",
	"common_kit_printer": "የቢትኮይን ንግድ ኪት ብሮሹር ለማተም VistaPrint.com እንመክራለን። ሁለት ወገን ማተም የሚችል ማንኛውም ማተሚያ ቤት ይጠቀሙ።",
	"common_kit_link_to_print": "ማተሚያ ማስፈንጠሪያ:",
	"common_kit_fold": "ማጠፊያ:",
	"common_kit_fold_trifold": "ሶስት ክፍል ማጠፊያ",
	"common_kit_unfolded_size": "ያልተጠቀለለ መጠን:",
	"common_kit_unfolded_size_bbk": "ደብዳቤ መጠን (8.5 in x 11 in)",
	"common_kit_paper_thickness": "ወረቀት ውፍረት:",
	"common_kit_paper_thickness_standard": "ደረጃ",
	"common_kit_paper_stock": "ወረቀት ዓይነት:",
	"common_kit_paper_stock_glossy": "አንጸባራቂ",
	"common_kit_exterior_print_file": "ውጫዊ ማተሚያ ፋይል:",
	"common_kit_interior_print_file": "ውስጣዊ ማተሚያ ፋይል:",
	"common_kit_cta_header": "ለአካባቢ ንግዶች ቢትኮይን ክፍያ ማስተዋወቅ",
	"common_biz_learn": "ቢትኮይን ለንግድ ለምን ጥሩ እንደሆነ ይወቁ",
	"common_biz_wallets": "ቢትኮይን ክፍያ ለመቀበል ቢትኮይን ቦርሳ ያግኙ",
	"common_biz_maps": "በቢትኮይን ነጋዴ ካርታ ላይ ይመዝገቡ",
	"common_biz_stickers": "ነፃ 'Bitcoin Accepted Here' ስቲከሮች",
	"common_biz_rewards": "ቢትኮይን ሽልማቶች",
	"common_biz_accounting": "ቢትኮይን ሂሳብ አያያዝ መመሪያ",
	"common_biz_faq": "ብዙ ጊዜ የሚጠየቁ ጥያቄዎች",
	"common_biz_kit": "ቢትኮይን ንግድ ኪት ያትሙ",
	"common_biz_accept_bitcoin_payments": "ቢትኮይን ክፍያዎችን ይቀበሉ",
	"common_biz_ready": "በንግድዎ ቢትኮይን ለመቀበል ዝግጁ ነዎት?",
	"common_biz_more": "ተጨማሪ የንግድ ግብዓቶች",
	"common_self_custody": "ራስ-ጠባቂነት",
	"common_not_your_keys": "ቁልፎችዎ ካልሆኑ",
	"common_cold_wallet": "ቀዝቃዛ ቦርሳ",
	"common_hot_wallet": "ሞቃት ቦርሳ",
	"common_sticker_files_mission_1": "ተልዕኮአችን በህዝባዊ ቦታዎች ቢትኮይን ስቲከሮች ለጥፎ ብዙ ሰዎች ስለ ቢትኮይን እንዲያውቁ ማድረግ ነው። ሁሉም ስቲከሮች ወደ ትምህርት ገጽ የሚወስድ QR ኮድ አላቸው:",
	"common_sticker_files_mission_2": "ቢትኮይን",
	"common_sticker_files_mission_3": "ዋጋ ግሽበት",
	"common_sticker_files_mission_4": "በአሜሪካ ወይም ካናዳ ከኖሩ፣",
	"common_sticker_files_mission_5": "ነፃ የእንግሊዝኛ ስቲከር ፓኬጅ ይጠይቁ",
	"common_published_by": "ያሳተመው:",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "ከ2022 ጀምሮ ቢትኮይን ትምህርት",
	"common_publisher_open_source": "ክፍት ምንጭ ፕሮጀክት",
	"common_reviewed_accuracy": "✓ ትክክለኛነት ተገምግሟል: 2026",
	"common_footer_tagline": "በትምህርት አማካኝነት የቢትኮይን ተቀባይነትን ማፋጠን።",
	"common_footer_contribute": "አበርክቱ",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "ምንጮች"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! common.json created for Amharic (am).');
