/**
 * Creates Amharic (am) translation files for content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'am';
const today = '2026-04-06';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "ቢትኮይን የባንክ ሩጫ የለውም",
	"bank_runs_header": "ቢትኮይን የባንክ ሩጫ የለውም",
	"bank_runs_header_2": "ግን ባንክዎ ሊኖረው ይችላል",
	"bank_runs_what": "የባንክ ሩጫ ምንድን ነው?",
	"bank_runs_what_content_1": "የባንክ ሩጫ የሚከሰተው ብዙ ሰዎች በአንድ ጊዜ ከባንክ ገንዘባቸውን ለማውጣት ሲሞክሩ ነው።",
	"bank_runs_what_content_2": "ባንኩ የማስወጣት ጥያቄዎችን ለማሟላት በቂ ገንዘብ ከሌለው የባንክ ሩጫ ሲከሰት ሙሉ በሙሉ ሊወድቅ ይችላል።",
	"bank_runs_how": "የባንክ ሩጫ እንዴት ይከሰታል?",
	"bank_runs_how_content_1": "የባንክ ስርዓታችን 'ከፊል ተጠባባቂ' ነው። ባንኮች ገንዘብዎን በከባቢ ውስጥ አስቀምጠው ማስወጣትዎን አይጠብቁም።",
	"bank_runs_how_content_2": "ይልቁንም ባንኮች ገንዘብዎን ወስደው ያበድሩት ወይም ያዋዕሉት። ይህ ገንዘብ ለረጅም ጊዜ ሊታሰር ይችላል ግን ባንኮች በማንኛውም ጊዜ ማስወጣት እንደሚችሉ ቃል ገቡ።",
	"bank_runs_how_content_3": "ታዲያ ባንኩ ገንዘብዎን ቀድሞ ካበደረ ወይም ካዋዐለ በኋላ ለማስወጣት ሲሞክሩ ምን ይሆናል?",
	"bank_runs_how_content_4": "እርስዎ ብቻ ከሆኑ ችግር የለውም። ባንኩ ሌላ ሰው ገንዘብ ወስዶ ይሰጥዎታል። ግን ብዙ ሰዎች በአንድ ጊዜ ቢፈልጉስ?",
	"bank_runs_how_content_5": "በ2023 መጋቢት Silicon Valley Bank ላይ የባንክ ሩጫ ሲከሰት ብዙ አሜሪካውያን ይህን ተማሩ።",
	"bank_runs_how_content_6": "ባንኩ የደንበኞችን ገንዘብ እስከ 30 ዓመት በታሰሩ ቦንዶች ላይ ኢንቨስት አድርጎ ነበር። ከዚህም ባሻገር ያ ቦንዶች ዋጋ ቀንሶ ነበር ስለዚህ ለተቀማጮች ገንዘብ ለማግኘት ቦንዶቹን መሸጥ አይችሉም ነበር።",
	"bank_runs_how_content_7": "ብዙ ሰዎች ሲያውቁ ችግሩ ተባባሰ። ተጨማሪ ማስወጣት ጥያቄ ቢመጣም ብዙዎቹ አልተጠናቀቁም። ሺዎች ኩባንያዎች ለሰራተኞች ደመወዝ መክፈል እንደማይችሉ ተገነዘቡ።",
	"bank_runs_how_content_8": "FDIC ገብቶ ተቀማጮችን ሙሉ ለሙሉ እንደሚከፍል ተስማማ። ችግር ተፈታ? በትክክል አይደለም...",
	"bank_runs_fdic": "FDIC ኢንሹራንስ ገንዘቤን ይጠብቃል?",
	"bank_runs_fdic_content_1": "FDIC ኢንሹራንስ ባንክ ሲወድቅ ተቀማጮችን ለመጠበቅ ተሰርቷል። ለእያንዳንዱ ተቀማጭ እስከ $250,000 ተሸፍኗል። ጥሩ ይመስላል?",
	"bank_runs_fdic_content_2": "በትክክል አይደለም። ባንክ ሲወድቅ FDIC ገንዘቡን ከየት ያመጣል? $125 ቢሊዮን የኢንሹራንስ ፈንድ አለው።",
	"bank_runs_fdic_content_3": "ብዙ ገንዘብ ይመስላል ግን ከኢንሹራንስ ለተሸፈነ ማስገቢያ ከ$10 ትሪሊዮን ማለት $10,000 ቢሊዮን ጋር ሲወዳደር ብዙ አይደለም።",
	"bank_runs_fdic_content_4": "FDIC ድር ጣቢያው ላይ ኢንሹራንስ ፈንዱ ከማስገቢያ 1% ብቻ ሊሸፍን እንደሚችል ያሳያል።",
	"bank_runs_fdic_content_5": "ከFDIC ኢንሹራንስ ፈንድ በላይ ባንክ ቢወድቅ ምናልባት አሜሪካ መንግስት ገንዘብ አትሞ ተቀማጮችን ሙሉ ለሙሉ ይከፍላል (ዋስትና ባይኖረውም)።",
	"bank_runs_fdic_content_6": "ግን ገንዘብ ማተም ዋጋ ግሽበት ያመጣል ስለዚህ ጥሩ መፍትሄ አይደለም።",
	"bank_runs_safe": "ከፊል ተጠባባቂ የማይጠቀም ባንክ አለ?",
	"bank_runs_safe_content_1": "አንዳንድ ባንኮች የተቀማጮችን ገንዘብ የማያበድሩ ወይም የማያዋዕሉ 'ደህንነቱ የተጠበቀ ባንክ' ለመሆን ሞክረዋል።",
	"bank_runs_safe_content_2": "እነዚህ ደህንነቱ የተጠበቀ ባንኮች ምንም የባንክ ሩጫ አደጋ አይኖራቸውም ነበር ግን ማመልከቻቸው በፌደራል ሪዘርቭ ተከልክሏል።",
	"bank_runs_safe_content_3": "ከተከለከሉ ጀምሮ ከፊል ተጠባባቂ የማይጠቀም ባንክ የለም።",
	"bank_runs_safe_content_4": "ግን ደስ የሚለው ራስዎ ባንክ ሆኖ ከፊል ተጠባባቂ ስርዓት ከመውጣት መንገድ አለ። አልጋ ስር ገንዘብ መደበቅ ማለት አይደለም።",
	"bank_runs_safe_content_5": "በጥሬ ገንዘብ መቆጠብ አሁንም ለዋጋ ግሽበት ተጋላጭ ነው።",
	"bank_runs_safe_content_6": "የምንናገረው ስለ ቢትኮይን ነው: ራስዎ ባንክ ሊሆኑ የሚያስችል አዲስ የፋይናንስ ስርዓት።",
	"bank_runs_protect": "ቢትኮይን ከባንክ ሩጫ ሊጠብቀኝ ይችላል?",
	"bank_runs_protect_content_1": "አዎ፣ ቢትኮይን ሙሉ ተጠባባቂ የፋይናንስ ስርዓት ነው።",
	"bank_runs_protect_content_2": "ቢትኮይንዎን ወደ ራስዎ ቦርሳ ማስወጣት ብቻ ያድርጉ እና የባንክ ሩጫ በቢትኮይን ይቻልም። ቢትኮይንዎን ገበያ ላይ ወይም Bitcoin ETF ላይ አያስቀምጡ።",
	"bank_runs_protect_content_3": "ወደ ራስዎ ቦርሳ እንዴት ማስወጣት እንደሚቻል ለማወቅ ቀላል ቢትኮይን ቦርሳ መመሪያውን ይመልከቱ።",
	"bank_runs_protect_content_4": "በቢትኮይን በመጨረሻ ገንዘብዎን ራስዎ ይቆጣጠራሉ።"
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "የቢትኮይን ቦርሳ መመሪያ",
	"wallets_description": "አስፈላጊ በሆኑ መንገዶች የሚለያዩ የተለያዩ ቢትኮይን ቦርሳዎች አሉ። ቀላል ጥያቄዎች ትክክለኛውን ቦርሳ ለመወሰን ይረዳሉ።",
	"wallets_header": "ቢትኮይንዎን ደህንነቱ በተጠበቀ ሁኔታ እንዴት ማከማቸት እንደሚቻል",
	"wallets_s1_c1": "ቢትኮይን ቦርሳዎች ተስማሚ ናቸው ስለዚህ ማንኛውንም ቦርሳ ተጠቅመው ለማንም ቢትኮይን መላክ ይችላሉ።",
	"wallets_s1_c2": "አስፈላጊ በሆኑ መንገዶች የሚለያዩ የተለያዩ ቢትኮይን ቦርሳዎች አሉ። ቀላል ጥያቄዎች ትክክለኛውን ቦርሳ ለመወሰን ይረዳሉ:",
	"wallets_question_1": "ራስ-ጠባቂ ቦርሳ ነው?",
	"wallets_s2_c1": "ከቢትኮይን ፈጠራዎች አንዱ እንደ ባንክ ያለ ተጠባባቂ ሳያስፈልግ ማከማቸት የመቻል ችሎታ ነው።",
	"wallets_s2_c2": "ቢትኮይንዎን ገበያ ወይም ETF ላይ ቢያስቀምጡ የቢትኮይን ነፃነት ጥቅሞችን ያጣሉ።",
	"wallets_s2_c3": "ራስ-ጠባቂ ቦርሳ የቢትኮይን ሙሉ ኃይል ያስገኛል: የነፃነት ገንዘብ።",
	"wallets_s2_c4": "ራስ-ጠባቂ ቦርሳ ሲጠቀሙ ገንዘብዎን ማጠፋት ወይም መላክ የሚችሉት እርስዎ ብቻ ነዎት። ማንም ገንዘብ መላክ ወይም መቀበል ሊያግድ አይችልም።",
	"wallets_s2_c5": "ራስ-ጠባቂ ቦርሳ ነን-ከስቶዲያል ቦርሳ ተብሎም ይጠራል።",
	"wallets_s3_c1": "ከስቶዲያል ቦርሳ ገንዘብዎን ሊቆጣጠሩ የማይችሉበት ቦርሳ ነው።",
	"wallets_s3_c2": "እነዚህ ቦርሳዎች ሶስተኛ ወገን ገንዘብ ተደራሽነት ሊሰጥ ከሚገባው ባንክ ስርዓት ጋር ይመሳሰላሉ።",
	"wallets_s3_c3": "Bitcoin ETF ከገዙ ወደ ራስ-ጠባቂነት ማስወጣት የማይችሉበት ከስቶዲያል ቦርሳ ነው።",
	"wallets_s3_c4": "ከስቶዲያል ቦርሳ ምቹ ሊመስል ይችላል ግን ተጠባባቂው በማንኛውም ጊዜ ሁሉንም ገንዘብ ለመውሰድ ቴክኒካል ችሎታ አለው።",
	"wallets_s3_c5": "ቁልፎችዎ ካልሆኑ ኮይኖችዎ አይደሉም!",
	"wallets_question_2": "ሞቃት ቦርሳ ወይስ ቀዝቃዛ ቦርሳ?",
	"wallets_s4_c1": "ቀዝቃዛ ቦርሳ ቢትኮይን ቁልፎችዎን ከኢንተርኔት ራቅ ብሎ ያስቀምጣል።",
	"wallets_s4_c2": "ይህ ሌቦች ቢትኮይንዎን ለመስረቅ ሊጠቀሙ የሚችሉትን ጥቃት ነጥቦችን ይገድባል እና ብዙ ጊዜ ለማይላክ ትልቅ ቢትኮይን ምርጥ ነው።",
	"wallets_s4_c3": "ቀዝቃዛ ቦርሳ እንደ ረጅም ጊዜ ቁጠባ ሂሳብ ያስቡ።",
	"wallets_s5_c1": "ሞቃት ቦርሳ ቢትኮይን ቁልፎችዎን ከኢንተርኔት ጋር በተገናኘ መሳሪያ ላይ ያስቀምጣል እንደ ስማርትፎን።",
	"wallets_s5_c2": "ሞቃት ቦርሳ ደህንነቱ የተጠበቀ ተደርጎ ይወሰዳል ግን ከቀዝቃዛ ቦርሳ ይበልጥ ተጋላጭ ሊሆን ይችላል።",
	"wallets_s5_c3": "ሞቃት ቦርሳ እንደ አካላዊ ኪስ ቦርሳ ያስቡ። ሁሉንም ቁጠባ ኪስ ቦርሳ ውስጥ አይቀመጥም ግን የእለት ወጪ ያደርጋሉ።",
	"wallets_s5_c4": "ሞቃት ቦርሳ ሁሉንም ቁጠባ ከቀዝቃዛ ማከማቻ ሳያወጡ ቢትኮይን ለመጠቀም ቀላል ያደርገዋል።",
	"wallets_question_3": "የማገገሚያ ሐረግን እንዴት መጠባበቅ?",
	"wallets_s6_c1": "ቢትኮይን ቦርሳ ሲያዋቅሩ መሳሪያዎ የማገገሚያ ሐረግ ያመነጫል። ይህ ሐረግ (ሲድ ሐረግ ተብሎም ይጠራል) 12 ወይም 24 ቃላት ነው።",
	"wallets_s6_c2": "ቦርሳዎ ተደራሽነት ካጡ ወይም መሳሪያዎ ቢሰበር ይህን ሐረግ አዲስ ቦርሳ ላይ አስገብተው ቢትኮይንዎን መልሰው ያገኛሉ።",
	"wallets_s6_c3": "አብዛኛው ቦርሳዎች ሐረጉን ለመፃፍ ወረቀት ይዘው ይመጣሉ ግን ብዙ ሰዎች ከወረቀት ይልቅ በብረት ላይ ለመፃፍ ይመርጣሉ። ይህ ከእሳት ወይም ጎርፍ ጊዜ ሐረጉን ለማጣት ያለውን እድል ይቀንሳል።",
	"wallets_s6_c4": "Jameson Lopp 70 የብረት ጠባቂ ኪቶች ሞክሮ ትክክለኛውን ለመምረጥ ይረዳዎታል።",
	"wallets_s6_c5": "የJameson ብረት ቢትኮይን ጠባቂ መመሪያ እዚህ ይመልከቱ።",
	"wallets_s6_c6": "ወይም ቢትኮይን ቦርሳ አማራጮችን ለማየት ወደ ታች ይሸብልሉ።",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "ላይትኒንግ ቦርሳ መመሪያ ይፈልጋሉ?",
	"wallets_starter_wallet": "ድንቅ የመጀመሪያ ቦርሳ",
	"wallets_mobile_app": "ሞባይል መተግበሪያ",
	"wallets_2fa_support": "2FA ድጋፍ",
	"wallets_air_gap_mode": "ኤር-ጋፕ ሞድ",
	"wallets_air_gap_camera": "ኤር-ጋፕ ሞድ + ካሜራ",
	"wallets_bitcoin_only": "ቢትኮይን ብቻ",
	"wallets_security_features": "ብዙ ደህንነት ባህሪዎች",
	"wallets_free": "100% ነፃ",
	"wallets_coldcard_mk5_costs": "ዋጋ $189",
	"wallets_coldcard_q_costs": "ዋጋ $289",
	"wallets_blockstream_jade_costs": "ዋጋ $79",
	"wallets_foundation_passport_costs": "ዋጋ $199",
	"wallets_seedsigner_costs": "ክፍሎች $50",
	"wallets_very_affordable": "በጣም ተመጣጣኝ",
	"wallets_pair_with_phone": "ከስልክ ጋር ይገናኙ",
	"wallets_battery": "ተሞላ ባትሪ",
	"wallets_build_your_own": "ራስዎ ይገንቡ",
	"wallets_qwerty_keyboard": "ሙሉ QWERTY ቁልፍ ሰሌዳ",
	"wallets_qr_scanner": "QR ኮድ አንባቢ"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "ቢትኮይን እንዴት መግዛት እንደሚቻል - ደረጃ-በደረጃ መመሪያ",
	"buy_header": "ቢትኮይን እንዴት መግዛት እንደሚቻል",
	"buy_intro_c1": "ለመጀመሪያ ጊዜ ቢትኮይን መግዛት ከባድ ሊመስል ይችላል ግን ደረጃ-በደረጃ ከከፈሉ በእውነት ቀላል ነው።",
	"buy_intro_c2": "ይህ መመሪያ ቢትኮይን ደህንነቱ በተጠበቀ ሁኔታ ለመግዛት እና ራስዎ ቦርሳ ለማከማቸት ያመራዎታል።",
	"buy_step_1_header": "ደረጃ 1: አገርዎን ይምረጡ",
	"buy_step_1_description": "አገሮች የተለያዩ ቢትኮይን ግዢ አማራጮች አሏቸው። አገርዎን ይምረጡ ምርጥ አማራጮችን ለማየት።",
	"buy_search_countries": "አገሮች ይፈልጉ",
	"buy_country_united_states": "ዩናይትድ ስቴትስ",
	"buy_country_australia": "አውስትራሊያ",
	"buy_country_austria": "ኦስትሪያ",
	"buy_country_belgium": "ቤልጂየም",
	"buy_country_brazil": "ብራዚል",
	"buy_country_canada": "ካናዳ",
	"buy_country_france": "ፈረንሳይ",
	"buy_country_germany": "ጀርመን",
	"buy_country_ireland": "አየርላንድ",
	"buy_country_italy": "ጣልያን",
	"buy_country_netherlands": "ኔዘርላንድ",
	"buy_country_new_zealand": "ኒው ዚላንድ",
	"buy_country_spain": "ስፔን",
	"buy_country_united_kingdom": "ብሪታንያ",
	"buy_country_argentina": "አርጀንቲና",
	"buy_country_chile": "ቺሊ",
	"buy_country_colombia": "ኮሎምቢያ",
	"buy_country_costa_rica": "ኮስታ ሪካ",
	"buy_country_czech_republic": "ቼክ ሪፐብሊክ",
	"buy_country_denmark": "ዴንማርክ",
	"buy_country_el_salvador": "ኤል ሳልቫዶር",
	"buy_country_estonia": "ኢስቶኒያ",
	"buy_country_finland": "ፊንላንድ",
	"buy_country_greece": "ግሪክ",
	"buy_country_guatemala": "ጓቴማላ",
	"buy_country_hong_kong": "ሆንግ ኮንግ",
	"buy_country_hungary": "ሃንጋሪ",
	"buy_country_iceland": "አይስላንድ",
	"buy_country_india": "ህንድ",
	"buy_country_israel": "እስራኤል",
	"buy_country_japan": "ጃፓን",
	"buy_country_latvia": "ላትቪያ",
	"buy_country_lithuania": "ሊትዌኒያ",
	"buy_country_luxembourg": "ሉክሰምበርግ",
	"buy_country_malta": "ማልታ",
	"buy_country_mexico": "ሜክሲኮ",
	"buy_country_norway": "ኖርዌይ",
	"buy_country_panama": "ፓናማ",
	"buy_country_poland": "ፖላንድ",
	"buy_country_portugal": "ፖርቱጋል",
	"buy_country_romania": "ሮማንያ",
	"buy_country_singapore": "ሲንጋፖር",
	"buy_country_slovakia": "ስሎቫኪያ",
	"buy_country_slovenia": "ስሎቬኒያ",
	"buy_country_south_africa": "ደቡብ አፍሪካ",
	"buy_country_south_korea": "ደቡብ ኮሪያ",
	"buy_country_sweden": "ስዊድን",
	"buy_country_switzerland": "ስዊዘርላንድ",
	"buy_country_thailand": "ታይላንድ",
	"buy_country_turkey": "ቱርክ",
	"buy_country_ukraine": "ዩክሬን",
	"buy_country_uruguay": "ኡሩጓይ",
	"buy_step_2_header": "ደረጃ 2: የክፍያ ዘዴ ይምረጡ",
	"buy_step_2_description": "ቢትኮይን ለመግዛት ሁለት ዋና መንገዶች አሉ: ባንክ ማስተላለፍ እና ጥሬ ገንዘብ። እያንዳንዳቸው ልዩ ጥቅም አላቸው።",
	"buy_method_bank_transfer": "ባንክ ማስተላለፍ",
	"buy_method_bank_fast": "ፈጣን እና ቀላል",
	"buy_method_bank_less_private": "ግላዊነት ያነሰ",
	"buy_method_bank_description": "ባንክ ማስተላለፍ ቢትኮይን ለመግዛት በጣም የተለመደ መንገድ ነው። ፈጣን፣ ምቹ እና ዝቅተኛ ክፍያ አለው።",
	"buy_method_choose_bank": "ባንክ ማስተላለፍ ይምረጡ",
	"buy_method_cash": "ጥሬ ገንዘብ",
	"buy_method_cash_private": "ግላዊነት ከፍተኛ",
	"buy_method_cash_limited": "ውሱን አማራጮች",
	"buy_method_cash_description": "በጥሬ ገንዘብ መግዛት ከፍተኛ ግላዊነት ይሰጣል ግን ውሱን አማራጮች እና በአካል መገናኘት ወይም ቢትኮይን ATM መጠቀም ሊያስፈልግ ይችላል።",
	"buy_method_choose_cash": "ጥሬ ገንዘብ ይምረጡ",
	"buy_step_3_header": "ደረጃ 3: ግዢ አማራጮች",
	"buy_step_3_description": "ለአገርዎ እና ክፍያ ዘዴ ምርጥ ቢትኮይን ግዢ አማራጮች:",
	"buy_platform_recommended": "የሚመከር",
	"buy_platform_strike_description": "Strike ቢትኮይን ለመግዛት ዝቅተኛ ክፍያ እና ወዲያውኑ ላይትኒንግ ኔትወርክ ድጋፍ ያለው ፈጣን እና ቀላል መንገድ ነው።",
	"buy_platform_swan_description": "Swan Bitcoin መደበኛ ግዢ እና ትምህርታዊ ግብዓቶች ያለው ቢትኮይን-ብቻ አገልግሎት ነው።",
	"buy_platform_river_description": "River ትምህርት እና ደህንነት ላይ ያተኮረ ቢትኮይን ግዢ፣ ማዕድን ቁፋሮ እና ጠባቂ አገልግሎት ነው።",
	"buy_platform_coinsquare_description": "Coinsquare ጠንካራ ቁጥጥር ተገዢነት እና ደንበኛ ድጋፍ ያለው ካናዳዊ ቢትኮይን ገበያ ነው።",
	"buy_platform_kraken_description": "Kraken ከፍተኛ ንግድ ባህሪዎች እና ጠንካራ ደህንነት ያለው የተረጋገጠ ቢትኮይን ገበያ ነው።",
	"buy_platform_atm_description": "ቢትኮይን ATM ላይ በጥሬ ገንዘብ ቢትኮይን ወዲያውኑ ይገዛሉ። Coin ATM Radar ተጠቅመው ቅርብ ATM ያግኙ።",
	"buy_platform_bisq_description": "Bisq ያለ KYC ግላዊ ቢትኮይን ንግድ የሚያስችል ያልተማከለ P2P ገበያ ነው።",
	"buy_platform_feature_instant": "ወዲያውኑ ግዢ",
	"buy_platform_feature_low_fees": "ዝቅተኛ ክፍያ",
	"buy_platform_feature_lightning": "ላይትኒንግ ኔትወርክ",
	"buy_platform_feature_dca": "መደበኛ ግዢ",
	"buy_platform_feature_education": "ትምህርታዊ ግብዓቶች",
	"buy_platform_feature_withdrawal": "ቀላል ማስወጣት",
	"buy_platform_feature_mining": "ቢትኮይን ማዕድን ቁፋሮ",
	"buy_platform_feature_custody": "ጠባቂ አገልግሎት",
	"buy_platform_feature_canadian": "ካናዳ ልዩ",
	"buy_platform_feature_regulated": "ቁጥጥር ገበያ",
	"buy_platform_feature_support": "ደንበኛ ድጋፍ",
	"buy_platform_feature_established": "የተረጋገጠ ድርጅት",
	"buy_platform_feature_security": "ጠንካራ ደህንነት",
	"buy_platform_feature_advanced": "ከፍተኛ ባህሪዎች",
	"buy_platform_feature_cash": "በጥሬ ገንዘብ ግዢ",
	"buy_platform_feature_anonymous": "ማንነት ጥበቃ",
	"buy_platform_feature_p2p": "P2P",
	"buy_platform_feature_private": "ግላዊ ንግድ",
	"buy_platform_feature_decentralized": "ያልተማከለ",
	"buy_platform_relai_description": "Relai ራስ-ጠባቂ ቦርሳ፣ አውቶ-ኢንቨስት እና ለአውሮፓ ዝቅተኛ ክፍያ ያለው ስዊስ ቢትኮይን-ብቻ መተግበሪያ ነው።",
	"buy_platform_feature_bitcoin_only": "ቢትኮይን ብቻ",
	"buy_platform_feature_self_custody": "ራስ-ጠባቂ ቦርሳ",
	"buy_platform_feature_auto_invest": "አውቶ-ኢንቨስት እቅድ",
	"buy_platform_feature_european": "አውሮፓ ልዩ",
	"buy_step_4_header": "ደረጃ 4: ቢትኮይንዎን ደህንነቱ በተጠበቀ ሁኔታ ያከማቹ",
	"buy_step_4_c1": "ቢትኮይን ከገዙ በኋላ በጣም አስፈላጊ ደረጃ ግል ቁልፎችዎን ወደሚቆጣጠሩበት ራስዎ ቦርሳ ማዘዋወር ነው።",
	"buy_step_4_c2": "ቢትኮይንዎን ገበያ ላይ ማስቀመጥ አደገኛ ነው። ቢትኮይኑን ራስዎ አይደለም የሚይዙት ገበያው ነው።",
	"buy_step_4_c3": "ግል ቁልፎችዎን ሲቆጣጠሩ ቢትኮይንዎ ትክክለኛ ባለቤትነት ያገኛሉ ማንም ሊወስድ አይችልም።",
	"buy_step_4_c4": "ለፍላጎትዎ ተስማሚ ቢትኮይን ቦርሳ እንዴት መምረጥ እንደሚቻል:",
	"buy_cta_wallets": "ቢትኮይን ቦርሳ መመሪያ ይመልከቱ"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "ቢትኮይን ላይትኒንግ ቦርሳ መመሪያ",
	"lightning_description": "ላይትኒንግ ቦርሳ ግል ሉዓላዊነትዎን እየጠበቁ ፈጣን እና ዝቅተኛ ክፍያ ቢትኮይን ለመላክ ያስችላል።",
	"lightning_header": "ላይትኒንግ ቦርሳ መመሪያ",
	"lightning_s1_c1": "ላይትኒንግ ፈጣን እና ዝቅተኛ ክፍያ ቢትኮይን ክፍያዎችን ለመላክ ያስችላል።",
	"lightning_s1_c2": "ላይትኒንግ መጠቀም ጥፋት-ያለው ምርጫ እንደሚኖር ማወቅ አስፈላጊ ነው። ፈጣን እና ዝቅተኛ ክፍያ ክፍያዎች ለማግኘት አንዳንድ ደህንነት ይቀንሳል።",
	"lightning_s1_c3": "ብዙ ጊዜ ላይትኒንግ ለትንሽ ቢትኮይን ብቻ ይጠቀሙ። ትልቅ ቢትኮይን ሁልጊዜ በሃርድዌር ቦርሳ ብቻ ያስቀምጡ።",
	"lightning_s1_c4": "ለተጨማሪ ዝርዝር ሃርድዌር ቦርሳ መመሪያውን ይመልከቱ።",
	"lightning_s1_c5": "ሁሉም ላይትኒንግ ቦርሳዎች ተመሳሳይ አይደሉም። ቀላል ጥያቄዎች ትክክለኛውን ጥፋት-ያለው ምርጫ ለመወሰን ይረዳሉ:",
	"lightning_question_1": "ለእኔ ትክክለኛው ምርጫ ምንድን ነው?",
	"lightning_s2_c1": "ከቢትኮይን ፈጠራዎች አንዱ እንደ ባንክ ያለ ተጠባባቂ ሳያስፈልግ ማከማቸት ነው። ራስ-ጠባቂ ቦርሳ የቢትኮይን ሙሉ ኃይል ያስገኛል።",
	"lightning_s2_c2": "ራስ-ጠባቂ ቦርሳ ሲጠቀሙ ገንዘብዎን ማጠፋት ወይም መላክ የሚችሉት እርስዎ ብቻ ነዎት። ማንም ሊያግድ፣ ሊሰርዝ ወይም ሊሰርቅ አይችልም።",
	"lightning_s2_c3": "ላይትኒንግ ለመጠቀም በጣም ሉዓላዊ መንገድ ራስዎ ኖድ ማስሮ ነው።",
	"lightning_s2_c4": "ይህ መመሪያ ራስዎ ኖድ የማያስፈልጉ ቀላል ላይትኒንግ ቦርሳዎች ላይ ያተኩራል።",
	"lightning_s2_c5": "ነን-ከስቶዲያል ላይትኒንግ ቦርሳ ቢጠቀሙም ቦርሳ ሰሪው ገንዘብ ለመስረቅ ክፉ ማዘመን እንደማያደርግ ማመን ያስፈልጋል።",
	"lightning_s3_c1": "ከስቶዲያል ቦርሳ ገንዘብዎን ሊቆጣጠሩ የማይችሉበት ቦርሳ ነው።",
	"lightning_s3_c2": "እነዚህ ቦርሳዎች ከባንክ ስርዓት ጋር ይመሳሰላሉ ሶስተኛ ወገን ገንዘብ ተደራሽነት ሊሰጥ ይገባል።",
	"lightning_s3_c3": "ከስቶዲያል ቦርሳ ምቹ ሊመስል ይችላል ግን ተጠባባቂው ሁሉንም ገንዘብ ለመውሰድ ቴክኒካል ችሎታ አለው።",
	"lightning_s3_c4": "አንዳንድ ሰዎች ለትንሽ ቢትኮይን ቀላል ስለሆነ ከስቶዲያል ላይትኒንግ ቦርሳ ይመርጣሉ። ያስታውሱ: ቁልፎችዎ ካልሆኑ ኮይኖችዎ አይደሉም!",
	"lightning_question_2": "ቦርሳ ይምረጡ",
	"lightning_s4_c1": "ይህ ሁሉ ባስተውሉ አሁን ትክክለኛውን ምርጫ ያለው ላይትኒንግ ቦርሳ መምረጥ ይችላሉ።",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "ብዙ ባህሪዎች",
	"lightning_mobile_app": "ሞባይል መተግበሪያ",
	"lightning_free": "100% ነፃ",
	"lightning_merchants": "ለነጋዴዎች ተስማሚ",
	"lightning_starter": "ድንቅ የመጀመሪያ ቦርሳ",
	"lightning_browser": "ብራውዘር-ተኮር",
	"lightning_custodial": "ሙሉ ከስቶዲያል ቦርሳ",
	"lightning_cta_hardware": "ቢትኮይን ሃርድዌር ቦርሳ መመሪያ ይፈልጋሉ?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "ከbitcoin.rocks ነፃ ቢትኮይን ስቲከሮች",
	"stickers_description": "በህዝባዊ ቦታዎች ቢትኮይን ስቲከሮች ለጥፈው ዙሪያዎ ሰዎች ስለ ቢትኮይን ያስተምሩ።",
	"stickers_header": "ነፃ ቢትኮይን ስቲከሮች",
	"stickers_choose_header": "ስቲከር ፓኬጅ ይምረጡ",
	"stickers_choose_c1": "ተልዕኮአችን በህዝባዊ ቦታዎች ቢትኮይን ስቲከሮች ለጥፎ ብዙ ሰዎች ስለ ቢትኮይን እንዲያውቁ ማድረግ ነው። ሁሉም ስቲከሮች ወደ ትምህርት ገጽ የሚወስድ QR ኮድ አላቸው:",
	"stickers_choose_c2": "ቢትኮይን",
	"stickers_choose_c3": "ዋጋ ግሽበት",
	"stickers_choose_c4": "ከዚህ በታች ስቲከር ፓኬጅ ይምረጡ",
	"stickers_text_pack": "ጽሑፍ ፓኬጅ",
	"stickers_signs_pack": "ምልክት ፓኬጅ",
	"stickers_instructions_1": "የፖስታ አድራሻዎን ያስገቡ ነፃ ቢትኮይን ስቲከር ፓኬጅ እንልክልዎታለን! ስቲከሮች ነጭ ፖስታ ውስጥ ይላካሉ።",
	"stickers_instructions_2": "የአድራሻ ውሂብ ነፃ ስቲከሮች ከተላኩ በኋላ ይሰረዛል።",
	"stickers_share_header": "ስቲከር ቦታዎችዎን ያጋሩ",
	"stickers_share_c1": "በNostr ላይ ስቲከር ቦታዎችዎን ያጋሩ ሌሎች ሰዎች ስቲከሮቻቸውን የት እንደሚለጥፉ ይመልከቱ።",
	"stickers_btn_share_on_nostr": "በNOSTR ላይ ያጋሩ",
	"stickers_btn_what_is_nostr": "NOSTR ምንድን ነው?",
	"stickers_flyers_link_before": "ስቲከር ሲለጥፉ ",
	"stickers_flyers_link_text": "ቢትኮይን በራሪ ወረቀቶች",
	"stickers_flyers_link_after": " ደግሞ አትመው ይለጥፉ ተጨማሪ ሰዎችን ለማስተማር።",
	"stickers_country_global_print": "ዓለም አቀፍ — ራስዎ ስቲከር ያትሙ",
	"stickers_country_global_order": "ዓለም አቀፍ — ብዛት ይዘዙ",
	"placeholder_name_optional": "ስም (አማራጭ)",
	"placeholder_address_line_1": "አድራሻ ሐረግ 1",
	"placeholder_address_line_2": "አድራሻ ሐረግ 2 (አማራጭ)",
	"placeholder_city": "ከተማ",
	"placeholder_state": "ክልል",
	"placeholder_province": "ግዛት",
	"placeholder_zip_code": "ዚፕ ኮድ",
	"placeholder_postal_code": "ፖስታ ኮድ",
	"placeholder_language": "ቋንቋ",
	"placeholder_which_stickers": "የትኞቹ ስቲከሮች?",
	"placeholder_email_optional": "ማሳወቂያ ለመቀበል ኢሜይል ያስገቡ (አማራጭ)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "ከbitcoin.rocks ነፃ ቢትኮይን ፖስት ካርዶች",
	"postcards_description": "ነፃ ቢትኮይን ፖስት ካርድ ፓኬጅ ተቀብለው ለሚያውቋቸው ሰው ቢትኮይንን ያስተዋውቁ።",
	"postcards_header": "ፖስት ካርድ ፕሮግራም ተዘግቷል",
	"postcards_program_closed_message": "ነፃ ቢትኮይን ፖስት ካርድ ፕሮግራም ተዘግቷል። በፖስታ አማካኝነት ቢትኮይን ትምህርት ለማስፋፋት ያገዙትን ሁሉ እናመሰግናለን!",
	"postcards_sticker_alternative_header": "ይልቁንም ነፃ ቢትኮይን ስቲከሮች ያግኙ",
	"postcards_sticker_alternative_message": "በነፃ ስቲከር ፕሮግራም ቢትኮይን ግንዛቤ ማስፋፋቱን ይቀጥሉ! ቢትኮይን ስቲከሮች በህዝባዊ ቦታዎች ለማጋራት ምርጥ ናቸው ወደ ትምህርት ይዘት QR ኮድ ያላቸው።",
	"postcards_sticker_cta": "ነፃ ስቲከሮች ያግኙ",
	"postcards_step_2": "ፖስት ካርድ ንድፍ",
	"postcards_instructions_4": "ለሚያውቋቸው ሰው ቢትኮይንን ለማስተዋወቅ ቀላል ለማድረግ ይህን ፖስት ካርድ ሰራን! አድራሻ እና ቴምብር ለጥፈው ፖስት ካርዱን ፖስታ ቤት ያስገቡ።",
	"postcards_instructions_5": "ተልዕኮአችን ቢትኮይን ተቀባይነትን ማፋጠን ነው። ነፃ ስቲከሮች ተቀብለው በህዝባዊ ቦታዎች ለጥፈው ይረዱ!",
	"postcards_instructions_6": "ስለ ቢትኮይን ተጨማሪ ሊማሩ የሚችሉ ሰዎች ዙሪያዎ ይኖራሉ። ዛሬ ቢትኮይን ስቲከሮች ያጋሩ!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "በአሜሪካ ዙሪያ እነዚህን ቢትኮይን ምልክቶች ለማስቀመጥ ይረዱ!",
	"signs_title": "ከbitcoin.rocks ነፃ ቢትኮይን ምልክቶች",
	"signs_choose_header": "በአሜሪካ ዙሪያ እነዚህን ቢትኮይን ምልክቶች ስለሰቀሉ እናመሰግናለን!",
	"signs_choose_c1": "ምልክቶቹ አልቀዋል! ተልዕኮአችን በትምህርት አማካኝነት ቢትኮይን ተቀባይነትን ማፋጠን ነው።",
	"signs_choose_c2": "ብዙ ሰዎች እነዚህን ነፃ ቢትኮይን ምልክቶች በህዝባዊ ቦታዎች ሰቅለው ረድተዋል። ሁሉም ምልክቶች ወደ ትምህርት ገጽ QR ኮድ አላቸው:",
	"signs_choose_c3": "ዋጋ ግሽበት",
	"signs_choose_c4": "ድንቅ ማህበረሰብ ምስጋና ይግባው ሺዎች ሰዎችን ደርሰው ቢትኮይን ቶሎ ጉድጓድ ውስጥ የመጀመሪያ ቆመት እንዲጀምሩ ረድተዋል።",
	"signs_share_header": "የምልክት ቦታዎችዎን ያጋሩ",
	"signs_share_c1": "በNostr ላይ የምልክት ቦታ ፎቶ ያጋሩ ሌሎች ሰዎች ምልክቶቻቸውን የት እንደሚሰቅሉ ይመልከቱ።",
	"signs_btn_share_on_nostr": "በNOSTR ላይ ያጋሩ",
	"signs_btn_what_is_nostr": "NOSTR ምንድን ነው?",
	"signs_instructions_1": "የፖስታ አድራሻዎን ያስገቡ 10 ቢትኮይን ምልክቶች ያለው ሳጥን እንልክልዎታለን!",
	"signs_instructions_2": "የአድራሻ ውሂብ ነፃ ምልክቶች ከተላኩ በኋላ ይሰረዛል።"
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "ከbitcoin.rocks ነፃ ቢትኮይን በራሪ ወረቀቶች",
	"flyers_description": "ቢትኮይን በራሪ ወረቀቶች ቤት አትመው በህዝባዊ ቦታዎች ይለጥፉ።",
	"flyers_header_1": "አትሙ & ይለጥፉ",
	"flyers_header_2": "ቢትኮይን በራሪ ወረቀቶች",
	"flyers_intro_header": "ቢትኮይን በራሪ ወረቀቶች እንዴት ማተም እና መለጠፍ እንደሚቻል",
	"flyers_intro_c1": "ተልዕኮአችን በህዝባዊ ቦታዎች ቢትኮይን በራሪ ወረቀቶች ለጥፎ ብዙ ሰዎች ስለ ቢትኮይን እንዲያውቁ ማድረግ ነው። እነዚህ በራሪ ወረቀቶች ወደ ትምህርታዊ",
	"flyers_intro_c2": "ቢትኮይን ድር ጣቢያችን QR ኮድ አላቸው።",
	"flyers_intro_c3": "ዋጋ ግሽበት",
	"flyers_intro_c4": "እነዚህን በራሪ ወረቀቶች ቤት ወይም ማተሚያ ቤት ያትሙ። ከዚያ በማስታወቂያ ሰሌዳ፣ ምሰሶ ወይም ሰዎች የሚያዩት ህዝባዊ ቦታ ይለጥፉ ስለ ቢትኮይን ያስተምሩ።",
	"flyers_intro_c5": "በራሪ ወረቀቶች ሲለጥፉ ",
	"flyers_intro_c6": "ነፃ ቢትኮይን ስቲከሮች",
	"flyers_intro_c7": " ደግሞ ይጠይቁ ተጨማሪ ሰዎችን ለማስተማር።",
	"flyers_btn_download": "በራሪ ወረቀት ያውርዱ",
	"flyers_btn_print": "በራሪ ወረቀት ያትሙ",
	"flyers_share_header": "በራሪ ወረቀት ቦታዎችዎን ያጋሩ",
	"flyers_share_c1": "በNostr ላይ በራሪ ወረቀት ቦታዎችዎን ያጋሩ ሌሎች ሰዎች የት እንደሚለጥፉ ይመልከቱ።",
	"flyers_btn_share_on_nostr": "በNOSTR ላይ ያጋሩ",
	"flyers_btn_what_is_nostr": "NOSTR ምንድን ነው?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "ይሳተፉ ቢትኮይንን ለማስፋፋት ይረዱ",
	"get_involved_description": "ነፃ ግብዓቶች ቢትኮይን ተቀባይነትን ለማስፋፋት ቀላል ያደርጋሉ።",
	"get_involved_header": "ይሳተፉ",
	"get_involved_header_2": "ቢትኮይንን ያስፋፉ",
	"get_involved_intro_1": "በአሁኑ ዓለም ሁኔታ ውስጥ መኖር ከባድ ሊሆን ይችላል።",
	"get_involved_intro_2": "ገንዘባችን ተበላሽቷል። ከዚህ የተነሳ የህብረተሰብ መሰረታዊ ክፍሎችም ተበላሽተዋል።",
	"get_involved_intro_3": "ቢትኮይንን ቀድሞ ካወቁ ቢትኮይን ሊያመጣ የሚችለውን ተስፋ ያውቃሉ። ይበልጥ ጥሩ ገንዘብ ሊያስችለው ስለሚችል ብሩህ ወደፊት ተስፋ።",
	"get_involved_intro_4": "ግን ዙሪያዎ ብዙ ሰዎች ስለ ቢትኮይን አያውቁም። ልክ እንደ እርስዎ ተበላሸ ዓለም ውስጥ ይኖራሉ ግን ጨለማ ውስጥ ብርሃን የላቸውም።",
	"get_involved_intro_5": "ግን እርስዎ ሊቀይሩት ይችላሉ። ቢትኮይን የሚያመጣውን ተስፋ ለዙሪያዎ ሰዎች ለማስፋፋት ቀላል የሚያደርጉ ብዙ ነፃ ግብዓቶች ሰርተናል።",
	"get_involved_sticker_header": "በህዝባዊ ቦታዎች ስቲከር ይለጥፉ",
	"get_involved_sticker_content_1": "ከማንም ጋር ሳይናገሩ ዙሪያዎ ሰዎችን ስለ ቢትኮይን ማስተማር ይችላሉ። በህዝባዊ ቦታ ነፃ ቢትኮይን ስቲከሮች መለጠፍ ብቻ ያስፈልጋል።",
	"get_involved_sticker_content_2": "በየወሩ በመቶዎች ሰዎች በእነዚህ ስቲከሮች QR ኮድ ይቃኛሉ። ዋጋ ግሽበት ስቲከሮች ወደ",
	"get_involved_sticker_content_3": "እንደ ዋጋ ግሽበት መፍትሄ ቢትኮይን ገጽ ያስፈንጥራሉ።",
	"get_involved_sticker_content_4": "ሌሎች ስቲከሮች ሰዎችን ወደ",
	"get_involved_sticker_content_5": "ቢትኮይን የተሻለ ዓለም እየገነባ መሆኑን የሚያሳይ ትምህርታዊ ዋና ገጽ ያስፈንጥራሉ።",
	"get_involved_sticker_content_6": "ሰዎች ያዩዋቸው ቦታዎች ላይ እነዚህን ስቲከሮች ለጥፈው ዙሪያዎ ሰዎች ቢትኮይን ቶሎ ጉድጓድ ውስጥ የመጀመሪያ ቆመት እንዲጀምሩ ይረዳሉ።",
	"get_involved_request_a": "ይጠይቁ",
	"get_involved_sticker_pack": "ስቲከር ፓኬጅ",
	"get_involved_postcard_header": "ፖስት ካርድ ይላኩ",
	"get_involved_postcard_content_1": "ነፃ ፖስት ካርድ ላክ ለሚያውቋቸው ሰው ቢትኮይን ተስፋ ያስፋፉ።",
	"get_involved_postcard_content_2": "እያንዳንዱ ፖስት ካርድ ጀርባ ስለ ቢትኮይን አሳማኝ ማብራሪያ እና ተጨማሪ ለመማር QR ኮድ አለው።",
	"get_involved_postcard_content_3": "ቢትኮይን ፖስት ካርድ ላኩ ቢትኮይንን በአዲስ ዓይን ሊያዩ እንዲችሉ ይረዷቸው።",
	"get_involved_postcard_pack": "ፖስት ካርድ ፓኬጅ",
	"get_involved_business_header": "ንግዶችን ያስተዋውቁ",
	"get_involved_business_content_1": "ቢትኮይን ዙሪያ ኢኮኖሚ ለመገንባት ይፈልጋሉ? ቢትኮይን ንግድ ኪት ለንግዶች ቢትኮይን ክፍያ መቀበል ቀላል ለማድረግ ይረዳል።",
	"get_involved_business_content_2": "እያንዳንዱ ንግድ ኪት ቢትኮይን ክፍያ መቀበል ጥቅሞችን የሚያሳይ በራሪ ወረቀት ይዟል። እያንዳንዱ በራሪ ወረቀት ወደ የተለያዩ",
	"get_involved_business_content_3": "ነፃ ቢትኮይን ንግድ ግብዓቶች ያስፈንጥራል።",
	"get_involved_business_kit": "ንግድ ኪት"
});

console.log('\nDone! Content files created for Amharic (am).');
