/**
 * Creates Chichewa (ny) translation files for remaining content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ny';
const today = '2026-04-02';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "Bitcoin Ilibe Kuthawa kwa Anthu Kumabanki",
	"bank_runs_header": "BITCOIN ILIBE KUTHAWA KWA ANTHU KUMABANKI",
	"bank_runs_header_2": "KOMA BANKI YANU MWINA ILI NAZO",
	"bank_runs_what": "KUTHAWA KWA ANTHU KUMABANKI NDI CHIYANI?",
	"bank_runs_what_content_1": "Kuthawa kwa anthu kumabanki kumachitika anthu ambiri akayesa kuchotsa ndalama zawo ku banki nthawi imodzi.",
	"bank_runs_what_content_2": "Ngati mabanki alibe ndalama zokwanira kukwaniritsa kuchotsa, amatha kugwa kwathunthu pakachitika kuthawa kwa anthu kumabanki.",
	"bank_runs_how": "KUTHAWA KWA ANTHU KUMABANKI KUMACHITIKA BWANJI?",
	"bank_runs_how_content_1": "Dongosolo lathu la mabanki ndi 'losunga gawo' lomwe likutanthauza kuti mabanki samangosungira ndalama zanu mu chipinda ndi kudikira kuti muzigwiritse ntchito kapena kuzichotsa.",
	"bank_runs_how_content_2": "M'malo mwake, banki yanu imatenga ndalama zanu ndipo imazibwereketsa kapena kuziyika. Izi zimatha kutsekera ndalama zanu kwa nthawi yaitali, ngakhale banki akukulonjezani kuthekera kochotsa ndalama zanu nthawi iliyonse.",
	"bank_runs_how_content_3": "Ndiye chimachitika ndi chiyani mukayesa kuchotsa ndalama zanu banki atabwereketsa kapena kuziyika?",
	"bank_runs_how_content_4": "Si vuto ngati ndinu nokha amene akuyesa kuchotsa. Banki angotenga ndalama za wina ndipo akupatsani. Koma chimachitika ndi chiyani anthu ambiri akayesa kuchotsa nthawi imodzi?",
	"bank_runs_how_content_5": "Anthu ambiri ku USA anazindikira pamene panachitika kuthawa ku Silicon Valley Bank mu March 2023.",
	"bank_runs_how_content_6": "Bankiyo anayika ndalama za makasitomala awo mu ma bondi a boma omwe anatsekeredwa kwa zaka mpaka 30. Kuipirapo, mtengo wa ma bondiwo unagwa kwambiri posachedwa, choncho Silicon Valley Bank sangathe kungogulitsa ma bondi kuti apeze ndalama za oika ndalama. Analibe ndalama zokwanira kukwaniritsa kuchotsa kwa oika ndalama.",
	"bank_runs_how_content_7": "Pamene anthu ambiri anazindikira, vutoli linangokula. Mapempho ambiri ochotsa anabwera, koma ambiri sanayang'aniridwe. Mabizinesi masauzande anazindikira kuti sadzatha kulipira ogwira ntchito awo chifukwa cha kugwa kwa bankiyo.",
	"bank_runs_how_content_8": "FDIC inalowa ndipo inavomereza kubwezera oika ndalama. Vuto lathetsedwa? Osati kwenikweni...",
	"bank_runs_fdic": "KODI INSHULANSI YA FDIC IMATETEZA NDALAMA ZANGA?",
	"bank_runs_fdic_content_1": "Inshulansi ya FDIC yapangidwa kuteteza oika ndalama ku banki ngati banki igwa. Zoikidwa zimatetezedwa mpaka $250,000 pa woika ndalama aliyense. Zikumveka bwino, sichoncho?",
	"bank_runs_fdic_content_2": "Osati kwenikweni. Ngati banki igwa, kodi FDIC imapeza ndalama kuti? Ali ndi ndalama za inshulansi za madola biliyoni 125.",
	"bank_runs_fdic_content_3": "Zimenezi zikumveka ndalama zambiri mpaka mutayerekezera ndi kuchuluka kwa ndalama zoikidwa zomwe amateteza: pafupifupi madola triliyoni 10 kapena biliyoni 10,000.",
	"bank_runs_fdic_content_4": "FDIC amaonetsa pa webusayiti yawo kuti ali ndi ndalama zokwanira mu ndalama zawo za inshulansi kuvundikira pang'ono kupitirira 1% ya ndalama zoikidwa.",
	"bank_runs_fdic_content_5": "Pakagwa banki yomwe ipitirira ndalama za inshulansi ya FDIC, ndi zotheka (koma osatsimikizika) kuti boma la US lingasindikize ndalama kuti libwezere oika ndalama.",
	"bank_runs_fdic_content_6": "Koma kusindikiza ndalama kumapangitsa kukwera kwa mitengo, choncho si yankho labwino.",
	"bank_runs_safe": "KODI PALI MABANKI OMWE SAMAGWIRITSA NTCHITO KUSUNGA GAWO?",
	"bank_runs_safe_content_1": "Mabanki ena ayesera kukhala 'mabanki otetezeka' omwe samabwereketsa kapena kuyika ndalama za oika ndalama.",
	"bank_runs_safe_content_2": "Ngakhale mabanki otetezeka awa akanakhala opanda chiwopsezo cha kuthawa kwa anthu kumabanki, mapempho awo akanidwa ndi Federal Reserve. Izi zikutanthauza kuti sangagwire ntchito mwalamulo ngati mabanki.",
	"bank_runs_safe_content_3": "Chifukwa analetsereka kugwira ntchito, palibe mabanki lero omwe samagwiritsa ntchito kusunga gawo.",
	"bank_runs_safe_content_4": "Mwayi wabwino, pali njira yotulukira mu dongosolo la kusunga gawo kukhala banki yanu. Ayi, sitikuyankhula za kubisa ndalama pansi pa bedi.",
	"bank_runs_safe_content_5": "Kusunga ndalama ndi chiwopsezo cha kukwera kwa mitengo.",
	"bank_runs_safe_content_6": "Tikuyankhula za Bitcoin: dongosolo latsopano la ndalama lomwe limakuthandizani kukhala banki yanu.",
	"bank_runs_protect": "KODI BITCOIN INGANDILETEZE KU KUTHAWA KWA ANTHU KUMABANKI?",
	"bank_runs_protect_content_1": "Inde, Bitcoin ndi dongosolo la ndalama losunga kwathunthu.",
	"bank_runs_protect_content_2": "Kuthawa kwa anthu kumabanki ndikosatheka mu Bitcoin bola muchotse Bitcoin yanu ku chikwama chanu. Musasiye bitcoin yanu pa exchange kapena mu chikuto ngati Bitcoin ETF.",
	"bank_runs_protect_content_3": "Onani Gaidi yathu yosavuta ya Zikwama za Bitcoin kuti muphunzire momwe mungachotsere ku chikwama chanu.",
	"bank_runs_protect_content_4": "Ndi Bitcoin, mungathe kukhala ndi ulamuliro wa ndalama zanu."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Gaidi ya Zikwama za Bitcoin",
	"wallets_description": "Pali zikwama zambiri za Bitcoin zomwe zimasiyana m'njira zofunika. Mutha kudziwa ngati chikwama ndi choyenera kwa inu pofunsa mafunso osavuta awa.",
	"wallets_header": "MOMWE MUNGASUNGIRE BITCOIN YANU MOTETEZEKA",
	"wallets_s1_c1": "Zikwama za Bitcoin zimagwirizana, choncho mutha kutumiza Bitcoin kwa aliyense mosasamala za chikwama chomwe akugwiritsa ntchito.",
	"wallets_s1_c2": "Pali zikwama zambiri za Bitcoin zomwe zimasiyana m'njira zofunika. Mutha kudziwa ngati chikwama ndi choyenera kwa inu pofunsa mafunso osavuta awa:",
	"wallets_question_1": "KODI NDI CHIKWAMA CHOKUSUNGA WEKHA?",
	"wallets_s2_c1": "Chimodzi mwa zatsopano za Bitcoin ndi kuthekera kosungira popanda kudalira wosunga, monga banki.",
	"wallets_s2_c2": "Ngati mukusunga bitcoin pa exchange kapena mu ETF, mumatayirira ufulu wa bitcoin.",
	"wallets_s2_c3": "Zikwama zokusunga wekha zimatsegula mphamvu yonse ya Bitcoin: ndalama zaufulu.",
	"wallets_s2_c4": "Ndi chikwama chokusunga wekha, ndinu nokha amene ali ndi kuthekera kogwiritsa ntchito kapena kutumiza ndalama zanu. Palibe amene angakuletseni kutumiza kapena kulandira ndalama zanu mukagwiritsa ntchito chikwama chokusunga wekha.",
	"wallets_s2_c5": "Zikwama zokusunga wekha zimatchedwanso zikwama zopanda wosunga.",
	"wallets_s3_c1": "Zikwama za wosunga ndi zikwama zomwe simuli ndi ulamuliro wa ndalama zanu.",
	"wallets_s3_c2": "Zikwama izi zimafanana kwambiri ndi dongosolo la mabanki pomwe mukuyenera kukhulupirira wina kukulolezani kupeza ndalama zanu. Ngati Bitcoin yanu ili pa exchange, mukugwiritsa ntchito chikwama cha wosunga.",
	"wallets_s3_c3": "Ngati munagula Bitcoin ETF, mukugwiritsa ntchito chikwama cha wosunga chomwe sichimakuthandizani kuchotsa ku kusunga wekha.",
	"wallets_s3_c4": "Zikwama za wosunga zingaoneke zosavuta, koma wosungayo ali ndi kuthekera ka teknikaili kuba ndalama zonse za ogwiritsa ntchito nthawi iliyonse.",
	"wallets_s3_c5": "Makiyi anu osati, ndalama zanu osati!",
	"wallets_question_2": "KODI NDI CHOTENTHA KAPENA CHOZIZIRA?",
	"wallets_s4_c1": "Zikwama zozizira zimasunga makiyi a Bitcoin yanu munjira yomwe sidzawaoneseratu pa intaneti.",
	"wallets_s4_c2": "Izi zimachepetsa kwambiri njira zomwe mbala ingathe kugwiritsa ntchito kuyesa kuba Bitcoin yanu, ndipo ndi zabwino kwambiri kwa ndalama zambiri za Bitcoin zomwe simukufunika kutumiza kawirikawiri.",
	"wallets_s4_c3": "Mutha kuganizira za chikwama chozizira ngati akaunti yosungira ndalama kwa nthawi yaitali, yotchedwanso kusunga chozizira.",
	"wallets_s5_c1": "Zikwama zotentha zimasunga makiyi a Bitcoin yanu pa chipangizo chomwe chili pa intaneti, monga foni yanu.",
	"wallets_s5_c2": "Zikwama zotentha nthawi zambiri zimaonedwa ngati zotetezeka, koma zingakhale ndi ziwopsezo zambiri kuposa zikwama zozizira.",
	"wallets_s5_c3": "Mutha kuganizira za chikwama chotentha ngati chikwama chooneka. Simungasunga ndalama zanu zonse mu chikwama chanu, koma mungasunge ndalama zogwiritsira ntchito.",
	"wallets_s5_c4": "Zikwama zotentha zimapangitsa kukhala kosavuta kwambiri kugwiritsa ntchito Bitcoin yanu popanda kuchotsa ndalama zanu zonse ku kusungidwa kwachozizira.",
	"wallets_question_3": "NDIDZASUNGA BWANJI MAWU ANGA OBWEZERETSA?",
	"wallets_s6_c1": "Mukakonza chikwama chanu cha Bitcoin, chipangizo chanu chidzapanga mawu obwezeretsa. Mawu obwezeretsa awa (omwe amatchedwa mawu oyambirira) ali ndi mawu 12 kapena 24.",
	"wallets_s6_c2": "Ngati mutayirira mwayi wopeza chikwama chanu kapena chipangizo chanu chiimirira kugwira ntchito, mutha kulowa mawu obwezeretsa awa mu chikwama chatsopano kuti mupeze Bitcoin yanu.",
	"wallets_s6_c3": "Zikwama zambiri zimaphatikiza pepala lolemba mawu anu obwezeretsa, koma anthu ambiri amakonda kusunga mawu awa pa chitsulo. Izi zimapangitsa kukhala kosatheka kutayirira mawu anu obwezeretsa pagwa masoka achilengedwe monga moto kapena chigumula.",
	"wallets_s6_c4": "Jameson Lopp wayesa zipangizo 70 zosunga pa chitsulo kuti akuthandizeni kusankha choyenera kwa inu.",
	"wallets_s6_c5": "Onani gaidi ya Jameson ya kusungira Bitcoin pa chitsulo pano.",
	"wallets_s6_c6": "Kapena pitirizani kumavina kuti mufufuze zikwama za Bitcoin.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "Mukufunafuna Gaidi yathu ya Zikwama za Lightning?",
	"wallets_starter_wallet": "Chikwama chabwino choyambira",
	"wallets_mobile_app": "Pulogalamu ya foni",
	"wallets_2fa_support": "Kuthandizira kwa 2FA",
	"wallets_air_gap_mode": "Njira yopanda ulalo",
	"wallets_air_gap_camera": "Njira yopanda ulalo + kamera",
	"wallets_bitcoin_only": "Bitcoin yokha",
	"wallets_security_features": "Mwayi wambiri wotetezera",
	"wallets_free": "Yaulere 100%",
	"wallets_coldcard_mk5_costs": "Imadya $189",
	"wallets_coldcard_q_costs": "Imadya $289",
	"wallets_blockstream_jade_costs": "Imadya $79",
	"wallets_foundation_passport_costs": "Imadya $199",
	"wallets_seedsigner_costs": "Zigawo zimadya $50",
	"wallets_very_affordable": "Yotsika mtengo kwambiri",
	"wallets_pair_with_phone": "Gwiritsani ntchito ndi foni yanu",
	"wallets_battery": "Batire yochajidwa",
	"wallets_build_your_own": "Pangani yanu",
	"wallets_qwerty_keyboard": "Kibodi yathunthu ya QWERTY",
	"wallets_qr_scanner": "Chosikana cha QR code"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "Momwe Mungagulire Bitcoin - Gaidi Yapang'ono",
	"buy_header": "MOMWE MUNGAGULIRE BITCOIN",
	"buy_intro_c1": "Kugula Bitcoin koyamba kungaoneke kovuta, koma ndikosavuta kwambiri mukagawa m'masitepe.",
	"buy_intro_c2": "Gaidi iyi idzakutsogolerani mu njira yogula Bitcoin motetezeka ndi kuisunga mu chikwama chanu.",
	"buy_step_1_header": "SITEPE 1: SANKHANI DZIKO LANU",
	"buy_step_1_description": "Mayiko osiyanasiyana ali ndi njira zosiyanasiyana zogulira Bitcoin. Sankhani dziko lanu kuti muone njira zabwino kwa inu.",
	"buy_search_countries": "Funafunani dziko lanu",
	"buy_country_united_states": "United States",
	"buy_country_australia": "Australia",
	"buy_country_austria": "Austria",
	"buy_country_belgium": "Belgium",
	"buy_country_brazil": "Brazil",
	"buy_country_canada": "Canada",
	"buy_country_france": "France",
	"buy_country_germany": "Germany",
	"buy_country_ireland": "Ireland",
	"buy_country_italy": "Italy",
	"buy_country_netherlands": "Netherlands",
	"buy_country_new_zealand": "New Zealand",
	"buy_country_spain": "Spain",
	"buy_country_united_kingdom": "United Kingdom",
	"buy_country_argentina": "Argentina",
	"buy_country_chile": "Chile",
	"buy_country_colombia": "Colombia",
	"buy_country_costa_rica": "Costa Rica",
	"buy_country_czech_republic": "Czech Republic",
	"buy_country_denmark": "Denmark",
	"buy_country_el_salvador": "El Salvador",
	"buy_country_estonia": "Estonia",
	"buy_country_finland": "Finland",
	"buy_country_greece": "Greece",
	"buy_country_guatemala": "Guatemala",
	"buy_country_hong_kong": "Hong Kong",
	"buy_country_hungary": "Hungary",
	"buy_country_iceland": "Iceland",
	"buy_country_india": "India",
	"buy_country_israel": "Israel",
	"buy_country_japan": "Japan",
	"buy_country_latvia": "Latvia",
	"buy_country_lithuania": "Lithuania",
	"buy_country_luxembourg": "Luxembourg",
	"buy_country_malta": "Malta",
	"buy_country_mexico": "Mexico",
	"buy_country_norway": "Norway",
	"buy_country_panama": "Panama",
	"buy_country_poland": "Poland",
	"buy_country_portugal": "Portugal",
	"buy_country_romania": "Romania",
	"buy_country_singapore": "Singapore",
	"buy_country_slovakia": "Slovakia",
	"buy_country_slovenia": "Slovenia",
	"buy_country_south_africa": "South Africa",
	"buy_country_south_korea": "South Korea",
	"buy_country_sweden": "Sweden",
	"buy_country_switzerland": "Switzerland",
	"buy_country_thailand": "Thailand",
	"buy_country_turkey": "Turkey",
	"buy_country_ukraine": "Ukraine",
	"buy_country_uruguay": "Uruguay",
	"buy_step_2_header": "SITEPE 2: SANKHANI NJIRA YANU YOLIPIRA",
	"buy_step_2_description": "Pali njira ziwiri zazikulu zogulira Bitcoin: kutumiza ndalama ku banki kapena ndalama. Iliyonse ili ndi phindu lake.",
	"buy_method_bank_transfer": "KUTUMIZA NDALAMA KU BANKI",
	"buy_method_bank_fast": "Mwachangu ndi Mosavuta",
	"buy_method_bank_less_private": "Yochepa Chinsinsi",
	"buy_method_bank_description": "Kutumiza ndalama ku banki ndi njira yodziwika kwambiri yogulira Bitcoin. Ndi yachangu, yosavuta, ndipo nthawi zambiri ili ndi malipiro ochepa.",
	"buy_method_choose_bank": "Sankhani Kutumiza ku Banki",
	"buy_method_cash": "NDALAMA",
	"buy_method_cash_private": "Yambiri Chinsinsi",
	"buy_method_cash_limited": "Njira Zocheperako",
	"buy_method_cash_description": "Kugula ndi ndalama kumapereka chinsinsi chambiri koma njira ndi zochepa ndipo zingafune kukumana ndi munthu kapena kugwiritsa ntchito Bitcoin ATM.",
	"buy_method_choose_cash": "Sankhani Ndalama",
	"buy_step_3_header": "SITEPE 3: NJIRA ZOGULIRA",
	"buy_step_3_description": "Nayi njira zabwino kwambiri zogulira Bitcoin kwa dziko lanu ndi njira yanu yolipira:",
	"buy_platform_recommended": "YOMALINGALIRIDWA",
	"buy_platform_strike_description": "Strike ndi njira yachangu ndi yosavuta kwambiri yogulira Bitcoin ndi malipiro ochepa ndi kuthandizira kwa Lightning Network.",
	"buy_platform_swan_description": "Swan Bitcoin imapereka ntchito za Bitcoin yokha ndi kugula kwapang'ono kwapang'ono ndi zinthu zophunzitsa.",
	"buy_platform_river_description": "River imapereka kugula Bitcoin, kufukula, ndi kusunga ndi cholinga cha maphunziro ndi chitetezo.",
	"buy_platform_coinsquare_description": "Coinsquare ndi msika wa Bitcoin wa ku Canada wokhala ndi malamulo olimba ndi kuthandizira makasitomala.",
	"buy_platform_kraken_description": "Kraken ndi msika wa Bitcoin wokhazikika wokhala ndi mwayi wapamwamba wa malonda ndi chitetezo cholimba.",
	"buy_platform_atm_description": "Ma ATM a Bitcoin amakuthandizani kugula Bitcoin ndi ndalama nthawi yomweyo. Pezani wapafupi pogwiritsa ntchito Coin ATM Radar.",
	"buy_platform_bisq_description": "Bisq ndi msika wopanda anthu apakati wopakati pa anthu womwe umalola kugula Bitcoin mwachinsinsi popanda KYC.",
	"buy_platform_feature_instant": "Kugula nthawi yomweyo",
	"buy_platform_feature_low_fees": "Malipiro ochepa",
	"buy_platform_feature_lightning": "Lightning Network",
	"buy_platform_feature_dca": "Kugula kwapang'ono kwapang'ono",
	"buy_platform_feature_education": "Zinthu zophunzitsa",
	"buy_platform_feature_withdrawal": "Kuchotsa mosavuta",
	"buy_platform_feature_mining": "Kufukula Bitcoin",
	"buy_platform_feature_custody": "Ntchito zosungira",
	"buy_platform_feature_canadian": "Yoganizira Canada",
	"buy_platform_feature_regulated": "Msika wolamulira",
	"buy_platform_feature_support": "Kuthandizira makasitomala",
	"buy_platform_feature_established": "Pulatifomu yokhazikika",
	"buy_platform_feature_security": "Chitetezo cholimba",
	"buy_platform_feature_advanced": "Mwayi wapamwamba",
	"buy_platform_feature_cash": "Kugula ndi ndalama",
	"buy_platform_feature_anonymous": "Yodzibisitsa kwambiri",
	"buy_platform_feature_p2p": "Pakati pa anthu",
	"buy_platform_feature_private": "Kugulitsa kwachinsinsi",
	"buy_platform_feature_decentralized": "Yogawidwa",
	"buy_platform_relai_description": "Relai ndi pulogalamu ya Bitcoin yokha ya ku Switzerland ndi chikwama chokusunga wekha, kugula mwachindunji, ndi malipiro ochepa kwa ogwiritsa ntchito ku Europe.",
	"buy_platform_feature_bitcoin_only": "Bitcoin yokha",
	"buy_platform_feature_self_custody": "Chikwama chokusunga wekha",
	"buy_platform_feature_auto_invest": "Dongosolo logula mwachindunji",
	"buy_platform_feature_european": "Yoganizira Europe",
	"buy_step_4_header": "SITEPE 4: SUNGANI BITCOIN YANU MOTETEZEKA",
	"buy_step_4_c1": "Mutagula Bitcoin, sitepe lofunika kwambiri ndi kuisamutsira ku chikwama chanu pomwe mumalamulira makiyi anu.",
	"buy_step_4_c2": "Kusiya Bitcoin pa exchange ndi chiwopsezo chifukwa simuli ndi Bitcoin kwenikweni - msikayo ndiye ali nayo.",
	"buy_step_4_c3": "Mukalamulira makiyi anu, muli ndi umwini weniweni wa Bitcoin yanu ndipo palibe amene angaitenge.",
	"buy_step_4_c4": "Phunzirani momwe mungasankhire chikwama cha Bitcoin choyenera:",
	"buy_cta_wallets": "Onani Gaidi Yathu ya Zikwama za Bitcoin"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Gaidi ya Zikwama za Bitcoin Lightning",
	"lightning_description": "Zikwama za Lightning zimakuthandizani kutumiza Bitcoin mwachangu ndi mwatsika mtengo pomwe mukusunga umwini wanu.",
	"lightning_header": "GAIDI YA ZIKWAMA ZA LIGHTNING",
	"lightning_s1_c1": "Lightning imakuthandizani kutumiza malipiro a Bitcoin mwachangu ndi mwatsika mtengo.",
	"lightning_s1_c2": "N'kofunika kudziwa kuti kugwiritsa ntchito Lightning kumabweretsa kusinthana. Posinthirana malipiro a Bitcoin achangu ndi otsika mtengo, nthawi zambiri mumachepetsa chitetezo china.",
	"lightning_s1_c3": "Nthawi zambiri, Lightning iyenera kugwiritsidwa ntchito ndi ndalama zing'onozing'ono za bitcoin yokha. Ndalama zambiri za bitcoin ziyenera kusungidwa mu chikwama cha chipangizo.",
	"lightning_s1_c4": "Onani Gaidi yathu ya Zikwama za Chipangizo kuti mudziwe zambiri.",
	"lightning_s1_c5": "Zikwama zonse za Lightning si zofanana. Mutha kudziwa chikwama chomwe chili ndi kusinthana koyenera kwa inu pofunsa funso limodzi losavuta:",
	"lightning_question_1": "NDI KUSINTHANA KOTANI KOMWE NDI KOYENERA KWA INE?",
	"lightning_s2_c1": "Chimodzi mwa zatsopano za Bitcoin ndi kuthekera kosungira popanda kudalira wosunga, monga banki. Zikwama zokusunga wekha zimatsegula mphamvu yonse ya Bitcoin.",
	"lightning_s2_c2": "Ndi chikwama chokusunga wekha, ndinu nokha amene ali ndi kuthekera kogwiritsa ntchito kapena kutumiza ndalama zanu. Palibe amene angakuletseni, kukutsekani, kapena kukubani mukagwiritsa ntchito chikwama chokusunga wekha. Izi zimatchedwanso zikwama zopanda wosunga.",
	"lightning_s2_c3": "Njira yaufulu kwambiri yogwiritsira ntchito Lightning ndi kuthamanga node yanu.",
	"lightning_s2_c4": "Gaidi iyi imakhala yokhudza zikwama za Lightning zosavuta zomwe sizifuna node yanu.",
	"lightning_s2_c5": "N'kofunika kudziwa kuti ngakhale pogwiritsa ntchito chikwama cha Lightning chopanda wosunga, mukudalirabe wopanga chikwamayo kuti asatumize zosintha zoyipa ndi kuba ndalama zanu.",
	"lightning_s3_c1": "Zikwama za wosunga ndi zikwama zomwe simuli ndi ulamuliro wa ndalama zanu.",
	"lightning_s3_c2": "Zikwama izi zimafanana kwambiri ndi dongosolo la mabanki pomwe mukuyenera kukhulupirira wina kukulolezani kupeza ndalama zanu.",
	"lightning_s3_c3": "Zikwama za wosunga zingaoneke zosavuta, koma wosungayo ali ndi kuthekera ka teknikaili kuba ndalama zonse za ogwiritsa ntchito nthawi iliyonse.",
	"lightning_s3_c4": "Anthu ena amakonda zikwama za Lightning za wosunga kwa ndalama zing'onozing'ono za bitcoin chifukwa ndi zosavuta kugwiritsa ntchito. Kumbukirani: makiyi anu osati, ndalama zanu osati!",
	"lightning_question_2": "SANKHANI CHIKWAMA CHANU",
	"lightning_s4_c1": "Ndi izi zonse m'maganizo, tsopano mutha kusankha chikwama cha Lightning chokhala ndi kusinthana koyenera kwa inu.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "Mwayi wochuluka",
	"lightning_mobile_app": "Pulogalamu ya foni",
	"lightning_free": "Yaulere 100%",
	"lightning_merchants": "Yabwino kwa amalonda",
	"lightning_starter": "Chikwama chabwino choyambira",
	"lightning_browser": "Chogwira ntchito pa msakatuli",
	"lightning_custodial": "Chikwama chathunthu cha wosunga",
	"lightning_cta_hardware": "Mukufunafuna Gaidi yathu ya Zikwama za Chipangizo za Bitcoin?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "Zitikiti za Bitcoin zaulere kuchokera ku bitcoin.rocks",
	"stickers_description": "Yikani chitikiti cha Bitcoin poyera kuti anthu okhala nawo pafupi aphunzire.",
	"stickers_header": "ZITIKITI ZA BITCOIN ZAULERE",
	"stickers_choose_header": "SANKHANI PAKETI YANU YA ZITIKITI",
	"stickers_choose_c1": "Cholinga chathu ndi kukuthandizani kubweretsa anthu ambiri ku Bitcoin poyika zitikiti za Bitcoin poyera. Zitikiti zathu zonse zili ndi ma QR code omwe amalumikizana ndi masamba ophunzitsa za",
	"stickers_choose_c2": "Bitcoin",
	"stickers_choose_c3": "kukwera kwa mitengo",
	"stickers_choose_c4": "Sankhani paketi yanu ya zitikiti pansipa",
	"stickers_text_pack": "PAKETI YA MAWU",
	"stickers_signs_pack": "PAKETI YA ZIZINDIKIRO",
	"stickers_instructions_1": "Lembani adilesi yanu ndipo tikutumizani Paketi ya Zitikiti za Bitcoin zaulere mu kalata! Zitikiti zanu zitumizidwa mu envelopu yoyera.",
	"stickers_instructions_2": "Deta ya adilesi imachotsedwa zitikiti zanu zaulere zikatumizidwa.",
	"stickers_share_header": "GAWANANI MALO ANU A ZITIKITI",
	"stickers_share_c1": "Gawanani malo anu a zitikiti nafe pa Nostr ndipo muone kumene anthu ena akuyika zitikiti zawo.",
	"stickers_btn_share_on_nostr": "GAWANANI PA NOSTR",
	"stickers_btn_what_is_nostr": "NOSTR NDI CHIYANI?",
	"stickers_flyers_link_before": "Pomwe mukuchita izi, sindikizani ndi kutchera ",
	"stickers_flyers_link_text": "mapepala a Bitcoin",
	"stickers_flyers_link_after": " kuti muthandize kubweretsa anthu ambiri ku Bitcoin.",
	"stickers_country_global_print": "Padziko lonse — Sindikizani zitikiti zanga",
	"stickers_country_global_order": "Padziko lonse — Odolani zambiri",
	"placeholder_name_optional": "Dzina (osafunika)",
	"placeholder_address_line_1": "Adilesi Mzere 1",
	"placeholder_address_line_2": "Adilesi Mzere 2 (osafunika)",
	"placeholder_city": "Mzinda",
	"placeholder_state": "Chigawo",
	"placeholder_province": "Chigawo",
	"placeholder_zip_code": "Nambala ya Zipcode",
	"placeholder_postal_code": "Nambala ya Pakalata",
	"placeholder_language": "Chilankhulo",
	"placeholder_which_stickers": "Zitikiti ziti?",
	"placeholder_email_optional": "Lembani imelo yanu kuti mudziwe (osafunika)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "Makadi a Bitcoin aulere kuchokera ku bitcoin.rocks",
	"postcards_description": "Pezani Paketi ya Makadi a Bitcoin aulere ndipo mugawane Bitcoin ndi munthu amene mumudziwa.",
	"postcards_header": "PULOGALAMU YA MAKADI YATSEKEKA",
	"postcards_program_closed_message": "Pulogalamu yathu ya makadi a Bitcoin aulere yatha. Zikomo kwa aliyense amene anatengapo mbali pofalitsa maphunziro a Bitcoin kudzera mu kalata!",
	"postcards_sticker_alternative_header": "PEZANI ZITIKITI ZA BITCOIN ZAULERE M'MALO MWAKE",
	"postcards_sticker_alternative_message": "Pitirizani kufalitsa kudziwa kwa Bitcoin ndi pulogalamu yathu ya zitikiti zaulere! Zitikiti zathu za Bitcoin ndi zabwino kwambiri kugawana pamalo oyera ndipo zili ndi ma QR code omwe amalumikizana ndi zomwe zaphunzitsa.",
	"postcards_sticker_cta": "PEZANI ZITIKITI ZAULERE",
	"postcards_step_2": "MOMWE MAKADI ANKAONEKERA",
	"postcards_instructions_4": "Tinapanga makadi awa kuti tikhale mosavuta kubweretsa munthu amene mumudziwa ku Bitcoin! Wonjezani adilesi ndi sitampu ndipo muyike khadi lanu mu kalata.",
	"postcards_instructions_5": "Cholinga chathu ndi kufulumizitsa kugwiritsiridwa ntchito kwa Bitcoin. Mutha kuthandiza popeza zitikiti zaulere ndi kuziyika pamalo oyera!",
	"postcards_instructions_6": "Tonse timadziwa anthu angapo omwe angapindule ndi kuphunzira zambiri za Bitcoin. Gawanani zitikiti za Bitcoin ndi iwo lero!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "Tithandizeni kuyika Zizindikiro izi za Bitcoin ku America konse!",
	"signs_title": "Zizindikiro za Bitcoin zaulere kuchokera ku bitcoin.rocks",
	"signs_choose_header": "ZIKOMO POTHANDIZA KUYIKA ZIZINDIKIRO IZI ZA BITCOIN KU AMERICA KONSE!",
	"signs_choose_c1": "Tsopano tatha zizindikiro kwathunthu! Cholinga chathu ndi kufulumizitsa kugwiritsiridwa ntchito kwa Bitcoin kudzera mu maphunziro.",
	"signs_choose_c2": "Ambiri anu munathandiza poyika zizindikiro izi za Bitcoin zaulere poyera. Zizindikiro zathu zonse zili ndi ma QR code omwe amalumikizana ndi tsamba lophunzitsa za",
	"signs_choose_c3": "kukwera kwa mitengo",
	"signs_choose_c4": "Chifukwa cha gulu lathu lodabwitsa, tinafika kwa anthu masauzande ndi kuwathandiza kuyamba ulendo wawo wa Bitcoin.",
	"signs_share_header": "GAWANANI MALO ANU A ZIZINDIKIRO",
	"signs_share_c1": "Gawanani chithunzi cha malo anu a zizindikiro nafe pa Nostr ndipo muone kumene anthu ena akuyika zizindikiro zawo.",
	"signs_btn_share_on_nostr": "GAWANANI PA NOSTR",
	"signs_btn_what_is_nostr": "NOSTR NDI CHIYANI?",
	"signs_instructions_1": "Lembani adilesi yanu ndipo tikutumizani bokosi la zizindikiro 10 za Bitcoin mu kalata!",
	"signs_instructions_2": "Deta ya adilesi imachotsedwa zizindikiro zanu zaulere zikatumizidwa."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "Mapepala a Bitcoin aulere kuchokera ku bitcoin.rocks",
	"flyers_description": "Sindikizani pepala la Bitcoin kunyumba ndipo muliyike poyera kuti anthu okhala nawo pafupi aphunzire.",
	"flyers_header_1": "SINDIKIZANI NDI KUTCHERA",
	"flyers_header_2": "MAPEPALA A BITCOIN",
	"flyers_intro_header": "MOMWE MUNGASINDIKIZIRE NDI KUTCHERA MAPEPALA A BITCOIN AWA",
	"flyers_intro_c1": "Cholinga chathu ndi kukuthandizani kubweretsa anthu ambiri ku Bitcoin poyika mapepala a Bitcoin poyera. Pepala ili ndi QR code yomwe imalumikizana ndi",
	"flyers_intro_c2": "webusayiti yathu yophunzitsa ya Bitcoin.",
	"flyers_intro_c3": "kukwera kwa mitengo",
	"flyers_intro_c4": "Sindikizani pepala ili kunyumba kwanu kapena ku malo osindikizira. Kenako, liyikeni pa mabodo a zizindikiro, mitengo ya foni mdera lanu, ndi malo ena oyera pomwe anthu angathe kuliona ndi kuphunzira za Bitcoin.",
	"flyers_intro_c5": "Pomwe mukuchita izi, pemphani paketi ya",
	"flyers_intro_c6": "zitikiti za Bitcoin zaulere",
	"flyers_intro_c7": "kuti muthandize kubweretsa anthu ambiri ku Bitcoin.",
	"flyers_btn_download": "TSITSANI PEPALA",
	"flyers_btn_print": "SINDIKIZANI PEPALA",
	"flyers_share_header": "GAWANANI MALO ANU A MAPEPALA",
	"flyers_share_c1": "Gawanani malo anu a mapepala nafe pa Nostr ndipo muone kumene anthu ena akuyika mapepala awo.",
	"flyers_btn_share_on_nostr": "GAWANANI PA NOSTR",
	"flyers_btn_what_is_nostr": "NOSTR NDI CHIYANI?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "Tengani nawo mbali ndi kuthandiza kufalitsa Bitcoin",
	"get_involved_description": "Zipangizo zathu zaulere zimapangitsa kukhala kosavuta kufalitsa Bitcoin.",
	"get_involved_header": "TENGANI NAWO MBALI",
	"get_involved_header_2": "FALITSANI BITCOIN",
	"get_involved_intro_1": "Zingakhale zomvetsa chisoni kukhala mu dziko lino masiku ano.",
	"get_involved_intro_2": "Ndalama zathu zathyoka. Chifukwa chake, mbali zofunika za chikhalidwe zathokanso.",
	"get_involved_intro_3": "Ngati muli mu Bitcoin kale, mudziwa chikhumbo chomwe Bitcoin imabweretsa. Chiyembekezo cha tsogolo lowala lopangidwa ndi ndalama zabwino.",
	"get_involved_intro_4": "Koma anthu ambiri okhala nawo pafupi sadziwa za Bitcoin. Akukhala mu dziko lomwelo lothyoka ngati inu, koma popanda chiyembekezo chowathandiza kudutsa mdima.",
	"get_involved_intro_5": "Koma mutha kuthandiza kusintha. Tapanga zipangizo zambiri zaulere kuti zikhale zosavuta kufalitsa chiyembekezo chomwe Bitcoin imabweretsa kwa okhala nawo pafupi.",
	"get_involved_sticker_header": "Yikani chitikiti poyera",
	"get_involved_sticker_content_1": "Mutha kuthandiza kuphunzitsa okhala nawo pafupi za Bitcoin popanda kulankhulana ndi aliyense. Yikani chimodzi mwa zitikiti zathu zaulere za Bitcoin poyera.",
	"get_involved_sticker_content_2": "Anthu mazana amasikana ma QR code pa zitikiti izi mwezi uliwonse. Zitikiti za kukwera kwa mitengo zimalumikizana ndi tsamba la",
	"get_involved_sticker_content_3": "Bitcoin ngati yankho la kukwera kwa mitengo.",
	"get_involved_sticker_content_4": "Zitikiti zina zimalumikizana ndi tsamba lathu loyambirira lophunzitsa lomwe limaonetsa anthu momwe",
	"get_involved_sticker_content_5": "Bitcoin ikumanga dziko labwino.",
	"get_involved_sticker_content_6": "Poyika zitikiti izi mdera lanu pamalo omwe anthu aziona, mutha kuthandiza okhala nawo pafupi kuyamba ulendo wawo wa Bitcoin.",
	"get_involved_request_a": "PEMPHANI",
	"get_involved_sticker_pack": "PAKETI YA ZITIKITI",
	"get_involved_postcard_header": "Tumizani khadi",
	"get_involved_postcard_content_1": "Mutha kuthandiza kufalitsa Chiyembekezo cha Bitcoin kwa munthu amene mumudziwa potumiza khadi limodzi la makadi athu aulere.",
	"get_involved_postcard_content_2": "Kumbuyo kwa khadi lililonse kuli ndi mawu olimbikitsa za Bitcoin pamodzi ndi QR code kuti muphunzire zambiri.",
	"get_involved_postcard_content_3": "Potumiza khadi la Bitcoin kwa munthu, mutha kuwathandiza kuona Bitcoin munjira yatsopano.",
	"get_involved_postcard_pack": "PAKETI YA MAKADI",
	"get_involved_business_header": "Bweretsani bizinesi",
	"get_involved_business_content_1": "Mukufuna kuthandiza kumanga chuma cha Bitcoin? Chipangizo chathu cha Bizinesi cha Bitcoin chimapangitsa kukhala kosavuta kuyankhulana ndi bizinesi za kulandira malipiro a Bitcoin.",
	"get_involved_business_content_2": "Chipangizo chilichonse cha bizinesi chimaphatikiza mapepala omwe amasonyeza phindu lolandira malipiro a Bitcoin. Pepala lililonse limalumikizana ndi",
	"get_involved_business_content_3": "zipangizo zaulere za bizinesi za Bitcoin.",
	"get_involved_business_kit": "CHIPANGIZO CHA BIZINESI"
});

console.log('\nDone! Content files created for Chichewa (ny).');
