/**
 * Creates Filipino (fil) translation for index.json (~130+ keys)
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'fil';
const today = '2026-04-04';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"bitcoin_builds_a_better_world": "Ang Bitcoin ay bumubuo ng mas magandang mundo.",
	"home_description": "Ang Bitcoin ay mas magandang pera na bumubuo ng mas magandang mundo. Pinoprotektahan ng Bitcoin ang mga karapatang pantao, naililigtas ang mga tao mula sa mataas na inflation, sinusuportahan ang mga lokal na magsasaka, binabawasan ang mga emisyon mula sa pagmimina ng langis, at marami pang iba.",
	"home_intro": "Ang Bitcoin ay mas magandang pera na bumubuo ng mas magandang mundo. Pindutin ang isang kategorya sa ibaba upang malaman kung paano pinapaganda ng Bitcoin, o mag-scroll lang upang mag-explore.",
	"home_btn_money": "MAS MAGANDANG PERA",
	"home_btn_salary": "ANG IYONG SAHOD",
	"home_btn_freedom": "KALAYAAN",
	"home_btn_human_rights": "KARAPATANG PANTAO",
	"home_btn_equality": "PAGKAKAPANTAY-PANTAY",
	"home_btn_property_rights": "KARAPATAN SA ARI-ARIAN",
	"home_btn_housing": "PABAHAY",
	"home_btn_business": "NEGOSYO",
	"home_btn_crowdfunding": "CROWDFUNDING",
	"home_btn_energy": "ENERHIYA",
	"home_btn_environment": "ANG KAPALIGIRAN",
	"home_btn_food": "PAGKAIN",
	"home_btn_art": "SINING",
	"home_btn_politics": "PULITIKA",
	"home_btn_war": "DIGMAAN",
	"home_btn_coding": "CODING",
	"home_btn_networks": "MGA NETWORK",
	"home_btn_payments": "MGA PAGBABAYAD",
	"home_btn_self_custody": "SELF-CUSTODY",
	"home_btn_you": "IKAW",
	"home_section_bitcoin_is": "ANG BITCOIN AY",
	"home_section_bitcoin_and": "BITCOIN AT",
	"home_link_type_website": "WEBSITE",
	"home_link_type_video": "VIDEO",
	"home_link_type_article": "ARTIKULO",
	"home_link_type_podcast": "PODCAST",
	"home_link_type_business_kit": "BUSINESS KIT",
	"home_link_type_data": "DATA",
	"home_link_type_research": "PANANALIKSIK",
	"home_link_type_story": "KWENTO",
	"home_link_type_book_excerpt": "SIPI NG LIBRO",
	"home_link_type_street_art": "STREET ART",
	"home_link_type_outreach": "OUTREACH",
	"home_link_type_campaign": "KAMPANYA",
	"home_link_type_software": "SOFTWARE",
	"home_link_type_hardware": "HARDWARE",
	"home_link_type_guide": "GABAY",
	"home_link_type_email": "EMAIL",
	"home_link_title_inflation": "Walang Inflation ang Bitcoin",
	"home_link_title_bank_runs": "Walang Bank Run ang Bitcoin",
	"home_link_title_gold": "Bitcoin vs Gold",
	"home_link_title_crypto": "Bitcoin vs Crypto",
	"home_link_title_cash": "Bitcoin vs Cash",
	"home_link_title_bonds": "Bitcoin vs Bonds",
	"home_link_title_cbdc": "Bitcoin vs CBDCs",
	"home_link_title_your_salary_1": "Alamin kung magkano ang kailangang dagdag sa iyong sahod upang makasabay sa inflation.",
	"home_link_title_freedom_1": "Bakit Mahalaga ang Bitcoin para sa Kalayaan",
	"home_link_title_freedom_2": "Nag-aalok ang Bitcoin ng kalayaan mula sa pampulitikang panunupil",
	"home_link_title_human_rights_1": "Paano Pinapatupad ng Bitcoin ang Karapatang Pantao",
	"home_link_title_human_rights_2": "Ang Tahimik na Rebolusyon ng Bitcoin sa Africa",
	"home_link_title_human_rights_3": "Pinoprotektahan ng Bitcoin ang Karapatang Pantao sa Buong Mundo",
	"home_link_title_equality_1": "Nagdadala ng Pag-asa at Pagkakataon ang Bitcoin sa mga South African",
	"home_link_title_equality_2": "Paano Maaaring Maging Game Changer ang Bitcoin para sa mga Black American",
	"home_link_title_property_rights_1": "Ang Bitcoin ang Perpektong Anyo ng Ari-arian",
	"home_link_title_property_rights_2": "Bitcoin vs Real Estate",
	"home_link_title_housing_1": "Paano Gagawing Abot-kaya Muli ng Bitcoin ang Pabahay",
	"home_link_title_business_3": "Bitcoin vs Stocks",
	"home_link_title_business_1": "Alamin Kung Bakit Maganda ang Bitcoin para sa Negosyo",
	"home_link_title_business_2": "Hikayatin ang Isang Lokal na Negosyo na Tumanggap ng Bitcoin",
	"home_link_title_crowdfunding_1": "Paano Pinaandar ng Bitcoin ang Pinakamalaking Protesta sa Nigeria sa Isang Henerasyon",
	"home_link_title_crowdfunding_2": "Ang Protesta ng mga Canadian Trucker ay Nakakalap ng Pera sa Bitcoin matapos I-block ng GoFundMe ang mga Donasyon",
	"home_link_title_crowdfunding_3": "Geyser = Crowdfund gamit ang Bitcoin",
	"home_link_title_energy_1": "Paano Pinapanatag ng Bitcoin ang Texas Power Grid",
	"home_link_title_energy_2": "Bakit gumagamit ng enerhiya ang Bitcoin?",
	"home_link_title_energy_3": "Hindi problema ang paggamit ng enerhiya ng Bitcoin. Narito kung bakit.",
	"home_link_title_energy_4": "Pinapanatag ng bitcoin mining ang mga power grid sa pamamagitan ng Demand Response",
	"home_link_title_energy_5": "Ang mga bitcoin miner ay nagdadala ng hydro power sa mga rural na komunidad ng Africa",
	"home_link_title_energy_6": "Paano Hinihikayat ng Bitcoin ang Renewable Energy",
	"home_link_title_environment_1": "Paano binabawasan ng bitcoin mining ang global methane emissions",
	"home_link_title_environment_2": "Paano nailigtas ng bitcoin mining ang isang National Park",
	"home_link_title_environment_3": "Ang Bitcoin ang pinaka-green na industriya sa buong mundo!",
	"home_link_title_environment_4": "Pinipigilan ng bitcoin mining ang natural gas na flare mula sa pagkontamina sa atmospera",
	"home_link_title_food_1": "Paano Nakakaapekto ang Inflation sa Presyo ng Pagkain",
	"home_link_title_food_2": "Paano Masama ang Fiat Money para sa Pagkain, Bukirin, at Lupa",
	"home_link_title_fine_art": "Bitcoin vs Fine Art",
	"home_link_title_art_1": "Sumali sa aming Bitcoin Sticker Initiative",
	"home_link_title_art_2": "Magpadala ng Bitcoin Postcard sa isang taong kilala mo",
	"home_link_title_art_3": "Mag-print at Mag-post ng mga Bitcoin Flyer",
	"home_link_title_politics_1": "Ang Bitcoin ay isang Political Paradox",
	"home_link_title_politics_2": "Maaari Kang Bumoto para sa Mas Magandang Pera",
	"home_link_title_war_1": "Paano Matatapos ng Bitcoin ang Walang Katapusang Digmaan",
	"home_link_title_war_2": "Bitcoin at mga Beterano: Isang Natural na Pagkakaisa",
	"home_link_title_war_3": "Paano Tinutulungan ng Bitcoin ang mga Sibilyan na Tumakas sa Digmaan sa Sudan",
	"home_link_title_coding_1": "Isang Interactive na Tutorial tungkol sa Technical na Bahagi ng Bitcoin",
	"home_link_title_coding_2": "bitcoinSwitch: i-retrofit ang anumang device para tumanggap ng Bitcoin",
	"home_link_title_coding_3": "I-code ang daan mo sa mga misteryo ng Bitcoin",
	"home_link_title_networks_1": "Isang live na view ng Bitcoin network",
	"home_link_title_networks_2": "Bitcoin vs Banks",
	"home_link_title_payments_1": "Bitcoin vs Visa",
	"home_link_title_payments_2": "Isang Pagtingin sa Lightning Network (Instant na Pagbabayad sa Bitcoin)",
	"home_link_title_payments_3": "Ang Bitcoin wallet ng El Salvador ay maaaring makatipid sa mga Salvadorean ng $400M taun-taon sa mga bayarin sa remittance",
	"home_link_title_payments_4": "Kunin ang Iyong Lightning Address upang Tumanggap ng Instant na Pagbabayad sa Bitcoin",
	"home_link_title_self_custody_1": "Paano Ligtas na Iimbak ang Iyong Bitcoin",
	"home_link_title_self_custody_2": "6 na Dahilan upang I-withdraw ang Iyong Bitcoin mula sa mga Exchange",
	"home_link_title_self_custody_3": "Gold, Bitcoin, at Self-Custody",
	"home_link_title_get_started_1": "Matuto ng mga pangunahing kaalaman sa Bitcoin",
	"home_link_title_get_started_2": "Kumuha ng iyong unang Bitcoin Wallet",
	"home_link_title_get_started_3": "Paano Bumili ng Bitcoin",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Compound Inflation Calculator",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! index.json created for Filipino (fil).');
