/**
 * Creates Filipino (fil) translation files for remaining content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'fil';
const today = '2026-04-04';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "Walang Bank Run ang Bitcoin",
	"bank_runs_header": "WALANG BANK RUN ANG BITCOIN",
	"bank_runs_header_2": "PERO ANG IYONG BANGKO AY MAAARING MAGKAROON",
	"bank_runs_what": "ANO ANG BANK RUN?",
	"bank_runs_what_content_1": "Nangyayari ang bank run kapag sobrang dami ng tao ang nagsusumikap na mag-withdraw ng kanilang pera mula sa bangko sa parehong oras.",
	"bank_runs_what_content_2": "Kung ang mga bangko ay walang sapat na pera na available upang tumugma sa mga withdrawal, maaari silang ganap na bumagsak kapag nangyari ang bank run.",
	"bank_runs_how": "PAANO NANGYAYARI ANG MGA BANK RUN?",
	"bank_runs_how_content_1": "Ang ating sistema ng pagbabangko ay 'fractional reserve' na nangangahulugang ang mga bangko ay hindi lang basta nagtatago ng iyong pera sa isang vault at naghihintay na gastusin mo ito o i-withdraw.",
	"bank_runs_how_content_2": "Sa halip, kinukuha ng iyong bangko ang iyong pera at ipinapahiram o ini-invest ito. Maaari itong i-lock ang iyong pera sa mahabang panahon, kahit na ang bangko ay nangangako sa iyo ng kakayahang i-withdraw ang iyong pera anumang oras.",
	"bank_runs_how_content_3": "Kaya ano ang mangyayari kung susubukan mong i-withdraw ang iyong pera matapos na ipahiram o i-invest na ito ng bangko?",
	"bank_runs_how_content_4": "Hindi ito problema kung ikaw lang ang nagsusumikap na mag-withdraw. Kukunin lang ng bangko ang pera ng ibang tao at ibibigay sa iyo sa halip. Ngunit ano ang mangyayari kapag sobrang dami ng tao ang nagsusumikap na mag-withdraw sa parehong oras?",
	"bank_runs_how_content_5": "Maraming tao sa USA ang nalaman nang magkaroon ng bank run sa Silicon Valley Bank noong Marso 2023.",
	"bank_runs_how_content_6": "Ini-invest ng bangko ang pera ng kanilang mga customer sa mga government bond na naka-lock hanggang 30 taon. Mas masama pa, ang halaga ng mga bond na iyon ay bumagsak nang malaki kamakailan, kaya hindi basta-basta maibebenta ng Silicon Valley Bank ang mga bond upang makuha ang pera ng kanilang mga depositor. Sila ay insolvent. Wala silang sapat na pera upang tumugma sa mga withdrawal ng kanilang mga depositor.",
	"bank_runs_how_content_7": "Habang mas maraming tao ang nalaman, mas lumala ang problema. Mas maraming withdrawal request ang pumasok, ngunit marami ang hindi naproseso. Libu-libong negosyo ang napagtantong hindi nila kayang bayaran ang kanilang mga empleyado dahil sa pagkabigo ng bangko.",
	"bank_runs_how_content_8": "Pumasok ang FDIC at sumang-ayon na gawin ang mga depositor na buo. Nasolusyonan na ba ang problema? Hindi eksakto...",
	"bank_runs_fdic": "PINOPROTEKTAHAN BA NG FDIC INSURANCE ANG AKING PERA?",
	"bank_runs_fdic_content_1": "Ang FDIC insurance ay dinisenyo upang protektahan ang mga depositor ng bangko sakaling mabigo ang isang bangko. Ang mga deposito ay insured hanggang $250,000 bawat depositor. Maganda pakinggan, diba?",
	"bank_runs_fdic_content_2": "Hindi eksakto. Kung mabigo ang isang bangko, saan kukuha ng pera ang FDIC? Mayroon silang insurance fund na may 125 bilyong dolyar.",
	"bank_runs_fdic_content_3": "Mukhang malaking halaga iyan hanggang sa ikumpara mo ito sa halaga ng mga deposito na kanilang insured: halos 10 trilyon o 10,000 bilyong dolyar.",
	"bank_runs_fdic_content_4": "Ipinakikita pa ng FDIC sa kanilang website na mayroon lamang silang sapat na pera sa kanilang insurance fund upang masaklawan ang kaunti lamang na higit sa 1% ng mga deposito.",
	"bank_runs_fdic_content_5": "Sa kaso ng pagkabigo ng bangko na lalampas sa FDIC insurance fund, malamang (ngunit hindi garantisado) na ang gobyerno ng US ay magpi-print ng pera upang gawin ang mga depositor na buo.",
	"bank_runs_fdic_content_6": "Ngunit ang pag-print ng pera ay nagdudulot ng inflation, kaya hindi ito magandang solusyon.",
	"bank_runs_safe": "MAY MGA BANGKO BANG HINDI GUMAGAMIT NG FRACTIONAL RESERVE?",
	"bank_runs_safe_content_1": "Ang ilang bangko ay nagsumikap na maging 'safe bank' na hindi nagpapahiram o nag-i-invest ng mga pondo ng depositor.",
	"bank_runs_safe_content_2": "Kahit na ang mga safe bank na ito ay walang panganib ng bank run, ang kanilang mga aplikasyon ay tinanggihan ng Federal Reserve. Nangangahulugan ito na hindi sila maaaring legal na gumana bilang mga bangko.",
	"bank_runs_safe_content_3": "Dahil na-block sila sa pagpapatakbo, walang mga bangko ngayon na hindi gumagamit ng fractional reserve.",
	"bank_runs_safe_content_4": "Sa kabutihang-palad, may paraan upang umalis sa fractional reserve system sa pamamagitan ng pagiging sarili mong bangko. Hindi, hindi namin pinag-uusapan ang pagtatago ng cash sa ilalim ng iyong kama.",
	"bank_runs_safe_content_5": "Ang pag-iipon sa cash ay vulnerable pa rin sa inflation.",
	"bank_runs_safe_content_6": "Pinag-uusapan namin ang Bitcoin: isang bagong sistema sa pananalapi na nagpapahintulot sa iyo na maging sarili mong bangko.",
	"bank_runs_protect": "MAAARI BANG PROTEKTAHAN AKO NG BITCOIN MULA SA MGA BANK RUN?",
	"bank_runs_protect_content_1": "Oo, ang Bitcoin ay isang full reserve financial system.",
	"bank_runs_protect_content_2": "Ang mga bank run ay imposible sa Bitcoin basta i-withdraw mo ang iyong Bitcoin sa sarili mong wallet. Huwag iwanan ang iyong bitcoin sa isang exchange o sa isang wrapper tulad ng Bitcoin ETF.",
	"bank_runs_protect_content_3": "Tingnan ang aming simpleng Gabay sa Bitcoin Wallet upang malaman kung paano mag-withdraw sa iyong sariling wallet.",
	"bank_runs_protect_content_4": "Sa Bitcoin, maaari ka na sa wakas na maging may kontrol ng iyong pera."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Gabay sa Bitcoin Wallet",
	"wallets_description": "Maraming magkakaibang Bitcoin wallet na nagkakaiba sa mahahalagang paraan. Maaari mong matukoy kung ang isang wallet ay tama para sa iyo sa pamamagitan ng pagtatanong ng mga simpleng tanong na ito.",
	"wallets_header": "PAANO LIGTAS NA IIMBAK ANG IYONG BITCOIN",
	"wallets_s1_c1": "Ang mga Bitcoin wallet ay interoperable, kaya maaari kang magpadala ng Bitcoin sa sinuman kahit anong wallet ang ginagamit nila.",
	"wallets_s1_c2": "Maraming magkakaibang Bitcoin wallet na nagkakaiba sa mahahalagang paraan. Maaari mong matukoy kung ang isang wallet ay tama para sa iyo sa pamamagitan ng pagtatanong ng mga simpleng tanong na ito:",
	"wallets_question_1": "SELF-CUSTODY BA ANG WALLET?",
	"wallets_s2_c1": "Isa sa mga inobasyon ng Bitcoin ay ang kakayahang iimbak ito nang hindi umaasa sa isang custodian, tulad ng bangko.",
	"wallets_s2_c2": "Kung hawak mo ang bitcoin sa isang exchange o sa isang ETF, nawawala ang mga benepisyo ng kalayaan ng bitcoin.",
	"wallets_s2_c3": "Ang mga self-custody wallet ay nag-a-unlock ng buong kapangyarihan ng Bitcoin: pera ng kalayaan.",
	"wallets_s2_c4": "Sa isang self-custody wallet, ikaw lamang ang may kakayahang gumastos o maglipat ng iyong pera. Walang maaaring pumigil sa iyo mula sa pagpapadala o pagtanggap ng iyong pera kapag gumagamit ka ng self-custody wallet.",
	"wallets_s2_c5": "Ang mga self-custody wallet ay tinatawag din na non-custodial wallet.",
	"wallets_s3_c1": "Ang mga custodial wallet ay mga wallet kung saan hindi ka ang may kontrol ng iyong pera.",
	"wallets_s3_c2": "Ang mga wallet na ito ay mas katulad ng sistema ng pagbabangko kung saan kailangan mong magtiwala sa isang third party upang bigyan ka ng access sa iyong pera. Kung ang iyong Bitcoin ay nasa isang exchange, gumagamit ka ng custodial wallet.",
	"wallets_s3_c3": "Kung bumili ka ng Bitcoin ETF, gumagamit ka ng custodial wallet na hindi ka pinapayagang mag-withdraw sa self-custody.",
	"wallets_s3_c4": "Ang mga custodial wallet ay maaaring mukhang maginhawa, ngunit ang custodian ay may teknikal na kakayahang nakawin ang lahat ng pondo ng user anumang oras.",
	"wallets_s3_c5": "Hindi mo ang susi, hindi mo ang barya!",
	"wallets_question_2": "HOT O COLD BA ITO?",
	"wallets_s4_c1": "Ang mga cold wallet ay nag-iimbak ng mga susi sa iyong Bitcoin sa paraang hindi kailanman nailalantad sa internet.",
	"wallets_s4_c2": "Malaki ang naililimita nito sa mga attack vector na maaaring gamitin ng isang magnanakaw upang subukang nakawin ang iyong Bitcoin, at pinakamahusay na gamitin para sa malalaking halaga ng Bitcoin na hindi mo kailangan madalas ilipat.",
	"wallets_s4_c3": "Maaari mong isipin ang cold wallet bilang isang pangmatagalang savings account, na kilala rin bilang cold storage.",
	"wallets_s5_c1": "Ang mga hot wallet ay nag-iimbak ng mga susi sa iyong Bitcoin sa isang device na konektado sa internet, tulad ng iyong telepono.",
	"wallets_s5_c2": "Ang mga hot wallet ay karaniwang itinuturing na ligtas, ngunit maaari silang may mas maraming vulnerability sa seguridad kaysa sa mga cold wallet.",
	"wallets_s5_c3": "Maaari mong isipin ang hot wallet tulad ng iyong pisikal na wallet. Hindi mo ilalagay ang buong ipon mo sa iyong wallet, ngunit maglalagay ka ng ilang gastusin.",
	"wallets_s5_c4": "Ginagawa ng mga hot wallet na mas madaling gumastos ng iyong Bitcoin nang hindi kinakailangang kunin ang iyong buong ipon mula sa cold storage.",
	"wallets_question_3": "PAANO AKO MAGBA-BACK UP NG AKING RECOVERY PHRASE?",
	"wallets_s6_c1": "Kapag na-set up mo ang iyong Bitcoin wallet, gagawa ang iyong device ng recovery phrase. Ang recovery phrase na ito (na tinatawag ding seed phrase) ay naglalaman ng 12 o 24 na salita.",
	"wallets_s6_c2": "Kung mawala ang access mo sa iyong wallet o huminto sa paggana ang iyong device, maaari mong i-input ang recovery phrase na ito sa isang bagong wallet upang makuha muli ang access sa iyong Bitcoin.",
	"wallets_s6_c3": "Karamihan sa mga wallet ay may kasamang papel upang isulat ang iyong recovery phrase, ngunit maraming tao ang mas gustong i-back up ang phrase na ito sa bakal sa halip. Ginagawa nitong mas mababa ang posibilidad na mawala ang iyong recovery phrase sa kaso ng natural na kalamidad tulad ng sunog o baha.",
	"wallets_s6_c4": "Si Jameson Lopp ay nasubok ang 70 steel backup kit upang matulungan kang piliin ang tamang para sa iyo.",
	"wallets_s6_c5": "Tingnan ang metal na gabay sa pag-backup ng Bitcoin ni Jameson dito.",
	"wallets_s6_c6": "O patuloy na mag-scroll upang i-explore ang mga opsyon ng Bitcoin wallet.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "Naghahanap ng aming Gabay sa Lightning Wallet?",
	"wallets_starter_wallet": "Mahusay na panimulang wallet",
	"wallets_mobile_app": "Mobile app",
	"wallets_2fa_support": "Suporta sa 2FA",
	"wallets_air_gap_mode": "Air-gap mode",
	"wallets_air_gap_camera": "Air-gap mode + camera",
	"wallets_bitcoin_only": "Bitcoin lamang",
	"wallets_security_features": "Maraming security feature",
	"wallets_free": "100% libre",
	"wallets_coldcard_mk5_costs": "Nagkakahalaga ng $189",
	"wallets_coldcard_q_costs": "Nagkakahalaga ng $289",
	"wallets_blockstream_jade_costs": "Nagkakahalaga ng $79",
	"wallets_foundation_passport_costs": "Nagkakahalaga ng $199",
	"wallets_seedsigner_costs": "Ang mga bahagi ay nagkakahalaga ng $50",
	"wallets_very_affordable": "Napaka-abot-kaya",
	"wallets_pair_with_phone": "I-pair sa iyong telepono",
	"wallets_battery": "Rechargeable battery",
	"wallets_build_your_own": "Buuin mo ang sarili mo",
	"wallets_qwerty_keyboard": "Buong QWERTY keyboard",
	"wallets_qr_scanner": "QR code scanner"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "Paano Bumili ng Bitcoin - Gabay na Hakbang-hakbang",
	"buy_header": "PAANO BUMILI NG BITCOIN",
	"buy_intro_c1": "Ang pagbili ng Bitcoin sa unang pagkakataon ay maaaring mukhang nakakalito, ngunit talagang napakadali kapag hinati-hati mo sa mga hakbang.",
	"buy_intro_c2": "Gagabayan ka ng gabay na ito sa proseso ng ligtas na pagbili ng Bitcoin at pag-iimbak nito sa iyong sariling wallet.",
	"buy_step_1_header": "HAKBANG 1: PILIIN ANG IYONG BANSA",
	"buy_step_1_description": "Ang iba't ibang bansa ay may iba't ibang opsyon sa pagbili ng Bitcoin na available. Piliin ang iyong bansa upang makita ang mga pinakamahusay na opsyon para sa iyo.",
	"buy_search_countries": "Maghanap ng iyong bansa",
	"buy_country_united_states": "United States",
	"buy_country_australia": "Australia",
	"buy_country_austria": "Austria",
	"buy_country_belgium": "Belgium",
	"buy_country_brazil": "Brazil",
	"buy_country_canada": "Canada",
	"buy_country_france": "France",
	"buy_country_germany": "Germany",
	"buy_country_ireland": "Ireland",
	"buy_country_italy": "Italy",
	"buy_country_netherlands": "Netherlands",
	"buy_country_new_zealand": "New Zealand",
	"buy_country_spain": "Spain",
	"buy_country_united_kingdom": "United Kingdom",
	"buy_country_argentina": "Argentina",
	"buy_country_chile": "Chile",
	"buy_country_colombia": "Colombia",
	"buy_country_costa_rica": "Costa Rica",
	"buy_country_czech_republic": "Czech Republic",
	"buy_country_denmark": "Denmark",
	"buy_country_el_salvador": "El Salvador",
	"buy_country_estonia": "Estonia",
	"buy_country_finland": "Finland",
	"buy_country_greece": "Greece",
	"buy_country_guatemala": "Guatemala",
	"buy_country_hong_kong": "Hong Kong",
	"buy_country_hungary": "Hungary",
	"buy_country_iceland": "Iceland",
	"buy_country_india": "India",
	"buy_country_israel": "Israel",
	"buy_country_japan": "Japan",
	"buy_country_latvia": "Latvia",
	"buy_country_lithuania": "Lithuania",
	"buy_country_luxembourg": "Luxembourg",
	"buy_country_malta": "Malta",
	"buy_country_mexico": "Mexico",
	"buy_country_norway": "Norway",
	"buy_country_panama": "Panama",
	"buy_country_poland": "Poland",
	"buy_country_portugal": "Portugal",
	"buy_country_romania": "Romania",
	"buy_country_singapore": "Singapore",
	"buy_country_slovakia": "Slovakia",
	"buy_country_slovenia": "Slovenia",
	"buy_country_south_africa": "South Africa",
	"buy_country_south_korea": "South Korea",
	"buy_country_sweden": "Sweden",
	"buy_country_switzerland": "Switzerland",
	"buy_country_thailand": "Thailand",
	"buy_country_turkey": "Turkey",
	"buy_country_ukraine": "Ukraine",
	"buy_country_uruguay": "Uruguay",
	"buy_step_2_header": "HAKBANG 2: PILIIN ANG IYONG PARAAN NG PAGBABAYAD",
	"buy_step_2_description": "Mayroong dalawang pangunahing paraan upang bumili ng Bitcoin: sa pamamagitan ng bank transfer o sa pamamagitan ng cash. Bawat isa ay may iba't ibang bentahe.",
	"buy_method_bank_transfer": "BANK TRANSFER",
	"buy_method_bank_fast": "Mabilis at Madali",
	"buy_method_bank_less_private": "Mas Mababang Privacy",
	"buy_method_bank_description": "Ang mga bank transfer ay ang pinakakaraniwang paraan upang bumili ng Bitcoin. Mabilis, maginhawa, at karaniwang may mas mababang bayarin.",
	"buy_method_choose_bank": "Piliin ang Bank Transfer",
	"buy_method_cash": "CASH",
	"buy_method_cash_private": "Mas Mataas na Privacy",
	"buy_method_cash_limited": "Limitadong Opsyon",
	"buy_method_cash_description": "Ang mga pagbili sa cash ay nag-aalok ng mas mataas na privacy ngunit may mas kaunting opsyon at maaaring mangailangan ng pakikipagkita sa isang tao nang personal o paggamit ng Bitcoin ATM.",
	"buy_method_choose_cash": "Piliin ang Cash",
	"buy_step_3_header": "HAKBANG 3: MGA OPSYON SA PAGBILI",
	"buy_step_3_description": "Narito ang mga pinakamahusay na opsyon sa pagbili ng Bitcoin para sa iyong bansa at paraan ng pagbabayad:",
	"buy_platform_recommended": "INIREREKOMENDA",
	"buy_platform_strike_description": "Ang Strike ang pinakamabilis at pinakamadaling paraan upang bumili ng Bitcoin na may mababang bayarin at instant na suporta sa Lightning Network.",
	"buy_platform_swan_description": "Ang Swan Bitcoin ay espesyalista sa mga serbisyong Bitcoin-only na may dollar-cost averaging at mga pang-edukasyonal na mapagkukunan.",
	"buy_platform_river_description": "Nag-aalok ang River ng pagbili ng Bitcoin, mining, at mga serbisyo sa custody na may pokus sa edukasyon at seguridad.",
	"buy_platform_coinsquare_description": "Ang Coinsquare ay isang Canadian Bitcoin exchange na may malakas na regulatory compliance at customer support.",
	"buy_platform_kraken_description": "Ang Kraken ay isang established na Bitcoin exchange na may advanced na mga feature sa trading at malakas na seguridad.",
	"buy_platform_atm_description": "Pinapayagan ka ng mga Bitcoin ATM na bumili ng Bitcoin gamit ang cash agad-agad. Makahanap ng isa malapit sa iyo gamit ang Coin ATM Radar.",
	"buy_platform_bisq_description": "Ang Bisq ay isang decentralized peer-to-peer na exchange na nagpapahintulot ng pribadong pangangalakal ng Bitcoin nang walang KYC.",
	"buy_platform_feature_instant": "Instant na pagbili",
	"buy_platform_feature_low_fees": "Mababang bayarin",
	"buy_platform_feature_lightning": "Lightning Network",
	"buy_platform_feature_dca": "Dollar-cost averaging",
	"buy_platform_feature_education": "Mga pang-edukasyonal na mapagkukunan",
	"buy_platform_feature_withdrawal": "Madaling withdrawal",
	"buy_platform_feature_mining": "Bitcoin mining",
	"buy_platform_feature_custody": "Mga serbisyo sa custody",
	"buy_platform_feature_canadian": "Pokus sa Canada",
	"buy_platform_feature_regulated": "Regulated exchange",
	"buy_platform_feature_support": "Customer support",
	"buy_platform_feature_established": "Established na platform",
	"buy_platform_feature_security": "Malakas na seguridad",
	"buy_platform_feature_advanced": "Mga advanced na feature",
	"buy_platform_feature_cash": "Pagbili sa cash",
	"buy_platform_feature_anonymous": "Mas anonymous",
	"buy_platform_feature_p2p": "Peer-to-peer",
	"buy_platform_feature_private": "Pribadong pangangalakal",
	"buy_platform_feature_decentralized": "Desentralisado",
	"buy_platform_relai_description": "Ang Relai ay isang Swiss Bitcoin-only app na may self-custody wallet, auto-invest feature, at mababang bayarin para sa mga European user.",
	"buy_platform_feature_bitcoin_only": "Bitcoin lamang",
	"buy_platform_feature_self_custody": "Self-custody wallet",
	"buy_platform_feature_auto_invest": "Mga auto-invest plan",
	"buy_platform_feature_european": "Pokus sa Europe",
	"buy_step_4_header": "HAKBANG 4: LIGTAS NA IIMBAK ANG IYONG BITCOIN",
	"buy_step_4_c1": "Pagkatapos bumili ng Bitcoin, ang pinakamahalagang hakbang ay ilipat ito sa iyong sariling wallet kung saan ikaw ang may kontrol ng mga private key.",
	"buy_step_4_c2": "Ang pag-iwan ng Bitcoin sa isang exchange ay mapanganib dahil hindi mo talaga pagmamay-ari ang Bitcoin - ang exchange ang may-ari.",
	"buy_step_4_c3": "Kapag ikaw ang may kontrol ng iyong sariling mga private key, mayroon kang tunay na pagmamay-ari ng iyong Bitcoin at walang maaaring kumuha nito sa iyo.",
	"buy_step_4_c4": "Alamin kung paano pumili ng tamang Bitcoin wallet para sa iyong mga pangangailangan:",
	"buy_cta_wallets": "Tingnan ang Aming Gabay sa Bitcoin Wallet"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Gabay sa Bitcoin Lightning Wallet",
	"lightning_description": "Ang mga Lightning wallet ay nagpapahintulot sa iyo na magpadala ng Bitcoin nang mabilis at mura habang pinapanatili ang iyong personal na soberanya.",
	"lightning_header": "GABAY SA LIGHTNING WALLET",
	"lightning_s1_c1": "Pinapahintulutan ka ng Lightning na magpadala ng mga bayad sa Bitcoin nang mabilis at mura.",
	"lightning_s1_c2": "Mahalagang malaman na ang paggamit ng lightning ay may mga trade-off. Kapalit ng mas mabilis at mas murang mga bayad sa Bitcoin, madalas mong isinasakripisyo ang ilang seguridad.",
	"lightning_s1_c3": "Sa pangkalahatan, ang Lightning ay dapat lamang gamitin sa maliliit na halaga ng bitcoin. Dapat ka lamang mag-imbak ng malalaking halaga ng bitcoin sa isang hardware wallet.",
	"lightning_s1_c4": "Tingnan ang aming Gabay sa Hardware Wallet para sa higit pang impormasyon.",
	"lightning_s1_c5": "Hindi lahat ng Lightning wallet ay pareho. Maaari mong matukoy kung aling wallet ang may tamang set ng trade-off para sa iyo sa pamamagitan ng pagtatanong ng isang simpleng tanong:",
	"lightning_question_1": "ANONG BALANSE NG TRADE-OFF ANG TAMA PARA SA AKIN?",
	"lightning_s2_c1": "Isa sa mga inobasyon ng Bitcoin ay ang kakayahang iimbak ito nang hindi umaasa sa isang custodian, tulad ng bangko. Ang mga self-custody wallet ay nag-a-unlock ng buong kapangyarihan ng Bitcoin.",
	"lightning_s2_c2": "Sa isang self-custody wallet, ikaw lamang ang may kakayahang gumastos o maglipat ng iyong pera. Walang maaaring pumigil sa iyo, mag-censor sa iyo, o magnakaw mula sa iyo kapag gumagamit ka ng self-custody wallet. Ang mga ito ay tinatawag din na non-custodial wallet.",
	"lightning_s2_c3": "Ang pinaka-sovereign na paraan upang gamitin ang Lightning ay sa pamamagitan ng pagpapatakbo ng iyong sariling node.",
	"lightning_s2_c4": "Ang gabay na ito ay nakatuon sa mga simpleng Lightning wallet na hindi nangangailangan ng sarili mong node.",
	"lightning_s2_c5": "Mahalagang malaman na kahit gamit ang non-custodial na Lightning wallet, nagtitiwala ka pa rin sa tagalikha ng wallet na hindi mag-push ng malisyosong app update at nakawin ang iyong pondo.",
	"lightning_s3_c1": "Ang mga custodial wallet ay mga wallet kung saan hindi ka ang may kontrol ng iyong pera.",
	"lightning_s3_c2": "Ang mga wallet na ito ay mas katulad ng sistema ng pagbabangko kung saan kailangan mong magtiwala sa isang third party upang bigyan ka ng access sa iyong pera. Kung ang iyong Bitcoin ay nasa isang exchange, gumagamit ka ng custodial wallet.",
	"lightning_s3_c3": "Ang mga custodial wallet ay maaaring mukhang maginhawa, ngunit ang custodian ay may teknikal na kakayahang nakawin ang lahat ng pondo ng user anumang oras.",
	"lightning_s3_c4": "Ang ilang tao ay mas gusto ang mga custodial Lightning wallet para sa maliliit na halaga ng bitcoin dahil sa kanilang kadalian ng paggamit. Tandaan lang: hindi mo ang susi, hindi mo ang barya!",
	"lightning_question_2": "PILIIN ANG IYONG WALLET",
	"lightning_s4_c1": "Sa lahat ng ito sa isip, maaari ka na ngayong pumili ng lightning wallet na may tamang balanse ng trade-off para sa iyo.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "Maraming feature",
	"lightning_mobile_app": "Mobile app",
	"lightning_free": "100% libre",
	"lightning_merchants": "Mahusay para sa mga merchant",
	"lightning_starter": "Mahusay na panimulang wallet",
	"lightning_browser": "Base sa browser",
	"lightning_custodial": "Ganap na custodial wallet",
	"lightning_cta_hardware": "Naghahanap ng aming Gabay sa Bitcoin Hardware Wallet?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "Libreng Bitcoin sticker mula sa bitcoin.rocks",
	"stickers_description": "Maglagay ng bitcoin sticker sa publiko upang ma-orange pill ang mga nasa paligid mo.",
	"stickers_header": "LIBRENG BITCOIN STICKER",
	"stickers_choose_header": "PILIIN ANG IYONG STICKER PACK",
	"stickers_choose_c1": "Ang aming misyon ay tulungan kang mag-orange pill ng mas maraming tao sa pamamagitan ng paglalagay ng mga Bitcoin sticker sa publiko. Lahat ng aming mga sticker ay may mga QR code na naglilink sa mga pahinang pang-edukasyon tungkol sa",
	"stickers_choose_c2": "Bitcoin",
	"stickers_choose_c3": "inflation",
	"stickers_choose_c4": "Piliin ang iyong sticker pack sa ibaba",
	"stickers_text_pack": "ANG TEXT PACK",
	"stickers_signs_pack": "ANG SIGNS PACK",
	"stickers_instructions_1": "Ilagay ang iyong mailing address at ipapadala namin sa iyo ang isang libreng Bitcoin Sticker Pack sa koreo! Ang iyong mga sticker ay ipapadala sa isang plain na puting sobre.",
	"stickers_instructions_2": "Ang data ng address ay binubura pagkatapos maipadala ang iyong mga libreng sticker.",
	"stickers_share_header": "IBAHAGI ANG IYONG MGA STICKER SPOT",
	"stickers_share_c1": "Ibahagi ang iyong mga sticker spot sa amin sa Nostr at tingnan kung saan naglalagay ang ibang tao ng kanilang mga sticker.",
	"stickers_btn_share_on_nostr": "IBAHAGI SA NOSTR",
	"stickers_btn_what_is_nostr": "ANO ANG NOSTR?",
	"stickers_flyers_link_before": "Habang nariyan ka na, mag-print at mag-post ng sarili mong ",
	"stickers_flyers_link_text": "mga Bitcoin flyer",
	"stickers_flyers_link_after": " upang makatulong na mag-orange pill ng mas maraming tao.",
	"stickers_country_global_print": "Global — Mag-print ng sarili kong sticker",
	"stickers_country_global_order": "Global — Mag-order nang maramihan",
	"placeholder_name_optional": "Pangalan (opsyonal)",
	"placeholder_address_line_1": "Address Line 1",
	"placeholder_address_line_2": "Address Line 2 (opsyonal)",
	"placeholder_city": "Lungsod",
	"placeholder_state": "Estado",
	"placeholder_province": "Lalawigan",
	"placeholder_zip_code": "Zip Code",
	"placeholder_postal_code": "Postal Code",
	"placeholder_language": "Wika",
	"placeholder_which_stickers": "Aling mga sticker?",
	"placeholder_email_optional": "Ilagay ang iyong email upang ma-notify (opsyonal)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "Libreng Bitcoin Postcard mula sa bitcoin.rocks",
	"postcards_description": "Kumuha ng libreng Bitcoin Postcard Pack at ibahagi ang Bitcoin sa isang taong kilala mo.",
	"postcards_header": "SARADO NA ANG POSTCARD PROGRAM",
	"postcards_program_closed_message": "Natapos na ang aming libreng Bitcoin postcard program. Salamat sa lahat ng lumahok sa pagpapakalat ng edukasyon sa Bitcoin sa pamamagitan ng koreo!",
	"postcards_sticker_alternative_header": "KUMUHA NG LIBRENG BITCOIN STICKER SA HALIP",
	"postcards_sticker_alternative_message": "Patuloy na magpakalat ng kamalayan sa Bitcoin gamit ang aming libreng sticker program! Ang aming mga Bitcoin sticker ay perpekto para sa pagbabahagi sa mga pampublikong lugar at may mga QR code na naglilink sa edukasyonal na nilalaman.",
	"postcards_sticker_cta": "KUMUHA NG LIBRENG STICKER",
	"postcards_step_2": "ANO ANG HITSURA NG MGA POSTCARD",
	"postcards_instructions_4": "Ginawa namin ang mga postcard na ito upang gawing mas madali para sa iyo na ipakilala ang isang taong kilala mo sa Bitcoin! Ilagay lang ang isang address at selyo at ihulog ang iyong postcard sa koreo.",
	"postcards_instructions_5": "Ang aming misyon ay pabilisin ang pagtanggap ng Bitcoin. Maaari kang tumulong sa pamamagitan ng pagkuha ng libreng sticker at paglalagay ng mga ito sa mga pampublikong lugar!",
	"postcards_instructions_6": "Lahat tayo ay may kilalang ilang tao na makikinabang sa pag-aaral ng higit pa tungkol sa Bitcoin. Ibahagi ang mga Bitcoin sticker sa kanila ngayon!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "Tulungan kaming ilagay ang mga Bitcoin Sign na ito sa buong America!",
	"signs_title": "Libreng Bitcoin Sign mula sa bitcoin.rocks",
	"signs_choose_header": "SALAMAT SA PAGTULONG NA ILAGAY ANG MGA BITCOIN SIGN NA ITO SA BUONG AMERICA!",
	"signs_choose_c1": "Ganap na naubos na ang aming mga sign! Ang aming misyon ay pabilisin ang pagtanggap ng Bitcoin sa pamamagitan ng edukasyon.",
	"signs_choose_c2": "Marami sa inyo ang tumulong sa pamamagitan ng paglalagay ng mga libreng Bitcoin sign na ito sa publiko. Lahat ng aming mga sign ay may mga QR code na naglilink sa isang pahinang pang-edukasyon tungkol sa",
	"signs_choose_c3": "inflation",
	"signs_choose_c4": "Salamat sa aming kamangha-manghang komunidad, naabot namin ang libu-libong tao at natulungan sila na magsimula sa kanilang pagbaba sa Bitcoin rabbit hole.",
	"signs_share_header": "IBAHAGI ANG IYONG MGA SIGN SPOT",
	"signs_share_c1": "Ibahagi ang litrato ng iyong sign spot sa amin sa Nostr at tingnan kung saan naglalagay ang ibang tao ng kanilang mga sign.",
	"signs_btn_share_on_nostr": "IBAHAGI SA NOSTR",
	"signs_btn_what_is_nostr": "ANO ANG NOSTR?",
	"signs_instructions_1": "Ilagay ang iyong mailing address at ipapadala namin sa iyo ang isang kahon ng 10 Bitcoin sign sa koreo!",
	"signs_instructions_2": "Ang data ng address ay binubura pagkatapos maipadala ang iyong mga libreng sign."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "Libreng Bitcoin Flyer mula sa bitcoin.rocks",
	"flyers_description": "Mag-print ng Bitcoin flyer sa bahay at ilagay ito sa publiko upang ma-orange pill ang mga nasa paligid mo.",
	"flyers_header_1": "MAG-PRINT AT MAG-POST NG",
	"flyers_header_2": "MGA BITCOIN FLYER",
	"flyers_intro_header": "PAANO MAG-PRINT AT MAG-POST NG MGA BITCOIN FLYER NA ITO",
	"flyers_intro_c1": "Ang aming misyon ay tulungan kang mag-orange pill ng mas maraming tao sa pamamagitan ng paglalagay ng mga Bitcoin flyer sa publiko. Ang flyer na ito ay may QR code na naglilink sa aming",
	"flyers_intro_c2": "edukasyonal na Bitcoin website.",
	"flyers_intro_c3": "inflation",
	"flyers_intro_c4": "I-print ang flyer na ito sa bahay o sa isang print shop. Pagkatapos, i-post ito sa mga bulletin board, mga poste ng telepono sa bayan, at iba pang mga pampublikong lugar kung saan makikita ito ng mga tao at matututo tungkol sa Bitcoin.",
	"flyers_intro_c5": "Habang nariyan ka na, humiling ng pack ng aming",
	"flyers_intro_c6": "libreng Bitcoin sticker",
	"flyers_intro_c7": "upang makatulong na mag-orange pill ng mas maraming tao.",
	"flyers_btn_download": "I-DOWNLOAD ANG FLYER",
	"flyers_btn_print": "I-PRINT ANG FLYER",
	"flyers_share_header": "IBAHAGI ANG IYONG MGA FLYER SPOT",
	"flyers_share_c1": "Ibahagi ang iyong mga flyer spot sa amin sa Nostr at tingnan kung saan naglalagay ang ibang tao ng kanilang mga flyer.",
	"flyers_btn_share_on_nostr": "IBAHAGI SA NOSTR",
	"flyers_btn_what_is_nostr": "ANO ANG NOSTR?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "Makisali at tumulong na ikalat ang Bitcoin",
	"get_involved_description": "Ang aming libreng mapagkukunan ay ginagawang mas madali ang pagpapakalat ng pagtanggap ng Bitcoin.",
	"get_involved_header": "MAKISALI",
	"get_involved_header_2": "IKALAT ANG BITCOIN",
	"get_involved_intro_1": "Maaaring nakakalungkot mamuhay sa kasalukuyang kalagayan ng ating mundo.",
	"get_involved_intro_2": "Ang ating pera ay sira. Dahil dito, ang mga pundamental na bahagi ng lipunan ay sira din.",
	"get_involved_intro_3": "Kung nasa Bitcoin ka na, alam mo ang pakiramdam ng pag-asa na maaaring dalhin ng Bitcoin. Pag-asa para sa mas maliwanag na kinabukasan na ginagawang posible ng mas magandang pera.",
	"get_involved_intro_4": "Ngunit napakaraming tao sa paligid mo ang hindi alam ang tungkol sa Bitcoin. Sila ay naninirahan sa parehong sirang mundo tulad mo, ngunit walang tanglaw ng pag-asa upang tulungan sila sa kadiliman.",
	"get_involved_intro_5": "Ngunit maaari kang tumulong na baguhin iyan. Gumawa kami ng ilang libreng mapagkukunan upang gawing mas madali ang pagpapakalat ng pag-asa na dala ng Bitcoin sa mga nasa paligid mo.",
	"get_involved_sticker_header": "Maglagay ng sticker sa publiko",
	"get_involved_sticker_content_1": "Maaari mong tulungan ang mga nasa paligid mo na matuto tungkol sa Bitcoin nang hindi kailangan makipag-usap sa kahit sino. Simpleng maglagay ng isa sa aming mga libreng Bitcoin sticker sa publiko.",
	"get_involved_sticker_content_2": "Daan-daang tao ang nag-i-scan ng mga QR code sa mga sticker na ito bawat buwan. Ang mga inflation sticker ay naglilink sa isang pahina tungkol sa",
	"get_involved_sticker_content_3": "Bitcoin bilang solusyon sa inflation.",
	"get_involved_sticker_content_4": "Ang ibang mga sticker ay naglilink sa aming edukasyonal na home page na nagpapakita sa mga tao kung paano",
	"get_involved_sticker_content_5": "bumubuo ang Bitcoin ng mas magandang mundo.",
	"get_involved_sticker_content_6": "Sa pamamagitan ng paglalagay ng mga sticker na ito sa iyong komunidad sa mga lugar na makikita ng mga tao, matutulungan mo ang mga nasa paligid mo na gawin ang kanilang mga unang hakbang pababa sa Bitcoin rabbit hole.",
	"get_involved_request_a": "HUMILING NG",
	"get_involved_sticker_pack": "STICKER PACK",
	"get_involved_postcard_header": "Magpadala ng postcard",
	"get_involved_postcard_content_1": "Maaari mong tulungang ikalat ang Pag-asa ng Bitcoin sa isang taong kilala mo sa pamamagitan ng pagpapadala sa kanila ng isa sa aming mga libreng postcard.",
	"get_involved_postcard_content_2": "Ang likod ng bawat postcard ay naglalaman ng isang nakakahikayat na blurb tungkol sa Bitcoin kasama ng QR code upang matuto pa.",
	"get_involved_postcard_content_3": "Sa pamamagitan ng pagpapadala sa isang tao ng Bitcoin postcard, matutulungan mo silang makita ang Bitcoin sa bagong paraan.",
	"get_involved_postcard_pack": "POSTCARD PACK",
	"get_involved_business_header": "Mag-onboard ng negosyo",
	"get_involved_business_content_1": "Gusto mo bang tumulong na buuin ang Bitcoin circular economy? Ang aming Bitcoin Business Kit ay ginagawang madaling lapitan ang isang negosyo tungkol sa pagtanggap ng mga bayad sa Bitcoin.",
	"get_involved_business_content_2": "Bawat business kit ay may kasamang mga flyer na nagha-highlight ng mga bentahe ng pagtanggap ng mga bayad sa Bitcoin. Bawat flyer ay naglilink sa iba't ibang",
	"get_involved_business_content_3": "libreng mapagkukunan para sa negosyo ng Bitcoin.",
	"get_involved_business_kit": "BUSINESS KIT"
});

console.log('\nDone! All content files created for Filipino (fil).');
