/**
 * Creates Hindi (hi) index_hi.json translation file
 */
const fs = require('fs');
const path = require('path');
const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'hi';
const today = '2026-04-02';

const data = {
	"@metadata": { "authors": ["Satoshi"], "last-updated": today, "locale": lang },
	"bitcoin_builds_a_better_world": "Bitcoin एक बेहतर दुनिया बना रहा है।",
	"home_description": "Bitcoin बेहतर मुद्रा है जो एक बेहतर दुनिया बना रही है। Bitcoin ने मानवाधिकारों की रक्षा की है, लोगों को उच्च मुद्रास्फीति से बचाया है, स्थानीय किसानों का समर्थन किया है, तेल ड्रिलिंग से उत्सर्जन कम किया है, और भी बहुत कुछ।",
	"home_intro": "Bitcoin बेहतर मुद्रा है जो एक बेहतर दुनिया बना रही है। नीचे किसी श्रेणी पर टैप करके जानें कि Bitcoin कैसे बेहतर बनाता है, या बस स्क्रॉल करके एक्सप्लोर करें।",
	"home_btn_money": "बेहतर मुद्रा",
	"home_btn_salary": "आपकी सैलरी",
	"home_btn_freedom": "स्वतंत्रता",
	"home_btn_human_rights": "मानवाधिकार",
	"home_btn_equality": "समानता",
	"home_btn_property_rights": "संपत्ति अधिकार",
	"home_btn_housing": "आवास",
	"home_btn_business": "व्यवसाय",
	"home_btn_crowdfunding": "क्राउडफ़ंडिंग",
	"home_btn_energy": "ऊर्जा",
	"home_btn_environment": "पर्यावरण",
	"home_btn_food": "भोजन",
	"home_btn_art": "कला",
	"home_btn_politics": "राजनीति",
	"home_btn_war": "युद्ध",
	"home_btn_coding": "कोडिंग",
	"home_btn_networks": "नेटवर्क",
	"home_btn_payments": "भुगतान",
	"home_btn_self_custody": "स्व-संरक्षण",
	"home_btn_you": "आप",
	"home_section_bitcoin_is": "BITCOIN है",
	"home_section_bitcoin_and": "BITCOIN और",
	"home_link_type_website": "वेबसाइट",
	"home_link_type_video": "वीडियो",
	"home_link_type_article": "लेख",
	"home_link_type_podcast": "पॉडकास्ट",
	"home_link_type_business_kit": "बिज़नेस किट",
	"home_link_type_data": "डेटा",
	"home_link_type_research": "शोध",
	"home_link_type_story": "कहानी",
	"home_link_type_book_excerpt": "पुस्तक अंश",
	"home_link_type_street_art": "स्ट्रीट आर्ट",
	"home_link_type_outreach": "आउटरीच",
	"home_link_type_campaign": "अभियान",
	"home_link_type_software": "सॉफ़्टवेयर",
	"home_link_type_hardware": "हार्डवेयर",
	"home_link_type_guide": "गाइड",
	"home_link_type_email": "ईमेल",
	"home_link_title_inflation": "Bitcoin में मुद्रास्फीति नहीं होती",
	"home_link_title_bank_runs": "Bitcoin में बैंक रन नहीं होते",
	"home_link_title_gold": "Bitcoin vs सोना",
	"home_link_title_crypto": "Bitcoin vs क्रिप्टोकरेंसी",
	"home_link_title_cash": "Bitcoin vs नकदी",
	"home_link_title_bonds": "Bitcoin vs बॉन्ड",
	"home_link_title_cbdc": "Bitcoin vs CBDC",
	"home_link_title_your_salary_1": "जानें कि मुद्रास्फीति से बचने के लिए आपकी सैलरी को कितना बढ़ना चाहिए।",
	"home_link_title_freedom_1": "Bitcoin स्वतंत्रता के लिए क्यों महत्वपूर्ण है",
	"home_link_title_freedom_2": "Bitcoin राजनीतिक दमन से स्वतंत्रता प्रदान करता है",
	"home_link_title_human_rights_1": "Bitcoin मानवाधिकारों को कैसे लागू करता है",
	"home_link_title_human_rights_2": "अफ्रीका की मौन Bitcoin क्रांति",
	"home_link_title_human_rights_3": "Bitcoin दुनिया भर में मानवाधिकारों की रक्षा कर रहा है",
	"home_link_title_equality_1": "Bitcoin दक्षिण अफ्रीकियों को आशा और अवसर दे रहा है",
	"home_link_title_equality_2": "Bitcoin अश्वेत अमेरिकियों के लिए गेम चेंजर कैसे हो सकता है",
	"home_link_title_property_rights_1": "Bitcoin संपत्ति का सबसे उत्तम रूप है",
	"home_link_title_property_rights_2": "Bitcoin vs रियल एस्टेट",
	"home_link_title_housing_1": "Bitcoin कैसे आवास को फिर से सस्ता बनाएगा",
	"home_link_title_business_3": "Bitcoin vs स्टॉक",
	"home_link_title_business_1": "जानें Bitcoin व्यवसाय के लिए क्यों अच्छा है",
	"home_link_title_business_2": "स्थानीय व्यवसाय को Bitcoin स्वीकार करने के लिए मनाएं",
	"home_link_title_crowdfunding_1": "Bitcoin ने नाइजीरिया के सबसे बड़े विरोध प्रदर्शनों को कैसे शक्ति दी",
	"home_link_title_crowdfunding_2": "GoFundMe द्वारा दान रोकने के बाद कनाडाई ट्रक ड्राइवरों ने Bitcoin में धन जुटाया",
	"home_link_title_crowdfunding_3": "Geyser = Bitcoin से क्राउडफ़ंड करें",
	"home_link_title_energy_1": "Bitcoin टेक्सास पावर ग्रिड को कैसे स्थिर करता है",
	"home_link_title_energy_2": "Bitcoin ऊर्जा क्यों उपयोग करता है?",
	"home_link_title_energy_3": "Bitcoin का ऊर्जा उपयोग कोई समस्या नहीं है। यहाँ जानें क्यों।",
	"home_link_title_energy_4": "Bitcoin माइनिंग डिमांड रिस्पॉन्स से ऊर्जा ग्रिड स्थिर कर रही है",
	"home_link_title_energy_5": "Bitcoin माइनर अफ्रीकी ग्रामीण समुदायों में जल विद्युत ला रहे हैं",
	"home_link_title_energy_6": "Bitcoin नवीकरणीय ऊर्जा को कैसे प्रोत्साहित करता है",
	"home_link_title_environment_1": "Bitcoin माइनिंग वैश्विक मीथेन उत्सर्जन कैसे कम कर रही है",
	"home_link_title_environment_2": "Bitcoin माइनिंग ने एक राष्ट्रीय उद्यान को कैसे बचाया",
	"home_link_title_environment_3": "Bitcoin पृथ्वी पर सबसे हरित उद्योग है!",
	"home_link_title_environment_4": "Bitcoin माइनिंग जलाई गई प्राकृतिक गैस को वायुमंडल प्रदूषित करने से रोक रही है",
	"home_link_title_food_1": "मुद्रास्फीति खाद्य कीमतों को कैसे प्रभावित करती है",
	"home_link_title_food_2": "फ़िएट मुद्रा भोजन, खेतों और पृथ्वी की मिट्टी के लिए कैसे हानिकारक है",
	"home_link_title_fine_art": "Bitcoin vs ललित कला",
	"home_link_title_art_1": "हमारी Bitcoin स्टिकर पहल में शामिल हों",
	"home_link_title_art_2": "किसी जानने वाले को Bitcoin पोस्टकार्ड भेजें",
	"home_link_title_art_3": "Bitcoin फ्लायर प्रिंट और पोस्ट करें",
	"home_link_title_politics_1": "Bitcoin एक राजनीतिक विरोधाभास है",
	"home_link_title_politics_2": "आप बेहतर मुद्रा के लिए वोट कर सकते हैं",
	"home_link_title_war_1": "Bitcoin कैसे अंतहीन युद्ध को समाप्त कर सकता है",
	"home_link_title_war_2": "Bitcoin और दिग्गज सैनिक: एक स्वाभाविक तालमेल",
	"home_link_title_war_3": "Bitcoin सूडान में युद्ध से नागरिकों को बचने में कैसे मदद कर रहा है",
	"home_link_title_coding_1": "Bitcoin की तकनीकी पक्ष के बारे में एक इंटरैक्टिव ट्यूटोरियल",
	"home_link_title_coding_2": "bitcoinSwitch: किसी भी डिवाइस को Bitcoin स्वीकार करने के लिए बदलें",
	"home_link_title_coding_3": "कोड करते हुए Bitcoin के रहस्य जानें",
	"home_link_title_networks_1": "Bitcoin नेटवर्क का लाइव दृश्य",
	"home_link_title_networks_2": "Bitcoin vs बैंक",
	"home_link_title_payments_1": "Bitcoin vs Visa",
	"home_link_title_payments_2": "लाइटनिंग नेटवर्क पर एक नज़र (तत्काल Bitcoin भुगतान)",
	"home_link_title_payments_3": "एल साल्वाडोर का Bitcoin वॉलेट साल्वाडोर वासियों को सालाना $400M रेमिटेंस शुल्क बचा सकता है",
	"home_link_title_payments_4": "तत्काल Bitcoin भुगतान प्राप्त करने के लिए अपना लाइटनिंग एड्रेस पाएं",
	"home_link_title_self_custody_1": "अपना Bitcoin सुरक्षित रूप से कैसे स्टोर करें",
	"home_link_title_self_custody_2": "एक्सचेंज से अपना Bitcoin निकालने के 6 कारण",
	"home_link_title_self_custody_3": "सोना, Bitcoin, और स्व-संरक्षण",
	"home_link_title_get_started_1": "Bitcoin की मूल बातें सीखें",
	"home_link_title_get_started_2": "अपना पहला Bitcoin वॉलेट पाएं",
	"home_link_title_get_started_3": "Bitcoin कैसे खरीदें",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "चक्रवृद्धि मुद्रास्फीति कैलकुलेटर",
	"home_link_author_time_magazine": "TIME पत्रिका",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}\n\nDone! Created index.json.`);
