/**
 * Creates Hindi (hi) common_hi.json translation file
 */
const fs = require('fs');
const path = require('path');
const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'hi';
const today = '2026-04-02';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"common_footer_mission_1": "bitcoin.rocks का मिशन शिक्षा के माध्यम से Bitcoin अपनाने में तेज़ी लाना है।",
	"common_footer_mission_2": "जानें कि इस ओपन-सोर्स प्रोजेक्ट में कैसे योगदान करें।",
	"common_footer_follow_first_half": "किसी भी Nostr क्लाइंट में खोजकर",
	"common_footer_follow_second_half": "हमें फ़ॉलो करें।",
	"common_footer_what_is_nostr": "Nostr क्या है?",
	"common_footer_about": "हमारे बारे में",
	"common_footer_email_us": "हमें ईमेल करें:",
	"common_cta_section_get_started": "शुरू करें",
	"common_cta_section_with_bitcoin": "BITCOIN के साथ",
	"common_cta_section_title_1": "Bitcoin की मूल बातें सीखें",
	"common_cta_section_title_1_alt": "Bitcoin के बारे में और जानें",
	"common_cta_section_title_2": "अपना पहला Bitcoin वॉलेट पाएं",
	"common_cta_section_title_3": "Bitcoin कैसे खरीदें",
	"common_cta_link_type_email": "ईमेल",
	"common_cta_link_type_guide": "गाइड",
	"common_cta_link_type_website": "वेबसाइट",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "BITCOIN क्या है?",
	"common_what_is_bitcoin_content_1": "Bitcoin दो चीज़ें हैं: एक डिजिटल मुद्रा और एक भुगतान नेटवर्क। आप Bitcoin नेटवर्क (भुगतान नेटवर्क) का उपयोग करके सीधे दूसरों को Bitcoin (डिजिटल मुद्रा) भेज सकते हैं।",
	"common_what_is_bitcoin_content_2": "Bitcoin मूल्य को स्टोर और ट्रांसफ़र करने का एक बिल्कुल नया तरीका है। पारंपरिक वित्तीय नेटवर्कों के विपरीत, Bitcoin नेटवर्क बिना किसी केंद्रीय प्राधिकरण या विश्वसनीय प्रशासक के काम कर सकता है। यह Bitcoin को अब तक की पहली खुली और सीमाहीन मुद्रा बनाता है।",
	"common_what_is_bitcoin_content_3": "Bitcoin एक डिजिटल मुद्रा है जो आपको आपकी संपत्ति पर पूर्ण स्वामित्व देती है। मानव इतिहास में पहली बार हर कोई ऐसी संपत्ति का मालिक हो सकता है जो वास्तव में दुर्लभ है, उपयोग के लिए अनुमति की आवश्यकता नहीं है, और सही तरीके से संग्रहीत होने पर ज़ब्त नहीं की जा सकती।",
	"common_what_is_bitcoin_content_4": "Bitcoin दुनिया में कहीं भी, तेज़ी से और सस्ते में भेजा जा सकता है। इसे बैंक जैसे किसी तीसरे पक्ष की ज़रूरत नहीं है।",
	"common_what_is_bitcoin_content_5": "Bitcoin किसी को भी अपनी संपत्ति सुरक्षित रूप से स्टोर करने की अनुमति देता है, बिना इस चिंता के कि सरकार इसे चुरा लेगी या मुद्रा छापकर इसकी कीमत कम कर देगी।",
	"common_what_is_bitcoin_content_6": "हर जगह सरकारें अधिक कागज़ी मुद्रा छाप सकती हैं, लेकिन कोई भी अधिक Bitcoin नहीं छाप सकता।",
	"common_what_is_bitcoin_content_7": "आप आसानी से अपने Bitcoin को स्व-संरक्षण में रख सकते हैं, जिससे आपको पूर्ण नियंत्रण मिलता है और Bitcoin की पूरी शक्ति का लाभ मिलता है।",
	"common_what_is_bitcoin_content_8": "अगर आप ऐप डाउनलोड कर सकते हैं, तो आप Bitcoin को स्व-संरक्षण में रख सकते हैं और किसी और पर निर्भर हुए बिना अपनी संपत्ति स्टोर कर सकते हैं।",
	"common_what_is_bitcoin_content_9": "Bitcoin बेहतर मुद्रा है।",
	"common_bitcoin_volatile": "मैंने सुना है BITCOIN बहुत अस्थिर है। क्या यह सुरक्षित है?",
	"common_bitcoin_volatile_content_1": "अल्पावधि में, Bitcoin की विनिमय दर में उतार-चढ़ाव होता है। इसे अस्थिरता कहते हैं।",
	"common_bitcoin_volatile_content_2": "लेकिन जो अस्थिरता आप दिन-प्रतिदिन देखते हैं वह लंबे समय में 'गायब' हो जाती है।",
	"common_bitcoin_volatile_content_3": "समय के साथ Bitcoin कम से कम अस्थिर होता जा रहा है। जितने अधिक लोग Bitcoin को दीर्घकालिक बचत खाते के रूप में उपयोग करते हैं, उतना ही इसकी कीमत स्थिर होती है।",
	"common_bitcoin_volatile_content_4": "कई लोग अस्थिरता के जोखिम को कम करने और समय के साथ अपनी क्रय शक्ति की रक्षा करने के सुरक्षित तरीके के रूप में कई वर्षों तक Bitcoin में मूल्य स्टोर करना चुनते हैं।",
	"common_bitcoin_volatile_content_5": "वेनेज़ुएला, सूडान, लेबनान, सीरिया, अर्जेंटीना, तुर्की, ब्राज़ील और कई अन्य देशों में, स्थानीय मुद्रा इतनी तेज़ी से गिरती है कि Bitcoin को बचत का अधिक स्थिर तरीका माना जाता है।",
	"common_bitcoin_afford": "मैं पूरा BITCOIN नहीं खरीद सकता",
	"common_bitcoin_afford_content_1": "एक डॉलर 100 सेंट से बनता है। एक Bitcoin 100,000,000 (10 करोड़) सैट्स से बनता है।",
	"common_bitcoin_afford_content_2": "आपको पूरा Bitcoin खरीदने की ज़रूरत नहीं है। ज़्यादातर लोगों के पास सिर्फ़ सैट्स होते हैं। सैट्स Bitcoin के अंश हैं। उदाहरण के लिए, अगर 1 पूरा Bitcoin $100,000 है तो $1 से आपको 1,000 सैट्स मिलते हैं!",
	"common_bitcoin_hacked": "क्या BITCOIN कभी हैक हुआ है?",
	"common_bitcoin_hacked_content_1": "आपने ऑनलाइन या समाचारों में 'Bitcoin हैक' के बारे में सुना होगा। अधिकांश लोग इन लेखों को पढ़कर मानते हैं कि Bitcoin नेटवर्क हैक हो गया है। हालांकि, Bitcoin नेटवर्क कभी हैक नहीं हुआ है।",
	"common_bitcoin_hacked_content_2": "Bitcoin नेटवर्क क्या है? Bitcoin नेटवर्क को रेलवे ट्रैक समझें। Bitcoin नेटवर्क के ट्रैक पर चलने वाली ट्रेनें Bitcoin लेनदेन हैं।",
	"common_bitcoin_hacked_content_3": "जब आप समाचारों में Bitcoin हैक के बारे में पढ़ते हैं, तो आप किसी कस्टोडियन (जैसे FTX) के हैक होने या दिवालिया होने के बारे में पढ़ रहे होते हैं।",
	"common_bitcoin_hacked_content_4": "कस्टोडियन ऐसी कंपनियां हैं जो आपके लिए आपका Bitcoin रखती हैं। लेकिन इसमें जोखिम है: जब कंपनी गलत प्रबंधन करे, चोरी करे, या बंद हो जाए तो आपका Bitcoin खो सकता है।",
	"common_bitcoin_hacked_content_5": "यह सबसे हाल ही में FTX के साथ हुआ।",
	"common_bitcoin_hacked_content_6": "हर किसी ने जिसने FTX पर भरोसा करके अपना Bitcoin रखा था, उसने अपना Bitcoin खो दिया। हर किसी ने जिसने अपना Bitcoin स्व-संरक्षण में रखा था, वह FTX से पूरी तरह अप्रभावित रहा। यही स्व-संरक्षण में Bitcoin की शक्ति है: अपने पैसे पर सच्चा नियंत्रण।",
	"common_bitcoin_hacked_content_7": "अपना Bitcoin किसी एक्सचेंज या ETF जैसे रैपर में छोड़ने की बजाय, सभी स्वतंत्रता लाभों के लिए इसे अपने वॉलेट में रखें।",
	"common_bitcoin_hacked_content_8": "जब आप अपना Bitcoin स्व-संरक्षण में रखते हैं, तो आपका पैसा Bitcoin नेटवर्क द्वारा सुरक्षित रहता है। यह दुनिया का सबसे सुरक्षित वित्तीय नेटवर्क है।",
	"common_bitcoin_hacked_content_9": "स्व-संरक्षण में, FTX का Sam आपका Bitcoin नहीं चुरा सकता।",
	"common_bitcoin_hacked_content_10": "सरकार अधिक Bitcoin नहीं छाप सकती और मुद्रास्फीति नहीं कर सकती।",
	"common_bitcoin_hacked_content_11": "स्व-संरक्षण में Bitcoin आपका पैसा है, Bitcoin नेटवर्क की शक्ति की बदौलत।",
	"common_bitcoin_energy": "BITCOIN ऊर्जा क्यों उपयोग करता है?",
	"common_bitcoin_energy_content_1": "Bitcoin नेटवर्क को सुरक्षित करने और आपके पैसे की रक्षा के लिए ऊर्जा का उपयोग करता है।",
	"common_bitcoin_energy_content_2": "Bitcoin काफी मात्रा में ऊर्जा का उपयोग करता है, और यह कई कारणों से एक अच्छी बात है।",
	"common_bitcoin_energy_list_1": "Bitcoin में बैंक रन नहीं होते।",
	"common_bitcoin_energy_list_2": "Bitcoin माइनिंग से ऊर्जा ग्रिड को स्थिर करने में मदद मिलती है।",
	"common_bitcoin_energy_list_3": "Bitcoin तेल ड्रिलिंग से उत्सर्जन कम करता है।",
	"common_bitcoin_energy_list_4": "Bitcoin अमेरिकियों द्वारा हर साल क्रिसमस लाइट्स पर खर्च की जाने वाली ऊर्जा से कम ऊर्जा का उपयोग करता है।",
	"common_bitcoin_energy_list_5": "Bitcoin पृथ्वी पर सबसे हरित उद्योग है!",
	"common_cic_intro_1": "बहुत से लोग चक्रवृद्धि ब्याज के बारे में जानते हैं, लेकिन बहुत कम लोग चक्रवृद्धि मुद्रास्फीति के बारे में जानते हैं।",
	"common_cic_intro_2": "हमारे चक्रवृद्धि मुद्रास्फीति कैलकुलेटर से, आप आसानी से गणना कर सकते हैं कि समय के साथ अपनी क्रय शक्ति बनाए रखने के लिए आपकी सैलरी को कितना बढ़ना चाहिए।",
	"common_cic_intro_3": "बस अपनी वर्तमान सैलरी, मुद्रास्फीति दर, और जितने वर्षों की गणना करनी है वह दर्ज करें, और हमारा कैलकुलेटर दिखाएगा कि मुद्रास्फीति के साथ बने रहने के लिए आपकी सैलरी क्या होनी चाहिए।",
	"common_current_salary": "वर्तमान सैलरी",
	"common_inflation_rate": "मुद्रास्फीति दर",
	"common_year": "वर्ष",
	"common_years": "वर्ष",
	"common_result_starting_message": "ऊपर फ़ॉर्म भरें और कैलकुलेट पर क्लिक करें।",
	"common_error_message": "त्रुटि: कृपया सभी 3 फ़ॉर्म फ़ील्ड भरें।",
	"common_result_message_1": "मुद्रास्फीति दर",
	"common_result_message_2": "के साथ, आपकी",
	"common_result_message_3": "सैलरी को बढ़कर",
	"common_result_message_in": "में",
	"common_result_message_4": "होनी चाहिए ताकि आपकी क्रय शक्ति बनी रहे।",
	"common_calculate_button_text": "गणना करें",
	"common_learn_more": "और जानें",
	"common_success": "सफ़ल!",
	"common_choose_your_country": "अपना देश चुनें",
	"common_country_usa": "अमेरिका",
	"common_country_canada": "कनाडा",
	"common_submit": "सबमिट करें",
	"common_language_afrikaans": "अफ़्रीकान्स",
	"common_language_arabic": "अरबी",
	"common_language_basque": "बास्क",
	"common_language_bulgarian": "बुल्गारियाई",
	"common_language_catalan": "कातालान",
	"common_language_chinese": "चीनी",
	"common_language_croatian": "क्रोएशियाई",
	"common_language_czech": "चेक",
	"common_language_danish": "डैनिश",
	"common_language_dutch": "डच",
	"common_language_english": "अंग्रेज़ी",
	"common_language_estonian": "एस्टोनियाई",
	"common_language_filipino": "फ़िलिपिनो",
	"common_language_finnish": "फ़िनिश",
	"common_language_french": "फ़्रेंच",
	"common_language_german": "जर्मन",
	"common_language_greek": "ग्रीक",
	"common_language_hausa": "हौसा",
	"common_language_hebrew": "हिब्रू",
	"common_language_hindi": "हिन्दी",
	"common_language_hungarian": "हंगेरियाई",
	"common_language_indonesian": "इंडोनेशियाई",
	"common_language_irish": "आयरिश",
	"common_language_italian": "इतालवी",
	"common_language_japanese": "जापानी",
	"common_language_korean": "कोरियाई",
	"common_language_malay": "मलय",
	"common_language_norwegian": "नॉर्वेजियन",
	"common_language_persian": "फ़ारसी",
	"common_language_polish": "पोलिश",
	"common_language_portuguese": "पुर्तगाली",
	"common_language_russian": "रूसी",
	"common_language_sinhala": "सिंहली",
	"common_language_slovak": "स्लोवाक",
	"common_language_slovenian": "स्लोवेनियाई",
	"common_language_spanish": "स्पैनिश",
	"common_language_swahili": "स्वाहिली",
	"common_language_swedish": "स्वीडिश",
	"common_language_thai": "थाई",
	"common_language_turkish": "तुर्की",
	"common_language_urdu": "उर्दू",
	"common_language_vietnamese": "वियतनामी",
	"common_language_yoruba": "योरूबा",
	"common_stickers_bulk_mess": "फ़ाइलों से खुद नहीं जूझना चाहते?",
	"common_stickers_bulk_want": "कुछ से ज़्यादा स्टिकर चाहिए?",
	"common_stickers_bulk_store": "उसी प्रिंटर से थोक में स्टिकर ऑर्डर करें जिसका हम उपयोग करते हैं।",
	"common_stickers_bulk_cheaper": "जितने अधिक स्टिकर खरीदेंगे, प्रति स्टिकर उतने सस्ते होंगे।",
	"common_stickers_print_instructions_1": "आप कहीं भी रहें, अपने खुद के स्टिकर प्रिंट करके भाग ले सकते हैं! स्टिकर फ़ाइलें और निर्देश डाउनलोड करने के लिए नीचे अपनी भाषा पर क्लिक करें।",
	"common_stickers_print_instructions_2": "कृपया ध्यान दें: सभी स्टिकर सभी भाषाओं में उपलब्ध नहीं हैं।",
	"common_stickers_request_language_1": "अपनी भाषा नहीं दिख रही?",
	"common_stickers_request_language_2": "अपनी स्थानीय भाषा में स्टिकर फ़ाइलों का अनुरोध करने के लिए नीचे फ़ॉर्म भरें।",
	"common_stickers_dimensions": "आयाम:",
	"common_stickers_type": "प्रकार:",
	"common_stickers_material": "सामग्री:",
	"common_stickers_where_to_print": "कहाँ प्रिंट करें:",
	"common_stickers_type_die_cut": "डाई-कट स्टिकर",
	"common_stickers_material_vinyl": "बाहरी उपयोग के लिए विनाइल स्टिकर",
	"common_stickers_printer": "हम StickerMule.com उपयोग करते हैं लेकिन आप कोई भी स्टिकर कंपनी उपयोग कर सकते हैं।",
	"common_stickers_dimensions_danger": "11.4544 सेमी x 8.382 सेमी (4.51 इंच x 3.3 इंच)",
	"common_stickers_dimensions_warning": "10.414 सेमी x 9.2202 सेमी (4.1 इंच x 3.63 इंच)",
	"common_stickers_dimensions_caution": "12.0142 सेमी x 7.9502 सेमी (4.73 इंच x 3.13 इंच)",
	"common_stickers_dimensions_fix": "11.3792 सेमी x 6.8072 सेमी (4.48 इंच x 2.68 इंच)",
	"common_stickers_dimensions_study": "14.605 सेमी x 5.1308 सेमी (5.75 इंच x 2.02 इंच)",
	"common_stickers_dimensions_bdhi": "21.59 सेमी x 4.6482 सेमी (8.5 इंच x 1.83 इंच)",
	"common_stickers_dimensions_cure_v2": "6.35 सेमी x 12.7 सेमी (2.5 इंच x 5 इंच)",
	"common_stickers_dimensions_got_inflation": "7.9248 सेमी x 14.605 सेमी (3.12 इंच x 5.75 इंच)",
	"common_stickers_dimensions_what_if": "21.7932 सेमी x 7.62 सेमी (8.58 इंच x 3 इंच)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20.995 सेमी x 6.35 सेमी (8.25 इंच x 2.5 इंच)",
	"common_nostr_join": "अभी NOSTR से जुड़ें",
	"common_nostr_protocol_header": "प्रोटोकॉल, प्लेटफ़ॉर्म नहीं",
	"common_nostr_protocol_c1": "Nostr एक नया प्रोटोकॉल है जो आपको सेंसरशिप, डीप्लेटफ़ॉर्मिंग, या डीबूस्टिंग के डर के बिना ऑनलाइन संवाद करने की अनुमति देता है।",
	"common_nostr_protocol_c2": "Twitter और Facebook जैसे प्लेटफ़ॉर्म एक कंपनी द्वारा नियंत्रित होते हैं, लेकिन Nostr प्रोटोकॉल पर किसी का नियंत्रण नहीं है।",
	"common_nostr_freedom_header": "जाने की स्वतंत्रता",
	"common_nostr_freedom_c1": "Nostr ईमेल के समान है। कोई भी ईमेल प्रोटोकॉल को नियंत्रित नहीं करता, और कोई भी इस पर क्लाइंट (जैसे Gmail, Hotmail, आदि) बना सकता है।",
	"common_nostr_freedom_c2": "कोई भी Nostr प्रोटोकॉल को नियंत्रित नहीं करता, और कोई भी इस पर क्लाइंट (जैसे Damus, Amethyst, आदि) बना सकता है।",
	"common_nostr_freedom_c3": "अगर आपको किसी क्लाइंट का काम करने का तरीका पसंद नहीं है, तो आप बिना अपने फ़ॉलोअर्स या सामग्री खोए अपना Nostr अकाउंट दूसरे क्लाइंट पर ट्रांसफ़र कर सकते हैं।",
	"common_nostr_bitcoin_header": "Bitcoin अंतर्निहित है",
	"common_nostr_bitcoin_c1": "Bitcoin Nostr प्रोटोकॉल में मूल रूप से अंतर्निहित है। अगर आपको कोई सामग्री पसंद आए, तो आप आसानी से किसी को धन्यवाद के रूप में Bitcoin भेज सकते हैं!",
	"common_nostr_bitcoin_c2": "Twitter और Facebook जैसे केंद्रीकृत प्लेटफ़ॉर्म पर, केंद्रीकृत कंपनी आपकी सामग्री से पैसा कमाती है। लेकिन Nostr जैसे खुले प्रोटोकॉल पर, आप अपनी सामग्री से पैसा कमाते हैं।",
	"common_nostr_download_client": "NOSTR से जुड़ने के लिए मुफ़्त क्लाइंट डाउनलोड करें",
	"common_nostr_iphone_clients": "iPhone क्लाइंट",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "iPhone ऐप",
	"common_nostr_first_client": "पहले क्लाइंट के रूप में सुझाया गया",
	"common_nostr_wallet_built_in": "अंतर्निहित Bitcoin ज़ैप वॉलेट",
	"common_nostr_download_now": "अभी डाउनलोड करें",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "परिचित इंटरफ़ेस",
	"common_nostr_separate_wallet": "अलग Bitcoin वॉलेट की ज़रूरत है",
	"common_nostr_android_clients": "Android क्लाइंट",
	"common_nostr_android_app": "Android ऐप",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "कई सुविधाएं",
	"common_nostr_browser_clients": "ब्राउज़र क्लाइंट",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "वेब क्लाइंट",
	"common_nostr_simple": "बहुत सरल",
	"common_nostr_test": "टेस्ट अकाउंट से Nostr आज़माने का आसान तरीका",
	"common_nostr_view_client": "क्लाइंट देखें",
	"common_kit_printer": "हम अपने Bitcoin बिज़नेस किट ब्रोशर प्रिंट करने के लिए VistaPrint.com की सलाह देते हैं। हालांकि, आप कोई भी प्रिंटिंग कंपनी उपयोग कर सकते हैं जो दोनों तरफ प्रिंट कर सके।",
	"common_kit_link_to_print": "प्रिंट लिंक:",
	"common_kit_fold": "फ़ोल्ड:",
	"common_kit_fold_trifold": "तीन-फ़ोल्ड",
	"common_kit_unfolded_size": "खुला आकार:",
	"common_kit_unfolded_size_bbk": "लेटर साइज़ (8.5 इंच x 11 इंच)",
	"common_kit_paper_thickness": "कागज़ की मोटाई:",
	"common_kit_paper_thickness_standard": "स्टैंडर्ड",
	"common_kit_paper_stock": "कागज़ का प्रकार:",
	"common_kit_paper_stock_glossy": "ग्लॉसी",
	"common_kit_exterior_print_file": "बाहरी प्रिंट फ़ाइल:",
	"common_kit_interior_print_file": "आंतरिक प्रिंट फ़ाइल:",
	"common_kit_cta_header": "स्थानीय व्यवसाय को Bitcoin स्वीकार करने के लिए मनाएं",
	"common_biz_learn": "जानें Bitcoin व्यवसाय के लिए क्यों अच्छा है",
	"common_biz_wallets": "Bitcoin भुगतान स्वीकार करने के लिए वॉलेट पाएं",
	"common_biz_maps": "Bitcoin व्यापारी मानचित्र पर सूचीबद्ध हों",
	"common_biz_stickers": "मुफ़्त 'यहाँ Bitcoin स्वीकार किया जाता है' स्टिकर",
	"common_biz_rewards": "Bitcoin पुरस्कार",
	"common_biz_accounting": "Bitcoin लेखांकन गाइड",
	"common_biz_faq": "अक्सर पूछे जाने वाले प्रश्न",
	"common_biz_kit": "अपना Bitcoin बिज़नेस किट प्रिंट करें",
	"common_biz_accept_bitcoin_payments": "BITCOIN भुगतान स्वीकार करें",
	"common_biz_ready": "अपने व्यवसाय में BITCOIN स्वीकार करने के लिए तैयार हैं?",
	"common_biz_more": "और व्यावसायिक संसाधन",
	"common_self_custody": "स्व-संरक्षण",
	"common_not_your_keys": "आपकी कुंजी नहीं",
	"common_cold_wallet": "कोल्ड वॉलेट",
	"common_hot_wallet": "हॉट वॉलेट",
	"common_sticker_files_mission_1": "हमारा मिशन सार्वजनिक स्थानों पर Bitcoin स्टिकर लगाकर अधिक लोगों को Bitcoin के बारे में जागरूक करने में आपकी मदद करना है। हमारे सभी स्टिकर पर QR कोड हैं जो",
	"common_sticker_files_mission_2": "Bitcoin",
	"common_sticker_files_mission_3": "मुद्रास्फीति",
	"common_sticker_files_mission_4": "के शैक्षिक पेजों से जुड़ते हैं। अगर आप अमेरिका या कनाडा में रहते हैं, तो आप",
	"common_sticker_files_mission_5": "मुफ़्त अंग्रेज़ी स्टिकर पैक का अनुरोध कर सकते हैं",
	"common_published_by": "प्रकाशक",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "2022 से Bitcoin शिक्षा",
	"common_publisher_open_source": "ओपन-सोर्स प्रोजेक्ट",
	"common_reviewed_accuracy": "✓ सटीकता के लिए समीक्षित: 2026",
	"common_footer_tagline": "शिक्षा के माध्यम से Bitcoin अपनाने में तेज़ी।",
	"common_footer_contribute": "योगदान करें",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "स्रोत"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log(`\nDone! Created common.json.`);
