/**
 * Creates Vietnamese (vi) translation file for common.json (~180+ keys)
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'vi';
const today = '2026-04-02';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"common_footer_mission_1": "Sứ mệnh của bitcoin.rocks là thúc đẩy việc áp dụng bitcoin thông qua giáo dục.",
	"common_footer_mission_2": "Tìm hiểu cách đóng góp cho dự án mã nguồn mở này.",
	"common_footer_follow_first_half": "Theo dõi chúng tôi trên Nostr bằng cách tìm kiếm",
	"common_footer_follow_second_half": "trên bất kỳ ứng dụng Nostr nào.",
	"common_footer_what_is_nostr": "Nostr là gì?",
	"common_footer_about": "Giới thiệu",
	"common_footer_email_us": "Email chúng tôi:",
	"common_cta_section_get_started": "BẮT ĐẦU",
	"common_cta_section_with_bitcoin": "VỚI BITCOIN",
	"common_cta_section_title_1": "Tìm hiểu cơ bản về Bitcoin",
	"common_cta_section_title_1_alt": "Tìm hiểu thêm về Bitcoin",
	"common_cta_section_title_2": "Tạo ví Bitcoin đầu tiên",
	"common_cta_section_title_3": "Cách mua Bitcoin",
	"common_cta_link_type_email": "EMAIL",
	"common_cta_link_type_guide": "HƯỚNG DẪN",
	"common_cta_link_type_website": "TRANG WEB",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "BITCOIN LÀ GÌ?",
	"common_what_is_bitcoin_content_1": "Bitcoin là hai thứ: một loại tiền kỹ thuật số và một mạng thanh toán. Bạn có thể gửi Bitcoin (tiền kỹ thuật số) trực tiếp cho người khác bằng mạng Bitcoin (mạng thanh toán).",
	"common_what_is_bitcoin_content_2": "Bitcoin là một cách hoàn toàn mới để lưu trữ và giao dịch giá trị. Không giống các mạng tài chính thông thường, mạng Bitcoin có thể hoạt động mà không cần cơ quan trung ương hay quản trị viên đáng tin cậy. Điều đó khiến Bitcoin trở thành loại tiền mở và không biên giới đầu tiên từ trước đến nay.",
	"common_what_is_bitcoin_content_3": "Bitcoin là tiền kỹ thuật số cho bạn quyền sở hữu hoàn toàn đối với tài sản. Lần đầu tiên trong lịch sử nhân loại, mọi người đều có thể sở hữu tài sản thực sự khan hiếm, không cần xin phép để sử dụng, và không thể bị tịch thu khi lưu trữ đúng cách.",
	"common_what_is_bitcoin_content_4": "Bitcoin có thể được gửi đến bất kỳ đâu trên thế giới, nhanh chóng và rẻ. Nó không cần bên trung gian thứ ba, như ngân hàng.",
	"common_what_is_bitcoin_content_5": "Bitcoin cho phép bất kỳ ai lưu trữ tài sản an toàn mà không lo chính phủ đánh cắp hoặc làm mất giá trị thông qua in tiền.",
	"common_what_is_bitcoin_content_6": "Chính phủ ở khắp nơi có thể in thêm tiền giấy, nhưng không ai có thể in thêm bitcoin.",
	"common_what_is_bitcoin_content_7": "Bạn có thể dễ dàng tự lưu trữ Bitcoin để nắm toàn quyền kiểm soát, cho bạn truy cập đầy đủ sức mạnh của Bitcoin.",
	"common_what_is_bitcoin_content_8": "Nếu bạn có thể tải ứng dụng, bạn có thể tự lưu trữ Bitcoin và bảo vệ tài sản mà không phụ thuộc vào ai.",
	"common_what_is_bitcoin_content_9": "Bitcoin là tiền tốt hơn.",
	"common_bitcoin_volatile": "TÔI NGHE NÓI BITCOIN BIẾN ĐỘNG. CÓ AN TOÀN KHÔNG?",
	"common_bitcoin_volatile_content_1": "Trong ngắn hạn, tỷ giá của Bitcoin có xu hướng dao động. Đây được gọi là biến động.",
	"common_bitcoin_volatile_content_2": "Nhưng biến động bạn thấy hàng ngày 'biến mất' trong dài hạn.",
	"common_bitcoin_volatile_content_3": "Bitcoin tiếp tục ngày càng ít biến động theo thời gian. Càng nhiều người sử dụng Bitcoin như tài khoản tiết kiệm dài hạn, giá trị của nó càng ổn định.",
	"common_bitcoin_volatile_content_4": "Nhiều người chọn lưu trữ giá trị bằng Bitcoin trong nhiều năm như cách an toàn để giảm thiểu rủi ro biến động và bảo vệ sức mua theo thời gian.",
	"common_bitcoin_volatile_content_5": "Ở một số quốc gia, như Venezuela, Sudan, Lebanon, Syria, Argentina, Thổ Nhĩ Kỳ, Brazil, và nhiều nơi khác, giá trị của đồng tiền địa phương lạm phát nhanh đến mức Bitcoin được coi là cách tiết kiệm ổn định hơn.",
	"common_bitcoin_afford": "TÔI KHÔNG ĐỦ KHẢ NĂNG MUA MỘT BITCOIN",
	"common_bitcoin_afford_content_1": "Một đô la gồm 100 xu. Một bitcoin gồm 100.000.000 (100 triệu) sats.",
	"common_bitcoin_afford_content_2": "Bạn không cần phải sở hữu một bitcoin nguyên. Hầu hết mọi người chỉ sở hữu sats. Sats là phần nhỏ của một bitcoin. Ví dụ, nếu 1 bitcoin nguyên là $100.000 thì $1 mua được 1.000 sats!",
	"common_bitcoin_hacked": "BITCOIN ĐÃ BAO GIỜ BỊ HACK CHƯA?",
	"common_bitcoin_hacked_content_1": "Bạn có thể đã nghe về 'hack Bitcoin' trên mạng hoặc tin tức. Hầu hết mọi người đọc các bài viết này và tin rằng mạng Bitcoin đã bị hack. Tuy nhiên, mạng Bitcoin chưa bao giờ bị hack.",
	"common_bitcoin_hacked_content_2": "Mạng Bitcoin là gì? Hãy nghĩ về mạng Bitcoin như đường ray xe lửa. Các đoàn tàu chạy trên đường ray của mạng Bitcoin là các giao dịch Bitcoin.",
	"common_bitcoin_hacked_content_3": "Khi bạn đọc về vụ hack Bitcoin trên tin tức, bạn đang đọc về một tổ chức lưu ký (như FTX) bị hack hoặc phá sản.",
	"common_bitcoin_hacked_content_4": "Tổ chức lưu ký là các công ty giữ bitcoin cho bạn. Tuy nhiên, điều này mang rủi ro: mất bitcoin khi công ty quản lý sai, đánh cắp, hoặc ngừng kinh doanh.",
	"common_bitcoin_hacked_content_5": "Điều này đã xảy ra gần đây nhất với FTX.",
	"common_bitcoin_hacked_content_6": "Mọi người tin tưởng FTX với bitcoin của họ đều mất bitcoin. Mọi người giữ bitcoin tự lưu trữ hoàn toàn không bị ảnh hưởng bởi FTX. Đó là sức mạnh của bitcoin tự lưu trữ: kiểm soát thực sự đối với tiền của bạn.",
	"common_bitcoin_hacked_content_7": "Thay vì để bitcoin trên sàn giao dịch hoặc trong các sản phẩm bao bọc như ETF, hãy giữ nó trong ví riêng để tận hưởng mọi lợi ích tự do.",
	"common_bitcoin_hacked_content_8": "Khi bạn tự lưu trữ bitcoin, tiền của bạn được bảo vệ bởi mạng Bitcoin. Đây là mạng tài chính an toàn nhất thế giới.",
	"common_bitcoin_hacked_content_9": "Khi tự lưu trữ, Sam từ FTX không thể đánh cắp bitcoin của bạn.",
	"common_bitcoin_hacked_content_10": "Chính phủ không thể in thêm bitcoin và gây lạm phát.",
	"common_bitcoin_hacked_content_11": "Bitcoin tự lưu trữ là tiền của bạn, nhờ sức mạnh của mạng Bitcoin.",
	"common_bitcoin_energy": "TẠI SAO BITCOIN SỬ DỤNG NĂNG LƯỢNG?",
	"common_bitcoin_energy_content_1": "Bitcoin sử dụng năng lượng để bảo mật mạng và bảo vệ tiền của bạn.",
	"common_bitcoin_energy_content_2": "Bitcoin sử dụng một lượng năng lượng đáng kể, và đây là điều tuyệt vời vì nhiều lý do.",
	"common_bitcoin_energy_list_1": "Bitcoin không có tình trạng rút tiền hàng loạt tại ngân hàng.",
	"common_bitcoin_energy_list_2": "Bitcoin giúp ổn định lưới điện bằng khai thác bitcoin.",
	"common_bitcoin_energy_list_3": "Bitcoin giảm phát thải từ khai thác dầu.",
	"common_bitcoin_energy_list_4": "Bitcoin sử dụng ít năng lượng hơn người Mỹ dùng cho đèn Giáng Sinh mỗi năm.",
	"common_bitcoin_energy_list_5": "Bitcoin là ngành công nghiệp xanh nhất trên Trái Đất!",
	"common_cic_intro_1": "Nhiều người biết về Lãi Kép, nhưng ít người biết về Lạm Phát Gộp.",
	"common_cic_intro_2": "Với Máy Tính Lạm Phát Gộp, bạn có thể dễ dàng tính toán mức lương cần tăng để duy trì sức mua theo thời gian.",
	"common_cic_intro_3": "Chỉ cần nhập mức lương hiện tại, tỷ lệ lạm phát, và số năm bạn muốn tính, máy tính sẽ cho bạn thấy mức lương cần đạt để theo kịp lạm phát.",
	"common_current_salary": "mức lương hiện tại",
	"common_inflation_rate": "tỷ lệ lạm phát",
	"common_year": "năm",
	"common_years": "năm",
	"common_result_starting_message": "Điền biểu mẫu trên và nhấn tính toán.",
	"common_error_message": "Lỗi: Vui lòng điền đầy đủ 3 trường biểu mẫu.",
	"common_result_message_1": "Với tỷ lệ lạm phát",
	"common_result_message_2": "mức lương",
	"common_result_message_3": "của bạn cần tăng lên",
	"common_result_message_in": "trong",
	"common_result_message_4": "để duy trì sức mua.",
	"common_calculate_button_text": "TÍNH TOÁN",
	"common_learn_more": "TÌM HIỂU THÊM",
	"common_success": "THÀNH CÔNG!",
	"common_choose_your_country": "Chọn quốc gia của bạn",
	"common_country_usa": "Hoa Kỳ",
	"common_country_canada": "Canada",
	"common_submit": "GỬI",
	"common_language_afrikaans": "TIẾNG AFRIKAANS",
	"common_language_arabic": "TIẾNG Ả RẬP",
	"common_language_basque": "TIẾNG BASQUE",
	"common_language_bulgarian": "TIẾNG BULGARIA",
	"common_language_catalan": "TIẾNG CATALAN",
	"common_language_chinese": "TIẾNG TRUNG QUỐC",
	"common_language_croatian": "TIẾNG CROATIA",
	"common_language_czech": "TIẾNG SÉC",
	"common_language_danish": "TIẾNG ĐAN MẠCH",
	"common_language_dutch": "TIẾNG HÀ LAN",
	"common_language_english": "TIẾNG ANH",
	"common_language_estonian": "TIẾNG ESTONIA",
	"common_language_filipino": "TIẾNG FILIPINO",
	"common_language_finnish": "TIẾNG PHẦN LAN",
	"common_language_french": "TIẾNG PHÁP",
	"common_language_german": "TIẾNG ĐỨC",
	"common_language_greek": "TIẾNG HY LẠP",
	"common_language_hausa": "TIẾNG HAUSA",
	"common_language_hebrew": "TIẾNG DO THÁI",
	"common_language_hindi": "TIẾNG HINDI",
	"common_language_hungarian": "TIẾNG HUNGARY",
	"common_language_indonesian": "TIẾNG INDONESIA",
	"common_language_irish": "TIẾNG IRELAND",
	"common_language_italian": "TIẾNG Ý",
	"common_language_japanese": "TIẾNG NHẬT",
	"common_language_korean": "TIẾNG HÀN QUỐC",
	"common_language_malay": "TIẾNG MÃ LAI",
	"common_language_norwegian": "TIẾNG NA UY",
	"common_language_persian": "TIẾNG BA TƯ",
	"common_language_polish": "TIẾNG BA LAN",
	"common_language_portuguese": "TIẾNG BỒ ĐÀO NHA",
	"common_language_russian": "TIẾNG NGA",
	"common_language_sinhala": "TIẾNG SINHALA",
	"common_language_slovak": "TIẾNG SLOVAK",
	"common_language_slovenian": "TIẾNG SLOVENIA",
	"common_language_spanish": "TIẾNG TÂY BAN NHA",
	"common_language_swahili": "TIẾNG SWAHILI",
	"common_language_swedish": "TIẾNG THỤY ĐIỂN",
	"common_language_thai": "TIẾNG THÁI",
	"common_language_turkish": "TIẾNG THỔ NHĨ KỲ",
	"common_language_urdu": "TIẾNG URDU",
	"common_language_vietnamese": "TIẾNG VIỆT",
	"common_language_yoruba": "TIẾNG YORUBA",
	"common_stickers_bulk_mess": "Không muốn tự xử lý tập tin?",
	"common_stickers_bulk_want": "Muốn nhiều hơn chỉ vài nhãn dán?",
	"common_stickers_bulk_store": "Đặt nhãn dán số lượng lớn từ cùng nhà in chúng tôi sử dụng.",
	"common_stickers_bulk_cheaper": "Càng mua nhiều nhãn dán, giá mỗi nhãn dán càng rẻ.",
	"common_stickers_print_instructions_1": "Bạn có thể tham gia bằng cách tự in nhãn dán, bất kể bạn sống ở đâu! Nhấp vào ngôn ngữ bên dưới để tải xuống tập tin nhãn dán & hướng dẫn.",
	"common_stickers_print_instructions_2": "Xin lưu ý: không phải tất cả nhãn dán đều có sẵn bằng tất cả ngôn ngữ.",
	"common_stickers_request_language_1": "Không thấy ngôn ngữ của bạn?",
	"common_stickers_request_language_2": "Điền biểu mẫu bên dưới để yêu cầu tập tin nhãn dán bằng ngôn ngữ địa phương.",
	"common_stickers_dimensions": "Kích thước:",
	"common_stickers_type": "Loại:",
	"common_stickers_material": "Chất liệu:",
	"common_stickers_where_to_print": "Nơi in:",
	"common_stickers_type_die_cut": "nhãn dán cắt khuôn",
	"common_stickers_material_vinyl": "nhãn dán vinyl dùng ngoài trời",
	"common_stickers_printer": "Chúng tôi sử dụng StickerMule.com nhưng bạn có thể dùng bất kỳ công ty nhãn dán nào.",
	"common_stickers_dimensions_danger": "11,4544 cm x 8,382 cm (4,51 in x 3,3 in)",
	"common_stickers_dimensions_warning": "10,414 cm x 9,2202 cm (4,1 in x 3,63 in)",
	"common_stickers_dimensions_caution": "12,0142 cm x 7,9502 cm (4,73 in x 3,13 in)",
	"common_stickers_dimensions_fix": "11,3792 cm x 6,8072 cm (4,48 in x 2,68 in)",
	"common_stickers_dimensions_study": "14,605 cm x 5,1308 cm (5,75 in x 2,02 in)",
	"common_stickers_dimensions_bdhi": "21,59 cm x 4,6482 cm (8,5 in x 1,83 in)",
	"common_stickers_dimensions_cure_v2": "6,35 cm x 12,7 cm (2,5 in x 5 in)",
	"common_stickers_dimensions_got_inflation": "7,9248 cm x 14,605 cm (3,12 in x 5,75 in)",
	"common_stickers_dimensions_what_if": "21,7932 cm x 7,62 cm (8,58 in x 3 in)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20,995 cm x 6,35 cm (8,25 in x 2,5 in)",
	"common_nostr_join": "THAM GIA NOSTR NGAY",
	"common_nostr_protocol_header": "Giao thức, không phải nền tảng",
	"common_nostr_protocol_c1": "Nostr là một giao thức mới cho phép bạn giao tiếp trực tuyến mà không sợ bị kiểm duyệt, gỡ nền tảng, hoặc giảm hiển thị",
	"common_nostr_protocol_c2": "Các nền tảng như Twitter và Facebook được kiểm soát bởi một công ty duy nhất, nhưng không ai kiểm soát giao thức Nostr.",
	"common_nostr_freedom_header": "Tự do di chuyển",
	"common_nostr_freedom_c1": "Nostr tương tự như email. Không ai kiểm soát giao thức email, và bất kỳ ai cũng có thể xây dựng ứng dụng (như Gmail, Hotmail, v.v.) trên đó.",
	"common_nostr_freedom_c2": "Không ai kiểm soát giao thức Nostr, và bất kỳ ai cũng có thể xây dựng ứng dụng (như Damus, Amethyst, v.v.) trên đó.",
	"common_nostr_freedom_c3": "Nếu bạn không thích cách một ứng dụng hoạt động, bạn có thể chuyển tài khoản Nostr sang ứng dụng khác mà không mất người theo dõi hay nội dung.",
	"common_nostr_bitcoin_header": "Bitcoin được tích hợp sẵn",
	"common_nostr_bitcoin_c1": "Bitcoin được tích hợp sẵn vào giao thức Nostr. Nếu bạn thấy nội dung hay, bạn có thể dễ dàng gửi bitcoin cho ai đó như lời cảm ơn!",
	"common_nostr_bitcoin_c2": "Trên các nền tảng tập trung như Twitter và Facebook, công ty tập trung kiếm tiền từ nội dung của bạn. Nhưng trên các giao thức mở như Nostr, bạn kiếm tiền từ nội dung của mình.",
	"common_nostr_download_client": "TẢI ỨNG DỤNG MIỄN PHÍ ĐỂ THAM GIA NOSTR",
	"common_nostr_iphone_clients": "Ứng dụng iPhone",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "Ứng dụng iPhone",
	"common_nostr_first_client": "Ứng dụng đầu tiên được khuyến nghị",
	"common_nostr_wallet_built_in": "Ví zap Bitcoin tích hợp sẵn",
	"common_nostr_download_now": "TẢI NGAY",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "Giao diện quen thuộc",
	"common_nostr_separate_wallet": "Cần ví bitcoin riêng",
	"common_nostr_android_clients": "Ứng dụng Android",
	"common_nostr_android_app": "Ứng dụng Android",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "Nhiều tính năng",
	"common_nostr_browser_clients": "Ứng dụng Trình duyệt",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "Ứng dụng Web",
	"common_nostr_simple": "Siêu đơn giản",
	"common_nostr_test": "Cách dễ dàng để thử Nostr bằng tài khoản thử nghiệm",
	"common_nostr_view_client": "XEM ỨNG DỤNG",
	"common_kit_printer": "Chúng tôi khuyến nghị VistaPrint.com để in tờ rơi Bộ Tài Liệu Doanh Nghiệp Bitcoin. Tuy nhiên, bạn có thể dùng bất kỳ công ty in nào miễn là họ có thể in hai mặt.",
	"common_kit_link_to_print": "Liên kết để in:",
	"common_kit_fold": "Gấp:",
	"common_kit_fold_trifold": "Gấp ba",
	"common_kit_unfolded_size": "Kích thước mở:",
	"common_kit_unfolded_size_bbk": "Khổ Letter (8,5 in x 11 in)",
	"common_kit_paper_thickness": "Độ dày giấy:",
	"common_kit_paper_thickness_standard": "Tiêu chuẩn",
	"common_kit_paper_stock": "Loại giấy:",
	"common_kit_paper_stock_glossy": "Bóng",
	"common_kit_exterior_print_file": "Tập tin in bên ngoài:",
	"common_kit_interior_print_file": "Tập tin in bên trong:",
	"common_kit_cta_header": "Giúp một doanh nghiệp địa phương chấp nhận Bitcoin",
	"common_biz_learn": "Tìm hiểu tại sao Bitcoin tốt cho doanh nghiệp",
	"common_biz_wallets": "Tải ví Bitcoin để chấp nhận thanh toán Bitcoin",
	"common_biz_maps": "Đăng ký trên bản đồ thương nhân Bitcoin",
	"common_biz_stickers": "Nhãn dán miễn phí 'Chấp Nhận Bitcoin Tại Đây'",
	"common_biz_rewards": "Phần thưởng Bitcoin",
	"common_biz_accounting": "Hướng Dẫn Kế Toán Bitcoin",
	"common_biz_faq": "Câu Hỏi Thường Gặp",
	"common_biz_kit": "In Bộ Tài Liệu Doanh Nghiệp Bitcoin của riêng bạn",
	"common_biz_accept_bitcoin_payments": "CHẤP NHẬN THANH TOÁN BITCOIN",
	"common_biz_ready": "SẴN SÀNG CHẤP NHẬN BITCOIN TẠI DOANH NGHIỆP?",
	"common_biz_more": "TÀI NGUYÊN DOANH NGHIỆP KHÁC",
	"common_self_custody": "TỰ LƯU TRỮ",
	"common_not_your_keys": "KHÔNG PHẢI KHÓA CỦA BẠN",
	"common_cold_wallet": "VÍ LẠNH",
	"common_hot_wallet": "VÍ NÓNG",
	"common_sticker_files_mission_1": "Sứ mệnh của chúng tôi là giúp bạn giới thiệu Bitcoin cho nhiều người hơn bằng cách dán nhãn dán Bitcoin ở nơi công cộng. Tất cả nhãn dán của chúng tôi có mã QR liên kết đến các trang giáo dục về",
	"common_sticker_files_mission_2": "Bitcoin",
	"common_sticker_files_mission_3": "lạm phát",
	"common_sticker_files_mission_4": "Nếu bạn sống ở Hoa Kỳ hoặc Canada, bạn có thể",
	"common_sticker_files_mission_5": "yêu cầu một gói nhãn dán tiếng Anh miễn phí",
	"common_published_by": "Được xuất bản bởi",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "Giáo dục Bitcoin từ năm 2022",
	"common_publisher_open_source": "Dự án mã nguồn mở",
	"common_reviewed_accuracy": "✓ Đã xem xét tính chính xác: 2026",
	"common_footer_tagline": "Thúc đẩy việc áp dụng bitcoin thông qua giáo dục.",
	"common_footer_contribute": "Đóng góp",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "Nguồn"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! Created Vietnamese common.json.');
