/**
 * Creates Lithuanian (lt) translation file for index.json (~130+ keys).
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'lt';
const today = '2026-04-04';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

writeFile(`index_${lang}.json`, {
	"bitcoin_builds_a_better_world": "Bitcoin kuria geresn\u012F pasaul\u012F.",
	"home_description": "Bitcoin yra geresni pinigai, kuriantys geresn\u012F pasaul\u012F. Bitcoin apsaugo \u017Emogaus teises, i\u0161gelb\u0117jo \u017Emones nuo didel\u0117s infliacijos, par\u0117m\u0117 vietinius \u016Bkininkus, suma\u017Eino emisijas i\u0161 naftos gavybos ir dar daug daugiau.",
	"home_intro": "Bitcoin yra geresni pinigai, kuriantys geresn\u012F pasaul\u012F. Paspauskite kategorij\u0105 \u017Eemiau, kad su\u017Einotum\u0117te, kaip Bitcoin daro tai geriau, arba tiesiog slinkite \u017Eemyn.",
	"home_btn_money": "GERESNI PINIGAI",
	"home_btn_salary": "J\u016AS\u0172 ATLYGINIMAS",
	"home_btn_freedom": "LAISV\u0116",
	"home_btn_human_rights": "\u017DMOGAUS TEIS\u0116S",
	"home_btn_equality": "LYGYB\u0116",
	"home_btn_property_rights": "NUOSAVYB\u0116S TEIS\u0116S",
	"home_btn_housing": "B\u016ASTAS",
	"home_btn_business": "VERSLAS",
	"home_btn_crowdfunding": "SUTELKTINIS FINANSAVIMAS",
	"home_btn_energy": "ENERGIJA",
	"home_btn_environment": "APLINKA",
	"home_btn_food": "MAISTAS",
	"home_btn_art": "MENAS",
	"home_btn_politics": "POLITIKA",
	"home_btn_war": "KARAS",
	"home_btn_coding": "PROGRAMAVIMAS",
	"home_btn_networks": "TINKLAI",
	"home_btn_payments": "MOK\u0116JIMAI",
	"home_btn_self_custody": "SAVARANKI\u0160KA SAUGYKLA",
	"home_btn_you": "J\u016AS",
	"home_section_bitcoin_is": "BITCOIN YRA",
	"home_section_bitcoin_and": "BITCOIN IR",
	"home_link_type_website": "SVETAIN\u0116",
	"home_link_type_video": "VAIZDO \u012ERA\u0160AS",
	"home_link_type_article": "STRAIPSNIS",
	"home_link_type_podcast": "TINKLALAID\u0116",
	"home_link_type_business_kit": "VERSLO RINKINYS",
	"home_link_type_data": "DUOMENYS",
	"home_link_type_research": "TYRIMAS",
	"home_link_type_story": "ISTORIJA",
	"home_link_type_book_excerpt": "KNYGOS I\u0160TRAUKA",
	"home_link_type_street_art": "GATV\u0116S MENAS",
	"home_link_type_outreach": "SKLEIDIMAS",
	"home_link_type_campaign": "KAMPANIJA",
	"home_link_type_software": "PROGRAMIN\u0116 \u012ERANGA",
	"home_link_type_hardware": "APARAT\u016AR\u0116 \u012ERANGA",
	"home_link_type_guide": "VADOVAS",
	"home_link_type_email": "EL. PA\u0160TAS",
	"home_link_title_inflation": "Bitcoin neturi infliacijos",
	"home_link_title_bank_runs": "Bitcoin neturi bank\u0173 panik\u0173",
	"home_link_title_gold": "Bitcoin prie\u0161 auks\u0105",
	"home_link_title_crypto": "Bitcoin prie\u0161 kriptovaliutas",
	"home_link_title_cash": "Bitcoin prie\u0161 grynuosius",
	"home_link_title_bonds": "Bitcoin prie\u0161 obligacijas",
	"home_link_title_cbdc": "Bitcoin prie\u0161 CBDC",
	"home_link_title_your_salary_1": "Su\u017Einokite, kiek turi padid\u0117ti j\u016Bs\u0173 atlyginimas, kad neatsilikt\u0173 nuo infliacijos.",
	"home_link_title_freedom_1": "Kod\u0117l Bitcoin svarbus laisvei",
	"home_link_title_freedom_2": "Bitcoin si\u016Blo laisv\u0119 nuo politin\u0117s represijos",
	"home_link_title_human_rights_1": "Kaip Bitcoin u\u017Etikrina \u017Emogaus teises",
	"home_link_title_human_rights_2": "Tylioji Bitcoin revoliucija Afrikoje",
	"home_link_title_human_rights_3": "Bitcoin saugo \u017Emogaus teises visame pasaulyje",
	"home_link_title_equality_1": "Bitcoin ne\u0161a vilt\u012F ir galimybes Piet\u0173 Afrikos gyventojams",
	"home_link_title_equality_2": "Kaip Bitcoin gali b\u016Bti l\u016B\u017Eio ta\u0161kas juodaodiams amerikiečiams",
	"home_link_title_property_rights_1": "Bitcoin yra tobula nuosavyb\u0117s forma",
	"home_link_title_property_rights_2": "Bitcoin prie\u0161 nekilnojam\u0105j\u012F turt\u0105",
	"home_link_title_housing_1": "Kaip Bitcoin v\u0117l padarys b\u016Bst\u0105 prieinam\u0105",
	"home_link_title_business_3": "Bitcoin prie\u0161 akcijas",
	"home_link_title_business_1": "Su\u017Einokite, kod\u0117l Bitcoin naudingas verslui",
	"home_link_title_business_2": "Pad\u0117kite vietiniam verslui priimti Bitcoin",
	"home_link_title_crowdfunding_1": "Kaip Bitcoin \u012Fgalino did\u017Eiausius Nigerijos protestus per kart\u0105",
	"home_link_title_crowdfunding_2": "Kanados vilkik\u0173 vairuotoj\u0173 protestas renka pinigus Bitcoin, kai GoFundMe blokuoja aukas",
	"home_link_title_crowdfunding_3": "Geyser = sutelktinis finansavimas su Bitcoin",
	"home_link_title_energy_1": "Kaip Bitcoin stabilizuoja Teksaso elektros tinkl\u0105",
	"home_link_title_energy_2": "Kod\u0117l Bitcoin naudoja energij\u0105?",
	"home_link_title_energy_3": "Bitcoin energijos naudojimas n\u0117ra problema. \u0160t\u0105i kod\u0117l.",
	"home_link_title_energy_4": "Bitcoin kasimas stabilizuoja energijos tinklus per paklausos atsakym\u0105",
	"home_link_title_energy_5": "Bitcoin kasyklininkai atne\u0161a hidroenergij\u0105 kaimo Afrikos bendruomen\u0117ms",
	"home_link_title_energy_6": "Kaip Bitcoin skatina atnaujinam\u0105j\u0105 energij\u0105",
	"home_link_title_environment_1": "Kaip Bitcoin kasimas ma\u017Eina pasaulines metano emisijas",
	"home_link_title_environment_2": "Kaip Bitcoin kasimas i\u0161gelb\u0117jo nacionalin\u012F park\u0105",
	"home_link_title_environment_3": "Bitcoin yra \u017Ealiausia industrija \u017Dem\u0117je!",
	"home_link_title_environment_4": "Bitcoin kasimas neleid\u017Eia deginamoms gamtin\u0117ms dujoms ter\u0161ti atmosfer\u0105",
	"home_link_title_food_1": "Kaip infliacija veikia maisto kainas",
	"home_link_title_food_2": "Kaip fiat pinigai kenkia maistui, \u016Bkiams ir \u017Dem\u0117s dirvai",
	"home_link_title_fine_art": "Bitcoin prie\u0161 dail\u0117s k\u016Brinius",
	"home_link_title_art_1": "Prisijunkite prie m\u016Bs\u0173 Bitcoin lipduk\u0173 iniciatyvos",
	"home_link_title_art_2": "I\u0161si\u0173skite Bitcoin atviruk\u0105 k\u0105 nors pa\u017E\u012Fstamam",
	"home_link_title_art_3": "Atsispausdinkite ir i\u0161kabinkite Bitcoin skrajutes",
	"home_link_title_politics_1": "Bitcoin yra politinis paradoksas",
	"home_link_title_politics_2": "Galite balsuoti u\u017E geresnius pinigus",
	"home_link_title_war_1": "Kaip Bitcoin gal\u0117t\u0173 u\u017Ebaigti nesibaigian\u010Dius karus",
	"home_link_title_war_2": "Bitcoin ir veteranai: nat\u016Bralus sutapimas",
	"home_link_title_war_3": "Kaip Bitcoin padeda civiliams pab\u0117gti nuo karo Sudane",
	"home_link_title_coding_1": "Interaktyvus vadov\u0117lis apie technin\u0119 Bitcoin pus\u0119",
	"home_link_title_coding_2": "bitcoinSwitch: pritaikykite bet kur\u012F \u012Frengin\u012F priimti Bitcoin",
	"home_link_title_coding_3": "Programuokite per Bitcoin paslaptis",
	"home_link_title_networks_1": "Gyvas Bitcoin tinklo vaizdas",
	"home_link_title_networks_2": "Bitcoin prie\u0161 bankus",
	"home_link_title_payments_1": "Bitcoin prie\u0161 Visa",
	"home_link_title_payments_2": "Pa\u017Evelgimas \u012F Lightning tinkl\u0105 (momentiniai Bitcoin mok\u0117jimai)",
	"home_link_title_payments_3": "El Salvadoro Bitcoin pinigin\u0117 gal\u0117t\u0173 sutaupyti salvadoriečiams 400 mln. $ per metus pervedim\u0173 mokes\u010Di\u0173",
	"home_link_title_payments_4": "Gaukite savo Lightning adres\u0105 momentiniams Bitcoin mok\u0117jimams gauti",
	"home_link_title_self_custody_1": "Kaip saugiai saugoti savo Bitcoin",
	"home_link_title_self_custody_2": "6 prie\u017Eastys i\u0161imti Bitcoin i\u0161 bir\u017E\u0173",
	"home_link_title_self_custody_3": "Auksas, Bitcoin ir savaranki\u0161ka saugykla",
	"home_link_title_get_started_1": "Su\u017Einokite Bitcoin pagrindus",
	"home_link_title_get_started_2": "Gaukite savo pirm\u0105j\u0105 Bitcoin pinigin\u0119",
	"home_link_title_get_started_3": "Kaip pirkti Bitcoin",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "Sud\u0117tin\u0117s infliacijos skaičiuokl\u0117",
	"home_link_author_time_magazine": "TIME Magazine",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
});

console.log('\nDone! Index file created for Lithuanian (lt).');
