/**
 * Creates Lithuanian (lt) translation files for remaining content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'lt';
const today = '2026-04-04';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "Bitcoin neturi bank\u0173 panik\u0173",
	"bank_runs_header": "BITCOIN NETURI BANK\u0172 PANIK\u0172",
	"bank_runs_header_2": "BET J\u016AS\u0172 BANKAS GALI TUR\u0116TI",
	"bank_runs_what": "KAS YRA BANK\u0172 PANIKA?",
	"bank_runs_what_content_1": "Bank\u0173 panika \u012Fvyksta, kai per daug \u017Emoni\u0173 vienu metu bando i\u0161siimti savo pinigus i\u0161 banko.",
	"bank_runs_what_content_2": "Jei bankai neturi pakankamai pinig\u0173 i\u0161mok\u0117jimams padengti, jie gali visi\u0161kai \u017Elugti.",
	"bank_runs_how": "KAIP ATSIRANDA BANK\u0172 PANIKOS?",
	"bank_runs_how_content_1": "M\u016Bs\u0173 bankin\u0117 sistema yra \u201Edalinio rezervo\u201C, tai rei\u0161kia, kad bankai ne tik laiko j\u016Bs\u0173 pinigus seife ir laukia, kol juos i\u0161leisite ar i\u0161siimsite.",
	"bank_runs_how_content_2": "Vietoj to, j\u016Bs\u0173 bankas paima j\u016Bs\u0173 pinigus ir juos skolina arba investuoja. Tai gali u\u017Erakinti j\u016Bs\u0173 pinigus ilgam laikui, nors bankas \u017Eada jums galimyb\u0119 bet kada i\u0161siimti pinigus.",
	"bank_runs_how_content_3": "Tai kas nutinka, jei bandote i\u0161siimti savo pinigus, kai bankas juos jau paskolino ar investavo?",
	"bank_runs_how_content_4": "Tai n\u0117ra problema, jei j\u016Bs esate vienintelis, bandantis i\u0161siimti. Bankas tiesiog paims kito \u017Emogaus pinigus ir duos jums. Bet kas nutinka, kai per daug \u017Emoni\u0173 bando i\u0161siimti vienu metu?",
	"bank_runs_how_content_5": "Daugelis JAV \u017Emoni\u0173 tai su\u017Einojo, kai 2023 m. kovo m\u0117n. \u012Fvyko Silicon Valley Bank panika.",
	"bank_runs_how_content_6": "Bankas investavo savo klient\u0173 pinigus \u012F vyriausyb\u0117s obligacijas, kurios buvo u\u017Erakintos iki 30 met\u0173. Dar blogiau, t\u0173 obligacij\u0173 vert\u0117 neseniai smarkiai krito, tod\u0117l Silicon Valley Bank negal\u0117jo tiesiog parduoti obligacij\u0173 ir gr\u0105\u017Einti ind\u0117linink\u0173 pinig\u0173. Jie buvo nemok\u016Bs.",
	"bank_runs_how_content_7": "Kai daugiau \u017Emoni\u0173 apie tai su\u017Einojo, problema tik pagilė. Daugiau i\u0161\u0117mimo prašymų buvo pateikta, bet daugelis nebuvo \u012Fvykdyti. T\u016Bkstančiai \u012Fmoni\u0173 suprato, kad negal\u0117s sumok\u0117ti atlyginim\u0173 darbuotojams d\u0117l banko \u017Elugimo.",
	"bank_runs_how_content_8": "FDIC \u012Fsikišo ir sutar\u0117 padengti ind\u0117lininkams. Problema i\u0161spr\u0119sta? Ne visai...",
	"bank_runs_fdic": "AR FDIC DRAUDIMAS SAUGO MANO PINIGUS?",
	"bank_runs_fdic_content_1": "FDIC draudimas skirtas apsaugoti banko ind\u0117lininkus banko \u017Elugimo atveju. Ind\u0117liai draud\u017Eiami iki 250 000 $ vienam ind\u0117lininkui. Skamba puikiai, tiesa?",
	"bank_runs_fdic_content_2": "Ne visai. Jei bankas \u017Elunga, i\u0161 kur FDIC gauna pinig\u0173? Jie turi draudimo fond\u0105 su 125 mlrd. doleri\u0173.",
	"bank_runs_fdic_content_3": "Tai skamba kaip daug pinig\u0173, kol nepalyginate su draud\u017Eiam\u0173 ind\u0117li\u0173 suma: beveik 10 trilijon\u0173 arba 10 000 mlrd. doleri\u0173.",
	"bank_runs_fdic_content_4": "FDIC net savo svetain\u0117je rodo, kad j\u0173 draudimo fonde u\u017Etenka pinig\u0173 padengti tik šiek tiek daugiau nei 1% ind\u0117li\u0173.",
	"bank_runs_fdic_content_5": "Banko \u017Elugimo atveju, vir\u0161ijan\u010Diu FDIC draudimo fond\u0105, tik\u0117tina (bet negarantuota), kad JAV vyriausyb\u0117 atspausdint\u0173 pinig\u0173 ind\u0117lininkams padengti.",
	"bank_runs_fdic_content_6": "Bet pinig\u0173 spausdinimas sukelia infliacij\u0105, tod\u0117l tai n\u0117ra puikus sprendimas.",
	"bank_runs_safe": "AR YRA BANK\u0172, KURIE NENAUDOJA DALINIO REZERVO?",
	"bank_runs_safe_content_1": "Kai kurie bankai band\u0117 b\u016Bti \u201Esaugiais bankais\u201C, kurie neskolina ir neinvestuoja ind\u0117linink\u0173 l\u0117\u0161\u0173.",
	"bank_runs_safe_content_2": "Nors \u0161ie saug\u016Bs bankai netur\u0117t\u0173 jokios bank\u0173 panikos rizikos, j\u0173 paraiškas atmet\u0117 Federalinis rezervas. Tai rei\u0161kia, kad jie negali teis\u0117tai veikti kaip bankai.",
	"bank_runs_safe_content_3": "Kadangi jiems u\u017Eblokuota veikla, \u0161iandien n\u0117ra banko, kuris nenaudot\u0173 dalinio rezervo.",
	"bank_runs_safe_content_4": "Laimei, yra b\u016Bdas atsisak yti dalinio rezervo sistemos b\u016Bnant savo paties banku. Ne, nekalbame apie grynuosius po čiu\u017Einiu.",
	"bank_runs_safe_content_5": "Taupymas grynaisiais vis tiek pažeid\u017Eiamas infliacijos.",
	"bank_runs_safe_content_6": "Kalbame apie Bitcoin: nauj\u0105 finansin\u0119 sistem\u0105, leid\u017Eian\u010Di\u0105 jums b\u016Bti savo paties banku.",
	"bank_runs_protect": "AR BITCOIN GALI APSAUGOTI MANE NUO BANK\u0172 PANIK\u0172?",
	"bank_runs_protect_content_1": "Taip, Bitcoin yra visi\u0161ko rezervo finansin\u0117 sistema.",
	"bank_runs_protect_content_2": "Bank\u0173 panikos Bitcoin sistemoje ne\u012Fmanomos, jei i\u0161siiimate savo Bitcoin \u012F savo pinigin\u0119. Nepalikite bitcoin bir\u017Eoje ar apvalkale kaip Bitcoin ETF.",
	"bank_runs_protect_content_3": "Per\u017Ei\u016Br\u0117kite m\u016Bs\u0173 papras t\u0105 Bitcoin pinigin\u0117s vadov\u0105, kad su\u017Einotum\u0117te, kaip i\u0161siimti \u012F savo pinigin\u0119.",
	"bank_runs_protect_content_4": "Su Bitcoin pagaliau galite kontroliuoti savo pinigus."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Bitcoin piniginių vadovas",
	"wallets_description": "Yra daug skirtingų Bitcoin piniginių, kurios svarbiais būdais skiriasi. Galite nustatyti, ar piniginė tinka jums, užduodami šiuos paprastus klausimus.",
	"wallets_header": "KAIP SAUGIAI SAUGOTI SAVO BITCOIN",
	"wallets_s1_c1": "Bitcoin piniginės yra suderinamos, todėl galite siųsti Bitcoin bet kam, nepriklausomai nuo to, kokią piniginę jie naudoja.",
	"wallets_s1_c2": "Yra daug skirtingų Bitcoin piniginių, kurios svarbiais būdais skiriasi. Galite nustatyti, ar piniginė tinka jums, užduodami šiuos paprastus klausimus:",
	"wallets_question_1": "AR TAI SAVARANKIŠKOS SAUGYKLOS PINIGINĖ?",
	"wallets_s2_c1": "Viena iš Bitcoin inovacijų yra galimybė jį saugoti nepasikliaujant saugotoju, pavyzdžiui, banku.",
	"wallets_s2_c2": "Jei laikote bitcoin biržoje ar ETF, prarandate bitcoin laisvės privalumus.",
	"wallets_s2_c3": "Savarankiškos saugyklos piniginės atleidžia visą Bitcoin galią: laisvės pinigus.",
	"wallets_s2_c4": "Su savarankiškos saugyklos pinigine tik jūs galite išleisti ar pervesti savo pinigus. Niekas negali sustabdyti jūsų nuo pinigų siuntimo ar gavimo.",
	"wallets_s2_c5": "Savarankiškos saugyklos piniginės taip pat vadinamos ne globėjiškomis piniginėmis.",
	"wallets_s3_c1": "Globėjiškos piniginės yra piniginės, kur jūs nekontroliuojate savo pinigų.",
	"wallets_s3_c2": "Šios piniginės labiau panašios į bankų sistemą, kur turite pasitikėti trečiąja šalimi dėl prieigos prie savo pinigų. Jei jūsų Bitcoin yra biržoje, naudojate globėjišką piniginę.",
	"wallets_s3_c3": "Jei pirkote Bitcoin ETF, naudojate globėjišką piniginę, kuri neleidžia išsiimti į savarankišką saugyklą.",
	"wallets_s3_c4": "Globėjiškos piniginės gali atrodyti patogios, bet globėjas turi techninę galimybę pavogti visus naudotojų pinigus bet kuriuo metu.",
	"wallets_s3_c5": "Ne jūsų raktai, ne jūsų monetos!",
	"wallets_question_2": "AR JI KARŠTA AR ŠALTA?",
	"wallets_s4_c1": "Šaltos piniginės saugo jūsų Bitcoin raktus būdu, kuris niekada jų neatskleidžia internetui.",
	"wallets_s4_c2": "Tai žymiai apriboja atakos vektorius, kuriuos vagis galėtų naudoti bandydamas pavogti jūsų Bitcoin, ir geriausiai tinka didelėms Bitcoin sumoms, kurių nereikia dažnai pervesti.",
	"wallets_s4_c3": "Šaltą piniginę galite laikyti ilgalaikiu taupomąja sąskaita, dar vadinama šalta saugykla.",
	"wallets_s5_c1": "Karštos piniginės saugo jūsų Bitcoin raktus įrenginyje, kuris prijungtas prie interneto, pvz., jūsų telefone.",
	"wallets_s5_c2": "Karštos piniginės paprastai laikomos saugiomis, bet gali turėti daugiau saugumo pažeidžiamumų nei šaltos piniginės.",
	"wallets_s5_c3": "Karštą piniginę galite laikyti kaip fizinę piniginę. Nelaikytumėte visų santaupų piniginėje, bet laikytumėte šiek tiek kasdienių išlaidų.",
	"wallets_s5_c4": "Karštos piniginės leidžia daug lengviau išleisti Bitcoin neištraukiant visų santaupų iš šaltos saugyklos.",
	"wallets_question_3": "KAIP PADARYTI ATSARGINĘ ATKŪRIMO FRAZĖS KOPIJĄ?",
	"wallets_s6_c1": "Kai nustatote savo Bitcoin piniginę, jūsų įrenginys sugeneruos atkūrimo frazę. Ši atkūrimo frazė (dar vadinama pradinė frazė) turi 12 ar 24 žodžius.",
	"wallets_s6_c2": "Jei kada nors prarasite prieigą prie savo piniginės ar jūsų įrenginys nustos veikti, galite įvesti šią atkūrimo frazę į naują piniginę ir atgauti prieigą prie savo Bitcoin.",
	"wallets_s6_c3": "Dauguma piniginių prideda popieriaus lapą atkūrimo frazei užrašyti, bet daugelis žmonių pageidauja šią frazę atsarginėje kopijoje laikyti ant plieno. Tai žymiai sumažina tikimybę prarasti atkūrimo frazę gamtos nelaimės, pvz., gaisro ar potvynio, atveju.",
	"wallets_s6_c4": "Jameson Lopp išbandė 70 plieninių atsarginių kopijų rinkinių, kad padėtų jums pasirinkti tinkamiausią.",
	"wallets_s6_c5": "Peržiūrėkite Jameson metalinio Bitcoin atsarginės kopijos vadovą čia.",
	"wallets_s6_c6": "Arba tęskite slinkimą, kad pamatytumėte Bitcoin piniginių variantus.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "Ieškote mūsų Lightning piniginių vadovo?",
	"wallets_starter_wallet": "Puiki pradinė piniginė",
	"wallets_mobile_app": "Mobilioji programėlė",
	"wallets_2fa_support": "2FA palaikymas",
	"wallets_air_gap_mode": "Oro tarpo režimas",
	"wallets_air_gap_camera": "Oro tarpo režimas + kamera",
	"wallets_bitcoin_only": "Tik Bitcoin",
	"wallets_security_features": "Daug saugumo funkcijų",
	"wallets_free": "100% nemokama",
	"wallets_coldcard_mk5_costs": "Kainuoja 189 $",
	"wallets_coldcard_q_costs": "Kainuoja 289 $",
	"wallets_blockstream_jade_costs": "Kainuoja 79 $",
	"wallets_foundation_passport_costs": "Kainuoja 199 $",
	"wallets_seedsigner_costs": "Dalių kaina 50 $",
	"wallets_very_affordable": "Labai prieinama",
	"wallets_pair_with_phone": "Suporuokite su telefonu",
	"wallets_battery": "Įkraunamas akumuliatorius",
	"wallets_build_your_own": "Susirinkite patys",
	"wallets_qwerty_keyboard": "Pilna QWERTY klaviatūra",
	"wallets_qr_scanner": "QR kodo skaitytuvas"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "Kaip pirkti Bitcoin \u2014 \u017Eingsnis po \u017Eingsnio vadovas",
	"buy_header": "KAIP PIRKTI BITCOIN",
	"buy_intro_c1": "Pirm\u0105 kart\u0105 pirkti Bitcoin gali atrodyti sud\u0117tinga, bet i\u0161 tikr\u0173j\u0173 tai gana paprasta, kai suskaidote \u012F \u017Eingsnius.",
	"buy_intro_c2": "\u0160is vadovas pad\u0117s jums saugiai nusipirkti Bitcoin ir saugoti j\u012F savo pinigin\u0117je.",
	"buy_step_1_header": "1 \u017DINGSNIS: PASIRINKITE SAVO \u0160AL\u012E",
	"buy_step_1_description": "Skirtingose \u0161alyse yra skirtingos Bitcoin pirkimo galimyb\u0117s. Pasirinkite savo \u0161al\u012F, kad pamatytum\u0117te geriausius variantus.",
	"buy_search_countries": "Ie\u0161kokite savo \u0161alies",
	"buy_country_united_states": "Jungtin\u0117s Valstijos",
	"buy_country_australia": "Australija",
	"buy_country_austria": "Austrija",
	"buy_country_belgium": "Belgija",
	"buy_country_brazil": "Brazilija",
	"buy_country_canada": "Kanada",
	"buy_country_france": "Pranc\u016Bzija",
	"buy_country_germany": "Vokietija",
	"buy_country_ireland": "Airija",
	"buy_country_italy": "Italija",
	"buy_country_netherlands": "Nyderlandai",
	"buy_country_new_zealand": "Naujoji Zelandija",
	"buy_country_spain": "Ispanija",
	"buy_country_united_kingdom": "Jungtin\u0117 Karalyst\u0117",
	"buy_country_argentina": "Argentina",
	"buy_country_chile": "\u010Cil\u0117",
	"buy_country_colombia": "Kolumbija",
	"buy_country_costa_rica": "Kosta Rika",
	"buy_country_czech_republic": "\u010Cekija",
	"buy_country_denmark": "Danija",
	"buy_country_el_salvador": "Salvadoras",
	"buy_country_estonia": "Estija",
	"buy_country_finland": "Suomija",
	"buy_country_greece": "Graikija",
	"buy_country_guatemala": "Gvatemala",
	"buy_country_hong_kong": "Honkongas",
	"buy_country_hungary": "Vengrija",
	"buy_country_iceland": "Islandija",
	"buy_country_india": "Indija",
	"buy_country_israel": "Izraelis",
	"buy_country_japan": "Japonija",
	"buy_country_latvia": "Latvija",
	"buy_country_lithuania": "Lietuva",
	"buy_country_luxembourg": "Liuksemburgas",
	"buy_country_malta": "Malta",
	"buy_country_mexico": "Meksika",
	"buy_country_norway": "Norvegija",
	"buy_country_panama": "Panama",
	"buy_country_poland": "Lenkija",
	"buy_country_portugal": "Portugalija",
	"buy_country_romania": "Rumunija",
	"buy_country_singapore": "Singap\u016Bras",
	"buy_country_slovakia": "Slovakija",
	"buy_country_slovenia": "Slov\u0117nija",
	"buy_country_south_africa": "Piet\u0173 Afrika",
	"buy_country_south_korea": "Piet\u0173 Kor\u0117ja",
	"buy_country_sweden": "\u0160vedija",
	"buy_country_switzerland": "\u0160veicarija",
	"buy_country_thailand": "Tailandas",
	"buy_country_turkey": "Turkija",
	"buy_country_ukraine": "Ukraina",
	"buy_country_uruguay": "Urugvajus",
	"buy_step_2_header": "2 \u017DINGSNIS: PASIRINKITE MOK\u0116JIMO B\u016AD\u0104",
	"buy_step_2_description": "Yra du pagrindiniai b\u016Bdai pirkti Bitcoin: banko pavedim u arba grynaisiais. Kiekvienas turi skirting\u0173 privalum\u0173.",
	"buy_method_bank_transfer": "BANKO PAVEDIMAS",
	"buy_method_bank_fast": "Greitas ir paprastas",
	"buy_method_bank_less_private": "Ma\u017Eiau privatu",
	"buy_method_bank_description": "Banko pavedimai yra da\u017Eniausias b\u016Bdas pirkti Bitcoin. Jie greiti, patog\u016Bs ir paprastai turi ma\u017Eesnius mokes\u010Dius.",
	"buy_method_choose_bank": "Pasirinkti banko pavedim\u0105",
	"buy_method_cash": "GRYNIEJI",
	"buy_method_cash_private": "Privatesnis",
	"buy_method_cash_limited": "Riboti variantai",
	"buy_method_cash_description": "Pirkimas grynaisiais si\u016Blo daugiau privatumo, bet turi ma\u017Eiau variant\u0173 ir gali reikalauti asmeninio susitikimo ar Bitcoin bankomato.",
	"buy_method_choose_cash": "Pasirinkti grynuosius",
	"buy_step_3_header": "3 \u017DINGSNIS: PIRKIMO VARIANTAI",
	"buy_step_3_description": "\u0160tai geriausi Bitcoin pirkimo variantai j\u016Bs\u0173 \u0161aliai ir mok\u0117jimo b\u016Bdui:",
	"buy_platform_recommended": "REKOMENDUOJAMA",
	"buy_platform_strike_description": "Strike yra greičiausias ir paprasčiausias b\u016Bdas pirkti Bitcoin su ma\u017Eais mokes\u010Diais ir momentine Lightning tinklo parama.",
	"buy_platform_swan_description": "Swan Bitcoin specializuojasi tik Bitcoin paslaugose su doleri\u0173 kain\u0173 vidurkinimu ir \u0161vietimo resursais.",
	"buy_platform_river_description": "River si\u016Blo Bitcoin pirkim\u0105, kasinim\u0105 ir saugojimo paslaugas su d\u0117mesiu \u0161vietimui ir saugumui.",
	"buy_platform_coinsquare_description": "Coinsquare yra Kanados Bitcoin bir\u017Ea su stipriu reguliavimo laikymusi ir klient\u0173 aptarnavimu.",
	"buy_platform_kraken_description": "Kraken yra \u012Fsikurusi Bitcoin bir\u017Ea su pa\u017Eangiomis prekybos funkcijomis ir stipriu saugumu.",
	"buy_platform_atm_description": "Bitcoin bankomatai leid\u017Eia pirkti Bitcoin grynaisiais i\u0161 karto. Raskite artimiausią naudodami Coin ATM Radar.",
	"buy_platform_bisq_description": "Bisq yra decentralizuota tarpusavio bir\u017Ea, leid\u017Eianti privaatiai prekiauti Bitcoin be KYC.",
	"buy_platform_feature_instant": "Momentiniai pirkimai",
	"buy_platform_feature_low_fees": "Ma\u017Ei mokes\u010Diai",
	"buy_platform_feature_lightning": "Lightning tinklas",
	"buy_platform_feature_dca": "Doleri\u0173 kain\u0173 vidurkinimas",
	"buy_platform_feature_education": "\u0160vietimo resursai",
	"buy_platform_feature_withdrawal": "Lengvas i\u0161\u0117mimas",
	"buy_platform_feature_mining": "Bitcoin kasimas",
	"buy_platform_feature_custody": "Saugojimo paslaugos",
	"buy_platform_feature_canadian": "Orientuota \u012F Kanad\u0105",
	"buy_platform_feature_regulated": "Reguliuojama bir\u017Ea",
	"buy_platform_feature_support": "Klient\u0173 aptarnavimas",
	"buy_platform_feature_established": "\u012Esikurusi platforma",
	"buy_platform_feature_security": "Stiprus saugumas",
	"buy_platform_feature_advanced": "Pa\u017Eangios funkcijos",
	"buy_platform_feature_cash": "Pirkimas grynaisiais",
	"buy_platform_feature_anonymous": "Anonimiškesnis",
	"buy_platform_feature_p2p": "Tarpusavio",
	"buy_platform_feature_private": "Privati prekyba",
	"buy_platform_feature_decentralized": "Decentralizuota",
	"buy_platform_relai_description": "Relai yra \u0160veicarijos Bitcoin program\u0117l\u0117 su savaranki\u0161kos saugyklos pinigine, automatinio investavimo funkcijomis ir ma\u017Eais mokes\u010Diais Europos naudotojams.",
	"buy_platform_feature_bitcoin_only": "Tik Bitcoin",
	"buy_platform_feature_self_custody": "Savaranki\u0161kos saugyklos pinigin\u0117",
	"buy_platform_feature_auto_invest": "Automatinio investavimo planai",
	"buy_platform_feature_european": "Orientuota \u012F Europ\u0105",
	"buy_step_4_header": "4 \u017DINGSNIS: SAUGIAI SAUGOKITE SAVO BITCOIN",
	"buy_step_4_c1": "Nusipirk\u0119 Bitcoin, svarbiausias \u017Eingsnis yra j\u012F perkelti \u012F savo pinigin\u0119, kur kontroliuojate privačius raktus.",
	"buy_step_4_c2": "Bitcoin palikimas bir\u017Eoje yra rizikingas, nes j\u016Bs i\u0161 tikr\u0173j\u0173 neturite Bitcoin — bir\u017Ea j\u012F turi.",
	"buy_step_4_c3": "Kai kontroliuojate savo privačius raktus, turite tikr\u0105 Bitcoin nuosavyb\u0119 ir niekas negali j\u016Bs\u0173 jo atimti.",
	"buy_step_4_c4": "Su\u017Einokite, kaip pasirinkti tinkam\u0105 Bitcoin pinigin\u0119 savo poreikiams:",
	"buy_cta_wallets": "Per\u017Ei\u016Br\u0117ti m\u016Bs\u0173 Bitcoin pinigin\u0117s vadov\u0105"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Bitcoin Lightning piniginių vadovas",
	"lightning_description": "Lightning piniginės leidžia siųsti Bitcoin greitai ir pigiai, kartu išlaikant asmeninį suverenitetą.",
	"lightning_header": "LIGHTNING PINIGINIŲ VADOVAS",
	"lightning_s1_c1": "Lightning leidžia siųsti Bitcoin mokėjimus greitai ir pigiai.",
	"lightning_s1_c2": "Svarbu žinoti, kad Lightning naudojimas turi kompromisų. Mainais už greitesnius, pigesnius Bitcoin mokėjimus dažnai prarandate šiek tiek saugumo.",
	"lightning_s1_c3": "Apskritai, Lightning turėtų būti naudojamas tik su mažomis bitcoin sumomis. Dideles bitcoin sumas visada turėtumėte saugoti aparatūrinėje piniginėje.",
	"lightning_s1_c4": "Peržiūrėkite mūsų aparatūrinių piniginių vadovą daugiau informacijos.",
	"lightning_s1_c5": "Ne visos Lightning piniginės yra vienodos. Galite nustatyti, kuri piniginė turi tinkamą kompromisų balansą jums, užduodami vieną paprastą klausimą:",
	"lightning_question_1": "KOKS KOMPROMISŲ BALANSAS MAN TINKAMAS?",
	"lightning_s2_c1": "Viena iš Bitcoin inovacijų yra galimybė jį saugoti nepasikliaujant saugotoju, pavyzdžiui, banku. Savarankiškos saugyklos piniginės atleidžia visą Bitcoin galią.",
	"lightning_s2_c2": "Su savarankiškos saugyklos pinigine tik jūs galite išleisti ar pervesti savo pinigus. Niekas negali jūsų sustabdyti, cenzūruoti ar pavogti iš jūsų. Tai dar vadinamos ne globėjiškomis piniginėmis.",
	"lightning_s2_c3": "Suvereniausias būdas naudoti Lightning yra paleisti savo mazgą.",
	"lightning_s2_c4": "Šis vadovas orientuotas į paprastas Lightning pinigines, kurioms nereikia savo mazgo.",
	"lightning_s2_c5": "Svarbu žinoti, kad net naudojant ne globėjišką Lightning piniginę, vis tiek pasitikite piniginės kūrėju, kad jis neišleis kenkėjiško programėlės atnaujinimo ir nepavogs jūsų lėšų.",
	"lightning_s3_c1": "Globėjiškos piniginės yra piniginės, kur jūs nekontroliuojate savo pinigų.",
	"lightning_s3_c2": "Šios piniginės labiau panašios į bankų sistemą, kur turite pasitikėti trečiąja šalimi dėl prieigos prie savo pinigų. Jei jūsų Bitcoin yra biržoje, naudojate globėjišką piniginę.",
	"lightning_s3_c3": "Globėjiškos piniginės gali atrodyti patogios, bet globėjas turi techninę galimybę pavogti visus naudotojų pinigus bet kuriuo metu.",
	"lightning_s3_c4": "Kai kurie žmonės pageidauja globėjiškų Lightning piniginių mažoms bitcoin sumoms dėl jų naudojimo paprastumo. Tiesiog atsiminkite: ne jūsų raktai, ne jūsų monetos!",
	"lightning_question_2": "PASIRINKITE SAVO PINIGINĘ",
	"lightning_s4_c1": "Turint visa tai omenyje, dabar galite pasirinkti Lightning piniginę su tinkamu kompromisų balansu jums.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "Daug funkcijų",
	"lightning_mobile_app": "Mobilioji programėlė",
	"lightning_free": "100% nemokama",
	"lightning_merchants": "Puikiai tinka prekiautojams",
	"lightning_starter": "Puiki pradinė piniginė",
	"lightning_browser": "Naršyklės pagrindu",
	"lightning_custodial": "Pilnai globėjiška piniginė",
	"lightning_cta_hardware": "Ieškote mūsų Bitcoin aparatūrinių piniginių vadovo?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "Nemokami Bitcoin lipdukai iš bitcoin.rocks",
	"stickers_description": "Priklijuokite Bitcoin lipduką viešoje vietoje, kad įtrauktumėte aplinkinius.",
	"stickers_header": "NEMOKAMI BITCOIN LIPDUKAI",
	"stickers_choose_header": "PASIRINKITE SAVO LIPDUKŲ PAKĄ",
	"stickers_choose_c1": "Mūsų misija — padėti jums įtraukti daugiau žmonių į Bitcoin klijuojant lipdukus viešose vietose. Visuose mūsų lipdukuose yra QR kodai, nukreipiantys į šviečiamąsias puslapius apie",
	"stickers_choose_c2": "Bitcoin",
	"stickers_choose_c3": "infliaciją",
	"stickers_choose_c4": "Pasirinkite savo lipdukų paką žemiau",
	"stickers_text_pack": "TEKSTO PAKA",
	"stickers_signs_pack": "ŽENKLŲ PAKA",
	"stickers_instructions_1": "Įveskite savo pašto adresą ir mes atsiųsime jums nemokamą Bitcoin lipdukų paką paštu! Jūsų lipdukai bus išsiųsti baltame voke.",
	"stickers_instructions_2": "Adreso duomenys ištrinami išsiuntus nemokamus lipdukus.",
	"stickers_share_header": "PASIDALINKITE SAVO LIPDUKŲ VIETOMIS",
	"stickers_share_c1": "Pasidalinkite savo lipdukų vietomis su mumis Nostr platformoje ir pažiūrėkite, kur kiti klijuoja savo lipdukus.",
	"stickers_btn_share_on_nostr": "DALINTIS NOSTR",
	"stickers_btn_what_is_nostr": "KAS YRA NOSTR?",
	"stickers_flyers_link_before": "Tuo pačiu metu atsispausdinkite ir iškabinkite savo ",
	"stickers_flyers_link_text": "Bitcoin skrajutes",
	"stickers_flyers_link_after": ", kad įtrauktumėte dar daugiau žmonių.",
	"stickers_country_global_print": "Globaliai — atsispausdinti savo lipdukus",
	"stickers_country_global_order": "Globaliai — užsakyti didmenomis",
	"placeholder_name_optional": "Vardas (neprivaloma)",
	"placeholder_address_line_1": "Adreso 1 eilutė",
	"placeholder_address_line_2": "Adreso 2 eilutė (neprivaloma)",
	"placeholder_city": "Miestas",
	"placeholder_state": "Valstija",
	"placeholder_province": "Provincija",
	"placeholder_zip_code": "Pašto kodas",
	"placeholder_postal_code": "Pašto kodas",
	"placeholder_language": "Kalba",
	"placeholder_which_stickers": "Kuriuos lipdukus?",
	"placeholder_email_optional": "Įveskite el. paštą pranešimui gauti (neprivaloma)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "Nemokami Bitcoin atvirukai iš bitcoin.rocks",
	"postcards_description": "Gaukite nemokamą Bitcoin atvirukų paką ir pasidalinkite Bitcoin su kuo nors pažįstamu.",
	"postcards_header": "ATVIRUKŲ PROGRAMA UŽDARYTA",
	"postcards_program_closed_message": "Mūsų nemokamų Bitcoin atvirukų programa baigėsi. Dėkojame visiems, dalyvavusiems skleidžiant Bitcoin švietimą paštu!",
	"postcards_sticker_alternative_header": "VIETOJ TO GAUKITE NEMOKAMŲ BITCOIN LIPDUKŲ",
	"postcards_sticker_alternative_message": "Tęskite Bitcoin žinomumo skleidimą su mūsų nemokama lipdukų programa! Mūsų Bitcoin lipdukai puikiai tinka dalinimuisi viešose vietose ir turi QR kodus, nukreipiančius į šviečiamąjį turinį.",
	"postcards_sticker_cta": "GAUTI NEMOKAMŲ LIPDUKŲ",
	"postcards_step_2": "KAIP ATRODĖ ATVIRUKAI",
	"postcards_instructions_4": "Sukūrėme šiuos atvirukus, kad būtų lengviau supažindinti ką nors pažįstamą su Bitcoin! Tiesiog pridėkite adresą ir pašto ženklą ir įmeskite atviruką į pašto dėžutę.",
	"postcards_instructions_5": "Mūsų misija — paspartinti Bitcoin priėmimą. Galite padėti gaudami nemokamus lipdukus ir juos klijuodami viešose vietose!",
	"postcards_instructions_6": "Visi pažįstame kelis žmones, kuriems būtų naudinga sužinoti daugiau apie Bitcoin. Pasidalinkite Bitcoin lipdukais su jais šiandien!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "Padėkite mums išstatyti šiuos Bitcoin ženklus visoje Amerikoje!",
	"signs_title": "Nemokami Bitcoin ženklai iš bitcoin.rocks",
	"signs_choose_header": "AČIŪ, KAD PADĖJOTE MUMS IŠSTATYTI ŠIUOS BITCOIN ŽENKLUS VISOJE AMERIKOJE!",
	"signs_choose_c1": "Ženklai jau baigėsi! Mūsų misija — paspartinti Bitcoin priėmimą per švietimą.",
	"signs_choose_c2": "Daugelis jūsų padėjote išstatydami šiuos nemokamus Bitcoin ženklus viešose vietose. Visuose mūsų ženkluose yra QR kodai, nukreipiantys į šviečiamąjį puslapį apie",
	"signs_choose_c3": "infliaciją",
	"signs_choose_c4": "Dėl mūsų nuostabios bendruomenės pasiekėme tūkstančius žmonių ir padėjome jiems žengti pirmuosius žingsnius Bitcoin link.",
	"signs_share_header": "PASIDALINKITE SAVO ŽENKLO VIETOMIS",
	"signs_share_c1": "Pasidalinkite savo ženklo vietos nuotrauka su mumis Nostr platformoje ir pažiūrėkite, kur kiti stato savo ženklus.",
	"signs_btn_share_on_nostr": "DALINTIS NOSTR",
	"signs_btn_what_is_nostr": "KAS YRA NOSTR?",
	"signs_instructions_1": "Įveskite savo pašto adresą ir mes atsiųsime jums dėžę su 10 Bitcoin ženklų paštu!",
	"signs_instructions_2": "Adreso duomenys ištrinami išsiuntus nemokamus ženklus."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "Nemokamos Bitcoin skrajutės iš bitcoin.rocks",
	"flyers_description": "Atsispausdinkite Bitcoin skrajutę namuose ir iškabinkite viešoje vietoje, kad įtrauktumėte aplinkinius.",
	"flyers_header_1": "ATSISPAUSDINKITE IR IŠKABINKITE",
	"flyers_header_2": "BITCOIN SKRAJUTES",
	"flyers_intro_header": "KAIP ATSISPAUSDINTI IR IŠKABINTI ŠIAS BITCOIN SKRAJUTES",
	"flyers_intro_c1": "Mūsų misija — padėti jums įtraukti daugiau žmonių į Bitcoin iškabinant skrajutes viešose vietose. Šioje skrajutėje yra QR kodas, nukreipiantis į mūsų",
	"flyers_intro_c2": "šviečiamąją Bitcoin svetainę.",
	"flyers_intro_c3": "infliaciją",
	"flyers_intro_c4": "Atsispausdinkite šią skrajutę namuose arba spaustuvėje. Tada iškabinkite ją skelbimų lentose, telefono stulpuose ir kitose viešose vietose, kur žmonės galės ją pamatyti ir sužinoti apie Bitcoin.",
	"flyers_intro_c5": "Tuo pačiu metu užsakykite mūsų",
	"flyers_intro_c6": "nemokamų Bitcoin lipdukų",
	"flyers_intro_c7": "paką, kad įtrauktumėte dar daugiau žmonių.",
	"flyers_btn_download": "ATSISIŲSTI SKRAJUTĘ",
	"flyers_btn_print": "SPAUSDINTI SKRAJUTĘ",
	"flyers_share_header": "PASIDALINKITE SAVO SKRAJUČIŲ VIETOMIS",
	"flyers_share_c1": "Pasidalinkite savo skrajučių vietomis su mumis Nostr platformoje ir pažiūrėkite, kur kiti kabina savo skrajutes.",
	"flyers_btn_share_on_nostr": "DALINTIS NOSTR",
	"flyers_btn_what_is_nostr": "KAS YRA NOSTR?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "Prisijunkite ir padėkite skleisti Bitcoin",
	"get_involved_description": "Mūsų nemokami resursai palengvina Bitcoin priėmimo skleidimą.",
	"get_involved_header": "PRISIJUNKITE",
	"get_involved_header_2": "SKLEISKITE BITCOIN",
	"get_involved_intro_1": "Gali būti slegianti gyventi dabartinėje pasaulio būklėje.",
	"get_involved_intro_2": "Mūsų pinigai sugadinti. Dėl to pagrindiniai visuomenės elementai taip pat sugadinti.",
	"get_involved_intro_3": "Jei jau domitės Bitcoin, žinote vilties jausmą, kurį Bitcoin gali atnešti. Viltį šviesnės ateities, kurią įgalina geresni pinigai.",
	"get_involved_intro_4": "Bet tiek daug žmonių aplink jus nežino apie Bitcoin. Jie gyvena tame pačiame sugadintame pasaulyje kaip ir jūs, bet be vilties švyturio.",
	"get_involved_intro_5": "Bet jūs galite padėti tai pakeisti. Sukūrėme keletą nemokamų resursų, palengvinančių Bitcoin vilties skleidimą aplinkiniais.",
	"get_involved_sticker_header": "Priklijuokite lipduką viešoje vietoje",
	"get_involved_sticker_content_1": "Galite padėti šviesti aplinkinius apie Bitcoin nesusidurdami su niekuo. Tiesiog priklijuokite vieną iš mūsų nemokamų Bitcoin lipdukų viešoje vietoje.",
	"get_involved_sticker_content_2": "Šimtai žmonių kiekvieną mėnesį nuskaito šių lipdukų QR kodus. Infliacijos lipdukai nukreipia į puslapį apie",
	"get_involved_sticker_content_3": "Bitcoin kaip sprendimą nuo infliacijos.",
	"get_involved_sticker_content_4": "Kiti lipdukai nukreipia į mūsų šviečiamąjį pagrindinį puslapį, kuris rodo žmonėms, kaip",
	"get_involved_sticker_content_5": "Bitcoin kuria geresnį pasaulį.",
	"get_involved_sticker_content_6": "Klijuodami šiuos lipdukus savo bendruomenėje vietose, kur žmonės juos matys, galite padėti aplinkiniais žengti pirmuosius žingsnius Bitcoin link.",
	"get_involved_request_a": "UŽSAKYKITE",
	"get_involved_sticker_pack": "LIPDUKŲ PAKĄ",
	"get_involved_postcard_header": "Išsiųskite atviruką",
	"get_involved_postcard_content_1": "Galite padėti skleisti Bitcoin viltį kam nors pažįstamam, išsiųsdami vieną iš mūsų nemokamų atvirukų.",
	"get_involved_postcard_content_2": "Kiekvieno atviruko kitoje pusėje yra įtikinamai parašytas tekstas apie Bitcoin kartu su QR kodu sužinoti daugiau.",
	"get_involved_postcard_content_3": "Siųsdami kam nors Bitcoin atviruką, galite padėti jiems pamatyti Bitcoin nauju kampu.",
	"get_involved_postcard_pack": "ATVIRUKŲ PAKĄ",
	"get_involved_business_header": "Įtraukite verslą",
	"get_involved_business_content_1": "Norite padėti kurti Bitcoin žiedinę ekonomiką? Mūsų Bitcoin verslo rinkinys palengvina pokalbį su verslu apie Bitcoin mokėjimų priėmimą.",
	"get_involved_business_content_2": "Kiekviename verslo rinkinyje yra skrajutės, išryškinančios Bitcoin mokėjimų priėmimo privalumus. Kiekviena skrajutė nukreipia į įvairius",
	"get_involved_business_content_3": "nemokamus Bitcoin verslo resursus.",
	"get_involved_business_kit": "VERSLO RINKINĮ"
});

console.log('\nDone! Content files created for Lithuanian (lt).');
