/**
 * Creates Lithuanian (lt) translation file for common.json (~180+ keys).
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'lt';
const today = '2026-04-04';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

writeFile(`common_${lang}.json`, {
	"common_footer_mission_1": "bitcoin.rocks misija \u2014 paspartinti Bitcoin pri\u0117mim\u0105 per \u0161vietim\u0105.",
	"common_footer_mission_2": "Su\u017Einokite, kaip prisid\u0117ti prie \u0161io atviro kodo projekto.",
	"common_footer_follow_first_half": "Sekite mus Nostr ie\u0161kodami",
	"common_footer_follow_second_half": "bet kuriame Nostr kliente.",
	"common_footer_what_is_nostr": "Kas yra Nostr?",
	"common_footer_about": "Apie",
	"common_footer_email_us": "Ra\u0161ykite mums:",
	"common_cta_section_get_started": "PRAD\u0116KITE",
	"common_cta_section_with_bitcoin": "SU BITCOIN",
	"common_cta_section_title_1": "Su\u017Einokite Bitcoin pagrindus",
	"common_cta_section_title_1_alt": "Su\u017Einokite daugiau apie Bitcoin",
	"common_cta_section_title_2": "Gaukite savo pirm\u0105j\u0105 Bitcoin pinigin\u0119",
	"common_cta_section_title_3": "Kaip pirkti Bitcoin",
	"common_cta_link_type_email": "EL. PA\u0160TAS",
	"common_cta_link_type_guide": "VADOVAS",
	"common_cta_link_type_website": "SVETAIN\u0116",
	"common_cta_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "KAS YRA BITCOIN?",
	"common_what_is_bitcoin_content_1": "Bitcoin yra du dalykai: skaitmeniniai pinigai ir mok\u0117jim\u0173 tinklas. Galite si\u0173sti Bitcoin (skaitmeninius pinigus) tiesiogiai kitiems \u017Emon\u0117ms naudodami Bitcoin tinkl\u0105 (mok\u0117jim\u0173 tinkl\u0105).",
	"common_what_is_bitcoin_content_2": "Bitcoin yra radikaliai naujas b\u016Bdas saugoti ir perduoti vert\u0119. Skirtingai nuo \u012Fprast\u0173 finansini\u0173 tinkl\u0173, Bitcoin tinklas gali veikti be centrin\u0117s valdžios ar patikint\u0173j\u0173 administratori\u0173. Tai padaro Bitcoin pirmaisiais kada nors atvirais ir be sien\u0173 pinigais.",
	"common_what_is_bitcoin_content_3": "Bitcoin yra skaitmeniniai pinigai, suteikiantys jums visi\u0161k\u0105 turto kontrol\u0119. Pirm\u0105 kart\u0105 \u017Emonijos istorijoje kiekvienas gali tur\u0117ti turt\u0105, kuris yra tikrai retas, nereikalauja leidimo naudoti ir negali b\u016Bti konfiskuotas, kai saugomas tinkamai.",
	"common_what_is_bitcoin_content_4": "Bitcoin gali b\u016Bti siunčiamas bet kur pasaulyje, greitai ir pigiai. Jam nereikia treči\u0173j\u0173 \u0161ali\u0173 pervedimo, kaip banko.",
	"common_what_is_bitcoin_content_5": "Bitcoin leidžia bet kam saugoti savo turt\u0105 saugiai, nesijaudinant, kad vyriausyb\u0117 j\u012F pavogs ar suma\u017Eins jo vert\u0119 spausdindama pinigus.",
	"common_what_is_bitcoin_content_6": "Vyriausyb\u0117s visur gali spausdinti daugiau popieriaus pinig\u0173, bet niekas negali spausdinti daugiau bitcoin.",
	"common_what_is_bitcoin_content_7": "Galite lengvai patys saugoti savo Bitcoin, perimdami visi\u0161k\u0105 jo kontrol\u0119, ir taip \u012Fgydami visi\u0161k\u0105 Bitcoin gali\u0105.",
	"common_what_is_bitcoin_content_8": "Jei galite atsisi\u0173sti program\u0117l\u0119, galite patys saugoti Bitcoin ir kaupti savo turt\u0105 nepasikliaudami niekuo kitu.",
	"common_what_is_bitcoin_content_9": "Bitcoin yra geresni pinigai.",
	"common_bitcoin_volatile": "GIRD\u0116JAU, KAD BITCOIN YRA NEPASTOVUS. AR TAI SAUGU?",
	"common_bitcoin_volatile_content_1": "Trumpuoju laikotarpiu Bitcoin keitimo kursas linkęs svyruoti. Tai vadinama nepastovumu.",
	"common_bitcoin_volatile_content_2": "Bet nepastovumas, kur\u012F matote kiekvien\u0105 dien\u0105, ilguoju laikotarpiu \u201Ei\u0161nyksta\u201C.",
	"common_bitcoin_volatile_content_3": "Bitcoin nuolat tampa vis ma\u017Eiau nepastovus. Kuo daugiau \u017Emoni\u0173 naudoja Bitcoin kaip ilgalaik\u0119 taupomaj\u0105 s\u0105skait\u0105, tuo labiau stabilizuojasi jo vert\u0117.",
	"common_bitcoin_volatile_content_4": "Daugelis \u017Emoni\u0173 renkasi saugoti vert\u0119 Bitcoin daugeliui met\u0173 kaip saug\u0173 b\u016Bd\u0105 suma\u017Einti nepastovumo rizik\u0105 ir apsaugoti savo perkam\u0105j\u0105 gali\u0105 laikui b\u0117gant.",
	"common_bitcoin_volatile_content_5": "Kai kuriose \u0161alyse, tokiose kaip Venesuela, Sudanas, Libanas, Sirija, Argentina, Turkija, Brazilija ir daugelyje kit\u0173, vietin\u0117s valiutos vert\u0117 i\u0161p\u016Bsta taip greitai, kad Bitcoin laikomas stabilesniu b\u016Bdu taupyti pinigus.",
	"common_bitcoin_afford": "A\u0160 NEGALIU \u012ESIGYTI VISO BITCOIN",
	"common_bitcoin_afford_content_1": "Doleris susideda i\u0161 100 cent\u0173. Bitcoin susideda i\u0161 100 000 000 (100 milijon\u0173) sats.",
	"common_bitcoin_afford_content_2": "Jums nereikia tur\u0117ti viso bitcoin. Dauguma \u017Emoni\u0173 turi tik sats. Sats yra bitcoin dalys. Pavyzd\u017Eiui, jei 1 visas bitcoin kainuoja 100 000 $, tada u\u017E 1 $ gausite 1 000 sats!",
	"common_bitcoin_hacked": "AR BITCOIN KADA NORS BUVO \u012ESILAUŽTA?",
	"common_bitcoin_hacked_content_1": "Gal b\u016Bt gird\u0117jote apie \u201EBitcoin \u012Fsilau\u017Eim\u0105\u201C internete ar naujienose. Dauguma \u017Emoni\u0173 perskaito \u0161iuos straipsnius ir mano, kad Bitcoin tinklas buvo \u012Fsilaužtas. Ta\u010Diau Bitcoin tinklas niekada nebuvo \u012Fsilaužtas.",
	"common_bitcoin_hacked_content_2": "Kas yra Bitcoin tinklas? \u012Esivaizduokite Bitcoin tinkl\u0105 kaip gele\u017Einkelio b\u0117gius. Traukiniai, va\u017Eiuojantys Bitcoin tinklo b\u0117giais, yra Bitcoin operacijos.",
	"common_bitcoin_hacked_content_3": "Kai skaitote apie Bitcoin \u012Fsilau\u017Eim\u0105 naujienose, skaitote apie saugotoj\u0105 (pvz., FTX), kuris buvo \u012Fsilaužtas arba bankrutavo.",
	"common_bitcoin_hacked_content_4": "Saugotojai yra \u012Fmon\u0117s, kurios laiko j\u016Bs\u0173 bitcoin u\u017E jus. Ta\u010Diau tai kelia rizik\u0105: prarasti bitcoin, kai \u012Fmon\u0117 j\u012F netinkamai valdo, pavagia ar u\u017Esidaro.",
	"common_bitcoin_hacked_content_5": "Tai neseniai nutiko su FTX.",
	"common_bitcoin_hacked_content_6": "Visi, kurie patik\u0117jo FTX savo bitcoin, prarado j\u012F. Visi, kurie laik\u0117 bitcoin savaranki\u0161kai, buvo visi\u0161kai nepaveikti FTX. Tokia yra savaranki\u0161kai saugomo bitcoin galia: tikra j\u016Bs\u0173 pinig\u0173 kontrol\u0117.",
	"common_bitcoin_hacked_content_7": "U\u017Euot palik\u0119 bitcoin bir\u017Eoje ar apvalkale kaip ETF, laikykite j\u012F savo pinigin\u0117je, kad gal\u0117tum\u0117te naudotis visais laisv\u0117s privalumais.",
	"common_bitcoin_hacked_content_8": "Kai patys saugote savo bitcoin, j\u016Bs\u0173 pinigus saugo Bitcoin tinklas. Tai saugiausias finansinis tinklas pasaulyje.",
	"common_bitcoin_hacked_content_9": "Savaranki\u0161kai saugant, Sam i\u0161 FTX negali pavogti j\u016Bs\u0173 bitcoin.",
	"common_bitcoin_hacked_content_10": "Vyriausyb\u0117 negali spausdinti daugiau bitcoin ir sukelti infliacij\u0105.",
	"common_bitcoin_hacked_content_11": "Savaranki\u0161kai saugomas Bitcoin yra j\u016Bs\u0173 pinigai, d\u0117l Bitcoin tinklo galios.",
	"common_bitcoin_energy": "KOD\u0116L BITCOIN NAUDOJA ENERGIJ\u0104?",
	"common_bitcoin_energy_content_1": "Bitcoin naudoja energij\u0105 tinklo apsaugai ir j\u016Bs\u0173 pinig\u0173 saugumui u\u017Etikrinti.",
	"common_bitcoin_energy_content_2": "Bitcoin naudoja reik\u0161ming\u0105 energijos kiek\u012F, ir tai yra puikus dalykas d\u0117l daugelio prie\u017Eas\u010Di\u0173.",
	"common_bitcoin_energy_list_1": "Bitcoin neturi bank\u0173 panik\u0173.",
	"common_bitcoin_energy_list_2": "Bitcoin padeda stabilizuoti energijos tinklus per Bitcoin kasinim\u0105.",
	"common_bitcoin_energy_list_3": "Bitcoin ma\u017Eina emisijas i\u0161 naftos gavybos.",
	"common_bitcoin_energy_list_4": "Bitcoin naudoja ma\u017Eiau energijos nei amerikiečiai sunaudoja Kal\u0117d\u0173 \u0161vies\u0173 kasmet.",
	"common_bitcoin_energy_list_5": "Bitcoin yra \u017Ealiausia industrija \u017Dem\u0117je!",
	"common_cic_intro_1": "Daugelis \u017Emoni\u0173 \u017Eino apie sud\u0117tines pal\u016Bkanas, bet ma\u017Eai kas \u017Eino apie sud\u0117tin\u0119 infliacij\u0105.",
	"common_cic_intro_2": "Su m\u016Bs\u0173 sud\u0117tin\u0117s infliacijos skaičiuokle galite lengvai apskaičiuoti, kiek turi padid\u0117ti j\u016Bs\u0173 atlyginimas, kad i\u0161laikytum\u0117te perkam\u0105j\u0105 gali\u0105 laikui b\u0117gant.",
	"common_cic_intro_3": "Tiesiog \u012Fveskite dabartin\u012F atlyginim\u0105, infliacijos norm\u0105 ir met\u0173 skaičių, ir m\u016Bs\u0173 skaičiuokl\u0117 parodys, koks tur\u0117t\u0173 b\u016Bti j\u016Bs\u0173 atlyginimas, kad neatsilikt\u0173 nuo infliacijos.",
	"common_current_salary": "dabartinis atlyginimas",
	"common_inflation_rate": "infliacijos norma",
	"common_year": "metai",
	"common_years": "metai",
	"common_result_starting_message": "U\u017Epildykite form\u0105 vir\u0161uje ir spauskite skaičiuoti.",
	"common_error_message": "Klaida: u\u017Epildykite visus 3 formos laukus.",
	"common_result_message_1": "Su infliacijos norma",
	"common_result_message_2": "j\u016Bs\u0173",
	"common_result_message_3": "atlyginimas turi padid\u0117ti iki",
	"common_result_message_in": "per",
	"common_result_message_4": "kad i\u0161laikytum\u0117te perkam\u0105j\u0105 gali\u0105.",
	"common_calculate_button_text": "SKAIČIUOTI",
	"common_learn_more": "SU\u017DINOTI DAUGIAU",
	"common_success": "S\u0116KMINGAS!",
	"common_choose_your_country": "Pasirinkite savo \u0161al\u012F",
	"common_country_usa": "JAV",
	"common_country_canada": "Kanada",
	"common_submit": "PATEIKTI",
	"common_language_afrikaans": "AFRIKAANS",
	"common_language_arabic": "ARAB\u0172",
	"common_language_basque": "BASK\u0172",
	"common_language_bulgarian": "BULGAR\u0172",
	"common_language_catalan": "KATALONIJOS",
	"common_language_chinese": "KIN\u0172",
	"common_language_croatian": "KROAT\u0172",
	"common_language_czech": "\u010CEK\u0172",
	"common_language_danish": "DAN\u0172",
	"common_language_dutch": "OLAND\u0172",
	"common_language_english": "ANGL\u0172",
	"common_language_estonian": "EST\u0172",
	"common_language_filipino": "FILIPINO",
	"common_language_finnish": "SUOMI\u0172",
	"common_language_french": "PRANC\u016AZ\u0172",
	"common_language_german": "VOKIE\u010CI\u0172",
	"common_language_greek": "GRAIK\u0172",
	"common_language_hausa": "HAUS\u0172",
	"common_language_hebrew": "HEBRAJ\u0172",
	"common_language_hindi": "HINDI",
	"common_language_hungarian": "VENGR\u0172",
	"common_language_indonesian": "INDONEZIJOS",
	"common_language_irish": "AIR\u0172",
	"common_language_italian": "ITAL\u0172",
	"common_language_japanese": "JAPON\u0172",
	"common_language_korean": "KOR\u0116JIEČI\u0172",
	"common_language_malay": "MALAJ\u0172",
	"common_language_norwegian": "NORVEG\u0172",
	"common_language_persian": "PERS\u0172",
	"common_language_polish": "LENK\u0172",
	"common_language_portuguese": "PORTUGAL\u0172",
	"common_language_russian": "RUS\u0172",
	"common_language_sinhala": "SINHAL\u0172",
	"common_language_slovak": "SLOVAK\u0172",
	"common_language_slovenian": "SLOV\u0116N\u0172",
	"common_language_spanish": "ISPAN\u0172",
	"common_language_swahili": "SVAHILI\u0172",
	"common_language_swedish": "\u0160VED\u0172",
	"common_language_thai": "TAJ\u0172",
	"common_language_turkish": "TURK\u0172",
	"common_language_urdu": "URDU",
	"common_language_vietnamese": "VIETNAMIE\u010CI\u0172",
	"common_language_yoruba": "JORUB\u0172",
	"common_stickers_bulk_mess": "Nenorite patys tvarkyti fail\u0173?",
	"common_stickers_bulk_want": "Norite daugiau nei kelis lipdukus?",
	"common_stickers_bulk_store": "U\u017Esakykite lipdukus didmenomis i\u0161 to paties spaustuvininko, kur\u012F naudojame.",
	"common_stickers_bulk_cheaper": "Kuo daugiau lipduk\u0173 perkate, tuo pigiau kainuoja vienas lipdukas.",
	"common_stickers_print_instructions_1": "Galite dalyvauti atsispausdindami savo lipdukus, nepriklausomai nuo to, kur gyvenate! Spauskite ant savo kalbos \u017Eemiau, kad atsisi\u0173stum\u0117te lipduk\u0173 failus ir instrukcijas.",
	"common_stickers_print_instructions_2": "Atkreipkite d\u0117mes\u012F: ne visi lipdukai pasiekiami visomis kalbomis.",
	"common_stickers_request_language_1": "Nematote savo kalbos?",
	"common_stickers_request_language_2": "U\u017Epildykite \u017Eemiau esan\u010Di\u0105 form\u0105, kad u\u017Esakytum\u0117te lipduk\u0173 failus savo kalba.",
	"common_stickers_dimensions": "Matmenys:",
	"common_stickers_type": "Tipas:",
	"common_stickers_material": "Med\u017Eiaga:",
	"common_stickers_where_to_print": "Kur spausdinti:",
	"common_stickers_type_die_cut": "i\u0161pjautas lipdukas",
	"common_stickers_material_vinyl": "viniliniai lipdukai lauko naudojimui",
	"common_stickers_printer": "Naudojame StickerMule.com, bet galite naudoti bet koki\u0105 lipduk\u0173 \u012Fmon\u0119.",
	"common_stickers_dimensions_danger": "11,4544 cm x 8,382 cm (4,51 in x 3,3 in)",
	"common_stickers_dimensions_warning": "10,414 cm x 9,2202 cm (4,1 in x 3,63 in)",
	"common_stickers_dimensions_caution": "12,0142 cm x 7,9502 cm (4,73 in x 3,13 in)",
	"common_stickers_dimensions_fix": "11,3792 cm x 6,8072 cm (4,48 in x 2,68 in)",
	"common_stickers_dimensions_study": "14,605 cm x 5,1308 cm (5,75 in x 2,02 in)",
	"common_stickers_dimensions_bdhi": "21,59 cm x 4,6482 cm (8,5 in x 1,83 in)",
	"common_stickers_dimensions_cure_v2": "6,35 cm x 12,7 cm (2,5 in x 5 in)",
	"common_stickers_dimensions_got_inflation": "7,9248 cm x 14,605 cm (3,12 in x 5,75 in)",
	"common_stickers_dimensions_what_if": "21,7932 cm x 7,62 cm (8,58 in x 3 in)",
	"common_stickers_dimensions_bitcoin_accepted_here": "20,995 cm x 6,35 cm (8,25 in x 2,5 in)",
	"common_nostr_join": "PRISIJUNKITE PRIE NOSTR DABAR",
	"common_nostr_protocol_header": "Protokolas, ne platforma",
	"common_nostr_protocol_c1": "Nostr yra naujas protokolas, leid\u017Eiantis bendrauti internete be baim\u0117s d\u0117l cenz\u016Bros, platformos atjungimo ar algoritm\u0173 slopinimo.",
	"common_nostr_protocol_c2": "Platformas kaip Twitter ir Facebook kontroliuoja viena \u012Fmon\u0117, bet niekas nekontroliuoja Nostr protokolo.",
	"common_nostr_freedom_header": "Laisv\u0117 jud\u0117ti",
	"common_nostr_freedom_c1": "Nostr pana\u0161us \u012F el. pa\u0161t\u0105. Niekas nekontroliuoja el. pa\u0161to protokolo, ir bet kas gali sukurti klient\u0105 (kaip Gmail, Hotmail ir kt.) ant jo.",
	"common_nostr_freedom_c2": "Niekas nekontroliuoja Nostr protokolo, ir bet kas gali sukurti klient\u0105 (kaip Damus, Amethyst ir kt.) ant jo.",
	"common_nostr_freedom_c3": "Jei jums nepatinka tam tikro kliento veikimas, galite nesunkiai perkelti savo Nostr paskyr\u0105 \u012F kit\u0105 klient\u0105 neprarasdami sek\u0117j\u0173 ar turinio.",
	"common_nostr_bitcoin_header": "Bitcoin \u012Fmontuotas",
	"common_nostr_bitcoin_c1": "Bitcoin yra \u012Fmontuotas \u012F Nostr protokol\u0105. Jei matote turin\u012F, kuris jums patinka, galite lengvai nusi\u0173sti bitcoin kaip pad\u0117k\u0105!",
	"common_nostr_bitcoin_c2": "Centralizuotose platformose kaip Twitter ir Facebook centralizuota \u012Fmon\u0117 u\u017Edirba i\u0161 j\u016Bs\u0173 turinio. Bet atviruose protokoluose kaip Nostr j\u016Bs u\u017Edirbate i\u0161 savo turinio.",
	"common_nostr_download_client": "ATSISI\u0172SKITE NEMOKAM\u0104 KLIENT\u0104 IR PRISIJUNKITE PRIE NOSTR",
	"common_nostr_iphone_clients": "iPhone klientai",
	"common_nostr_primal": "PRIMAL",
	"common_nostr_iphone_app": "iPhone program\u0117l\u0117",
	"common_nostr_first_client": "Rekomenduojamas pirmasis klientas",
	"common_nostr_wallet_built_in": "\u012Emontuota Bitcoin zap pinigin\u0117",
	"common_nostr_download_now": "ATSISI\u0172STI DABAR",
	"common_nostr_damus": "DAMUS",
	"common_nostr_familiar": "Pa\u017E\u012Fstama s\u0105saja",
	"common_nostr_separate_wallet": "Reikia atskiros bitcoin pinigin\u0117s",
	"common_nostr_android_clients": "Android klientai",
	"common_nostr_android_app": "Android program\u0117l\u0117",
	"common_nostr_amethyst": "AMETHYST",
	"common_nostr_features": "Daug funkcij\u0173",
	"common_nostr_browser_clients": "Nar\u0161ykl\u0117s klientai",
	"common_nostr_iris": "IRIS",
	"common_nostr_web_client": "Interneto klientas",
	"common_nostr_simple": "Labai paprastas",
	"common_nostr_test": "Lengvas b\u016Bdas i\u0161bandyti Nostr naudojant bandom\u0105j\u0105 paskyr\u0105",
	"common_nostr_view_client": "PER\u017DI\u016AR\u0116TI KLIENT\u0104",
	"common_kit_printer": "Rekomenduojame VistaPrint.com savo Bitcoin verslo rinkinio bro\u0161i\u016Br\u0173 spausdinimui. Ta\u010Diau galite naudoti bet koki\u0105 spaustuv\u0119, kuri gali spausdinti abipusiai.",
	"common_kit_link_to_print": "Nuoroda spausdinti:",
	"common_kit_fold": "Lankstymas:",
	"common_kit_fold_trifold": "Trisluoksnis lankstymas",
	"common_kit_unfolded_size": "I\u0161lankstytas dydis:",
	"common_kit_unfolded_size_bbk": "Laiško dydis (8,5 in x 11 in)",
	"common_kit_paper_thickness": "Popieriaus storis:",
	"common_kit_paper_thickness_standard": "Standartinis",
	"common_kit_paper_stock": "Popieriaus tipas:",
	"common_kit_paper_stock_glossy": "Blizgus",
	"common_kit_exterior_print_file": "I\u0161orin\u0117s dalies spausdinimo failas:",
	"common_kit_interior_print_file": "Vidin\u0117s dalies spausdinimo failas:",
	"common_kit_cta_header": "Pad\u0117kite vietiniam verslui priimti Bitcoin",
	"common_biz_learn": "Su\u017Einokite, kod\u0117l Bitcoin naudingas verslui",
	"common_biz_wallets": "Gaukite Bitcoin pinigin\u0119 priimti Bitcoin mok\u0117jimus",
	"common_biz_maps": "U\u017Esiregistruokite Bitcoin prekiautoj\u0173 \u017Eem\u0117lapiuose",
	"common_biz_stickers": "Nemokami \u201EBitcoin Accepted Here\u201C lipdukai",
	"common_biz_rewards": "Bitcoin apdovanojimai",
	"common_biz_accounting": "Bitcoin apskaitos vadovas",
	"common_biz_faq": "Da\u017Enai u\u017Eduodami klausimai",
	"common_biz_kit": "Atsispausdinkite savo Bitcoin verslo rinkin\u012F",
	"common_biz_accept_bitcoin_payments": "PRIIMKITE BITCOIN MOK\u0116JIMUS",
	"common_biz_ready": "PASIRUO\u0160\u0116 PRIIMTI BITCOIN SAVO VERSLE?",
	"common_biz_more": "DAUGIAU VERSLO RESURS\u0172",
	"common_self_custody": "SAVARANKI\u0160KA SAUGYKLA",
	"common_not_your_keys": "NE J\u016AS\u0172 RAKTAI",
	"common_cold_wallet": "\u0160ALTA PINIGIN\u0116",
	"common_hot_wallet": "KAR\u0160TA PINIGIN\u0116",
	"common_sticker_files_mission_1": "M\u016Bs\u0173 misija \u2014 pad\u0117ti jums \u012Ftraukti daugiau \u017Emoni\u0173 \u012F Bitcoin klijuojant lipdukus vie\u0161ose vietose. Visuose m\u016Bs\u0173 lipdukuose yra QR kodai, nukreipiantys \u012F \u0161viečiam\u0105sias pus lapius apie",
	"common_sticker_files_mission_2": "Bitcoin",
	"common_sticker_files_mission_3": "infliacij\u0105",
	"common_sticker_files_mission_4": "Jei gyvenate JAV ar Kanadoje, galite",
	"common_sticker_files_mission_5": "u\u017Esakyti nemokam\u0105 angli\u0161k\u0173 lipduk\u0173 pak\u0105",
	"common_published_by": "Paskelbta",
	"common_publisher_name": "bitcoin.rocks",
	"common_publisher_since": "Bitcoin \u0161vietimas nuo 2022 m.",
	"common_publisher_open_source": "Atviro kodo projektas",
	"common_reviewed_accuracy": "\u2713 Patikrinta d\u0117l tikslumo: 2026",
	"common_footer_tagline": "Spartiname Bitcoin pri\u0117mim\u0105 per \u0161vietim\u0105.",
	"common_footer_contribute": "Prisid\u0117ti",
	"common_footer_nostr": "Nostr",
	"common_sources_heading": "\u0160altiniai"
});

console.log('\nDone! Common file created for Lithuanian (lt).');
