/**
 * Creates Bengali (bn) content page translation files:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */
const fs = require('fs');
const path = require('path');
const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'bn';
const today = '2026-04-06';
const meta = { "@metadata": { "authors": ["Satoshi"], "last-updated": today, "locale": lang } };

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "Bitcoin-এ ব্যাংক রান নেই",
	"bank_runs_header": "BITCOIN-এ ব্যাংক রান নেই",
	"bank_runs_header_2": "কিন্তু আপনার ব্যাংকে হতে পারে",
	"bank_runs_what": "ব্যাংক রান কী?",
	"bank_runs_what_content_1": "ব্যাংক রান ঘটে যখন অনেক মানুষ একই সময়ে ব্যাংক থেকে তাদের অর্থ উত্তোলন করার চেষ্টা করে।",
	"bank_runs_what_content_2": "যদি ব্যাংকের কাছে উত্তোলনের সাথে মিলাতে যথেষ্ট অর্থ না থাকে, ব্যাংক রান ঘটলে তারা সম্পূর্ণ ভেঙে পড়তে পারে।",
	"bank_runs_how": "ব্যাংক রান কিভাবে ঘটে?",
	"bank_runs_how_content_1": "আমাদের ব্যাংকিং ব্যবস্থা 'ভগ্নাংশ রিজার্ভ' যার মানে ব্যাংক শুধু আপনার অর্থ ভল্টে রেখে আপনার খরচ বা উত্তোলনের জন্য অপেক্ষা করে না।",
	"bank_runs_how_content_2": "পরিবর্তে, আপনার ব্যাংক আপনার অর্থ নিয়ে ঋণ দেয় বা বিনিয়োগ করে। এটি দীর্ঘ সময়ের জন্য আপনার অর্থ আটকে রাখতে পারে, যদিও ব্যাংক আপনাকে যেকোনো সময় আপনার অর্থ উত্তোলনের ক্ষমতার প্রতিশ্রুতি দেয়।",
	"bank_runs_how_content_3": "তাহলে ব্যাংক ইতিমধ্যে আপনার অর্থ ঋণ দেওয়া বা বিনিয়োগ করার পর আপনি যদি তা উত্তোলন করার চেষ্টা করেন?",
	"bank_runs_how_content_4": "আপনি যদি একমাত্র ব্যক্তি হন যে উত্তোলন করার চেষ্টা করছেন তাহলে সমস্যা নেই। ব্যাংক অন্য কারো অর্থ নিয়ে আপনাকে দেবে। কিন্তু যদি অনেক মানুষ একই সময়ে উত্তোলন করার চেষ্টা করে?",
	"bank_runs_how_content_5": "২০২৩ সালের মার্চে Silicon Valley Bank-এ রান হলে যুক্তরাষ্ট্রের অনেক মানুষ এটি জানতে পারে।",
	"bank_runs_how_content_6": "ব্যাংক তাদের গ্রাহকদের অর্থ সরকারি বন্ডে বিনিয়োগ করেছিল যা ৩০ বছর পর্যন্ত লক ছিল। আরও খারাপ, সেই বন্ডের মূল্য সম্প্রতি ব্যাপকভাবে কমেছিল, তাই Silicon Valley Bank তাদের আমানতকারীদের অর্থ পেতে বন্ড বিক্রি করতে পারেনি। তারা দেউলিয়া ছিল। তাদের আমানতকারীদের উত্তোলনের সাথে মেলানোর জন্য পর্যাপ্ত অর্থ ছিল না।",
	"bank_runs_how_content_7": "আরও মানুষ জানতে পারলে, সমস্যা আরও খারাপ হয়। আরও উত্তোলন অনুরোধ আসে, কিন্তু অনেকগুলো প্রক্রিয়া হয়নি। হাজার হাজার ব্যবসা বুঝতে পারে যে ব্যাংক ব্যর্থ হওয়ায় তারা তাদের কর্মচারীদের বেতন দিতে পারবে না।",
	"bank_runs_how_content_8": "FDIC এগিয়ে এসে আমানতকারীদের পূর্ণ করতে সম্মত হয়। সমস্যা সমাধান? ঠিক তা নয়...",
	"bank_runs_fdic": "FDIC বীমা কি আমার অর্থ রক্ষা করে?",
	"bank_runs_fdic_content_1": "FDIC বীমা ব্যাংক ব্যর্থ হলে ব্যাংক আমানতকারীদের রক্ষা করার জন্য ডিজাইন করা হয়েছে। প্রতি আমানতকারীর $২৫০,০০০ পর্যন্ত আমানত বীমা করা হয়। দুর্দান্ত শোনাচ্ছে, তাই না?",
	"bank_runs_fdic_content_2": "ঠিক তা নয়। যদি একটি ব্যাংক ব্যর্থ হয়, FDIC অর্থ কোথা থেকে পায়? তাদের বীমা তহবিলে ১২৫ বিলিয়ন ডলার আছে।",
	"bank_runs_fdic_content_3": "এটি অনেক অর্থ মনে হয় যতক্ষণ না আপনি এটিকে তারা যে পরিমাণ আমানত বীমা করে তার সাথে তুলনা করেন: প্রায় ১০ ট্রিলিয়ন বা ১০,০০০ বিলিয়ন ডলার।",
	"bank_runs_fdic_content_4": "FDIC এমনকি তাদের ওয়েবসাইটে দেখায় যে তাদের বীমা তহবিলে আমানতের ১% এর সামান্য বেশি কভার করার জন্য পর্যাপ্ত অর্থ আছে।",
	"bank_runs_fdic_content_5": "FDIC বীমা তহবিল অতিক্রম করে এমন ব্যাংক ব্যর্থতার ক্ষেত্রে, মার্কিন সরকার আমানতকারীদের পূর্ণ করতে অর্থ ছাপাবে এটি সম্ভাব্য (কিন্তু নিশ্চিত নয়)।",
	"bank_runs_fdic_content_6": "কিন্তু অর্থ ছাপানো মুদ্রাস্ফীতি ঘটায়, তাই এটি কোনো ভালো সমাধান নয়।",
	"bank_runs_safe": "ভগ্নাংশ রিজার্ভ ব্যবহার করে না এমন কোনো ব্যাংক আছে?",
	"bank_runs_safe_content_1": "কিছু ব্যাংক 'নিরাপদ ব্যাংক' হওয়ার চেষ্টা করেছে যারা আমানতকারীদের তহবিল ঋণ দেয় না বা বিনিয়োগ করে না।",
	"bank_runs_safe_content_2": "যদিও এই নিরাপদ ব্যাংকগুলোতে ব্যাংক রানের শূন্য ঝুঁকি থাকবে, তাদের আবেদন ফেডারেল রিজার্ভ দ্বারা প্রত্যাখ্যান করা হয়েছে। এর মানে তারা আইনত ব্যাংক হিসেবে কাজ করতে পারে না।",
	"bank_runs_safe_content_3": "যেহেতু তাদের কাজ করা থেকে ব্লক করা হয়েছে, আজ এমন কোনো ব্যাংক নেই যা ভগ্নাংশ রিজার্ভ ব্যবহার করে না।",
	"bank_runs_safe_content_4": "সৌভাগ্যবশত, নিজের ব্যাংক হয়ে ভগ্নাংশ রিজার্ভ ব্যবস্থা থেকে বেরিয়ে আসার একটি উপায় আছে। না, আমরা বিছানার নিচে নগদ লুকানোর কথা বলছি না।",
	"bank_runs_safe_content_5": "নগদে সঞ্চয় করা এখনও মুদ্রাস্ফীতির জন্য ঝুঁকিপূর্ণ।",
	"bank_runs_safe_content_6": "আমরা Bitcoin-এর কথা বলছি: একটি নতুন আর্থিক ব্যবস্থা যা আপনাকে নিজের ব্যাংক হতে দেয়।",
	"bank_runs_protect": "BITCOIN কি আমাকে ব্যাংক রান থেকে রক্ষা করতে পারে?",
	"bank_runs_protect_content_1": "হ্যাঁ, Bitcoin হলো একটি পূর্ণ রিজার্ভ আর্থিক ব্যবস্থা।",
	"bank_runs_protect_content_2": "Bitcoin-এ ব্যাংক রান অসম্ভব যতক্ষণ আপনি আপনার Bitcoin আপনার নিজের ওয়ালেটে উত্তোলন করেন। আপনার bitcoin এক্সচেঞ্জে বা Bitcoin ETF-এর মতো র‍্যাপারে রাখবেন না।",
	"bank_runs_protect_content_3": "কিভাবে আপনার নিজের ওয়ালেটে উত্তোলন করবেন তা জানতে আমাদের সহজ Bitcoin ওয়ালেট গাইড দেখুন।",
	"bank_runs_protect_content_4": "Bitcoin দিয়ে, আপনি অবশেষে আপনার অর্থের নিয়ন্ত্রণে থাকতে পারেন।"
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Bitcoin ওয়ালেট গাইড",
	"wallets_description": "অনেক বিভিন্ন Bitcoin ওয়ালেট আছে যা গুরুত্বপূর্ণ উপায়ে আলাদা। এই সহজ প্রশ্নগুলো জিজ্ঞাসা করে আপনি নির্ধারণ করতে পারেন কোন ওয়ালেট আপনার জন্য সঠিক।",
	"wallets_header": "কিভাবে নিরাপদে আপনার BITCOIN সংরক্ষণ করবেন",
	"wallets_s1_c1": "Bitcoin ওয়ালেট আন্তঃকার্যক্ষম, তাই আপনি যেকোনো ওয়ালেট ব্যবহার করুক না কেন যে কাউকে Bitcoin পাঠাতে পারেন।",
	"wallets_s1_c2": "অনেক বিভিন্ন Bitcoin ওয়ালেট আছে যা গুরুত্বপূর্ণ উপায়ে আলাদা। এই সহজ প্রশ্নগুলো জিজ্ঞাসা করে আপনি নির্ধারণ করতে পারেন কোন ওয়ালেট আপনার জন্য সঠিক:",
	"wallets_question_1": "এটি কি একটি স্ব-হেফাজত ওয়ালেট?",
	"wallets_s2_c1": "Bitcoin-এর একটি উদ্ভাবন হলো কাস্টোডিয়ান, যেমন ব্যাংকের উপর নির্ভর না করে এটি সংরক্ষণ করার ক্ষমতা।",
	"wallets_s2_c2": "আপনি যদি এক্সচেঞ্জে বা ETF-তে bitcoin ধরে রাখেন, আপনি bitcoin-এর স্বাধীনতা সুবিধা হারান।",
	"wallets_s2_c3": "স্ব-হেফাজত ওয়ালেট Bitcoin-এর পূর্ণ শক্তি আনলক করে: স্বাধীনতার অর্থ।",
	"wallets_s2_c4": "একটি স্ব-হেফাজত ওয়ালেটে, আপনিই একমাত্র যিনি আপনার অর্থ খরচ বা স্থানান্তর করতে পারেন। স্ব-হেফাজত ওয়ালেট ব্যবহার করলে কেউ আপনাকে আপনার অর্থ পাঠানো বা গ্রহণ করা থেকে থামাতে পারে না।",
	"wallets_s2_c5": "স্ব-হেফাজত ওয়ালেটকে নন-কাস্টোডিয়াল ওয়ালেটও বলা হয়।",
	"wallets_s3_c1": "কাস্টোডিয়াল ওয়ালেট হলো সেই ওয়ালেট যেখানে আপনি আপনার অর্থের নিয়ন্ত্রণে নন।",
	"wallets_s3_c2": "এই ওয়ালেটগুলো ব্যাংকিং ব্যবস্থার মতো যেখানে আপনাকে আপনার অর্থে প্রবেশের জন্য তৃতীয় পক্ষকে বিশ্বাস করতে হয়। আপনার Bitcoin যদি এক্সচেঞ্জে থাকে, আপনি কাস্টোডিয়াল ওয়ালেট ব্যবহার করছেন।",
	"wallets_s3_c3": "আপনি যদি Bitcoin ETF কিনে থাকেন, আপনি একটি কাস্টোডিয়াল ওয়ালেট ব্যবহার করছেন যা আপনাকে স্ব-হেফাজতে উত্তোলন করতে দেয় না।",
	"wallets_s3_c4": "কাস্টোডিয়াল ওয়ালেট সুবিধাজনক মনে হতে পারে, কিন্তু কাস্টোডিয়ানের কাছে যেকোনো সময় সমস্ত ব্যবহারকারীর তহবিল চুরি করার প্রযুক্তিগত ক্ষমতা আছে।",
	"wallets_s3_c5": "আপনার কী নয়, আপনার কয়েন নয়!",
	"wallets_question_2": "এটি কি হট না কোল্ড?",
	"wallets_s4_c1": "কোল্ড ওয়ালেট আপনার Bitcoin-এর কী এমনভাবে সংরক্ষণ করে যা কখনো ইন্টারনেটে প্রকাশ করে না।",
	"wallets_s4_c2": "এটি উল্লেখযোগ্যভাবে আক্রমণের ভেক্টর সীমিত করে যা একজন চোর আপনার Bitcoin চুরি করতে ব্যবহার করতে পারে, এবং বড় পরিমাণ Bitcoin-এর জন্য সবচেয়ে ভালো যা আপনাকে ঘন ঘন স্থানান্তর করতে হয় না।",
	"wallets_s4_c3": "আপনি কোল্ড ওয়ালেটকে দীর্ঘমেয়াদী সঞ্চয় হিসেবে ভাবতে পারেন, যা কোল্ড স্টোরেজ নামেও পরিচিত।",
	"wallets_s5_c1": "হট ওয়ালেট আপনার Bitcoin-এর কী ইন্টারনেটের সাথে সংযুক্ত ডিভাইসে, যেমন আপনার ফোনে সংরক্ষণ করে।",
	"wallets_s5_c2": "হট ওয়ালেট সাধারণত নিরাপদ বলে বিবেচিত, কিন্তু কোল্ড ওয়ালেটের চেয়ে তাদের বেশি নিরাপত্তা দুর্বলতা থাকতে পারে।",
	"wallets_s5_c3": "আপনি হট ওয়ালেটকে ভৌত ওয়ালেটের মতো ভাবতে পারেন। আপনি আপনার সম্পূর্ণ সঞ্চয় ওয়ালেটে রাখবেন না, কিন্তু কিছু খরচের অর্থ রাখবেন।",
	"wallets_s5_c4": "হট ওয়ালেট কোল্ড স্টোরেজ থেকে আপনার সম্পূর্ণ সঞ্চয় বের না করে আপনার Bitcoin খরচ করা অনেক সহজ করে।",
	"wallets_question_3": "আমি কিভাবে আমার রিকভারি ফ্রেজ ব্যাকআপ করবো?",
	"wallets_s6_c1": "আপনি যখন আপনার Bitcoin ওয়ালেট সেটআপ করবেন, আপনার ডিভাইস একটি রিকভারি ফ্রেজ তৈরি করবে। এই রিকভারি ফ্রেজ (সিড ফ্রেজও বলা হয়) ১২ বা ২৪টি শব্দ ধারণ করে।",
	"wallets_s6_c2": "আপনি যদি কখনো আপনার ওয়ালেটে প্রবেশ হারান বা আপনার ডিভাইস কাজ করা বন্ধ করে, আপনি এই রিকভারি ফ্রেজ একটি নতুন ওয়ালেটে ইনপুট করে আপনার Bitcoin-এ পুনরায় প্রবেশ পেতে পারেন।",
	"wallets_s6_c3": "বেশিরভাগ ওয়ালেট আপনার রিকভারি ফ্রেজ লেখার জন্য একটি কাগজ অন্তর্ভুক্ত করে, কিন্তু অনেক মানুষ এই ফ্রেজ স্টিলে ব্যাকআপ করতে পছন্দ করে। এটি আগুন বা বন্যার মতো প্রাকৃতিক বিপর্যয়ে আপনার রিকভারি ফ্রেজ হারানোর সম্ভাবনা অনেক কমিয়ে দেয়।",
	"wallets_s6_c4": "Jameson Lopp আপনার জন্য সঠিকটি বেছে নিতে সাহায্য করতে ৭০টি স্টিল ব্যাকআপ কিট পরীক্ষা করেছেন।",
	"wallets_s6_c5": "Jameson-এর মেটাল Bitcoin ব্যাকআপ গাইড এখানে দেখুন।",
	"wallets_s6_c6": "অথবা Bitcoin ওয়ালেট বিকল্পগুলো অন্বেষণ করতে স্ক্রল করতে থাকুন।",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "আমাদের লাইটনিং ওয়ালেট গাইড খুঁজছেন?",
	"wallets_starter_wallet": "দুর্দান্ত স্টার্টার ওয়ালেট",
	"wallets_mobile_app": "মোবাইল অ্যাপ",
	"wallets_2fa_support": "2FA সমর্থন",
	"wallets_air_gap_mode": "এয়ার-গ্যাপ মোড",
	"wallets_air_gap_camera": "এয়ার-গ্যাপ মোড + ক্যামেরা",
	"wallets_bitcoin_only": "শুধু Bitcoin",
	"wallets_security_features": "অনেক নিরাপত্তা বৈশিষ্ট্য",
	"wallets_free": "১০০% বিনামূল্যে",
	"wallets_coldcard_mk5_costs": "দাম $189",
	"wallets_coldcard_q_costs": "দাম $289",
	"wallets_blockstream_jade_costs": "দাম $79",
	"wallets_foundation_passport_costs": "দাম $199",
	"wallets_seedsigner_costs": "পার্টস খরচ $50",
	"wallets_very_affordable": "অত্যন্ত সাশ্রয়ী",
	"wallets_pair_with_phone": "আপনার ফোনের সাথে জোড়া লাগান",
	"wallets_battery": "রিচার্জেবল ব্যাটারি",
	"wallets_build_your_own": "নিজে তৈরি করুন",
	"wallets_qwerty_keyboard": "পূর্ণ QWERTY কীবোর্ড",
	"wallets_qr_scanner": "QR কোড স্ক্যানার"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "কিভাবে Bitcoin কিনবেন - ধাপে ধাপে গাইড",
	"buy_header": "কিভাবে BITCOIN কিনবেন",
	"buy_intro_c1": "প্রথমবার Bitcoin কেনা কঠিন মনে হতে পারে, কিন্তু ধাপে ভাগ করলে এটি আসলে বেশ সহজ।",
	"buy_intro_c2": "এই গাইড আপনাকে নিরাপদে Bitcoin কেনা এবং আপনার নিজের ওয়ালেটে সংরক্ষণ করার প্রক্রিয়ায় নিয়ে যাবে।",
	"buy_step_1_header": "ধাপ ১: আপনার দেশ বেছে নিন",
	"buy_step_1_description": "বিভিন্ন দেশে বিভিন্ন Bitcoin কেনার বিকল্প উপলব্ধ। আপনার জন্য সেরা বিকল্পগুলো দেখতে আপনার দেশ বেছে নিন।",
	"buy_search_countries": "আপনার দেশ খুঁজুন",
	"buy_country_united_states": "মার্কিন যুক্তরাষ্ট্র",
	"buy_country_australia": "অস্ট্রেলিয়া",
	"buy_country_austria": "অস্ট্রিয়া",
	"buy_country_belgium": "বেলজিয়াম",
	"buy_country_brazil": "ব্রাজিল",
	"buy_country_canada": "কানাডা",
	"buy_country_france": "ফ্রান্স",
	"buy_country_germany": "জার্মানি",
	"buy_country_ireland": "আয়ারল্যান্ড",
	"buy_country_italy": "ইতালি",
	"buy_country_netherlands": "নেদারল্যান্ডস",
	"buy_country_new_zealand": "নিউজিল্যান্ড",
	"buy_country_spain": "স্পেন",
	"buy_country_united_kingdom": "যুক্তরাজ্য",
	"buy_country_argentina": "আর্জেন্টিনা",
	"buy_country_chile": "চিলি",
	"buy_country_colombia": "কলম্বিয়া",
	"buy_country_costa_rica": "কোস্টা রিকা",
	"buy_country_czech_republic": "চেক প্রজাতন্ত্র",
	"buy_country_denmark": "ডেনমার্ক",
	"buy_country_el_salvador": "এল সালভাদর",
	"buy_country_estonia": "এস্তোনিয়া",
	"buy_country_finland": "ফিনল্যান্ড",
	"buy_country_greece": "গ্রীস",
	"buy_country_guatemala": "গুয়াতেমালা",
	"buy_country_hong_kong": "হংকং",
	"buy_country_hungary": "হাঙ্গেরি",
	"buy_country_iceland": "আইসল্যান্ড",
	"buy_country_india": "ভারত",
	"buy_country_israel": "ইসরায়েল",
	"buy_country_japan": "জাপান",
	"buy_country_latvia": "লাটভিয়া",
	"buy_country_lithuania": "লিথুয়ানিয়া",
	"buy_country_luxembourg": "লুক্সেমবার্গ",
	"buy_country_malta": "মাল্টা",
	"buy_country_mexico": "মেক্সিকো",
	"buy_country_norway": "নরওয়ে",
	"buy_country_panama": "পানামা",
	"buy_country_poland": "পোল্যান্ড",
	"buy_country_portugal": "পর্তুগাল",
	"buy_country_romania": "রোমানিয়া",
	"buy_country_singapore": "সিঙ্গাপুর",
	"buy_country_slovakia": "স্লোভাকিয়া",
	"buy_country_slovenia": "স্লোভেনিয়া",
	"buy_country_south_africa": "দক্ষিণ আফ্রিকা",
	"buy_country_south_korea": "দক্ষিণ কোরিয়া",
	"buy_country_sweden": "সুইডেন",
	"buy_country_switzerland": "সুইজারল্যান্ড",
	"buy_country_thailand": "থাইল্যান্ড",
	"buy_country_turkey": "তুরস্ক",
	"buy_country_ukraine": "ইউক্রেন",
	"buy_country_uruguay": "উরুগুয়ে",
	"buy_step_2_header": "ধাপ ২: আপনার পেমেন্ট পদ্ধতি বেছে নিন",
	"buy_step_2_description": "Bitcoin কেনার দুটি প্রধান উপায় আছে: ব্যাংক ট্রান্সফার বা নগদ। প্রতিটির আলাদা সুবিধা আছে।",
	"buy_method_bank_transfer": "ব্যাংক ট্রান্সফার",
	"buy_method_bank_fast": "দ্রুত ও সহজ",
	"buy_method_bank_less_private": "কম গোপনীয়",
	"buy_method_bank_description": "ব্যাংক ট্রান্সফার হলো Bitcoin কেনার সবচেয়ে সাধারণ উপায়। এগুলো দ্রুত, সুবিধাজনক এবং সাধারণত কম ফি থাকে।",
	"buy_method_choose_bank": "ব্যাংক ট্রান্সফার বেছে নিন",
	"buy_method_cash": "নগদ",
	"buy_method_cash_private": "আরও গোপনীয়",
	"buy_method_cash_limited": "সীমিত বিকল্প",
	"buy_method_cash_description": "নগদ কেনাকাটা আরও গোপনীয়তা দেয় কিন্তু কম বিকল্প আছে এবং কারো সাথে সামনাসামনি দেখা করা বা Bitcoin ATM ব্যবহার করার প্রয়োজন হতে পারে।",
	"buy_method_choose_cash": "নগদ বেছে নিন",
	"buy_step_3_header": "ধাপ ৩: কেনার বিকল্প",
	"buy_step_3_description": "আপনার দেশ এবং পেমেন্ট পদ্ধতির জন্য সেরা Bitcoin কেনার বিকল্পগুলো এখানে:",
	"buy_platform_recommended": "প্রস্তাবিত",
	"buy_platform_strike_description": "Strike হলো কম ফি এবং তাৎক্ষণিক লাইটনিং নেটওয়ার্ক সমর্থন সহ Bitcoin কেনার সবচেয়ে দ্রুত ও সহজ উপায়।",
	"buy_platform_swan_description": "Swan Bitcoin ডলার-কস্ট এভারেজিং এবং শিক্ষামূলক সম্পদ সহ শুধু-Bitcoin সেবায় বিশেষজ্ঞ।",
	"buy_platform_river_description": "River শিক্ষা এবং নিরাপত্তায় মনোযোগ দিয়ে Bitcoin কেনা, মাইনিং এবং কাস্টডি সেবা প্রদান করে।",
	"buy_platform_coinsquare_description": "Coinsquare হলো একটি কানাডীয় Bitcoin এক্সচেঞ্জ যেখানে শক্তিশালী নিয়ন্ত্রক সম্মতি এবং গ্রাহক সমর্থন আছে।",
	"buy_platform_kraken_description": "Kraken হলো একটি প্রতিষ্ঠিত Bitcoin এক্সচেঞ্জ যেখানে উন্নত ট্রেডিং বৈশিষ্ট্য এবং শক্তিশালী নিরাপত্তা আছে।",
	"buy_platform_atm_description": "Bitcoin ATM আপনাকে তাৎক্ষণিকভাবে নগদ দিয়ে Bitcoin কিনতে দেয়। Coin ATM Radar ব্যবহার করে আপনার কাছে একটি খুঁজুন।",
	"buy_platform_bisq_description": "Bisq হলো একটি বিকেন্দ্রীভূত পিয়ার-টু-পিয়ার এক্সচেঞ্জ যা KYC ছাড়া ব্যক্তিগত Bitcoin ট্রেডিং অনুমতি দেয়।",
	"buy_platform_feature_instant": "তাৎক্ষণিক কেনাকাটা",
	"buy_platform_feature_low_fees": "কম ফি",
	"buy_platform_feature_lightning": "লাইটনিং নেটওয়ার্ক",
	"buy_platform_feature_dca": "ডলার-কস্ট এভারেজিং",
	"buy_platform_feature_education": "শিক্ষামূলক সম্পদ",
	"buy_platform_feature_withdrawal": "সহজ উত্তোলন",
	"buy_platform_feature_mining": "Bitcoin মাইনিং",
	"buy_platform_feature_custody": "কাস্টডি সেবা",
	"buy_platform_feature_canadian": "কানাডা কেন্দ্রিক",
	"buy_platform_feature_regulated": "নিয়ন্ত্রিত এক্সচেঞ্জ",
	"buy_platform_feature_support": "গ্রাহক সমর্থন",
	"buy_platform_feature_established": "প্রতিষ্ঠিত প্ল্যাটফর্ম",
	"buy_platform_feature_security": "শক্তিশালী নিরাপত্তা",
	"buy_platform_feature_advanced": "উন্নত বৈশিষ্ট্য",
	"buy_platform_feature_cash": "নগদ কেনাকাটা",
	"buy_platform_feature_anonymous": "আরও বেনামী",
	"buy_platform_feature_p2p": "পিয়ার-টু-পিয়ার",
	"buy_platform_feature_private": "ব্যক্তিগত ট্রেডিং",
	"buy_platform_feature_decentralized": "বিকেন্দ্রীভূত",
	"buy_platform_relai_description": "Relai হলো একটি সুইস শুধু-Bitcoin অ্যাপ যেখানে স্ব-হেফাজত ওয়ালেট, অটো-ইনভেস্ট বৈশিষ্ট্য এবং ইউরোপীয় ব্যবহারকারীদের জন্য কম ফি আছে।",
	"buy_platform_feature_bitcoin_only": "শুধু Bitcoin",
	"buy_platform_feature_self_custody": "স্ব-হেফাজত ওয়ালেট",
	"buy_platform_feature_auto_invest": "অটো-ইনভেস্ট প্ল্যান",
	"buy_platform_feature_european": "ইউরোপ কেন্দ্রিক",
	"buy_step_4_header": "ধাপ ৪: আপনার BITCOIN নিরাপদে সংরক্ষণ করুন",
	"buy_step_4_c1": "Bitcoin কেনার পর, সবচেয়ে গুরুত্বপূর্ণ ধাপ হলো এটি আপনার নিজের ওয়ালেটে সরানো যেখানে আপনি প্রাইভেট কী নিয়ন্ত্রণ করেন।",
	"buy_step_4_c2": "এক্সচেঞ্জে Bitcoin রেখে দেওয়া ঝুঁকিপূর্ণ কারণ আপনি প্রকৃতপক্ষে Bitcoin-এর মালিক নন - এক্সচেঞ্জ মালিক।",
	"buy_step_4_c3": "আপনি যখন আপনার নিজের প্রাইভেট কী নিয়ন্ত্রণ করেন, আপনার কাছে আপনার Bitcoin-এর প্রকৃত মালিকানা থাকে এবং কেউ এটি আপনার কাছ থেকে নিতে পারে না।",
	"buy_step_4_c4": "আপনার প্রয়োজনের জন্য সঠিক Bitcoin ওয়ালেট কিভাবে বেছে নেবেন তা জানুন:",
	"buy_cta_wallets": "আমাদের Bitcoin ওয়ালেট গাইড দেখুন"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Bitcoin লাইটনিং ওয়ালেট গাইড",
	"lightning_description": "লাইটনিং ওয়ালেট আপনাকে আপনার ব্যক্তিগত সার্বভৌমত্ব বজায় রেখে দ্রুত এবং সস্তায় Bitcoin পাঠাতে সক্ষম করে।",
	"lightning_header": "লাইটনিং ওয়ালেট গাইড",
	"lightning_s1_c1": "লাইটনিং আপনাকে দ্রুত এবং সস্তায় Bitcoin পেমেন্ট পাঠাতে সক্ষম করে।",
	"lightning_s1_c2": "লাইটনিং ব্যবহার করার সাথে ট্রেড-অফ আছে জানা গুরুত্বপূর্ণ। দ্রুত, সস্তা Bitcoin পেমেন্টের বিনিময়ে, আপনি প্রায়ই কিছু নিরাপত্তা ত্যাগ করেন।",
	"lightning_s1_c3": "সাধারণত, লাইটনিং শুধুমাত্র অল্প পরিমাণ bitcoin-এর সাথে ব্যবহার করা উচিত। বড় পরিমাণ bitcoin সর্বদা একটি হার্ডওয়্যার ওয়ালেটে সংরক্ষণ করা উচিত।",
	"lightning_s1_c4": "আরও তথ্যের জন্য আমাদের হার্ডওয়্যার ওয়ালেট গাইড দেখুন।",
	"lightning_s1_c5": "সব লাইটনিং ওয়ালেট একই নয়। এই একটি সহজ প্রশ্ন জিজ্ঞাসা করে আপনি নির্ধারণ করতে পারেন কোন ওয়ালেটে আপনার জন্য সঠিক ট্রেড-অফ ভারসাম্য আছে:",
	"lightning_question_1": "আমার জন্য কোন ট্রেড-অফ ভারসাম্য সঠিক?",
	"lightning_s2_c1": "Bitcoin-এর একটি উদ্ভাবন হলো কাস্টোডিয়ান, যেমন ব্যাংকের উপর নির্ভর না করে এটি সংরক্ষণ করার ক্ষমতা। স্ব-হেফাজত ওয়ালেট Bitcoin-এর পূর্ণ শক্তি আনলক করে।",
	"lightning_s2_c2": "একটি স্ব-হেফাজত ওয়ালেটে, আপনিই একমাত্র যিনি আপনার অর্থ খরচ বা স্থানান্তর করতে পারেন। কেউ আপনাকে থামাতে, সেন্সর করতে বা চুরি করতে পারে না যখন আপনি স্ব-হেফাজত ওয়ালেট ব্যবহার করেন। এগুলোকে নন-কাস্টোডিয়াল ওয়ালেটও বলা হয়।",
	"lightning_s2_c3": "লাইটনিং ব্যবহারের সবচেয়ে সার্বভৌম উপায় হলো আপনার নিজের নোড চালানো।",
	"lightning_s2_c4": "এই গাইড সহজ লাইটনিং ওয়ালেটের উপর কেন্দ্রীভূত যেগুলোর জন্য আপনার নিজের নোড প্রয়োজন নেই।",
	"lightning_s2_c5": "জানা গুরুত্বপূর্ণ যে এমনকি একটি নন-কাস্টোডিয়াল লাইটনিং ওয়ালেট ব্যবহার করেও, আপনি এখনও ওয়ালেট নির্মাতাকে বিশ্বাস করছেন যে তারা একটি ক্ষতিকর অ্যাপ আপডেট পুশ করবে না এবং আপনার তহবিল চুরি করবে না।",
	"lightning_s3_c1": "কাস্টোডিয়াল ওয়ালেট হলো সেই ওয়ালেট যেখানে আপনি আপনার অর্থের নিয়ন্ত্রণে নন।",
	"lightning_s3_c2": "এই ওয়ালেটগুলো ব্যাংকিং ব্যবস্থার মতো যেখানে আপনাকে আপনার অর্থে প্রবেশের জন্য তৃতীয় পক্ষকে বিশ্বাস করতে হয়। আপনার Bitcoin যদি এক্সচেঞ্জে থাকে, আপনি কাস্টোডিয়াল ওয়ালেট ব্যবহার করছেন।",
	"lightning_s3_c3": "কাস্টোডিয়াল ওয়ালেট সুবিধাজনক মনে হতে পারে, কিন্তু কাস্টোডিয়ানের কাছে যেকোনো সময় সমস্ত ব্যবহারকারীর তহবিল চুরি করার প্রযুক্তিগত ক্ষমতা আছে।",
	"lightning_s3_c4": "কিছু মানুষ তাদের ব্যবহারের সহজতার কারণে অল্প পরিমাণ bitcoin-এর জন্য কাস্টোডিয়াল লাইটনিং ওয়ালেট পছন্দ করে। শুধু মনে রাখবেন: আপনার কী নয়, আপনার কয়েন নয়!",
	"lightning_question_2": "আপনার ওয়ালেট বেছে নিন",
	"lightning_s4_c1": "এই সব মাথায় রেখে, আপনি এখন আপনার জন্য সঠিক ট্রেড-অফ ভারসাম্য সহ লাইটনিং ওয়ালেট বেছে নিতে পারেন।",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "অনেক বৈশিষ্ট্য",
	"lightning_mobile_app": "মোবাইল অ্যাপ",
	"lightning_free": "১০০% বিনামূল্যে",
	"lightning_merchants": "মার্চেন্টদের জন্য দুর্দান্ত",
	"lightning_starter": "দুর্দান্ত স্টার্টার ওয়ালেট",
	"lightning_browser": "ব্রাউজার ভিত্তিক",
	"lightning_custodial": "সম্পূর্ণ কাস্টোডিয়াল ওয়ালেট",
	"lightning_cta_hardware": "আমাদের Bitcoin হার্ডওয়্যার ওয়ালেট গাইড খুঁজছেন?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "bitcoin.rocks থেকে বিনামূল্যে Bitcoin স্টিকার",
	"stickers_description": "আপনার চারপাশের মানুষদের অরেঞ্জ পিল করতে জনসমক্ষে একটি bitcoin স্টিকার লাগান।",
	"stickers_header": "বিনামূল্যে BITCOIN স্টিকার",
	"stickers_choose_header": "আপনার স্টিকার প্যাক বেছে নিন",
	"stickers_choose_c1": "আমাদের লক্ষ্য হলো জনসমক্ষে Bitcoin স্টিকার লাগিয়ে আরও বেশি মানুষকে অরেঞ্জ পিল করতে আপনাকে সাহায্য করা। আমাদের সব স্টিকারে QR কোড আছে যা শিক্ষামূলক পেজে লিংক করে",
	"stickers_choose_c2": "Bitcoin",
	"stickers_choose_c3": "মুদ্রাস্ফীতি",
	"stickers_choose_c4": "নিচে আপনার স্টিকার প্যাক বেছে নিন",
	"stickers_text_pack": "টেক্সট প্যাক",
	"stickers_signs_pack": "সাইন্স প্যাক",
	"stickers_instructions_1": "আপনার মেইলিং ঠিকানা লিখুন এবং আমরা আপনাকে মেইলে একটি বিনামূল্যে Bitcoin স্টিকার প্যাক পাঠাবো! আপনার স্টিকার একটি সাদা খামে পাঠানো হবে।",
	"stickers_instructions_2": "আপনার বিনামূল্যে স্টিকার পাঠানোর পর ঠিকানার তথ্য মুছে ফেলা হয়।",
	"stickers_share_header": "আপনার স্টিকার স্পট শেয়ার করুন",
	"stickers_share_c1": "Nostr-এ আমাদের সাথে আপনার স্টিকার স্পট শেয়ার করুন এবং অন্যরা কোথায় তাদের স্টিকার লাগাচ্ছে দেখুন।",
	"stickers_btn_share_on_nostr": "NOSTR-এ শেয়ার করুন",
	"stickers_btn_what_is_nostr": "NOSTR কী?",
	"stickers_flyers_link_before": "আপনি যখন এই কাজে আছেন, আরও বেশি মানুষকে অরেঞ্জ পিল করতে আপনার নিজের ",
	"stickers_flyers_link_text": "Bitcoin ফ্লায়ার",
	"stickers_flyers_link_after": " প্রিন্ট করুন ও পোস্ট করুন।",
	"stickers_country_global_print": "বিশ্বব্যাপী — আমার নিজের স্টিকার প্রিন্ট করুন",
	"stickers_country_global_order": "বিশ্বব্যাপী — বাল্কে অর্ডার করুন",
	"placeholder_name_optional": "নাম (ঐচ্ছিক)",
	"placeholder_address_line_1": "ঠিকানা লাইন ১",
	"placeholder_address_line_2": "ঠিকানা লাইন ২ (ঐচ্ছিক)",
	"placeholder_city": "শহর",
	"placeholder_state": "রাজ্য",
	"placeholder_province": "প্রদেশ",
	"placeholder_zip_code": "জিপ কোড",
	"placeholder_postal_code": "পোস্টাল কোড",
	"placeholder_language": "ভাষা",
	"placeholder_which_stickers": "কোন স্টিকার?",
	"placeholder_email_optional": "বিজ্ঞপ্তি পেতে আপনার ইমেইল দিন (ঐচ্ছিক)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "bitcoin.rocks থেকে বিনামূল্যে Bitcoin পোস্টকার্ড",
	"postcards_description": "একটি বিনামূল্যে Bitcoin পোস্টকার্ড প্যাক পান এবং আপনার পরিচিত কারো সাথে Bitcoin শেয়ার করুন।",
	"postcards_header": "পোস্টকার্ড প্রোগ্রাম বন্ধ",
	"postcards_program_closed_message": "আমাদের বিনামূল্যে Bitcoin পোস্টকার্ড প্রোগ্রাম শেষ হয়েছে। মেইলের মাধ্যমে Bitcoin শিক্ষা ছড়াতে অংশগ্রহণকারী সবাইকে ধন্যবাদ!",
	"postcards_sticker_alternative_header": "পরিবর্তে বিনামূল্যে BITCOIN স্টিকার পান",
	"postcards_sticker_alternative_message": "আমাদের বিনামূল্যে স্টিকার প্রোগ্রামের সাথে Bitcoin সচেতনতা ছড়াতে থাকুন! আমাদের Bitcoin স্টিকার জনসমক্ষে শেয়ার করার জন্য নিখুঁত এবং শিক্ষামূলক বিষয়বস্তুর সাথে সংযুক্ত QR কোড আছে।",
	"postcards_sticker_cta": "বিনামূল্যে স্টিকার পান",
	"postcards_step_2": "পোস্টকার্ড কেমন দেখতে ছিল",
	"postcards_instructions_4": "আমরা এই পোস্টকার্ডগুলো তৈরি করেছি যাতে আপনার পরিচিত কাউকে Bitcoin-এর সাথে পরিচয় করিয়ে দেওয়া সহজ হয়! শুধু একটি ঠিকানা এবং একটি স্ট্যাম্প যোগ করুন এবং আপনার পোস্টকার্ড মেইলে ফেলুন।",
	"postcards_instructions_5": "আমাদের লক্ষ্য হলো Bitcoin গ্রহণকে ত্বরান্বিত করা। আপনি বিনামূল্যে স্টিকার পেয়ে এবং জনসমক্ষে লাগিয়ে সাহায্য করতে পারেন!",
	"postcards_instructions_6": "আমরা সবাই কিছু মানুষকে চিনি যারা Bitcoin সম্পর্কে আরও জানলে উপকৃত হতে পারে। আজই তাদের সাথে Bitcoin স্টিকার শেয়ার করুন!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "আমেরিকা জুড়ে এই Bitcoin সাইনবোর্ড লাগাতে আমাদের সাহায্য করুন!",
	"signs_title": "bitcoin.rocks থেকে বিনামূল্যে Bitcoin সাইনবোর্ড",
	"signs_choose_header": "আমেরিকা জুড়ে এই BITCOIN সাইনবোর্ড লাগাতে সাহায্য করার জন্য ধন্যবাদ!",
	"signs_choose_c1": "আমাদের সাইনবোর্ড এখন সম্পূর্ণ শেষ! আমাদের লক্ষ্য হলো শিক্ষার মাধ্যমে Bitcoin গ্রহণকে ত্বরান্বিত করা।",
	"signs_choose_c2": "আপনাদের অনেকে জনসমক্ষে এই বিনামূল্যে Bitcoin সাইনবোর্ড লাগিয়ে সাহায্য করেছেন। আমাদের সব সাইনবোর্ডে QR কোড আছে যা একটি শিক্ষামূলক পেজে লিংক করে",
	"signs_choose_c3": "মুদ্রাস্ফীতি",
	"signs_choose_c4": "আমাদের দুর্দান্ত সম্প্রদায়ের কল্যাণে, আমরা হাজার হাজার মানুষের কাছে পৌঁছেছি এবং তাদের Bitcoin র‍্যাবিট হোলে প্রথম পদক্ষেপ নিতে সাহায্য করেছি।",
	"signs_share_header": "আপনার সাইন স্পট শেয়ার করুন",
	"signs_share_c1": "Nostr-এ আমাদের সাথে আপনার সাইন স্পটের ছবি শেয়ার করুন এবং অন্যরা কোথায় তাদের সাইনবোর্ড লাগাচ্ছে দেখুন।",
	"signs_btn_share_on_nostr": "NOSTR-এ শেয়ার করুন",
	"signs_btn_what_is_nostr": "NOSTR কী?",
	"signs_instructions_1": "আপনার মেইলিং ঠিকানা লিখুন এবং আমরা আপনাকে মেইলে ১০টি Bitcoin সাইনবোর্ডের একটি বাক্স পাঠাবো!",
	"signs_instructions_2": "আপনার বিনামূল্যে সাইনবোর্ড পাঠানোর পর ঠিকানার তথ্য মুছে ফেলা হয়।"
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "bitcoin.rocks থেকে বিনামূল্যে Bitcoin ফ্লায়ার",
	"flyers_description": "বাড়িতে একটি Bitcoin ফ্লায়ার প্রিন্ট করুন এবং আপনার চারপাশের মানুষদের অরেঞ্জ পিল করতে জনসমক্ষে লাগান।",
	"flyers_header_1": "প্রিন্ট করুন ও পোস্ট করুন",
	"flyers_header_2": "BITCOIN ফ্লায়ার",
	"flyers_intro_header": "কিভাবে এই BITCOIN ফ্লায়ার প্রিন্ট করুন ও পোস্ট করুন",
	"flyers_intro_c1": "আমাদের লক্ষ্য হলো জনসমক্ষে Bitcoin ফ্লায়ার লাগিয়ে আরও বেশি মানুষকে অরেঞ্জ পিল করতে আপনাকে সাহায্য করা। এই ফ্লায়ারে একটি QR কোড আছে যা আমাদের",
	"flyers_intro_c2": "শিক্ষামূলক Bitcoin ওয়েবসাইটে লিংক করে।",
	"flyers_intro_c3": "মুদ্রাস্ফীতি",
	"flyers_intro_c4": "বাড়িতে বা প্রিন্ট শপে এই ফ্লায়ার প্রিন্ট করুন। তারপর, শহরের বুলেটিন বোর্ড, টেলিফোন পোল এবং অন্যান্য জনসমক্ষের জায়গায় পোস্ট করুন যেখানে মানুষ এটি দেখতে পারে এবং Bitcoin সম্পর্কে শিখতে পারে।",
	"flyers_intro_c5": "আপনি যখন এই কাজে আছেন, আমাদের",
	"flyers_intro_c6": "বিনামূল্যে Bitcoin স্টিকার",
	"flyers_intro_c7": "এর একটি প্যাক অনুরোধ করুন আরও বেশি মানুষকে অরেঞ্জ পিল করতে।",
	"flyers_btn_download": "ফ্লায়ার ডাউনলোড করুন",
	"flyers_btn_print": "ফ্লায়ার প্রিন্ট করুন",
	"flyers_share_header": "আপনার ফ্লায়ার স্পট শেয়ার করুন",
	"flyers_share_c1": "Nostr-এ আমাদের সাথে আপনার ফ্লায়ার স্পট শেয়ার করুন এবং অন্যরা কোথায় তাদের ফ্লায়ার লাগাচ্ছে দেখুন।",
	"flyers_btn_share_on_nostr": "NOSTR-এ শেয়ার করুন",
	"flyers_btn_what_is_nostr": "NOSTR কী?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "জড়িত হন এবং Bitcoin ছড়াতে সাহায্য করুন",
	"get_involved_description": "আমাদের বিনামূল্যে সম্পদ Bitcoin গ্রহণ ছড়ানো সহজ করে।",
	"get_involved_header": "জড়িত হন",
	"get_involved_header_2": "BITCOIN ছড়ান",
	"get_involved_intro_1": "আমাদের বিশ্বের বর্তমান অবস্থায় বেঁচে থাকা হতাশাজনক হতে পারে।",
	"get_involved_intro_2": "আমাদের অর্থ ভাঙা। ফলস্বরূপ, সমাজের মৌলিক অংশগুলোও ভাঙা।",
	"get_involved_intro_3": "আপনি যদি ইতিমধ্যে Bitcoin-এ থাকেন, আপনি সেই আশার অনুভূতি জানেন যা Bitcoin আনতে পারে। উন্নত অর্থ দ্বারা সম্ভব একটি উজ্জ্বল ভবিষ্যতের আশা।",
	"get_involved_intro_4": "কিন্তু আপনার চারপাশের অনেক মানুষ Bitcoin সম্পর্কে জানে না। তারা আপনার মতো একই ভাঙা বিশ্বে বাস করছে, কিন্তু অন্ধকারের মধ্য দিয়ে তাদের সাহায্য করার জন্য আশার বীকন ছাড়া।",
	"get_involved_intro_5": "কিন্তু আপনি এটি পরিবর্তন করতে সাহায্য করতে পারেন। আমরা আপনার চারপাশের মানুষদের কাছে Bitcoin যে আশা আনে তা ছড়ানো সহজ করতে বেশ কিছু বিনামূল্যে সম্পদ তৈরি করেছি।",
	"get_involved_sticker_header": "জনসমক্ষে একটি স্টিকার লাগান",
	"get_involved_sticker_content_1": "আপনি কারো সাথে কথা না বলেই আপনার চারপাশের মানুষদের Bitcoin সম্পর্কে শিক্ষিত করতে সাহায্য করতে পারেন। কেবল আমাদের বিনামূল্যে Bitcoin স্টিকারগুলোর একটি জনসমক্ষে লাগান।",
	"get_involved_sticker_content_2": "প্রতি মাসে শত শত মানুষ এই স্টিকারের QR কোড স্ক্যান করে। মুদ্রাস্ফীতি স্টিকারগুলো একটি পেজে লিংক করে",
	"get_involved_sticker_content_3": "মুদ্রাস্ফীতির সমাধান হিসেবে Bitcoin।",
	"get_involved_sticker_content_4": "অন্য স্টিকারগুলো আমাদের শিক্ষামূলক হোম পেজে লিংক করে যা মানুষকে দেখায় কিভাবে",
	"get_involved_sticker_content_5": "Bitcoin একটি উন্নত বিশ্ব গড়ে তুলছে।",
	"get_involved_sticker_content_6": "আপনার সম্প্রদায়ে মানুষ যেখানে দেখতে পাবে সেসব জায়গায় এই স্টিকার লাগিয়ে, আপনি আপনার চারপাশের মানুষদের Bitcoin র‍্যাবিট হোলে প্রথম পদক্ষেপ নিতে সাহায্য করতে পারেন।",
	"get_involved_request_a": "একটি অনুরোধ করুন",
	"get_involved_sticker_pack": "স্টিকার প্যাক",
	"get_involved_postcard_header": "একটি পোস্টকার্ড পাঠান",
	"get_involved_postcard_content_1": "আপনি আপনার পরিচিত কাউকে আমাদের বিনামূল্যে পোস্টকার্ডগুলোর একটি পাঠিয়ে Bitcoin-এর আশা ছড়াতে সাহায্য করতে পারেন।",
	"get_involved_postcard_content_2": "প্রতিটি পোস্টকার্ডের পেছনে Bitcoin সম্পর্কে একটি আকর্ষণীয় ব্লার্ব এবং আরও জানতে একটি QR কোড আছে।",
	"get_involved_postcard_content_3": "কাউকে একটি Bitcoin পোস্টকার্ড পাঠিয়ে, আপনি তাদের Bitcoin-কে নতুন দৃষ্টিভঙ্গিতে দেখতে সাহায্য করতে পারেন।",
	"get_involved_postcard_pack": "পোস্টকার্ড প্যাক",
	"get_involved_business_header": "একটি ব্যবসাকে অনবোর্ড করুন",
	"get_involved_business_content_1": "Bitcoin সার্কুলার ইকোনমি গড়ে তুলতে চান? আমাদের Bitcoin ব্যবসায়িক কিট একটি ব্যবসাকে Bitcoin পেমেন্ট গ্রহণের বিষয়ে কথা বলা সহজ করে।",
	"get_involved_business_content_2": "প্রতিটি ব্যবসায়িক কিটে ফ্লায়ার অন্তর্ভুক্ত যা Bitcoin পেমেন্ট গ্রহণের সুবিধাগুলো তুলে ধরে। প্রতিটি ফ্লায়ার বিভিন্ন",
	"get_involved_business_content_3": "বিনামূল্যে Bitcoin ব্যবসায়িক সম্পদে লিংক করে।",
	"get_involved_business_kit": "ব্যবসায়িক কিট"
});

console.log('\nDone creating content files for Bengali (bn).');
