/**
 * Creates Burmese (my) common.json translation file (~180+ keys).
 */
const fs = require('fs');
const path = require('path');
const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'my';
const today = '2026-04-07';

const data = {
	"@metadata": { "authors": ["Satoshi"], "last-updated": today, "locale": lang },
	"common_footer_mission_1": "bitcoin.rocks ၏ ရည်ရွယ်ချက်မှာ ပညာရေးမှတစ်ဆင့် bitcoin လက်ခံသုံးစွဲမှုကို အရှိန်မြှင့်ရန်ဖြစ်ပါသည်။",
	"common_footer_mission_2": "ဤ open-source ပရောဂျက်ကို ဘယ်လို ပံ့ပိုးကူညီရမလဲ သိရှိပါ။",
	"common_footer_follow_first_half": "Nostr client မည်သည့်တစ်ခုတွင်မဆို",
	"common_footer_follow_second_half": "ရှာဖွေ၍ ကျွန်ုပ်တို့ကို follow လုပ်ပါ။",
	"common_footer_what_is_nostr": "Nostr ဆိုတာ ဘာလဲ?",
	"common_footer_about": "အကြောင်း",
	"common_footer_email_us": "အီးမေးလ်ပို့ပါ:",
	"common_cta_section_get_started": "စတင်ပါ",
	"common_cta_section_with_bitcoin": "BITCOIN ဖြင့်",
	"common_cta_section_title_1": "Bitcoin ၏ အခြေခံများ သိရှိပါ",
	"common_cta_section_title_1_alt": "Bitcoin အကြောင်း ပိုမိုသိရှိပါ",
	"common_cta_section_title_2": "သင့်ပထမဆုံး Bitcoin ပိုက်ဆံအိတ် ရယူပါ",
	"common_cta_section_title_3": "Bitcoin ဘယ်လိုဝယ်မလဲ",
	"common_cta_link_type_email": "အီးမေးလ်",
	"common_cta_link_type_guide": "လမ်းညွှန်",
	"common_cta_link_type_website": "ဝက်ဘ်ဆိုက်",
	"common_cta_author_21_days_of_bitcoin": "Bitcoin ရက် ၂၁ ရက်",
	"common_cta_author_bitcoin_rocks": "bitcoin.rocks",
	"common_cta_author_strike": "Strike",
	"common_what_is_bitcoin": "BITCOIN ဆိုတာ ဘာလဲ?",
	"common_what_is_bitcoin_content_1": "Bitcoin သည် အရာနှစ်ခုဖြစ်ပါသည်: ဒစ်ဂျစ်တယ်ငွေနှင့် ငွေပေးချေမှုကွန်ရက်တစ်ခု။ Bitcoin ကွန်ရက် (ငွေပေးချေမှုကွန်ရက်) ကို အသုံးပြု၍ အခြားသူများထံ Bitcoin (ဒစ်ဂျစ်တယ်ငွေ) တိုက်ရိုက်ပို့နိုင်ပါသည်။",
	"common_what_is_bitcoin_content_2": "Bitcoin သည် တန်ဖိုးကို သိမ်းဆည်းပြီး အရောင်းအဝယ်ပြုရန် စွန့်စားသော နည်းလမ်းအသစ်ဖြစ်ပါသည်။ ပုံမှန်ငွေကြေးကွန်ရက်များနှင့် မတူဘဲ Bitcoin ကွန်ရက်သည် ဗဟိုအာဏာပိုင် သို့မဟုတ် ယုံကြည်ရသော စီမံခန့်ခွဲသူ မလိုဘဲ အလုပ်လုပ်နိုင်ပါသည်။ ၎င်းသည် Bitcoin ကို ပထမဆုံး ဖွင့်ပြီး နယ်နိမိတ်မရှိသော ငွေကြေး ဖြစ်စေပါသည်။",
	"common_what_is_bitcoin_content_3": "Bitcoin သည် သင့်ဓနဥစ္စာအပေါ် အပြည့်အဝပိုင်ဆိုင်ခွင့်ပေးသော ဒစ်ဂျစ်တယ်ငွေဖြစ်ပါသည်။ လူသားသမိုင်းတွင် ပထမဆုံးအကြိမ် လူတိုင်းက စစ်မှန်စွာ ရှားပါးပြီး အသုံးပြုရန် ခွင့်ပြုချက်မလိုဘဲ မှန်ကန်စွာ သိမ်းဆည်းပါက သိမ်းယူ၍မရသော ပိုင်ဆိုင်မှုတစ်ခု ပိုင်ဆိုင်နိုင်ပါသည်။",
	"common_what_is_bitcoin_content_4": "Bitcoin ကို ကမ္ဘာ့မည်သည့်နေရာသို့မဆို လျင်မြန်ပြီး ဈေးသက်သာစွာ ပို့နိုင်ပါသည်။ ဘဏ်ကဲ့သို့ တတိယပါတီ ငွေလွှဲသူ မလိုအပ်ပါ။",
	"common_what_is_bitcoin_content_5": "Bitcoin သည် အစိုးရက ခိုးယူခြင်း သို့မဟုတ် ငွေပုံနှိပ်ခြင်းဖြင့် တန်ဖိုးလျော့ကျစေခြင်းကို စိတ်မပူဘဲ ဓနဥစ္စာကို လုံခြုံစွာ သိမ်းဆည်းနိုင်စေပါသည်။",
	"common_what_is_bitcoin_content_6": "ကမ္ဘာတစ်ဝှမ်းရှိ အစိုးရများ စက္ကူငွေ ပိုပုံနှိပ်နိုင်သော်လည်း မည်သူမျှ bitcoin ပိုပုံနှိပ်၍ မရပါ။",
	"common_what_is_bitcoin_content_7": "Bitcoin ၏ စွမ်းအားအပြည့်အဝ ရရှိရန် သင့် Bitcoin ကို လွယ်ကူစွာ ကိုယ်ပိုင်ထိန်းသိမ်းနိုင်ပါသည်။",
	"common_what_is_bitcoin_content_8": "အက်ပ်တစ်ခု ဒေါင်းလုဒ်လုပ်နိုင်ပါက Bitcoin ကို ကိုယ်ပိုင်ထိန်းသိမ်းပြီး အခြားသူတစ်ဦးကိုမျှ မမှီခိုဘဲ ဓနဥစ္စာ သိမ်းဆည်းနိုင်ပါသည်။",
	"common_what_is_bitcoin_content_9": "Bitcoin သည် ပိုကောင်းသော ငွေကြေးဖြစ်ပါသည်။",
	"common_bitcoin_volatile": "BITCOIN သည် မတည်ငြိမ်ကြောင်း ကြားဖူးပါသည်။ လုံခြုံပါသလား?",
	"common_bitcoin_volatile_content_1": "ရေတိုတွင် Bitcoin ၏ ငွေလဲနှုန်းသည် အတက်အကျ ဖြစ်တတ်ပါသည်။ ၎င်းကို မတည်ငြိမ်မှုဟု ခေါ်ပါသည်။",
	"common_bitcoin_volatile_content_2": "သို့သော် နေ့စဉ် မြင်ရသော မတည်ငြိမ်မှုသည် ရေရှည်တွင် 'ပျောက်ကွယ်' သွားပါသည်။",
	"common_bitcoin_volatile_content_3": "Bitcoin သည် အချိန်ကြာလာသည်နှင့် မတည်ငြိမ်မှု နည်းလာပါသည်။ လူပိုများများ Bitcoin ကို ရေရှည်စုဆောင်းငွေအကောင့်အဖြစ် အသုံးပြုသည်နှင့်အမျှ တန်ဖိုး ပိုတည်ငြိမ်လာပါသည်။",
	"common_bitcoin_volatile_content_4": "လူအများအပြားက မတည်ငြိမ်မှုအန္တရာယ် လျှော့ချပြီး အချိန်ကြာလာသည်နှင့် ဝယ်နိုင်စွမ်း ကာကွယ်ရန် နှစ်ပေါင်းများစွာ Bitcoin တွင် တန်ဖိုးသိုလှောင်ရန် ရွေးချယ်ကြပါသည်။",
	"common_bitcoin_volatile_content_5": "ဗင်နီဇွဲလား၊ ဆူဒန်၊ လက်ဘနွန်၊ ဆီးရီးယား၊ အာဂျင်တီးနား၊ တူရကီ၊ ဘရာဇီး နှင့် အခြားနိုင်ငံများစွာကဲ့သို့ အချို့နိုင်ငံများတွင် ဒေသတွင်းငွေကြေးတန်ဖိုး အလျင်အမြန် ငွေကြေးဖောင်းပွသောကြောင့် Bitcoin ကို ငွေစုဆောင်းရန် ပိုတည်ငြိမ်သော နည်းလမ်းအဖြစ် သတ်မှတ်ကြပါသည်။",
	"common_bitcoin_afford": "BITCOIN တစ်ခုလုံး ဝယ်နိုင်စွမ်း မရှိပါ",
	"common_bitcoin_afford_content_1": "ဒေါ်လာ ၁ တွင် ဆင့် ၁၀၀ ပါသကဲ့သို့ bitcoin ၁ တွင် sats ၁၀၀,၀၀၀,၀၀၀ (သန်း ၁၀၀) ပါဝင်ပါသည်။",
	"common_bitcoin_afford_content_2": "bitcoin တစ်ခုလုံး ပိုင်ဆိုင်ရန် မလိုပါ။ လူအများစုက sats များသာ ပိုင်ဆိုင်ကြပါသည်။ Sats များသည် bitcoin ၏ အပိုင်းအစများဖြစ်ပါသည်။ ဥပမာ bitcoin ၁ ခု $၁၀၀,၀၀၀ ဖြစ်ပါက $၁ ဖြင့် sats ၁,၀၀၀ ဝယ်နိုင်ပါသည်!",
	"common_bitcoin_hacked": "BITCOIN ကို HACK ခံဖူးပါသလား?",
	"common_bitcoin_hacked_content_1": "အွန်လိုင်း သို့မဟုတ် သတင်းများတွင် 'Bitcoin hack' အကြောင်း ကြားဖူးနိုင်ပါသည်။ လူအများစုက ဤဆောင်းပါးများကို ဖတ်ပြီး Bitcoin ကွန်ရက် hack ခံရသည်ဟု ယုံကြည်ကြပါသည်။ သို့သော် Bitcoin ကွန်ရက်ကို ဘယ်တော့မှ hack မခံခဲ့ရပါ။",
	"common_bitcoin_hacked_content_2": "Bitcoin ကွန်ရက်ဆိုတာ ဘာလဲ? Bitcoin ကွန်ရက်ကို ရထားလမ်းကြောင်းအဖြစ် စဉ်းစားပါ။ Bitcoin ကွန်ရက်၏ ရထားလမ်းကြောင်းပေါ်တွင် စီးနေသော ရထားများသည် Bitcoin အရောင်းအဝယ်များ ဖြစ်ပါသည်။",
	"common_bitcoin_hacked_content_3": "သတင်းတွင် Bitcoin hack ဖတ်ရသောအခါ FTX ကဲ့သို့ ထိန်းသိမ်းသူ hack ခံရခြင်း သို့မဟုတ် ဒေဝါလီခံခြင်းအကြောင်း ဖတ်နေခြင်းဖြစ်ပါသည်။",
	"common_bitcoin_hacked_content_4": "ထိန်းသိမ်းသူများသည် သင့်အတွက် bitcoin ထိန်းသိမ်းပေးသော ကုမ္ပဏီများဖြစ်ပါသည်။ သို့သော် ကုမ္ပဏီက မှားယွင်းစွာ စီမံခန့်ခွဲ၊ ခိုးယူ သို့မဟုတ် ပိတ်သိမ်းသောအခါ bitcoin ဆုံးရှုံးနိုင်သည့် အန္တရာယ်ရှိပါသည်။",
	"common_bitcoin_hacked_content_5": "ဤအရာသည် FTX နှင့် မကြာသေးမီ ဖြစ်ခဲ့ပါသည်။",
	"common_bitcoin_hacked_content_6": "FTX ကို ယုံကြည်သူတိုင်း ၎င်းတို့၏ bitcoin ဆုံးရှုံးခဲ့ပါသည်။ ကိုယ်ပိုင်ထိန်းသိမ်းခြင်းတွင် bitcoin ထားသူတိုင်း FTX ကြောင့် လုံးဝ ထိခိုက်ခြင်းမရှိပါ။ ၎င်းသည် ကိုယ်ပိုင်ထိန်းသိမ်းခြင်းတွင် bitcoin ၏ စွမ်းအားဖြစ်ပါသည်: သင့်ငွေ၏ စစ်မှန်သော ထိန်းချုပ်ခွင့်။",
	"common_bitcoin_hacked_content_7": "exchange သို့မဟုတ် ETF ကဲ့သို့ wrapper တွင် bitcoin မထားဘဲ လွတ်လပ်မှု အကျိုးကျေးဇူးအားလုံးအတွက် သင့်ကိုယ်ပိုင်ပိုက်ဆံအိတ်တွင် ထိန်းသိမ်းပါ။",
	"common_bitcoin_hacked_content_8": "bitcoin ကို ကိုယ်ပိုင်ထိန်းသိမ်းသောအခါ Bitcoin ကွန်ရက်က သင့်ငွေကို ကာကွယ်ပေးပါသည်။ ၎င်းသည် ကမ္ဘာ့အလုံခြုံဆုံး ငွေကြေးကွန်ရက်ဖြစ်ပါသည်။",
	"common_bitcoin_hacked_content_9": "ကိုယ်ပိုင်ထိန်းသိမ်းခြင်းတွင် FTX မှ Sam သင့် bitcoin ခိုးယူ၍ မရပါ။",
	"common_bitcoin_hacked_content_10": "အစိုးရက bitcoin ပိုပုံနှိပ်ပြီး ငွေကြေးဖောင်းပွမှု ဖြစ်စေ၍မရပါ။",
	"common_bitcoin_hacked_content_11": "ကိုယ်ပိုင်ထိန်းသိမ်းခြင်းတွင် Bitcoin သည် Bitcoin ကွန်ရက်၏ စွမ်းအားကြောင့် သင့်ငွေဖြစ်ပါသည်။",
	"common_bitcoin_energy": "BITCOIN ဘာကြောင့် စွမ်းအင်သုံးသလဲ?",
	"common_bitcoin_energy_content_1": "Bitcoin သည် ကွန်ရက်ကို လုံခြုံစေပြီး သင့်ငွေကို ကာကွယ်ရန် စွမ်းအင်သုံးပါသည်။",
	"common_bitcoin_energy_content_2": "Bitcoin သည် သိသာသော စွမ်းအင်ပမာဏ အသုံးပြုပြီး ၎င်းသည် အကြောင်းရင်းများစွာကြောင့် ကောင်းမွန်သော အရာဖြစ်ပါသည်။",
	"common_bitcoin_energy_list_1": "Bitcoin တွင် ဘဏ်ပြေးခြင်း မရှိပါ။",
	"common_bitcoin_energy_list_2": "Bitcoin သည် bitcoin mining ဖြင့် စွမ်းအင်ဂရစ်များကို တည်ငြိမ်စေပါသည်။",
	"common_bitcoin_energy_list_3": "Bitcoin သည် ရေနံတူးဖော်မှုမှ ထုတ်လွှတ်မှုကို လျှော့ချပါသည်။",
	"common_bitcoin_energy_list_4": "Bitcoin သည် အမေရိကန်တို့ ခရစ္စမတ်မီးများအတွက် နှစ်စဉ်သုံးသည့် စွမ်းအင်ထက် နည်းပါသည်။",
	"common_bitcoin_energy_list_5": "Bitcoin သည် ကမ္ဘာ့အစိမ်းရောင်ဆုံး လုပ်ငန်းဖြစ်ပါသည်!",
	"common_cic_intro_1": "လူအများအပြားက ပေါင်းစပ်အတိုးအကြောင်း သိကြသော်လည်း ပေါင်းစပ်ငွေကြေးဖောင်းပွမှုအကြောင်း လူနည်းစုသာ သိကြပါသည်။",
	"common_cic_intro_2": "ကျွန်ုပ်တို့၏ ပေါင်းစပ်ငွေကြေးဖောင်းပွမှု ဂဏန်းတွက်စက်ဖြင့် အချိန်ကြာလာသည်နှင့် ဝယ်နိုင်စွမ်း ထိန်းသိမ်းရန် သင့်လစာ ဘယ်လောက်တိုးရမလဲ လွယ်ကူစွာ တွက်ချက်နိုင်ပါသည်။",
	"common_cic_intro_3": "သင့်လက်ရှိလစာ၊ ငွေကြေးဖောင်းပွနှုန်းနှင့် တွက်ချက်လိုသော နှစ်အရေအတွက်ကို ထည့်ရုံဖြင့် ငွေကြေးဖောင်းပွမှုနှင့် ရင်ဘောင်တန်းရန် သင့်လစာ ဘယ်လောက်ဖြစ်ရမည်ကို ဂဏန်းတွက်စက်က ပြပေးပါမည်။",
	"common_current_salary": "လက်ရှိလစာ",
	"common_inflation_rate": "ငွေကြေးဖောင်းပွနှုန်း",
	"common_year": "နှစ်",
	"common_years": "နှစ်များ",
	"common_result_starting_message": "အထက်ပါဖောင် ဖြည့်ပြီး တွက်ချက် ကို နှိပ်ပါ။",
	"common_error_message": "အမှား: ဖောင်ကွက်လပ် ၃ ခုလုံး ဖြည့်ပါ။",
	"common_result_message_1": "ငွေကြေးဖောင်းပွနှုန်း",
	"common_result_message_2": "သင့်",
	"common_result_message_3": "လစာသည် တိုးရပါမည်",
	"common_result_message_in": "အတွင်း",
	"common_result_message_4": "ဝယ်နိုင်စွမ်း ထိန်းသိမ်းရန်။",
	"common_calculate_button_text": "တွက်ချက်ပါ",
	"common_learn_more": "ပိုမိုသိရှိပါ",
	"common_success": "အောင်မြင်ပါပြီ!",
	"common_choose_your_country": "သင့်နိုင်ငံ ရွေးချယ်ပါ",
	"common_country_usa": "အမေရိကန်",
	"common_country_canada": "ကနေဒါ",
	"common_submit": "တင်ပြပါ",
	"common_language_afrikaans": "အာဖရိကန်စ်", "common_language_arabic": "အာရဗီ", "common_language_basque": "ဘတ်စ်", "common_language_bulgarian": "ဘူလ်ဂေးရီးယား", "common_language_catalan": "ကတ်တလန်", "common_language_chinese": "တရုတ်", "common_language_croatian": "ခရိုအေးရှား", "common_language_czech": "ချက်", "common_language_danish": "ဒိန်းမတ်", "common_language_dutch": "ဒတ်ချ်", "common_language_english": "အင်္ဂလိပ်", "common_language_estonian": "အက်စ်တိုးနီးယား", "common_language_filipino": "ဖိလစ်ပိုင်", "common_language_finnish": "ဖင်လန်", "common_language_french": "ပြင်သစ်", "common_language_german": "ဂျာမန်", "common_language_greek": "ဂရိ", "common_language_hausa": "ဟောင်ဆာ", "common_language_hebrew": "ဟီဘရူး", "common_language_hindi": "ဟိန္ဒီ", "common_language_hungarian": "ဟန်ဂေရီ", "common_language_indonesian": "အင်ဒိုနီးရှား", "common_language_irish": "အိုင်းရစ်ရှ်", "common_language_italian": "အီတလီ", "common_language_japanese": "ဂျပန်", "common_language_korean": "ကိုရီးယား", "common_language_malay": "မလေး", "common_language_norwegian": "နော်ဝေ", "common_language_persian": "ပါရှန်း", "common_language_polish": "ပိုလန်", "common_language_portuguese": "ပေါ်တူဂီ", "common_language_russian": "ရုရှ", "common_language_sinhala": "ဆင်ဟာလ", "common_language_slovak": "စလိုဗက်", "common_language_slovenian": "စလိုဗေးနီးယား", "common_language_spanish": "စပိန်", "common_language_swahili": "ဆွာဟီလီ", "common_language_swedish": "ဆွီဒင်", "common_language_thai": "ထိုင်း", "common_language_turkish": "တူရကီ", "common_language_urdu": "အူရ်ဒူ", "common_language_vietnamese": "ဗီယက်နမ်", "common_language_yoruba": "ယိုရူဘာ",
	"common_stickers_bulk_mess": "ဖိုင်များကို ကိုယ်တိုင်ကိုင်တွယ်လိုခြင်း မရှိပါသလား?",
	"common_stickers_bulk_want": "စတစ်ကာ အနည်းငယ်ထက် ပိုလိုပါသလား?",
	"common_stickers_bulk_store": "ကျွန်ုပ်တို့ အသုံးပြုသော ပုံနှိပ်စက်ရုံထံမှ စတစ်ကာ အများအပြား မှာယူပါ။",
	"common_stickers_bulk_cheaper": "စတစ်ကာ ပိုဝယ်လေ စတစ်ကာတစ်ခုစီ ဈေးပိုသက်သာလေ ဖြစ်ပါသည်။",
	"common_stickers_print_instructions_1": "သင်ဘယ်နေရာမှာပဲနေနေ ကိုယ်ပိုင်စတစ်ကာ ပုံနှိပ်၍ ပါဝင်နိုင်ပါသည်! စတစ်ကာဖိုင်များနှင့် ညွှန်ကြားချက်များ ဒေါင်းလုဒ်ရန် အောက်ပါ သင့်ဘာသာစကားကို နှိပ်ပါ။",
	"common_stickers_print_instructions_2": "ကျေးဇူးပြု၍ သတိပြုပါ: ဘာသာစကားအားလုံးတွင် စတစ်ကာအားလုံး ရရှိနိုင်ခြင်းမဟုတ်ပါ။",
	"common_stickers_request_language_1": "သင့်ဘာသာစကား မတွေ့ပါသလား?",
	"common_stickers_request_language_2": "သင့်ဒေသတွင်းဘာသာစကားဖြင့် စတစ်ကာဖိုင်များ တောင်းဆိုရန် အောက်ပါဖောင်ကို ဖြည့်ပါ။",
	"common_stickers_dimensions": "အတိုင်းအတာ:", "common_stickers_type": "အမျိုးအစား:", "common_stickers_material": "ပစ္စည်း:", "common_stickers_where_to_print": "ပုံနှိပ်ရမည့်နေရာ:",
	"common_stickers_type_die_cut": "die-cut စတစ်ကာ", "common_stickers_material_vinyl": "အပြင်သုံးအတွက် vinyl စတစ်ကာ",
	"common_stickers_printer": "ကျွန်ုပ်တို့ StickerMule.com ကို အသုံးပြုသော်လည်း မည်သည့် စတစ်ကာကုမ္ပဏီကိုမဆို အသုံးပြုနိုင်ပါသည်။",
	"common_stickers_dimensions_danger": "11.4544 cm x 8.382 cm (4.51 in x 3.3 in)", "common_stickers_dimensions_warning": "10.414 cm x 9.2202 cm (4.1 in x 3.63 in)", "common_stickers_dimensions_caution": "12.0142 cm x 7.9502 cm (4.73 in x 3.13 in)", "common_stickers_dimensions_fix": "11.3792 cm x 6.8072 cm (4.48 in x 2.68 in)", "common_stickers_dimensions_study": "14.605 cm x 5.1308 cm (5.75 in x 2.02 in)", "common_stickers_dimensions_bdhi": "21.59 cm x 4.6482 cm (8.5 in x 1.83 in)", "common_stickers_dimensions_cure_v2": "6.35 cm x 12.7 cm (2.5 in x 5 in)", "common_stickers_dimensions_got_inflation": "7.9248 cm x 14.605 cm (3.12 in x 5.75 in)", "common_stickers_dimensions_what_if": "21.7932 cm x 7.62 cm (8.58 in x 3 in)", "common_stickers_dimensions_bitcoin_accepted_here": "20.995 cm x 6.35 cm (8.25 in x 2.5 in)",
	"common_nostr_join": "NOSTR ကို ယခုပဲ ပါဝင်ပါ",
	"common_nostr_protocol_header": "Protocol ဖြစ်သည်၊ platform မဟုတ်",
	"common_nostr_protocol_c1": "Nostr သည် ဆင်ဆာဖြတ်ခြင်း၊ platform မှ ဖယ်ရှားခြင်း သို့မဟုတ် ဆွဲချခြင်း မစိုးရိမ်ဘဲ အွန်လိုင်းတွင် ဆက်သွယ်နိုင်စေသော protocol အသစ်ဖြစ်ပါသည်",
	"common_nostr_protocol_c2": "Twitter နှင့် Facebook ကဲ့သို့ platform များကို ကုမ္ပဏီတစ်ခုတည်းက ထိန်းချုပ်သော်လည်း Nostr protocol ကို မည်သူမျှ ထိန်းချုပ်ခြင်းမရှိပါ။",
	"common_nostr_freedom_header": "ရွှေ့ပြောင်းခွင့် လွတ်လပ်မှု",
	"common_nostr_freedom_c1": "Nostr သည် email နှင့် ဆင်တူပါသည်။ email protocol ကို မည်သူမျှ ထိန်းချုပ်ခြင်းမရှိပြီး မည်သူမဆို client (Gmail, Hotmail ကဲ့သို့) တည်ဆောက်နိုင်ပါသည်။",
	"common_nostr_freedom_c2": "Nostr protocol ကို မည်သူမျှ ထိန်းချုပ်ခြင်းမရှိပြီး မည်သူမဆို client (Damus, Amethyst ကဲ့သို့) တည်ဆောက်နိုင်ပါသည်။",
	"common_nostr_freedom_c3": "client တစ်ခု၏ အလုပ်လုပ်ပုံ မကြိုက်ပါက follower သို့မဟုတ် အကြောင်းအရာ မဆုံးရှုံးဘဲ Nostr အကောင့်ကို အခြား client သို့ ချောမွေ့စွာ ရွှေ့ပြောင်းနိုင်ပါသည်။",
	"common_nostr_bitcoin_header": "Bitcoin ပါဝင်ပြီးသား",
	"common_nostr_bitcoin_c1": "Bitcoin သည် Nostr protocol တွင် မူရင်းအတိုင်း ပါဝင်ပါသည်။ ကြိုက်သော အကြောင်းအရာ တွေ့ပါက ကျေးဇူးတင်ကြောင်း bitcoin zap လုပ်နိုင်ပါသည်!",
	"common_nostr_bitcoin_c2": "Twitter နှင့် Facebook ကဲ့သို့ ဗဟိုချုပ်ကိုင် platform များတွင် ဗဟိုချုပ်ကိုင်ကုမ္ပဏီက သင့်အကြောင်းအရာမှ ငွေရှာပါသည်။ သို့သော် Nostr ကဲ့သို့ ဖွင့် protocol များတွင် သင်က သင့်အကြောင်းအရာမှ ငွေရှာပါသည်။",
	"common_nostr_download_client": "NOSTR ပါဝင်ရန် အခမဲ့ CLIENT ဒေါင်းလုဒ်လုပ်ပါ",
	"common_nostr_iphone_clients": "iPhone Client များ", "common_nostr_primal": "PRIMAL", "common_nostr_iphone_app": "iPhone အက်ပ်", "common_nostr_first_client": "ပထမ client အဖြစ် အကြံပြု", "common_nostr_wallet_built_in": "Bitcoin zap ပိုက်ဆံအိတ် ပါဝင်ပြီးသား", "common_nostr_download_now": "ယခု ဒေါင်းလုဒ်လုပ်ပါ", "common_nostr_damus": "DAMUS", "common_nostr_familiar": "ရင်းနှီးသော interface", "common_nostr_separate_wallet": "သီးခြား bitcoin ပိုက်ဆံအိတ် လိုအပ်", "common_nostr_android_clients": "Android Client များ", "common_nostr_android_app": "Android အက်ပ်", "common_nostr_amethyst": "AMETHYST", "common_nostr_features": "လုပ်ဆောင်ချက် များစွာ", "common_nostr_browser_clients": "Browser Client များ", "common_nostr_iris": "IRIS", "common_nostr_web_client": "Web Client", "common_nostr_simple": "အလွန်ရိုးရှင်း", "common_nostr_test": "စမ်းသပ်အကောင့်ဖြင့် Nostr စမ်းသုံးရန် လွယ်ကူသောနည်း", "common_nostr_view_client": "CLIENT ကြည့်ပါ",
	"common_kit_printer": "ကိုယ်ပိုင် Bitcoin စီးပွားရေး ကိရိယာအစုံ လက်ကမ်းစာစောင် ပုံနှိပ်ရန် VistaPrint.com ကို အကြံပြုပါသည်။ သို့သော် နှစ်ဖက်ပုံနှိပ်နိုင်သည့် မည်သည့် ပုံနှိပ်ကုမ္ပဏီကိုမဆို အသုံးပြုနိုင်ပါသည်။",
	"common_kit_link_to_print": "ပုံနှိပ်ရန် လင့်ခ်:", "common_kit_fold": "ခေါက်:", "common_kit_fold_trifold": "သုံးခေါက်", "common_kit_unfolded_size": "မခေါက်ထားသော အရွယ်အစား:", "common_kit_unfolded_size_bbk": "Letter size (8.5 in x 11 in)", "common_kit_paper_thickness": "စာရွက်အထူ:", "common_kit_paper_thickness_standard": "စံ", "common_kit_paper_stock": "စာရွက်အမျိုးအစား:", "common_kit_paper_stock_glossy": "တောက်ပြောင်", "common_kit_exterior_print_file": "အပြင်ဘက် ပုံနှိပ်ဖိုင်:", "common_kit_interior_print_file": "အတွင်းဘက် ပုံနှိပ်ဖိုင်:",
	"common_kit_cta_header": "ဒေသတွင်း စီးပွားရေးတစ်ခုကို Bitcoin လက်ခံစေပါ",
	"common_biz_learn": "Bitcoin သည် စီးပွားရေးအတွက် ဘာကြောင့်ကောင်းကြောင်း သိရှိပါ", "common_biz_wallets": "Bitcoin ငွေပေးချေမှု လက်ခံရန် Bitcoin ပိုက်ဆံအိတ် ရယူပါ", "common_biz_maps": "Bitcoin ကုန်သည်မြေပုံများတွင် စာရင်းသွင်းပါ", "common_biz_stickers": "အခမဲ့ 'Bitcoin ဤနေရာတွင် လက်ခံပါသည်' စတစ်ကာများ", "common_biz_rewards": "Bitcoin ဆုလာဘ်များ", "common_biz_accounting": "Bitcoin စာရင်းကိုင် လမ်းညွှန်", "common_biz_faq": "မကြာခဏ မေးလေ့ရှိသော မေးခွန်းများ", "common_biz_kit": "သင့်ကိုယ်ပိုင် Bitcoin စီးပွားရေး ကိရိယာအစုံ ပုံနှိပ်ပါ",
	"common_biz_accept_bitcoin_payments": "BITCOIN ငွေပေးချေမှု လက်ခံပါ", "common_biz_ready": "သင့်စီးပွားရေးတွင် BITCOIN လက်ခံရန် အသင့်ဖြစ်ပြီလား?", "common_biz_more": "စီးပွားရေး အရင်းအမြစ် ပိုမို",
	"common_self_custody": "ကိုယ်ပိုင်ထိန်းသိမ်းခြင်း", "common_not_your_keys": "သင့်သော့ မဟုတ်", "common_cold_wallet": "COLD ပိုက်ဆံအိတ်", "common_hot_wallet": "HOT ပိုက်ဆံအိတ်",
	"common_sticker_files_mission_1": "ကျွန်ုပ်တို့၏ ရည်ရွယ်ချက်မှာ အများပြည်သူနေရာများတွင် Bitcoin စတစ်ကာ ကပ်ခြင်းဖြင့် လူပိုများများကို orange pill လုပ်ရန် ကူညီခြင်းဖြစ်ပါသည်။ ကျွန်ုပ်တို့၏ စတစ်ကာအားလုံးတွင် ပညာရေးဆိုင်ရာ စာမျက်နှာများသို့ လင့်ခ်ချိတ်သော QR ကုဒ်များ ပါဝင်ပါသည်",
	"common_sticker_files_mission_2": "Bitcoin", "common_sticker_files_mission_3": "ငွေကြေးဖောင်းပွမှု",
	"common_sticker_files_mission_4": "အမေရိကန် သို့မဟုတ် ကနေဒါတွင် နေထိုင်ပါက",
	"common_sticker_files_mission_5": "အခမဲ့ အင်္ဂလိပ် စတစ်ကာ အစုံ တောင်းဆိုနိုင်ပါသည်",
	"common_published_by": "ထုတ်ဝေသူ", "common_publisher_name": "bitcoin.rocks", "common_publisher_since": "၂၀၂၂ ခုနှစ်ကတည်းက Bitcoin ပညာရေး", "common_publisher_open_source": "Open-source ပရောဂျက်",
	"common_reviewed_accuracy": "✓ တိကျမှုအတွက် ပြန်လည်သုံးသပ်ပြီး: ၂၀၂၆",
	"common_footer_tagline": "ပညာရေးမှတစ်ဆင့် bitcoin လက်ခံသုံးစွဲမှုကို အရှိန်မြှင့်ခြင်း။",
	"common_footer_contribute": "ပံ့ပိုးကူညီပါ", "common_footer_nostr": "Nostr", "common_sources_heading": "အရင်းအမြစ်များ"
};

const filePath = path.join(i18nDir, lang, `common_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone creating common.json for Burmese (my).');
