/**
 * Creates Arabic (ar) index.json translation file.
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ar';
const today = '2026-04-04';

const data = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	},
	"bitcoin_builds_a_better_world": "البيتكوين يبني عالماً أفضل.",
	"home_description": "البيتكوين نقود أفضل تبني عالماً أفضل. البيتكوين حمى حقوق الإنسان، وأنقذ الناس من التضخم العالي، ودعم المزارعين المحليين، وقلل الانبعاثات من حفر النفط، وأكثر من ذلك بكثير.",
	"home_intro": "البيتكوين نقود أفضل تبني عالماً أفضل. اضغط على فئة أدناه لتعرف كيف يجعلها البيتكوين أفضل، أو ابدأ بالتمرير لاستكشاف.",
	"home_btn_money": "نقود أفضل",
	"home_btn_salary": "راتبك",
	"home_btn_freedom": "الحرية",
	"home_btn_human_rights": "حقوق الإنسان",
	"home_btn_equality": "المساواة",
	"home_btn_property_rights": "حقوق الملكية",
	"home_btn_housing": "الإسكان",
	"home_btn_business": "الأعمال",
	"home_btn_crowdfunding": "التمويل الجماعي",
	"home_btn_energy": "الطاقة",
	"home_btn_environment": "البيئة",
	"home_btn_food": "الغذاء",
	"home_btn_art": "الفن",
	"home_btn_politics": "السياسة",
	"home_btn_war": "الحرب",
	"home_btn_coding": "البرمجة",
	"home_btn_networks": "الشبكات",
	"home_btn_payments": "المدفوعات",
	"home_btn_self_custody": "الاحتفاظ الذاتي",
	"home_btn_you": "أنت",
	"home_section_bitcoin_is": "البيتكوين هو",
	"home_section_bitcoin_and": "البيتكوين و",
	"home_link_type_website": "موقع إلكتروني",
	"home_link_type_video": "فيديو",
	"home_link_type_article": "مقال",
	"home_link_type_podcast": "بودكاست",
	"home_link_type_business_kit": "حزمة أعمال",
	"home_link_type_data": "بيانات",
	"home_link_type_research": "بحث",
	"home_link_type_story": "قصة",
	"home_link_type_book_excerpt": "مقتطف كتاب",
	"home_link_type_street_art": "فن الشارع",
	"home_link_type_outreach": "توعية",
	"home_link_type_campaign": "حملة",
	"home_link_type_software": "برنامج",
	"home_link_type_hardware": "جهاز",
	"home_link_type_guide": "دليل",
	"home_link_type_email": "بريد إلكتروني",
	"home_link_title_inflation": "البيتكوين ليس لديه تضخم",
	"home_link_title_bank_runs": "البيتكوين ليس لديه أزمات بنكية",
	"home_link_title_gold": "البيتكوين مقابل الذهب",
	"home_link_title_crypto": "البيتكوين مقابل العملات المشفرة",
	"home_link_title_cash": "البيتكوين مقابل النقد",
	"home_link_title_bonds": "البيتكوين مقابل السندات",
	"home_link_title_cbdc": "البيتكوين مقابل العملات الرقمية للبنوك المركزية",
	"home_link_title_your_salary_1": "اكتشف كم يحتاج راتبك للزيادة لمواكبة التضخم.",
	"home_link_title_freedom_1": "لماذا البيتكوين مهم للحرية",
	"home_link_title_freedom_2": "البيتكوين يوفر الحرية من القمع السياسي",
	"home_link_title_human_rights_1": "كيف يفرض البيتكوين حقوق الإنسان",
	"home_link_title_human_rights_2": "ثورة البيتكوين الصامتة في أفريقيا",
	"home_link_title_human_rights_3": "البيتكوين يحمي حقوق الإنسان حول العالم",
	"home_link_title_equality_1": "البيتكوين يجلب الأمل والفرص لجنوب أفريقيا",
	"home_link_title_equality_2": "كيف يمكن للبيتكوين أن يغير قواعد اللعبة للأمريكيين السود",
	"home_link_title_property_rights_1": "البيتكوين هو الشكل المثالي للملكية",
	"home_link_title_property_rights_2": "البيتكوين مقابل العقارات",
	"home_link_title_housing_1": "كيف سيجعل البيتكوين الإسكان في متناول الجميع مرة أخرى",
	"home_link_title_business_3": "البيتكوين مقابل الأسهم",
	"home_link_title_business_1": "تعلم لماذا البيتكوين مفيد للأعمال",
	"home_link_title_business_2": "اجعل عملاً محلياً يقبل البيتكوين",
	"home_link_title_crowdfunding_1": "كيف غذّى البيتكوين أكبر احتجاجات نيجيرية منذ جيل",
	"home_link_title_crowdfunding_2": "احتجاج سائقي الشاحنات الكنديين يجمع أموالاً بالبيتكوين بعد حظر GoFundMe للتبرعات",
	"home_link_title_crowdfunding_3": "Geyser = تمويل جماعي بالبيتكوين",
	"home_link_title_energy_1": "كيف يستقر البيتكوين شبكة الطاقة في تكساس",
	"home_link_title_energy_2": "لماذا يستخدم البيتكوين الطاقة؟",
	"home_link_title_energy_3": "استخدام البيتكوين للطاقة ليس مشكلة. إليك لماذا.",
	"home_link_title_energy_4": "تعدين البيتكوين يستقر شبكات الطاقة من خلال الاستجابة للطلب",
	"home_link_title_energy_5": "معدّنو البيتكوين يجلبون الطاقة الكهرومائية للمجتمعات الأفريقية الريفية",
	"home_link_title_energy_6": "كيف يحفز البيتكوين الطاقة المتجددة",
	"home_link_title_environment_1": "كيف يقلل تعدين البيتكوين انبعاثات الميثان العالمية",
	"home_link_title_environment_2": "كيف أنقذ تعدين البيتكوين متنزهاً وطنياً",
	"home_link_title_environment_3": "البيتكوين هو أكثر صناعة صديقة للبيئة على وجه الأرض!",
	"home_link_title_environment_4": "تعدين البيتكوين يمنع الغاز الطبيعي المحترق من تلويث الغلاف الجوي",
	"home_link_title_food_1": "كيف يؤثر التضخم على أسعار الغذاء",
	"home_link_title_food_2": "كيف تضر النقود الورقية بالغذاء والمزارع وتربة الأرض",
	"home_link_title_fine_art": "البيتكوين مقابل الفن الراقي",
	"home_link_title_art_1": "انضم إلى مبادرة ملصقات البيتكوين",
	"home_link_title_art_2": "أرسل بطاقة بريدية عن البيتكوين لشخص تعرفه",
	"home_link_title_art_3": "اطبع وعلّق منشورات البيتكوين",
	"home_link_title_politics_1": "البيتكوين مفارقة سياسية",
	"home_link_title_politics_2": "يمكنك التصويت لنقود أفضل",
	"home_link_title_war_1": "كيف يمكن للبيتكوين أن ينهي الحروب اللانهائية",
	"home_link_title_war_2": "البيتكوين والمحاربين القدماء: توافق طبيعي",
	"home_link_title_war_3": "كيف يساعد البيتكوين المدنيين على الهروب من الحرب في السودان",
	"home_link_title_coding_1": "دليل تفاعلي حول الجانب التقني للبيتكوين",
	"home_link_title_coding_2": "bitcoinSwitch: حوّل أي جهاز لقبول البيتكوين",
	"home_link_title_coding_3": "ابرمج طريقك عبر أسرار البيتكوين",
	"home_link_title_networks_1": "عرض حي لشبكة البيتكوين",
	"home_link_title_networks_2": "البيتكوين مقابل البنوك",
	"home_link_title_payments_1": "البيتكوين مقابل فيزا",
	"home_link_title_payments_2": "نظرة على شبكة Lightning (مدفوعات بيتكوين فورية)",
	"home_link_title_payments_3": "محفظة Bitcoin في السلفادور يمكن أن توفر للسلفادوريين 400 مليون دولار سنوياً في رسوم التحويلات",
	"home_link_title_payments_4": "احصل على عنوان Lightning الخاص بك لتلقي مدفوعات بيتكوين فورية",
	"home_link_title_self_custody_1": "كيف تخزن بيتكوينك بأمان",
	"home_link_title_self_custody_2": "6 أسباب لسحب بيتكوينك من البورصات",
	"home_link_title_self_custody_3": "الذهب والبيتكوين والاحتفاظ الذاتي",
	"home_link_title_get_started_1": "تعلم أساسيات البيتكوين",
	"home_link_title_get_started_2": "احصل على أول محفظة بيتكوين لك",
	"home_link_title_get_started_3": "كيف تشتري البيتكوين",
	"home_link_author_bitcoin_rocks": "bitcoin.rocks",
	"home_link_author_youtube": "YouTube",
	"home_link_author_cic": "حاسبة التضخم المركب",
	"home_link_author_time_magazine": "مجلة TIME",
	"home_link_author_fortune": "Fortune",
	"home_link_author_anita_posch": "Anita Posch",
	"home_link_author_quartz": "Quartz",
	"home_link_author_yahoo_finance": "Yahoo Finance",
	"home_link_author_geyser": "Geyser",
	"home_link_author_bitcoin_uses_energy": "BitcoinUses.Energy",
	"home_link_author_lyn_alden": "Lyn Alden",
	"home_link_author_forbes": "Forbes",
	"home_link_author_coindesk": "CoinDesk",
	"home_link_author_daniel_batten": "Daniel Batten",
	"home_link_author_mit_technology_review": "MIT Technology Review",
	"home_link_author_mit_media_lab": "MIT Media Lab",
	"home_link_author_bitcoin_is_green": "BitcoinIs.Green",
	"home_link_author_texas_am_university": "Texas A&M University",
	"home_link_author_saifedean_ammous": "Saifedean Ammous",
	"home_link_author_bitcoin_magazine": "Bitcoin Magazine",
	"home_link_author_vfbm": "VoteForBetter.Money",
	"home_link_author_misha_guttentag": "Misha Guttentag",
	"home_link_author_wes_lippman": "Wes Lippman",
	"home_link_author_satsie": "Satsie",
	"home_link_author_makerbits": "MakerBits",
	"home_link_author_saving_satoshi": "Saving Satoshi",
	"home_link_author_kevin_rooke": "Kevin Rooke",
	"home_link_author_blockworks": "Blockworks",
	"home_link_author_lightning_address": "LightningAddress.com",
	"home_link_author_arman_the_parman": "Arman The Parman",
	"home_link_author_21_days_of_bitcoin": "21 Days of Bitcoin",
	"home_link_author_strike": "Strike",
	"home_link_author_bitcoin_explorama": "Bitcoin Explorama",
	"home_link_author_mempool_space": "Mempool.space"
};

const filePath = path.join(i18nDir, lang, `index_${lang}.json`);
fs.mkdirSync(path.dirname(filePath), { recursive: true });
fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n', 'utf8');
console.log(`CREATED: ${filePath}`);
console.log('\nDone! Index file created for Arabic (ar).');
