/**
 * Creates Arabic (ar) translation files for content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'ar';
const today = '2026-04-04';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "البيتكوين ليس لديه أزمات بنكية",
	"bank_runs_header": "البيتكوين ليس لديه أزمات بنكية",
	"bank_runs_header_2": "لكن بنكك قد يكون لديه",
	"bank_runs_what": "ما هي الأزمة البنكية؟",
	"bank_runs_what_content_1": "تحدث الأزمة البنكية عندما يحاول عدد كبير جداً من الأشخاص سحب أموالهم من البنك في نفس الوقت.",
	"bank_runs_what_content_2": "إذا لم يكن لدى البنوك ما يكفي من المال المتاح لمطابقة عمليات السحب، يمكن أن تنهار بالكامل عند حدوث أزمة بنكية.",
	"bank_runs_how": "كيف تحدث الأزمات البنكية؟",
	"bank_runs_how_content_1": "نظامنا المصرفي هو \"احتياطي جزئي\" مما يعني أن البنوك لا تحتفظ بأموالك في خزنة وتنتظرك لإنفاقها أو سحبها.",
	"bank_runs_how_content_2": "بدلاً من ذلك، يأخذ بنكك أموالك ويقرضها أو يستثمرها. هذا يمكن أن يقيّد أموالك لفترات طويلة، رغم أن البنك يعدك بإمكانية سحب أموالك في أي وقت.",
	"bank_runs_how_content_3": "فماذا يحدث إذا حاولت سحب أموالك بعد أن أقرضها البنك أو استثمرها؟",
	"bank_runs_how_content_4": "ليست مشكلة إذا كنت الوحيد الذي يحاول السحب. سيأخذ البنك ببساطة أموال شخص آخر ويعطيها لك. لكن ماذا يحدث عندما يحاول الكثير من الناس السحب في نفس الوقت؟",
	"bank_runs_how_content_5": "اكتشف كثير من الأشخاص في الولايات المتحدة ذلك عندما حدثت أزمة على بنك Silicon Valley في مارس 2023.",
	"bank_runs_how_content_6": "كان البنك قد استثمر أموال عملائه في سندات حكومية مقيدة لمدة تصل إلى 30 عاماً. والأسوأ من ذلك، أن قيمة تلك السندات انخفضت بشكل كبير مؤخراً، لذا لم يتمكن بنك Silicon Valley من بيع السندات للحصول على أموال مودعيه. كان معسراً. لم يكن لديه ما يكفي من المال لمطابقة عمليات سحب مودعيه.",
	"bank_runs_how_content_7": "مع اكتشاف المزيد من الأشخاص، ازدادت المشكلة سوءاً. جاءت المزيد من طلبات السحب، لكن الكثير منها لم تتم معالجته. أدركت آلاف الشركات أنها لن تتمكن من دفع رواتب موظفيها بسبب فشل البنك.",
	"bank_runs_how_content_8": "تدخلت مؤسسة FDIC ووافقت على تعويض المودعين بالكامل. المشكلة حُلّت؟ ليس تماماً...",
	"bank_runs_fdic": "هل يحمي تأمين FDIC أموالي؟",
	"bank_runs_fdic_content_1": "تأمين FDIC مصمم لحماية مودعي البنوك في حالة فشل البنك. الودائع مؤمنة حتى 250,000 دولار لكل مودع. يبدو رائعاً، أليس كذلك؟",
	"bank_runs_fdic_content_2": "ليس تماماً. إذا فشل بنك، من أين تحصل FDIC على المال؟ لديها صندوق تأمين بـ 125 مليار دولار.",
	"bank_runs_fdic_content_3": "يبدو كمبلغ كبير حتى تقارنه بمبلغ الودائع التي يؤمنونها: ما يقرب من 10 تريليون أو 10,000 مليار دولار.",
	"bank_runs_fdic_content_4": "حتى أن FDIC تُظهر على موقعها أن لديها ما يكفي من المال في صندوق التأمين لتغطية أكثر قليلاً من 1% من الودائع.",
	"bank_runs_fdic_content_5": "في حالة فشل بنكي تجاوز صندوق تأمين FDIC، من المرجح (لكن غير مضمون) أن الحكومة الأمريكية ستطبع أموالاً لتعويض المودعين بالكامل.",
	"bank_runs_fdic_content_6": "لكن طباعة الأموال تسبب التضخم، لذا هذا ليس حلاً رائعاً.",
	"bank_runs_safe": "هل هناك بنوك لا تستخدم الاحتياطي الجزئي؟",
	"bank_runs_safe_content_1": "حاولت بعض البنوك أن تكون \"بنوكاً آمنة\" لا تقرض أو تستثمر أموال المودعين.",
	"bank_runs_safe_content_2": "رغم أن هذه البنوك الآمنة لن تكون لديها أي مخاطر أزمات بنكية، إلا أن طلباتها رُفضت من قبل الاحتياطي الفيدرالي. هذا يعني أنها لا تستطيع العمل قانونياً كبنوك.",
	"bank_runs_safe_content_3": "لأنها مُنعت من العمل، لا توجد بنوك اليوم لا تستخدم الاحتياطي الجزئي.",
	"bank_runs_safe_content_4": "لحسن الحظ، هناك طريقة للخروج من نظام الاحتياطي الجزئي بأن تكون بنكك الخاص. لا، نحن لا نتحدث عن تخبئة النقود تحت فراشك.",
	"bank_runs_safe_content_5": "الادخار نقداً لا يزال عرضة للتضخم.",
	"bank_runs_safe_content_6": "نتحدث عن البيتكوين: نظام مالي جديد يتيح لك أن تكون بنكك الخاص.",
	"bank_runs_protect": "هل يمكن للبيتكوين حمايتي من الأزمات البنكية؟",
	"bank_runs_protect_content_1": "نعم، البيتكوين نظام مالي باحتياطي كامل.",
	"bank_runs_protect_content_2": "الأزمات البنكية مستحيلة في البيتكوين طالما تسحب بيتكوينك إلى محفظتك الخاصة. لا تترك بيتكوينك في بورصة أو في غلاف مثل Bitcoin ETF.",
	"bank_runs_protect_content_3": "اطلع على دليل محافظ البيتكوين البسيط لدينا لتعرف كيف تسحب إلى محفظتك الخاصة.",
	"bank_runs_protect_content_4": "مع البيتكوين، يمكنك أخيراً أن تتحكم في أموالك."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "دليل محافظ البيتكوين",
	"wallets_description": "هناك العديد من محافظ البيتكوين المختلفة التي تختلف بطرق مهمة. يمكنك تحديد ما إذا كانت المحفظة مناسبة لك بطرح هذه الأسئلة البسيطة.",
	"wallets_header": "كيف تخزن بيتكوينك بأمان",
	"wallets_s1_c1": "محافظ البيتكوين متوافقة، لذا يمكنك إرسال البيتكوين لأي شخص بغض النظر عن المحفظة التي يستخدمها.",
	"wallets_s1_c2": "هناك العديد من محافظ البيتكوين المختلفة التي تختلف بطرق مهمة. يمكنك تحديد ما إذا كانت المحفظة مناسبة لك بطرح هذه الأسئلة البسيطة:",
	"wallets_question_1": "هل هي محفظة احتفاظ ذاتي؟",
	"wallets_s2_c1": "أحد ابتكارات البيتكوين هو القدرة على تخزينه دون الاعتماد على أمين حفظ، مثل البنك.",
	"wallets_s2_c2": "إذا كنت تحتفظ بالبيتكوين في بورصة أو في ETF، فأنت تفقد فوائد الحرية التي يقدمها البيتكوين.",
	"wallets_s2_c3": "محافظ الاحتفاظ الذاتي تفتح القوة الكاملة للبيتكوين: نقود الحرية.",
	"wallets_s2_c4": "مع محفظة الاحتفاظ الذاتي، أنت الوحيد الذي لديه القدرة على إنفاق أو تحويل أموالك. لا يمكن لأحد منعك من إرسال أو تلقي أموالك عندما تستخدم محفظة الاحتفاظ الذاتي.",
	"wallets_s2_c5": "محافظ الاحتفاظ الذاتي تُسمى أيضاً المحافظ غير الحفظية.",
	"wallets_s3_c1": "المحافظ الحفظية هي محافظ لا تتحكم فيها في أموالك.",
	"wallets_s3_c2": "هذه المحافظ أشبه بالنظام المصرفي حيث يجب عليك الوثوق بطرف ثالث لمنحك الوصول إلى أموالك. إذا كان بيتكوينك في بورصة، فأنت تستخدم محفظة حفظية.",
	"wallets_s3_c3": "إذا اشتريت Bitcoin ETF، فأنت تستخدم محفظة حفظية لا تسمح لك بالسحب إلى الاحتفاظ الذاتي.",
	"wallets_s3_c4": "قد تبدو المحافظ الحفظية مريحة، لكن أمين الحفظ لديه القدرة التقنية لسرقة جميع أموال المستخدمين في أي وقت.",
	"wallets_s3_c5": "ليست مفاتيحك، ليست عملاتك!",
	"wallets_question_2": "هل هي ساخنة أم باردة؟",
	"wallets_s4_c1": "المحافظ الباردة تخزن مفاتيح بيتكوينك بطريقة لا تعرضها للإنترنت أبداً.",
	"wallets_s4_c2": "هذا يحد بشكل كبير من نقاط الهجوم التي قد يستخدمها لص لمحاولة سرقة بيتكوينك، وهو الأفضل للمبالغ الكبيرة من البيتكوين التي لا تحتاج لتحويلها كثيراً.",
	"wallets_s4_c3": "يمكنك التفكير في المحفظة الباردة كحساب ادخار طويل الأجل، يُعرف أيضاً بالتخزين البارد.",
	"wallets_s5_c1": "المحافظ الساخنة تخزن مفاتيح بيتكوينك على جهاز متصل بالإنترنت، مثل هاتفك.",
	"wallets_s5_c2": "المحافظ الساخنة تُعتبر عموماً آمنة، لكنها قد تحتوي على ثغرات أمنية أكثر من المحافظ الباردة.",
	"wallets_s5_c3": "يمكنك التفكير في المحفظة الساخنة كمحفظة جيب. لن تخزن مدخراتك بالكامل في محفظة جيبك، لكنك ستخزن بعض أموال الإنفاق.",
	"wallets_s5_c4": "المحافظ الساخنة تجعل من الأسهل بكثير إنفاق بيتكوينك دون الحاجة لإخراج مدخراتك بالكامل من التخزين البارد.",
	"wallets_question_3": "كيف سأنسخ عبارة الاسترداد احتياطياً؟",
	"wallets_s6_c1": "عند إعداد محفظة البيتكوين، سيُنشئ جهازك عبارة استرداد. عبارة الاسترداد هذه (تُسمى أيضاً عبارة البذرة) تحتوي على 12 أو 24 كلمة.",
	"wallets_s6_c2": "إذا فقدت الوصول إلى محفظتك أو توقف جهازك عن العمل، يمكنك إدخال عبارة الاسترداد هذه في محفظة جديدة لاستعادة الوصول إلى بيتكوينك.",
	"wallets_s6_c3": "معظم المحافظ تتضمن ورقة لكتابة عبارة الاسترداد، لكن كثير من الناس يفضلون نسخ هذه العبارة احتياطياً على الفولاذ بدلاً من ذلك. هذا يجعل من الأقل احتمالاً فقدان عبارة الاسترداد في حالة كارثة طبيعية مثل حريق أو فيضان.",
	"wallets_s6_c4": "اختبر Jameson Lopp 70 حزمة نسخ احتياطي فولاذية لمساعدتك في اختيار المناسبة لك.",
	"wallets_s6_c5": "اطلع على دليل Jameson للنسخ الاحتياطي المعدني للبيتكوين هنا.",
	"wallets_s6_c6": "أو تابع التمرير لاستكشاف خيارات محافظ البيتكوين.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "تبحث عن دليل محافظ Lightning؟",
	"wallets_starter_wallet": "محفظة مبتدئين رائعة",
	"wallets_mobile_app": "تطبيق هاتف",
	"wallets_2fa_support": "دعم المصادقة الثنائية",
	"wallets_air_gap_mode": "وضع الفجوة الهوائية",
	"wallets_air_gap_camera": "وضع الفجوة الهوائية + كاميرا",
	"wallets_bitcoin_only": "بيتكوين فقط",
	"wallets_security_features": "الكثير من ميزات الأمان",
	"wallets_free": "مجاني 100%",
	"wallets_coldcard_mk5_costs": "السعر 189 دولاراً",
	"wallets_coldcard_q_costs": "السعر 289 دولاراً",
	"wallets_blockstream_jade_costs": "السعر 79 دولاراً",
	"wallets_foundation_passport_costs": "السعر 199 دولاراً",
	"wallets_seedsigner_costs": "تكلفة القطع 50 دولاراً",
	"wallets_very_affordable": "في متناول الجميع",
	"wallets_pair_with_phone": "إقران مع هاتفك",
	"wallets_battery": "بطارية قابلة لإعادة الشحن",
	"wallets_build_your_own": "ابنِ محفظتك بنفسك",
	"wallets_qwerty_keyboard": "لوحة مفاتيح QWERTY كاملة",
	"wallets_qr_scanner": "ماسح رمز QR"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "كيف تشتري البيتكوين - دليل خطوة بخطوة",
	"buy_header": "كيف تشتري البيتكوين",
	"buy_intro_c1": "شراء البيتكوين لأول مرة قد يبدو مربكاً، لكنه في الواقع بسيط جداً عندما تقسمه إلى خطوات.",
	"buy_intro_c2": "سيرشدك هذا الدليل خلال عملية شراء البيتكوين بأمان وتخزينه في محفظتك الخاصة.",
	"buy_step_1_header": "الخطوة 1: اختر بلدك",
	"buy_step_1_description": "الدول المختلفة لديها خيارات مختلفة لشراء البيتكوين. اختر بلدك لرؤية أفضل الخيارات المتاحة لك.",
	"buy_search_countries": "ابحث عن بلدك",
	"buy_country_united_states": "الولايات المتحدة",
	"buy_country_australia": "أستراليا",
	"buy_country_austria": "النمسا",
	"buy_country_belgium": "بلجيكا",
	"buy_country_brazil": "البرازيل",
	"buy_country_canada": "كندا",
	"buy_country_france": "فرنسا",
	"buy_country_germany": "ألمانيا",
	"buy_country_ireland": "أيرلندا",
	"buy_country_italy": "إيطاليا",
	"buy_country_netherlands": "هولندا",
	"buy_country_new_zealand": "نيوزيلندا",
	"buy_country_spain": "إسبانيا",
	"buy_country_united_kingdom": "المملكة المتحدة",
	"buy_country_argentina": "الأرجنتين",
	"buy_country_chile": "تشيلي",
	"buy_country_colombia": "كولومبيا",
	"buy_country_costa_rica": "كوستاريكا",
	"buy_country_czech_republic": "جمهورية التشيك",
	"buy_country_denmark": "الدنمارك",
	"buy_country_el_salvador": "السلفادور",
	"buy_country_estonia": "إستونيا",
	"buy_country_finland": "فنلندا",
	"buy_country_greece": "اليونان",
	"buy_country_guatemala": "غواتيمالا",
	"buy_country_hong_kong": "هونغ كونغ",
	"buy_country_hungary": "المجر",
	"buy_country_iceland": "آيسلندا",
	"buy_country_india": "الهند",
	"buy_country_israel": "إسرائيل",
	"buy_country_japan": "اليابان",
	"buy_country_latvia": "لاتفيا",
	"buy_country_lithuania": "ليتوانيا",
	"buy_country_luxembourg": "لوكسمبورغ",
	"buy_country_malta": "مالطا",
	"buy_country_mexico": "المكسيك",
	"buy_country_norway": "النرويج",
	"buy_country_panama": "بنما",
	"buy_country_poland": "بولندا",
	"buy_country_portugal": "البرتغال",
	"buy_country_romania": "رومانيا",
	"buy_country_singapore": "سنغافورة",
	"buy_country_slovakia": "سلوفاكيا",
	"buy_country_slovenia": "سلوفينيا",
	"buy_country_south_africa": "جنوب أفريقيا",
	"buy_country_south_korea": "كوريا الجنوبية",
	"buy_country_sweden": "السويد",
	"buy_country_switzerland": "سويسرا",
	"buy_country_thailand": "تايلاند",
	"buy_country_turkey": "تركيا",
	"buy_country_ukraine": "أوكرانيا",
	"buy_country_uruguay": "أوروغواي",
	"buy_step_2_header": "الخطوة 2: اختر طريقة الدفع",
	"buy_step_2_description": "هناك طريقتان رئيسيتان لشراء البيتكوين: بتحويل بنكي أو نقداً. لكل منهما مزايا مختلفة.",
	"buy_method_bank_transfer": "تحويل بنكي",
	"buy_method_bank_fast": "سريع وسهل",
	"buy_method_bank_less_private": "أقل خصوصية",
	"buy_method_bank_description": "التحويلات البنكية هي الطريقة الأكثر شيوعاً لشراء البيتكوين. إنها سريعة ومريحة وعادة ما تكون رسومها أقل.",
	"buy_method_choose_bank": "اختر التحويل البنكي",
	"buy_method_cash": "نقداً",
	"buy_method_cash_private": "أكثر خصوصية",
	"buy_method_cash_limited": "خيارات محدودة",
	"buy_method_cash_description": "الشراء النقدي يوفر خصوصية أكثر لكن خياراته أقل وقد يتطلب مقابلة شخص ما أو استخدام جهاز صراف آلي للبيتكوين.",
	"buy_method_choose_cash": "اختر النقد",
	"buy_step_3_header": "الخطوة 3: خيارات الشراء",
	"buy_step_3_description": "إليك أفضل خيارات شراء البيتكوين لبلدك وطريقة الدفع:",
	"buy_platform_recommended": "موصى به",
	"buy_platform_strike_description": "Strike هي أسرع وأسهل طريقة لشراء البيتكوين برسوم منخفضة ودعم فوري لشبكة Lightning.",
	"buy_platform_swan_description": "Swan Bitcoin متخصصة في خدمات البيتكوين فقط مع استثمار منتظم وموارد تعليمية.",
	"buy_platform_river_description": "River تقدم شراء البيتكوين والتعدين وخدمات الحفظ مع التركيز على التعليم والأمان.",
	"buy_platform_coinsquare_description": "Coinsquare هي بورصة بيتكوين كندية مع امتثال تنظيمي قوي ودعم عملاء.",
	"buy_platform_kraken_description": "Kraken هي بورصة بيتكوين راسخة مع ميزات تداول متقدمة وأمان قوي.",
	"buy_platform_atm_description": "أجهزة الصراف الآلي للبيتكوين تتيح لك شراء البيتكوين نقداً فوراً. ابحث عن واحد بالقرب منك باستخدام Coin ATM Radar.",
	"buy_platform_bisq_description": "Bisq هي بورصة لامركزية من نظير إلى نظير تتيح تداول البيتكوين الخاص بدون KYC.",
	"buy_platform_feature_instant": "شراء فوري",
	"buy_platform_feature_low_fees": "رسوم منخفضة",
	"buy_platform_feature_lightning": "شبكة Lightning",
	"buy_platform_feature_dca": "استثمار منتظم",
	"buy_platform_feature_education": "موارد تعليمية",
	"buy_platform_feature_withdrawal": "سحب سهل",
	"buy_platform_feature_mining": "تعدين البيتكوين",
	"buy_platform_feature_custody": "خدمات الحفظ",
	"buy_platform_feature_canadian": "مركز كندي",
	"buy_platform_feature_regulated": "بورصة منظمة",
	"buy_platform_feature_support": "دعم العملاء",
	"buy_platform_feature_established": "منصة راسخة",
	"buy_platform_feature_security": "أمان قوي",
	"buy_platform_feature_advanced": "ميزات متقدمة",
	"buy_platform_feature_cash": "شراء نقدي",
	"buy_platform_feature_anonymous": "أكثر مجهولية",
	"buy_platform_feature_p2p": "من نظير إلى نظير",
	"buy_platform_feature_private": "تداول خاص",
	"buy_platform_feature_decentralized": "لامركزي",
	"buy_platform_relai_description": "Relai هو تطبيق بيتكوين سويسري فقط مع محفظة احتفاظ ذاتي وميزات استثمار تلقائي ورسوم منخفضة للمستخدمين الأوروبيين.",
	"buy_platform_feature_bitcoin_only": "بيتكوين فقط",
	"buy_platform_feature_self_custody": "محفظة احتفاظ ذاتي",
	"buy_platform_feature_auto_invest": "خطط استثمار تلقائي",
	"buy_platform_feature_european": "مركز أوروبي",
	"buy_step_4_header": "الخطوة 4: خزّن بيتكوينك بأمان",
	"buy_step_4_c1": "بعد شراء البيتكوين، الخطوة الأهم هي نقله إلى محفظتك الخاصة حيث تتحكم في المفاتيح الخاصة.",
	"buy_step_4_c2": "ترك البيتكوين في بورصة محفوف بالمخاطر لأنك لا تملك البيتكوين فعلاً - البورصة هي التي تملكه.",
	"buy_step_4_c3": "عندما تتحكم في مفاتيحك الخاصة، لديك ملكية حقيقية لبيتكوينك ولا يمكن لأحد أخذه منك.",
	"buy_step_4_c4": "تعلم كيف تختار محفظة البيتكوين المناسبة لاحتياجاتك:",
	"buy_cta_wallets": "اطلع على دليل محافظ البيتكوين"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "دليل محافظ Lightning للبيتكوين",
	"lightning_description": "محافظ Lightning تمكنك من إرسال البيتكوين بسرعة وبتكلفة منخفضة مع الحفاظ على سيادتك الشخصية.",
	"lightning_header": "دليل محافظ LIGHTNING",
	"lightning_s1_c1": "تمكنك Lightning من إرسال مدفوعات بيتكوين بسرعة وبتكلفة منخفضة.",
	"lightning_s1_c2": "من المهم معرفة أن استخدام Lightning يأتي مع مقايضات. مقابل مدفوعات بيتكوين أسرع وأرخص، غالباً ما تضحي ببعض الأمان.",
	"lightning_s1_c3": "بشكل عام، يجب استخدام Lightning فقط مع كميات صغيرة من البيتكوين. يجب تخزين المبالغ الكبيرة فقط في محفظة أجهزة.",
	"lightning_s1_c4": "اطلع على دليل محافظ الأجهزة لمزيد من المعلومات.",
	"lightning_s1_c5": "ليست كل محافظ Lightning متشابهة. يمكنك تحديد المحفظة التي لديها التوازن المناسب من المقايضات بطرح سؤال واحد بسيط:",
	"lightning_question_1": "ما هو توازن المقايضات المناسب لي؟",
	"lightning_s2_c1": "أحد ابتكارات البيتكوين هو القدرة على تخزينه دون الاعتماد على أمين حفظ، مثل البنك. محافظ الاحتفاظ الذاتي تفتح القوة الكاملة للبيتكوين.",
	"lightning_s2_c2": "مع محفظة الاحتفاظ الذاتي، أنت الوحيد الذي لديه القدرة على إنفاق أو تحويل أموالك. لا يمكن لأحد إيقافك أو رقابتك أو السرقة منك عندما تستخدم محفظة الاحتفاظ الذاتي. هذه تُسمى أيضاً المحافظ غير الحفظية.",
	"lightning_s2_c3": "الطريقة الأكثر سيادة لاستخدام Lightning هي تشغيل عقدتك الخاصة.",
	"lightning_s2_c4": "يركز هذا الدليل على محافظ Lightning البسيطة التي لا تتطلب عقدتك الخاصة.",
	"lightning_s2_c5": "من المهم معرفة أنه حتى عند استخدام محفظة Lightning غير حفظية، أنت لا تزال تثق بمنشئ المحفظة بعدم إرسال تحديث ضار للتطبيق وسرقة أموالك.",
	"lightning_s3_c1": "المحافظ الحفظية هي محافظ لا تتحكم فيها في أموالك.",
	"lightning_s3_c2": "هذه المحافظ أشبه بالنظام المصرفي حيث يجب عليك الوثوق بطرف ثالث لمنحك الوصول إلى أموالك. إذا كان بيتكوينك في بورصة، فأنت تستخدم محفظة حفظية.",
	"lightning_s3_c3": "قد تبدو المحافظ الحفظية مريحة، لكن أمين الحفظ لديه القدرة التقنية لسرقة جميع أموال المستخدمين في أي وقت.",
	"lightning_s3_c4": "يفضل بعض الناس محافظ Lightning الحفظية للمبالغ الصغيرة من البيتكوين بسبب سهولة استخدامها. فقط تذكر: ليست مفاتيحك، ليست عملاتك!",
	"lightning_question_2": "اختر محفظتك",
	"lightning_s4_c1": "مع كل هذا في الاعتبار، يمكنك الآن اختيار محفظة Lightning التي لديها التوازن المناسب من المقايضات لك.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "الكثير من الميزات",
	"lightning_mobile_app": "تطبيق هاتف",
	"lightning_free": "مجاني 100%",
	"lightning_merchants": "رائع للتجار",
	"lightning_starter": "محفظة مبتدئين رائعة",
	"lightning_browser": "يعمل في المتصفح",
	"lightning_custodial": "محفظة حفظية بالكامل",
	"lightning_cta_hardware": "تبحث عن دليل محافظ أجهزة البيتكوين؟"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "ملصقات بيتكوين مجانية من bitcoin.rocks",
	"stickers_description": "ضع ملصق بيتكوين في مكان عام لتعريف من حولك بالبيتكوين.",
	"stickers_header": "ملصقات بيتكوين مجانية",
	"stickers_choose_header": "اختر حزمة ملصقاتك",
	"stickers_choose_c1": "مهمتنا هي مساعدتك في تعريف المزيد من الناس بالبيتكوين عن طريق وضع ملصقات البيتكوين في الأماكن العامة. جميع ملصقاتنا تحتوي على رموز QR تربط بصفحات تعليمية عن",
	"stickers_choose_c2": "البيتكوين",
	"stickers_choose_c3": "التضخم",
	"stickers_choose_c4": "اختر حزمة ملصقاتك أدناه",
	"stickers_text_pack": "حزمة النصوص",
	"stickers_signs_pack": "حزمة العلامات",
	"stickers_instructions_1": "أدخل عنوانك البريدي وسنرسل لك حزمة ملصقات بيتكوين مجانية بالبريد! ستُشحن ملصقاتك في ظرف أبيض عادي.",
	"stickers_instructions_2": "يتم حذف بيانات العنوان بعد شحن ملصقاتك المجانية.",
	"stickers_share_header": "شارك أماكن ملصقاتك",
	"stickers_share_c1": "شارك أماكن ملصقاتك معنا على Nostr وشاهد أين يضع الآخرون ملصقاتهم.",
	"stickers_btn_share_on_nostr": "شارك على NOSTR",
	"stickers_btn_what_is_nostr": "ما هو NOSTR؟",
	"stickers_flyers_link_before": "بينما أنت في ذلك، اطبع وعلّق ",
	"stickers_flyers_link_text": "منشورات البيتكوين",
	"stickers_flyers_link_after": " الخاصة بك لمساعدة المزيد من الناس على التعرف على البيتكوين.",
	"stickers_country_global_print": "عالمي — اطبع ملصقاتي بنفسي",
	"stickers_country_global_order": "عالمي — اطلب بالجملة",
	"placeholder_name_optional": "الاسم (اختياري)",
	"placeholder_address_line_1": "عنوان السطر 1",
	"placeholder_address_line_2": "عنوان السطر 2 (اختياري)",
	"placeholder_city": "المدينة",
	"placeholder_state": "الولاية",
	"placeholder_province": "المقاطعة",
	"placeholder_zip_code": "الرمز البريدي",
	"placeholder_postal_code": "الرمز البريدي",
	"placeholder_language": "اللغة",
	"placeholder_which_stickers": "أي ملصقات؟",
	"placeholder_email_optional": "أدخل بريدك الإلكتروني ليتم إشعارك (اختياري)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "بطاقات بريدية مجانية عن البيتكوين من bitcoin.rocks",
	"postcards_description": "احصل على حزمة بطاقات بريدية مجانية عن البيتكوين وشارك البيتكوين مع شخص تعرفه.",
	"postcards_header": "برنامج البطاقات البريدية مغلق",
	"postcards_program_closed_message": "انتهى برنامج البطاقات البريدية المجانية عن البيتكوين. شكراً لكل من شارك في نشر تعليم البيتكوين عبر البريد!",
	"postcards_sticker_alternative_header": "احصل على ملصقات بيتكوين مجانية بدلاً من ذلك",
	"postcards_sticker_alternative_message": "استمر في نشر الوعي بالبيتكوين مع برنامج الملصقات المجاني! ملصقات البيتكوين الخاصة بنا مثالية للمشاركة في الأماكن العامة وتأتي مع رموز QR تربط بمحتوى تعليمي.",
	"postcards_sticker_cta": "احصل على ملصقات مجانية",
	"postcards_step_2": "كيف كانت تبدو البطاقات البريدية",
	"postcards_instructions_4": "صنعنا هذه البطاقات البريدية لتسهيل تعريف شخص تعرفه بالبيتكوين! فقط أضف عنواناً وطابعاً وأرسل بطاقتك البريدية.",
	"postcards_instructions_5": "مهمتنا هي تسريع تبني البيتكوين. يمكنك المساعدة عن طريق الحصول على ملصقات مجانية ووضعها في الأماكن العامة!",
	"postcards_instructions_6": "كلنا نعرف بعض الأشخاص الذين يمكنهم الاستفادة من تعلم المزيد عن البيتكوين. شارك ملصقات البيتكوين معهم اليوم!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "ساعدنا في وضع هذه اللافتات عن البيتكوين في أنحاء أمريكا!",
	"signs_title": "لافتات بيتكوين مجانية من bitcoin.rocks",
	"signs_choose_header": "شكراً لمساعدتنا في وضع هذه اللافتات عن البيتكوين في أنحاء أمريكا!",
	"signs_choose_c1": "لقد نفدت اللافتات لدينا تماماً! مهمتنا هي تسريع تبني البيتكوين من خلال التعليم.",
	"signs_choose_c2": "ساعد كثير منكم بوضع هذه اللافتات المجانية عن البيتكوين في الأماكن العامة. جميع لافتاتنا تحتوي على رموز QR تربط بصفحة تعليمية عن",
	"signs_choose_c3": "التضخم",
	"signs_choose_c4": "بفضل مجتمعنا الرائع، وصلنا لآلاف الأشخاص وساعدناهم في أخذ خطواتهم الأولى في عالم البيتكوين.",
	"signs_share_header": "شارك أماكن لافتاتك",
	"signs_share_c1": "شارك صورة لمكان لافتتك معنا على Nostr وشاهد أين يضع الآخرون لافتاتهم.",
	"signs_btn_share_on_nostr": "شارك على NOSTR",
	"signs_btn_what_is_nostr": "ما هو NOSTR؟",
	"signs_instructions_1": "أدخل عنوانك البريدي وسنرسل لك صندوقاً من 10 لافتات بيتكوين بالبريد!",
	"signs_instructions_2": "يتم حذف بيانات العنوان بعد شحن لافتاتك المجانية."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "منشورات بيتكوين مجانية من bitcoin.rocks",
	"flyers_description": "اطبع منشور بيتكوين في المنزل وضعه في مكان عام لتعريف من حولك بالبيتكوين.",
	"flyers_header_1": "اطبع وعلّق",
	"flyers_header_2": "منشورات البيتكوين",
	"flyers_intro_header": "كيف تطبع وتعلّق هذه المنشورات عن البيتكوين",
	"flyers_intro_c1": "مهمتنا هي مساعدتك في تعريف المزيد من الناس بالبيتكوين عن طريق وضع منشورات البيتكوين في الأماكن العامة. هذا المنشور يحتوي على رمز QR يربط بـ",
	"flyers_intro_c2": "موقعنا التعليمي عن البيتكوين.",
	"flyers_intro_c3": "التضخم",
	"flyers_intro_c4": "اطبع هذا المنشور في المنزل أو في مكتبة طباعة. ثم علّقه على لوحات الإعلانات وأعمدة الهاتف في المدينة والأماكن العامة الأخرى حيث يمكن للناس رؤيته والتعرف على البيتكوين.",
	"flyers_intro_c5": "بينما أنت في ذلك، اطلب حزمة من",
	"flyers_intro_c6": "ملصقات بيتكوين مجانية",
	"flyers_intro_c7": "لمساعدة المزيد من الناس على التعرف على البيتكوين.",
	"flyers_btn_download": "تنزيل المنشور",
	"flyers_btn_print": "طباعة المنشور",
	"flyers_share_header": "شارك أماكن منشوراتك",
	"flyers_share_c1": "شارك أماكن منشوراتك معنا على Nostr وشاهد أين يضع الآخرون منشوراتهم.",
	"flyers_btn_share_on_nostr": "شارك على NOSTR",
	"flyers_btn_what_is_nostr": "ما هو NOSTR؟"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "شارك وساعد في نشر البيتكوين",
	"get_involved_description": "مواردنا المجانية تسهّل نشر تبني البيتكوين.",
	"get_involved_header": "شارك",
	"get_involved_header_2": "انشر البيتكوين",
	"get_involved_intro_1": "قد يكون العيش في الوضع الحالي لعالمنا محبطاً.",
	"get_involved_intro_2": "نقودنا معطلة. ونتيجة لذلك، قطع أساسية من المجتمع معطلة أيضاً.",
	"get_involved_intro_3": "إذا كنت بالفعل مهتماً بالبيتكوين، فأنت تعرف شعور الأمل الذي يمكن أن يجلبه البيتكوين. أمل في مستقبل أكثر إشراقاً أصبح ممكناً بفضل نقود أفضل.",
	"get_involved_intro_4": "لكن كثير من الناس حولك لا يعرفون عن البيتكوين. إنهم يعيشون في نفس العالم المعطل مثلك، لكن بدون منارة أمل لمساعدتهم عبر الظلام.",
	"get_involved_intro_5": "لكن يمكنك المساعدة في تغيير ذلك. لقد صنعنا عدة موارد مجانية لتسهيل نشر الأمل الذي يجلبه البيتكوين لمن حولك.",
	"get_involved_sticker_header": "ضع ملصقاً في مكان عام",
	"get_involved_sticker_content_1": "يمكنك المساعدة في تعليم من حولك عن البيتكوين دون الحاجة للتفاعل مع أي شخص. ببساطة ضع أحد ملصقات البيتكوين المجانية في مكان عام.",
	"get_involved_sticker_content_2": "يقوم مئات الأشخاص بمسح رموز QR على هذه الملصقات كل شهر. ملصقات التضخم تربط بصفحة عن",
	"get_involved_sticker_content_3": "البيتكوين كحل للتضخم.",
	"get_involved_sticker_content_4": "الملصقات الأخرى تربط بصفحتنا الرئيسية التعليمية التي تُظهر للناس كيف",
	"get_involved_sticker_content_5": "يبني البيتكوين عالماً أفضل.",
	"get_involved_sticker_content_6": "بوضع هذه الملصقات في مجتمعك في أماكن يراها الناس، يمكنك مساعدة من حولك في أخذ خطواتهم الأولى في عالم البيتكوين.",
	"get_involved_request_a": "اطلب",
	"get_involved_sticker_pack": "حزمة ملصقات",
	"get_involved_postcard_header": "أرسل بطاقة بريدية",
	"get_involved_postcard_content_1": "يمكنك المساعدة في نشر أمل البيتكوين لشخص تعرفه عن طريق إرسال إحدى بطاقاتنا البريدية المجانية له.",
	"get_involved_postcard_content_2": "يحتوي ظهر كل بطاقة بريدية على فقرة مقنعة عن البيتكوين مع رمز QR لتعلم المزيد.",
	"get_involved_postcard_content_3": "بإرسال بطاقة بريدية عن البيتكوين لشخص ما، يمكنك مساعدته في رؤية البيتكوين بطريقة جديدة.",
	"get_involved_postcard_pack": "حزمة بطاقات بريدية",
	"get_involved_business_header": "أدخل عملاً تجارياً",
	"get_involved_business_content_1": "تريد المساعدة في بناء اقتصاد البيتكوين الدائري؟ حزمة أعمال البيتكوين الخاصة بنا تسهّل التعامل مع عمل تجاري حول قبول مدفوعات البيتكوين.",
	"get_involved_business_content_2": "تتضمن كل حزمة أعمال منشورات تسلط الضوء على مزايا قبول مدفوعات البيتكوين. كل منشور يربط بمجموعة متنوعة من",
	"get_involved_business_content_3": "موارد أعمال البيتكوين المجانية.",
	"get_involved_business_kit": "حزمة أعمال"
});

console.log('\nDone! Content files created for Arabic (ar).');
