/**
 * Creates Croatian (hr) translation files for content pages:
 * bank-runs, wallets, buy, lightning, stickers, postcards, signs, flyers, get-involved
 */

const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '..', '..', 'i18n');
const lang = 'hr';
const today = '2026-04-07';

const meta = {
	"@metadata": {
		"authors": ["Satoshi"],
		"last-updated": today,
		"locale": lang
	}
};

function writeFile(relPath, data) {
	const filePath = path.join(i18nDir, lang, relPath);
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, JSON.stringify({ ...meta, ...data }, null, '\t') + '\n', 'utf8');
	console.log(`CREATED: ${filePath}`);
}

// bank-runs
writeFile(`bank-runs_${lang}.json`, {
	"bitcoin_doesnt_have_bank_runs": "Bitcoin nema navale na banke",
	"bank_runs_header": "BITCOIN NEMA NAVALE NA BANKE",
	"bank_runs_header_2": "ALI VAŠA BANKA MOŽDA IMA",
	"bank_runs_what": "ŠTO JE NAVALA NA BANKU?",
	"bank_runs_what_content_1": "Navala na banku događa se kada previše ljudi pokušava podići svoj novac iz banke u isto vrijeme.",
	"bank_runs_what_content_2": "Ako banke nemaju dovoljno raspoloživog novca za pokriti podizanja, mogu potpuno propasti kada se navala dogodi.",
	"bank_runs_how": "KAKO SE NAVALE NA BANKE DOGAĐAJU?",
	"bank_runs_how_content_1": "Naš bankarski sustav je 'frakcijski rezervni' što znači da banke ne drže vaš novac u trezoru i čekaju da ga potrošite ili podignete.",
	"bank_runs_how_content_2": "Umjesto toga, vaša banka uzima vaš novac i posuđuje ga ili ulaže. To može zaključati vaš novac na duža razdoblja, iako vam banka obećava mogućnost podizanja novca u bilo kojem trenutku.",
	"bank_runs_how_content_3": "Dakle, što se događa ako pokušate podići svoj novac nakon što ga je banka već posudila ili uložila?",
	"bank_runs_how_content_4": "Nije problem ako ste jedini koji pokušava podići. Banka će jednostavno uzeti tuđi novac i dati ga vama. Ali što se događa kada previše ljudi pokušava podići u isto vrijeme?",
	"bank_runs_how_content_5": "Mnogi ljudi u SAD-u su to saznali kada je bila navala na Silicon Valley Bank u ožujku 2023.",
	"bank_runs_how_content_6": "Banka je uložila novac svojih klijenata u državne obveznice koje su bile zaključane do 30 godina. Još gore, vrijednost tih obveznica nedavno je dramatično pala, tako da Silicon Valley Bank nije mogla jednostavno prodati obveznice da dobije novac svojih štediša. Bili su insolventni. Nisu imali dovoljno novca za pokriti podizanja svojih štediša.",
	"bank_runs_how_content_7": "Kako je sve više ljudi saznalo, problem je samo postajao gori. Više zahtjeva za podizanje je pristizalo, ali mnogi nisu bili obrađeni. Tisuće tvrtki shvatile su da neće moći platiti svoje zaposlenike zbog propasti banke.",
	"bank_runs_how_content_8": "FDIC je intervenirao i pristao nadoknaditi štiše u cijelosti. Problem riješen? Ne baš...",
	"bank_runs_fdic": "ŠTITI LI FDIC OSIGURANJE MOJ NOVAC?",
	"bank_runs_fdic_content_1": "FDIC osiguranje dizajnirano je za zaštitu bankovnih štediša u slučaju propasti banke. Depoziti su osigurani do 250.000 dolara po štediši. Zvuči sjajno, zar ne?",
	"bank_runs_fdic_content_2": "Ne baš. Ako banka propadne, odakle FDIC dobiva novac? Imaju osiguravajući fond sa 125 milijardi dolara.",
	"bank_runs_fdic_content_3": "To zvuči kao puno novca dok to ne usporedite s iznosom depozita koje osiguravaju: gotovo 10 bilijuna ili 10.000 milijardi dolara.",
	"bank_runs_fdic_content_4": "FDIC čak pokazuje na svojoj web stranici da imaju dovoljno novca u svom osiguravajućem fondu za pokriti nešto malo više od 1% depozita.",
	"bank_runs_fdic_content_5": "U slučaju propasti banke koja bi premašila osiguravajući fond FDIC-a, vjerojatno (ali ne i zajamčeno) bi američka vlada tiskala novac kako bi nadoknadila štediše.",
	"bank_runs_fdic_content_6": "Ali tiskanje novca uzrokuje inflaciju, pa to nije sjajno rješenje.",
	"bank_runs_safe": "POSTOJE LI BANKE KOJE NE KORISTE FRAKCIJSKI REZERVNI SUSTAV?",
	"bank_runs_safe_content_1": "Neke banke su pokušale biti 'sigurne banke' koje ne posuđuju niti ulažu sredstva štediša.",
	"bank_runs_safe_content_2": "Iako te sigurne banke ne bi imale nikakav rizik od navala na banke, njihove prijave odbijene su od strane Federalnih rezervi. To znači da ne mogu legalno poslovati kao banke.",
	"bank_runs_safe_content_3": "Budući da im je onemogućeno poslovanje, danas ne postoje banke koje ne koriste frakcijski rezervni sustav.",
	"bank_runs_safe_content_4": "Srećom, postoji način da se isključite iz frakcijskog rezervnog sustava tako da budete svoja vlastita banka. Ne, ne govorimo o skrivanju gotovine pod madrac.",
	"bank_runs_safe_content_5": "Štednja u gotovini još uvijek je ranjiva na inflaciju.",
	"bank_runs_safe_content_6": "Govorimo o Bitcoinu: novom financijskom sustavu koji vam omogućuje da budete svoja vlastita banka.",
	"bank_runs_protect": "MOŽE LI ME BITCOIN ZAŠTITITI OD NAVALA NA BANKE?",
	"bank_runs_protect_content_1": "Da, Bitcoin je potpuno rezervni financijski sustav.",
	"bank_runs_protect_content_2": "Navale na banke nemoguće su u Bitcoinu sve dok povučete svoj Bitcoin u vlastiti novčanik. Ne ostavljajte svoj bitcoin na burzi ili u omotaču poput Bitcoin ETF-a.",
	"bank_runs_protect_content_3": "Pogledajte naš jednostavan vodič za Bitcoin novčanike da naučite kako povući u vlastiti novčanik.",
	"bank_runs_protect_content_4": "S Bitcoinom konačno možete imati kontrolu nad svojim novcem."
});

// wallets
writeFile(`wallets_${lang}.json`, {
	"bitcoin_wallet_guide": "Vodič za Bitcoin novčanike",
	"wallets_description": "Postoji mnogo različitih Bitcoin novčanika koji se razlikuju na važne načine. Možete odrediti je li novčanik pravi za vas postavljajući ova jednostavna pitanja.",
	"wallets_header": "KAKO SIGURNO POHRANITI SVOJ BITCOIN",
	"wallets_s1_c1": "Bitcoin novčanici su međusobno kompatibilni, tako da možete slati Bitcoin bilo kome bez obzira na to koji novčanik koriste.",
	"wallets_s1_c2": "Postoji mnogo različitih Bitcoin novčanika koji se razlikuju na važne načine. Možete odrediti je li novčanik pravi za vas postavljajući ova jednostavna pitanja:",
	"wallets_question_1": "JE LI TO NOVČANIK U SAMOSKRBNIŠTVU?",
	"wallets_s2_c1": "Jedna od inovacija Bitcoina je mogućnost pohrane bez oslanjanja na skrbnika, poput banke.",
	"wallets_s2_c2": "Ako držite bitcoin na burzi ili u ETF-u, gubite prednosti slobode koje bitcoin nudi.",
	"wallets_s2_c3": "Novčanici u samoskrbništvu otključavaju punu moć Bitcoina: novac slobode.",
	"wallets_s2_c4": "S novčanikom u samoskrbništvu, vi ste jedini s mogućnošću trošenja ili prijenosa svog novca. Nitko vas ne može spriječiti u slanju ili primanju novca kada koristite novčanik u samoskrbništvu.",
	"wallets_s2_c5": "Novčanici u samoskrbništvu također se nazivaju nekustodijalni novčanici.",
	"wallets_s3_c1": "Kustodijalni novčanici su novčanici u kojima nemate kontrolu nad svojim novcem.",
	"wallets_s3_c2": "Ti novčanici su sličniji bankarskom sustavu gdje morate vjerovati trećoj strani da vam daje pristup vašem novcu. Ako je vaš Bitcoin na burzi, koristite kustodijalni novčanik.",
	"wallets_s3_c3": "Ako ste kupili Bitcoin ETF, koristite kustodijalni novčanik koji vam ne dopušta povlačenje u samoskrbništvo.",
	"wallets_s3_c4": "Kustodijalni novčanici mogu djelovati praktično, ali skrbnik ima tehničku mogućnost krasti sva korisnička sredstva u bilo kojem trenutku.",
	"wallets_s3_c5": "Ne vaši ključevi, ne vaše kovanice!",
	"wallets_question_2": "JE LI VRUĆI ILI HLADNI?",
	"wallets_s4_c1": "Hladni novčanici pohranjuju ključeve vašeg Bitcoina na način koji ih nikada ne izlaže internetu.",
	"wallets_s4_c2": "To značajno ograničava vektore napada koje lopov može koristiti za krađu vašeg Bitcoina, i najbolje se koristi za velike svote Bitcoina koje ne trebate često prenositi.",
	"wallets_s4_c3": "Hladni novčanik možete zamisliti kao dugoročni štedni račun, također poznat kao hladna pohrana.",
	"wallets_s5_c1": "Vrući novčanici pohranjuju ključeve vašeg Bitcoina na uređaju spojenom na internet, poput vašeg telefona.",
	"wallets_s5_c2": "Vrući novčanici se općenito smatraju sigurnima, ali mogu imati više sigurnosnih ranjivosti od hladnih novčanika.",
	"wallets_s5_c3": "Vrući novčanik možete zamisliti kao fizički novčanik. Ne biste pohranili cijelu ušteđevinu u novčaniku, ali biste pohranili nešto novca za potrošnju.",
	"wallets_s5_c4": "Vrući novčanici znatno olakšavaju trošenje Bitcoina bez izvlačenja cijele ušteđevine iz hladne pohrane.",
	"wallets_question_3": "KAKO ĆU SIGURNOSNO KOPIRATI SVOJU FRAZU ZA OPORAVAK?",
	"wallets_s6_c1": "Kada postavite svoj Bitcoin novčanik, vaš uređaj će generirati frazu za oporavak. Ova fraza za oporavak (također nazvana seed fraza) sadrži 12 ili 24 riječi.",
	"wallets_s6_c2": "Ako ikada izgubite pristup svom novčaniku ili vaš uređaj prestane raditi, možete unijeti ovu frazu za oporavak u novi novčanik kako biste ponovno dobili pristup svom Bitcoinu.",
	"wallets_s6_c3": "Većina novčanika uključuje list papira za zapisivanje fraze za oporavak, ali mnogi ljudi preferiraju sigurnosnu kopiju ove fraze na čeliku. To znatno smanjuje mogućnost gubitka fraze za oporavak u slučaju prirodne katastrofe poput požara ili poplave.",
	"wallets_s6_c4": "Jameson Lopp je testirao 70 čeličnih sigurnosnih kompleta kako bi vam pomogao odabrati pravi za vas.",
	"wallets_s6_c5": "Pogledajte Jamesonov vodič za metalnu sigurnosnu kopiju Bitcoina ovdje.",
	"wallets_s6_c6": "Ili nastavite listati da istražite opcije Bitcoin novčanika.",
	"wallets_blockstream_green": "BLOCKSTREAM GREEN",
	"wallets_coldcard_mk5": "COLDCARD MK5",
	"wallets_coldcard_q": "COLDCARD Q",
	"wallets_blockstream_jade": "BLOCKSTREAM JADE",
	"wallets_foundation_passport": "FOUNDATION PASSPORT",
	"wallets_seedsigner": "SEEDSIGNER",
	"wallets_cta_lightning": "Tražite naš vodič za Lightning novčanike?",
	"wallets_starter_wallet": "Sjajan početni novčanik",
	"wallets_mobile_app": "Mobilna aplikacija",
	"wallets_2fa_support": "Podrška za 2FA",
	"wallets_air_gap_mode": "Air-gap način rada",
	"wallets_air_gap_camera": "Air-gap način rada + kamera",
	"wallets_bitcoin_only": "Samo Bitcoin",
	"wallets_security_features": "Mnogo sigurnosnih značajki",
	"wallets_free": "100% besplatan",
	"wallets_coldcard_mk5_costs": "Košta 189 $",
	"wallets_coldcard_q_costs": "Košta 289 $",
	"wallets_blockstream_jade_costs": "Košta 79 $",
	"wallets_foundation_passport_costs": "Košta 199 $",
	"wallets_seedsigner_costs": "Dijelovi koštaju 50 $",
	"wallets_very_affordable": "Vrlo pristupačan",
	"wallets_pair_with_phone": "Uparite s telefonom",
	"wallets_battery": "Punjiva baterija",
	"wallets_build_your_own": "Sastavite vlastiti",
	"wallets_qwerty_keyboard": "Puna QWERTY tipkovnica",
	"wallets_qr_scanner": "Čitač QR kodova"
});

// buy
writeFile(`buy_${lang}.json`, {
	"buy_bitcoin_guide": "Kako kupiti Bitcoin - Vodič korak po korak",
	"buy_header": "KAKO KUPITI BITCOIN",
	"buy_intro_c1": "Kupovina Bitcoina prvi put može djelovati zastrašujuće, ali zapravo je prilično jednostavna kada je rastavite na korake.",
	"buy_intro_c2": "Ovaj vodič će vas provesti kroz proces sigurne kupovine Bitcoina i pohrane u vlastitom novčaniku.",
	"buy_step_1_header": "KORAK 1: ODABERITE SVOJU ZEMLJU",
	"buy_step_1_description": "Različite zemlje imaju različite mogućnosti kupovine Bitcoina. Odaberite svoju zemlju da vidite najbolje opcije za vas.",
	"buy_search_countries": "Pretražite svoju zemlju",
	"buy_country_united_states": "Sjedinjene Američke Države",
	"buy_country_australia": "Australija",
	"buy_country_austria": "Austrija",
	"buy_country_belgium": "Belgija",
	"buy_country_brazil": "Brazil",
	"buy_country_canada": "Kanada",
	"buy_country_france": "Francuska",
	"buy_country_germany": "Njemačka",
	"buy_country_ireland": "Irska",
	"buy_country_italy": "Italija",
	"buy_country_netherlands": "Nizozemska",
	"buy_country_new_zealand": "Novi Zeland",
	"buy_country_spain": "Španjolska",
	"buy_country_united_kingdom": "Ujedinjeno Kraljevstvo",
	"buy_country_argentina": "Argentina",
	"buy_country_chile": "Čile",
	"buy_country_colombia": "Kolumbija",
	"buy_country_costa_rica": "Kostarika",
	"buy_country_czech_republic": "Češka",
	"buy_country_denmark": "Danska",
	"buy_country_el_salvador": "El Salvador",
	"buy_country_estonia": "Estonija",
	"buy_country_finland": "Finska",
	"buy_country_greece": "Grčka",
	"buy_country_guatemala": "Gvatemala",
	"buy_country_hong_kong": "Hong Kong",
	"buy_country_hungary": "Mađarska",
	"buy_country_iceland": "Island",
	"buy_country_india": "Indija",
	"buy_country_israel": "Izrael",
	"buy_country_japan": "Japan",
	"buy_country_latvia": "Latvija",
	"buy_country_lithuania": "Litva",
	"buy_country_luxembourg": "Luksemburg",
	"buy_country_malta": "Malta",
	"buy_country_mexico": "Meksiko",
	"buy_country_norway": "Norveška",
	"buy_country_panama": "Panama",
	"buy_country_poland": "Poljska",
	"buy_country_portugal": "Portugal",
	"buy_country_romania": "Rumunjska",
	"buy_country_singapore": "Singapur",
	"buy_country_slovakia": "Slovačka",
	"buy_country_slovenia": "Slovenija",
	"buy_country_south_africa": "Južnoafrička Republika",
	"buy_country_south_korea": "Južna Koreja",
	"buy_country_sweden": "Švedska",
	"buy_country_switzerland": "Švicarska",
	"buy_country_thailand": "Tajland",
	"buy_country_turkey": "Turska",
	"buy_country_ukraine": "Ukrajina",
	"buy_country_uruguay": "Urugvaj",
	"buy_step_2_header": "KORAK 2: ODABERITE NAČIN PLAĆANJA",
	"buy_step_2_description": "Postoje dva glavna načina kupovine Bitcoina: bankovnim prijenosom ili gotovinom. Svaki ima različite prednosti.",
	"buy_method_bank_transfer": "BANKOVNI PRIJENOS",
	"buy_method_bank_fast": "Brzo i jednostavno",
	"buy_method_bank_less_private": "Manje privatno",
	"buy_method_bank_description": "Bankovni prijenosi su najčešći način kupovine Bitcoina. Brzi su, praktični i obično imaju niže naknade.",
	"buy_method_choose_bank": "Odaberite bankovni prijenos",
	"buy_method_cash": "GOTOVINA",
	"buy_method_cash_private": "Privatnije",
	"buy_method_cash_limited": "Ograničene opcije",
	"buy_method_cash_description": "Kupovina gotovinom nudi više privatnosti, ali ima manje opcija i može zahtijevati osobni susret ili korištenje Bitcoin bankomata.",
	"buy_method_choose_cash": "Odaberite gotovinu",
	"buy_step_3_header": "KORAK 3: OPCIJE KUPOVINE",
	"buy_step_3_description": "Evo najboljih opcija za kupovinu Bitcoina za vašu zemlju i način plaćanja:",
	"buy_platform_recommended": "PREPORUČENO",
	"buy_platform_strike_description": "Strike je najbrži i najlakši način kupovine Bitcoina s niskim naknadama i trenutnom podrškom Lightning Networka.",
	"buy_platform_swan_description": "Swan Bitcoin specijaliziran je za usluge isključivo vezane uz Bitcoin s prosjekom troška u dolarima i edukativnim resursima.",
	"buy_platform_river_description": "River nudi kupovinu Bitcoina, rudarenje i usluge skrbništva s fokusom na edukaciju i sigurnost.",
	"buy_platform_coinsquare_description": "Coinsquare je kanadska Bitcoin burza s jakom regulatornom usklađenošću i korisničkom podrškom.",
	"buy_platform_kraken_description": "Kraken je etablirana Bitcoin burza s naprednim značajkama trgovanja i jakom sigurnošću.",
	"buy_platform_atm_description": "Bitcoin bankomati omogućuju trenutnu kupovinu Bitcoina gotovinom. Pronađite najbliži pomoću Coin ATM Radara.",
	"buy_platform_bisq_description": "Bisq je decentralizirana peer-to-peer burza koja omogućuje privatno trgovanje Bitcoinom bez KYC-a.",
	"buy_platform_feature_instant": "Trenutna kupovina",
	"buy_platform_feature_low_fees": "Niske naknade",
	"buy_platform_feature_lightning": "Lightning Network",
	"buy_platform_feature_dca": "Prosjek troška u dolarima",
	"buy_platform_feature_education": "Edukativni resursi",
	"buy_platform_feature_withdrawal": "Jednostavno povlačenje",
	"buy_platform_feature_mining": "Rudarenje Bitcoina",
	"buy_platform_feature_custody": "Usluge skrbništva",
	"buy_platform_feature_canadian": "Fokus na Kanadu",
	"buy_platform_feature_regulated": "Regulirana burza",
	"buy_platform_feature_support": "Korisnička podrška",
	"buy_platform_feature_established": "Etablirana platforma",
	"buy_platform_feature_security": "Jaka sigurnost",
	"buy_platform_feature_advanced": "Napredne značajke",
	"buy_platform_feature_cash": "Kupovina gotovinom",
	"buy_platform_feature_anonymous": "Više anonimno",
	"buy_platform_feature_p2p": "Peer-to-peer",
	"buy_platform_feature_private": "Privatno trgovanje",
	"buy_platform_feature_decentralized": "Decentralizirano",
	"buy_platform_relai_description": "Relai je švicarska aplikacija samo za Bitcoin s novčanikom u samoskrbništvu, značajkama automatskog ulaganja i niskim naknadama za europske korisnike.",
	"buy_platform_feature_bitcoin_only": "Samo Bitcoin",
	"buy_platform_feature_self_custody": "Novčanik u samoskrbništvu",
	"buy_platform_feature_auto_invest": "Planovi automatskog ulaganja",
	"buy_platform_feature_european": "Fokus na Europu",
	"buy_step_4_header": "KORAK 4: SIGURNO POHRANITE SVOJ BITCOIN",
	"buy_step_4_c1": "Nakon kupovine Bitcoina, najvažniji korak je premjestiti ga u vlastiti novčanik gdje kontrolirate privatne ključeve.",
	"buy_step_4_c2": "Ostavljanje Bitcoina na burzi je rizično jer zapravo ne posjedujete Bitcoin - burza ga posjeduje.",
	"buy_step_4_c3": "Kada kontrolirate vlastite privatne ključeve, imate istinsko vlasništvo nad svojim Bitcoinom i nitko vam ga ne može oduzeti.",
	"buy_step_4_c4": "Saznajte kako odabrati pravi Bitcoin novčanik za vaše potrebe:",
	"buy_cta_wallets": "Pogledajte naš vodič za Bitcoin novčanike"
});

// lightning
writeFile(`lightning_${lang}.json`, {
	"bitcoin_lightning_wallet_guide": "Vodič za Bitcoin Lightning novčanike",
	"lightning_description": "Lightning novčanici vam omogućuju brzo i jeftino slanje Bitcoina uz očuvanje vaše osobne suverenosti.",
	"lightning_header": "VODIČ ZA LIGHTNING NOVČANIKE",
	"lightning_s1_c1": "Lightning vam omogućuje brzo i jeftino slanje Bitcoin plaćanja.",
	"lightning_s1_c2": "Važno je znati da korištenje Lightninga dolazi s kompromisima. U zamjenu za brža, jeftinija Bitcoin plaćanja, često žrtvujete nešto sigurnosti.",
	"lightning_s1_c3": "Općenito, Lightning bi se trebao koristiti samo s malim iznosima bitcoina. Velike iznose bitcoina trebali biste uvijek pohranjivati samo u hardverski novčanik.",
	"lightning_s1_c4": "Pogledajte naš vodič za hardverske novčanike za više informacija.",
	"lightning_s1_c5": "Nisu svi Lightning novčanici isti. Možete odrediti koji novčanik ima pravu ravnotežu kompromisa za vas postavljanjem jednog jednostavnog pitanja:",
	"lightning_question_1": "KOJA RAVNOTEŽA KOMPROMISA JE PRAVA ZA MENE?",
	"lightning_s2_c1": "Jedna od inovacija Bitcoina je mogućnost pohrane bez oslanjanja na skrbnika, poput banke. Novčanici u samoskrbništvu otključavaju punu moć Bitcoina.",
	"lightning_s2_c2": "S novčanikom u samoskrbništvu, vi ste jedini s mogućnošću trošenja ili prijenosa svog novca. Nitko vas ne može spriječiti, cenzurirati ili krasti od vas kada koristite novčanik u samoskrbništvu. Ovi se također nazivaju nekustodijalni novčanici.",
	"lightning_s2_c3": "Najsuvereniji način korištenja Lightninga je pokretanje vlastitog čvora.",
	"lightning_s2_c4": "Ovaj vodič fokusiran je na jednostavne Lightning novčanike koji ne zahtijevaju vlastiti čvor.",
	"lightning_s2_c5": "Važno je znati da čak i korištenjem nekustodijalnog Lightning novčanika, još uvijek vjerujete tvorcu novčanika da neće objaviti zlonamjerno ažuriranje aplikacije i ukrasti vaša sredstva.",
	"lightning_s3_c1": "Kustodijalni novčanici su novčanici u kojima nemate kontrolu nad svojim novcem.",
	"lightning_s3_c2": "Ti novčanici su sličniji bankarskom sustavu gdje morate vjerovati trećoj strani da vam daje pristup vašem novcu. Ako je vaš Bitcoin na burzi, koristite kustodijalni novčanik.",
	"lightning_s3_c3": "Kustodijalni novčanici mogu djelovati praktično, ali skrbnik ima tehničku mogućnost krasti sva korisnička sredstva u bilo kojem trenutku.",
	"lightning_s3_c4": "Neki ljudi preferiraju kustodijalne Lightning novčanike za male iznose bitcoina zbog njihove jednostavnosti korištenja. Samo zapamtite: ne vaši ključevi, ne vaše kovanice!",
	"lightning_question_2": "ODABERITE SVOJ NOVČANIK",
	"lightning_s4_c1": "Imajući sve ovo na umu, sada možete odabrati lightning novčanik koji ima pravu ravnotežu kompromisa za vas.",
	"phoenix": "PHOENIX",
	"breez": "BREEZ",
	"mutiny_wallet": "MUTINY WALLET",
	"wallet_of_satoshi": "WALLET OF SATOSHI",
	"lightning_features": "Mnogo značajki",
	"lightning_mobile_app": "Mobilna aplikacija",
	"lightning_free": "100% besplatan",
	"lightning_merchants": "Sjajan za trgovce",
	"lightning_starter": "Sjajan početni novčanik",
	"lightning_browser": "Baziran na pregledniku",
	"lightning_custodial": "Potpuno kustodijalni novčanik",
	"lightning_cta_hardware": "Tražite naš vodič za Bitcoin hardverske novčanike?"
});

// stickers
writeFile(`stickers_${lang}.json`, {
	"free_bitcoin_stickers": "Besplatne Bitcoin naljepnice od bitcoin.rocks",
	"stickers_description": "Stavite Bitcoin naljepnicu na javno mjesto da upoznate ljude oko sebe s Bitcoinom.",
	"stickers_header": "BESPLATNE BITCOIN NALJEPNICE",
	"stickers_choose_header": "ODABERITE SVOJ PAKET NALJEPNICA",
	"stickers_choose_c1": "Naša misija je pomoći vam da više ljudi upoznate s Bitcoinom stavljanjem Bitcoin naljepnica na javna mjesta. Sve naše naljepnice imaju QR kodove koji vode na edukativne stranice o",
	"stickers_choose_c2": "Bitcoinu",
	"stickers_choose_c3": "inflaciji",
	"stickers_choose_c4": "Odaberite svoj paket naljepnica ispod",
	"stickers_text_pack": "TEKSTUALNI PAKET",
	"stickers_signs_pack": "PAKET ZNAKOVA",
	"stickers_instructions_1": "Unesite svoju poštansku adresu i poslat ćemo vam besplatni paket Bitcoin naljepnica poštom! Vaše naljepnice bit će isporučene u običnoj bijeloj omotnici.",
	"stickers_instructions_2": "Podaci o adresi brišu se nakon slanja besplatnih naljepnica.",
	"stickers_share_header": "PODIJELITE SVOJA MJESTA S NALJEPNICAMA",
	"stickers_share_c1": "Podijelite svoja mjesta s naljepnicama s nama na Nostru i pogledajte gdje drugi ljudi stavljaju svoje naljepnice.",
	"stickers_btn_share_on_nostr": "PODIJELI NA NOSTRU",
	"stickers_btn_what_is_nostr": "ŠTO JE NOSTR?",
	"stickers_flyers_link_before": "Dok ste već tu, ispišite i zalijepite vlastite ",
	"stickers_flyers_link_text": "Bitcoin letke",
	"stickers_flyers_link_after": " kako biste pomogli upoznati još više ljudi s Bitcoinom.",
	"stickers_country_global_print": "Globalno — Ispisat ću vlastite naljepnice",
	"stickers_country_global_order": "Globalno — Naruči u velikim količinama",
	"placeholder_name_optional": "Ime (neobavezno)",
	"placeholder_address_line_1": "Adresni red 1",
	"placeholder_address_line_2": "Adresni red 2 (neobavezno)",
	"placeholder_city": "Grad",
	"placeholder_state": "Država",
	"placeholder_province": "Pokrajina",
	"placeholder_zip_code": "Poštanski broj",
	"placeholder_postal_code": "Poštanski broj",
	"placeholder_language": "Jezik",
	"placeholder_which_stickers": "Koje naljepnice?",
	"placeholder_email_optional": "Unesite e-mail za obavijest (neobavezno)"
});

// postcards
writeFile(`postcards_${lang}.json`, {
	"free_bitcoin_postcards": "Besplatne Bitcoin razglednice od bitcoin.rocks",
	"postcards_description": "Nabavite besplatni paket Bitcoin razglednica i podijelite Bitcoin s nekim koga poznajete.",
	"postcards_header": "PROGRAM RAZGLEDNICA ZATVOREN",
	"postcards_program_closed_message": "Naš besplatni program Bitcoin razglednica je završio. Hvala svima koji su sudjelovali u širenju Bitcoin edukacije putem pošte!",
	"postcards_sticker_alternative_header": "UMJESTO TOGA NABAVITE BESPLATNE BITCOIN NALJEPNICE",
	"postcards_sticker_alternative_message": "Nastavite širiti svijest o Bitcoinu s našim besplatnim programom naljepnica! Naše Bitcoin naljepnice savršene su za dijeljenje na javnim mjestima i dolaze s QR kodovima koji vode na edukativni sadržaj.",
	"postcards_sticker_cta": "NABAVITE BESPLATNE NALJEPNICE",
	"postcards_step_2": "KAKO SU RAZGLEDNICE IZGLEDALE",
	"postcards_instructions_4": "Napravili smo ove razglednice da vam olakšamo predstavljanje Bitcoina nekome koga poznajete! Samo dodajte adresu i marku i ubacite razglednicu u poštu.",
	"postcards_instructions_5": "Naša misija je ubrzati usvajanje Bitcoina. Možete pomoći nabavljajući besplatne naljepnice i stavljajući ih na javna mjesta!",
	"postcards_instructions_6": "Svi poznajemo nekoliko ljudi kojima bi koristilo da nauče više o Bitcoinu. Podijelite Bitcoin naljepnice s njima već danas!"
});

// signs
writeFile(`signs_${lang}.json`, {
	"signs_description": "Pomozite nam postaviti ove Bitcoin znakove diljem Amerike!",
	"signs_title": "Besplatni Bitcoin znakovi od bitcoin.rocks",
	"signs_choose_header": "HVALA ŠTO STE NAM POMOGLI POSTAVITI OVE BITCOIN ZNAKOVE DILJEM AMERIKE!",
	"signs_choose_c1": "Sada smo potpuno ostali bez znakova! Naša misija je ubrzati usvajanje Bitcoina kroz edukaciju.",
	"signs_choose_c2": "Mnogi od vas pomogli su postavljanjem ovih besplatnih Bitcoin znakova na javna mjesta. Svi naši znakovi imaju QR kodove koji vode na edukativnu stranicu o",
	"signs_choose_c3": "inflaciji",
	"signs_choose_c4": "Zahvaljujući našoj nevjerojatnoj zajednici, dosegnuli smo tisuće ljudi i pomogli im napraviti prve korake u Bitcoin zečju rupu.",
	"signs_share_header": "PODIJELITE SVOJA MJESTA SA ZNAKOVIMA",
	"signs_share_c1": "Podijelite fotografiju svog mjesta sa znakom s nama na Nostru i pogledajte gdje drugi ljudi postavljaju svoje znakove.",
	"signs_btn_share_on_nostr": "PODIJELI NA NOSTRU",
	"signs_btn_what_is_nostr": "ŠTO JE NOSTR?",
	"signs_instructions_1": "Unesite svoju poštansku adresu i poslat ćemo vam kutiju s 10 Bitcoin znakova poštom!",
	"signs_instructions_2": "Podaci o adresi brišu se nakon slanja besplatnih znakova."
});

// flyers
writeFile(`flyers_${lang}.json`, {
	"free_bitcoin_flyers": "Besplatni Bitcoin letci od bitcoin.rocks",
	"flyers_description": "Ispišite Bitcoin letak kod kuće i stavite ga na javno mjesto da upoznate ljude oko sebe s Bitcoinom.",
	"flyers_header_1": "ISPIŠITE I ZALIJEPITE",
	"flyers_header_2": "BITCOIN LETKE",
	"flyers_intro_header": "KAKO ISPISATI I ZALIJEPITI OVE BITCOIN LETKE",
	"flyers_intro_c1": "Naša misija je pomoći vam da više ljudi upoznate s Bitcoinom stavljanjem Bitcoin letaka na javna mjesta. Ovaj letak ima QR kod koji vodi na našu",
	"flyers_intro_c2": "edukativnu Bitcoin web stranicu.",
	"flyers_intro_c3": "inflaciju",
	"flyers_intro_c4": "Ispišite ovaj letak kod kuće ili u kopirnici. Zatim ga zalijepite na oglasne ploče, telefonske stupove po gradu i druga javna mjesta gdje ga ljudi mogu vidjeti i naučiti o Bitcoinu.",
	"flyers_intro_c5": "Dok ste već tu, zatražite paket naših",
	"flyers_intro_c6": "besplatnih Bitcoin naljepnica",
	"flyers_intro_c7": "kako biste pomogli upoznati još više ljudi s Bitcoinom.",
	"flyers_btn_download": "PREUZMI LETAK",
	"flyers_btn_print": "ISPIŠI LETAK",
	"flyers_share_header": "PODIJELITE SVOJA MJESTA S LETCIMA",
	"flyers_share_c1": "Podijelite svoja mjesta s letcima s nama na Nostru i pogledajte gdje drugi ljudi stavljaju svoje letke.",
	"flyers_btn_share_on_nostr": "PODIJELI NA NOSTRU",
	"flyers_btn_what_is_nostr": "ŠTO JE NOSTR?"
});

// get-involved
writeFile(`get-involved_${lang}.json`, {
	"get_involved_and_help_spread_bitcoin": "Uključite se i pomozite širiti Bitcoin",
	"get_involved_description": "Naši besplatni resursi olakšavaju širenje usvajanja Bitcoina.",
	"get_involved_header": "UKLJUČITE SE",
	"get_involved_header_2": "ŠIRITE BITCOIN",
	"get_involved_intro_1": "Može biti depresivno živjeti u trenutnom stanju našeg svijeta.",
	"get_involved_intro_2": "Naš novac je pokvaren. Kao rezultat toga, temeljni dijelovi društva su također pokvareni.",
	"get_involved_intro_3": "Ako ste već u Bitcoinu, znate osjećaj nade koji Bitcoin može donijeti. Nada za svjetliju budućnost koju omogućuje bolji novac.",
	"get_involved_intro_4": "Ali toliko mnogo ljudi oko vas ne zna za Bitcoin. Žive u istom pokvarenom svijetu kao i vi, ali bez zrake nade koja bi im pomogla kroz tamu.",
	"get_involved_intro_5": "Ali vi to možete promijeniti. Napravili smo nekoliko besplatnih resursa kako bismo olakšali širenje nade koju Bitcoin donosi ljudima oko vas.",
	"get_involved_sticker_header": "Stavite naljepnicu na javno mjesto",
	"get_involved_sticker_content_1": "Možete pomoći educirati ljude oko sebe o Bitcoinu bez potrebe za interakcijom s ikime. Jednostavno stavite jednu od naših besplatnih Bitcoin naljepnica na javno mjesto.",
	"get_involved_sticker_content_2": "Stotine ljudi skenira QR kodove na tim naljepnicama svaki mjesec. Naljepnice o inflaciji vode na stranicu o",
	"get_involved_sticker_content_3": "Bitcoinu kao rješenju za inflaciju.",
	"get_involved_sticker_content_4": "Ostale naljepnice vode na našu edukativnu početnu stranicu koja ljudima pokazuje kako",
	"get_involved_sticker_content_5": "Bitcoin gradi bolji svijet.",
	"get_involved_sticker_content_6": "Stavljajući ove naljepnice u vašoj zajednici na mjesta gdje će ih ljudi vidjeti, možete pomoći onima oko vas da naprave prve korake u Bitcoin zečju rupu.",
	"get_involved_request_a": "ZATRAŽITE",
	"get_involved_sticker_pack": "PAKET NALJEPNICA",
	"get_involved_postcard_header": "Pošaljite razglednicu",
	"get_involved_postcard_content_1": "Možete pomoći širiti nadu Bitcoina nekome koga poznajete slanjem jedne od naših besplatnih razglednica.",
	"get_involved_postcard_content_2": "Poleđina svake razglednice sadrži uvjerljiv tekst o Bitcoinu zajedno s QR kodom za saznati više.",
	"get_involved_postcard_content_3": "Slanjem nekome Bitcoin razglednice, možete im pomoći da Bitcoin sagledaju na novi način.",
	"get_involved_postcard_pack": "PAKET RAZGLEDNICA",
	"get_involved_business_header": "Uvedite tvrtku",
	"get_involved_business_content_1": "Želite pomoći izgraditi Bitcoin kružnu ekonomiju? Naš Bitcoin poslovni paket olakšava pristupanje tvrtki o prihvaćanju Bitcoin plaćanja.",
	"get_involved_business_content_2": "Svaki poslovni paket uključuje letke koji ističu prednosti prihvaćanja Bitcoin plaćanja. Svaki letak vodi na razne",
	"get_involved_business_content_3": "besplatne Bitcoin poslovne resurse.",
	"get_involved_business_kit": "POSLOVNI PAKET"
});

console.log(`\nDone! Created 9 content files.`);
