[phases.setup]
nixPkgs = ["nodejs_18", "python3"]

[phases.install]
cmds = ["cd forms-backend && npm install"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "cd forms-backend && node seed.js && node server.js"
